### ISSUE TITLE
Issue Installing/Initilializing Flowise/ TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by paragonsean** [FlowiseAI/Flowise#1003]
I have setup flowise on both my local machine using both yarn and npm.. I also installed it on render https://flowise-037q.onrender.com/ feel free to access the instance to help me figure out what is going on. when i use the local chat feature it gives me TypeError: Cannot read properties of undefined (reading 'split').. when I try to use python it gives me a "Traceback (most recent call last):
  File "C:\Users\spocam\test.py", line 9, in <module>
    output = query({
  File "C:\Users\spocam\test.py", line 7, in query
    return response.json()
  File "C:\Users\spocam\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)" .. What am I doing wrong?

**Comment by HenryHengZJ** [comment]
you need to upload a file:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/fced2e5f-6035-421c-ba8d-9e4a235e8c67)
