### ISSUE TITLE
[FEATURE] SEMANTIC SEARCH

### ISSUE THREAD

**Issue by MrBrabus75** [FlowiseAI/Flowise#1006]
Hello,

I would like to know if this is feasible or if I am dreaming.
Is it possible with OpenAI embedding to insert a large number of documents (CIS BENCHMARK, Redmine Project, GLPI ticket, etc.) of different types (json, pdf, txt, etc.) into a vector database?

Subsequently, with OpenAIGPT, when I ask a question, will it conduct a semantic search or search by similarity or score to find the most relevant elements to assist in answering me?

If yes, could I get some advice?

Thank you in advance.

**Comment by HenryHengZJ** [comment]
yep, have a look at templates to see what is possible:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/8dfd6df2-1fb3-4f97-83e6-0e2966817ae2)
