### ISSUE TITLE
[FEATURE] get traceid of langfuse as a response object 

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [FlowiseAI/Flowise#1007]
**Describe the feature you'd like**
A clear and concise description of what you would like Flowise to have.

right now we only get prompt output as a response .

I need the traceid of langfuse as a response object with prompt output so that users have more control over the implementation of langfuse scores() and other langfuse features."

**Additional context**

**Comment by HenryHengZJ** [comment]
can you point us to langfuse docs for that? currently we just pass in langfuse callbacks into chains/agents, and the response we get back from langchain doesnt have the traceid

**Comment by DIWAKARKASHYAP** [comment]
sure
https://langfuse.com/docs/integrations/sdk/typescript 
this is in node js , document is also available in python

**Comment by giorgosera** [comment]
I am interested in this too. 

Now it is a bit of a pain to work with Flowise <> Langfuse. Specifically, the lack of access to traceId as mentioned here in the response causes downstream issues. 

For example, in our case we'd like to track user feedback on an LLM response (thumbs up/down) and associate it with a specific traceId. 

Now we resort to hacks and run into timing issues. It'd be extremely helpful to get back the `traceId`. Or at least allow us to pass `metadata` in Langfuse so we can do our own matching. I opened anothet relevant ticket [here](https://github.com/FlowiseAI/Flowise/discussions/1648).

**Comment by HenryHengZJ** [comment]
@giorgosera [PR](https://github.com/FlowiseAI/Flowise/pull/2055) merged. Its now working. See [discussion](https://github.com/FlowiseAI/Flowise/discussions/1648#discussioncomment-8958090)
