### ISSUE TITLE
[FEATURE] OpenSearch on Flowise and it's authorization for HTTP API

### ISSUE THREAD

**Issue by freemjstudio** [FlowiseAI/Flowise#1008]
Hi I'm trying to use OpenSearch on flowise but I have no idea to give master user id & password for authorization
Where can I input master user id & password of OpenSearch on Flowise ?

**Comment by HenryHengZJ** [comment]
its not possible yet on Flowise, we'll need to add that functionality similar to Chroma auth [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/vectorstores/Chroma/Chroma_Upsert.ts#L31), welcoming any PR

**Comment by freemjstudio** [comment]
Okay I will check the code of OpenSearch plug-in 
Thank you for the answer !
