### ISSUE TITLE
[FEATURE] Rate limit message should be displayed in chat windows.

### ISSUE THREAD

**Issue by mazouz01** [FlowiseAI/Flowise#1016]
Actually, the message is displayed in the console with error code 429; without showing the cause, it would be better to display the message in the chat window.

**Comment by HenryHengZJ** [comment]
its's showing the message:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/5c36cc4d-ec00-4147-849f-8b1fa0953003)

can you try using the latest embed version `1.0.13`

**Comment by mazouz01** [comment]
With the last version of chat Embed I get the error:
![image](https://github.com/FlowiseAI/Flowise/assets/33160504/309c7a3d-8a61-4641-a23d-f63a98b8d823)

**Comment by HenryHengZJ** [comment]
you may have to sync your forked embedded repo for the latest updated changes. feel free to reopen if issue persits!
