### ISSUE TITLE
[FEATURE] Support JSON Schema

### ISSUE THREAD

**Issue by biandayu** [FlowiseAI/Flowise#1032]
When an application calls Flowise through the API, it hopes that the returned result is a fixed-format, accurate Json result. To do this, we need to make Json Schema a part of the prompt, just as the TypeChat project does. Currently, Flowise's prompt template already uses a single { } to represent variables, which conflicts with Json Schema, and Format Prompt Values is not enough to express complex Json formats, such as when the value is an object or an enum. Can I use {{ }} to represent variables instead?

**Comment by biandayu** [comment]
It would be even better if there was a Prompt Template that specifically supports JSON Schema!

[https://github.com/microsoft/TypeChat](url)

**Comment by HenryHengZJ** [comment]
think its also somewhat related to this issue here - https://github.com/FlowiseAI/Flowise/issues/968, for now you can encode the json
