### ISSUE TITLE
Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client[BUG]

### ISSUE THREAD

**Issue by quickshipIT** [FlowiseAI/Flowise#1038]
Hi Guys
i'm trying to use SQL DB Chain 
database connected successfully.
i'm trying to query then this error message arrive.

![image](https://github.com/FlowiseAI/Flowise/assets/115209477/4d22624e-9915-43ea-8094-03874f049cde)

**Comment by HenryHengZJ** [comment]
@chungyau97
