### ISSUE TITLE
[FEATURE] Integration with Ollama

### ISSUE THREAD

**Issue by giacomorebonato** [FlowiseAI/Flowise#1052]
**Describe the feature you'd like**

[Ollama](https://ollama.ai) is an LLM that is very easy to run on both Mac and Linux and it doesn't have the same API of OpenAI/LocalAI.
It would be nice to have support for it in Flowise

**Additional context**

Is there already support for it by any chance and I only can't find it?

**Comment by HenryHengZJ** [comment]
Its available in latest version v1.3.8
