### ISSUE TITLE
[FEATURE] Cache Embeddings

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#1061]
**Describe the feature you'd like**
Implement cache for embeddings similar to LLM Cache where users are able to connect throught the flow.

**Additional context**
Docs - https://js.langchain.com/docs/modules/data_connection/text_embedding/how_to/caching_embeddings

**Comment by HenryHengZJ** [comment]
@vinodkiran

**Comment by vinodkiran** [comment]
@HenryHengZJ 

Here are some high-level thoughts for this implementation

Node Category: Cache (same as LLM cache)
Node: Redis Embeddings Cache (nodes/cache/RedisCache/RedisEmbeddingCache.ts), 
      Input  -> Embedding; 
      Input  -> Namespace (string)
      Output -> Embedding 

Typical flow would be OpenAI Embedding (input) RedisEmbeddingCache (output) Open AI LLM (or chat)

**Comment by vinodkiran** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/842544/a4aecb0a-a77a-4db6-9809-b3c5d3fa0702)

![image](https://github.com/FlowiseAI/Flowise/assets/842544/c5fe8faf-cda7-4393-a187-33ef2b1c0080)

**Comment by vinodkiran** [comment]
PR Submitted: https://github.com/FlowiseAI/Flowise/pull/1083

**Comment by HenryHengZJ** [comment]
thank you @vinodkiran !
