### ISSUE TITLE
[BUG] Docker failed at first startup. Vulnerability found? [BUG]  

### ISSUE THREAD

**Issue by Engr-M** [FlowiseAI/Flowise#1072]
**Describe the bug**
First install. 
Can't start docker 
Status : Exited
![image](https://github.com/FlowiseAI/Flowise/assets/148049899/4ab61459-53e9-42d5-bf60-35a93c93590a)

**To Reproduce**
1. Follow this instruction Oct. 16, 2023 : https://docs.flowiseai.com/getting-started
2. 
![image](https://github.com/FlowiseAI/Flowise/assets/148049899/9a9fc48b-8c78-4eb2-80b1-b014d4f47caa)

**Vulnerabilities**
![image](https://github.com/FlowiseAI/Flowise/assets/148049899/f3d0d1fe-55ad-4bd7-a345-9764e44db4a1)
![image](https://github.com/FlowiseAI/Flowise/assets/148049899/b9dc0b70-a3f5-4bc5-a817-b48b85c492b9)
![image](https://github.com/FlowiseAI/Flowise/assets/148049899/5f6bdf40-be6a-42a6-bc7e-d412620f1205)

**Setup**
-   OS: Windows
-   Browser Edge

**Comment by HenryHengZJ** [comment]
if you're using Windows, you have to convert all files under `packages/server/bin` from `CRLF` to `LF` end of line: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/ae357b6c-5881-4ac2-9b50-9c992738ddbe)

Then rebuild the image
