### ISSUE TITLE
[BUG] Streaming chat for ChatOpenAI Custom

### ISSUE THREAD

**Issue by yavisht** [FlowiseAI/Flowise#1081]
**Describe the bug**
Streaming chat does not work on ChatOpenAI Custom

**To Reproduce**
<img width="591" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/6112201/8dc178d3-af09-4346-8129-730a6fbbc00c">

**Expected behavior**
The messages are not streaming back from the chat widget, it just loads the whole message.

**Screenshots**
<video src='https://github.com/FlowiseAI/Flowise/assets/6112201/bf417991-a5d4-42f9-a54c-58e760c04fd8' />

**Flow**
See screenshot

**Additional context**
If I change it to ChatOpenAI, message are streaming back.

**Comment by billsecond** [comment]
Same here.

**Comment by lswencn** [comment]
I also encountered this issue. How can it be resolved?

**Comment by Wowso** [comment]
There is a workaround.

After the prediction API is executed, the Flowise server checks whether the Chat Model supports streaming through the isFlowValidForStream function.

The chatOpenAICustom model is missing from the streamAvailableLLMs variable.

By temporarily adding it, streaming can be enabled.

I'm not sure why only the chatOpenAICustom model is excluded.

https://github.com/FlowiseAI/Flowise/blob/56f9208d7c2d9045da77e85c9b4e124fb9497744/packages/server/src/utils/index.ts#L1189

```typescript
const streamAvailableLLMs = {
        'Chat Models': [
            'azureChatOpenAI',
            'chatOpenAI',
            'chatOpenAI_LlamaIndex',
            'chatOpenAICustom', << Add
            'chatAnthropic',
            'chatAnthropic_LlamaIndex',
            'chatOllama',
            'chatOllama_LlamaIndex',
            'awsChatBedrock',
            'chatMistralAI',
            'chatMistral_LlamaIndex',
            'groqChat',
            'chatGroq_LlamaIndex',
            'chatCohere',
            'chatGoogleGenerativeAI',
            'chatTogetherAI',
            'chatTogetherAI_LlamaIndex',
            'chatFireworks',
            'chatBaiduWenxin'
        ],
        LLMs: ['azureOpenAI', 'openAI', 'ollama']
    }
```
