### ISSUE TITLE
[BUG] all chatflows are deleted on receiving some HTML formatted message.

### ISSUE THREAD

**Issue by agerskov** [FlowiseAI/Flowise#1093]
**Describe the bug**

all my chatflows gets deleted and sometimes even reset the instance.

Last part of that html  from huggingface states "Sorry, there is an error on our side."

not sure if this is an error from huggingface or flowise.
Perhaps it happens when that received message gets saved to the chatMessages array and then it gets corrupted because the html from huggingface isn't the right format.

**To Reproduce**

import chatflow.
add API key for replicate
send message

**Expected behavior**
chat should return a message or error message.

**Screenshots**
![image](https://github.com/FlowiseAI/FlowiseChatEmbed/assets/1219711/9ccb6333-826a-4030-a9fb-730df58c5467)

**Flow**
If applicable, add exported flow in order to help replicating the problem.
[Image Creator! Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13033805/Image.Creator.Chatflow.json)

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

I use huggingface free tier to host it. using docker
flowise@1.3.8

**Additional context**

**Comment by HenryHengZJ** [comment]
related #1094
