### ISSUE TITLE
[FEATURE] Localai Authorization key

### ISSUE THREAD

**Issue by Dbone29** [FlowiseAI/Flowise#1099]
**Describe the feature you'd like**
You can set one or more API_KEY= in the .env in localai. If this is set, the localai server requires an Authorisation: Bearer Token and thus no longer allows requests that do not have this header. It would be nice to be able to specify this token in flowise.

**Additional context**
This function exists since localai v1.24.0 and must be entered manually in the .env.

**Comment by avin-kavish** [comment]
@HenryHengZJ  I can try this. Would it work if I implement it as a input to the nodes or should I have it as an `.env` setting?

**Comment by kkacsh321** [comment]
I worked this out locally, and put up a PR here: https://github.com/FlowiseAI/Flowise/pull/1495 that should satisfy this with any luck.
