### ISSUE TITLE
[FEATURE] Image, Video and Audio Chat Prompt Inputs

### ISSUE THREAD

**Issue by ATaylorAerospace** [FlowiseAI/Flowise#1105]
Hello Flowise team. 

I am requesting the addition of a dropdown  in the Chat Box to accomodate Image, Video and Audio Chat prompt inputs.

With the extremely rapid rollout and adaptation of Multimodal Models; Image, Video and Audio are quickly becoming the primary inputs for Generative AI prompts. (Versus old school text bar only input prompting as was prevalent back in early to mid 2023)
 
Thank You!

![Chatbox](https://github.com/FlowiseAI/Flowise/assets/112668339/b1346892-1161-4237-81f2-dfcb0009579b)

**Comment by HenryHengZJ** [comment]
would love to also expand to multimodal!

**Comment by ATaylorAerospace** [comment]
Let me know what pacxkage might be best to start review and I will be willing to help kick off a PR

**Comment by omarbigboy** [comment]
This would be amazing!

**Comment by vladisimo** [comment]
OpenRouter returns images as a base64 but Flowise doesn't show this at all. Super disappointing.
