### ISSUE TITLE
fail to use ollama[BUG]

### ISSUE THREAD

**Issue by LeisureLover** [FlowiseAI/Flowise#1113]
**Describe the bug**
when i use ollama to build a chatflow, it cannot run.

the error show here:
[server]: Error: Ollama call failed with status code 400: stat /home/.ollama/models/manifests/registry.ollama.ai/library/latest: no such file or directory.

i go to look at the directory, the directory is wrong. because there is an extra /llama2 in the actual directory.
/home/.ollama/models/manifests/registry.ollama.ai/library/llama2/latest

**Comment by HenryHengZJ** [comment]
Have you tested and see if using Ollama API does it work? Might be related to your Ollama setup
