### ISSUE TITLE
[FEATURE] Connect to getumbrel/llama-gpt 

### ISSUE THREAD

**Issue by zMIMI99** [FlowiseAI/Flowise#1120]
I would like to be able to connect from FlowiseAI to this locally running AI, getumbrel/llama-gpt (stared via Docker and running at http://ip:port).
I rather not using the LocalAI solution, unless there is no other choice. If this is possible, please point me in the right direction or please provide me with some instructions or guidelines on how to do this.

**Comment by HenryHengZJ** [comment]
looks like getumbrel/llama-gpt is a full chat application running using llama models. You can use Ollama to have your llama2 models running, and use it within F;owise

**Comment by zMIMI99** [comment]
Do you mean that I should use the llama modles in Ollama in flowiseai or do you mean that I can connect to getumbrel/llama-gpt via Ollama? I would like to keep using getumbrel/llama-gpt because of its CUDA support and roadmap.

**Comment by zMIMI99** [comment]
I guess that you suggesting to use the Ollama installation instead. I installed Ollama and tested it with postman, and it is up and running. Then when I try to connect to it from Flowise (ChatOllama Base URL: http://localhost:11434, Model Name:llama2:13b) I always get "fetch failed" as a response. Any suggestions?
