### ISSUE TITLE
[BUG] Conversational Agent Throws Exception When Used With Chain Tool,  Retrieval QA Chain & Open Source Model

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [FlowiseAI/Flowise#1124]
**Describe the bug**
Conversational agent when used along with a chain tool backed by Retrieval QA chain and an open source LLM like PALM 2 doesn't work properly and 100% of time fail to fetch data from vector store.

**To Reproduce**
1. Do a set up as shown below in Flowise UI.
2. Put a csv file having a customer id, name and phone number.
3. Ask the same question as shown in the screenshot below.

**Expected behavior**
The conversational agent should be able to use the customer-qna chain tool and fetch the results by querying from vector store.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/71944582/0d334854-c343-416d-9fbd-5e77f0d741e2)

![image](https://github.com/FlowiseAI/Flowise/assets/71944582/071acdda-3218-435d-aaa8-1e0259dc1125)

**Flow**
Added the chat flow json file in order to help you reproduce the issue.
[Google Palm Flow - Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13113934/Google.Palm.Flow.-.Chatflow.json)

**Setup**
-   Installation [`yarn start`]
-   Flowise Version [e.g. 1.3.8]
-   OS: [Windows]
-   Browser [chrome]

**Additional context**
1. The result is same even if I replace "Retrieval QA Chain" with "Conversational Retrieval QA Chain".
2. I haven't tried out with Open AI as I don't have any investment done for it. 

Resolving this issue will unlock more areas for open source models via Flowise.

**Comment by HenryHengZJ** [comment]
I suggest create a flow first to upsert the docs to vector store. Then use `Conversational Retrieval Agent` template to retrieve from vector store:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/b992a74c-9a29-4595-a0c2-4cd438bfc4e5)

**Comment by HenryHengZJ** [comment]
yeah i agree. Most open source models dont work with agent/complex chain because the underlying prompt is tailored more to ChatGPT. In that case, try using `Prompt Chaining with VectorStore` template, which means create your own PromptTemplate and LLMChain and use that as a ChainTool
