### ISSUE TITLE
[BUG] POST /api/v1/internal-prediction/95fefbef-5421-4f5f-86b0-b2ce15e58d2b

### ISSUE THREAD

**Issue by apavlinov** [FlowiseAI/Flowise#1125]
i've faced with bug on following architecture in chat interface

<img width="1737" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/48765650/0b6d236c-8dfb-4d60-8ee3-b9f378055de4">

Reproduce Request:
curl 'http://localhost:3001/api/v1/internal-prediction/95fefbef-5421-4f5f-86b0-b2ce15e58d2b' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: ru,en-US;q=0.9,en;q=0.8,uk;q=0.7,pt-PT;q=0.6,pt;q=0.5' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Cookie: SL_G_WPT_TO=en; SL_GWPT_Show_Hide_tmp=undefined; SL_wptGlobTipTmp=undefined' \
  -H 'Origin: http://localhost:3001' \
  -H 'Referer: http://localhost:3001/canvas/95fefbef-5421-4f5f-86b0-b2ce15e58d2b' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="117", "Not;A=Brand";v="8", "Chromium";v="117"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw $'{"question":"test","history":[{"message":"asdsd","type":"userMessage"},{"message":"TypeError: Cannot read properties of undefined (reading \'startsWith\')","type":"apiMessage"},{"message":"test","type":"userMessage"},{"message":"TypeError: Cannot read properties of undefined (reading \'startsWith\')","type":"apiMessage"},{"message":"test","type":"userMessage"},{"message":"TypeError: Cannot read properties of undefined (reading \'startsWith\')","type":"apiMessage"}],"socketIOClientId":"Pw54P3rf0y0wI6-UAAAD"}' \
  --compressed
  
  
  Response:
  TypeError: Cannot read properties of undefined (reading 'startsWith')
  
  
  Log:
 flowise_1  | 2023-10-24 13:16:18 [INFO]: ⬆️ POST /api/v1/internal-prediction/95fefbef-5421-4f5f-86b0-b2ce15e58d2b
flowise_1  | 2023-10-24 13:16:18 [ERROR]: Cannot read properties of undefined (reading 'startsWith')
flowise_1  | TypeError: Cannot read properties of undefined (reading 'startsWith')
flowise_1  |     at Text_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Text/Text.js:56:27)
flowise_1  |     at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:223:72)
flowise_1  |     at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:816:40)
flowise_1  |     at async /usr/local/lib/node_modules/flowise/dist/index.js:609:13
flowise_1  | 2023-10-24 13:16:18 [ERROR]: [server]: Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
flowise_1  | Error: TypeError: Cannot read properties of undefined (reading 'startsWith')
flowise_1  |     at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:235:19)
flowise_1  |     at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:816:40)
flowise_1  |     at async /usr/local/lib/node_modules/flowise/dist/index.js:609:13

**Comment by apavlinov** [comment]
In this case no, i've uploaded data into Milvus database early

**Comment by automaton82** [comment]
I think this is the error you get when a document loader returns no data.
