### ISSUE TITLE
[BUG] properties of undefined error using HuggingFace Inference Embedding

### ISSUE THREAD

**Issue by ptyin** [FlowiseAI/Flowise#1129]
**Describe the bug**

Some unexpected behavior in `HuggingFaceInferenceEmbedding/core#_embed` method:
```typescript
    async _embed(texts: string[]): Promise<number[][]> {
        // replace newlines, which can negatively affect performance.
        const clean = texts.map((text) => text.replace(/\n/g, ' '))  // error
```
causes
```
TypeError: Cannot read properties of undefined (reading 'replace')
flowise-flowise-1 |     at /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/embeddings/HuggingFaceInferenceEmbedding/core.js:19:48
```

**To Reproduce**

- Document Loader
- HuggingFace Inference Embedding
- In-Memory Vector Store

**Expected behavior**

A check before replace text.

**Screenshots**

<img width="709" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/32592585/cd84b77a-b3af-4854-915b-be96a7474b9a">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
  - **docker**
-   Flowise Version [e.g. 1.2.11]
  - **latest, i.e., 1.3.8**
-   OS: [e.g. macOS, Windows, Linux]
  - **mac osx arm64**
-   Browser [e.g. chrome, safari]
  - **chrome**

**Additional context**

**Comment by HenryHengZJ** [comment]
works for me though: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/83f5e871-370c-44f0-8906-ebf6ead1cee1)

**Comment by ptyin** [comment]
> works for me though: ![image](https://user-images.githubusercontent.com/26460777/278064031-83f5e871-370c-44f0-8906-ebf6ead1cee1.png)

Is it possible the content of document leads to different results? Could you please help me try this doc [https://arxiv.org/pdf/2304.08103.pdf](https://arxiv.org/pdf/2304.08103.pdf), and see if it can reproduce the error?

**Comment by HenryHengZJ** [comment]
works - 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/4c1cb40f-ed46-40fc-94a7-13031ff95289)
