### ISSUE TITLE
[BUG] Build error (TS)

### ISSUE THREAD

**Issue by siddiqss** [FlowiseAI/Flowise#1135]
**Describe the bug**
Property 'INDEX_NOT_EXIST' does not exist on type 'typeof ErrorCode'. Did you mean 'IndexNotExist'?ts(2551)
error.d.ts(39, 5): 'IndexNotExist' is declared here.
Error emerges in: packages/components/nodes/vectorstores/Milvus/Milvus_Upsert.ts

**To Reproduce**
yarn build

**Expected behavior**
build should complete

**Setup**
-   Flowise Version 1.3.8
-   OS: macOS

**Comment by automaton82** [comment]
I think this could be closed now, it seems resolved after the PR.
