### ISSUE TITLE
Azure WebApp Deployment Documentation 

### ISSUE THREAD

**Issue by Proteusiq** [FlowiseAI/Flowise#1137]
### Azure WebApp Deployment
I have successfully deployed flowise as Azure WebApp instead of Containers Instance. 

I would not mind to help contribute to documentation of the steps I took or terraform script to deploy flowise as a WebApp with Postgres DB on Azure.

**Comment by chz8494** [comment]
Awesome, could it be free tier?

**Comment by HenryHengZJ** [comment]
would be extremely grateful!! here's the repo - https://github.com/FlowiseAI/FlowiseDocs/tree/main/deployment

**Comment by vskavo** [comment]
> ### Azure WebApp Deployment
> I have successfully deployed flowise as Azure WebApp instead of Containers Instance.
> 
> I would not mind to help contribute to documentation of the steps I took or terraform script to deploy flowise as a WebApp with Postgres DB on Azure.

Did you posted the steps to achieve this?

**Comment by Proteusiq** [comment]
We have now complete the who deployment and it could be performed with a single terraform command that will setup flowise app and postgres DB.

I will add the steps deployment tomorrow

**Comment by Proteusiq** [comment]
> We have now complete the who deployment and it could be performed with a single terraform command that will setup flowise app and postgres DB.
> 
> I will add the steps deployment tomorrow

We are trying to find the best way to add it. We have decided to have two deployments types as we already have container instance way Azure. I will send a pull request and we can edit and change together as a community as we see fit.

**Comment by Proteusiq** [comment]
Made a PR https://github.com/FlowiseAI/FlowiseDocs/pull/57
