### ISSUE TITLE
[BUG] Unable to build anymore on any machine

### ISSUE THREAD

**Issue by automaton82** [FlowiseAI/Flowise#1139]
**Describe the bug**
The build no longer works on any machine, including Windows, Linux and Docker

**To Reproduce**
git clone the repo, follow the build instructions with `yarn install` and `yarn build`. Error as follows:

> flowise-ui:build: $ craco build
> flowise-ui:build: Creating an optimized production build...
> flowise-ui:build: Failed to compile.
> flowise-ui:build: 
> flowise-ui:build: Module parse failed: Unexpected token (143:13)
> flowise-ui:build: File was processed with these loaders:
> flowise-ui:build:  * ../../node_modules/babel-loader/lib/index.js
> flowise-ui:build:  * ../../node_modules/source-map-loader/dist/cjs.js
> flowise-ui:build: You may need an additional loader to handle the result of these loaders.
> flowise-ui:build: |     // `return some()`, `else if()`, `(x*sum(1, 2))`
> flowise-ui:build: |     variants: [{
> flowise-ui:build: >       begin: /=/,
> flowise-ui:build: |       end: /;/
> flowise-ui:build: |     }, {
> flowise-ui:build: 
> flowise-ui:build: 
> flowise-ui:build: error Command failed with exit code 1.
> flowise-ui:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> flowise-ui:build: ERROR: command finished with error: command (E:\git\UpdatedFlowise\packages\ui) yarn run build exited (1)

**Expected behavior**
Builds.

**Comment by gwhale** [comment]
getting similar issue with my builds :(

**Comment by smroczek2** [comment]
Mine is on render and am having the same issue, I tried restoring from a snapshot, but it is just looping starting and failing. 

==> Running 'yarn start'
Oct 27 08:02:33 AM  yarn run v1.22.5
Oct 27 08:02:34 AM  $ run-script-os
Oct 27 08:02:34 AM  $ cd packages/server/bin && ./run start
Oct 27 08:02:37 AM  (node:104) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
Oct 27 08:02:37 AM  (Use `node --trace-deprecation ...` to show where the warning was created)
Oct 27 08:02:37 AM  (node:104) [ERR_DLOPEN_FAILED] Error Plugin: flowise: The module '/opt/render/project/src/node_modules/canvas/build/Release/canvas.node'
Oct 27 08:02:37 AM  was compiled against a different Node.js version using
Oct 27 08:02:37 AM  NODE_MODULE_VERSION 115. This version of Node.js requires
Oct 27 08:02:37 AM  NODE_MODULE_VERSION 120. Please try re-compiling or re-installing
Oct 27 08:02:37 AM  the module (for instance, using `npm rebuild` or `npm install`).
Oct 27 08:02:37 AM  module: @oclif/core@1.26.2
Oct 27 08:02:37 AM  task: toCached
Oct 27 08:02:37 AM  plugin: flowise
Oct 27 08:02:37 AM  root: /opt/render/project/src/packages/server
Oct 27 08:02:37 AM  See more details with DEBUG=*
Oct 27 08:02:37 AM   ›   Error: command start not found
Oct 27 08:02:37 AM  error Command failed with exit code 2.
Oct 27 08:02:37 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Oct 27 08:02:37 AM  error Command failed with exit code 2.
Oct 27 08:02:37 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by automaton82** [comment]
Okay this appears fixed this morning with a fresh install. Only 1135 remains.
