### ISSUE TITLE
[FEATURE] Load Prompts from Langsmith Hub

### ISSUE THREAD

**Issue by vinodkiran** [FlowiseAI/Flowise#1142]
**Load Prompts from Langsmith Hub**

[Langsmith Hub](https://smith.langchain.com/hub) is a popular platform to discover, share, and version control prompts. This is a proposal for integration of Flowise to that platform to allow users to take advantage of a large library of prompts.

The following image depicts a draft thought process, and we are seeking inputs/suggestions on this feature.

![image](https://github.com/FlowiseAI/Flowise/assets/842544/6c41461d-ae28-4800-9af1-7041cc75bf8c)

A similar thought process will be implemented for ChatPromptTemplate as well.

**Comment by HenryHengZJ** [comment]
is this doable in JS, I know python we can do
```
from langchain import hub
obj = hub.pull("homanp/superagent")
```

**Comment by vinodkiran** [comment]
Yes, I have a basic version that works locally. 
[See Gist](https://gist.github.com/vinodkiran/463c2603ca7ed135d9d21437a1a34f94
)

**Comment by HenryHengZJ** [comment]
ah didnt know they have `langchain/hub`

**Comment by vinodkiran** [comment]
Draft PR in place for early review/feedback: https://github.com/FlowiseAI/Flowise/pull/1175
