### ISSUE TITLE
[FEATURE] Add to Supabase Node Credential for API and URL

### ISSUE THREAD

**Issue by Zochory** [FlowiseAI/Flowise#1145]
Description: I would like to suggest adding support for Supabase Node credentials in Flowise. Currently, Flowise supports various authentication methods for different services, but it does not have built-in support for Supabase Node API and URL credentials.

**Comment by HenryHengZJ** [comment]
Supabase can be used as backend databsae by configuring the env variable: https://docs.flowiseai.com/configuration/environment-variables#for-database
