### ISSUE TITLE
[BUG]canvas was compiled against a different Node.js

### ISSUE THREAD

**Issue by Marlonluo** [FlowiseAI/Flowise#1151]
**Describe the bug**
I have up to date node 
C:\Windows\System32>node --version
v20.9.0

still get this error.

**To Reproduce**
C:\Windows\System32>npx flowise start
    Error: The module '\\?\C:\Users\022370672\AppData\Roaming\npm\node_modules\flowise\node_modules\canvas\build\Release\canvas.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 115. This version of Node.js requires
    NODE_MODULE_VERSION 120. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or `npm install`).
    Code: ERR_DLOPEN_FAILED

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by dongwangdw** [comment]
This may be not a bug. it works for me, either with yarn or npm. But my node version is 21.1.0.

**Comment by Marlonluo** [comment]
it is not about Node Version; I update to 21.1.0 still not working.
C:\Windows\System32>npm install -g node@21.1.0

removed 1 package, and changed 2 packages in 3m

C:\Windows\System32>npx flowise start
    Error: The module
    '\\?\C:\Users\022370672\AppData\Roaming\npm\node_modules\flowise\node_modules\canvas\build\Release\canvas.node'
    was compiled against a different Node.js version using
    NODE_MODULE_VERSION 115. This version of Node.js requires
    NODE_MODULE_VERSION 120. Please try re-compiling or re-installing
    the module (for instance, using `npm rebuild` or `npm install`).
    Code: ERR_DLOPEN_FAILED
