### ISSUE TITLE
[BUG]Fail to yarn build

### ISSUE THREAD

**Issue by nobod4t** [FlowiseAI/Flowise#1153]
**Describe the bug**
```
flowise-components:build: nodes/vectorstores/Milvus/Milvus_Upsert.ts(255,59): error TS2551: Property 'IndexNotExist' does not exist on type 'typeof ErrorCode'. Did you mean 'INDEX_NOT_EXIST'?
```

**To Reproduce**

change to main branch, pull and yarn build

**Expected behavior**
Building should be OK

This commit [60ac084](https://github.com/FlowiseAI/Flowise/commit/60ac08413a79636091972aecf286edab34e4a509) produce this.

**Comment by neo4dev** [comment]
same issue deploying on render.com
Nov 1 08:53:48 PM  #17 10.70 flowise-ui:build:
Nov 1 08:54:21 PM  #17 44.39 flowise-components:build: nodes/vectorstores/Milvus/Milvus_Upsert.ts(255,59): error TS2551: Property 'INDEX_NOT_EXIST' does not exist on type 'typeof ErrorCode'. Did you mean 'IndexNotExist'?
Nov 1 08:54:21 PM  #17 44.57 flowise-components:build: error Command failed with exit code 2.
Nov 1 08:54:21 PM  #17 44.57 flowise-components:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Nov 1 08:54:21 PM  #17 44.60 flowise-components:build: ERROR: command finished with error: command (/usr/src/packages/packages/components) yarn run build exited (2)

**Comment by dongwangdw** [comment]
really? It should be INDEX_NOT_EXIST instead of IndexNotExist. See below:
![Screenshot 2023-11-01 at 9 20 47 PM](https://github.com/FlowiseAI/Flowise/assets/2303377/0b7d2e3b-b428-4054-b4b5-cb3fc9273d87)

**Comment by HenryHengZJ** [comment]
this is strange, a while back it was the other way round - https://github.com/FlowiseAI/Flowise/pull/1136

**Comment by nobod4t** [comment]
> this is strange, a while back it was the other way round - #1136

The right reference should be ErrorCode.INDEX_NOT_EXIST or use  "IndexNotExist" directly, not just ErrorCode.IndexNotExist.

**Comment by neo4dev** [comment]
> this is strange, a while back it was the other way round - #1136

I sync the latest repo and it works now. Thanks.

**Comment by nobod4t** [comment]
Oh the error code is fron milvus not flowise.
