### ISSUE TITLE
Help: yarn install failed,Request timed out

### ISSUE THREAD

**Issue by ian2743** [FlowiseAI/Flowise#1154]
Mac m1

>yarn install

error /Users/lishuai/Documents/A-Work/D-AiProject/Flowise-flowise-1.3.8/node_modules/faiss-node: Command failed.
Exit code: 1
Command: prebuild-install --runtime napi --verbose || (npm i cmake-js && npm run build)
Arguments: 
Directory: /Users/lishuai/Documents/A-Work/D-AiProject/Flowise-flowise-1.3.8/node_modules/faiss-node
Output:
prebuild-install info begin Prebuild-install version 7.1.1
prebuild-install info looking for local prebuild @ prebuilds/faiss-node-v0.2.3-napi-v8-darwin-arm64.tar.gz
prebuild-install info looking for cached prebuild @ /Users/lishuai/.npm/_prebuilds/224c8b-faiss-node-v0.2.3-napi-v8-darwin-arm64.tar.gz
prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/download/v0.2.3/faiss-node-v0.2.3-napi-v8-darwin-arm64.tar.gz
prebuild-install warn install Request timed out
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

**Comment by dongwangdw** [comment]
maybe you need to check your network. 
I can run it with no issue.

**Comment by uilfl** [comment]
@isikhi  that works for me!  tks
