### ISSUE TITLE
[FEATURE] QA with Sources

### ISSUE THREAD

**Issue by beddows** [FlowiseAI/Flowise#116]
Very nice UI!

Would be great if the VectorDB QA Chain node included the parameter `returnSourceDocuments` (i.e.: setting the `returnSourceDocuments` to `true` when calling the chain).

**Comment by HenryHengZJ** [comment]
@beddows `returnSourceDocuments` allows you to get back the different Document chunks like this:
```
sourceDocuments: [
    Document {
      pageContent: 'somedoc..',
      metadata: [Object]
    },
]
```
Is that what you are expected to receive?

**Comment by beddows** [comment]
@HenryHengZJ Yes, that looks correct. The metadata can be used by the LLM summarizer to identify the sources of the chunks that are contributing to the final answer (and will provide the sources when prompted to do so).

**Comment by HenryHengZJ** [comment]
@beddows do you mind to have a quick test to see if that satisfy your use cases?

In the line under [this](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/VectorDBQAChain/VectorDBQAChain.ts#L43) can you add `chain.returnSourceDocuments = true`?

My thought is that we'll have to use [Output Parser](https://js.langchain.com/docs/modules/prompts/output_parsers/#structured-output-parser) if we want to see the specific source where the answer is from, not sure how to use the `sourceDocuments` array returned from `returnSourceDocuments`

**Comment by nmoturi** [comment]
> @beddows do you mind to have a quick test to see if that satisfy your use cases?
> 
> In the line under [this](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/VectorDBQAChain/VectorDBQAChain.ts#L43) can you add `chain.returnSourceDocuments = true`?
> 
Hi Henry,

Langchain implementation of ectorDBQAWithSourcesChain is deprecated - It needed to be added in the RetrievalQA Chain

warnings.warn( "`VectorDBQAWithSourcesChain` is deprecated - " "please use `from langchain.chains import RetrievalQAWithSourcesChain

**Comment by HenryHengZJ** [comment]
Perfect, this line then - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/RetrievalQAChain/RetrievalQAChain.ts#L43

**Comment by HenryHengZJ** [comment]
Its now supported using ConversationalRetrievalQAChain - https://github.com/FlowiseAI/Flowise/pull/274
