### ISSUE TITLE
[FEATURE] Support for Setting Custom PostgreSQL Schema

### ISSUE THREAD

**Issue by lusky601632** [FlowiseAI/Flowise#1160]
Hello,

I have noticed that the current implementation for PostgreSQL defaults to the public schema. In our use case, this default schema is not preferable due to specific access restrictions.

Upon reviewing the documentation, I did not find an option to configure the PostgreSQL schema within your environment settings. Being able to specify a different schema is crucial for our application's database organization and access control.

Feature Request:

Add the capability to set a custom schema for PostgreSQL database connections.
Provide an environment variable or a configuration parameter to specify the desired schema.
This enhancement would not only benefit our current situation but could also be helpful for other users who need similar flexibility due to policy constraints or organizational standards.

I am looking forward to your thoughts on this proposal and would be happy to discuss it further.

Thank you for your time and consideration.

Best regards,
Sky

**Comment by HenryHengZJ** [comment]
Do you mean the database tables schema (if so, why would you want to change the schema)? or the connection configuration to your PostgreSQL instance?
