### ISSUE TITLE
[Feature] Selecting the specific language only for the answers

### ISSUE THREAD

**Issue by devcoder111** [FlowiseAI/Flowise#1171]
Hi
This is my chatflow
![image](https://github.com/FlowiseAI/Flowise/assets/42604047/e208bdcc-5d07-441a-8525-6329d952377d)

In this chat flow, the response's language depends on the user's first word I think
But I want to have the chat that responds with only a specific language(ex: Norwegian)
Is that possible?

Thanks

**Comment by retail-amelis** [comment]
Hi @devcoder111,
try to add specific prompting ub the modal "Additional Parameters" into the Chain.

something like this:

-------------------------------------------------
Language rules:
Answer all the questions in Norwegian.
-------------------------------------------------

**Comment by devcoder111** [comment]
Hi @retail-amelis 
Thanks for your response.
But there is no prompt chain on my workflow, I have conversational qa chain only

**Comment by HenryHengZJ** [comment]
Closing as its a duplicate of #1172
