### ISSUE TITLE
[Bug] Language is wrong on my chatflow

### ISSUE THREAD

**Issue by devcoder111** [FlowiseAI/Flowise#1172]
Hi
This is my chatflow
![image](https://github.com/FlowiseAI/Flowise/assets/42604047/905cb3c6-301f-4868-afe8-79eadbef870d)

In this chat flow, I wrote in Norwegian, but the response is in English, need to be Norwegian
I want to have a chat that responds with only a specific language(ex: Norwegian)
Is that possible?

Thanks

**Comment by HenryHengZJ** [comment]
You can try specify the System Message in Norwegian in the Chain, and explicitly tells it to only response in Norwegian

**Comment by devcoder111** [comment]
I wrote the System Message In Norwegian in the chain, but still saying with English

**Comment by saevarb** [comment]
We are having similar problems and I think the most likely culprit is LangChain. 

Our use case is a bit different than yours, as we are using tools, but I don't think it's unlikely that at some point, your flow ends up in a similar situation.

In our particular case, after the agent has used a tool to retrieve some information, LangChain ends up constructing this [prompt](https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/agents/chat_convo/prompt.ts#L54).



Which is then used [here](https://github.com/langchain-ai/langchainjs/blob/ff7ef3d2b7cd36cd8b0bb39d19d60f3636e9ec4a/langchain/src/agents/chat_convo/index.ts#L101). This is hard-coded in LangChain and can't be configured without modifying the code as it is currently.

**Comment by HenryHengZJ** [comment]
We've now revamped `ConversationalRetrievalQAChain` and allow total customization on the prompts:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/a1705dd3-efa2-48de-8822-e1d8238f0405)

Previously some of these prompts are still written in English and not exposed to user for modification. With this, you can write all the prompts in language of your choice
