### ISSUE TITLE
[FEATURE] access vector store meta data in final output

### ISSUE THREAD

**Issue by bacca-chew** [FlowiseAI/Flowise#1184]
**Describe the feature you'd like**
You can use the meta data from the vector store receivers for filtering purposes, but it would also be convenient if we could access it in the final response of the Conversation Retrieval QA Chain.

**Additional context**
I've tried adding it to the [finalText variable](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/ConversationChain/ConversationChain.ts#L79-L82) but that doesn't seem to work for some reason.
Or is that not where I should be looking?

**Comment by HenryHengZJ** [comment]
how would u like to access from the final response? You can turn on `Return Source Document` and that will return the sources
