### ISSUE TITLE
[BUG]Ollama component does not work

### ISSUE THREAD

**Issue by j3nsykes** [FlowiseAI/Flowise#1189]
**Describe the bug**
ollama component does not connect. There is minimal documentation but what I can fidn i have followed. Flowise is running locally via Docker on localhost:3000 . Ollama is served on localhost:11434
Immediately produces a fetch fail when prompted. 

When I check if ollama is running via Terminal and check the http://localhost:11434/api/tags it is running and downloaded successfully. It also successfully connects to other local apps working in similar ways to FlowiseAI. leading me to think there is an issue with the component

**Flow**
chatflow 
[ollama Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13289424/ollama.Chatflow.json)

**Setup**
-   Installation :docker
-   OS: macOS
-   Browser:chrome

**Comment by HenryHengZJ** [comment]
can you try `http://host.docker.internal:11434` in the Ollma base URL?

**Comment by HenryHengZJ** [comment]
oh I was trying the other way round - Ollama on Docker, FW on local

**Comment by billygogo** [comment]
> can you try `http://host.docker.internal:11434` in the Ollma base URL?

thank you, I solved same problem.

**Comment by sirpilan** [comment]
Running fowise and ollama in separate containers.

add this to your `<flowise_dir>/docker/docker-compose.yaml`:

```
services:
    flowise:
        # PART BELOW ---8<---8<---
        extra_hosts:
            - host.docker.internal:host-gateway
       # UNTIL HERE ---8<---8<---
```

`up` it again.

use `http://host.docker.internal:11434` as `Base URL`

in case you are using open-webui (former ollama-webui) then default port will be `11435`

**Comment by netgfx** [comment]
I'm still facing this issue, I have flowise and Ollama on different containers, both have NGinx infront. I can see the `Ollama is running` on the Ollama server but when I try to connect (with a port or not) I still get the "fetch failed" message

**Comment by pancodia** [comment]
The solution from @sirpilan works for me! I also installed Ollama via docker and Flowise via docker compose. 
I am not an expert on docker network. But I guess this is caused by Ollama and Flowise containers are not on the same network in docker or on subnets that can communicate with each other.
I previously used [Open WebUI](https://github.com/open-webui/open-webui?tab=readme-ov-file#installation-with-default-configuration) to interact with Ollama. It needs to set `--add-host=host.docker.internal:host-gateway` when creating the docker.

**Comment by SargeJoseph** [comment]
I'm also running ollama and flowise via docker in separate containers. 
Replacing the base URL fixed the issue with the OllamaChat node **but it didn't fix the issue when Follow-up Prompts was enabled in the configuration and Ollama was set up as the provider.**

The only way I was able to make it work was by also changing the base URL directly in browser.cjs located here:

/usr/local/lib/node_modules/flowise/node_modules/ollama/dist/browser.cjs

I don't know if there is another way but it finally worked :)
