### ISSUE TITLE
Exporting to a webpage

### ISSUE THREAD

**Issue by umaar** [FlowiseAI/Flowise#12]
Once you've made a chatflow, and export it to JSON, is there some tool that can use and embed it on a website? I guess what I'm wondering is the use case for building this, thanks

**Comment by HenryHengZJ** [comment]
Currently this is not available. The goal is to be able to deploy the flow to cloud services.  Deployed chatflow will have a chat interface which can be interacted with or embed as a code into your application codebase.

**Comment by umaar** [comment]
Cool thanks
