### ISSUE TITLE
[FEATURE] Login page on UI

### ISSUE THREAD

**Issue by mahaboobkhan29** [FlowiseAI/Flowise#120]
Can you make a login page in UI that i can only acces the website beacause the website is open so anyone have see the api key

**Comment by HenryHengZJ** [comment]
Its implemented - https://github.com/FlowiseAI/Flowise/pull/103

https://github.com/FlowiseAI/Flowise#-authentication

**Comment by mahaboobkhan29** [comment]
@HenryHengZJ Thank You.. can we change the parroticon in chat UI with our own icon?

I have change with mine in local code but when i use Embed in website still parroticon  is showing

**Comment by HenryHengZJ** [comment]
definitely, the embedded chat widget is just the first pass, more customization will be released soon :)
