### ISSUE TITLE
[Question] Is there a running list of Feature Requests?

### ISSUE THREAD

**Issue by austinbiggs** [FlowiseAI/Flowise#1204]
I'd love to jump in and contribute to Flowise. It would be great if there were a system (maybe a set of labels) to track feature requests by package.

**Comment by HenryHengZJ** [comment]
Hey @austinbiggs we currently dont have a public feature requests yet, only our internal backlog, happy to share that on Discord

Anything tagged with `enhancement` or `help wanted` are good to start with

**Comment by austinbiggs** [comment]
> Anything tagged with `enhancement` or `help wanted` are good to start with

@HenryHengZJ thanks for the reply, I'd be down to sync on Discord. I'll hit you up.
