### ISSUE TITLE
BraveSearch Agent has Description Error 

### ISSUE THREAD

**Issue by john-cornell** [FlowiseAI/Flowise#1211]
**Describe the bug**
When I add a Brave Search agent to a conversational agent and chat with it I get the following:

Error: Got a tool undefined without a description. This agent requires descriptions for all tools.

**To Reproduce**

1. Add Conversational Agent
2. Add Chat
3. Add Brave Search API as Allowed Agent

**Expected behavior**
I expect it to respond as per its returned search

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/2315889/63714a75-e8a2-4385-954f-9a9794509572)

**Comment by HenryHengZJ** [comment]
works for me?
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/65b988ea-e918-4984-8e92-90adf5eef378)

**Comment by HenryHengZJ** [comment]
Try creating it from scratch as its been tested and worked correctly. closing for now.
