### ISSUE TITLE
[BUG] Plugin API Key 

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#122]
When using the AI Plugin node, this is the type of response I receive:

Langchain: "It seems like we need to provide an API key to access the Polygon API. I'll check if we have an API key for Polygon."

Do plugins require API Key to run?
Will someone tell me where to store the API keys?

**Comment by ShivangRawat30** [comment]
Q. Do plugins require API Key to run?
Ans. If a plugin interacts with an API that requires authentication, it's common for the plugin to request an API key from the user. This key is then used by the plugin to make authenticated API requests on behalf of the user. 
Some plugins may work without any external API integration or may use alternative authentication methods such as OAuth or tokens.

Q. Will someone tell me where to store the API keys?
Ans. you can store the api key in .env file

**Comment by HenryHengZJ** [comment]
Duplicated issue #132
