### ISSUE TITLE
[FEATURE] Enable test for Flowise

### ISSUE THREAD

**Issue by nobody4t** [FlowiseAI/Flowise#1220]
**Describe the feature you'd like**

Currently, Flowise got no tests.
So enable the tests framework for this repos.

**Comment by nobod4t** [comment]
@HenryHengZJ Is there any module/function which should be in 1st priority for testing. From my opinion, backend is.
Any advice?

**Comment by HenryHengZJ** [comment]
backend definitely, functions in /utils
