### ISSUE TITLE
[FEATURE] huggingface chat

### ISSUE THREAD

**Issue by ranon-rat** [FlowiseAI/Flowise#1228]
I think it would be more practical that at the moment of generating the prompt that is going to be passed to the huggingface endpoints they follow their format, I say this mostly because I have been trying to use a huggingface endpoint for that but it doesn't work and gives me strange results.
I only mention this because I was checking your code and I didn't see anywhere that it follows the typical format of 
```html
<s>[INST]previous question[/INST] answer</s>
<s>[INST]<<SYS>>system prompt<</SYS>>> question[/INST]answer</s>
```

**Comment by HenryHengZJ** [comment]
This is only specific to Llama2 format, and there are lots of other models on HF. Hence its better for user to specify by themselv on the agent system prompt
