### ISSUE TITLE
[FEATURE] Support for Thread ID in API Requests for OpenAI Assistant

### ISSUE THREAD

**Issue by lucasduarte0** [FlowiseAI/Flowise#1232]
## Current Behavior
Currently, the API does not seem to support thread management. In my usage, I've noticed that the API retrieves a random thread for each call, which makes it challenging to handle specific conversation threads in applications that manage multiple chats simultaneously.

## Desired Behavior
The proposed feature would allow users to send a specific thread ID with each API request. This would enable the API to handle requests in the context of the specified thread, rather than randomly selecting a thread. This feature is crucial for building more structured and organized chat management systems using the Flowise API.

## Use Case
This feature is particularly useful for applications that need to manage multiple, concurrent chat conversations. By allowing the API to handle specific threads, developers can create more sophisticated and user-friendly chat interfaces.

## Questions
1. Is this feature currently possible with the existing API?
2. If not, what would be the process for considering and potentially implementing this feature?

I have reviewed the existing code and documentation but haven't found any references to thread management in the API. I look forward to hearing your thoughts on this feature request.

Thank you for considering this enhancement to the Flowise API.

**Comment by HenryHengZJ** [comment]
It does. Just specify `chatId` in your body request as documented here - https://docs.flowiseai.com/memory/threads
