### ISSUE TITLE
[BUG?] Override GoogleVertex Models

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#1233]
@chungyau97 - I am unable to override the list of models for GoogleVertex node. I'd like to use the GA models text-bison@001 or chat-bison@001. Here is a screenshot of a chat node. This only supports latest models. Is there a way to override the models without using Google Makersuite node?

<img width="181" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/121184261/abfadcb6-ddc4-43ee-a6d9-4bca3e301251">

**Comment by HenryHengZJ** [comment]
you can add the model under the [options](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatGoogleVertexAI/ChatGoogleVertexAI.ts#L48)

**Comment by vijaykammili** [comment]
@HenryHengZJ - Can we override this config or are you suggesting we make this change in the code itself?

**Comment by HenryHengZJ** [comment]
> @HenryHengZJ - Can we override this config or are you suggesting we make this change in the code itself?

You'll have to make the changes on the code
