### ISSUE TITLE
[BUG] Dependency issue for HuggingFace deployment

### ISSUE THREAD

**Issue by leeek** [FlowiseAI/Flowise#1238]
**Describe the bug**
If I duplicate the HuggingFace [space](https://huggingface.co/spaces/FlowiseAI/Flowise), I get the runtime error:

> 2023-11-15 16:07:49 [INFO]: 📦 [server]: Data Source has been initialized!
2023-11-15 16:07:52 [ERROR]: ❌ [server]: Error during Data Source initialization: Cannot find module '/usr/local/lib/node_modules/flowise/node_modules/@gomomento/sdk/dist/src/index.js'. Please verify that the package.json has a valid "main" entry
Error: Cannot find module '/usr/local/lib/node_modules/flowise/node_modules/@gomomento/sdk/dist/src/index.js'. Please verify that the package.json has a valid "main" entry

If I ignore this error and proceed, I am unable to make new credentials.

**To Reproduce**

1. Go to the HuggingFace space: https://huggingface.co/spaces/FlowiseAI/Flowise
2. Duplicate it to your own account
3. Observe the runtime error

**Additional context**
I was able to fix this by modifying the Dockerfile line from `RUN npm install -g flowise` to `RUN npm install -g flowise@"^1.4.2" "@gomomento/sdk@<1.50.0"`. `gomomento` released updates last night that seem to have broken something.

The quick fix is to modify this [line](https://github.com/FlowiseAI/Flowise/blob/a311e024e1eae56e656e8774a0747d479addb27a/packages/components/package.json#L25) but I don't know what changed to cause issues.

**Comment by automaton82** [comment]
The entire build is broken because of that dependency. You need to rollback the gomomento package like you mentioned. There's another bug open also about this.

I suggest Flowise target lesser versions of upgrades via `~` instead of `^` to power the probability of breakages.

**Comment by HenryHengZJ** [comment]
@automaton82 does changing that line mentioned above from `^` to `~` able to solve the issue?

**Comment by HenryHengZJ** [comment]
related #https://github.com/FlowiseAI/Flowise/issues/1239

**Comment by automaton82** [comment]
@HenryHengZJ I changed my local copy to:

`"@gomomento/sdk": "~1.47.3",`

And this solved it for me.

**Comment by HenryHengZJ** [comment]
updated to latest version `^1.51.1`, should resolved now. feel free to reopen if thats not the case
