### ISSUE TITLE
[BUG] on build Cannot find module '@gomomento/sdk' or its corresponding type declaration

### ISSUE THREAD

**Issue by Cannon-Cloud** [FlowiseAI/Flowise#1239]
On docker build: 
<img width="1485" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/87342611/48eae021-a75c-4146-99c6-89fcf2ded23b">

**Comment by davideuler** [comment]
I've came across the same error.

**Comment by automaton82** [comment]
You have to roll the package back in the package.json file. The latest one is broken.

Flowise should probably stick only with minor updates on all packages (`~`) instead of the current `^`. This isn't the first time a package has broken the build.

**Comment by HenryHengZJ** [comment]
updating to `"@gomomento/sdk": "^1.47.1",` seems to work. should keep an eye on langchainjs dependencies to have these packages up to date

**Comment by HenryHengZJ** [comment]
updated to latest version ^1.51.1, should resolved now. feel free to reopen if thats not the case
