### ISSUE TITLE
[BUG] Recent point releases are not creating new releases in github

### ISSUE THREAD

**Issue by nsvrana** [FlowiseAI/Flowise#1240]
**Describe the bug**
The Github release is still 1.4.0 while it looks like both 1.4.1 and 1.4.2 have been updated. This means my application says it is version 1.4.2 but the latest version is 1.4.0.

![image](https://github.com/FlowiseAI/Flowise/assets/4226491/be12ec50-fcb7-4f9b-9103-095852442e85)

**Comment by HenryHengZJ** [comment]
should be resolved in the latest release
