### ISSUE TITLE
401 Unauthorized Error When Using DELETE API Endpoint

### ISSUE THREAD

**Issue by samsam002** [FlowiseAI/Flowise#1251]
Hello Community,,

I've been encountering a persistent issue with the DELETE API endpoint for deleting chat history. Despite providing the correct API key in the header, I consistently receive a "401 Unauthorized" response. 

Here's the cURL command I'm using:
curl -X DELETE "[http://localhost:3000/api/v1/chatmessage/{your-chatflowid}](http://localhost:3000/api/v1/chatmessage/{chat-flow-id}"
-H "Authorization: Bearer {api_key}"

I have verified that my API key is correct and checked the endpoint URL. Are there any additional authentication steps or headers that I might be missing? Any guidance or assistance with this issue would be greatly appreciated.

Thank you,

**Comment by HenryHengZJ** [comment]
chat history is an admin endpoint, you have to use BasicAuth (username + password) for that not the Bearer Token
