### ISSUE TITLE
[BUG]No login authentication by Container deployment in Azure with persistent storage

### ISSUE THREAD

**Issue by delinecnlin** [FlowiseAI/Flowise#1266]
**Describe the bug**
No login authentication by Container deployment in Azure with persistent storage

**To Reproduce**
use the method in flowise docs for Azure

**Expected behavior**

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/135121608/94e96a65-52b6-4d63-91fe-581e1c3721ee)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by delinecnlin** [comment]
It used to have that by previous installation

**Comment by HenryHengZJ** [comment]
have you set the env variables - `FLOWISE_USERNAME` and `FLOWISE_PASSWORD`? https://docs.flowiseai.com/deployment/azure
no changes were made there, it should works as before

**Comment by delinecnlin** [comment]
> have you set the env variables - `FLOWISE_USERNAME` and `FLOWISE_PASSWORD`? https://docs.flowiseai.com/deployment/azure no changes were made there, it should works as before

yes, here is the output:
{
  "confidentialComputeProperties": null,
  "containers": [
    {
      "command": [
        "/bin/sh",
        "-c",
        "flowise start"
      ],
      "environmentVariables": [
        {
          "name": "FLOWISEUSERNAME",
          "secureValue": null,
          "value": "fsafaf"
        },
        {
          "name": "FLOWISEPASSWORD",
          "secureValue": null,
          "value": "afsafaf"
        },
        {
          "name": "DATABASEPATH",
          "secureValue": null,
          "value": "/opt/flowise/.flowise"
        },
        {
          "name": "APIKEYPATH",
          "secureValue": null,
          "value": "/opt/flowise/.flowise"
        },
        {
          "name": "SECRETKEYPATH",
          "secureValue": null,
          "value": "/opt/flowise/.flowise"
        },
        {
          "name": "LOGPATH",
          "secureValue": null,
          "value": "/opt/flowise/.flowise/logs"
        }
      ],
      "image": "flowiseai/flowise",
      "instanceView": {
        "currentState": {
          "detailStatus": "",
          "exitCode": null,
          "finishTime": null,
          "startTime": "2023-11-22T05:13:04.660000+00:00",
          "state": "Running"
        },
        "events": [
          {
            "count": 1,
            "firstTimestamp": "2023-11-22T05:11:40+00:00",
            "lastTimestamp": "2023-11-22T05:11:40+00:00",
            "message": "pulling image \"flowiseai/flowise@sha256:36af2ea41f09d4a69b76babb43e88f582eda82d99235896ad3d9b17519ce860b\"",
            "name": "Pulling",
            "type": "Normal"
          },
          {
            "count": 1,
            "firstTimestamp": "2023-11-22T05:12:48+00:00",
            "lastTimestamp": "2023-11-22T05:12:48+00:00",
            "message": "Successfully pulled image \"flowiseai/flowise@sha256:36af2ea41f09d4a69b76babb43e88f582eda82d99235896ad3d9b17519ce860b\"",
            "name": "Pulled",
            "type": "Normal"
          },
          {
            "count": 1,
            "firstTimestamp": "2023-11-22T05:13:04+00:00",
            "lastTimestamp": "2023-11-22T05:13:04+00:00",
            "message": "Started container",
            "name": "Started",
            "type": "Normal"
          }
        ],
        "previousState": null,
        "restartCount": 0
      },
      "livenessProbe": null,
      "name": "affassfa",
      "ports": [
        {
          "port": 80,
          "protocol": "TCP"
        },
        {
          "port": 3000,
          "protocol": "TCP"
        }
      ],
      "readinessProbe": null,
      "resources": {
        "limits": null,
        "requests": {
          "cpu": 1.0,
          "gpu": null,
          "memoryInGb": 1.5
        }
      },
      "securityContext": null,
      "volumeMounts": [
        {
          "mountPath": "/opt/flowise/.flowise",
          "name": "azurefile",
          "readOnly": null
        }
      ]
    }
  ],
  "diagnostics": null,
  "dnsConfig": null,
  "encryptionProperties": null,
  "extensions": null,
  "id": "/subscriptions/fc69bb3a-a652-4352-a03a-942fc7651a81/resourceGroups/rg-linseasia/providers/Microsoft.ContainerInstance/containerGroups/flowiseproduction",
  "identity": null,
  "imageRegistryCredentials": null,
  "initContainers": [],
  "instanceView": {
    "events": [
      {
        "count": 1,
        "firstTimestamp": "2023-11-22T05:13:02.869000+00:00",
        "lastTimestamp": "2023-11-22T05:13:02.869000+00:00",
        "message": "Successfully mounted Azure File Volume.",
        "name": "SuccessfulMountAzureFileVolume",
        "type": "Normal"
      }
    ],
    "state": "Running"
  },
  "ipAddress": {
    "autoGeneratedDomainNameLabelScope": "Unsecure",
    "dnsNameLabel": "afafaf",
    "fqdn": "afsafs.southeastasia.azurecontainer.io",
    "ip": "afafafa",
    "ports": [
      {
        "port": 80,
        "protocol": "TCP"
      },
      {
        "port": 3000,
        "protocol": "TCP"
      }
    ],
    "type": "Public"
  },
  "location": "southeastasia",
  "name": "asfsafa",
  "osType": "Linux",
  "priority": null,
  "provisioningState": "Succeeded",
  "resourceGroup": "fasfa",
  "restartPolicy": "OnFailure",
  "sku": "Standard",
  "subnetIds": null,
  "tags": {},
  "type": "Microsoft.ContainerInstance/containerGroups",
  "volumes": [
    {
      "azureFile": {
        "readOnly": null,
        "shareName": "fileflowise",
        "storageAccountKey": null,
        "storageAccountName": "storeflowise"
      },
      "emptyDir": null,
      "gitRepo": null,
      "name": "azurefile",
      "secret": null
    }
  ],
  "zones": null
}

**Comment by HenryHengZJ** [comment]
are you missing an underscore? `FLOWISE_USERNAME`

**Comment by delinecnlin** [comment]
Just fix it by reinstall with another updated version and it works again. can be closed
