### ISSUE TITLE
How to allow tools, QA and returning source documents all in one?

### ISSUE THREAD

**Issue by WilliWespe** [FlowiseAI/Flowise#1267]
I need an end node that allows tools, but also returns the sources on which it forms its answer.
My chatflow looks like this:
![image](https://github.com/FlowiseAI/Flowise/assets/16957566/43927682-4bbb-4e15-9e8a-a6883858f48e)

In a Conversational Retrieval QA Chain I can switch on "Return Source Documents", but this node doesn't allow tools.
![image](https://github.com/FlowiseAI/Flowise/assets/16957566/2d891fd5-066c-4c12-8297-b1db87844c03)

Is there a node or architecture, that can do all of this?
Allowing tools, QA and referencing/returning the sources?

**Comment by HenryHengZJ** [comment]
We are looking at it to see how we can make this available

**Comment by WilliWespe** [comment]
Thanks

**Comment by WilliWespe** [comment]
Is it perhaps possible to extract the sources and the answer separately and build a new prompt from them?

Something like this:
![image](https://github.com/FlowiseAI/Flowise/assets/16957566/4d679a82-5e65-42b2-a8e9-956b95ec93d9)

Otherwise my idea is to build two separate chatflows. One to return the answer with the source documents and one to modify the answer with the tools. Then I would also build a custom tool that fetches the answer and sources from the first chatflow and enters it into an agent that can apply tools to the input.

Or are there better possibilities?

**Comment by HenryHengZJ** [comment]
you can now return source documents on retriever tool

**Comment by WilliWespe** [comment]
> you can now return source documents on retriever tool

What flowise version do you have?
I reinstalled mine. My version is now 1.4.11.
But my Retriever Tool looks different than yours. Do you know why that's the case?
![image](https://github.com/FlowiseAI/Flowise/assets/16957566/728c8b3b-607e-4d42-a798-c52991380634)

**Comment by HenryHengZJ** [comment]
@WilliWespe just released a new version. You should now see it on 1.4.12
