### ISSUE TITLE
[BUG] github repo 

### ISSUE THREAD

**Issue by bigredcoder** [FlowiseAI/Flowise#127]
I use the GitHub template and the chat does not understand my question. Seems to not be scraping the repo and uploading to pinecone. All api keys are correct. Any idea why this is not working?

**Comment by HenryHengZJ** [comment]
Yeah currently GithubLoader only be able to get `.md` files. If you're looking to ask question on the code, it won't be able to do that yet

**Comment by bigredcoder** [comment]
Thank you. Trying to find a solution like this where I can have a bot that can have conversations with my code base with long-term memory. Basically, a jr developer agent.

**Comment by ill-yes** [comment]
You need to activate recursive scanning.

**Comment by kevinseabourne** [comment]
is this still an issue ?

**Comment by jtuck41** [comment]
Any update on this? Features to chat with full git codebases?

**Comment by mynumu** [comment]
hello any update - has this been added to FW thanks

**Comment by HenryHengZJ** [comment]
We can turn on Recursive option to go over each and everyfiles within the repo: 
![image](https://github.com/user-attachments/assets/7a4b5bff-1c1b-412d-bdb3-709cdb266a37)
