### ISSUE TITLE
[BUG]  OpenAI assistant with chain tool doesn't work 

### ISSUE THREAD

**Issue by agnosus** [FlowiseAI/Flowise#1286]
Tried using a QA retrieval chain as tool for OpenAI assistant and I got a crash!

![Capture](https://github.com/FlowiseAI/Flowise/assets/64579856/4495cddd-e58e-453e-bc52-b2ce75120867)
![Capture1](https://github.com/FlowiseAI/Flowise/assets/64579856/08a4240c-38c9-4dd0-8a32-85b405fa3065)

**Comment by HenryHengZJ** [comment]
works for me: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/e6abd6b9-8beb-47dc-ae4d-f87eaec843ef)

**Comment by HenryHengZJ** [comment]
maybee you need a higher tier of Render instance. I'd suggest you try running it locally first

**Comment by agnosus** [comment]
Hi Henry
The seems to be a bug when I replace 'Retrieval QA chain' with 'Conversational retrieval QA chain' in the above flow:
![image](https://github.com/FlowiseAI/Flowise/assets/64579856/cc89d745-c9de-44f1-9d3d-df13bcca9c8f)
![image](https://github.com/FlowiseAI/Flowise/assets/64579856/e6281b3a-647b-4f27-8d0c-f1627de6543f)
