### ISSUE TITLE
[FEATURE] Support personal access token (PAT) in ConfluenceLoader

### ISSUE THREAD

**Issue by yoHasse** [FlowiseAI/Flowise#1288]
**Describe the feature you'd like**
We're not able to use the ConfluenceLoader for our server instance.

The current loader requires username + accesstoken. For installations greater than 7.9 you have to use a PAT as a bearer token instead.

**Additional context**
This issue cannot be resolved until the following issue + PR has been completed for langchainjs:
https://github.com/langchain-ai/langchainjs/issues/3408

After that I will make a contribution and PR for this issue.

**Comment by HenryHengZJ** [comment]
@yoHasse let me know if you need any help!

**Comment by yoHasse** [comment]
> @yoHasse let me know if you need any help!

@HenryHengZJ work and family is really hectic right now so I'm not sure when I'll have time for this. If anyone wants to pitch in, I'd appreciate it a lot 😅

I hope to squeeze in a few hours next week (after the holidays) but I can't promise anything as of now. 😥

**Comment by HenryHengZJ** [comment]
PR https://github.com/FlowiseAI/Flowise/pull/1998 merged
