### ISSUE TITLE
[FEATURE] Able to reach to function_call in result

### ISSUE THREAD

**Issue by emrahtoy** [FlowiseAI/Flowise#1292]
As some of the models support functions that result with function_call property in the result, I would like to reach it when I send a request to the Flowise prediction endpoint.

Right now Flowise API responses have JSON format but it only includes the text field. I would like to get function_call in addition on this.

**Comment by emrahtoy** [comment]
FYI: Function call is updated with [tools](https://platform.openai.com/docs/guides/function-calling)
PS: It would be nice to consider [json mode](https://platform.openai.com/docs/guides/text-generation/json-mode)

**Comment by HenryHengZJ** [comment]
@emrahtoy the API response now includes a property `usedTools` which are the tools/functions used by agent:
<img width="631" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/ec6bf2b5-d190-459a-8d81-8a12635a1d9c">

**Comment by emrahtoy** [comment]
Awesome @HenryHengZJ, just in time!
