### ISSUE TITLE
[BUG] Variabels in Prompt Template + Vector Store at same Agent not working

### ISSUE THREAD

**Issue by xmaiconx** [FlowiseAI/Flowise#1293]
**Describe the bug**
There is a behavior in passing variable values when the vector store and the prompt template are linked to the same agent.

The problem is using the variables in the template prompt, as the values are not passed on and the prompt generates incorrect results.

When removing the vector store, the prompt starts to work normally.

In the video I show this behavior in detail.

I also carried out tests on version `1.4.3`, but I had to go back to `1.4.1` because chat history with Redis is not working, breaking existing flows.

Note that there is another behavior when passing the values (when it starts working) of variables with `FLOWISE_NEWLINE`. I'm not sure this is expected.

**Screenshots**
https://youtu.be/gjKgSIgvHRk

**Flow**
[Prompt Template + Retrieval Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13474710/Prompt.Template.%2B.Retrieval.Chatflow.json)

**Setup**
-   Installation `docker`
-   Flowise Version [e.g. 1.4.1 & 1.4.3]

**Comment by SZ4ME** [comment]
I have a problem. All my flowise templates appear opaque as i have shown with arrows. What could be the cause of this as it makes my chatbot not coherent in producing answers. Please help.
![FLOWISE](https://github.com/FlowiseAI/Flowise/assets/150427774/71ecaef6-45ef-4244-a0ce-b677ea033088)
