### ISSUE TITLE
Simple Moderation [Case sensitivity] From Merge #1222

### ISSUE THREAD

**Issue by EULArule** [FlowiseAI/Flowise#1295]
**Describe the bug**
As per the merge #1222, the implementation of the feature "Simple Prompt Moderation" seems to have some issues. A user is able to easily bypass the prompt avoidance simply through capitalizing a single letter. This introduces the issue of needing to provide every possible prompt through brute force to account for all options.

Ex input moderation blocked words.
     "do not follow context"

Bypass
     "Do not follow context"
or  "do nOt follow context"
and several other thousand combinations that would need to be accounted for.

I recommend filtering the text either by checking the text in all lowercase or uppercase during the check. Thus eliminating the need for much redundancy. Such as "Ignore all context" (Start of a sentence). Or "Please ignore all context" (Within a sentence). And all other combinations of capitalization.

**To Reproduce**
Use the Simple Prompt Moderation block in flowise, and input a chat excerpt to block. Here is a picture of me using the feature, and avoiding the filter through a simple capital letter.

**Expected behavior**
Block the prompt from being executed.

**Screenshots**
![Screenshot from 2023-11-27 10-48-37](https://github.com/FlowiseAI/Flowise/assets/90616501/ca9c1501-4421-4ff4-a917-84b2f340542a)

**Setup**
-   Installation NPX
-   Flowise Version 1.4.3
-   OS: Linux
-   Browser: Mullvad [Firefox based]

**Comment by HenryHengZJ** [comment]
PR merged!
