### ISSUE TITLE
[FEATURE] GPT 4 turbo models in ChatOpenAi node

### ISSUE THREAD

**Issue by AdamSGit** [FlowiseAI/Flowise#1299]
I noticed that the following openai models are missing from the `ChatOpenAi.ts` node : 

- `gpt-4-1106-preview`
- `gpt-4-vision-preview`

Do you want me to make a PR for that ?

**Comment by emrahtoy** [comment]
As I have been using the most recent version by pulling via git this may still be an issue for you but I do have the right model list in the ChatOpenAI Node. @AdamSGit 

![image](https://github.com/FlowiseAI/Flowise/assets/4387637/42cd806d-1d81-4319-8b97-fb450bcad601)

**Comment by adolfousier** [comment]
> As I have been using the most recent version by pulling via git this may still be an issue for you but I do have the right model list in the ChatOpenAI Node. @AdamSGit 
> 
> 
> 
> ![image](https://github.com/FlowiseAI/Flowise/assets/4387637/42cd806d-1d81-4319-8b97-fb450bcad601)
> 
> 

How can I pull it from the git to my repo? Thank you

**Comment by emrahtoy** [comment]
I assume you have forked the FlowiseAI/Flowise repository. In this case, you should see something like the image below on the top of your own repository;
![image](https://github.com/FlowiseAI/Flowise/assets/4387637/036534e5-7838-4eac-805b-e5899ef9166a)
"Sync Fork" will do the job. @adolfousier
