### ISSUE TITLE
User ID

### ISSUE THREAD

**Issue by petertoner** [FlowiseAI/Flowise#130]
I don't see the opportunity to identify a user. I will want multiple users to access my flow.

Is it currently possible? If not can the function be added?

**Comment by HenryHengZJ** [comment]
Currently there isnt a way to identify user. You'll have to implement the logic on your front end

**Comment by petertoner** [comment]
Hey Henry, I’m a non-program l, would you be so kind as to give me some clues to how to do this at least inside Flowise.

Thank you!

Peter.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HenryHengZJ** [comment]
hey Peter, unfortunately this isn't possible on Flowise right now. We'll see if we can accommodate this request down the line and hopefully some tutorials for that
