### ISSUE TITLE
[BUG] Missing escape character in CURL example

### ISSUE THREAD

**Issue by tcpxenos** [FlowiseAI/Flowise#131]
**Describe the bug**
The example CURL code is missing a backslash to escape the newline

**To Reproduce**
Open the API Endpoint dialog, open the CURL tab, and choose an API key

**Screenshots**
Example output, missing a backslash after `how are you?"}'`
```
curl http://myip:3000/api/v1/prediction/myendpoint \
     -X POST \
     -d '{"question": "Hey, how are you?"}'
     -H "Authorization: Bearer myapikey"
```

**Setup**

-   OS: Docker on Debian
-   Browser: Chrome

**Comment by Pathholder1806** [comment]
Hey @tcpxenos I would like to contribute to this issue!
