### ISSUE TITLE
[BUG] Space on first word in Embedded Chat

### ISSUE THREAD

**Issue by jeffh86** [FlowiseAI/Flowise#1313]
See attached image.

The first word for the chatbot answers is always indented (there is a space). Has this been seen before? Do you know how I would fix it?

Thanks for all the great work!
![Screenshot 2023-11-29 172316](https://github.com/FlowiseAI/Flowise/assets/142155913/c024d930-76c9-4344-8ba0-57c0d6a7b677)

**Comment by HenryHengZJ** [comment]
resolved:
<img width="1268" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/5ffcacc2-c414-47db-869c-7cd050afab41">
