### ISSUE TITLE
Refresh bar is stuck at the top of the screen when using a fullpage react embedment[BUG]

### ISSUE THREAD

**Issue by jacklion710** [FlowiseAI/Flowise#1314]
**Describe the bug**
When using the FullPageChat component in a Next.js environment there is a consistent blue bar with the refresh button stuck to the top of my window. 

**To Reproduce**

1. in chatflow go to 'api endpoint'
2. Click on embed>Fullpage React and copy the code
3. Paste the code in the JSX block of a react component and import+install flowise-embed and flowise-embed-react
4. See the blue bar stuck at the top

**Expected behavior**
I would expect it to appear above the chat box and not be detached at the top of the window. At the very least it should be able to be hidden from the UI or moved.

**Flow**
I'm using a simple OpenAI assistant with a Fullpage React embedment
![Screenshot 2023-11-29 at 3 44 20 PM](https://github.com/FlowiseAI/Flowise/assets/104385151/64a24c43-4b5e-4bef-817a-34a9cd042174)

**Comment by jacklion710** [comment]
> The top bar is allow users to refresh the session (top right button). You can customize it via configuration: `title` and `titleAvatarSrc`: https://github.com/FlowiseAI/FlowiseChatEmbed#configuration

is it possible to suppress it entirely? It doesn't look good on my web page and is not necessary for my goal

**Comment by HenryHengZJ** [comment]
unfortunately not, if supress it, there is no way to refresh and clear the chat messages

**Comment by jacklion710** [comment]
> unfortunately not, if supress it, there is no way to refresh and clear the chat messages

I understand the purpose of the refresh bar for clearing chat messages, but in my case, refreshing the page would serve the same purpose. The issue is that the bar's fixed position at the top of the screen, regardless of scrolling, clashes with my frontend design. Ideally, the bar should be integrated with the chat box, not separate from it. Is there any way to modify its position so it aligns better with my page layout? My JSX block suggests that even floating elements should align between my navbar and footer components. The inability to customize this aspect of the FullPageChat component is quite limiting, especially since it affects the overall aesthetic of my webpage. Any guidance on how to resolve this would be greatly appreciated.

**Comment by HenryHengZJ** [comment]
ah okay got it, some of the users were having the same issue as well with full page chatbot, will take a look at it

**Comment by jacklion710** [comment]
> ah okay got it, some of the users were having the same issue as well with full page chatbot, will take a look at it

Much appreciated. Please keep me posted and if you require steps or code to recreate the issue I am happy to provide that.

**Comment by jacklion710** [comment]
Hi, just wanted to follow up on this thread. Any updates?

**Comment by 0xi4o** [comment]
Fixed in https://github.com/FlowiseAI/FlowiseChatEmbed/pull/74
