### ISSUE TITLE
How can i use returned value from custom tool in OPENAI Function Agents System Message, Thank you so much in Advance.🙏🏼

### ISSUE THREAD

**Issue by xmi1an** [FlowiseAI/Flowise#1318]
I have a custom tool that generate a random word, and i want that random word in system message, how can i archive that?

Here is image of what i want.

Thank you so much in Advance.

![image](https://github.com/FlowiseAI/Flowise/assets/8353799/c98cf93a-3e34-4b97-b3bf-66e5db93fa0a)

**Comment by HenryHengZJ** [comment]
unfortunately its not possible for now to have variables inside system message
