### ISSUE TITLE
[BUG] Plugin API Key

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#132]
**Describe the bug**
Chat bot ignores plugins or have an issue locating API Key for plugin

Error: Failed to fetch API spec from https://webreader.webpilotai.com/openapi.yaml with status 403
May 20 01:49:25 AM      at AIPluginTool.fromPluginUrl (/opt/render/project/src/node_modules/langchain/dist/tools/aiplugin.cjs:48:19)
May 20 01:49:25 AM      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
May 20 01:49:25 AM      at async AIPlugin.init (/opt/render/project/src/packages/components/dist/nodes/tools/AIPlugin/AIPlugin.js:25:26)
May 20 01:49:25 AM      at async buildLangchain (/opt/render/project/src/packages/server/dist/utils/index.js:208:50)
May 20 01:49:25 AM      at async App.processPrediction (/opt/render/project/src/packages/server/dist/index.js:414:40)
May 20 01:49:25 AM      at async /opt/render/project/src/packages/server/dist/index.js:263:13 

**To Reproduce**

1. Set the plugin url
2. Test chat app

**Expected behavior**
I expect the chat agent to use the plugin. However, it either ignores the plugin or attempts to find the API key for the plugin. There's no where to enter API Key.

**Setup**

-   OS: [Mac M1]
-   Browser [Chrome]

**Comment by HenryHengZJ** [comment]
hey thanks for the bug! We'll add a `headers` field for you to enter the headers like `{Authorization: Bearer ...}` for the `RequestsGet` and `RequestsPost` tools

**Comment by WizKid1968** [comment]
Awesome, I look forward to it, thanks!

**Comment by HenryHengZJ** [comment]
Now you can configure Url, Description, Headers for GET and POST tools 🎉
Simply re-sync your fork.

![RequestTools](https://github.com/FlowiseAI/Flowise/assets/26460777/e87e352a-e997-4291-95d2-ee0e9c0f9ca7)
