### ISSUE TITLE
[BUG] Chatflows dashboard raises warnings in the browser javascript console

### ISSUE THREAD

**Issue by vinodkiran** [FlowiseAI/Flowise#1332]
**Describe the bug**
The new list view on the dashboard raises warnings in the javascript console

**To Reproduce**

1. Enable Developer tools 
2. Open Console from the tools to view browser console
3. Open Flowise Dashboard
4. See warning in the console

**Expected behavior**
No Errors/ Warnings to be seen.

**Screenshots**

<img width="1498" alt="Screenshot 2023-12-04 at 10 38 02" src="https://github.com/FlowiseAI/Flowise/assets/842544/2799ec2a-582b-4d49-8938-3f16705cbfe5">

**Comment by takuabonn** [comment]
hi @vinodkiran 
I want to work in this issue. will u assign it to me?

**Comment by takuabonn** [comment]
hi @vinodkiran 

Fix is complete.
please confirm below pull request.  🙇
[#1334](https://github.com/FlowiseAI/Flowise/pull/1334)
