### ISSUE TITLE
[BUG] Request failed with status code 429

### ISSUE THREAD

**Issue by AtanasD** [FlowiseAI/Flowise#134]
Description
when trying to run website QnA example and I get "Request failed with status code 429"

To Reproduce
-open example
-input text
-get error

}
[llm/error] [1:chain:agent_executor > 2:chain:llm_chain > 3:llm:openai] [113.11s] LLM run errored with error: "Request failed with status code 429"
[chain/error] [1:chain:agent_executor > 2:chain:llm_chain] [113.11s] Chain run errored with error: "Request failed with status code 429"
[chain/error] [1:chain:agent_executor] [113.11s] Chain run errored with error: "Request failed with status code 429"

`
Expected
receive answer from openai api

Screenshot
<img width="822" alt="2023-05-20 10_24_30-Flowise - LangchainJS UI" src="https://github.com/FlowiseAI/Flowise/assets/15182897/87165507-c17c-45b5-8d1f-4524b0bf219b">

Setup
-   Win10 LTSC
-   Chrome

**Comment by HenryHengZJ** [comment]
99% of the time when we see 429, its OpenAI API key related. Try creating a new key, make sure its not expired etc

**Comment by awatt12** [comment]
I am getting rate limited with the API call for Flowise but when I use the flow builder, I do not get wait limited. Is there a reason why?

**Comment by chungyau97** [comment]
Hi @awatt12, flow builder chat ui does not have rate limit for testing purposes.

**Comment by awatt12** [comment]
Is the api call rate limited? On Nov 20, 2023, at 12:40 AM, Ong Chung Yau ***@***.***> wrote:﻿
Hi @awatt12, flow builder chat ui does not have rate limit for testing purposes.
