### ISSUE TITLE
[BUG] Fail to execute model for flow_id: 002_stablegemini_m_8k_disagg 

### ISSUE THREAD

**Issue by kientv** [FlowiseAI/Flowise#1349]
Seem that gemini model is error:   
![image](https://github.com/FlowiseAI/Flowise/assets/3217438/18d698d5-867e-4cdf-b422-89b345b71a17)

**Comment by HenryHengZJ** [comment]
do we have gemini API already?

**Comment by kientv** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/3217438/555a9033-7098-44fb-a025-18d17471aa18)

**Comment by HenryHengZJ** [comment]
added new gemini integration - https://github.com/FlowiseAI/Flowise/pull/1396
