### ISSUE TITLE
Discussion on Prettier Configuration - Semicolon Usage

### ISSUE THREAD

**Issue by gokuljs** [FlowiseAI/Flowise#1355]
### Description
This section aims to discuss our project's Prettier configuration, focusing on the `semi` property. This setting determines whether to automatically insert semicolons at the end of statements.

### Current Configuration
Our current Prettier configuration is as follows:

```json
{
    "printWidth": 140,
    "singleQuote": true,
    "jsxSingleQuote": true,
    "trailingComma": "none",
    "tabWidth": 4,
    "semi": false,
    "endOfLine": "auto"
}
```

### Discussion Point

The semi: false setting in our configuration opts out of automatic semicolon insertion. While JavaScript's automatic semicolon insertion is capable, there are arguments for explicit semicolon usage in JavaScript development for clarity and error prevention.

#### Cons

Avoids potential pitfalls associated with JavaScript's automatic semicolon insertion
Provides clearer statement endings, potentially improving readability
Aligns with traditional JavaScript best practices

### Suggested Action
I propose we have a discussion about whether we should keep the current setting (semi: false) or switch to semi: true.

**Comment by gokuljs** [comment]
#1356

**Comment by gokuljs** [comment]
#1357

**Comment by HenryHengZJ** [comment]
I personallly don't like having semicolon, as its cleaner, unless it brings huge benefit

**Comment by gokuljs** [comment]
In the above pr I have already made all the changes and integrated a Husky pre-commit for the same purpose. I will test everything shortly and inform you of the results.
