### ISSUE TITLE
SQL Database Chain and MSSQL self-signed certificate

### ISSUE THREAD

**Issue by ansutung** [FlowiseAI/Flowise#1364]
Hello everyone, I need assistance configuring the SQL Server connection in the network through the "SQL Database Chain". My connection string is as follows:

```
mssql://utest:mypw@192.168.10.11:1433/DBName1?trustServerCertificate=true
```

However, I always encounter the error:

```
Failed to connect to 192.168.10.11:1433 - self-signed certificate
```

**Comment by JeffCristine** [comment]
I had the same problem and posted my question here: https://github.com/FlowiseAI/Flowise/discussions/848  Seems like a simple add - can someone point me to the SQL interface code so maybe I can change it and do some local testing with MS-SQL dev databases (no SSL cert on the dev DBs)?

**Comment by HenryHengZJ** [comment]
> I had the same problem and posted my question here: #848 Seems like a simple add - can someone point me to the SQL interface code so maybe I can change it and do some local testing with MS-SQL dev databases (no SSL cert on the dev DBs)?

this is where the connection configuration is made - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts#L193

We recently also added a new node - Custom JS Function which you can connect to your database without UI restriction from Flowise: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/0af3294c-e498-47db-9031-d3779773e23f)
