### ISSUE TITLE
Langsmith stopped working after updating to flowise 1.4.5 [BUG]

### ISSUE THREAD

**Issue by agerskov** [FlowiseAI/Flowise#1384]
**Describe the bug**
Langsmith stopped working after updating to flowise 1.4.5

**To Reproduce**

1. create chatflow add langsmith 
2. chat with it
3. no entry on langsmith

**Expected behavior**
1. create chatflow add langsmith 
2. chat with it
3. entry on langsmith

**Screenshots**
multiple entries before i updated
![image](https://github.com/FlowiseAI/Flowise/assets/1219711/1ec368db-fd8c-4d07-ba32-9124d1181d26)

**Comment by HenryHengZJ** [comment]
Langsmith is experiencing degraded performance at the moment:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/4727f948-3b39-4d9f-a09a-91ba2fded6e4)

**Comment by HenryHengZJ** [comment]
verified working correctly
