### ISSUE TITLE
[FEATURE] Retriever not favouring different source files

### ISSUE THREAD

**Issue by robertofabrizi** [FlowiseAI/Flowise#1393]
**Describe the feature you'd like**
I'd like to talk to my codebase but I can't seem to find out how to get multiple results from the same file. In this example I've injested the java classes of the Play Framework github repo (web subfolder) into a Pinecone DB. When I ask it broader questions like what's the relationship between two classes it works, but when I ask it specific questions regarding a single file it doesn't, for example there are 14 constructors in the Form class, but in no test I managed to get the right answer back

**Additional context**
Attached is a screenshot with a mix of tests that I've done
<img width="1467" alt="Screenshot 2023-12-14 165125" src="https://github.com/FlowiseAI/Flowise/assets/6720929/719add99-b5fc-4149-9645-4bbd477c37b2">

**Comment by HenryHengZJ** [comment]
we are revamping Conversational Retrieval QA Chain, which allow much more customization to be done.
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/0a05771d-481f-4296-9af8-2809d41e9bd5)

For example, you can modify the Response Prompt to be something like: `You are a world class engineer, an expert programmer and problem-solver, tasked to answer any question about XXXX. Using the provided context, answer the user's question to the best of your ability using the resources provided.`
