### ISSUE TITLE
[FEATURE] Support for TogetherAI

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#1400]
Add support for TogetherAI under LLM nodes - https://js.langchain.com/docs/integrations/llms/togetherai

- Must have access to API to test it out
- Must enable streaming mode - https://js.langchain.com/docs/integrations/llms/togetherai#streaming

**Comment by jiabaow** [comment]
I can work on this.

**Comment by HenryHengZJ** [comment]
Thanks! We have the integration in already, shouldve close this issue

**Comment by jiabaow** [comment]
I see chatmodels/ChatTogetherAI and embeddings/TogetherAIEmbedding, but not llms/TogetherAI, did I miss something?

**Comment by HenryHengZJ** [comment]
Oh yeah we don't have that yet, feel free to add the integration for LLM node
