### ISSUE TITLE
[BUG]Error: Request to Ollama server failed: 500 Internal Server Error（/api/embeddings)

### ISSUE THREAD

**Issue by heoyongun** [FlowiseAI/Flowise#1415]
**Describe the bug**
2023/12/20 - 16:12:41 | 500 |     362.827µs |      172.26.0.2 | POST     "/api/embeddings"

![스크린샷 2023-12-20 16-16-05](https://github.com/FlowiseAI/Flowise/assets/6076067/e8dd7fc5-10f2-4b02-9e90-f2b4b5bf4b2e)

**To Reproduce**

1. Upsert Vector Database Button Click 
2. Error Message Show

**Screenshots**
![스크린샷 2023-12-20 16-21-46](https://github.com/FlowiseAI/Flowise/assets/6076067/4bc3adbe-1f37-4663-bc36-f653cde74772)

**Flow**
If applicable, add exported flow in order to help replicating the problem.
[local llm Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13724251/local.llm.Chatflow.json)

sample.txt file
[sample.txt](https://github.com/FlowiseAI/Flowise/files/13724259/sample.txt)

**Setup**
-   Installation [docker compose]
-   Flowise Version [1.4.5]
-   OS: [Linux ubuntu 22.04LTS ]
-   Browser [chrome]
-   OLLAMA MODEL [mistral]

**Comment by tcpiplab** [comment]
I'm having this exact same problem on Mac OS Sonoma 14.2.1, M2 Pro chip.

```
time=2024-02-03T14:49:52.666-08:00 level=INFO source=dyn_ext_server.go:156 msg="Starting llama main loop"
[GIN] 2024/02/03 - 14:49:52 | 200 |  4.109615916s |       127.0.0.1 | POST     "/api/chat"
[GIN] 2024/02/03 - 14:50:00 | 500 |    1.825666ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/02/03 - 14:50:04 | 500 |    1.303417ms |       127.0.0.1 | POST     "/api/embeddings"
[GIN] 2024/02/03 - 14:50:22 | 500 |      2.0265ms |       127.0.0.1 | POST     "/api/embeddings"
```

But it works fine if I do the POST with `curl`:

```
$ curl http://localhost:11434/api/embeddings -d '{
  "model": "llama2",
  "prompt": "Here is an article about llamas..."
}'
{"embedding":[1.7122478485107422,0.8994832038879395,......
```

So I think this must mean that there is something wrong with the body of the POST being sent by the FlowWise Ollama embeddings widget. 

Thanks.
