### ISSUE TITLE
[BUG]how dose SQLDatabase Chain go when I

### ISSUE THREAD

**Issue by littleKanghui** [FlowiseAI/Flowise#1420]
when I add a include table for sqlDatabase Chain ,it thow [the  do not contains table margin_trading] ,but my database exactily contains this table 
![image](https://github.com/FlowiseAI/Flowise/assets/154517876/a77c2983-19f5-4c31-b910-b5dce06cc566)
![image](https://github.com/FlowiseAI/Flowise/assets/154517876/6c5b1eac-4413-4de1-affa-4b09552318b9)
![image](https://github.com/FlowiseAI/Flowise/assets/154517876/69b94a25-bfbb-4dcd-b94a-b847c3618d7a)

how does it happend? please help me!

**Comment by HenryHengZJ** [comment]
@littleKanghui we released another template - SQL Prompt which allow a more robust way to use your prompt, connect to your databases using custom JS function: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/4afe6e1b-a570-4030-a507-bdfb4b188eb1)

in the meantime, we'll take a look at the `Include Table` issue

**Comment by scheung38** [comment]
@HenryHengZJ this is for MySQL? How to modify this template as I have SQL Server MSSQL

**Comment by scheung38** [comment]
Keen to know why for example a ChatOpenAI node is replicated x3 times here when a single node instance of ChatOpenAI node can fan out to x3 connections?

**Comment by HenryHengZJ** [comment]
> Keen to know why for example a ChatOpenAI node is replicated x3 times here when a single node instance of ChatOpenAI node can fan out to x3 connections?

Flowise traverse the graph from left to right, hence 3 nodes are needed instead of just 1, otherwise it will causes the graph into infinite loop

**Comment by HenryHengZJ** [comment]
> @HenryHengZJ this is for MySQL? How to modify this template as I have SQL Server MSSQL

this is for SingleStore SQL, but its a piece of JS code that is modifiable

**Comment by yangzishy** [comment]
> [@littleKanghui](https://github.com/littleKanghui) we released another template - SQL Prompt which allow a more robust way to use your prompt, connect to your databases using custom JS function: ![image](https://github.com/FlowiseAI/Flowise/assets/26460777/4afe6e1b-a570-4030-a507-bdfb4b188eb1)
> 
> in the meantime, we'll take a look at the `Include Table` issue



Hello,`include Table`  has the problem been resolved?
