### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined[BUG]

### ISSUE THREAD

**Issue by rizwanriaz-se** [FlowiseAI/Flowise#1430]
**Describe the bug**
I am getting undefined when I try to upsert document using ElasticSearch in my chatflow. The same thing works properly with Pinecone. I have attached my chatflow below:
![WhatsApp Image 2023-12-23 at 15 57 16_5e0e6c34](https://github.com/FlowiseAI/Flowise/assets/77151292/0d4ce619-9515-46da-9d73-6e05fc8278d0)
![WhatsApp Image 2023-12-23 at 15 58 00_8cfcc674](https://github.com/FlowiseAI/Flowise/assets/77151292/a196d48c-d039-4733-9314-da572b953836)

**Comment by HenryHengZJ** [comment]
I was able to upsert successfully with the guide - https://docs.flowiseai.com/integrations/vector-stores/elastic

**Comment by iamrizwan077** [comment]
I have just checked the docs, but it shows the one with elastic cloud. I am using the docker one; the credentials I have are host, username, and password. I debugged my issue further and it shows the endpoint parameter is missing, I thought this might be the issue, so tried passing it a default value, and later totally removing that endpoint parameter. But I am still getting the same error. Putting some console log statements show that the Elasticsearch functions: prepareClientArgs, prepareConnectionOptions etc are properly working, and upsert results in error when building langchain..

![image](https://github.com/FlowiseAI/Flowise/assets/77151292/9b684200-0f66-401f-b7c9-aec9f226f89c)

**Comment by iamrizwan077** [comment]
I have debugged further, and it stops at:
```            const cloudUrls = Buffer.from(id.split(':')[1], 'base64').toString().split('$');
               opts.node = `https://${cloudUrls[1]}.${cloudUrls[0]}`;
``` in file: /workspaces/Flowise/node_modules/@elastic/elasticsearch/lib/client.js . 
In opts.node line, I am getting undefined in URL. Then I hard-coded my url here, and got "Error: ConnectionError: self-signed certificate in certificate chain"
