### ISSUE TITLE
[FEATURE] Keeping older messages in the chat and the initial message as reference

### ISSUE THREAD

**Issue by kdhaka94** [FlowiseAI/Flowise#144]
**Describe the feature you'd like**
Having older messages in the chat, and the initial prompt may only be sent at the top of the messages for reference, so that the OPEN-AI API may respond accordingly, as I see right now that it just replaces the text with placeholder which is not viable for each time a user is sending a message, it should only be keeping the context for the first time

**Comment by HenryHengZJ** [comment]
hey im not sure if im following. 

mind clarifying more with logs and screenshots?
