### ISSUE TITLE
[BUG] Regarding API Loader in Documents 

### ISSUE THREAD

**Issue by MirzaAreebBaig** [FlowiseAI/Flowise#1443]
**Describe the bug**
Hello, I have used API Loader in documents now i have 2 issues here
1 - The data which is deleted from the JSON file is still appearing while chatting with the bot
2 - If i create 2 API bots even though they have 2 different data with 2 different links but still both bots have same data

Please advice me how to solve this issue or let me know the best possible way to build bot for such use case

The components i'm using are AWSChatBedrock, API Loader, Conversation Chain & Buffer Memory
Please advice what can be done on this. Thank You :)

**Comment by HenryHengZJ** [comment]
There are few ways to solve this issue.
1. Use Conversational Retrieval method (you can refer to several templates in marketplace) and upsert to a vector database. Specify filter or namespace/collection to seperate data for upserting. You can then later query it by using the same filter/namespace/collection.
2. Use [long term memory](https://docs.flowiseai.com/integrations/memory/long-term-memory) to separate sessions between users, using buffer memory will allow user1 to share the same memory as user2

**Comment by MirzaAreebBaig** [comment]
Hey,
Thank you for your reply.

As per your suggestion i have implemented the long term memory & The issue had solved.
Thank You.
