### ISSUE TITLE
[BUG] Use Notion Database, AggregateError

### ISSUE THREAD

**Issue by heoyongun** [FlowiseAI/Flowise#1446]
2023-12-29 05:46:08 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/ba37fc5a-f7e0-49b7-b044-35e77ceaf8f8

2023-12-29 05:46:08 [ERROR]: [server]: Error: AggregateError

![스크린샷 2023-12-29 14-48-51](https://github.com/FlowiseAI/Flowise/assets/6076067/f9db4606-2a33-48b1-b38a-06edf98bac98)

**To Reproduce**

1.Upsert Vector Database Button Click
2. Error Message Show

**Screenshots**
![스크린샷 2023-12-29 14-51-44](https://github.com/FlowiseAI/Flowise/assets/6076067/b9489b5f-7793-4549-932b-08c89d65a8fa)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

[notion test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13791217/notion.test.Chatflow.json)

**Setup**
- Installation [docker compose]
- Flowise Version [1.4.5]
- OS: [Linux ubuntu 22.04LTS ]
- Browser [chrome]
- OPENAI MODEL [GPT3.5]

**Comment by vinodkiran** [comment]
I was able to replicate and fix this issue.

Try the following::

1) ensure that the NotionDB component Node has only the DatabaseID (not the URL)
2) ensure that the DB has permissions for the integration :: https://developers.notion.com/docs/create-a-notion-integration#give-your-integration-page-permissions 

I was able to upsert successfully.
