### ISSUE TITLE
[BUG] - Pinecone upsert creates multiple identical records

### ISSUE THREAD

**Issue by niztal** [FlowiseAI/Flowise#1458]
**Describe the bug**

When trying to run upsert over pinceone vector store (could be reproducible for other vector stores, I personally didn't try that),
It creates the same vectors over and over again, while my expectation it will run "upsert" - meaning only the changes(delta) would get insert.

**To Reproduce**

1. Go to chatflow which includes pincecone vector store
2. Click on "Upsert button" (the green DB at the top right next to the chat window) 
![image](https://github.com/FlowiseAI/Flowise/assets/19833797/2aba3288-282b-476b-a562-c70148500e16)

3. Click Upsert
![image](https://github.com/FlowiseAI/Flowise/assets/19833797/444bb7f9-d1c3-4f7b-887a-e3156bedd486)

4. Run this flow (1-3) few times

**Expected behavior**
Go to the pinceone console, open your index and watch the "Vectors count" no. it is expected it will remain on X "Vector count"

![image](https://github.com/FlowiseAI/Flowise/assets/19833797/4b031c16-dae4-4fc5-b71b-1cb78114b528)

**Setup**
-   Flowise Version  1.4.8

I saw over the issues this issue (https://github.com/FlowiseAI/Flowise/issues/930) which was closed but the solution is not clear, even when I'm not changing anything on the canva nor on the files I'm ingesting into pinecone, the issue still occurs

Not sure if it's relevant I'm using openai model 4-1106-preview

Thanks

**Comment by HenryHengZJ** [comment]
You are right. We still don't yet implement a solution to just upsert the `delta` changes, everything will be re-upsert again. This is the area we need to improve. Was thinking of cache the vector embeddings to user local file, and compare the new embeddings to the cached embeddings, and upsert the new ones

**Comment by niztal** [comment]
@HenryHengZJ 

Thank you very much for the honest response,

Do you have any estimation for the fix you were proposing?

**Comment by HenryHengZJ** [comment]
we are using the upsert API under the hood via langchain abstraction. however the ids are different each time you upsert, that causes duplication.

dont have any estimation, but its one of the higher priority item we are taking a look at

**Comment by niztal** [comment]
Thanks for your honesty @HenryHengZJ 

One last question please

Untill you'll fix this issue, if I'll reinsert the same vectors over and over again, is that something which may effect the performance or the accuracy of my bot?

Thanks

**Comment by niztal** [comment]
seems like it is a very hard task to achieve, I recommend not using upsert, but rather do delete all documents and re-insert these. @HenryHengZJ

**Comment by e-lobo** [comment]
so`upsert` cannot be used? im also noticing duplicates in my vector store. @HenryHengZJ your solution to use redis did not work

**Comment by dentro-innovation** [comment]
Guys I'm using a record manager to not have duplicates, works like a charm!

**Comment by niztal** [comment]
> Guys I'm using a record manager to not have duplicates, works like a charm!

@dentro-innovation can you elaborate further? Wdym record manager?

**Comment by dentro-innovation** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/135163019/6bc9bf0b-01be-4248-993e-96dfc0551674)

just open your Flowise instance and look for it

**Comment by niztal** [comment]
> ![image](https://private-user-images.githubusercontent.com/135163019/340386723-6bc9bf0b-01be-4248-993e-96dfc0551674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDcwNjAsIm5iZiI6MTcxODY0Njc2MCwicGF0aCI6Ii8xMzUxNjMwMTkvMzQwMzg2NzIzLTZiYzliZjBiLTAxYmUtNDI0OC05OTNlLTk2ZGZjMDU1MTY3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNzUyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNWI3YTk5ZjkwZDAzZDgzMDg1MjQ4Yzc5OTRmZWI0Y2Y4YWU2OGVjYTMyYmRjZThiYjQzYzJlYTliOGZjNmM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ueosFMrFonMnMaS_AizbUX_zvBlhJMyT6n4OBetfVDQ)
> 
> just open your Flowise instance and look for it

I wasn't aware of such capability, thanks
