### ISSUE TITLE
[FEATURE]: Enable Custom tool to use Streaming 

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#1463]
**Describe the feature you'd like**

Sometimes we create custom tool to get responses from another Flowise chatflow. Custom tool currently does not support streaming hence final response would look slow. i assume enable streaming at custom tool level would enhance things here.

**Comment by HenryHengZJ** [comment]
on a closer look, tools are not responsible for streaming, chains/agents are. Closing this for now
