### ISSUE TITLE
[BUG] 502 Server Error - Long Running Chat Flow Causes Chat Session to Terminate Early

### ISSUE THREAD

**Issue by dkindlund** [FlowiseAI/Flowise#1468]
**Describe the bug**
When constructing a long-running chat flow, the chat window appears to timeout early and yield this error always:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

Is there any way to instruct the chat window to WAIT LONGER before throwing some sort of timeout error?

**To Reproduce**

1. Build a complicated chat flow that takes longer than 30 seconds to fully complete.
2. Submit query into chat window.
3. See 502 Server Errors

**Expected behavior**
Is there any way to override the 30 second timeout for the chat window per input?

**Screenshots**
<img width="613" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/85660/971ffa49-d858-4bf3-9c7e-13e6fa66e691">

**Comment by dkindlund** [comment]
To reproduce this issue further, use the attached `test-delay-v1 Chatflow.json` as a template:
[test-delay-v1 Chatflow.json](https://github.com/FlowiseAI/Flowise/files/13823733/test-delay-v1.Chatflow.json)

Specifically, the `Custom Tool` is named `wait_for_num_seconds` and has this structure:
![image](https://github.com/FlowiseAI/Flowise/assets/85660/40af274a-56fc-4041-942a-0e0c44706a0a)

I've attached the `wait_for_num_seconds-CustomTool.json` file here:
[wait_for_num_seconds-CustomTool.json](https://github.com/FlowiseAI/Flowise/files/13823741/wait_for_num_seconds-CustomTool.json)

Essentially, the core tool code looks like this:
```
/*
* Must return a string value at the end of function
*/

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

try {
    await sleep($seconds * 1000);
    return 'Slept after ' + $seconds + ' seconds';
} catch (error) {
    console.error(error);
    return '';
}
```

And the System Message for the Agent looks like this:
```
You are an AI assistant that echos back all user input.  But before you echo back to the user, you call the wait_for_num_seconds tool to delay your output by 30 seconds.
```

**Comment by dkindlund** [comment]
If I change the System Message to only sleep for 1 second like:
```
You are an AI assistant that echos back all user input.  But before you echo back to the user, you call the wait_for_num_seconds tool to delay your output by 1 seconds.
```

Then, I see that the chat UI works *correctly*:
Initial input w/ sleep starting...
![image](https://github.com/FlowiseAI/Flowise/assets/85660/3efa9a9b-153a-4e76-8585-ec850cae8687)

Then, after 1 second, the bot response updates...
![image](https://github.com/FlowiseAI/Flowise/assets/85660/412f8086-ffc3-41c9-be3e-14ac4fa88fcc)

**Comment by dkindlund** [comment]
If I change it to 2 seconds, it also works correctly:

Sleep starting...
![image](https://github.com/FlowiseAI/Flowise/assets/85660/0f0a341d-62c8-401f-b94a-1856bc114b33)

Then completion after 2 seconds:
![image](https://github.com/FlowiseAI/Flowise/assets/85660/5a914e2e-27a1-489b-9351-8d63d8d036f7)

**Comment by dkindlund** [comment]
If I change it to 20 seconds, 

Sleep starting...
![image](https://github.com/FlowiseAI/Flowise/assets/85660/e3f44874-c96f-4df9-a957-4eef302dcd7f)

No update in the UI:
![image](https://github.com/FlowiseAI/Flowise/assets/85660/f3625f3a-ba8e-4f4b-bf2a-acb1dec47b0d)

If I close the chat window and reopen it again, I see it refreshed:
![image](https://github.com/FlowiseAI/Flowise/assets/85660/bccd7618-ee3b-47e5-b081-947b42b38581)

**Comment by dkindlund** [comment]
If I change it to 30 seconds, this is what I see:

Sleep starting...
![image](https://github.com/FlowiseAI/Flowise/assets/85660/ae9147fa-fd54-4092-952c-2ec2bc2b0030)

Then failure:
![image](https://github.com/FlowiseAI/Flowise/assets/85660/0b0cddec-63f5-45e8-8070-c9abde59dd33)

**Comment by dkindlund** [comment]
It seems like the `OpenAI Function Agent` was never really built for streaming outputs while tools run more than about 1 second of total execution.  I'm not really sure how to fix this.  I tried turning OFF streaming altogether within the `AzureChatOpenAI` node, but that really didn't solve anything.

If anyone has ideas on how to fix this, I'd sincerely appreciate it!

**Comment by Jaredude** [comment]
Are you using nginx? I had a similar problem. It defaults to a 30 second timeout on read and send. I updated the nginx config proxy_read_timeout and proxy_send_timeout both to 300 (5 minutes) and haven't had any problems with streams or API calls taking 2+ minutes.

**Comment by dkindlund** [comment]
Hey @Jaredude, I'm running the Kubernetes workload inside GCP on Autopilot.  GCP *might* use nginx internally, but I'm not 100% sure.  Do you happen to know the proxy configuration settings for GCP?  I assume this setting might be something I need to set in like an `ingress.yaml` file, perhaps?

**Comment by Jaredude** [comment]
I haven't done much with Kubernetes, but it seems like it should be possible: https://cloud.google.com/endpoints/docs/openapi/custom-nginx

**Comment by dkindlund** [comment]
Thanks, @Jaredude!  I think you helped me figure out the issue.  It was a 30 second timeout assigned to the proxy by GCP.  In order to fix this issue, I had to make the following changes to my YAML files:

Note: To set the timeout to be 10 minutes (for example) -- we specify 600 seconds below.

1) Create a `backendconfig.yaml` file with the following content:
```
    apiVersion: cloud.google.com/v1
    kind: BackendConfig
    metadata:
      name: flowise-backendconfig
      namespace: your-namespace
    spec:
      timeoutSec: 600
 ```

2) Issue:
```kubectl apply -f backendconfig.yaml```

3) Update your `service.yaml` file with the following reference to the `BackendConfig`:
```
    apiVersion: v1
    kind: Service
    metadata:
      annotations:
        cloud.google.com/backend-config: '{"default": "flowise-backendconfig"}'
      name: flowise-service
      namespace: your-namespace
    ...
 ```

4) Issue:
```kubectl apply -f service.yaml```

^ @HenryHengZJ , you may want to update your GCP deployment guide to include these caveats:
https://docs.flowiseai.com/configuration/deployment/gcp

**Comment by HenryHengZJ** [comment]
thanks @dkindlund @Jaredude ! will update the docs
