### ISSUE TITLE
I can not create only embeddings bot

### ISSUE THREAD

**Issue by calseus** [FlowiseAI/Flowise#1472]
I want to crate a bot that when user ask a question bot will show related texts which embedded. But there is no such an option. Bot force me to create a chatbot

**Comment by Jaredude** [comment]
Are you saying you want to have a flow where you pass the question to the flow and the flow creates an embedding and returns the embedding array value as it's answer?

**Comment by calseus** [comment]
Yes. When i ask a question i can see the embeddings. But it has to be a chat flow. But i want to ask a question or give a sample text etc and see the related texts with embedding

**Comment by Jaredude** [comment]
I don't think there's a combination of nodes that would make that happen out of the box. One thing you could do is use a custom tool that calls whatever embedding API you're wanting to use and return the embedding array from the Custom Tool that would then return the embedding array to the Agent that would use a Structured Output Parser to return the original question and the response from the Custom tool.
