### ISSUE TITLE
[BUG] Error executing tool ToolInputParsingException [Error]: Received tool input did not match expected schema

### ISSUE THREAD

**Issue by manoj-lk-code** [FlowiseAI/Flowise#1478]
As the title says, I don't know if this is limited to my instance, but I have a particular issue with the OpenAI Assistant and custom tools steps.

I have a total of three custom tools that I configured with the correct name, parameters, and JavaScript to send the data to the webhook URL. When the Assistant initiates the function calling, I get the error below, which I am trying to figure out to see how I can solve it.

Does anybody know how to solve this?

![image_2024-01-04_145047270](https://github.com/FlowiseAI/Flowise/assets/81701675/96d1d194-b294-4bcf-a167-36c81ef8cbe9)

I have attached the error log screenshot. 

![image](https://github.com/FlowiseAI/Flowise/assets/81701675/b2c58d89-ee19-4c34-9252-e73126b68718)

**Comment by HenryHengZJ** [comment]
this is not an instance issue, its custom tool. OpenAI Assistant does not givee the correct input arguments to the custom tool, hence causing the error. If you use OpenAI Function Agent, do you face the same problem?
