### ISSUE TITLE
Request Timed Out [BUG]

### ISSUE THREAD

**Issue by Digital-Thor** [FlowiseAI/Flowise#1484]
**Describe the bug**
Chat box instantly responds with "Request Timed Out"

**To Reproduce**
1. Installed Flowise using the Docker instructions from Flowise Github page.  
2. Loaded the Translator flow from the Marketplace tab
3. Loaded the OpenAI credentials key name and value in credentials and set in ChatOpenAI node
4. Saved Flow
5. Started the chat window
6. Entered text to translate in chat window
7. Got "Request Timed Out"
8. Browser debugger console says :
```
:3000/api/v1/internal-prediction/c302....89cd:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Expected behavior**
Text translated to French (default set in flow)

**Flow**
Standard Language Translator flow from Marketplace

**Setup**
-   Installation: Docker
-   Flowise Version: 1.4.8
-   OS: Windows 11
-   Browser: Bug occurring in both Chrome and Brave

**Additional context**

**Comment by HenryHengZJ** [comment]
Might be related to your local proxy setup?

**Comment by Digital-Thor** [comment]
> Might be related to your local proxy setup?

Thanks.  Possibly.  I loaded the Dev version in Node and things are working now.

**Comment by Digital-Thor** [comment]
Got Dev version working instead.
