### ISSUE TITLE
Ctrl+S = Save

### ISSUE THREAD

**Issue by JBrosDevelopment** [FlowiseAI/Flowise#1490]
# Save
It would be a lot nicer if Ctrl+S would save the current Flow instead of the browser trying to save the page. Thats really it.

**Comment by Aum-Kansara** [comment]
Hi @JBrosDevelopment , I figured out to handle CTRL+S press Event. Just want to know about which function to execute to save Chatflow when CTRL+S is pressed.

**Comment by joshkyh** [comment]
Sorry @JBrosDevelopment, did you figure out how to save the current Flow with Ctrl+S? I think @Aum-Kansara is suggesting we add a listener, but I'm not familiar with front-end code, any chance this can be a feature that comes without client-side modifications?

```
document.addEventListener("keydown", function(event) {
    if (event.ctrlKey && event.key === 's') {
        event.preventDefault();  // Prevent the browser's default save dialog
        saveChatflow();  // Call the function that saves the Chatflow
    }
});

function saveChatflow() {
    // Code to save the Chatflow
    console.log("Chatflow saved!");
}
```

**Comment by JBrosDevelopment** [comment]
Hey @joshkyh, I did not figure out how to do this. I actually closed this issue because it had been 4+ months since I have used Flowise and I don't even remember what the exacts of the issue was. I'm not a Flowise developer and I have no idea about the client-side modifications. Thank you for responding.
