### ISSUE TITLE
DELETE /api/v1/chatmessage/ not working

### ISSUE THREAD

**Issue by younessouilmi** [FlowiseAI/Flowise#1506]
GET /api/v1/chatmessage/{my-chatflowid} returns several hundred messages
DELETE /api/v1/chatmessage/{my-chatflowid}  returns {"raw":[],"affected":0}
a subsequent GET /api/v1/chatmessage/{my-chatflowid} confirms that messages have not been deleted

I am missing something?

**Comment by younessouilmi** [comment]
hi @HenryHengZJ, you seem familiar with issues related to chatmessage endpoint. Any idea why I might be experiencing the above issue?
Thanks in advance

**Comment by HenryHengZJ** [comment]
@younessouilmi thanks for the bug! put up a bugfix
