### ISSUE TITLE
[BUG] Azure Davinci 003

### ISSUE THREAD

**Issue by rajabhupati** [FlowiseAI/Flowise#1507]
**Describe the bug**

**To Reproduce**

1. Go to 'https://youtube.com/watch?v=fn4GCZuiwdk&list=PL4HikwTaYE0HDOuXMm5sU6DH6_ZrHBLSJ&index=3)'
2. Tried to replicate the behaviour
3. See error
400 The completion operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here:
https://go.microsoft.com/fwlink/?linkid=2197993

**Expected behavior**
Ideally I chose text-davinci-003 in Azure Open AI But error says its not working with gpt35 model
**Screenshots**

![image](https://github.com/FlowiseAI/Flowise/assets/18282819/6a38658d-c51a-4bf2-995c-f24f28ee2298)

**Flow**
If applicable, add exported flow in order to help replicating the [problem.](
[LLM Conv chain Chatflow (1).json](https://github.com/FlowiseAI/Flowise/files/13872350/LLM.Conv.chain.Chatflow.1.json)

**Setup**
-   Installation - npx flowise start
-   Flowise- Recent
-   OS: [ macOS]
-   Browser [ chrome]

**Additional context**

**Comment by HenryHengZJ** [comment]
If im not mistaken, davincii model is being deprecated, we will also remove them from Flowise soon, have you tried Azure Chat?
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/9f1edc8d-d60f-4d75-8002-dcf62aad7e06)

**Comment by rajabhupati** [comment]
Azure chat works . We are good to close this
