### ISSUE TITLE
[FEATURE] Please Add support for Google Gemini Pro vision in flowise 

### ISSUE THREAD

**Issue by HakaishinShwet** [FlowiseAI/Flowise#1522]
Devs please add gemini pro vision in flowise so that we can have some fun with it. i have used gemini pro vision of dify.ai selfhosted version, its pretty good and you can see can take reference from there open source if needed but please do add it to complete google gemini package :-)
Thanks for your hardwork devs

**Comment by octopop** [comment]
+1

**Comment by DocSJ1980** [comment]
+1

**Comment by isaiah2004** [comment]
+1

**Comment by amirasaran** [comment]
+1

**Comment by lattebbrook** [comment]
+1
