### ISSUE TITLE
Use the description, rather than the prompt in the Assistant Selection Dialog

### ISSUE THREAD

**Issue by YAYJAY** [FlowiseAI/Flowise#1531]
In the Assistants Page, and in the Assistant Load, and Assistant Selection dropdown selectors the current way to show more detail than the title is to show the prompt. 

My prompts are nearly all very large and the selection process is hard with the scrolling with many of my prompts having the same or very similar text at the beginning paragraphs. 

![image](https://github.com/FlowiseAI/Flowise/assets/3819168/74dbd899-b5ac-48ce-8775-37878406f3b9)

It would be more ideal if the 'description' field was used on the tiles, and in the selection dialogs. This would seem to be a better way for people to identify and select. It would take much less scrolling to get down through a large list of assistants. 

Thank you.

**Comment by HenryHengZJ** [comment]
Welcome PR for changing this, [code](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/agents/OpenAIAssistant/OpenAIAssistant.ts#L87)

**Comment by YAYJAY** [comment]
yay. thank you @HenryHengZJ 
Now onto #1526. pretty please. 
![image](https://github.com/FlowiseAI/Flowise/assets/3819168/41aa4d73-0f2c-44e5-bc82-8e4e2a9dffc4)
