### ISSUE TITLE
Can't Add Credentials

### ISSUE THREAD

**Issue by rizvand** [FlowiseAI/Flowise#1536]
**Description**
Hi, I am experiencing issues adding credentials. I cannot add any credentials; it throws the error `Error: Credential azureOpenAIApi not found.`

**To Reproduce**
1. Go to *Credentials*
2. Click on *Add Credential*

**Screenshots**
<img width="1223" alt="Screenshot 2024-01-16 at 11 33 01" src="https://github.com/FlowiseAI/Flowise/assets/52346702/dbe70b5f-fe13-4477-a01b-b3b41b386f0f">
<img width="505" alt="Screenshot 2024-01-16 at 11 33 53" src="https://github.com/FlowiseAI/Flowise/assets/52346702/fadb5865-fc2c-4d0f-bb34-084231e2995b">
<img width="814" alt="Screenshot 2024-01-16 at 11 34 45" src="https://github.com/FlowiseAI/Flowise/assets/52346702/d467814a-2a16-418d-9d2a-601867bf8d72">
<img width="627" alt="Screenshot 2024-01-16 at 11 33 13" src="https://github.com/FlowiseAI/Flowise/assets/52346702/5e8c526d-b045-4d36-b8b0-bf330090a74e">

**Setup**
-   Installation: Following this [guide](https://docs.flowiseai.com/configuration/deployment/railway)
-   Flowise Version: `1.4.9`
-   Browser: chrome

**Comment by hemant-manwani** [comment]
I am getting a similar issue, the api  `/api/v1/components-credentials` is returning empty array, probably because the data initialization is not completed successfully. May be related to this one  https://github.com/FlowiseAI/Flowise/issues/1538

**Comment by rizvand** [comment]
> I am getting a similar issue, the api `/api/v1/components-credentials` is returning empty array, probably because the data initialization is not completed successfully. May be related to this one #1538

the data initialization error happened to mine as well

**Comment by younessouilmi** [comment]
same here since I've upgraded to the latest commit, I can't access/update existing credentials neither. 
I've tried deploying older commits (from few days back) but still having the same issue.

**Comment by rizvand** [comment]
Hi guys, try locking the `@upstash/redis` version. If I understand correctly, recent updates from `@upstash/redis` may have caused this data initialization error

<img width="1467" alt="Screenshot 2024-01-16 at 16 48 16" src="https://github.com/FlowiseAI/Flowise/assets/52346702/50512c41-7a09-45d7-8b10-84fa8efe9e02">

**Comment by automaton82** [comment]
Yea I'm having the same issue.

**Comment by automaton82** [comment]
Locking `components\package.json' with the screenshot info does fix it:

`"@upstash/redis": "1.22.1",`

Perhaps it should just be locked to there for now until it's fixed.

**Comment by HenryHengZJ** [comment]
yep will push a fix to lock that for now

**Comment by younessouilmi** [comment]
I've just deployed the latest commit (including the Upstash Redis fix)
it has fixed the previously reported error but now I am getting this **new Error: Credentials could not be decrypted.**
I now can add new credentials but can not access existing ones

**Comment by automaton82** [comment]
That's because you didn't store the secret and it created a new one :)

**Comment by younessouilmi** [comment]
> That's because you didn't store the secret and it created a new one :)

well not a big deal, but I am not sure what I should have done :-)
FYI I use a Render Starter instance

**Comment by 0xi4o** [comment]
Fixed in [v1.4.10](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.4.10).
