### ISSUE TITLE
Cannot add OpenAI API Key with ChatOpenAI Node

### ISSUE THREAD

**Issue by ALEXdotAfrica** [FlowiseAI/Flowise#1540]
I am running Flowise 1.49. on Hugging Face with Docker (as per the instructions in the documentation=

I cannot add my Open API Key

When I add the ChatOpenAI Node and select the dropdown "Create New", there is no popup to add the API key and description. 
This error happens on Hugging Face with 1.4.9, however it does not happen on Hugging Face with 1.4.3.

**Comment by ganesh-iyer** [comment]
I think [this bug](https://github.com/FlowiseAI/Flowise/issues/1536) is related to yours.  I'm seeing the same behavior (your post as well as the linked one), on my local npx setup.

**Comment by 0xi4o** [comment]
We just released a patch to fix this issue. Please upgrade to v1.4.10.
