### ISSUE TITLE
[BUG] Error: Cannot read properties of undefined (reading 'activeChatflows')

### ISSUE THREAD

**Issue by LcCompany** [FlowiseAI/Flowise#1541]
Hi,

I get this error when trying to chat with any of my bots:

Cannot read properties of undefined (reading 'activeChatflows') when trying to chat with the bot after merging with the latsest update.

I use docker on Render.com

On server side I see this in my logs: [ERROR]: [server]: Error: Cannot read properties of undefined (reading 'activeChatflows')

Any idea how to fix?

**Comment by frankwengerek** [comment]
Hi,

I get the same error after merging the latest updates.
Server log:
ERROR]: [server]: Error: Cannot read properties of undefined (reading 'activeChatflows')
TypeError: Cannot read properties of undefined (reading 'activeChatflows')

How to fix it?

**Comment by automaton82** [comment]
I also had this error but it was fallout from the redis issue, and fixed via #1544. This should be closed along with the rest.
