### ISSUE TITLE
Cannot Connect Credentials: ChatOpenAI, OpenAI Embedding, Pinecone [BUG]

### ISSUE THREAD

**Issue by amazingnerd** [FlowiseAI/Flowise#1543]
**Describe the bug**
I cannot Connect Credentials: ChatOpenAI, OpenAI Embedding, Pinecone
**To Reproduce**

1. Click on dropbox 'Create New'
2. Nothing happened

**Comment by rizvand** [comment]
I am experiencing the same issue. For a temporary solution, maybe you can try locking the `@upstash/redis` version [see here](https://github.com/FlowiseAI/Flowise/issues/1536#issuecomment-1893402582) or rollback to the previous deployment. Both options worked for me (at least for now).

**Comment by 0xi4o** [comment]
Locking the version was the solution. The new patch (v1.4.10) is out which will fix the issue.
