### ISSUE TITLE
[FEATURE] ConversationalRetrievalQAChain return sourceDocuments with similarityScore

### ISSUE THREAD

**Issue by tomorrowthief** [FlowiseAI/Flowise#1553]
Can ConversationalRetrievalQAChain return sourceDocuments with similarityScore ？ or how to do now？

**Comment by HenryHengZJ** [comment]
You can use Similarity Score Retriever, Cohere Rerank for that: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/97632aa0-7480-4c5b-84a0-5dfb4cb00cfd)
