### ISSUE TITLE
[FEATURE] Additional types for JSON output parser (Structured Output Parser)

### ISSUE THREAD

**Issue by Arun-N** [FlowiseAI/Flowise#1554]
**Describe the feature you'd like**
Currently only **string**, **number** and **boolean** are the available options in Structured Output Parser. It needs the ability to add nested JSON and arrays so that we can make more complex structures. Another alternative approach could be the ability to chain output parsers to achieve the same affect.

**Additional context**
I'm trying to replicate some prompts from our current langchain implementation to Flowise, but it's proving difficult due to output parser lacking the above types. As far as I have tried, currently it's not possible to define some structure like this one:
```json
{"outlines": {"main": "some main text", "sub": ["sub text 1", "sub text 2", "sub text 3"]}, {...}, {...}}
```

**Comment by HenryHengZJ** [comment]
yeah we'll have to add support to those types

**Comment by HenryHengZJ** [comment]
merged a PR which allow user to specify their own output parser schema - https://github.com/FlowiseAI/Flowise/pull/1672
