### ISSUE TITLE
[BUG] Replit Setup

### ISSUE THREAD

**Issue by HermesMacedo** [FlowiseAI/Flowise#1564]
Flowise has an error after updating.

When trying to add the credential it simply fails to create it. and generates a new docker.

It is not storing the credentials correctly.

![error-credenci](https://github.com/FlowiseAI/Flowise/assets/3227749/75aa1672-4cf0-4be0-a8db-8aa5775c46a6)

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.4.10]
-   OS: [Windows 11]
-   Browser [chrome]

**Comment by HenryHengZJ** [comment]
Not sure whats causing it.
But a workaround is to specify this var `FLOWISE_SECRETKEY_OVERWRITE` in your `.env` file inside docker folder of Flowise project. 
Then make sure your `docker-compose.yml` has the variable as well
