### ISSUE TITLE
Uploading knowledge base to Flowise using another application

### ISSUE THREAD

**Issue by golytics** [FlowiseAI/Flowise#1571]
Good day for everyone and thanks for your contribution.

I have a question. I am thinking to upload files to Flowise programmatically without using Flowise GUI. Is that possible? Is it possible to do this using another applicaton? can I make a web application that is able to do this?

Thanks in advance

**Comment by HenryHengZJ** [comment]
you can do so via API - https://docs.flowiseai.com/using-flowise/api#document-loaders-with-upload
