### ISSUE TITLE
A Demo to use Flowise to talk to databases

### ISSUE THREAD

**Issue by golytics** [FlowiseAI/Flowise#1572]
Good day dear All,

Do you know any demo that shows hoe to make Flowise talk to a database.

Hint: I don't know how to connect to the database.

Thanks in advance

**Comment by HenryHengZJ** [comment]
there are 2 templates from marketplace you can refer to:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/d14e900c-3d77-4251-b92e-46080f691eb4)

will publish in-depth tutorial soon

**Comment by golytics** [comment]
Thanks,@HenryHeng
I tried them bu I believe I still need guidance
Thank you but please make it comprehensive if possible. show us where is the database, the address of the server, son.

Thanks again

**Comment by golytics** [comment]
I have tried the following in the SQL DB Chain example you gave above.
I have Northwind database (Northwind.db). For the node of "SQL database chain" node, I used the following path for Sqlite "C:\Users\Mohamed\northwind.db;Version=3;" & for the additional parameters, I made them as follows:

Include Tables --> Employees
Sample table's rows info --> 3
Top Keys -->3

Custom Prompt --> Given an input question, first create a syntactically correct {dialect} query to run, then look at the results of the query and return the answer. Unless the user specifies in his question a specific number of examples he wishes to obtain, always limit your query to at most {top_k} results. You can order the results by a relevant column to return the most interesting examples in the database. 

Never query for all the columns from a specific table, only ask for a the few relevant columns given the question. 

Pay attention to use only the column names that you can see in the schema description. Be careful to not query for columns that do not exist. Also, pay attention to which column is in which table. 

Use the following format: 

Question: "Question here" 
SQLQuery: "SQL Query to run" 
SQLResult: "Result of the SQLQuery" 
Answer: "Final answer here" 

Only use the tables listed below. 

{table_info} 

Question: {input} 





To be honest, I don't know how to use it but I asked " list 5 employees" in the chatbot and I got the following reply:

Error: Include tables not found in database: the table Employees was not found in the database


And I am sure that the databse has a table called Employees.


I will be grateful if you can guide me to operate this :)

thank you

**Comment by golytics** [comment]
Hello,
@HenryHengZJ 
Hope all is great with you.
Any news about the above request?

Thanks in advance
