### ISSUE TITLE
[BUG] can’t connect to Pinecone 

### ISSUE THREAD

**Issue by doumlegare** [FlowiseAI/Flowise#1573]
I just updated to latest version and of flowiseui and I can’t connect anymore 
The message said that have error connecting to vontroller

**Comment by HenryHengZJ** [comment]
can you share what is your setup, how you install flowise?

**Comment by doumlegare** [comment]
hello, thanks four your fast response, here's a loom video, hope it helps
https://www.loom.com/share/8e23435989b6450bb22860390619f106?sid=ab08c4df-4983-44e0-a4fd-f4eb0f4f0686

**Comment by HenryHengZJ** [comment]
@doumlegare I tested on Railway with `1.4.10` it works for me

1.) Use the new Pinecone node
2.) Click the green button at top right:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/f9acf8eb-09a6-4be7-9f93-10a4312607cb)
3.) Click upsert:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/504d4b50-6b72-4f88-8540-4be480f8d4d1)
4.) Verify your data on Pinecone
5.) Proceed to chat:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/add79e2b-4104-40ae-a016-300f2d9535e7)

**Comment by doumlegare** [comment]
i made a test and i have same issue.
Do you use pod or the new serverless system?
https://www.loom.com/share/895875d24f4e4b34a59c711f9ea7352e?sid=a8238759-d06f-4a8d-9c53-2a530a8b01d1

**Comment by doumlegare** [comment]
Hello @HenryHengZJ ,
i think that i have found the issue.
Pinecone implement in last past days the serverless options instead of pods.
My previous tests was with serverless and was not working.
Here's a video with implementing with pods and it works.
do you have a solution to make it works with serverless instead?
https://www.loom.com/share/702bd6f04e1449089d7d9a2ceb5c03ec?sid=56567cf2-c7d6-4653-856b-be9c338826bb
thanks you

**Comment by doumlegare** [comment]
i contact Pinecone and there is their response
---------------------
Hi Dominic,
 
Could you confirm which Pinecone SDK and version you're using? I suspect you're using an older version of the Python client. The latest version is 3.0 and solves a number of issues with connecting to Pinecone, including removing the need to call the whoami endpoint entirely. 
 
Try upgrading using pip install -U pinecone-client=3.0 then run your script again. Note that you'll need to make some changes to your script since the newest version changes how you establish a connection. You'll want to replace the import statement with
from pinecone import Pinecone
Then, change the call to init() with
pc = Pinecone(api_key=YOUR_API_KEY)
For more details about migrating to 3.0 please see [our migration guide](https://canyon-quilt-082.notion.site/Pinecone-Python-SDK-v3-0-0-Migration-Guide-056d3897d7634bf7be399676a4757c7b#a21aff70b403416ba352fd30e300bce3).
 
If you continue to receive errors when instantiating your connection, please be sure to provide us the full stacktrace of any errors you receive. That will help us better guide you on next steps.
 
Thanks,
Cory

**Comment by HenryHengZJ** [comment]
@doumlegare yep i was testing using pod, not serverless. it wasnt available in `1.4.10`. Just pushed a new update `1.4.11`, if you update your railway app, you should now be able to use pinecone serverless.

feel free to reopen if issue still persists

**Comment by doumlegare** [comment]
Thank you henry for your prompt help. still new with github / railway don't really know how to update
I have forked the latest version in my repo.
Any tips to make it work without loosing job done?
