### ISSUE TITLE
[BUG] [ERROR]: unhandledRejection:  ENOENT: no such file or directory, open '/home/.flowise/settings.json'

### ISSUE THREAD

**Issue by dkindlund** [FlowiseAI/Flowise#1579]
**Describe the bug**
So I redeployed Flowise as a Google Cloud Run Docker container that's using a remote PostgresQL database for configuration.  In this mode, I was expecting NOT to have to configure any sort of local storage within the Flowise container.  Flowise starts up fine in this mode, BUT when I attempt to save any sort of chatflow, I get this error:

[ERROR]: unhandledRejection:  ENOENT: no such file or directory, open '/home/.flowise/settings.json

So I'm trying to understand:
1) Even with Flowise connecting to a remote DB for config, it seems that Flowise *still* needs to write out something called "settings.json" locally to disk.
2) And if you don't do that, you can't save chatflows -- but I thought chatflows were saved to the remote DB only?

So my questions are:
- What purpose does the "settings.json" serve?
- Is there any way to have the data that's normally saved in "settings.json" instead be saved to the remote DB?
- Is there any way to configure Flowise *without* needing local storage IF a remote DB is configured?

**Comment by dkindlund** [comment]
After further digging, it seems there are two issues with using Flowise in a Google Cloud Run service, without a local disk, and with a remote DB:

1) The `settings.json` file appears to be storing a unique identifier for PostHog telemetry tracking.
2) The `api.json` file appears to store all the API keys needed to allow others to talk to Flowise APIs.

I understand the need and purpose of both of these.  They make sense.

@HenryHengZJ , what I'm wondering is:
1) Is there any way the data in `api.json` and `settings.json` could be stored in the remote DB (or sqlite) rather than as a file on disk?  (If we can migrate the logic into there, then Flowise would no longer need a local disk, I think? -- the goal would be to make Flowise operate in an entirely serverless manner.)

2) I noticed that `settings.json` appears to be **hardcoded** to the `/home/.flowise/settings.json` path.  This means if you attach a local disk to the Flowise container, currently, it *must* be in the `/home/.flowise` path.  This is because the PostHog `settings.json` appears to **not** respect any of the other environmental variables provided.  As an interim fix, could this be changed?  Maybe we need a `POSTHOG_PATH` environment variable as a short term solution?

**Comment by HenryHengZJ** [comment]
@dkindlund thanks for the input! yes in future we plan to introduce user entity into Flowise for multi-tenancy and roles, and files like settings and api will be moved to that entity.

For now, I'll use `SECRETKEY_PATH` as the location for `settings.json` (trying to avoid having another `SETTINGS_PATH`) - https://github.com/FlowiseAI/Flowise/pull/1583
