### ISSUE TITLE
[BUG] "ChatGoogleGenerativeAI" together with "Conversational Retrieval Agent" not work

### ISSUE THREAD

**Issue by fejdraus** [FlowiseAI/Flowise#1580]
When using ChatGoogleGenerativeAI together with Conversational Retrieval Agent (in order to use tools like databases) it gives an error 
```
"[GoogleGenerativeAI Error]: Error fetching from
https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent
: [400 Bad Request] Please ensure that multiturn requests ends with a user role or a function response"
```
![image](https://github.com/FlowiseAI/Flowise/assets/46014577/d09d6328-9795-4934-85c6-0ad20740cbab)

**Setup**
-   Installation yarn start
-   Flowise Version 1.4.10
-   OS: Windows
-   Browser chrome

**Comment by HenryHengZJ** [comment]
for now it doesnt work with gemini due to ther underlying prompt being used in agent

**Comment by fejdraus** [comment]
Is it possible to make an agent separately like they did for OpenAI?
