### ISSUE TITLE
[BUG]  Error [server ]ENOENT: no such file or directory, open '/root/.flowise/settings.json

### ISSUE THREAD

**Issue by remixdance** [FlowiseAI/Flowise#1582]
I updated my Open AI assistant and when try to chat The bot give me the error : ENOENT: no such file or directory, open '/root/.flowise/settings.json' How I can solve it
 I have 3 custom tools , each tool calls an API

**Expected behavior**
Retrive the right response.

**Flow**
![image](https://github.com/FlowiseAI/Flowise/assets/42038961/fbb04986-95f6-4130-b2da-9a83978a7838)
![image](https://github.com/FlowiseAI/Flowise/assets/42038961/35d2c46a-ffbb-4596-9798-de2c7832a6fa)

![image](https://github.com/FlowiseAI/Flowise/assets/42038961/c23544fc-e08e-4744-9b26-e139f693a0eb)

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version 1.4.10
-   OS: Docker Render web service
-   Browser chrome
**Additional context**
Before I updated the Open AI assistant the chat was working fine, I updated because on the right corner I saw a warining that the node was the version 1 and needs to updated to version 3

**Comment by niztal** [comment]
@HenryHengZJ 

when the env variable of DATABASE_TYPE is set (e.g. "mysql") I still get this error when trying to upsert my Pinecone vectorstore

I'm using the latest image.

![image](https://github.com/FlowiseAI/Flowise/assets/19833797/168d613c-0bf8-48eb-b3a0-bc54f5e091af)

**Comment by niztal** [comment]
@HenryHengZJ I've fixed this issue please review PR

https://github.com/FlowiseAI/Flowise/pull/1630

Thanks
