### ISSUE TITLE
RedisCache TTL - should the 'set' option be 'PX' instead of 'EX'?

### ISSUE THREAD

**Issue by dkindlund** [FlowiseAI/Flowise#1589]
Hey @HenryHengZJ , just looking at this line of code:

https://github.com/FlowiseAI/Flowise/blob/764efcccb738e1683b7e0cf623044ce3286d2f39/packages/components/nodes/cache/RedisCache/RedisCache.ts#L97

The input prompt is specifying the TTL in milliseconds, but the 'set' option of 'EX' assumes the number is in seconds.  Because our original input is in milliseconds, shouldn't we change the 'set' option to 'PX' accordingly?

Ref: https://redis.io/commands/set/

**Comment by HenryHengZJ** [comment]
@dkindlund yep you're right, we should!
