### ISSUE TITLE
[BUG] Typo on landing page

### ISSUE THREAD

**Issue by emanuele-toma** [FlowiseAI/Flowise#1615]
**Describe the bug**
On the landing page of the website there are two sentences with a typo:

Just under the title there is:
"Open source UI visual tool to build your customized LLM **ochestration** flow & AI agents"

And under get started the title:
"LLM **Ochestration**"

**Expected behavior**
It should be O**r**chestration

**Screenshots**
![immagine](https://github.com/FlowiseAI/Flowise/assets/34580249/6cb65f18-0c1e-49b9-892d-882d3564efa1)
![immagine](https://github.com/FlowiseAI/Flowise/assets/34580249/88e18aa3-6958-4a1f-bec4-6ea1f63ad7ca)

**Comment by HenryHengZJ** [comment]
appreciate the notice, now fixed!
