### ISSUE TITLE
[BUG] Switch to Async Operations for Vector Document Upserts?

### ISSUE THREAD

**Issue by dkindlund** [FlowiseAI/Flowise#1626]
**Describe the bug**
I have an Airtable table with 500+ records.  I also have Flowise configured in Google Cloud Run service with a 10 minute timeout per connection.  When I perform an upsert into a Postgres Vector Store, I see the job start.  Then, because the job takes longer than 10 minutes to complete, Google Cloud Run terminates the session early (because of the 10 minute timeout).  HOWEVER, it seems even though the connection to the browser terminated, the backend upsert job is still going (which is good).

The core issue though, is that Flowise doesn't *appear* to treat upsert jobs as an asynchronous operation.  Meaning, the browser is expected to *wait* until the upsert job completes.  For many, many documents, this job will take longer than whatever timeout is specified and so the browser connection will eventually *fail* early.  Many users might *think* this failure means their documents didn't get successfully upserted.

**To Reproduce**

1. Create an Airtable base with more than about 5 fields and 1000 records
2. Configure Flowise with a 10 minute timeout
3. Perform upsert into a Postgres database
4. Wait 10 mins
5. See browser connection silently terminate
6. Wait another 20 mins
7. See Postgres have all 1000 records inserted

**Expected behavior**
Instead of having the browser *wait* for the upsert job to complete, I'd recommend Flowise return some sort of "Job ID" and then have the browser refresh periodically to check if the job actually completed.  This means having some sort of job scheduling and queuing system so that upserts operate in an asynchronous manner.

I get that this is a complicated ask, but the alternative is that you can only have Flowise upsert *small* numbers of records/documents at a time, which means it won't work for larger, production workloads.

@HenryHengZJ , maybe this is already on the roadmap, but I figured it's worth calling out for tracking purposes.

**Comment by dkindlund** [comment]
Update: It seems I was able to get upserts to process much *faster* by changing the default batch size in the Embeddings node from 1 to 100.  I'm wondering why the default Embeddings batch size is set so low by default, accordingly.

If there's no explicit reason why the default batch size in the Embeddings node (for Azure OpenAI) is 1 -- could we change the default to like 100 instead, @HenryHengZJ ?

**Comment by HenryHengZJ** [comment]
@dkindlund I think previously there was a problem wehn no batch size is specified, thats why default to 1. Feel free to open a PR to make default as 100

**Comment by dkindlund** [comment]
@HenryHengZJ , okay, will do!  It seems a batch size of 100 is the "sweet spot" for getting Azure OpenAI Embeddings to work against a large volume of upserts in the vector stores.
