### ISSUE TITLE
Chat wizard's  icon modification. [FEATURE]

### ISSUE THREAD

**Issue by mahaboobkhan29** [FlowiseAI/Flowise#163]
Please update the UI to modify the chat wizard's parrot icon with our own icon so that we can use it on our website. If the parrot icon in the chat wizard looks weird with the website design, we would like to replace it with a more suitable icon.

**Comment by HenryHengZJ** [comment]
with the latest update, you can now configure mostly everything on the embedded widget: https://github.com/FlowiseAI/FlowiseChatEmbed#configuration

<img width="661" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/b7d18cc0-27f9-4b98-a78c-8dc17fac4a26">
