### ISSUE TITLE
Local LLM with tools

### ISSUE THREAD

**Issue by tjthejuggler** [FlowiseAI/Flowise#1640]
The ability to use tools without having to use an openAI API key.

**Comment by automaton82** [comment]
You can use the conversational agent with any chat model and tools, including Ollama locally. Is that what you mean?

**Comment by tjthejuggler** [comment]
Awesome, yeah, that is exactly what I needed. thanks so much!

**Comment by tjthejuggler** [comment]
Awesome, yeah, that is exactly what I needed. thanks so much!
