### ISSUE TITLE
[BUG] cohere rerank retriever topk not working 

### ISSUE THREAD

**Issue by matrixmayhem** [FlowiseAI/Flowise#1655]
The top k parameter of the new cohere rerank retriever node doesn't work. It retrieves ALL the results. 

I want to rerank 50 results that I get from pinecone, rerank them and return the top 5 results. Cohere rerank node  returns all 50 results in my conversational retrieval QA chain.

**Comment by HenryHengZJ** [comment]
fixed - https://github.com/FlowiseAI/Flowise/pull/1656
