### ISSUE TITLE
Does not work when I install it on Kartra.

### ISSUE THREAD

**Issue by Lesinarretables** [FlowiseAI/Flowise#1658]
Hello,

Describe the bug:

When I install the script in the "Embed tracking code into the <body>" section of Kartra (LMS), the script starts successfully, the chatbot appears and opens, but the response to the question remains in loading and never reaches my server, where Flowise is hosted. However, if I directly use the link to connect with Share Chatbot, the chatbot works fine. Is it possible that the message is being blocked at the Kartra level and therefore never sent to my server?

Flowise is installed and hosted on a DigitalOcean server.

Thank you for your assistance.

**Comment by automaton82** [comment]
If you open devtools it says it's loading mixed content (HTTPS and HTTP). You need both to be HTTPS.

By the way you should lockdown your Flowise instance, anyone (including me) can just pull it up here:
http://209.97.184.137:3000/

And start deleting your chatflows. Suggest you secure it.

**Comment by Lesinarretables** [comment]
You're welcome! Yes, I will set up a new server tonight; it was just a first test. Thank you for your assistance.
