### ISSUE TITLE
[BUG] "SQLITE_CONSTRAINT: NOT NULL constraint failed: chat_message.content"

### ISSUE THREAD

**Issue by wflanagan** [FlowiseAI/Flowise#1665]
I upgraded to the current main as of today (it's still current) on Render.com. Using the CURL, I attempted to make an API call. I get a 500 error response, and the body of the html response states: "SQLITE_CONSTRAINT: NOT NULL constraint failed: chat_message.content"

I have verified that the response is sgenerated, but it's attempt to parse and put it into SQLITE seems to fail. This is the current logs:

```
*****FINAL RESULT*****
{
  "label": "person",
  "gender": "undefined"
}
2024-02-02 12:21:14 [ERROR]: [server]: Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: chat_message.content
QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: chat_message.content
    at Statement.handler (/usr/src/packages/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:88:37)
```

The flow works in the chat window. 

This is the configuration.  

![CleanShot 2024-02-02 at 07 28 01](https://github.com/FlowiseAI/Flowise/assets/263397/2cd038c5-8be2-432b-905f-da019da6878b)

**Comment by HenryHengZJ** [comment]
I've tested it on Render, seems to work fine. Have you tried redeploying? Or perhaps can u try if you face same issue using other chain/agent? Like conversation chain

**Comment by levuepress** [comment]
How did you solve your problem?
