### ISSUE TITLE
[FEATURE] APIChain support or how am I supposed to query custom REST APIs?

### ISSUE THREAD

**Issue by nabbl** [FlowiseAI/Flowise#167]
**Describe the feature you'd like**
So maybe this already works but what I want to do with flowise which works nicely in langchain is to make GET or POST requests to a privately hosted REST API via api bearer token. Get the json and make informed descisions based on the response and then make post requests according to the decisions made by the LLM.
Didn't get it to work on flowise though because there is no tool or chain or anything to put URL and authorization tokens anywhere.

**Comment by HenryHengZJ** [comment]
You mean API Chain - https://python.langchain.com/en/latest/modules/chains/examples/api.html?

**Comment by nabbl** [comment]
Great! thx

**Comment by tao12345666333** [comment]
https://github.com/hwchase17/langchainjs/pull/1400 has been merged.

**Comment by HenryHengZJ** [comment]
APIChain is now available on Flowise!

Have a look at the demoL https://github.com/FlowiseAI/Flowise/pull/197
