### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by ranon-rat** [FlowiseAI/Flowise#1675]
**Describe the bug**
I have follow a simple example of a conversational agent.
For some reason is not working and the model is giving me the next error.
Im using the mistral api for the chat model 
![imagen](https://github.com/FlowiseAI/Flowise/assets/66473662/2a0aa690-b3bf-4a8b-ab85-cd54c4f68c8f)

**To Reproduce**

![imagen](https://github.com/FlowiseAI/Flowise/assets/66473662/d470e106-f776-415a-a0dd-da0ef78742fb)

**Expected behavior**
I just expect basic stuff
**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [ docker]
-   Flowise Version [ 1.4.10]
-   OS: [ Linux]
-   Browser [firefox]

**Comment by HenryHengZJ** [comment]
I think in this case, try deleteing the conversation chain, and drag it again from the menu, see if it works
