### ISSUE TITLE
[FEATURE] New option "keep_alive" with Ollama 

### ISSUE THREAD

**Issue by ansutung** [FlowiseAI/Flowise#1679]
**Additional context**
The information about "keep_alive" parramater at link: [https://github.com/ollama/ollama/releases/tag/v0.1.23](https://github.com/ollama/ollama/releases/tag/v0.1.23)

**Comment by HenryHengZJ** [comment]
PR merged - https://github.com/FlowiseAI/Flowise/pull/2892
