### ISSUE TITLE
[FEATURE] SQl Database Chain Q & A

### ISSUE THREAD

**Issue by scheung38** [FlowiseAI/Flowise#1681]
This is my discussion:

https://github.com/FlowiseAI/Flowise/discussions/1674

if I copy the AI generated

```
SELECT TOP 5 Supplier 
FROM payment_reports 
ORDER BY reportId, amount DESC;
```

and 

prompt it again, AI replied:

I'm sorry for any confusion, but as an AI, I don't have the ability to execute SQL queries in a live database. I can help generate SQL queries based on the information provided to me. The query you've written is correct for selecting the top 5 suppliers from the payment_reports table, ordered by reportId and amount in descending order, in a Microsoft SQL Server database.

To execute this query, you would need to run it in your SQL Server Management Studio or any other SQL client connected to your database. The results will depend on the current data in your payment_reports table.

Then how do we execute the autogenerated SQL query?

**Comment by HenryHengZJ** [comment]
I would recommend taking a look at SQL Prompt template in marketplace:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/2e156242-f487-4231-8390-0735c2e1b384)

That is where the SQL query can be executed using custom function
