### ISSUE TITLE
[BUG] Supabase Setup

### ISSUE THREAD

**Issue by JayP127** [FlowiseAI/Flowise#169]
Using the same template to query a csv file works with Pinecone but not with Supabase. I get the following error with Supabase:

Error searching for documents: PGRST202 Could not find the function public.CFP(match_count, query_embedding) in the schema cache Searched for the function public.CFP with parameters match_count, query_embedding or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.

I am attaching a screenshot:
![image](https://github.com/FlowiseAI/Flowise/assets/37101612/ed3f5fb6-fa04-4513-baee-36a14e1cb736)

I have triple-checked the Supabase API Key and Project URL. They seem to be OK

**Comment by mgunnin** [comment]
Yeah I'm getting some other type of errors with Supabase.. Seems like there is an update needed perhaps?

**Comment by HenryHengZJ** [comment]
you'll have to use the `pg-vector` extension. you can follow the guide here: 

1.) Register Supabase account

2.) Dashboard => New Project =>  SQL Editor => New Query

3.) Copy & Paste queries below and execute:
```
-- Enable the pgvector extension to work with embedding vectors
create extension vector;

-- Create a table to store your documents
create table documents (
  id bigserial primary key,
  content text, -- corresponds to Document.pageContent
  metadata jsonb, -- corresponds to Document.metadata
  embedding vector(1536) -- 1536 works for OpenAI embeddings, change if needed
);

-- Create a function to search for documents
create function match_documents (
  query_embedding vector(1536),
  match_count int,
  filter jsonb DEFAULT '{}'
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;
```

**Comment by JayP127** [comment]
I have it working now. I also have a couple of comments regarding the "Supabase Upsert Document" module:

1. The Supabase API Key corresponds to the "service_role" key
2. The Query Name field corresponds to the name of the function, in the code you presented above, the function is "match_documents". 

Best.

Jay

**Comment by jbainpro** [comment]
I tried everything as described here, documents are being upserted however there is an error: 42883 operator does not exist: extensions.vector <=> extensions.vector null

I couldn't run this command as it said its already installed: "create extension vector;"

![Screen Shot 2023-05-30 at 04 48 50](https://github.com/FlowiseAI/Flowise/assets/60293260/d843abef-ff0b-4541-aa34-9515a1d4c7e9)

Regards

**Comment by jbainpro** [comment]
I solved the issue.

**Comment by sunnythaper** [comment]
@HenryHengZJ and @mgunnin just wanted to say ty. Reading both your comments allowed me to set up a working example. I wish some of that was in official documentation or something tho, cause I was lost for a good while. Anyway, thanks again.

**Comment by HenryHengZJ** [comment]
@sunnythaper its now available - https://docs.flowiseai.com/vector-stores/supabase

**Comment by sunnythaper** [comment]
@HenryHengZJ wow, thank you so much! I hope this saves future users some time! Potentially future me when I try to do this again after a brief hiatus.
