### ISSUE TITLE
[BUG] WebSocket stops responding unexpectedly

### ISSUE THREAD

**Issue by DrBanjo11** [FlowiseAI/Flowise#1696]
**Describe the bug**
The websocket stops responding (incognito session fixes it).

The websocket times out after working successfully multiple times. The only way I have to restore connection is to open a new incognito session. Working on Chrome

WebSocket connection to '<URL>' failed: WebSocket is closed before the connection is established.
index-e0da01c4.js:942 WebSocket connection to 'wss://HOST/socket.io/?EIO=4&transport=websocket' failed: WebSocket is closed before the connection is established.

**Comment by HenryHengZJ** [comment]
Dont think its Flowise related, maybe a cache on browser that mess it up?

**Comment by DrBanjo11** [comment]
I think it has to do with connection disposal, how often does Flowise closes the connection if it does not receive the ping?

**Comment by HenryHengZJ** [comment]
> I think it has to do with connection disposal, how often does Flowise closes the connection if it does not receive the ping?

that is the default socketIO config, in Flowise we didnt specify any configuration for timeout
