### ISSUE TITLE
[FEATURE] Run LangChain in the client side instead of server side

### ISSUE THREAD

**Issue by badbye** [FlowiseAI/Flowise#17]
**Describe the feature you'd like**
[LangChain can be used in the browser](https://js.langchain.com/docs/getting-started/install#browser). I think this whole project could work without a server.

**Comment by HenryHengZJ** [comment]
Yeah it works on browser now but not sure what's the limitation there.

For now we'd prefer to stick to using server for NodeJS thread processing, serve api logics, connecting to databases for your chatflows and messages (we'll add postgres, sql). Most npm dependencies used are also designed for Node
