### ISSUE TITLE
[BUG] Azure ChatOpenAI gpt-4-32k has 4096 context token limit

### ISSUE THREAD

**Issue by matthewsilver** [FlowiseAI/Flowise#1711]
**Describe the bug**
Trying to use Azure ChatOpenAI gpt-4-32k, but getting errors like "This model's maximum context length is 4096 tokens. However, your messages resulted in 4106 tokens (4054 in the messages, 52 in the functions). Please reduce the length of the messages or functions." This happens even after I manually increase the Max Tokens parameter in the chat model.

**To Reproduce**
See screenshots below. Go through conversation until over 4096 tokens in memory.

**Screenshots**

![image](https://github.com/FlowiseAI/Flowise/assets/17550966/42499e85-c420-47ce-9a74-8a23933443a2)
![image](https://github.com/FlowiseAI/Flowise/assets/17550966/5d7856c7-09e6-4aea-8ff5-c9c1e5245e9b)

**Comment by chungyau97** [comment]
Hey @matthewsilver, could you try setting it to the max 80 K?

![image](https://github.com/FlowiseAI/Flowise/assets/33013947/58478d42-401c-4bd7-9df4-6b52504a292a)

**Comment by matthewsilver** [comment]
Hi @chungyau97, I set it to 80000 but it still gives me the 4096 token limit error. The error message does change a bit, it now says I requested 80000 tokens in the completion.

**Comment by matthewsilver** [comment]
Hi @chungyau97, do you have an update on this? Thanks!

**Comment by HenryHengZJ** [comment]
strange, can you try to re-add the node, create from scratch? gpt-4-32k should have 32k context limit, not 4k context limit
