### ISSUE TITLE
"ER_DATA_TOO_LONG" Error with PDF File Component when DATABASE_TYPE is MySQL

### ISSUE THREAD

**Issue by mahendrasinghbora** [FlowiseAI/Flowise#1719]
### Description:

When using the PDF file component in a Flowise chatflow with MySQL as the database type, an "ER_DATA_TOO_LONG: Data too long for column 'flowData' at row 1" error occurs. This indicates that the generated flow data exceeds the length limit of the `flowData` column in the MySQL table `chat_flow`.

![image](https://github.com/FlowiseAI/Flowise/assets/26798296/3d713bfe-29e0-4b63-bb1e-7300ae339d48)

**Steps to Reproduce:**

1. Create a new Flowise chatflow.
2. Add a PDF file component (node) to the chatflow.
3. Configure the component with desired content (The PDF file I had used was 135 pages long).
4. Try to save the chatflow.

**Expected Result:**

The chatflow is successfully saved.

**Actual Result:**

The chatflow fails to save with the "ER_DATA_TOO_LONG" error.

**Possible Causes:**

The `flowData` column in the MySQL table may be defined with a character limit that is too small to store the PDF file. The current data type used for `flowData` is TEXT which has a maximum length of 65,535 bytes.

**Possible Solutions:**

I have temporarily fixed it by increased the character limit of the `flowData` column in the `chat_flow` table by changing is type to LONGTEXT from TEXT.

But now the chatflows are taking a lot of time to load and are a bit laggy. I guess it is also because of the fact that the contents of the PDF are stored in the `flowData` column.

**Comment by chungyau97** [comment]
Hey @mahendrasinghbora, we are figuring out a better way to store the file instead of storing the data in `flowData` column.
Yea, this is because we store the data of the PDF file into the `flowData`. 
Since you already upserted the document into vector store you can delete the document loader and save it. This will allow faster loading.

**Comment by HenryHengZJ** [comment]
Every file that is uploaded is no longer stored as base64 string, instead stored to a local file path specified by `BLOB_STORAGE_PATH` env variable. If not specified, the default directory is `<user-home-dir>/.flowise/storage`.

This fix is released to `v1.6.4`
