### ISSUE TITLE
Custom chain promt for Conversational Retrieval QA

### ISSUE THREAD

**Issue by mahaboobkhan29** [FlowiseAI/Flowise#172]
How can I add a custom chain prompt for Conversational Retrieval QA Chain? When I ask a question that is unrelated to the context I stored in Pinecone, the Conversational Retrieval QA Chain currently answers with some random text. Instead, I want to provide a prompt to the chain to answer the question based on the given context. Can you guide me on how to achieve this?

**Comment by mahaboobkhan29** [comment]
@HenryHengZJ your a life saver man!!!.. and i am still using render.com to run your code can you have any documentation for deploy in aws?

**Comment by HenryHengZJ** [comment]
will work on the docs soon!

**Comment by ianmcfall** [comment]
Realize this is a little late - but does anyone know how to achieve this in langchainjs? I've been using flowiseai to get my feet wet, but now I need to replicate the same chatflow with this feature separately.

I found this `systemMessagePrompt`: but I'm not sure how to implement it:

[Flowise](https://github.com/FlowiseAI/Flowise/tree/main)/[packages](https://github.com/FlowiseAI/Flowise/tree/main/packages)/[components](https://github.com/FlowiseAI/Flowise/tree/main/packages/components)/[nodes](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes)/[chains](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/chains)/[ConversationalRetrievalQAChain](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/chains/ConversationalRetrievalQAChain)
/ConversationalRetrievalQAChain.ts
