### ISSUE TITLE
[BUG] i cant see my saved flow after i enable database setting at the server/.env file.  

### ISSUE THREAD

**Issue by nerkasnimo** [FlowiseAI/Flowise#1721]
**Describe the bug**
if i set the database setting, i cant see my saved flow. if i disable it i can see again. is there any way flow transferring between local to database. 

**To Reproduce**

1. save a flow
2. Go to "package/server/.env"
3. enable the database settings. 
```
DATABASE_TYPE=postgres
DATABASE_PORT=5432
DATABASE_HOST=localhost
DATABASE_NAME=flowise
DATABASE_USER=postgres
DATABASE_PASSWORD=***

```
5. restart flowise
6. See error

**Expected behavior**
be able to transfer local saved flow to database. or something like that.

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. git into conda , `yarn install`, `yarn build`, `yarn dev` ]
-   Flowise Version [e.g. 1.15]
-   OS: [ Windows, ]
-   Browser [e.g. brave, chrome]

**Additional context**

**Comment by Jaredude** [comment]
Change your install to local. Then export the flow you have. Then change your env file. Restart flowise, and import the json file into your flow. You'll also have to setup your credentials. Hope that helps.

**Comment by chungyau97** [comment]
Hi @nerkasnimo,

The default database we used is SQLite. 
When you enable database configuration, you are creating another database, which results in not being able to see your saved chatflows.
