### ISSUE TITLE
Pinecone DB not usable with a pinecone serverless plan

### ISSUE THREAD

**Issue by mansel089** [FlowiseAI/Flowise#1722]
**Describe the bug**
After changeing from a free pod based pinecone to a serverless pinecone DB  I am not able to connect to the DB. In the working setup I just receive a 404 error

**To Reproduce**
Every flow which is using a pinecone DB with a serverless index.

**Feedback regarding the bug from pinecone**
_Thank you for contacting Pinecone Support. Yes, the Pinecone client's new version (3.0.x) is required to access serverless indexes; you can find more information in our documentation. The legacy client can only be used to access pod-based indexes.
 
api.pinecone.io.. is the correct endpoint, but some users in our community forum have indicated that Flowise still needs to upgrade to the latest version. Their code on [Github] uses 2.0.1, which is the legacy client, and will not be compatible with serverless. Unfortunately, there's nothing I can do on my end; I'd recommend reporting a Github issue_

**Expected behavior**
An update which is necessary regarding to the answer from pinecone

**Screenshots**
![Bildschirmfoto 2024-02-13 um 18 32 52](https://github.com/FlowiseAI/Flowise/assets/155970612/34a0d6ec-93c5-4a9d-8bc3-5b899c881fa1)

**Setup**
-   Installation on render.com using fork the github repository and installing it  from there
-   Flowise Version 1.4.11

**Additional context**

**Comment by giordano221** [comment]
I'm having the same problem. See the printout of the error.

<img width="1509" alt="Captura de Tela 2024-02-15 às 10 34 53" src="https://github.com/FlowiseAI/Flowise/assets/18662157/c55216ca-fa8d-4ebf-9418-97f052bf34f2">

**Comment by HenryHengZJ** [comment]
@chungyau97 is taking a look at this

**Comment by HenryHengZJ** [comment]
with the new langchain upgrade [PR](https://github.com/FlowiseAI/Flowise/pull/1691), I've tested both pod and serverless, they are working. You can test it once a new release is out

**Comment by HenryHengZJ** [comment]
new release is out with `1.5.1`, test and see if it works
