### ISSUE TITLE
QueryFailedError: SQLITE_READONLY: attempt to write a readonly database

### ISSUE THREAD

**Issue by r-pathak** [FlowiseAI/Flowise#1723]
Hi all,

Firstly this tool is very very cool - just want to mention that.

However, I launch it in my terminal using npx flowise start. This works correctly, then I set up the following flow:

<img width="1047" alt="Screenshot 2024-02-13 at 23 27 08" src="https://github.com/FlowiseAI/Flowise/assets/96482421/5632e491-5a37-4146-bd42-512034dbe7f8">

Once that's done, I am trying to setup a credential for my model to Azure AI studio ( the interface has been updated a bit since the docs were created, but done what I can)

I've used the openAI key as my API key, the instance name as gpt-4, the deployment name as my deployment name as shown in Azure AI studio and finally the relevant version of gpt-4, 1106-preview as the version.

However, I get the following error in my terminal when I press 'add':

QueryFailedError: SQLITE_READONLY: attempt to write a readonly database

Am I missing a step, or is this a bug? I'm not sure if the config should be slightly different since the UI in the docs has since been updated from Azure.

Also noticing that when I had {input} as my text prompt, I get the same error in my terminal.

Not sure if anyone else has seen this, would be great to know more on how I can fix this.

Thanks in advance!

**Comment by chungyau97** [comment]
Hi @r-pathak, which platform are you running Flowise on Mac/Win/Linux?

**Comment by r-pathak** [comment]
Ah yeah, ofc I forgot to mention - running on Mac. Although once I'm done testing locally will likely deploy as an Azure app service on Linux

**Comment by HenryHengZJ** [comment]
Flowise automatically create a SQLite database stored in user home directory `/.flowise`, you need to grant write access to that with `sudo chown -R "$USER":"$USER" /path/to/my-folder`

**Comment by sgcodes7471** [comment]
what to do if I am on WIndows?
