### ISSUE TITLE
[BUG] Trying to run the vector upsert feature, getting error 401

### ISSUE THREAD

**Issue by MMX-cpu** [FlowiseAI/Flowise#1724]
![Screenshot from 2024-02-13 18-39-20](https://github.com/FlowiseAI/Flowise/assets/114899591/45d5374e-5631-429a-8960-aab8a5afea64)

Trying to run the Vector upsert feature and getting "Error: command "insertmany" failed with the following errors: [{"message":"Request failed with status code 401"}]

Running openai embedding with astraDB. Using valid credentials.

**Comment by HenryHengZJ** [comment]
should be resolved with this PR - https://github.com/FlowiseAI/Flowise/pull/2071
