### ISSUE TITLE
[BUG] Inaccessible CORS When Deploying Via Azure Container

### ISSUE THREAD

**Issue by r-pathak** [FlowiseAI/Flowise#1728]
Hi. 

I've followed the docs here:
https://docs.flowiseai.com/configuration/deployment/azure#create-a-container-instance-without-persistent-storage

and created a container instance in Azure on which I have built and tested that my chat flow is returning the desired results. I'm not using persistent storage, but when I embed the chat bubble via 'embed react popup' and try to start a chat, I am seeing the following error in my console:

<img width="494" alt="Screenshot 2024-02-14 at 15 46 41" src="https://github.com/FlowiseAI/Flowise/assets/96482421/99204e64-22ad-45e6-a06b-069aa7bc5891">

I'm aware of setting up CORS on an azure web app instance, but for a container instance I don't see these options. Is there a fix for this? Or am I missing something?

Thanks in advance!

**Comment by r-pathak** [comment]
FYI, for anyone reading - the local host is the URL for my container instance, this is for sure running on there lol

**Comment by r-pathak** [comment]
Found the fix. You want to create a API management resource in Azure, then on the container instance you can add a CORS header to incoming requests.

Not sure if it's a production-ready fix, but should be fine if you can guarantee the only calls are being made from the Flowise embed.

**Comment by r-pathak** [comment]
Hi @CoreyH,

I ended up picking a different solution - so I can't actually refer to this to be precise...

But from memory, you want to add a CORS header to incoming requests to the http API for the flowise container instance:

https://learn.microsoft.com/en-us/azure/api-management/enable-cors-power-platform

I think this link explains how to do this (albeit not for a container instance) but should be findable in the API management console with a bit of digging.

Hope that helps, sorry that I couldn't be more precise on this

**Comment by CoreyH** [comment]
@r-pathak what solution did you end up with? 

My current thinking is that I should redo deployment using App Services w/ Containers instead of using ACI. ACI isn't really meant for this type of app.
