### ISSUE TITLE
[BUG] Results on Chatbot Preview Page are different from dashboard chat window and API response.

### ISSUE THREAD

**Issue by ggingmin** [FlowiseAI/Flowise#1729]
**Describe the bug**

Hello, I am a user who is using the Flowise service well. I would like to inquire about the chat message window through "share chatbot". When I ask a question in the chat window of the dashboard configured with a chatflow in Flowise, the answer is generated well based on the upserted resources. However, on the preview page generated through "share chatbot", the answers are not accurate or different from those in the dashboard chat window.

I wonder if there is a difference in caching per session or in the way API calls are made.

I always support the Flowise project and team. Thank you.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flow**
[test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14291495/test.Chatflow.json)

**Setup**
-   Installation: Docker
-   Flowise Version: 1.5.0
-   OS: Linux
-   Browser: Chrome

**Additional context**

**Comment by Jaredude** [comment]
Are you able to provide some screenshot examples of the difference you're experiencing?

**Comment by ggingmin** [comment]
Here you are, Thanks.

![스크린샷 2024-02-16 오후 5 52 21](https://github.com/FlowiseAI/Flowise/assets/24824279/2b9545f6-428b-44ba-9104-84137a6b8836)

**Comment by Jaredude** [comment]
What if you make the same call via the api using postman?

**Comment by HenryHengZJ** [comment]
there is no difference between the external and internal chat logic. I'd recommend using analytics to see if the step by steps are the same:
<img width="520" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/77448bfe-d583-4c96-b677-3d165cae669f">
