### ISSUE TITLE
[BUG] GPT-3.5-turbo model option is utilizing GPT-3.5-turbo-0613

### ISSUE THREAD

**Issue by XIII-IIIX** [FlowiseAI/Flowise#1730]
In the Chat Model _ChatOpenAI_ the GPT-3.5-turbo model option is utilizing GPT-3.5-turbo-0613. I would have assumed this was the most up-to-date model, gpt-3.5-turbo-0125, which is otherwise unlisted.

![chrome_C41OqiDOx9](https://github.com/FlowiseAI/Flowise/assets/130880508/1128b296-d8fd-44cd-9df3-6c96b33d3da7)

![chrome_SeQpdAMXRT](https://github.com/FlowiseAI/Flowise/assets/130880508/a7e84ce8-255f-4dc0-8461-36708aa5ad24)

Since there is already a _GPT-3.5-turbo-0613_ listed, this should either be removed or updated to show the correct model version.

**Comment by HenryHengZJ** [comment]
from the official [docs](https://platform.openai.com/docs/models/gpt-3-5-turbo) its currently pointing to 0613. But yeah feel free to open a PR to add the new `gpt-3.5-turbo-0125` if you dont mind :)
