### ISSUE TITLE
[BUG] yarn.lock is incorrectly .gitignored, potentially leading to build failures

### ISSUE THREAD

**Issue by saevarb** [FlowiseAI/Flowise#1731]
**Describe the bug**
Currently, yarn.lock is gitignore, which it shouldn't. In my fork, which I originally made a few months ago, a lockfile was created automatically. Updating the fork to match the new main branch means my lockfile is now incorrect, which (in my particular scenario) leads to build failures in `OpenAIAssistant.ts` because the `openai` version is not correct. This is just one example of a problem that can happen when no lockfile is present.

**Expected behavior**
The lockfile should be includede as part of the repository.

**Comment by HenryHengZJ** [comment]
when we switch to pnpm, a frozen lockfile will be provided - https://github.com/FlowiseAI/Flowise/pull/1272
