### ISSUE TITLE
[FEATURE] Add current model gpt-3.5-turbo-0125 to ChatOpenAI Chat Model

### ISSUE THREAD

**Issue by XIII-IIIX** [FlowiseAI/Flowise#1735]
Please add the current model _gpt-3.5-turbo-0125_ for the Chat Model ChatOpenAI 

Currently, the model listed as _GPT-3.5-turbo_ is utilizing _GPT-3.5-turbo-0613_. Please correct to make sure folks understand which model they are using. 

![chrome_C41OqiDOx9](https://github.com/FlowiseAI/Flowise/assets/130880508/5d1bd8c1-f95a-4dc8-97ad-a5fd2ce23c54)

**Comment by KazeroG** [comment]
💯 add new models

| MODEL | CONTEXT WINDOW| TRAINING DATA|
|--------|--------|--------|
| gpt-4-0125-preview| 128,000 tokens	| Up to Dec 2023|
| gpt-4-turbo-preview	| 128,000 tokens	| Up to Dec 2023|
| gpt-4-1106-preview| 128,000 tokens	| Up to Dec 2023|
| gpt-4-vision-preview| 128,000 tokens	| Up to Dec 2023| 
| gpt-4-1106-vision-preview	| 128,000 tokens	| Up to Dec 2023|

**Comment by chungyau97** [comment]
Hi @XIII-IIIX,

Please update your Flowise to be able to use `gpt-3.5-turbo-0125`.
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/f21a3a14-11f9-4817-aa23-05e38c79905b)

`gpt-3.5-turbo` is a dynamic model dependent on OpenAI's admin  configurations. For more information click [here](https://platform.openai.com/docs/models/gpt-3-5-turbo).
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/2ae0d290-d2ef-4562-b660-17baf7b83ee2)

**Comment by chungyau97** [comment]
Hi @KazeroG, please wait this PR #1744 to be review and merge.
