### ISSUE TITLE
[BUG] Flowise install fails on YARN BUILD and YARN START - Local, Render and Other

### ISSUE THREAD

**Issue by leonvanzyl** [FlowiseAI/Flowise#1739]
**Describe the bug**
Users are unable to set up Flowise, irrespective of the platform.
The issue seems to have started in the last day.

Users have been reporting that they are unable to install Flowise by cloning the Flowise Repo.
Running YARN INSTALL is successful, but YARN BUILD and YARN START fails.
This is therefore affecting local setups and cloud deployments, making Flowise unusable.

This is also affecting the global installation option (npm install -g flowise).

YARN BUILD
```
flowise-components#build: command (C:\AI\Flowise\packages\components) C:\Users\leon\AppData\Local\Temp\yarn--1708072574489-0.22103713331349772\yarn.cmd run build exited (2)

 Tasks:    0 successful, 2 total
Cached:    0 cached, 2 total
  Time:    1m2.038s
Failed:    flowise-components#build

 ERROR  run failed: command  exited (2)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

YARN START
```
C:\AI\Flowise>yarn start
yarn run v1.22.21
$ run-script-os
$ cd packages/server/bin && run start
 »   Error: command start not found
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by HenryHengZJ** [comment]
issue has been temporarily resolved - https://github.com/FlowiseAI/Flowise/commit/342adff8cb551c0166c75a6b10d66e7832dcef95

**Comment by leonvanzyl** [comment]
Excellent job with the webinar man.  You know your stuff.
