### ISSUE TITLE
[BUG] Conversational Retrieval QA chain not passing Rephrase Prompt. 

### ISSUE THREAD

**Issue by matrixmayhem** [FlowiseAI/Flowise#1742]
Bug with the Conversational Retrieval QA chain:
The rephrased question doesn't get passed to the llm. Only the user question gets passed. It does the performs the summary call to the llm but that is not them passed toh the next call.

**Comment by Jaredude** [comment]
Are you able to provide more details about the issue you are encountering? What is the flow? What is chained? And what are you using to connect the tools/chains to the Conversation Retrieval QA?

**Comment by matrixmayhem** [comment]
Prompt to test rephrase:
```
Ignore the following conversation and a follow up question, rephrase the follow up question to be a standalone question about starwars.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone Question:
```
As you can see in the screenshot , the questions is being rephrased but the rephrased question is NOT being passed to the LLM.
I am on version 1.5.0



<br class="Apple-interchange-newline">
</body>
</html>
![chat flow](https://github.com/FlowiseAI/Flowise/assets/656347/907698b9-eb13-4a03-8c10-eb46a8a5ed8f)
![llmonitor](https://github.com/FlowiseAI/Flowise/assets/656347/12b561ba-d47e-4c8a-ba8b-0fc488640dd2)

**Comment by Jaredude** [comment]
I see what's going on... You're trying to do everything within the single Conversational Retrieval QA Chain. That will not produce the results that you're looking for.

One way to look at it is that you're trying to get a single prompt to perform separate things. You can get a prompt to perform multiple things (which your current prompt does), but it cannot perform separate things. In other words, you're trying to get the conversation to update its own prompt by referencing itself and then calling itself again within the output from the original call. It's not capable of doing that.

You would need to perform prompt chaining to get the results that you're looking for. The output of one prompt would produce the input for another prompt. Then you would need figure out which agent to use to allow for a conversation using the prompt chain as a tool.

Hope that makes sense.

There is more than one way to handle what you're trying to do, but having a single CRQAC do all of it will not accomplish it.

**Comment by HenryHengZJ** [comment]
@matrixmayhem if you have the first message sent, the rephrase prompt will not be used. When you have a 2nd message sent, then it will be used.
<img width="760" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/afa69049-8f55-409a-8073-e4626a52d7d7">
<img width="605" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/db0cdb45-c044-4dc2-a6ad-b68386226ffd">

**Comment by matrixmayhem** [comment]
I have tired it with multiple message and it still uses the user mesage instead of the 'rephrased message'. This problem has started after the UI update to the "Conversational Retrival QA Chain" node.
![3 questions](https://github.com/FlowiseAI/Flowise/assets/656347/5f84def6-3426-48e3-919e-c0f80f15d29e)
![3 questions trace](https://github.com/FlowiseAI/Flowise/assets/656347/55487ad5-e5f3-46e6-a821-692a69f65d21)
