### ISSUE TITLE
[BUG] Environnement pinecone is missing .. 

### ISSUE THREAD

**Issue by muhammedInan** [FlowiseAI/Flowise#1743]
![image](https://github.com/FlowiseAI/Flowise/assets/11853317/49ef6f19-87d3-4922-9bb1-1bce9a4a08bf)

Environnement pinecone is missing.in Flowise

**Comment by muhammedInan** [comment]
yes because I've filled in the correct api and index and yet I get this error
 The API key you provided was rejected while calling
https://api.pinecone.io/indexes/chatbot
. Please check your configuration values and try again. You can find the configuration values for your project in the Pinecone developer console at
https://app.pinecone.io/

**Comment by HenryHengZJ** [comment]
Okay with the new [PR](https://github.com/FlowiseAI/Flowise/pull/1691) just merged, I've tested both pod and serverless, they are working fine. You can test it again once a new release is out

**Comment by HenryHengZJ** [comment]
released in `1.5.1` now! feel free to reopen if issue still persists

**Comment by muhammedInan** [comment]
error is still here , flowise reject api pinecone . 
Can you test the integration between openAi and pinecone and retrieval chain please ?
