### ISSUE TITLE
[FEATURE] PLease give proper interface for particular bot chat and what i mean by this is that there should be option to open nice frontend for chatting instead of what options are currently available in flowise

### ISSUE THREAD

**Issue by HakaishinShwet** [FlowiseAI/Flowise#1747]
it is not too comfortable for me to conversate in present available options available in flowise like no one use mini conversation mode and in max size too it is just overlay kinda thing over flowsise graph but what i actually want is proper different url in which chat interface direct open for that particular bot so that i can bookmark that link and directly go to conversate with that bot instead of first going in flowise and then clicking two three times and then too not get what i actually want. Hope i am able to make you understand this and this option will not only benefit me but others too and make communication with bot faster and easier and in proper ui instead of bigger overlay of conversation ;-))
Thanks for hardwork devs

**Comment by HenryHengZJ** [comment]
is this the Share Chatbot link?
<img width="707" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/d5945d9e-4bd4-4915-9bb7-b496952bc9fb">

it opens up a new chatbot page where you can just bookmark it

**Comment by HakaishinShwet** [comment]
@HenryHengZJ thanks i didnt knew about it :-) solved my issue
