### ISSUE TITLE
Error status code 429 is displayed in the chat

### ISSUE THREAD

**Issue by ghost** [FlowiseAI/Flowise#175]
Everytime I go to chat with the model, it hangs, and after restarting the node server, some error is dsplayed from the previous session in the chat
![error](https://github.com/FlowiseAI/Flowise/assets/134267736/5b0c3cc9-f812-4881-8fce-092278f38815)

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/Flowise/issues/134

**Comment by lovishescobar** [comment]
created a new key multiple times, still the same error

**Comment by fischcheng** [comment]
you might want to refer to OpenAI API documentation. 
https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details

I am paying the ChatGPT+ $20/month, but that does not include free a paid API key, you need to updated to a paid plan for OpenAI API. The $18 quota came with the $20/month ChatGPT+ has an expiration date (for me that's long gone). Hope this help.

**Comment by lovishescobar** [comment]
Yeah running models locally now using langchain. Have built a custom UI using streamlit
