### ISSUE TITLE
[BUG] DynamoDB Chat Memory error

### ISSUE THREAD

**Issue by gabrielcmk** [FlowiseAI/Flowise#1752]
**Describe the bug**
DynamoDB Chat Memory node causes the flow to stop working and keep returning the _**Cannot convert undefined or null to object**_ message.

**To Reproduce**

1. Link a DynamoDB Chat Memory node to a Conversational QA Retrieval QA Chain's Memory input.
2. Test the flow sending any message through the chat and it should return the error message

**Expected behavior**
Return to functioning state as before the 1.5.0 version.

**Screenshots**
![step_1](https://github.com/FlowiseAI/Flowise/assets/83649489/2f3ed754-a110-4b2f-857e-02eeba08080b)
![step_2](https://github.com/FlowiseAI/Flowise/assets/83649489/eb6f3da0-4afd-41a5-b17a-83f4de6f9a36)

**Setup**
-   Hosted on AWS ECS (Linux)
-   Flowise version 1.5.0
-   Local machine using Windows 10
-   Google Chrome browser

**Additional context**
Was working perfectly before the 1.5.0 version update, which I did last week. After the update, every flow with this setup started experiencing this behavior. Other flows without the DynamoDB Chat Memory node are still working fine. If I remove the DynamoDB Chat Memory node of this exact flow it also works fine.

**Comment by HenryHengZJ** [comment]
@Jaredude I think you've tested DynamoDB before and its working right? Any idea?

**Comment by Jaredude** [comment]
This should be fixed with this PR: https://github.com/FlowiseAI/Flowise/pull/1697

@gabrielcmk If you pull the latest from GitHub main branch, this issue should be fixed.

@HenryHengZJ I'm not familiar with the CI/CD for the Flowise docker container. Does a new tag need to be created to update the container so that it can be pulled via `docker pull flowiseai/flowise` for those with Flowise running via docker?

**Comment by gabrielcmk** [comment]
> oh yeah its not pushed to a new version yet, we will have to cut the release, publish to npm, push a new docker image with the latest version.

Got it. Thanks, guys @Jaredude @HenryHengZJ! 
I'm gonna rollback my version until this fix is released on Docker.

**Comment by HenryHengZJ** [comment]
released in `1.5.1` now! feel free to reopen if issue still persists
