### ISSUE TITLE
@matrixmayhem if you have the first message sent, the rephrase prompt will not be used. When you have a 2nd message sent, then it will be used.

### ISSUE THREAD

**Issue by matrixmayhem** [FlowiseAI/Flowise#1769]
@matrixmayhem if you have the first message sent, the rephrase prompt will not be used. When you have a 2nd message sent, then it will be used.
<img width="760" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/afa69049-8f55-409a-8073-e4626a52d7d7">
<img width="605" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/db0cdb45-c044-4dc2-a6ad-b68386226ffd">

_Originally posted by @HenryHengZJ in https://github.com/FlowiseAI/Flowise/issues/1742#issuecomment-1952745253_
 
I have tired it with multiple message and it still uses the user mesage instead of the 'rephrased message'. This problem has started after the update to the "Conversational Retrival QA Chain" node.

![3 questions](https://github.com/FlowiseAI/Flowise/assets/656347/6fda91f7-7251-44a2-946a-af64e25ce661)
![3 questions trace](https://github.com/FlowiseAI/Flowise/assets/656347/b007d2fe-0708-47c9-966a-e6fab524b32c)

**Comment by Jaredude** [comment]
Your chat doesn't have a memory node. Add a simple memory node, and you'll see the chat_history value include prior messages.

**Comment by Jaredude** [comment]
Do you have screenshots from the prior version where this was working? Or can you rollback and show screenshots of the prior node working as you're expecting it to?

**Comment by matrixmayhem** [comment]
Corrected spelling and grammar:
"I installed version 1.3.9 and it behaved exactly as it should. Here are the screenshots:
The second question, "Who is Luke?" gets rephrased and asked as, "Can you please provide more information on who Luke is?"
Then the third question is asked, "Who is his father?" gets rephrased and asked as, "Who is Anakin Skywalker?" (screenshot attached below):
The problem in version 1.5.0 is that the question does get rephrased but is not passed to the language model. This is clearly a bug. What's the point of this intermediate step of rephrasing the question if it is not passed to the language model?"

![1 3 9 messages](https://github.com/FlowiseAI/Flowise/assets/656347/a8aa8a1b-33cd-4a66-ada3-68660dd0c23c)
![1 3 9 nodes](https://github.com/FlowiseAI/Flowise/assets/656347/aa82b67e-aeb9-4176-a6f2-0c7033f3b41f)
![1 3 9 llmonitor](https://github.com/FlowiseAI/Flowise/assets/656347/ce7ea079-cde6-4ddb-af45-e307e35c2550)
![1 3 9 question rephrase](https://github.com/FlowiseAI/Flowise/assets/656347/817336a4-8ff8-45ac-add9-f442a4d6462d)
![1 3 9 rephrased question asked](https://github.com/FlowiseAI/Flowise/assets/656347/d5eaf633-2081-409b-a23c-6be0d9c33ce7)

**Comment by Jaredude** [comment]
@matrixmayhem Thanks for the additional information. That has helped me identify that the QA chain was working up to at least version 1.4.9.

**Comment by HenryHengZJ** [comment]
the rephrased question get passed to vector store to get relevant context, not LLM

1.) Rephrased question:
<img width="974" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/1cd313d2-9bfe-445d-9414-fda842ad4453">

2.) Vector Retriever:
<img width="975" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/c43f0c3c-5534-421e-8224-91096e5d59b2">
