### ISSUE TITLE
[FEATURE] Pinecone: Retrieve X Chunks Before & Y Chunks after the Matching Chunk

### ISSUE THREAD

**Issue by mikehudson2** [FlowiseAI/Flowise#1770]
In the Flowise Vectara node, in response to a query, Vectara similarity matches the query to a single sentence chunk in the VDB, and retrieves that sentence. It can _**also**_ optionally retrieve x sentences before and y sentences after the matching sentence. This is really useful for bringing in context wider than the matching chunk.

Would it be possible to do something similar in Pinecone or Weaviate so that the matching chunk is retrieved _**together with**_ a specified number of contiguous chunks before and after it?

**Comment by HenryHengZJ** [comment]
this is a functionality offered by Vectara, I'm not sure if Pinecone or Weaviate offer similar functionality

**Comment by mikehudson2** [comment]
I don't think P or W do this out-of-the-box. But something similar would be achievable using Langchain's Parent Document Retriever: [https://python.langchain.com/docs/modules/data_connection/retrievers/parent_document_retriever](url). Any chance of that being added?
