### ISSUE TITLE
Flowise installation from Dockerhub not running

### ISSUE THREAD

**Issue by HPrei** [FlowiseAI/Flowise#1774]
I have installed the latest version of Flowise from docker hub on my Qnap-NAS in container station. The installation worked, but Flowise always starts running but stops again immediately.

Do I have to enter additional parameters in the environment? Are there any helpful tips for a beginner?

**Comment by Proteusiq** [comment]
> I have installed the latest version of Flowise from docker hub on my Qnap-NAS in container station. The installation worked, but Flowise always starts running but stops again immediately.
> 
> Do I have to enter additional parameters in the environment? Are there any helpful tips for a beginner?

Have you tried 
`docker run -d --name flowise -p 3000:3000 flowise start`

I think documentation misses `start`

**Comment by HPrei** [comment]
Thank you very much for your tip. I tried again today on the NAS, unfortunately without success. Flowise works locally on my Macbook, but I would like to run it on the NAS. I also installed n8n from Dockerhub, it worked on the first try!

**Comment by Proteusiq** [comment]
Can you share the logs? of running

`docker run -p 3000:3000 flowise /bin/sh -c 'flowise start'`

**Comment by HPrei** [comment]
An hour ago, I tried it again and it worked. I don't know what I did differently, but it worked today. I did not use Dockerhub, but installed directly with docker compose.

**Comment by Proteusiq** [comment]
Should this not be closed as resolved, @HPrei ?
