### ISSUE TITLE
Implement Agent Swarm Functionality for Advanced LLM Orchestration

### ISSUE THREAD

**Issue by leandrosilvaferreira** [FlowiseAI/Flowise#1780]
**Describe the feature you'd like**
I propose the addition of an agent swarm feature to Flowise, enabling the platform to orchestrate large-scale, decentralized AI agent operations. This feature would allow users to build and manage swarms of AI agents that can work collaboratively to achieve complex goals. Given the potential of agent swarms for enhancing workflow, productivity, and efficiency across various domains, integrating this capability could significantly expand Flowise's applicability and appeal, particularly in fields like data analysis, robotics, and healthcare.

**Additional context**
Agent swarms represent a sophisticated approach to AI, where multiple agents operate in concert, inspired by natural phenomena like bird flocks or fish schools. This decentralization offers robustness, scalability, and flexibility, making it a powerful tool for complex problem-solving and automation tasks.

**Comment by petrevisan** [comment]
this feature it would be really helpfull!

**Comment by marcos-inja** [comment]
Fantastic, it would be great to have this feature!

**Comment by HenryHengZJ** [comment]
we're working on integrating multi agents using langgraph into flowise!

**Comment by HenryHengZJ** [comment]
released! https://github.com/FlowiseAI/Flowise/pull/2319 💯
