### ISSUE TITLE
[FEATURE] Jina AI support

### ISSUE THREAD

**Issue by davepoon** [FlowiseAI/Flowise#1787]
**Describe the feature you'd like**
Adding Jina AI to Flowise will be a valuable enhancement for embedding nodes.

Additionally, Langchain JS has support for the Jina AI embedding models integration,
https://python.langchain.com/docs/integrations/text_embedding/jina

**Additional context**
We discovered that the Jina embedding is superior to bge/gte solutions and supports multiple languages, making it a valuable alternative to OpenAI embedding.

**Comment by aimzieslol** [comment]
This would be great! Would a workaround be using the `Ollama Embeddings` or the `Custom Open AI Embeddings` nodes?

**Comment by definitelynotchirag** [comment]
@davepoon Hey would like to work on this issue, can i pick it up?

**Comment by HenryHengZJ** [comment]
> @davepoon Hey would like to work on this issue, can i pick it up?

you can definitely work on it!

**Comment by definitelynotchirag** [comment]
@HenryHengZJ @davepoon Hello I have made a pull Request, could you please look into it?

**Comment by definitelynotchirag** [comment]
#3355

**Comment by davepoon** [comment]
@definitelynotchirag thanks for the awesome work!!
