### ISSUE TITLE
[FEATURE] regard chat module as LLM

### ISSUE THREAD

**Issue by chinesewebman** [FlowiseAI/Flowise#18]
since there are chatgpt-3.5-turbo (the most cheap one) and getp-4 32k (the most powerful one), why not put it as LLM?

or could you add chatgpt-3.5-turbo and gpt4 to openai LLM definition? thanks!

**Comment by HenryHengZJ** [comment]
the models are there for ChatOpenAI: https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts#L31
![image](https://user-images.githubusercontent.com/26460777/232309938-7581f2e4-f037-4469-a938-5d0fcbc351fe.png)

**Comment by chinesewebman** [comment]
thanks！
