### ISSUE TITLE
[FEATURE]deploy on vercel

### ISSUE THREAD

**Issue by 541013515** [FlowiseAI/Flowise#180]
**Describe the feature you'd like**
deploy on vercel

**Additional context**
how to deploy on vercel

**Comment by HenryHengZJ** [comment]
related to this - https://github.com/FlowiseAI/Flowise/issues/81

In short, we can't really deploy on vercel (maybe im wrong) because its a monorepo with backend+frontend. Vercel is for frontend deployment + edge serverless function.
