### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading '_def')

### ISSUE THREAD

**Issue by SchmitzBen-UC** [FlowiseAI/Flowise#1801]
I am trying to create a Chatbot using the "Open AI Assitent" Flow from the Marketplace, but whenever I test it in Flowise i get the error: Cannot read properties of undefined (reading '_def') instead of an answer from the assistent. 

I directly followed this tutorial: https://www.youtube.com/watch?v=DW6D1nAx5Z0, where it worked.

1. Go to 'Marketplace'
2. Choose the "Open AI Assistent"
3.Create an Assistent with custom Instructions, Model GPT-4-1106 and a viable Open AI Key
4. Try to Test it in the Flowise UI and see the Error i described

I Expected to see a similar answer as to what i saw in the OpenAI - Playground

<img width="218" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/161053217/bf85a8c8-b856-4384-b09e-a0205fdff94d">

[240223-WEBCON BOT Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14386969/240223-WEBCON.BOT.Chatflow.json)

**Setup**
-   `npx flowise start`
-   Flowise Version 1.5.1
-   Windows
-   edge

**Additional context**
This is the output in the console: 
<img width="893" alt="Screenshot 2024-02-23 163236" src="https://github.com/FlowiseAI/Flowise/assets/161053217/a1f292e5-9338-4fb5-99f6-cf597b07f321">

Thanks for your help!

**Comment by HenryHengZJ** [comment]
I think there was some error on the template, will update it. But in the meantime, if you try creating one from scratch, it works

**Comment by HenryHengZJ** [comment]
pushed a fix to the template, verified its now working - https://github.com/FlowiseAI/Flowise/commit/79812a23e4ceb50bec35b34f74be2c085bbb0330
