### ISSUE TITLE
[FEATURE] Consume Chatflow in Slack

### ISSUE THREAD

**Issue by whyike** [FlowiseAI/Flowise#1809]
Is it possible to make conversion with slack bot (PM) that send questions to FlowiseAI Q&A Chatflow and sending answers back to sender??

**Comment by HenryHengZJ** [comment]
not natively, you'll have to use flowise API and connect with other third party automation provider like Zapier, Make.com etc https://youtu.be/rGehI5PNP2o?si=1oBaqoNRV9gA0MHk

**Comment by yairyairyair** [comment]
+1 i would really like this feature REALLY @HenryHengZJ

**Comment by NOGIT007** [comment]
It seems every time you build something with Flowise within a Company the input/output goes through Slack as the main User interface. It would be nice if Flowise could make an integration towards Slack simpler without going through 3.party vendor. @HenryHengZJ @whyike

**Comment by MortenAndreNilsson** [comment]
Integration with Slack would be very beneficial for us as we are using Slack as the main channel, Embedding Agents into Slack will enable us to expand usage a lot.

**Comment by orlinradev** [comment]
+1
