### ISSUE TITLE
Support config to change the background color of title and title text

### ISSUE THREAD

**Issue by netgfx** [FlowiseAI/Flowise#1828]
**Describe the feature you'd like**
As described here: https://github.com/FlowiseAI/FlowiseEmbedReact/issues/3

The Flowise embed code has properties to support change of the Embed or Share title background color and text color, but Flowise doesn't expose the properties on the config object of the embed.

**Comment by HenryHengZJ** [comment]
You can change the title color:
```
theme: {
    button: {
        backgroundColor: '#3B81F6' // <-- change this one
    }
}
```

**Comment by netgfx** [comment]
It could use some better documentation and naming convention

**Comment by HenryHengZJ** [comment]
> It could use some better documentation and naming convention

agreed, we will separate out into different naming like `titleBarColor` etc.

**Comment by netgfx** [comment]
I guess if the fullscreen component wasn't used from shadow-dom and existed as a standalone normal React component or plain HTML component it could be extended more easily but I get that you would have to support two components then because the bubble-chat one needs to be in shadow-dom to isolate styles from the hosting site.
