### ISSUE TITLE
[FEATURE] Update Mistral Components new Models and Functions

### ISSUE THREAD

**Issue by m4rcster** [FlowiseAI/Flowise#1833]
**Describe the feature you'd like**

Mistral launched on 26.02.2024 their new models and a function calling API. Is there a plan to update the components to reflect this? And add a function calling component?

https://mistral.ai/news/mistral-large/

**Additional context**

https://docs.mistral.ai/guides/model-selection/
https://docs.mistral.ai/guides/function-calling/

**Comment by HenryHengZJ** [comment]
Released to `v1.6.2`
