### ISSUE TITLE
Can we allow the front-end to pass in documents for Q&A 可否允许前端传入文件，进行问答

### ISSUE THREAD

**Issue by ye7love7** [FlowiseAI/Flowise#1837]
从市场上的例子来看，似乎都是由后台直接配置哪些文件，那么前台是否可以提供任何功能，直接进行一次性问答以及知识库管理？谢谢！
Looking at market's examples, it seems to be all about which files are configured directly by the backend, is there any functionality that can be provided to the frontend for direct one-off Q&A as well as knowledge base management? Thank you!

**Comment by HenryHengZJ** [comment]
we currently dont offer front end portal for these type of functionalities yet. just the embedded chatbot and api - https://docs.flowiseai.com/using-flowise/embed
