### ISSUE TITLE
[BUG] Deprecated Import from "langchain/schema"

### ISSUE THREAD

**Issue by maulanaakbardj** [FlowiseAI/Flowise#1839]
**Describe the bug**
After updating Flowise to version 1.6.0, a warning appeared in the output, stating:
```
[WARNING]: Importing from "langchain/schema" is deprecated.
Instead, please import from the appropriate entrypoint in "@langchain/core" or "langchain".
This will be mandatory after the next "langchain" minor version bump to 0.2.
```

**To Reproduce**

1. Update Flowise to version 1.6.0.
2. Run the command npx flowise start.
3. Observe the console output to receive the warning mentioned above.

**Expected behavior**

**Screenshots**
<img width="305" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/67249292/9b05bb48-a77b-4f55-af2f-b40e697ac466">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
- Installation: npx flowise start
- Flowise Version: 1.6.0
- Operating System: Windows
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
resolved via this [PR](https://github.com/FlowiseAI/Flowise/pull/1856)
