### ISSUE TITLE
[BUG] Chatbot not running if flowise isnt running

### ISSUE THREAD

**Issue by SchmitzBen-UC** [FlowiseAI/Flowise#1841]
**Describe the bug**
My Chatbot build with Flowise isnt running if i dont have flowise running beside it.

I had a [bug](https://github.com/FlowiseAI/Flowise/issues/1801) where it wouldnt even answer when i tested it in the flowise interface, however, that was fixed by recreating the Template i originally used. 

**Expected behavior**
Of Course i want the Chatbot to respond to questions from other people.

**Flow**
[chatbot try Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14449908/chatbot.try.Chatflow.json)

**Setup**
-   npx flowise start
-   Flowise Version 1.5.1
-   OS: Windows
-   edge

Do i need to adjust things in the outputted embed code for it to work as expected?

**Comment by NityaSG** [comment]
Flowise needs to be running all the time in the background. Your chatbot invokes the endpoint of your chatflow which is live on flowise.

**Comment by NityaSG** [comment]
- You need to deploy the flowise app on cloud first - AWS/GCP/Render etc. 
- After that you will see an embed option inside a chatflow on top right. 
- Copy the Html popup code provided there in the flowise and paste it in your wordpress' html <body></body> tag

**Comment by SchmitzBen-UC** [comment]
i already have the html embed option. How exactly would i go about deploying the app/ chatflow on cloud?

**Comment by NityaSG** [comment]
https://docs.flowiseai.com/configuration/deployment

**Comment by SchmitzBen-UC** [comment]
I followed the steps of the video on https://docs.flowiseai.com/configuration/deployment/azure and it all worked out but now the bot is not responding
