### ISSUE TITLE
[BUG] 504 when Upserting to Pinecone

### ISSUE THREAD

**Issue by mikehudson2** [FlowiseAI/Flowise#1844]
504 error when upserting to Pinecone with 2.72MB .txt file chunked in 100 characters no overlap.  

IDE Terminal reads:
@mikehudson2 ➜ /workspaces/Flowise (main) $ flowise start
2024-03-01 11:08:11 [INFO]: Starting Flowise...
2024-03-01 11:08:12 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-03-01 11:08:12 [INFO]: 📦 [server]: Data Source has been initialized!
2024-03-01 11:10:47 [INFO]: 🖊 PUT /api/v1/chatflows/d4b86ac9-aee0-411e-8241-d151c2debe61
2024-03-01 11:11:00 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/d4b86ac9-aee0-411e-8241-d151c2debe61

<--- Last few GCs --->

[5720:0x7488200]   326849 ms: Mark-Compact 2039.6 (2064.5) -> 2039.4 (2068.7) MB, 150.66 / 0.00 ms  (average mu = 0.270, current mu = 0.106) allocation failure; scavenge might not succeed
[5720:0x7488200]   327108 ms: Mark-Compact (reduce) 2047.0 (2072.5) -> 2042.7 (2065.2) MB, 69.10 / 0.01 ms  (+ 100.3 ms in 32 steps since start of marking, biggest step 31.9 ms, walltime since start of marking 222 ms) (average mu = 0.313, current mu = 0.3

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xca5430 node::Abort() [node]
 2: 0xb7807d  [node]
 3: 0xeca0b0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0xeca397 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 5: 0x10dc0e5  [node]
 6: 0x10f3f68 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0x10f5eda v8::internal::Heap::HandleGCRequest() [node]
 8: 0x1061547 v8::internal::StackGuard::HandleInterrupts() [node]
 9: 0x1219b96 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
10: 0x121e589 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
11: 0x121b054 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<true>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
12: 0x121e589 v8::internal::JsonStringifier::Result v8::internal::JsonStringifier::Serialize_<false>(v8::internal::Handle<v8::internal::Object>, bool, v8::internal::Handle<v8::internal::Object>) [node]
13: 0x121f376 v8::internal::JsonStringify(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [node]
14: 0xf5c192 v8::internal::Builtin_JsonStringify(int, unsigned long*, v8::internal::Isolate*) [node]
15: 0x193cdf6  [node]
Aborted (core dumped)
[Pinecone Upserter - Custom Chatflow 2.json]

**Screenshots**

**Flow**
[Pinecone Upserter - Custom Chatflow 2.json](https://github.com/FlowiseAI/Flowise/files/14460435/Pinecone.Upserter.-.Custom.Chatflow.2.json)
![Screenshot](https://github.com/FlowiseAI/Flowise/assets/38255405/b547426a-3a16-4717-a367-ef3922770228)

**Setup**
-   Flowise Version 1.6
-   Browser: latest chrome
-   Running in web version of Github Codespaces. 
-   Default Codespaces machine is 2-core 8GB RAM but similar result with 4-core 16M RAM

**Additional context**
Upserting with larger chunk size (500) was unproblematic.

**Comment by HenryHengZJ** [comment]
sounds like the Github Codespaces was running out of RAM/memory, I'd recommend to deploy to cloud or run it locally - https://docs.flowiseai.com/configuration/deployment

**Comment by mikehudson2** [comment]
For anyone else experiencing the same problem upgrading from 2-core 8GB RAM to 4-core 16M RAM in Codespaces did not help.

**Comment by ruelluna** [comment]
I'm in the standard plan of Render and this error still exist.
![Screenshot 04-17-2024 18 38 44](https://github.com/FlowiseAI/Flowise/assets/982036/da9b38a9-d659-4c29-b9d8-b2e29c61f64d)
