### ISSUE TITLE
Error: Expected a Runnable, function or object. Instead got an unsupported type.

### ISSUE THREAD

**Issue by Shonazarovmirkamol** [FlowiseAI/Flowise#1850]
**Describe the bug**
When the question is asked, it doesn't return an answer but "Error: Expected a Runnable, function or object. Instead got an unsupported type."

**To Reproduce**
1. Set up flow as shown in the screenshot, ask question

**Expected behavior**
I want an answer to the question

**Screenshots**
![flowise](https://github.com/FlowiseAI/Flowise/assets/68827554/82b417a4-5290-4a8b-8cef-184d97079be1)
![flowise1](https://github.com/FlowiseAI/Flowise/assets/68827554/505874c7-bd4c-4ab2-b066-5864c14f523a)

**Flow**
If applicable, add exported flow to help replicate the problem.
[rag advice Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14463105/rag.advice.Chatflow.json)
**Setup**
-   Installation [`npx flowise start`]
-   Flowise Version [flowise@1.6.0]
-   OS: [Windows]
-   Browser [chrome]

**Additional context**

**Comment by Shonazarovmirkamol** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/68827554/13e7af56-6a4c-420b-9182-d03d8cc754e5)

**Comment by HenryHengZJ** [comment]
have you tried upserting the documents to vector store with the top right green button?
<img width="1166" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/c6bdd86d-7628-4025-8298-c29271e838bb">

Also, attached is the chatflow:
[Conversation Retrieval QA Chain Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14471337/Conversation.Retrieval.QA.Chain.Chatflow.json)
