### ISSUE TITLE
[BUG] custom tool not called by Conv. Agent

### ISSUE THREAD

**Issue by remiwuillemin** [FlowiseAI/Flowise#1853]
**Describe the bug**
I have a specific custom tool that take 3 arguments (firstname, lastname, email) and call a web service with these args.
From a chatbot, I want the user to be asked for these arguments and the web service to be called.

I can't make it works as expected and I suspect it could be a bug.

**To Reproduce**
if I use  the OpenAi Function Agent, I can see that the custom tool is correctly executed (web service called) but chatbot does not ask for firstname/lastname/email and everytime, John Doe details are given.
![image](https://github.com/FlowiseAI/Flowise/assets/58466566/4d6995f5-f0b6-4b40-bd5d-634cf18055d0)
Here are the logs from the console :
![image](https://github.com/FlowiseAI/Flowise/assets/58466566/e946e124-6913-44a7-8633-1255994160de)

If I use a conversational agent, the behavior is totally the opposite : I'm prompted for my details but then the custom tool is not executed. 
![image](https://github.com/FlowiseAI/Flowise/assets/58466566/0c169a4d-ba97-43cb-96e6-3a2664677537)

Console: 
![image](https://github.com/FlowiseAI/Flowise/assets/58466566/a855268f-8d74-4bfc-8f31-c62401b2fa2a)

I have tried many combinaisons with different agent and LLM.. No chance so far !

**Additional context**
Flowise on docker (compose), v1.6.0

**Comment by remiwuillemin** [comment]
Solved ! reading again this ticket, I saw the issue was somehow related to arguments mapping.
In the custom tool prompt, "first name", "last name" and "email" was specified to be asked by the agent. OpenAI Function Agent was able to map that to firstname/lastname/email but the conversation  agent was doing the mapping to first_mane/last_name/email and so, failed to invoke the custom tool code with the correct argument name...

**Comment by iloukou** [comment]
hi , how did you solved this please

**Comment by iloukou** [comment]
> Solved ! reading again this ticket, I saw the issue was somehow related to arguments mapping. In the custom tool prompt, "first name", "last name" and "email" was specified to be asked by the agent. OpenAI Function Agent was able to map that to firstname/lastname/email but the conversation agent was doing the mapping to first_mane/last_name/email and so, failed to invoke the custom tool code with the correct argument name...

how did you solve this please
