### ISSUE TITLE
[BUG] The automatically generated curl command is missing the `\`

### ISSUE THREAD

**Issue by VernHe** [FlowiseAI/Flowise#186]
**Describe the bug**
After quickly deploying the service via Docker, using the `Translator` template and testing with the automatically generated curl, I found that the `\`·

**Screenshots**
<img width="876" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/44822675/4290c033-6abb-421f-b02f-bd89e6f230ee">

**Setup**

-   OS: Debian 11
-   Browser chrome

**Additional context**
I saw a similar problem mentioned in the history of the problem, but this good line has not been completely fixed

**Comment by HenryHengZJ** [comment]
if you resync fork, does the issue still occurs?

should be resolved with https://github.com/FlowiseAI/Flowise/pull/145

**Comment by HenryHengZJ** [comment]
Update is pushed to new release. Let me know if you still see the issue @VernHe

**Comment by VernHe** [comment]
If the docker image has been updated, then theoretically this problem should no longer occur, and I've seen the source code, and it has been fixed. But I did start it as docker-compose directly in the docker directory of the source according to the README documentation.
I will try to reproduce it again. @HenryHengZJ
