### ISSUE TITLE
Unable to run flowise using docker. 

### ISSUE THREAD

**Issue by gkgourav45** [FlowiseAI/Flowise#1862]
**Image creation fails**
yarn build command gives error
**To Reproduce**
1. clone repo
2. Run docker build -t flowise:1.5.0 .
3. check log
4. . See error
=> [11/12] COPY . .                                                                                          0.9s 
 => ERROR [12/12] RUN yarn build                                                                             28.8s 
------
 > [12/12] RUN yarn build:
#16 1.484 yarn run v1.22.19
#16 1.542 $ turbo run build
#16 2.146
#16 2.146 Attention:
#16 2.146 Turborepo now collects completely anonymous telemetry regarding usage.
#16 2.146 This information is used to shape the Turborepo roadmap and prioritize features.
#16 2.146 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, 
by visiting the following URL:
#16 2.146 https://turbo.build/repo/docs/telemetry
#16 2.146
#16 2.670 • Packages in scope: flowise, flowise-components, flowise-ui
#16 2.670 • Running build in 3 packages
#16 2.670 • Remote caching disabled
#16 2.703 flowise-ui:build: cache miss, executing c7f792750140de21
#16 2.708 flowise-components:build: cache miss, executing 5b190549943e5095
#16 3.021 flowise-components:build: $ tsc && gulp
#16 3.040 flowise-ui:build: $ craco build
#16 5.300 flowise-ui:build: Creating an optimized production build...
#16 9.566 flowise-ui:build: One of your dependencies, babel-preset-react-app, is importing the
#16 9.566 flowise-ui:build: "@babel/plugin-proposal-private-property-in-object" package without
#16 9.566 flowise-ui:build: declaring it in its dependencies. This is currently working because
#16 9.566 flowise-ui:build: "@babel/plugin-proposal-private-property-in-object" is already in your
#16 9.566 flowise-ui:build: node_modules folder for unrelated reasons, but it may break at any time.
#16 9.566 flowise-ui:build:
#16 9.566 flowise-ui:build: babel-preset-react-app is part of the create-react-app project, which
#16 9.566 flowise-ui:build: is not maintianed anymore. It is thus unlikely that this bug will
#16 9.566 flowise-ui:build: ever be fixed. Add "@babel/plugin-proposal-private-property-in-object" to
#16 9.566 flowise-ui:build: your devDependencies to work around this error. This will make this message
#16 9.566 flowise-ui:build: go away.
#16 9.566 flowise-ui:build:
#16 27.71 flowise-components:build: nodes/memory/MongoDBMemory/MongoDBMemory.ts(121,17): error TS2322: Type '{ messages: { $each: StoredMessage[]; }; }' is not assignable to type 'PushOperator<Document>'.
#16 27.71 flowise-components:build:   Type '{ messages: { $each: StoredMessage[]; }; }' is not assignable to type 'NotAcceptedFields<Document, readonly any[]>'.
#16 27.71 flowise-components:build:     Property 'messages' is incompatible with index signature.
#16 27.71 flowise-components:build:       Type '{ $each: StoredMessage[]; }' is not assignable to type 'undefined'.#16 27.71 flowise-components:build: nodes/memory/MongoDBMemory/MongoDBMemory.ts(177,21): error TS2322: Type '{ messages: { $each: StoredMessage[]; }; }' is not assignable to type 'PushOperator<Document>'.
#16 27.71 flowise-components:build:   Type '{ messages: { $each: StoredMessage[]; }; }' is not assignable to type 'NotAcceptedFields<Document, readonly any[]>'.
#16 27.71 flowise-components:build:     Property 'messages' is incompatible with index signature.
#16 27.71 flowise-components:build:       Type '{ $each: StoredMessage[]; }' is not assignable to type 'undefined'.#16 27.71 flowise-components:build: nodes/memory/MongoDBMemory/MongoDBMemory.ts(189,21): error TS2322: Type '{ messages: { $each: StoredMessage[]; }; }' is not assignable to type 'PushOperator<Document>'.
#16 27.71 flowise-components:build:   Type '{ messages: { $each: StoredMessage[]; }; }' is not assignable to type 'NotAcceptedFields<Document, readonly any[]>'.
#16 27.71 flowise-components:build:     Property 'messages' is incompatible with index signature.
#16 27.71 flowise-components:build:       Type '{ $each: StoredMessage[]; }' is not assignable to type 'undefined'.#16 27.81 flowise-components:build: error Command failed with exit code 2.
#16 27.81 flowise-components:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
#16 27.82 flowise-components:build: ERROR: command finished with error: command (/usr/src/packages/packages/components) /tmp/yarn--1709542001736-0.599332845192742/yarn run build exited (2)
#16 27.87 flowise-components#build: command (/usr/src/packages/packages/components) /tmp/yarn--1709542001736-0.599332845192742/yarn run build exited (2)
#16 27.88
#16 27.88  Tasks:    0 successful, 2 total
#16 27.88 Cached:    0 cached, 2 total
#16 27.88   Time:    25.723s
#16 27.88 Failed:    flowise-components#build
#16 27.88
#16 27.88  ERROR  run failed: command  exited (2)
#16 28.66 error Command failed with exit code 2.
#16 28.66 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 2

**Expected behavior**
Image should be created successfully

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-  docker version 20.10.21
-   Flowise Version  1.5.0
-   OS: [Windows,]

**Additional context**

**Comment by automaton82** [comment]
I think this was fixed in https://github.com/FlowiseAI/Flowise/commit/52dbfc6a4f61f11b09b4cd8dc5ad77156291db3c ?

**Comment by rrubio** [comment]
You might want to do a docker pull insteall. This works right away for me. I followed this example and installed on a linux box - https://docs.flowiseai.com/configuration/deployment/digital-ocean refer to this section.

```
docker pull flowiseai/flowise
```
