### ISSUE TITLE
[BUG] The OpenAI Embedding Node for LamaIndex does not work for 3072 vector dimension

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#1864]
The OpenAI Embedding Node for LamaIndex is fixed at vector dimension 1536, independently if you select the text-embedding-3-large model which is 3072.

This produces a error message and it does not index any data at Pinecone.

The node works for text-embedding-ada-002 / 1536 as expected.

Version 1.6.0

<img width="559" alt="0001" src="https://github.com/FlowiseAI/Flowise/assets/138339291/65b1ae9b-6334-42af-81aa-6b8bf6834627">
<img width="382" alt="0002" src="https://github.com/FlowiseAI/Flowise/assets/138339291/1e3ca535-caf6-4a6a-b925-23946692dd6e">
<img width="284" alt="0003" src="https://github.com/FlowiseAI/Flowise/assets/138339291/9fcebf2c-b734-477f-a1c0-9519f05f1112">

**Comment by HenryHengZJ** [comment]
I dont think we hard-coded `1536`, its undefined and we let the OpenAI SDK to figure out what dimension to use depending on the model.

**Comment by Codechilla** [comment]
Same problem, but with Qdrant (local) instead of Pincone.
