### ISSUE TITLE
[BUG] Starter Prompt appearance issues

### ISSUE THREAD

**Issue by tone-o** [FlowiseAI/Flowise#1865]
**Describe the bug**

- if there are more than 2-3 starter prompts: they are hidden
- for a longer starter prompts the text is cut
- the starter prompts cannot be shown vertically
- there is no scroll, if they don't fit into the view

**To Reproduce**

1. Create a flow with conversation retrieval QA chain
2. Add 3 or more Starter Prompts
3. Use a longer name for the third Prompt like "Change email or address"
4.  Save the flow
5. Open the new chat to see how the starter prompts look

**Expected behavior**

- To show all starter prompts
- To not cut the last one
- to see the starter flows filling the vertical area if they don't fir at the bottom

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/143943820/89bd9969-564a-4c6f-828f-bd7dc2a21188)

**Setup**
-   Installation - `npx flowise start`
-   Flowise Version1.6.0
-   OS: Windows 10
-   Browser Firefox

**Comment by HenryHengZJ** [comment]
[PR](https://github.com/FlowiseAI/Flowise/pull/1941) merged and released to v1.6.2
