### ISSUE TITLE
[QUESTION] Yarn Dev Setup

### ISSUE THREAD

**Issue by ssntouba** [FlowiseAI/Flowise#1871]
Hi,

When I try to run it in dev mode doing (yarn dev) i am having this kind of error in the frontend

Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
ERROR in ./src/App.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/api/apikey.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/api/assistants.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/api/chatflows.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/api/chatmessage.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/api/client.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

ERROR in ./src/api/config.js 1:40-126
Module not found: Error: You attempted to import /Users/x/Desktop/flowise/Flowise/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.

/Users/x/Desktop/flowise/Flowise/node_modules/react-scripts/config/placeholder.js
Referenced from: /Users/x/Desktop/flowise/Flowise/.eslintrc.js
Any help ???

**Comment by HenryHengZJ** [comment]
actually never seen these errors. but suggest you running on higher node version, do a fresh install and rebuild

**Comment by ssntouba** [comment]
still facing this error 
to reproduce :

- git clone https://github.com/FlowiseAI/Flowise.git
- cd Flowise
- create .env file for ui and server port 8080 and 3000
- yarn install
- yarn dev

node version : v20.2.0 ; yarn version : 1.22.11 running on mac m1 

any idea ?

**Comment by automaton82** [comment]
Did you run yarn install inside of the package directories by chance? I've seen similar happen in that situation.

Yarn install must only be run at the root dir, and only once.

**Comment by ssntouba** [comment]
Hi @automaton82  ,

I run it at the root dir just after cloning the project, and still facing these issues. yarn install and yarn dev

**Comment by automaton82** [comment]
It's the one in the repo in .\Dockerfile
