### ISSUE TITLE
[BUG] JSON parsing error

### ISSUE THREAD

**Issue by MrNoname3** [FlowiseAI/Flowise#1879]
Hello!

First of all, thank you for your fantastic work!

I am trying to get the agent to work with the Calculator and BraveSearch API tools. I use Ollama with Mistral. The calculator works fine, but every time I try the BraveSearch API tool, I get a JSON parsing error. I have tried to analyse it using LangSmith, where you can follow how I interacted with it. This is the link, I hope you can check it out:
https://smith.langchain.com/public/e198ef54-c818-4d5c-9545-f7574db4c40b/r

This is my flow:
![flow](https://github.com/FlowiseAI/Flowise/assets/26522650/1ef5fe02-a2f5-41de-b8c4-523899c5b5ed)

I don't know what is causing this JSON parsing error, maybe I did something wrong.

**Comment by HenryHengZJ** [comment]
We'll be working with a dedicated Ollama function agent, from the tracing log, it looks like Mistral is giving incorrect JSON output, causing parse to fail.

We just released MistralAI Tool Agent, which definitely works

**Comment by HenryHengZJ** [comment]
> We'll be working with a dedicated Ollama function agent, from the tracing log, it looks like Mistral is giving incorrect JSON output, causing parse to fail.
> 
> We just released MistralAI Tool Agent, which definitely works

You can now use ToolAgent + (Ollama or Mistral) Chat
