### ISSUE TITLE
Colorcoding or any other indicator what you can chain in

### ISSUE THREAD

**Issue by Fingolf6455** [FlowiseAI/Flowise#1880]
**Describe the feature you'd like**
I you are new to flowise it is really hard to find out what you can chain together and what not. 
Give some simple colorcoding or form coding that let me easily grasp what I can connect.
**Additional context**
I tried to link the OpenAIAssistant Node to any other note and it never worked. The information there is insufficient to inform the user.
Just make stop sign and don't make it look like any other node.
<img width="227" alt="Bildschirmfoto 2024-03-05 um 21 06 58" src="https://github.com/FlowiseAI/Flowise/assets/72171703/ad0d443e-9b4a-4c29-a496-4014be5fbc56">

**Comment by HenryHengZJ** [comment]
We have similar ticket here - https://github.com/FlowiseAI/Flowise/issues/1375. Yes its a UI enhancment we plan to work on.
