### ISSUE TITLE
[BUG] The sorting done to place "Flowise Docs QnA" at the beginning is undone by alphabetical sorting

### ISSUE THREAD

**Issue by automaton82** [FlowiseAI/Flowise#1881]
**Describe the bug**
This code exists within `index.ts` to seemlingly place "Flowise Docs QnA" at the very beginning of the marketplace:
```
            const FlowiseDocsQnA = templates.find((tmp) => tmp.name === 'Flowise Docs QnA')
            const FlowiseDocsQnAIndex = templates.findIndex((tmp) => tmp.name === 'Flowise Docs QnA')
            if (FlowiseDocsQnA && FlowiseDocsQnAIndex > 0) {
                templates.splice(FlowiseDocsQnAIndex, 1)
                templates.unshift(FlowiseDocsQnA)
            }
            return res.json(templates.sort((a, b) => a.templateName.localeCompare(b.templateName)))
```

However immediately after putting it at the beginning of the array, the array is then sorting alphabetically which moves the item back into alphabetical order.

If this is not intend ended the order needs to be changed.

**To Reproduce**

1. Go to marketplace
2. Notice Flowise Docs QnA is not first

**Expected behavior**
Judging by the code my guess is this was meant to be first. If not, the extra special sorting can be removed.

**Additional context**
@HenryHengZJ let me know what the intent is, was that one supposed to be first or in alphabetical order

**Comment by automaton82** [comment]
Also I don't think `tmp.name` is even valid? I think it would have to be `tmp.templateName` if the comparison were to work.

**Comment by HenryHengZJ** [comment]
oh yep, it should be `templateName`, and we should `unshift` after sort alphabetically

**Comment by automaton82** [comment]
Okay I can issue a PR to fix. Thanks!

**Comment by automaton82** [comment]
Opened PR #1899 to fix.
