### ISSUE TITLE
[FEATURE] Could we please have Claude 3 Support

### ISSUE THREAD

**Issue by EngineeringErgonomics** [FlowiseAI/Flowise#1893]
**Describe the feature you'd like**

I would like to request that Flowise add support for Anthropic's latest language model, Claude 3. Claude 3 was released in August 2023 and offers significant improvements over previous versions, including more reliable and insightful responses, expanded knowledge, and enhanced safety features. Some key capabilities of Claude 3 that would be valuable in Flowise include:

- Improved reasoning abilities for answering complex questions and analyzing information
- Expanded knowledge cutoff of August 2023 for more up-to-date information 
- More nuanced and careful handling of sensitive/controversial topics
- Enhanced ability to engage in open-ended conversations and provide thoughtful opinions
- Stronger safety constraints to avoid harmful or biased outputs

Adding support for Claude 3 would allow Flowise users to leverage the latest advancements in language AI to build more capable and robust conversational flows and knowledge bases. It would help keep Flowise on the cutting edge as an AI-powered automation platform.

**Additional context**

Some additional details and considerations for this feature request:

- Claude 3 has a similar API to previous Claude models, so integration may be relatively straightforward from a technical perspective. However, there may be some new API parameters or usage guidelines to implement.

- Anthropic's usage policies and pricing for Claude 3 may need to be reviewed to ensure compliance and assess feasibility/cost of supporting it in Flowise.

- User documentation and templates may need to be updated to cover Claude 3 specific features, best practices, and examples.

- It would be ideal to allow users to easily switch between different Claude model versions (Claude 1, 2, 3) on a per-flow basis, to allow flexibility for different use cases and cost/performance tradeoffs.

Please let me know if you need any other information to consider this feature request. I believe Claude 3 support would be a valuable addition to keep Flowise at the forefront of practical AI technology. Thank you for your consideration!

**Comment by HenryHengZJ** [comment]
in work! it takes a little bit longer as we are also bringing the multi modal capability as well

**Comment by HenryHengZJ** [comment]
Released to `v1.6.2`
