### ISSUE TITLE
[BUG] Unable to Change Font Size in Embedded Chatbots

### ISSUE THREAD

**Issue by mikehudson2** [FlowiseAI/Flowise#1897]
When embedding a Chatflow in a website as a Popup Html, with "Show Embed Chat Config", if I reduce the fontSize from the default 16 to, for example, 11, only the human part of the dialogue appears smaller. The AI responses remain too large. See screenshot. 
![Screenshot](https://github.com/FlowiseAI/Flowise/assets/38255405/2383ea84-6aa6-478e-860d-ca77b894700f)

**Comment by HenryHengZJ** [comment]
@0xi4o perhaps something we can look at?

**Comment by toi500** [comment]
Also, boderRadius would be great too.

**Comment by HenryHengZJ** [comment]
should be fixed https://github.com/FlowiseAI/FlowiseChatEmbed/pull/115
