### ISSUE TITLE
[QUESTION] Combine OpenAI Function with OpenAI Assistant

### ISSUE THREAD

**Issue by khenzo** [FlowiseAI/Flowise#1900]
**Combine OpenAI Function and OpenAI Assistant**
Hi all, 
I'm trying to use the response from the following flow (I've used the one in the documentation) to pass the OpenAI Function results to a OpenAI Assistant. The goal of the Assistant would be to create a chart from the tools results (for example the first 5 top movers). The assistant has the code interpreter enabled.

Is it possible? Any idea how to achive this?
Thx!

**Current flow**
![image](https://github.com/FlowiseAI/Flowise/assets/2485256/68830c51-7987-4073-a966-921e1d61829b)

**Comment by toi500** [comment]
Acording to the OpenAI documentation are the gpt-3.5-turbo-0125 and gpt-4-turbo-preview model who have been trained to both detect when a function should to be called.

Your chat show you are using GPT4.

Source: https://platform.openai.com/docs/guides/function-calling

![Screenshot_2024-03-08-02-19-11-21_4641ebc0df1485bf6b47ebd018b5ee76](https://github.com/FlowiseAI/Flowise/assets/138339291/b6b2f273-0be0-453e-8f73-27818ef6af6c)

**Comment by khenzo** [comment]
Thx for the answer,

function calling is working fine (by the way I've tested it with different models). 
I'm able to get stock data from the API and show the answer into the chat.
What I want to achieve is to pass those data to an OpenAI Assistant Agent (that I've already tested alone and it's working well) and create a chart (visual reports) if it is in the user intent.

**Comment by HenryHengZJ** [comment]
Create the OpenAI Function Agent as another chatflow. Then create a Custom Tool that calls with prediction API. Connect the tool to OpenAI Assistant. Similar [guide](https://docs.flowiseai.com/use-cases/webhook-tool)

**Comment by HenryHengZJ** [comment]
Closing for now.

**Comment by khenzo** [comment]
I'll try this!

Thank you.
