### ISSUE TITLE
[ QUESTION ] chatGPT "Customize ChatGPT / Custom Instructions"

### ISSUE THREAD

**Issue by rrubio** [FlowiseAI/Flowise#1902]
Hi Guys,

Please excuse the ignorance, under chatGPT there's an option to "Customize ChatGPT" (see screenshot below).  Is there an equivalent in flowise? or would this just be part of my prompt "RAG"?

<img width="626" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/4221574/2819df62-8c95-4da7-96e2-77af364683d1">

**Comment by HenryHengZJ** [comment]
That would be part of your System Message Prompt

**Comment by rrubio** [comment]
Hey! @HenryHengZJ  thanks mate, that did the job.
