### ISSUE TITLE
[BUG] FAISS vectore store requests docstore.json

### ISSUE THREAD

**Issue by nicolasduerr** [FlowiseAI/Flowise#1916]
**Describe the bug**
When using the FAISS node with an existing faiss.index file, I run into the issue that it requests a "docstore.json". When creating the FAISS index file with langchain, there's no docstore.json saved to disk. The documentation says that the docstore is part of the index-file itself.

The error in the chat window states:

```
Error: ENOENT: no such file or directory, open '/Users/.../.../faiss/docstore.json'

``` 

**To Reproduce**

1. Add a FAISS vector store node
2. Provide the path where the faiss.index file is stored
3. Attach e.g. Azure OpenAI Embeddings node
4. Run the chat and ask a question

**Expected behavior**
- I want to use the plain FAISS index file

**Setup**
-   Installation: yarn start
-   Flowise Version: 1.25
-   OS: macOS
-   Browser: Chrome

**Additional context**
Please add documentation how to use this node and the specific file names and file-types that are needed.

**Comment by wayneWudh** [comment]
i also facing this issue. does anyone has method to solve it?

**Comment by pfcstyle** [comment]
https://github.com/langchain-ai/langchainjs/issues/1475.   it's a bug of faiss-node

**Comment by pfcstyle** [comment]
Same issue.

**Comment by theVedanta** [comment]
Facing the same thing; also, would love to see some documentation with regards to FAISS.

**Comment by pfcstyle** [comment]
Found the solution:

https://docs.flowiseai.com/use-cases/upserting-data#id-6.-full-overview

We need to Upsert to init faiss vector store.
