### ISSUE TITLE
[BUG] Issues with Saving Chat Flows, Adding Tools, and Using Chats 

### ISSUE THREAD

**Issue by qbbqqb** [FlowiseAI/Flowise#1917]
**Describe the bug**
I cannot save chat flows, add tools, or utilise chats.

**To Reproduce**
Before encountering this error, I uploaded files to the Pinecone vector store. The maximum total uploaded file size was not more than 200MB. This is a new deployment, so the disk is currently empty.

**Screenshots**
<img width="1674" alt="Screenshot 2024-03-10 at 21 03 51" src="https://github.com/FlowiseAI/Flowise/assets/80670638/ddce331c-0c8e-47fa-b049-d044ca141449">

<img width="1175" alt="Screenshot 2024-03-10 at 21 04 54" src="https://github.com/FlowiseAI/Flowise/assets/80670638/a26cb03c-1e0a-4d8e-824c-0dcd1345fdb6">

**Setup**
-   Installation [deployed on the railway.app; 8 GB of RAM, 8 vCPU, and 100 GB of Shared Disk]
-   Flowise Version [e.g. 1.6.0]

**Additional context**
I attempted to change the file size limit to 2000MB by adjusting the variable FLOWISE_FILE_SIZE_LIMIT=2000MB, but this did not work.

**Comment by rrubio** [comment]
@qbbqqb  Did you make the change under the UI Variables?

<img width="1672" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/4221574/41c4a5a3-3e69-47fd-b735-b1fa3a96dfd5">

**Comment by rrubio** [comment]
For anyone coming across this issue, you need to update the ".env" file under the "/your_path/Flowise/docker/.env".  Stop the container and then rebuild.

```
sudo docker-compose up --build -d
```
