### ISSUE TITLE
Error: Request failed with status code 401

### ISSUE THREAD

**Issue by Nerdydroids** [FlowiseAI/Flowise#192]
Hello, someone else experiencing this error? 
Do you have any solution for it?

**Comment by IterNobody** [comment]
Maybe api key incorrect ?

**Comment by DmacMcgreg** [comment]
same error. API key copied directly from OpenAI
<img width="1433" alt="CleanShot 2023-05-27 at 14 51 18@2x" src="https://github.com/FlowiseAI/Flowise/assets/3266023/65a7bed8-ddea-4bc2-9a3c-a1fe672f70eb">

**Comment by eialanjones** [comment]
+1 Same here

**Comment by vanetreg** [comment]
Same issue

**Comment by Karimium0** [comment]
Same issue here, anyone managed to fix this ?

**Comment by uzair-7886** [comment]
same issue +1

**Comment by uzair-7886** [comment]
tried three different api keys from three different accounts but still not working

**Comment by TheTinkerJ** [comment]
not same issue, my error code is 404, and i change the llm to `gpt-3.5-turbo-0613` then it works

**Comment by abslearn** [comment]
same issue

**Comment by DmacMcgreg** [comment]
@chungyau97  this is not the case, since I've tried with multiple fresh keys, please re-open.

**Comment by chungyau97** [comment]
Could you share your Flowise configuration? 
1. Node version
2. Method of setting up
3. Device OS

**Comment by kaisiant** [comment]
My side is working fine. I tried deleting one character from the key, and it shows 401, which is correct.
macOS 13.2.1 (22D68)

1. npm install -g flowise
2. npx flowise start

<img width="1411" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26655111/38395ff7-f37d-4909-9d21-9a52376d00bd">

**Comment by chungyau97** [comment]
@DmacMcgreg,

Seem like your problem is related to the older version of NodeJS.

Please proceed to download the `LTS` version of it. [18.17.0 LTS](https://nodejs.org/en)
If you're adventurous enough, give [NVM](https://github.com/nvm-sh/nvm) a try. This is to manage different version of NodeJS

**Comment by NISHANTSHRIVASTAV** [comment]
Hi @chungyau97 ,

Getting **401 status code** as shown below in server error logs:

`2023-08-08 05:30:23 [ERROR]: [server]: Error: Request failed with status code 401 and body {"statusCode":401,"message":"Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired."}`

Azure OpenAI keys are valid and not expired.

Request you to please check the detailed issue [here](https://github.com/FlowiseAI/Flowise/issues/710).

Please let us know how to resolve the same.

**Comment by chungyau97** [comment]
Hi @NISHANTSHRIVASTAV,

I will close this issue as I replied in #710.

**Comment by NikolayBG** [comment]
How I was able to fix:

1. Went to https://platform.openai.com/account/billing/overview and put some money in order to have credits to call OpenAI API
2. Created new API key for OpenAI
3. In Flowise make sure you have the same API keys in Chat Open AI and OpenAI Embedding 

This was my way.
