### ISSUE TITLE
Download Fails at /api/v1/openai-assistants-file [BUG]

### ISSUE THREAD

**Issue by AdamSiwy** [FlowiseAI/Flowise#1923]
**Describe the bug**
When giving a assistants-file for Download in the Chat Conversation the download fails with 404

**To Reproduce**

1. Upload a assistants-file to the UI for a openAI Assistant
2. Sync file to OpenAI
3. Open a Chatbot window.
4. Ask for the assistance file
5. Klick on the Download Button 
6. response: {…} }
​
code: "ERR_BAD_REQUEST"
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
message: "Request failed with status code 404"
​
name: "AxiosError"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: Blob, status: 404, statusText: "Not Found", … }

**Expected behavior**
Download of the File.

**Screenshots**
![grafik](https://github.com/FlowiseAI/Flowise/assets/30761117/8775aa40-80e9-400b-b621-53bd7b3d5dad)

**Flow**
-
**Setup**
-   Installation yarn start
-   Flowise Version 1.6.0
-   OS: Ubunut
-   Browser Firefox

**Additional context**
Hosted with Plesk on a vhosts environment

**Comment by HenryHengZJ** [comment]
Sometimes OpenAI might not generate the correct download link, is this occuring everytime or ocassionally?

**Comment by HenryHengZJ** [comment]
should be fixed via v2 API [PR](https://github.com/FlowiseAI/Flowise/pull/2258)
