### ISSUE TITLE
yarn start command start not found

### ISSUE THREAD

**Issue by iampick** [FlowiseAI/Flowise#1928]
fresh clone from repo passed
yarn install passed
yarn build passed

**Describe the bug**

(base) [main][~/SSD1T/vscode/AI/Flowise]$ yarn start
yarn run v1.22.19
$ run-script-os
$ cd packages/server/bin && ./run start
 ›   Error: command start not found
error Command failed with exit code 2.

*** my package.json (only script) ***
 "scripts": {
        "build": "turbo run build",
        "build-force": "pnpm clean && turbo run build --force",
        "dev": "turbo run dev --parallel",
        "start": "run-script-os",
        "start:windows": "cd packages/server/bin && run start",
        "start:default": "cd packages/server/bin && ./run start",
        "clean": "pnpm --filter \"./packages/**\" clean",
        "nuke": "pnpm --filter \"./packages/**\" nuke && rimraf node_modules .turbo",
        "format": "prettier --write \"**/*.{ts,tsx,md}\"",
        "lint": "eslint \"**/*.{js,jsx,ts,tsx,json,md}\"",
        "lint-fix": "pnpm lint --fix",
        "quick": "pretty-quick --staged",
        "postinstall": "husky install",
        "migration:create": "pnpm typeorm migration:create"
    },

**Comment by HenryHengZJ** [comment]
We've changed the package manager to pnpm. Feel free to follow the new README guide

**Comment by arberrexhepi** [comment]
> flowise@1.6.2 start:default
> cd packages/server/bin && ./run start
 ›   Error: command start not found
