### ISSUE TITLE
[BUG] Missing SSL Toggle in New PostgreSQL Module

### ISSUE THREAD

**Issue by simplecloudbox** [FlowiseAI/Flowise#1930]
Describe the bug:

The new PostgreSQL module in FlowiseAI lacks the option to enable SSL for database connections. This makes it impossible to establish secure connections to PostgreSQL databases that require SSL encryption. The old Postgres-module had that feature to enable SSL-connections but in the new Postgres-module it is missing (see screenshot).

1. Navigate to the PostgreSQL module in Flowise.
2. Set up a new database connection.
3. There is no option or toggle available to enable SSL for the connection.

Expected behavior:

There should be an option or a toggle available to enable SSL for PostgreSQL database connections. This would allow for secure connections to databases that require SSL encryption, ensuring the security of data transmission.

Screenshots:

<img width="1537" alt="postgres missing ssl-toogle" src="https://github.com/FlowiseAI/Flowise/assets/4971898/d042f00c-ed32-43d8-ba07-5dc90e100df9">

Setup:

Installation: Docker
Flowise Version: 1.6.0

**Comment by adhiiisetiawan** [comment]
hi @simplecloudbox i wanna ask another question but not related with your problem, but still use postgreSQL. is this postgreSQL already can use without problem before? I trying to use postgreSQL but got an error when try sending chat. here's the error, are you encountered same problem before?
```bash
flowise-1   | 2024-03-14 02:53:51 [INFO]: Starting Flowise...
flowise-1   | 2024-03-14 02:53:51 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
flowise-1   | 2024-03-14 02:53:51 [INFO]: 📦 [server]: Data Source has been initialized!
flowise-1   | 2024-03-14 02:54:19 [INFO]: ⬆️ POST /api/v1/credentials
flowise-1   | 2024-03-14 02:54:32 [INFO]: ⬆️ POST /api/v1/chatflows
flowise-1   | 2024-03-14 02:54:36 [INFO]: 🖊 PUT /api/v1/chatflows/ab02a909-a5d0-4cf5-99ad-8ccf16bc9160
flowise-1   | 2024-03-14 02:54:39 [INFO]: ⬆️ POST /api/v1/internal-prediction/ab02a909-a5d0-4cf5-99ad-8ccf16bc9160
flowise-1   | 2024-03-14 02:54:39 [ERROR]: connect ECONNREFUSED 127.0.0.1:5432
flowise-1   | Error: connect ECONNREFUSED 127.0.0.1:5432
flowise-1   |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
flowise-1   | 2024-03-14 02:54:39 [ERROR]: [server]: Error: Error: connect ECONNREFUSED 127.0.0.1:5432
flowise-1   | Error: Error: connect ECONNREFUSED 127.0.0.1:5432
flowise-1   |     at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:331:19)
flowise-1   |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
flowise-1   |     at async App.buildChatflow (/usr/local/lib/node_modules/flowise/dist/index.js:1512:40)
flowise-1   |     at async /usr/local/lib/node_modules/flowise/dist/index.js:1066:13
```

**Comment by adhiiisetiawan** [comment]
hi @simplecloudbox i mean run on chatflow, so it's like chat with our personal data from database. in general, most of tutorials explain using pdf as a data source, but what if i wanna use my DB as a data source, is it possible? SQLite/PostgreSQL/MySQL

**Comment by HenryHengZJ** [comment]
@simplecloudbox you can enter SSL in the additonal config:
<img width="507" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/9b685fca-b78b-4ca4-80fb-182b2a7f5f55">

We disabled the turn on/off because there were many ways to have SSL connection, and thus we decided to let user specify their own way
