### ISSUE TITLE
[BUG] Out of Memory

### ISSUE THREAD

**Issue by mikehudson2** [FlowiseAI/Flowise#1932]
![Screenshot 2024-03-12 134846](https://github.com/FlowiseAI/Flowise/assets/38255405/380776f5-ea9c-44b9-95cd-320a806fefc7)
Render says "Server unhealthy. Ran out of memory (used over 2GB) while running your code."

Deployed at Render, "Standard" package.

In short, with either of the following I get this crash:
1. Crawling and upserting within Flowise (see attached screenshot)
2. Upserting an Apify JSON dataset (markdown only) as local file within Flowise.

Both methods work for a site of 1k pages but fail for a site of 10k.

**Comment by HenryHengZJ** [comment]
the amount of scraped pages might be too much, have you tried scraping for smaller sub pages?
