### ISSUE TITLE
Extending the Prediction API response

### ISSUE THREAD

**Issue by konstohrimenko** [FlowiseAI/Flowise#1933]
Is it possible to add additional data from a Custom Tool to the Prediction API response? Something like this:
Custom Tool function
```javascript
$response.userName = $username;
```
Prediction API response
```json
{
    "text": "...",
    "chatMessageId": "...",
    "chatId": "...",
    "sessionId": "...",
    "userName": "Name"
}
```

**Comment by KonstantinOhrimenko** [comment]
No, not that. I have created a tool to determine the user name. The next step is to return that value to the third-party application in the same request:
1. API request `POST` `/api/v1/prediction/{{flow-id}}`:
```json
{
  "question": "My name is John Doe",
  "overrideConfig": {
    "sessionId": "session-1"
  }
}
```
2. The AI agent determines the user name as John Doe, and then Flowise calls my custom tool "username_tool". This tool should add the user name to the response (how to?)
3. Expected API response
```json
{
  "text": "Nice to meet you John Doe!",
  "sessionId": "session-1",
  "usedTools": {
    "username_tool": {
      "name": "John Doe"
    }
  }
}
```

My custom tool
<img src="https://github.com/FlowiseAI/Flowise/assets/75303199/ee7ef166-8a4c-4bf6-9f7e-388f41588226" width="500">

@HenryHengZJ

**Comment by konstohrimenko** [comment]
No, not that. I have created a tool to determine the user name. The next step is to return that value to the third-party application in the same request:
1. API request `POST` `/api/v1/prediction/{{flow-id}}`:
```json
{
  "question": "My name is John Doe",
  "overrideConfig": {
    "sessionId": "session-1"
  }
}
```
2. The AI agent determines the user name as John Doe, and then Flowise calls my custom tool "username_tool". This tool should add the user name to the response (how to?)
3. Expected API response
```json
{
  "text": "Nice to meet you John Doe!",
  "sessionId": "session-1",
  "usedTools": {
    "username_tool": {
      "name": "John Doe"
    }
  }
}
```

My custom tool
<img src="https://github.com/FlowiseAI/Flowise/assets/75303199/ee7ef166-8a4c-4bf6-9f7e-388f41588226" width="500">

@HenryHengZJ

**Comment by HenryHengZJ** [comment]
The `usedTools` are already there in API response:
<img width="786" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/81ce9819-82ce-4aa1-8dbc-aadb6c536802">

**Comment by konstohrimenko** [comment]
I understood why there is no 'usedTools' property in the response – only the OpenAI Assistant can provide information about used tools. In my case, the OpenAI Function Agent was used.

Thanks

**Comment by HenryHengZJ** [comment]
@konstohrimenko you should be able to get `usedTools` in OpenAI Tools Agent now
