### ISSUE TITLE
[BUG] Frustrating on MACOS, backspace while deleting text on a flow will delete the flow

### ISSUE THREAD

**Issue by antibitcoin** [FlowiseAI/Flowise#1939]
**Describe the bug**
When I expand a box lets say a prompt or code or whatever and I am pressing backspace to delete a text, it will exit the box and delete the flow, with no way to go back and restore it I lose the whole progress and have to insert a new flow and type everything again, I started using visual code to type stuff before pasting it, I wonder why not remove the shortcut to delete flows and make the deletion only using the on screen gui or at least put a warning "Do you want to delete this module" or whatever, its frustrating so many times I just exit and come back to work the next day because of this and how pissed I get for losing progress.
**To Reproduce**
Type something on an expanding code, promt or any box with the maximize button and than while editing press backspace multiple types trying to delete text, I think when u reach the begining of the line instead of going up it will exit the box and delete the partent without a warning.

**Expected behavior**
Delete just the text not the whole thing!

**Comment by HenryHengZJ** [comment]
we have a PR that removes the shortcut - https://github.com/FlowiseAI/Flowise/pull/1505 , I was hesitant before but I think we're seeing more frustration of accidentally removing the flow than the ease that shortcut brings. Will remove that in next release
