### ISSUE TITLE
[FEATURE] Toggle Between Chunks & Links in "Return Source Documents" in CR QA Chain

### ISSUE THREAD

**Issue by mikehudson2** [FlowiseAI/Flowise#1949]
In Conversational Retrieval QA Chain we can toggle on/off "Return Source Documents". When this is 'on' it would be useful to be able to choose between displaying URL links or chunks

**Comment by HenryHengZJ** [comment]
If you are using Cheerio or any other web scraping document loader, it doesn't make sense to return chunk, so it's returning URL, same for other file loaders, in an opposite way.
