### ISSUE TITLE
Error 400 when using "azure openai embeddings" instead of "openai embeddings"[BUG]

### ISSUE THREAD

**Issue by dmanresa-saes** [FlowiseAI/Flowise#195]
Hello,

I am experiencing an issue when using "azure openai embeddings" in my project. When I use "openai embeddings", everything works fine, but when switching to "azure openai embeddings", I receive the following error:

**error: request failed with status code 400**

**To Reproduce**

1. Use "openai embeddings" in the project (works correctly).
2. Switch to "azure openai embeddings".
3. Run the project.
4. Observe the mentioned error.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/60778681/50dbba90-ba85-4d8e-b68c-16ecef3fc9f9)
**Setup**

-   OS: Windows 10
-   Browser: all

**Additional context**
node v18.15.0

**Comment by dmanresa-saes** [comment]
I can also see in the console:

  response: {
    status: 400,
**    statusText: 'model_error',**
    headers: {
      'content-length': '346',
      'content-type': 'application/json',
      'access-control-allow-origin': '*',
      'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
      'openai-processing-ms': '44.0331',
      'x-content-type-options': 'nosniff',
      'x-request-id': 'aa255825-12b9-4418-8360-42019c443819',
      'ms-azureml-model-error-reason': 'model_error',
      'ms-azureml-model-error-statuscode': '400',
      'x-ms-client-request-id': 'fd12f8f1-a6fe-4a2b-ab8b-a13eac030be6',
      'apim-request-id': 'fd12f8f1-a6fe-4a2b-ab8b-a13eac030be6',
      'x-ms-region': 'West Europe',
      date: 'Fri, 26 May 2023 17:56:08 GMT',
      connection: 'close'

**Comment by chungyau97** [comment]
@dmanresa-saes 
I have done the changes requested. #215 
Could you help try out this branch `bugfix/AzureOpenAIEmbeddingError` to check whether the same error occur again?

**Comment by dmanresa-saes** [comment]
Works perfectly!
