### ISSUE TITLE
I can not create API key for my flowise deployed on onrender.com

### ISSUE THREAD

**Issue by iampick** [FlowiseAI/Flowise#1954]
**Describe the bug**

<img width="1255" alt="Screenshot at Mar 15 09-57-05" src="https://github.com/FlowiseAI/Flowise/assets/7637063/3c4b79fe-42f9-4134-9616-34d87b9a1e93">

How can I fix it

thank you.

**Comment by HenryHengZJ** [comment]
Should be fixed now!
