### ISSUE TITLE
[FEATURE] MS SQL Support

### ISSUE THREAD

**Issue by Namec999** [FlowiseAI/Flowise#196]
Hello All,

Is there any plan to add support for more DB's like mssql server, or any workaround to make it possible.

My goal is to provide some data analysis through my training the agent on my structured data.

Best

**Comment by HenryHengZJ** [comment]
yes! we have that on one of the features to develop

**Comment by Namec999** [comment]
let the force be with you then :-)

**Comment by Namec999** [comment]
sending you force to make you, achieve this one ;-)

let the force be with you

**Comment by lpongetti** [comment]
#761
