### ISSUE TITLE
[BUG] Ollama answer in the chat cannot be parsed

### ISSUE THREAD

**Issue by SikamikanikoBG** [FlowiseAI/Flowise#1968]
**Describe the bug**
I am using Ollama latest and tinyllama.
with a very simple chatflow in Flowise:
![image](https://github.com/FlowiseAI/Flowise/assets/46193504/0009b1d7-392f-4b76-9069-76ad8f0218a2)

and this is the result in the test chat:
![image](https://github.com/FlowiseAI/Flowise/assets/46193504/81e71c7c-2563-4aea-bbec-6b5be13b57c1)

![image](https://github.com/FlowiseAI/Flowise/assets/46193504/2b01e096-1584-40fc-ac53-a0cd9c9ac3cb)

But when I enter in cmd with Ollama and ask the same question everything is super fine:
![image](https://github.com/FlowiseAI/Flowise/assets/46193504/b8562790-c017-46fc-a85f-753ce1b5bc43)

**To Reproduce**

Setup the flow and try to chat

**Expected behavior**
To have as minimum the same recipe for scrambled eggs :) Same answer as cmd one.

**Screenshots**
Applied above

**Flow**
Applied above

**Setup**

-   Docker setup
-   Flowise Version 1.6.0
-   OS: Linux Leap 15.4
-   Browser Chrome
- Ollama version 0.1.29

**Additional context**

**Comment by automaton82** [comment]
Click additional parameters and remove the system message and prompt etc. only put the user input and response nothing else.

Does it fix it?

**Comment by HenryHengZJ** [comment]
running from command line vs using conversational agent is different. Conversational agent has built-in prompt that ask the LLM to give data in JSON format, and its tailored to ChatGPT. For other models, try using LLMChain

**Comment by SikamikanikoBG** [comment]
Thank you, now it is ok!
