### ISSUE TITLE
Render build fails

### ISSUE THREAD

**Issue by dhruvmynd** [FlowiseAI/Flowise#1972]
**Describe the bug**
Render build fails. 

**To Reproduce**
Render build fails with yarn commands 

below are the logs 

==> Checking out commit 58122e985c26620206d8a1c7848acfe2dacc6b14 in branch main
==> Downloading cache...
==> Transferred 617MB in 9s. Extraction took 15s.
==> Requesting node version >=18.15.0 <19.0.0 || ^20
==> Using Node version 20.11.1 via /opt/render/project/src/package.json
==> Docs on specifying a Node version: https://render.com/docs/node-version
==> Running build command 'yarn install; yarn build'...
error This project's package.json defines "packageManager": "yarn@pnpm@8.14.0". However the current global version of Yarn is 1.22.22.
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
error This project's package.json defines "packageManager": "yarn@pnpm@8.14.0". However the current global version of Yarn is 1.22.22.
Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.
==> Build failed 😞
==> Common ways to troubleshoot your deploy: https://docs.render.com/troubleshooting-deploys

**Comment by HenryHengZJ** [comment]
You'll have to change the yarn command to pnpm command. For example, yarn install to pnpm install, yarn build to pnpm build
