### ISSUE TITLE
[FEATURE] Confluence Loader Integration ( Server/Data Center) 

### ISSUE THREAD

**Issue by mrkhachaturov** [FlowiseAI/Flowise#1973]
**Describe the feature you'd like**
Confluence Loader Integration upgrade for Server/Data Center support
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/confluence

**Additional context**

**Comment by mrkhachaturov** [comment]
@HenryHengZJ Can I contribute with this issue? I managed to improve the integration! The only question I have is, during the credential input stage, it is implied that you can either specify a username access token for Confluence Cloud or a personal access token for Confluence Server/Datacenter. 

I couldn't figure out how to implement a dropdown list for selecting cloud or datacenter when entering credentials.

I can suggest renaming the current integration with Confluence API to Confluence Cloud API and adding a second Confluence Server/Data Center API.

Locally, I simply made the fields optional, but I don't think this is entirely correct.

![CleanShot 2024-03-20 at 00 44 31@2x](https://github.com/FlowiseAI/Flowise/assets/105451445/bd959d1b-4103-43c6-9f27-6b92f86f3965)

**Comment by mrkhachaturov** [comment]
![CleanShot 2024-03-20 at 00 47 51@2x](https://github.com/FlowiseAI/Flowise/assets/105451445/0f16685d-66f2-4e10-b0e2-e2cf609b7e41)

**Comment by mrkhachaturov** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/105451445/2a87e538-068a-47b4-9d55-597199a46d83)

![image](https://github.com/FlowiseAI/Flowise/assets/105451445/79e17e83-0aff-49f9-8446-71161b1e2d50)

**Comment by HenryHengZJ** [comment]
[PR](https://github.com/FlowiseAI/Flowise/pull/1998) merged!
