### ISSUE TITLE
[PineconeAuthorizationError] - help needed

### ISSUE THREAD

**Issue by hrgarber** [FlowiseAI/Flowise#1977]
I am unable for some reason to upsert into pinecone. I have tried redoing my API keys about 5 times. I have tried serverless and default, recreating new indexes, etc.

![Screenshot 2024-03-17 162312](https://github.com/FlowiseAI/Flowise/assets/75917163/0241ecd3-8af2-4019-b7fb-e4a48e8a77ba)

you can see In this picture that i tried 2 different indexes. 

What am i doing wrong? I am on version 1.6.1

**Comment by HenryHengZJ** [comment]
Pinning Pinecone dependency should solve the issue - https://github.com/FlowiseAI/Flowise/pull/2036

**Comment by HenryHengZJ** [comment]
Should be resolved in `v1.6.3`
