### ISSUE TITLE
[BUG] error occurs when upserting files using Folder with Files with many files

### ISSUE THREAD

**Issue by meokey** [FlowiseAI/Flowise#1978]
**Describe the bug**
I'm running the container on Synology DSM 7.2.
The error occurs when I upload many files using "Folder with Files". Small amount of files works fine.
As I add more files into the folder and Upsert, at some point, the process was interrupted and the below error message shows in red:

`<!DOCTYPE html> <html> <head> <meta charset="utf-8"> <style>body{font-family:Arial,Helvetica,sans-serif;font-size:12px;text-align:center}h1{color:#06C;font-size:25px;line-height:60px;margin-top:56px}img{margin-top:40px} </style> </head> <body> <img src="data:image/jpg;base64,/9j/......//Z "/> <h1 id="a"></h1> <hr> <p>&copy; 2023 <a href="http://www.synology.com">Synology Inc.</a></p> </body> <script type ="text/javascript"> /* Copyright (c) 2023 Synology Inc. All rights reserved. */ (function(){var a={en:"Sorry, the page you are looking for is not found.",zh:"\u62b1\u6b49\uff0c\u60a8\u6240\u6307\u5b9a\u7684\u9875\u9762\u4e0d\u5b58\u5728\u3002",it:"La pagina richiesta non \u00e8 stata trovata.","zh-HK":"\u62b1\u6b49\uff0c\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",cs:"Hledan\u00e1 str\u00e1nka nebyla nalezena.",es:"Lo sentimos, no se encuentra la p\u00e1gina que est\u00e1 buscando.",ru:"\u0418\u0437\u0432\u0438\u043d\u0438\u0442\u0435, \u0438\u0441\u043a\u043e\u043c\u0430\u044f \u0432\u0430\u043c\u0438 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u0430.",nl:"Sorry, de pagina die u zoekt kan niet weergegeven worden.",pt:"Desculpe, a p\u00e1gina que procura n\u00e3o foi encontrada.",no:"Beklager, siden du leter etter finnes ikke.",nb:"Beklager, siden du leter etter finnes ikke.",tr:"\u00dczg\u00fcn\u00fcz, arad\u0131\u011f\u0131n\u0131z sayfa bulunamad\u0131.",pl:"Przepraszamy, nie znaleziono strony, kt\u00f3rej szukasz.",fr:"D\u00e9sol\u00e9, la page que vous recherchez est introuvable.",de:"Es tut uns Leid, die von Ihnen gesuchte Seite konnte nicht gefunden werden.",da:"Desv\u00e6rre, den side, du leder efter, kunne ikke findes.","pt-BR":"Desculpe, a p\u00e1gina que procura n\u00e3o foi encontrada.","zh-MO":"\u62b1\u6b49\uff0c\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",hu:"Eln\u00e9z\u00e9st, a keresett oldal nem tal\u00e1lhat\u00f3.",ja:"\u7533\u3057\u8a33\u3042\u308a\u307e\u305b\u3093\u304c\u3001\u635c\u3057\u3066\u3044\u308b\u30da\u30fc\u30b8\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093",nn:"Beklager, siden du leter etter finnes ikke.","zh-TW":"\u62b1\u6b49\uff0c\u60a8\u6240\u6307\u5b9a\u7684\u9801\u9762\u4e0d\u5b58\u5728\u3002",ko:"\uc8c4\uc1a1\ud569\ub2c8\ub2e4. \ucc3e\uace0\uc790 \ud558\ub294 \ud398\uc774\uc9c0\ub97c \ubc1c\uacac\ud558\uc9c0 \ubabb\ud588\uc2b5\ub2c8\ub2e4.",sv:"Sidan du s\u00f6ker hittades inte."};var b=window.navigator.browserLanguage||window.navigator.language;if(-1==["zh-TW","zh-MO","zh-HK","pt-BR"].indexOf(b)){b=b.split("-",1)}document.getElementById("a").innerHTML=a[b]||a.en})(); </script> </html>`

**To Reproduce**

1. Use Folder with Files
2. Click on 'Upsert'
3. See error

**Expected behavior**
No error is expected when upserting the files

**Screenshots**
N/A
**Flow**
N/A

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
running the container with docker on Synology DSM 7.2 using below command:
`$ docker-compose up -d`
-   Flowise Version [e.g. 1.2.11]
1.6.1
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]
Chrome

**Additional context**
- I checked the logs on /root/.flowise/logs but nothing.
- I have revised the below env var to avoid file size limit, but it does not help.
`FLOWISE_FILE_SIZE_LIMIT=200mb`
- suspect timeout error due to long process?

**Comment by meokey** [comment]
sorry please ignore the issue and feel free to close it.

I figured out the issue - it's not about the project, it's about the proxy timeout settings of the Syonology Reverse Proxy I used to point to FlowiseAI. I increased the timeout value on Synology and it works fine.

**Comment by HenryHengZJ** [comment]
thanks for figuring out the issue! @meokey
