### ISSUE TITLE
[FEATURE] how can we deploy flowise on GCP

### ISSUE THREAD

**Issue by sergedahdouh** [FlowiseAI/Flowise#198]
hello 
please provide a tutorial on how we can apply  flowise on GCP 
thank you in advance

**Comment by HenryHengZJ** [comment]
will work on the docs 👍

**Comment by ggalanter** [comment]
How about AWS? Trying to deploy on Ubuntu.  No luck. Any help?

**Comment by HenryHengZJ** [comment]
AWS docs is live - https://docs.flowiseai.com/deployment/aws
Still working on GCP

**Comment by kbala** [comment]
I just deployed to GCP :)

**Comment by HenryHengZJ** [comment]
@kbala would you be willing to write the guides down? Or if you're familiar with markdown can you contribute 1 to [here](https://github.com/FlowiseAI/FlowiseDocs/tree/main/deployment)? We would be so grateful if you can do that!

**Comment by kbala** [comment]
@HenryHengZJ Ok, I try to take care for GCP doc.

**Comment by HenryHengZJ** [comment]
thank you @kbala for the GCP documentation!

Now live on - https://docs.flowiseai.com/deployment/gcp

**Comment by jeremygachet** [comment]
Hello,
Thank you very much for your document.
I'm a total noob with K8s, and I do not manage to add a persistent disk mount nor an HTTPS certificate on the deployment.
Could someone help me, please?
