### ISSUE TITLE
I want more explanation about "history" key in the PredictionAPI

### ISSUE THREAD

**Issue by amrpyt** [FlowiseAI/Flowise#1989]
I want to build chatbot with memory with every user, but when i request the API it dose not have a context!

**Comment by emrahtoy** [comment]
There might be an explanation needed in the documentation indeed.  

Short-term memory components are not meant to store and manage history as a logic state. Instead, they are meant to function state which does the necessary conversions and apply processes like sliding memory window depending on the LLM you prefer. As they don't have any kind of mechanism to keep the data state (known as stateless) you have to provide (state) data which is the "history" in this context.

@HenryHengZJ the explanation above would look good in the documentation.

**Comment by amrpyt** [comment]
@emrahtoy 
So if i build a flow in make.com or Zappier, then put a http request node and put my flowise flow Curl information in this node, it will be a chatbot without memory or context, any idea how to fix this problem?

**Comment by emrahtoy** [comment]
> @emrahtoy So if i build a flow in make.com or Zappier, then put an http request node and put my flowise flow Curl information in this node, it will be a chatbot without memory or context, any idea how to fix this problem?

That is why Flowise also provides embeddable chatbot.
![image](https://github.com/FlowiseAI/Flowise/assets/4387637/2d9bddbf-6d42-49ae-83cd-647bbb2d1f5a)

In case you still need an API way solution then a small script can help. Otherwise, we may need a new component for such purpose.

**Comment by HenryHengZJ** [comment]
@amrpyt while we are working on the fix, you;ll have to use other memory nodes as mentioned here - https://docs.flowiseai.com/integrations/langchain/memory/long-term-memory
