### ISSUE TITLE
[BUG] I Deployed the chatflow to Azure but the Chatbot still cant access it

### ISSUE THREAD

**Issue by SchmitzBen-UC** [FlowiseAI/Flowise#1995]
I Deployed the chatflow to Azure but the Chatbot still cant access it. I followed the Tutorial at the bottom of the Deployment Page... https://docs.flowiseai.com/configuration/deployment/azure and i cant get the embed to work. the chat is working in the test interface but it just doesnt stop loading on my website... Any idea why this is happening?

**Comment by euroblaze** [comment]
@SchmitzBen-UC 
You may want to provide logs, debug data. 
Thanks

**Comment by SchmitzBen-UC** [comment]
@euroblaze how exactly do i provide those, when the flow isnt running on my device anymore. 

The Chatflow is exactly the same as in this issue: https://github.com/FlowiseAI/Flowise/issues/1841

I think i found the problem:

Mixed Content: The page at 'url ' was loaded over HTTPS, but requested an insecure resource 'http://rest of the chatflow request'. This request has been blocked; the content must be served over HTTPS.

I will look into that.

**Comment by TheVoidRoger** [comment]
Any luck on this setup? I'm also having issue embedding it to any websites. Running perfectly fine inside Flowise. 
![fw-embed-error](https://github.com/FlowiseAI/Flowise/assets/142100135/68932d7b-f105-4a90-a62e-f75157baea15)

**Comment by SchmitzBen-UC** [comment]
Well i am accessing it from an https Ressource now, but there are still errors: 

`GET https://new_url/socket.io/?EIO=4&transport=polling&t=OvqeKcH net::ERR_FAILED 200 (OK)`
and
`Access to XMLHttpRequest at 'https://new_url/socket.io/?EIO=4&transport=polling&t=OvqeKcH' from origin 'https://site_url' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by TheVoidRoger** [comment]
This is hosted in DigitalOcean, we replicated it in Azure... unfortunately had the same issue.
But when I deployed it on Render, it managed to show the app flawlessly. It may has something to do the with routing or firewall config. Any thoughts on this?

We would appreciate if we can make this work with DO / Azure.

> Any luck on this setup? I'm also having issue embedding it to any websites. Running perfectly fine inside Flowise. ![fw-embed-error](https://private-user-images.githubusercontent.com/142100135/316120928-68932d7b-f105-4a90-a62e-f75157baea15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjIwMzYsIm5iZiI6MTcxMTM2MTczNiwicGF0aCI6Ii8xNDIxMDAxMzUvMzE2MTIwOTI4LTY4OTMyZDdiLWYxMDUtNGE5MC1hNjJlLWY3NTE1N2JhZWExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxMDE1MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDhlNWQ1NjRlMTRkMDQ3NTU3MjQwOTI5MjUzMDRjZmJkNDUwZjUwNjYwYjQwNjViM2M1ZmI0NWMxN2E3ZGNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.75fhTi1iGH98UlPdf-__O64d_p9z-xjd-ZUd8_F9FB0)

**Comment by lde-net2** [comment]
you might need to set the flowise env variable CORS_ORIGINS="*"

on azure container app, 
you need to enable the http traffic if not using https (allow insecure connections in "ingress") 
CORS_ORIGINS can be set in containers >  environment variables
