### ISSUE TITLE
Blobs for source documents not shown when using flowise-embed 1.2.0

### ISSUE THREAD

**Issue by frankwengerek** [FlowiseAI/Flowise#1996]
Blobs for the source documents are shown only for a spilt second when using the newest flowise-embed version 1.2.0. In versions 1.1.0 and earlier there was no problem.

![flowise-embed1 1 0](https://github.com/FlowiseAI/Flowise/assets/130894905/fbc6b254-6261-44f9-b60b-139843e85a0f)
![flowise-embed1 2 0](https://github.com/FlowiseAI/Flowise/assets/130894905/380e5df2-424b-4811-b04b-def77d485f26)

**Comment by HenryHengZJ** [comment]
PR merged and pushed to new embed release - https://github.com/FlowiseAI/FlowiseChatEmbed/pull/121
