### ISSUE TITLE
[BUG] Broken database migration on upgrade to 1.6.2

### ISSUE THREAD

**Issue by leandrosilvaferreira** [FlowiseAI/Flowise#2000]
**Describe the bug**
During the upgrade from version 1.6.1 to 1.6.2 of Flowise using Docker, the application fails to start due to a migration error related to an invalid input syntax for type UUID. The specific migration that fails is "FieldTypes1710497452584", with the error message indicating an invalid input syntax for type uuid: "48991505856". Additionally, a `TypeError` related to reading properties of undefined is encountered, further preventing the application from starting.

**To Reproduce**

1. Start with Flowise version 1.6.1 installed via Docker.
2. Attempt to upgrade to version 1.6.2 using Docker by running the appropriate upgrade command.
3. Observe the logs during the upgrade process.
4. The error messages related to the invalid UUID syntax and the TypeError are displayed, preventing the application from starting successfully.

**Expected behavior**
The upgrade process should complete without errors, and the application should start successfully with the new version (1.6.2). Data migrations should handle UUIDs correctly, and no type errors should occur during initialization.

**Setup**

-   Installation: docker
-   Flowise Version: Attempting to upgrade from 1.6.1 to 1.6.2

**Additional context**
The error occurs during the data source initialization phase, specifically during the execution of database migrations. It seems there is an issue with how UUIDs are handled or expected in the migration "FieldTypes1710497452584". Additionally, the `TypeError` suggests there might be an issue with accessing properties on an undefined object during the application's startup sequence.

**Comment by HenryHengZJ** [comment]
@emrahtoy

**Comment by emrahtoy** [comment]
@leandrosilvaferreira could you share the whole error log? Which Database server have you been using?

This situation might have occurred due to former migrations. Have you tried with a fresh 1.6.1 install or was it already an updated version since the older versions?

48991505856 indeed is not an UUIDso the type error is pretty normal. But this number may be the error code or something like that, which refers to something specific. A full log could be useful in this case.

@HenryHengZJ Other than this I will check optional/nullable fields.

**Comment by neliocaa** [comment]
This error its caused on migration, on alter table to uuid, the previos data is not uuid, so cause de error

packages/server/src/database/migrations/postgres/1710497452584-FieldTypes.ts

`Migration "FieldTypes1710497452584" failed, error: invalid input syntax for type uuid: "waai-380"
`

**Comment by neliocaa** [comment]
in my case, the table chat_message, when external type, on sessionId and chatId, use another pattern!

**Comment by emrahtoy** [comment]
> In my case, the table chat_message, when external type, on sessionId and chatId, use another pattern!

These changes are made for PostgreSQL compatibility. But one of these variables is a user-defined variable. I will change it back to "varchar" as soon as I determine which one is the right one.

@neliocaa could you tell me which one or ones are user defined in your database ?

**Comment by neliocaa** [comment]
I currently use both fields, with the same values, I can't confirm at this point the purpose of each one, I need to check with another dev who did an integration that uses this.

> > In my case, the table chat_message, when external type, on sessionId and chatId, use another pattern!
> 
> These changes are made for PostgreSQL compatibility. But one of these variables is a user-defined variable. I will change it back to "varchar" as soon as I determine which one is the right one.
> 
> @neliocaa could you tell me which one or ones are user defined in your database ?

**Comment by HenryHengZJ** [comment]
@neliocaa would you be able to confirm if the fix - https://github.com/FlowiseAI/Flowise/pull/2021 works?

**Comment by neliocaa** [comment]
> @neliocaa would you be able to confirm if the fix - #2021 works?

I'm using a docker image, but it probably solved it, when they release a new release, I'll get back to you with feedback

**Comment by neliocaa** [comment]
plz, update docker image!
