### ISSUE TITLE
DynamoDB Memory not working

### ISSUE THREAD

**Issue by jaredmcqueen** [FlowiseAI/Flowise#2005]
<img width="1341" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/3491953/540dfcbc-9680-4f6c-a451-eeb0b3bac891">

DynamoDB is successfully connected, and I see additional entries get appended to the array on every message.  That said, it does not work.  The LLMs do not remember anything.

If I replace the DynamoDB Memory node with Buffer Memory, it works exactly as you would expect.  Zero other changes.

I'm running 1.6.2

**Comment by jaredmcqueen** [comment]
Found the issue

`this.messageAttributeName` is undefined and causes all the problems:

`const messageAttributeName = this.messageAttributeName` 

leading to nothing being returned here:
`const items = response.Item ? response.Item[messageAttributeName]?.L ?? [] : []`

full code here:

```ts
    async getChatMessages(overrideSessionId = '', returnBaseMessages = false): Promise<IMessage[] | BaseMessage[]> {
        if (!this.dynamodbClient) return []
        console.log('this', this)

        const dynamoKey = overrideSessionId ? this.overrideDynamoKey(overrideSessionId) : this.dynamoKey
        const tableName = this.tableName
        const messageAttributeName = this.messageAttributeName
        console.log('this should be messages', messageAttributeName)

        const params: GetItemCommandInput = {
            TableName: tableName,
            Key: dynamoKey
        }

        const response = await this.dynamodbClient.send(new GetItemCommand(params))
        const items = response.Item ? response.Item[messageAttributeName]?.L ?? [] : []
        const messages = items
            .map((item) => ({
                type: item.M?.type.S,
                data: {
                    role: item.M?.role?.S,
                    content: item.M?.text.S
                }
            }))
            .filter((x): x is StoredMessage => x.type !== undefined && x.data.content !== undefined)
        const baseMessages = messages.map(mapStoredMessageToChatMessage)
        return returnBaseMessages ? baseMessages : convertBaseMessagetoIMessage(baseMessages)
    }

**Comment by jaredmcqueen** [comment]
another fix is on this line https://github.com/FlowiseAI/Flowise/blob/0c0308b9c4e0df9801d5e09bb49726c352bcde99/packages/components/nodes/memory/DynamoDb/DynamoDb.ts#L227

you could do this:
`const messageAttributeName = this.messageAttributeName ?? 'messages'

**Comment by vinodkiran** [comment]
PR Raised. https://github.com/FlowiseAI/Flowise/pull/2011
