### ISSUE TITLE
[BUG] 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"assistant\" roles in a row"}}

### ISSUE THREAD

**Issue by aodrasa** [FlowiseAI/Flowise#2006]
**Describe the bug**
Recieving the following error while in a conversation (often after 2-3 messages sent)
``` 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages: roles must alternate between \"user\" and \"assistant\", but found multiple \"assistant\" roles in a row"}} ```

**To Reproduce**

1. Start chat
2. Exchange a few messages
3. See error

**Expected behavior**
Continued conversation 

**Screenshots**
![CleanShot 2024-03-21 at 11 55 55@2x](https://github.com/FlowiseAI/Flowise/assets/121209163/052ec52f-90ea-4b60-8668-b00534d0bda1)

**Flow**
![CleanShot 2024-03-21 at 11 50 01@2x](https://github.com/FlowiseAI/Flowise/assets/121209163/10b948db-3c46-418d-98ba-78b4a5ea4a2e)

**Setup**

-   Installation: Azure 
-   Flowise Version: 1.6.2	
-   OS: macOS
-   Browser: Safari

**Comment by HenryHengZJ** [comment]
Can you try using XML Agent? As Claude doesnt have support for function calling yet, Conversational Agent might not works well

**Comment by HenryHengZJ** [comment]
<img width="1276" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/172ab7e4-44ba-4421-b350-0cf902e617ff">

**Comment by iperezx** [comment]
I can reproduce a similar error when connecting a start button with a LLM. So we are still seeing this.
I get this error when using the liteLLM provider (gemma3, with tool calling) but then switch it to Ollama provider (gemma3 without tool calling).
