### ISSUE TITLE
packageManager yarn versioning error

### ISSUE THREAD

**Issue by sundance91** [FlowiseAI/Flowise#2009]
I have been getting the below bug when trying to deploy FlowiseAI on render.com as a web service.

error This project's package.json defines "packageManager": "yarn@pnpm@8.14.0". However the current global version of Yarn is 1.22.22.[BUG]
**To Reproduce**

1. Go to 'render.com'
2. Fork the FlowiseAI repo into your local git repo
3. Connect to the FlowiseAI repo on Render using your Git credentials
4. Set Node as your runtime.
5.  Put yarn; yarn install; yarn build
6. Use the Starter Instance type
7. Set No for your Auto-Deploy steps

All of the above steps can be found here: https://www.youtube.com/watch?v=kOwmPe8aLAA&t=234s

**Expected behavior**
The web service is supposed to successfully deploy.

**Screenshots**
<img width="742" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/11153655/e809ebaf-275d-4233-92c2-d3a20a72a802">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version 1.6.2
-   OS: Windows
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by vinodkiran** [comment]
We changed the package manager to PNPM - try using the commands

* npm i -g pnpm
* pnpm install
* pnpm build
* pnpm start
