### ISSUE TITLE
Local LLM

### ISSUE THREAD

**Issue by Bruce-Yue** [FlowiseAI/Flowise#2010]
I want to know, is it support local LLM? Or it only support OpenAI?

**Comment by BadlyDrawnBoy** [comment]
You can use any local LLM povider as long as it provides an OpenAI like API. Means 'localai' (had a lot of trouble trying to get it working), 'Koboldcpp' and others..

**Comment by HenryHengZJ** [comment]
and also Ollama, LocalAI
