### ISSUE TITLE
[BUG] Unable to connect to Postgres-DB in Chatflow module

### ISSUE THREAD

**Issue by simplecloudbox** [FlowiseAI/Flowise#2013]
**Describe the bug**

Unable to connect to Postgres-DB in Chatflow module

**Steps to reproduce the behavior:**

1. Add credentials for Postgres
2. Add Postgres module to Chatflow
3. Add host (tried external subdomain, localhost and IP), DB, port
4. Additional parameters: **sslmode="require"** + add table name
5. Save chatflow
6. Upsert 
7. **Error: error: pg_hba.conf rejects connection for host "XX", user "XX", database "XX", no encryption**

**Expected behavior**
Postgres-DB connection is working

**Setup**

-   Flowise Version 1.6.2
-   Kubernetes

**Screenshots**

<img width="576" alt="Bildschirmfoto 2024-03-21 um 15 34 18" src="https://github.com/FlowiseAI/Flowise/assets/4971898/9612a579-7406-4f64-a576-841ce84122a5">

<img width="1067" alt="Bildschirmfoto 2024-03-21 um 15 32 39" src="https://github.com/FlowiseAI/Flowise/assets/4971898/a69cd3f6-6bec-46c2-b516-1ddf7be23e09">

<img width="670" alt="Bildschirmfoto 2024-03-21 um 15 34 25" src="https://github.com/FlowiseAI/Flowise/assets/4971898/c8e0a999-e064-40a3-8a92-3fdc07f62183">

**Comment by HenryHengZJ** [comment]
yep - https://js.langchain.com/docs/integrations/vectorstores/pgvector#setup-a-pgvector-self-hosted-instance-with-docker-compose

**Comment by rubrix** [comment]
I have added the vector extension but still get the same error... is this because I am use a self-signed certificate? what is the correct parameter for that? I just have sslmode=require exactly as above..
