### ISSUE TITLE
Use Flowise for multiple tables

### ISSUE THREAD

**Issue by BrianMoreno1994** [FlowiseAI/Flowise#2014]
Is it possible to use this tool for multiple tables using the "SQL Prompt" template from the marketplace. 

I've been testing it out and as far as I've seen you can only use it for one table at a time.

Any help is greatly appreciated.

**Comment by HenryHengZJ** [comment]
You can try using SQL Database Chain as that will get all tables from specified database. Otherwise, you'll have to write custom JS code to get the multiple tables
