### ISSUE TITLE
[FEATURE] Return source documents also in embedded chat

### ISSUE THREAD

**Issue by PeterGilles** [FlowiseAI/Flowise#2016]
**Describe the feature you'd like**
When embedding a chatflow e.g. as pop-up html or fullpage html, I can use the chat, but the links to source documents from a Conversational Retrieval QA chain are not displayed as they are when using the testing chat possibilty in the Flowise platform itself. It would be great if they would be shown in the embedded deployments of a chatflow as well.

**Comment by HenryHengZJ** [comment]
Hey @PeterGilles, it should be fixed now with this PR - https://github.com/FlowiseAI/FlowiseChatEmbed/pull/121
