### ISSUE TITLE
[BUG] Conversation Chain returns both the follow-up question and its corresponding answer in a single response with AWS bedrock

### ISSUE THREAD

**Issue by yyipkei123** [FlowiseAI/Flowise#2022]
**Describe the bug**
I recently set up a workflow using Conversation Chain and AWS ChatBedrock. However, I noticed that sometimes the responses include follow-up questions, and I haven't been able to find a way to remove them.

**Expected behavior**
The expected output should only consist of the answer without including the follow-up question and answer.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/124754092/4cb18069-4a27-453d-a5c9-b40efc8d6e34)

**Comment by HenryHengZJ** [comment]
With llama2, you probably need a different prompt. My suggestion is to connect the Conversation Chain to a Chat Prompt Template, and specify the prompt that is more suited towards llama2

**Comment by yyipkei123** [comment]
Thank you. Actually i would like to perform RAG with llama2 and utilize the Conversational Retrieval QA Chain. Could you please guide me on how to adding a Chat Prompt Template for Conversational Retrieval QA Chain? Additionally, do you happen to have any samples or examples on how to perform RAG with llama2 in Flowise?
