### ISSUE TITLE
Is this a bug? Session id Memory 

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#2031]
I notice that when you set up a `Session id` for a Memory Module, lets say `Session Id=Test`,  it only works from the `UI` Source:

--
<img width="1008" alt="Screenshot 2024-03-25 205740" src="https://github.com/FlowiseAI/Flowise/assets/138339291/0ff8b1ae-c381-4495-8b54-748322a4324b">
--

But if you try the same chatbot from the `API/EMBED` source, the `Session id` is random.

--
<img width="981" alt="Screenshot 2024-03-25 205918" src="https://github.com/FlowiseAI/Flowise/assets/138339291/099eaaea-35e9-4871-9d0d-e41daf9b0f52">
--

If this is not a bug, what is the point to set up a custom `Session id`?

It would be very useful if the bot is only being used for 1 user, so they have all the data grouped.

**Comment by saatchi-david** [comment]
@toi500 
I'm experiencing the same when setting a session ID in the Zep memory node. I also expected the set ID to be used everywhere.

**Comment by toi500** [comment]
@saatchi-david 

Apparently it is a thing for all memory nodes. I got this issue with the Zep memory node too and then I tried the Upstash one with the same results.

**Comment by toi500** [comment]
@HenryHengZJ 

Please try to inject the embed script of your testing chatflow to a html file and test it from the font end, that is how I reproduce the bug. I got my flowise instance on Railway, but i dont think this is relevant.

Just tested and got the same results:
![Screenshot 2024-03-30 155827](https://github.com/FlowiseAI/Flowise/assets/138339291/fc559b5b-740c-4045-9ddd-a3a0e010e95b)
![Screenshot 2024-03-30 155844](https://github.com/FlowiseAI/Flowise/assets/138339291/bcd2599d-288a-4778-9878-700826314ecf)

I also get it right via postmant
![Screenshot 2024-03-30 164144](https://github.com/FlowiseAI/Flowise/assets/138339291/68320601-2c91-4488-be73-4678e52bd7b9)

**Comment by HenryHengZJ** [comment]
What does your embedded script looks like? @toi500

**Comment by toi500** [comment]
![Screenshot 2024-03-30 194952](https://github.com/FlowiseAI/Flowise/assets/138339291/e0dfe30c-9601-4543-872d-90cb29b70950)
![Screenshot 2024-03-30 195142](https://github.com/FlowiseAI/Flowise/assets/138339291/52a7d0bf-ecb2-4fbd-a2c0-966f9cac445e)
<img width="863" alt="Screenshot 2024-03-30 195229" src="https://github.com/FlowiseAI/Flowise/assets/138339291/956a8b82-fe67-4468-a247-be97e040cee0">
![Screenshot 2024-03-30 195407](https://github.com/FlowiseAI/Flowise/assets/138339291/674b2f13-c71b-43da-afef-67986ad59283)

**Comment by HenryHengZJ** [comment]
@toi500 for a workaround, since you have hard-coded the sessionId on the UI, you can also do so in the embed script:

```
<script type="module">
    import Chatbot from 'https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js';
    Chatbot.init({
        chatflowid: '80612c28-aae1-446d-8d73-58dfd998d565',
        apiHost: 'http://localhost:3000',
        chatflowConfig: {
            sessionId: "abcde"
        }
    });
  </script>
```

**Comment by toi500** [comment]
It worked. Thank you for that, I really appreciate it.

So, is this sort of buggy or we do need to overwrite the session id via the embed script too?

**Comment by HenryHengZJ** [comment]
This is the current design, you'll have to provide sessionId in the chatflow config for embedded, hard coded sessionId is meant for user to test it on UI

**Comment by toi500** [comment]
Makes sense. Thank you for the clarification, I really appreciate it.
