### ISSUE TITLE
[BUG] ChatAnthropic ignoring Max Tokens (always 256)

### ISSUE THREAD

**Issue by CypherNaught-0x** [FlowiseAI/Flowise#2032]
**Describe the bug**
When using the new Anthropic Chat Models the output is often truncated.
Setting the `Max Tokens` under "Additional Parameters" to the supported limit of 4096 results in the debug output stating the model is still using `max_tokens: 256` and as a result the output gets cut short.

**To Reproduce**
1, Add new Anthropic Chat Model. 
2. Use claude-3-sonnet (should happen with others I believe).
3. Change `Max Tokens` to 4096 under "Additional Settings"
4. Generate output expected to be longer than 256 tokens.
5. Look for `max_tokens` in debug log and see output truncated

**Expected behavior**
The user can change the maximum number of generated tokens.

**Setup**

-   Installation docker
-   Flowise Docker Version 1.6.2
-   OS: Linux

**Comment by HenryHengZJ** [comment]
should be fixed with this [PR](https://github.com/FlowiseAI/Flowise/pull/2003)
