### ISSUE TITLE
[BUG] - [inputText] is not permitted when upgrading to Claude 3 and cohere models

### ISSUE THREAD

**Issue by haimco50** [FlowiseAI/Flowise#2060]
Upgrading bedrock model from claude 2 to claude 3 and embedding model from
amazon.titan-embed-text-v1 to cohere.embed-multilingual-v3
and started getting the bellow errror when tryting to upsert embeddings.

![image](https://github.com/FlowiseAI/Flowise/assets/91170552/f940ef7c-e416-462b-be1e-fe65dd26f9e9)

issue seeems to be related to this issue :
https://github.com/langchain-ai/langchain/pull/18630

and may need upgradiung the conversation retrieval QA chain node to support this but not sure...

![image](https://github.com/FlowiseAI/Flowise/assets/91170552/9fba64d6-4414-4352-847c-a99b831c066d)

**To Reproduce**
trying to upserts / chat after upgrading will cause a validation error to apear.

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by haimco50** [comment]
I changed the embedding model to amazon.titan-embed-g1-text-02 (as it's shown in my flow) so it can work - the issue is happenning with cohere.embed-multilingual-v3 model

**Comment by HenryHengZJ** [comment]
> I changed the embedding model to amazon.titan-embed-g1-text-02 (as it's shown in my flow) so it can work - the issue is happenning with cohere.embed-multilingual-v3 model

thanks for pinning down the issue, can u try to see if upgrading langchain community package solves the issue

**Comment by haimco50** [comment]
Already did so, this is the first thing I did - it didn't work - IMHO the issue seems to be with the Flowise AWS BedrockChat componnent  - see this thread issue - 
https://github.com/langchain-ai/langchain/issues/18514

**Comment by HenryHengZJ** [comment]
found out the issue, because we are using body format that is only compatible with amazon titan embeddings - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/embeddings/AWSBedrockEmbedding/AWSBedrockEmbedding.ts#L150

cohere embeddings require another type of body format
