### ISSUE TITLE
[BUG] Starter Prompt cant be removed after setting them up

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#2065]
**Describe the bug**
After you set up Starter Prompts you cant remove it 100% from the chatbot. Please see captures.

**To Reproduce**
Set up 1 Starter Prompt
Try to delete it
Check the chatbot

**Screenshots**
![Screenshot 2024-03-29 184214](https://github.com/FlowiseAI/Flowise/assets/138339291/5176feaa-dc07-453e-9a54-4e9d4043daed)
<img width="412" alt="Screenshot 2024-03-29 184233" src="https://github.com/FlowiseAI/Flowise/assets/138339291/51b5ebbe-24e3-4461-81d7-580025cc6c3d">

**Setup**
Flowise instance is up to date

**Comment by HenryHengZJ** [comment]
Not on the embedded side yet, waiting for the PR to be merged

**Comment by 0xi4o** [comment]
Fixed in https://github.com/FlowiseAI/FlowiseChatEmbed/pull/131
