### ISSUE TITLE
[BUG] flowise@1.6.2 - QDrant does not return anything 

### ISSUE THREAD

**Issue by philchass** [FlowiseAI/Flowise#2067]
**Describe the bug**
I have a QDrant collection already created (rag_mandat)
When I use Python + Langchain and retrieve info → it works.
In Flowise → I can't retrieve anything :(
 
**Flow**
<img width="1512" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/410509/ef0b7240-3a5f-46d4-9480-ef049d7ae9ac">

**Setup**
[flowise@1.6.2](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.6.2)

**Comment by HenryHengZJ** [comment]
It works fine for me:
<img width="1271" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/60ef5653-aeb5-4a87-8e26-161807a3d1ab">

I can see content from Qdrant was successfully retrieved. If you are using metadata filter, kindly refer to this guide - https://docs.flowiseai.com/integrations/langchain/vector-stores/qdrant#filtering

**Comment by philchass** [comment]
I don't use any metadata in this collection.
My example is the same as yours 🤪
When I try in a chatbot developed with Python and Langchain, it works fine!

**Comment by toi500** [comment]
Did you try to put your Retriever Description in English?

**Comment by philchass** [comment]
Yes, I tried in English.

**Comment by philchass** [comment]
<img width="1696" alt="Capture d’écran 2024-04-04 à 02 00 35" src="https://github.com/FlowiseAI/Flowise/assets/410509/9061790b-2b38-46b1-bd8c-d0001b12fa15">

Here is the LangSmith trace. I can't understand the "\n\n" input for the mandats function.

**Comment by HenryHengZJ** [comment]
Closing for now, feel free to reopen if issue persists
