### ISSUE TITLE
[QUESTION] Conversational Retrieval QA Chain

### ISSUE THREAD

**Issue by fulgorastral** [FlowiseAI/Flowise#2068]
Hi guys. I have been using a lot lately the feature Conversational retrieval QA Chain and I was wondering how the additional parameters work. Rephrase Prompt and Response prompt. Can anyone here help me out? 

Thanks!

**Comment by HenryHengZJ** [comment]
hope this helps - https://docs.flowiseai.com/use-cases/web-scrape-qna#query
