### ISSUE TITLE
[BUG]Can't use ifElseFunction node

### ISSUE THREAD

**Issue by crazygo** [FlowiseAI/Flowise#2078]
**Describe the bug**
When I connected to True, or connected to false, it worked fine. When I chained true and  false together to the following processes, the command line will report exception

**To Reproduce**
![CleanShot 2024-04-02 at 02 23 39@2x](https://github.com/FlowiseAI/Flowise/assets/9395888/c1a49bb1-71a4-4279-86c3-9efcaace79f4)

**Expected behavior**
This node should fork the following processes

**Screenshots**
2024-04-02 02:20:23 [ERROR]: [server]: Error: nodeInstance.run is not a function
TypeError: nodeInstance.run is not a function
    at App.buildChatflow (/Users/admin/Flowise/packages/server/dist/index.js:1934:38)
    at async /Users/admin/Flowise/packages/server/dist/index.js:1265:13

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by crazygo** [comment]
nodeInstance is 
```
IfElseFunction_Utilities {
  label: 'IfElse Function',
  name: 'ifElseFunction',
  version: 1,
  type: 'IfElseFunction',
  icon: 'ifelsefunction.svg',
  category: 'Utilities',
  description: 'Split flows based on If Else javascript functions',
  baseClasses: [ 'IfElseFunction', 'Utilities' ],
  inputs: [
    {
      label: 'Input Variables',
      name: 'functionInputVariables',
      description: 'Input variables can be used in the function with prefix $. For example: $var',
      type: 'json',
      optional: true,
      acceptVariable: true,
      list: true
    },
    {
      label: 'IfElse Name',
      name: 'functionName',
      type: 'string',
      optional: true,
      placeholder: 'If Condition Match'
    },
    {
      label: 'If Function',
      name: 'ifFunction',
      description: 'Function must return a value',
      type: 'code',
      rows: 2,
      default: 'if ("hello" == "hello") {\n    return true;\n}'
    },
    {
      label: 'Else Function',
      name: 'elseFunction',
      description: 'Function must return a value',
      type: 'code',
      rows: 2,
      default: 'return false;'
    }
  ],
  outputs: [
    { label: 'True', name: 'returnTrue', baseClasses: [Array] },
    { label: 'False', name: 'returnFalse', baseClasses: [Array] }
  ]
}

```
nodeInstance.run is undfined

**Comment by HenryHengZJ** [comment]
What processes are you chaining the true and false to? can you share the whole flow?

**Comment by crazygo** [comment]
> What processes are you chaining the true and false to? can you share the whole flow?

hello, It works fine when I checkout with tag flowise@1.6.1 
Perhaps there were some issues in the master branch, I have closed this issue for now.
