### ISSUE TITLE
[question]Flowis 如何配置梯子通过中国可以访问呢openai接口

### ISSUE THREAD

**Issue by huangbz2007** [FlowiseAI/Flowise#2081]
1、Flowise 如何配置梯子通过中国可以访问呢openai接口

2、Flowise 如何配置其他中国的大模型，比如文心一言，智谱等

**Comment by HenryHengZJ** [comment]
目前还没有直接的方式，欢迎任何的pull requests!

**Comment by crazygo** [comment]
可以在 LLM model 里设置 base url

**Comment by iceycc** [comment]
> You can set the base url in the LLM model

How does it work, and are there any examples?
