### ISSUE TITLE
[FEATURE] Upload Files on Claude LLMs

### ISSUE THREAD

**Issue by haimco50** [FlowiseAI/Flowise#2084]
Not sure whether it's a bug or I am misisng something here...but based on the flow description the claude chatflow example should have been able to support uploading files up to 200K tokens but in reality  it supports uploading just image files only.

marketplace flow :
![image](https://github.com/FlowiseAI/Flowise/assets/91170552/3f58f6c3-da23-4d45-9b11-3fdbaab4b882)

any text/pdf file :
![image](https://github.com/FlowiseAI/Flowise/assets/91170552/d6cc8ea4-76cf-4808-9c19-787ed37185ec)

Image:
![image](https://github.com/FlowiseAI/Flowise/assets/91170552/e8534fb2-3737-4286-93a7-73121d243dc6)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
You can include the whole Text File as part of the prompt:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/e2694902-8b39-4999-80d5-ae0c59603069)

[200k Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14850030/200k.Chatflow.json)

**Comment by haimco50** [comment]
but doing it isn't going to solve the UI bot part ? but maybe just with an API integration with a custom bot UI that I can build , right ?
Aplogize if this is a basic question..., I'm new to this platform.
btw, great platform overall, I would be glad to contribute down the road once I know more...:-)

**Comment by HenryHengZJ** [comment]
oh you want to have the upload file option on the chatbot? if so, you will have to implement the frontend part on your side and you can use the API for backend:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/3d93cee5-354a-4612-88b5-37cb2119fa72)

**Comment by haimco50** [comment]
yes, I can do so but....it would be much nicer and maybe faster...to support file upload for None image file from the chatbot...exactly as it's in claude.AI website,

**Comment by HenryHengZJ** [comment]
PR here: https://github.com/FlowiseAI/Flowise/pull/3314
