### ISSUE TITLE
Custom POST Variables - API

### ISSUE THREAD

**Issue by BrianMoreno1994** [FlowiseAI/Flowise#2087]
Hi, I am currently consuming Flowise's API for a custom chatbot. 

The template I am using is the "SQL Prompt" to make queries to the DB and output a natural language response based on the query executed. So far so good, however, I'd like to be able to send a custom variable to the API and create queries that only apply to that variable.

For example, I'd like to send a variable via POST called "customer_id" and the queries created should only apply to that customer.

I've read that I have to use `overrideConfig` to achieve this and have included it in my POST request body, but I haven't gotten any luck yet.

```
overrideConfig: {
  vars: {
    customer_id: this.customer_id
  }
}
```

So I have two issues:

1. How can I retrieve that POST variable and use it inside the prompt?

2. Do you think the following prompt template is good enough or should I add something else?
```
Based on the provided SQL table schema and question below, return a SQL SELECT ALL query that would answer the user's question. For example: SELECT * FROM table WHERE id = '1'. 

Don't add ```sql or '```sql in the beginning
This query should only apply for customer [INSERT-CUSTOMER-ID-HERE]
------------
SCHEMA: {schema}
------------
QUESTION: {question}
------------
SQL QUERY:
```

**Comment by HenryHengZJ** [comment]
to use it within prompt, you will have to first use `CustomFunction` node to catch the `vars`, then pass into the `Format Prompt Values` of Prompt Template
