### ISSUE TITLE
OpenAI Assistant error: Error processing thread

### ISSUE THREAD

**Issue by GustavoSD** [FlowiseAI/Flowise#2096]
**Describe the bug**
I'm trying to create a chatbot with OpenAI Assistant Agent, then I create an assistant, then save. When I try to interact with the both, I get the error....

Error: Error processing thread: failed, Thread ID: thread_xxx, Run ID: run_xxxStatus: failed

**To Reproduce**
Create a new Chartflow.
1. Add a new node -> Agents -> OpenAI Assistant
2. Configure the assistant
3. Save
4. Try the chatbot (try saying Hello).

**Expected behavior**
It should respond, but instead it shows an error.

**Comment by HenryHengZJ** [comment]
Should be resolved in latest version. Feel free to reopen if issue persists
