### ISSUE TITLE
[BUG]  csv agent error: PythonError: Traceback

### ISSUE THREAD

**Issue by tomorrowthief** [FlowiseAI/Flowise#2098]
**Describe the bug**
when use csv agent， got this error：

flowise:dev: 2024-04-04 10:23:47 [INFO]: ⬆️ POST /api/v1/internal-prediction/e95eeae6-00b3-42e6-96b0-1856507ce4c9
flowise:dev: 2024-04-04 10:23:47 [ERROR]: [server]: Error: PythonError: Traceback (most recent call last):
flowise:dev:   File "/lib/python311.zip/_pyodide/_base.py", line 573, in eval_code_async
flowise:dev:     await CodeRunner(
flowise:dev:   File "/lib/python311.zip/_pyodide/_base.py", line 393, in run_async
flowise:dev:     coroutine = eval(self.code, globals, locals)
flowise:dev:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
flowise:dev:   File "<exec>", line 1, in <module>
flowise:dev: ModuleNotFoundError: The module 'pandas' is included in the Pyodide distribution, but it is not installed.
flowise:dev: You can install it by calling:
flowise:dev:   await micropip.install("pandas") in Python, or
flowise:dev:   await pyodide.loadPackage("pandas") in JavaScript
flowise:dev: See https://pyodide.org/en/stable/usage/loading-packages.html for more details.

<img width="937" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/9032068/77ea2bbf-0253-411f-a963-dd9460d8d658">

**To Reproduce**

1. local devlopment
2. use csv agent
3. See error

**Setup**

-   latested branch main
-   macos monterey 12.1 chips: apple m1

**Comment by tomorrowthief** [comment]
i have install pandas by pip install pandas

**Comment by HenryHengZJ** [comment]
Tested and seems to be working:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/1cd26728-b4a5-4b26-999f-f20db695e76e)

You shouldnt need to install pandas separately, as they are automatically loaded by pydiode [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/agents/CSVAgent/core.ts#L12)

**Comment by tomorrowthief** [comment]
ok，i will try again。
