### ISSUE TITLE
Conversational Retrieval QA Chain - context update - question

### ISSUE THREAD

**Issue by haimco50** [FlowiseAI/Flowise#2103]
Is there any way to update the context  of  the Conversational Retrieval QA Chain (chatFlow from marketplace) - seems that that the context is "Hard Coded" with only the info coming from the vector store and there is no way to update it externally - ideally I want to have the ability to update it from a plan text file

**Comment by toi500** [comment]
Do you me this one?

![Screenshot 2024-04-05 003352](https://github.com/FlowiseAI/Flowise/assets/138339291/67502322-a365-410b-a773-485c6aa18bf8)

**Comment by haimco50** [comment]
thanks for your answer - I know I can edit the prompt over this area , the issue is that I want to update it from an external file and potentially from some template file dynamicly, if the node component had another input with some prompt node that would be ideal or in other way somehow...

**Comment by toi500** [comment]
No sure what you want to accomplish here but when you a Multi Retrieval QA Chain you can add a Vector Store Retriever node to let the model know when you use the info from a Vector Store and then, if you want to, use the Chain Tool to connect the whole chain to an Agent and let the Agent when to use the chain.

I do not think there is a easy way to do it "dynamically".

--
<img width="1322" alt="Screenshot 2024-04-05 144151" src="https://github.com/FlowiseAI/Flowise/assets/138339291/7e88a2d5-de61-48e9-b42d-1c6ca1fca7aa">
--
![Screenshot 2024-04-05 144411](https://github.com/FlowiseAI/Flowise/assets/138339291/0ff2c766-75e8-4a07-a477-a40e1af64c34)
 --

Here is the template of the whole chatfhow:
[Template (Multi Retrieval Chain) Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14885122/Template.Multi.Retrieval.Chain.Chatflow.json)

**Comment by HenryHengZJ** [comment]
@haimco50 the ideal way is as follow:
1.) Upsert your data with different metadata to vector store
2.) Using Flowise API, you can override the config metadata filter:
```
{
  "question": "what is my name",
  "overrideConfig": {
     "pineconeMetadataFilter": {"source": "doc1"}
  }
}
```

**Comment by haimco50** [comment]
thanks much @toi500 and @HenryHengZJ for your suggestions - will try it out!
