### ISSUE TITLE
[BUG] Unable to set up Starter Prompts 

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#2107]
Error when you try to save a Starter Prompt. Please see capture.

**Screenshots**
![Screenshot 2024-04-05 152023](https://github.com/FlowiseAI/Flowise/assets/138339291/ddf6fad4-584c-4b01-987e-5e6c7926b397)

**Setup**

-   Flowise Version 1.6.3

**Additional context**
I know that the started prompts are kinda buggy from my last report #2065

**Comment by HenryHengZJ** [comment]
Should be resolved with this PR https://github.com/FlowiseAI/Flowise/pull/2116

**Comment by HenryHengZJ** [comment]
Released the fix in `v1.6.4`
