### ISSUE TITLE
[BUG] Docker fails to run with new version flowise@1.2.10 release 

### ISSUE THREAD

**Issue by gavytron** [FlowiseAI/Flowise#211]
**Describe the bug**
flowise/1.2.6 linux-x64 node-v18.16.0   used to work with Windows 10 WSL Docker Desktop.
BUT
After updating the local repository to 1.2.10 release  (commit/0dbd9e1127a9f2006783ac4151821ef20f3329a5)
the container stops running immediately after the command
docker run -d --name flowise -p 3000:3000 flowise

**To Reproduce**
git pull
https://github.com/FlowiseAI/Flowise/commit/0dbd9e1127a9f2006783ac4151821ef20f3329a5

cd docker
docker build --no-cache -t flowise .
docker run -d --name flowise -p 3000:3000 flowise

Go to Docker desktop and see that the image is not running
Press the "play" button to run it and observe that it stops running immediately (exit code 0).
The browser of course gives error:
Firefox can’t establish a connection to the server at localhost:3000.

**Expected behavior**
Docker used to run on Windows+WSL2+Docker desktop
The container used to be running, the browser used to work at localhost:3000

**Screenshots**

**Setup**

-   OS: Windows 10 + WSL2 Ubuntu
-   Browser: Firefox localhost:3000

**Additional context**
used to work before version flowise@1.2.10 release
flowise/1.2.6 linux-x64 node-v18.16.0   used to work with Windows 10 WSL Docker Desktop

**Comment by HenryHengZJ** [comment]
hey, are you running docker via docker compose or are you building the image locally?

For docker-compose: https://github.com/FlowiseAI/Flowise#docker-compose

For running image locally: https://github.com/FlowiseAI/Flowise#docker-image

Note: you only need to `cd` into docker folder when using docker compose, if you are building image locally, do it on the root level

**Comment by gavytron** [comment]
thank you :-)

**Comment by HenryHengZJ** [comment]
Not yet have that, will put that in soon! :)
