### ISSUE TITLE
[FEATURE] Prevent the documents from being queried again when requesting for a completion

### ISSUE THREAD

**Issue by mateusluizfb** [FlowiseAI/Flowise#2110]
**Describe the feature you'd like**
I'm looking for a way to prevent the documents from being queried again when requesting for a completion.

**Additional context**
I have a vector store connected to multiple Puppeteer Document nodes, this vector store was updated using the upsert function. But it looks like every time I ask for a completion, those Document nodes are running again and blocking the request to proceed with the persisted info from the vector store, that it was previously upserted and it wouldn't need to load the documents again.

To deal with this scenario, I had to create two separate flows: one for the upsert and one for completion only, where the latter doesn't have the document nodes connected to the vector store.

**Comment by HenryHengZJ** [comment]
Fixed [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/utils/index.ts#L512)
