### ISSUE TITLE
[BUG] Hugging Face and AWS deployment - incomplete response

### ISSUE THREAD

**Issue by Jakub-Zak** [FlowiseAI/Flowise#2118]
I have deployed FlowiseAI into Hugging Faces and to AWS, as described by your documentation. Application works, everything runs OK, but when I execute valid OpenAI chat, that works properly on localhost, response is cut (stream ends after ~10 seconds) and isn't completed (not even word is completed). Is there any property that I should setup? It seems like timeout, but no error generated.  I've done testing of this behavior in both FlowiseAI web interface and even via REST API via Postman. 

Thanks for help!

**Comment by HenryHengZJ** [comment]
Have you tried setting a higher Max Tokens?

**Comment by Jakub-Zak** [comment]
Thanks for heads up. I've left it on default setup as I had it after installation. Let me try it...
