### ISSUE TITLE
[FEATURE] Automatic Inclusion of File Name in Metadata for CSV and PDF Imports

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2129]
**Describe the feature you'd like**
I would like Flowise to have a feature where both CSV and PDF import nodes automatically capture and include the name of the imported file in the metadata. A clear and concise inclusion of file names in the metadata would provide significant benefits for users who need to track the origins of their data across various documents and ensure efficient data processing and management.

**Additional context**
As it stands, there doesn't appear to be a built-in feature to automatically append the file name of imported CSV or PDF documents to their respective metadata within Flowise. This functionality would be particularly useful when handling multiple files, as it would aid in maintaining organized records and enhance traceability. If this can be implemented or if there are any plans for such an enhancement in upcoming releases, it would be excellent to know. Additionally, if there are any current methods or scripts that can serve as a temporary solution, that information would also be valuable.

Thank you for considering adding this capability. It would surely be a valuable addition to the FlowiseAI toolkit.

**Comment by HenryHengZJ** [comment]
thanks for the suggestion! For now, its abit manual as you will have to add as part of the metadata:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/bbc5da6c-cc94-430c-9243-dd32a3535180)

**Comment by haimco50** [comment]
@HenryHengZJ , @seonghobae 
Great enhancement suggestion indeed - 2 questions related to this :
1) instead of this "manual/Hard coded process" - is it possible to take the file name from pdffile field (it didn't work...) - something like...

![image](https://github.com/FlowiseAI/Flowise/assets/91170552/ed76485b-18ae-48b6-8ac2-5c07043e79e6)

2) also , if I want the file name  or any other additional field to be upserted to my Embedding Postgres DB as an additional embedding key  - any idea how to do it ? tried to "play" with the additional configuration of Postgres node but without success 

Thanks for any lead here - been struggling on this for some time


Thankd for any lead here - been strugelling on this for some time

**Comment by seonghobae** [comment]
> @HenryHengZJ , @seonghobae Great enhancement suggestion indeed - 2 questions related to this :
> 
> 1. instead of this "manual/Hard coded process" - is it possible to take the file name from pdffile field (it didn't work...) - something like...
> 
> ![image](https://private-user-images.githubusercontent.com/91170552/322625609-ed76485b-18ae-48b6-8ac2-5c07043e79e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyOTAwNjcsIm5iZiI6MTcxNDI4OTc2NywicGF0aCI6Ii85MTE3MDU1Mi8zMjI2MjU2MDktZWQ3NjQ4NWItMThhZS00OGI2LThhYzItNWMwNzA0M2U3OWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA3MzYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlZGUxNzI5ZDFjMzkzMGQwZDJhYWQ2MDRkZmZjNTA4NDIzYWMwMDhhZWRkM2IwMDY4YWFjYzIyYTJmZjM1MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PEDEPUd9j4bImAD9ZOUE2NIDSwUkiE6ZiAIGdIbqMTo)

I don't know It's possible, because I'm not expert of javascript language. However If I put files into vector store with GitHub, can write repository information and file informations into metadata automatically.

> 
> 2. also , if I want the file name  or any other additional field to be upserted to my Embedding Postgres DB as an additional embedding key  - any idea how to do it ? tried to "play" with the additional configuration of Postgres node but without success
> 
> Thanks for any lead here - been struggling on this for some time
In recent version, upsert function has been updated.

**Comment by HenryHengZJ** [comment]
Try using document store, you can do that by setting the metadata field:
![image](https://github.com/user-attachments/assets/11342fef-602f-4161-8757-e15465761171)

Its abit manual but not too difficult
