### ISSUE TITLE
[FEATURE] Support for top_p parameter in AzureChatOpenAI.ts

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2130]
**Describe the feature you'd like**
I'd like to request the addition of support for the `top_p` parameter within the AzureChatOpenAI.ts file used by Flowise AI. In the current implementation, there seems to be no section for specifying the `top_p` parameter which is crucial for controlling the probability distribution when generating text responses. This is unlike the existing provisions in ChatOpenAI.ts where we have `if (topP) obj.topP = parseFloat(topP)` allowing for dynamic adjustments.

Having this feature within AzureChatOpenAI.ts would align the capabilities of using Azure as a backend with the flexibility offered when using OpenAI directly. It will enable developers to fine-tune responses for more creative or deterministic outputs based on their use cases.

**Additional context**
The `top_p` parameter is an important feature for many developers who rely on controlling response randomness and determinism. The inclusion of this parameter will enhance the customization capability for those using Azure-backed models through Flowise AI.

Here is a comparison for reference:
In ChatOpenAI.ts:
```ts
if (topP) obj.topP = parseFloat(topP);
```

Currently missing in AzureChatOpenAI.ts.

Best,
Seongho Bae

**Comment by HenryHengZJ** [comment]
Thanks for the suggestion! Would you love to open a pull request for that?

**Comment by seonghobae** [comment]
JavaScript is a complex language for me because I am not familiar with this framework, so I'm not confident in making a pull request to suggest improvements.
