### ISSUE TITLE
[BUG]The FullPageChat ( via shared link) does not support multi-line input when holding down the shift key; however, the popup one in editing mode can do this.  Thank you!

### ISSUE THREAD

**Issue by nne998** [FlowiseAI/Flowise#2136]
The FullPageChat ( via shared link) does not support multi-line input when holding down the shift key; however, the popup one in editing mode can do this.

Thank you!

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/FlowiseChatEmbed/pull/131

**Comment by HenryHengZJ** [comment]
should be released with the latest embed version
