### ISSUE TITLE
Same chat history showing in different chat flow

### ISSUE THREAD

**Issue by mahaboobkhan29** [FlowiseAI/Flowise#214]
I have two chatflows. When I chat in the first chatflow, the chat history is showing in the second chatflow. I thought that if I log in on a different system, the chat history would reset, but it is still showing.

So, if I use an embed script on our website, will the chat history of different users show to all users?

**Comment by HenryHengZJ** [comment]
hey @mahaboobkhan29 Flowise is single user based for now. Chat messages are based on chatflow.

Having said that, chat embed works a lil bit different. Chat messages from embedded chat will not get stored to database. If user refresh your website, the chat messages will be gone. So users wont see each other messages if thats what youre asking

**Comment by mahaboobkhan29** [comment]
Hello @HenryHengZJ , yes, that's exactly what I'm asking. I have been using Flowise for the past month; it's great and easy to use. You are doing a fantastic job! I hope it remains open source forever. Also, I am interested in a conversational retrieval chain with source links. Are you working on that?

**Comment by HenryHengZJ** [comment]
Yep, will be working on that next - https://github.com/FlowiseAI/Flowise/discussions/188

**Comment by HenryHengZJ** [comment]
Return source docs now supported using ConversationalRetrievalQAChain - https://github.com/FlowiseAI/Flowise/pull/274
