### ISSUE TITLE
PineconeNotFoundError: A call to https://api.pinecone.io/indexes/index1 returned HTTP status 404.

### ISSUE THREAD

**Issue by zbalsara21** [FlowiseAI/Flowise#2144]
I am using 1.6.3 build and since morning I am not able to connect to my flow. I keep getting this error message when I try to query to my chatbot or upsert.

PineconeNotFoundError: A call to
https://api.pinecone.io/indexes/index1
returned HTTP status 404.

I am not using serverless index. Can someone please help.

**Comment by AtendePro** [comment]
Good afternoon
I'm facing an ERROR when connecting Flowise with Pinecone, it apparently doesn't upload the file and doesn't create the indexes

PineconeUnmappedHttpError: An unexpected error occurred while calling the
https://api.pinecone.io/indexes/firstindex
endpoint.

Error: Forbidden
Your client does not have permission to get URL /indexes/firstindex from this server.
Status: 403.

I tested it now by getting the API
{
     "statusCode": 500,
     "success": false,
     "message": "Error: vectorsService.upsertVector - SyntaxError: Unexpected token k in JSON at position 1",
     "stack": {}
}
One difference I saw in mentoring training is that now at Pinecone there is no longer the APi Enviroment

Error: vectorsService.upsertVector - Error: PineconeUnmappedHttpError: An unexpected error occurred while calling the https://api.pinecone.io/indexes/firstindex endpoint. <html><head> <meta http-equiv="content-type" content="text/html;charset=utf-8"> <title>403 Forbidden</title> </head> <body text=#000000 bgcolor=#ffffff> <h1>Error: Forbidden</h1> <h2>Your client does not have permission to get URL <code>/indexes/firstindex</code> from this server.</h2> <h2>< /h2> </body></html> Status: 403.
![Captura de Tela 2024-04-29 às 17 24 01](https://github.com/FlowiseAI/Flowise/assets/168581650/6d2b2384-2498-44d4-b732-c6c245f4a593)
![Captura de Tela 2024-04-29 às 17 24 44](https://github.com/FlowiseAI/Flowise/assets/168581650/3edc87e5-f711-460a-9a71-f20372a2f3a6)
![Captura de Tela 2024-04-29 às 17 25 06](https://github.com/FlowiseAI/Flowise/assets/168581650/c763731c-fb01-4787-9df2-f69e4c839138)
![Captura de Tela 2024-04-29 às 17 26 11](https://github.com/FlowiseAI/Flowise/assets/168581650/8276914d-da8f-43b8-8764-26037a8566af)
![Captura de Tela 2024-04-29 às 17 26 31](https://github.com/FlowiseAI/Flowise/assets/168581650/752902c9-6a34-4c7e-8068-c75c684d39e8)
![Captura de Tela 2024-04-29 às 17 27 07](https://github.com/FlowiseAI/Flowise/assets/168581650/58c0294d-f239-4e12-b562-5865e5b8285c)
![Captura de Tela 2024-04-29 às 17 28 15](https://github.com/FlowiseAI/Flowise/assets/168581650/41a69cba-88a5-4db1-91f1-2a8fe0768091)
![Captura de Tela 2024-04-29 às 17 31 42](https://github.com/FlowiseAI/Flowise/assets/168581650/c70d2220-68bd-48dc-8cfe-287db70e64dc)
![Captura de Tela 2024-04-29 às 18 17 54](https://github.com/FlowiseAI/Flowise/assets/168581650/7b907de9-5bc5-4190-ae3c-e8cc4289c989)
![Captura de Tela 2024-04-29 às 19 06 40](https://github.com/FlowiseAI/Flowise/assets/168581650/7fd5ee22-742b-4fbc-ac59-1a874ec67fb7)

**Comment by RespectMashego** [comment]
did you guys foubd solution?. i am experiencing same issue

**Comment by HenryHengZJ** [comment]
should be resolved now with the pinecone version upgrade - https://github.com/FlowiseAI/Flowise/pull/2310

feel free to reopen if issue still persists

**Comment by mabdullahabid** [comment]
Looks like this is happening again!

**Comment by mabdullahabid** [comment]
```
2024-08-30 07:07:10 [ERROR]: PineconeUnmappedHttpError: An unexpected error occured while calling the https://api.pinecone.io/indexes/gondola-site-gen endpoint.  
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/indexes/gondola-site-gen</code> from this server.</h2>
<h2></h2>
</body></html>
 Status: 403.
Error: PineconeUnmappedHttpError: An unexpected error occured while calling the https://api.pinecone.io/indexes/gondola-site-gen endpoint.  
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/indexes/gondola-site-gen</code> from this server.</h2>
<h2></h2>
</body></html>
 Status: 403.
    at Pinecone_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Pinecone/Pinecone.js:80:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:415:37)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:126:32)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2024-08-30 07:07:10 [ERROR]: [server]: Error: Error: PineconeUnmappedHttpError: An unexpected error occured while calling the https://api.pinecone.io/indexes/gondola-site-gen endpoint.  
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/indexes/gondola-site-gen</code> from this server.</h2>
<h2></h2>
</body></html>
 Status: 403.
Error: Error: PineconeUnmappedHttpError: An unexpected error occured while calling the https://api.pinecone.io/indexes/gondola-site-gen endpoint.  
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/indexes/gondola-site-gen</code> from this server.</h2>
<h2></h2>
</body></html>
 Status: 403.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:493:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:126:32)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
```

**Comment by Aplex2723** [comment]
Yep, same from this side, getting Error: vectorsService.upsertVector - Error: PineconeNotFoundError: A call to https://api.pinecone.io/indexes/sawzilla-kb-stihl returned HTTP status 404.

**Comment by mossyblog** [comment]
Same error as the above, followed same steps and same outcomes as the above comments.

**Comment by SnahNitram** [comment]
This happens almost once every 24h for my setup. A restart of flowise resolves it, but it is utterly annoying.

**Comment by kennyakers** [comment]
Also seeing this problem.
