### ISSUE TITLE
[FEATURE] Suppress System Messages in Frontend

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#2152]
**Describe the feature you'd like**
In the Embed Chat configuration, allow the option to set up a default error response that the chatbot will provide when it encounters unexpected issues. This will prevent technical error messages from being displayed to users in the frontend, improving the user experience and avoiding the disclosure of sensitive information.

--
<img width="502" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/138339291/ad4b1b35-8a7c-4f33-88cb-0f20cd918283">
--

**Additional context**
Currently, the chatbot display system errors directly to users in the frontend. While this is helpful for debugging, it can be awkward and expose internal technical details that users shouldn't see in a production environment.

--
![Screenshot 2024-04-10 163027](https://github.com/FlowiseAI/Flowise/assets/138339291/46d1395b-aa5c-49b1-b3e2-bf14e7ef944b)
--

**Comment by saatchi-david** [comment]
I've been meaning to ask for the same. This is an important one. I would only add that it would be ideal to specify in the chatflow configuration rather than the embed so the error message could be used when the chatflow is accessed via api as well.

**Comment by toi500** [comment]
Actually you are right. Setting this custom system message in the Chatflow Configuration would be even better.

**Comment by HenryHengZJ** [comment]
@0xi4o has put up a [PR](https://github.com/FlowiseAI/FlowiseChatEmbed/pull/139) for that.

You can now specify custom error message on embedded:
```
Chatbot.init({
    chatflowid: '91e9c803-5169-4db9-8207-3c0915d71c5f',
    apiHost: 'http://localhost:3000',
    theme: {
      chatWindow: {
        errorMessage: 'This is a custom error message'
      }
    }
})
```

**Comment by saatchi-david** [comment]
Awesome! Thanks Henry!
