### ISSUE TITLE
[BUG] CORS_ORIGINS failing when using docker-compose

### ISSUE THREAD

**Issue by mateusluizfb** [FlowiseAI/Flowise#2157]
**Describe the bug**
When using a docker-compose, for some reason setting the CORS_ORIGINS like this: `CORS_ORIGINS="*"` doesn't work, only if you set like `CORS_ORIGINS=*`

**To Reproduce**
Just run the docker-compose passing `CORS_ORIGINS="*"` and try to request a embeded chat from another origin.

**Expected behavior**
To work with both `CORS_ORIGINS="*"` or `CORS_ORIGINS=*`, or any custom origin

**Screenshots**

### Response headers using `CORS_ORIGINS="*"`
![Screenshot 2024-04-11 at 11 52 22](https://github.com/FlowiseAI/Flowise/assets/14284674/f002ff3d-56d7-44c7-aa17-fc0e50743abd)

### Response headers using `CORS_ORIGINS=*`
![Screenshot 2024-04-11 at 11 54 10](https://github.com/FlowiseAI/Flowise/assets/14284674/fe17e76d-171c-4f85-b27a-0021131b97e6)

**Setup**

-   Installation docker, using docker-compose
-   Flowise Version: 1.6.0
-   OS: macOS
-   Browser chrome,

**Additional context**
I've noticed that the problem persists with any custom origin when using docker, not sure if happens when running natively.

**Comment by HenryHengZJ** [comment]
ah okay, we should change the `.env.example` from `# CORS_ORIGINS="*"` to `# CORS_ORIGINS=*`

**Comment by jiabaow** [comment]
Hello, it looks like the problem is already fixed. Maybe this issue can be closed now.
