### ISSUE TITLE
Unable to pass data through to Webhook in Make.com

### ISSUE THREAD

**Issue by ridabourji1988** [FlowiseAI/Flowise#216]
This is the setup i have for my chatbot:
<img width="910" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/8b7c558e-d104-4b26-a4b4-a126e455c593">

This is the code to connect to the chain:

import requests

API_URL = "https://flowise-chat-doc-********************************************"

def query(payload):
    response = requests.post(API_URL, json=payload)
    return response.json()
    
output = query({
    "question": "Hey, how are you?",
})

========================

This is the inputConfig:

import requests

API_URL = "https://flowise-chat-doc-******************************************************"

def query(payload):
    response = requests.post(API_URL, json=payload)
    return response.json()

output = query({
    "question": "Hey, how are you?",
    "overrideConfig": {
        "temperature": 1,
        "maxTokens": 1,
        "topP": 1,
        "frequencyPenalty": 1,
    }
})

===========================

Now this is the webhook setup in Make.com :  

<img width="442" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/dadb5b01-321f-4db6-8569-9bc2c0ad2d1d">

<img width="842" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/edc52238-d77c-49d8-9b28-45437eff1adf">

=============================

Data Structure:

<img width="726" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/46fda497-162e-459d-b496-2d4607d0f7b2">
<img width="731" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/1797f27a-ccb6-4e1f-9eee-6b298ec12783">
<img width="737" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/176f83ea-f799-42ed-8829-c6b691dc4f75">

<img width="728" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/e55d7b76-4fde-436c-b89e-50f3e823510f">

==============================

After making a request from Bubble:

<img width="924" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/fa59799c-68a0-4377-8282-ca094a70fc2b">

No data pass through: 

<img width="552" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/133111502/d5c74d5c-db6b-4497-a2a2-ece62462efe2">

**Comment by HenryHengZJ** [comment]
hey @ridabourji1988 we recently just introduce APIChain which you can call any webhook using POST request.

If you update to `1.2.10` version, you can see it from the marketplace - `API Agent`. In that template, we can call any webhook and passing the data as well (I was using Pipedream). We'll be deprecating and remove this MakeWebhook in next release.

PR - https://github.com/FlowiseAI/Flowise/pull/197

https://twitter.com/FlowiseAI/status/1663585856609714188

**Comment by ridabourji1988** [comment]
hey @HenryHengZJ thanks for taking the time to look at my issue and respond.
I don't know the reason behind deprecating MakeWebhook but i guess it would be cool to integrate it as part of the tools/toolkits available for agents. I see it similar to Zapier NLA where you can create some tools that will be used by the agent if needed. The power of make is that you can build complex scenarios with conditions whereas in Zapier is more of a linear/sequential scenario without the ability to integrate conditions. I will try API Chain and will let you know if that solves the issue ;) Great work ! Keep moving forward !

**Comment by HenryHengZJ** [comment]
I've written a guide on how to create custom tool that can call any webhook endpoint and pass in dynamic body - https://docs.flowiseai.com/use-cases/webhook-tool
