### ISSUE TITLE
[BUG] No response from html embed from flowise deployed on digital ocean

### ISSUE THREAD

**Issue by leonkiong** [FlowiseAI/Flowise#2162]
hi, non-coder here please go easy on me. 

Have followed the steps to deploy flowise onto digital ocean, no issues on the deployment, everything works. Created a simple openai chatflow (LLM chain, OpenAI model, simple tell a joke about {subject} prompt template) to test. Works in my deployed digital ocean domainname/canvas, also worked when using the share chatbot option in embed pop-up.

Issue is when I use the popup html or fullpage html embed code and embed into the body of a webpage, I'm not getting a response, it just shows the three dot processing chat bubble after i typed my first input in the chatbox.

I've set up Langsmiith to monitor the chatflow configuration, it monitored the canvas and share chatbot inputs but nothing from the html embeds. 

Grateful to anyone that has a resolution to this and apologies if this problem has been surfaced before. I'll continue to scan the boards for a solution.

**Comment by toi500** [comment]
Can you please share a capture of your chatflow so we can check ur configuration?

**Comment by HenryHengZJ** [comment]
you should have smtg similar to this in your embedded code:
```
<script type="module">
      import Chatbot from "https://cdn.jsdelivr.net/gh/HenryHengZJ/FlowiseChatEmbed-Test/dist/web.js"
      Chatbot.init({
          chatflowid: "chatflow-id",
          apiHost: "http://localhost:3000",
      })
</script>
```

You'll need to change the `apiHost` to your Digital Ocean IPv4 address, smtg like `175.30.10.1:3000`

**Comment by amansoniamazatic** [comment]
@leonkiong @HenryHengZJ , I think you are encountering a CORS error. To confirm whether it's indeed a CORS error, simply type a message in the embed chatbot, then open the inspect menu and navigate to the networking tab. If you see any CORS-related entries, then it's a CORS error. To resolve this issue, just add the following environment variable to your .env file:

CORS_ORIGINS=your main domain website
