### ISSUE TITLE
[FEATURE] Allowing users to access the chatbot with no username and password

### ISSUE THREAD

**Issue by jeffjoslin** [FlowiseAI/Flowise#2163]
First, we wanted to extend our appreciation for all the effort in developing this amazing application, Thank you!

Feature Request:
Ability to set a username and password for the designer only allowing users to access the chatbot with no username and password.

**Comment by HenryHengZJ** [comment]
Thanks! In the Share Chatbot page, you can turn on Make Public, to allow users to access chatbot without username and password:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/3d10f1e1-e473-48a6-bdb1-b55cdbfe0f0a)

**Comment by jeffjoslin** [comment]
Thank you!!! Again, truly appreciate you fast response! :)
