### ISSUE TITLE
[BUG] Node Search function: Does not retrieve React Agent

### ISSUE THREAD

**Issue by mike4lyf** [FlowiseAI/Flowise#2164]
**Describe the bug**
When searching for nodes via Flowise UI (top left button), search function does not work as expected. Cannot find ReAct Agent

**To Reproduce**
1. On Chatflow development screen
2. Add node button
3. Search nodes for: **rea**
4. Does not return any ReAct agent nodes

**Expected behavior**
List of search results includes 'ReAct Agent for xxx'

**Screenshots**

![rea](https://github.com/FlowiseAI/Flowise/assets/8893034/0c3c4472-da3b-45cb-a59e-c5b3b6ad0c55)
![search](https://github.com/FlowiseAI/Flowise/assets/8893034/f64d0f70-7f7f-4af6-aae5-8bad5ccc6006)

**Setup**

-   Installation: npx flowise start
-   Flowise Version: 1.6.4
-   OS: Windows
-   Browser: Firefox

**Additional context**
NIL

**Comment by HenryHengZJ** [comment]
good catch! we still have the name as `mrklAgent` - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/agents/MRKLAgentChat/MRKLAgentChat.ts#L30

We'll need to update those as well

**Comment by HenryHengZJ** [comment]
Solved with this [PR](https://github.com/FlowiseAI/Flowise/pull/2180)
