### ISSUE TITLE
[FEATURE] Claude 3 Tool Agent

### ISSUE THREAD

**Issue by BadlyDrawnBoy** [FlowiseAI/Flowise#2168]
**Describe the feature you'd like**
Anthropic released a description of how to use Claude 3 with Tools: https://docs.anthropic.com/claude/docs/tool-use
It would be nice to have a agent that is specialized for this, like the MistralAI Tool Agent.

Thanks a lot for your great work!

**Comment by HenryHengZJ** [comment]
we are deprecating all specialized tool agent, but instead a common Tool Agent. This agent can be used with Anthropic, OpenAI, Vertex, Mistral:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/efb27411-6914-4783-a701-a63c4c5db7cc)

**Comment by BadlyDrawnBoy** [comment]
If I was smart enough (without having to use AI) to contribute to the project, I would definitely do so - I haven't yet figured out what is needed to write my own modules or where to find what / how the implementation of the tool use is done. Anyway, thank you very much!

**Comment by giachat** [comment]
> we are deprecating all specialized tool agent, but instead a common Tool Agent. This agent can be used with Anthropic, OpenAI, Vertex, Mistral: ![image](https://private-user-images.githubusercontent.com/26460777/322279925-efb27411-6914-4783-a701-a63c4c5db7cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxMTczMDEsIm5iZiI6MTcxMzExNzAwMSwicGF0aCI6Ii8yNjQ2MDc3Ny8zMjIyNzk5MjUtZWZiMjc0MTEtNjkxNC00NzgzLWE3MDEtYTYzYzRjNWRiN2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE0VDE3NTAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMjFkZTQ1NDMxYzg5MDEzMmZmYTUzYzEyMDQ0OWVmZDdiMGMxYjU4M2Y4ZjlmMzdhOTE4NmJhYjZlYWI5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rDas-kaHvdWoqfgauMmmQCkn4gxmfR5fSez3EnbEMT4)
> 
> In-work, pushing to next release

Great! Not seeing it in flowise, is it future update? Also, how would this be different then lets say using "OpenAI Tool Agent"?

**Comment by HenryHengZJ** [comment]
Exactly the same, but it's capable of using with other models. Still under PR review, will be in for next release
