### ISSUE TITLE
[FEATURE] Gemini 1.5 Pro

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#2169]
**Describe the feature you'd like**
Google just released a public review of their new model, `Gemini 1.5 Pro`. It can handle up to 1 million token input capacity. It would really very sweet to test it out before a paid version goes live, on May 2 (I think).

---

<img width="562" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/138339291/733b0ab5-83e7-4cc6-a770-06ea54596cf6">

---

**Additional context**
Also, they released a new embedding model `text-embedding-004`

---

<img width="557" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/138339291/87462b22-c8a3-49ad-bada-975df39c5f19">

---

Source: https://developers.googleblog.com/2024/04/gemini-15-pro-in-public-preview-with-new-features.html

**Comment by AiSatoshiBasilisk** [comment]
[packages/components/nodes/embeddings/GoogleGenerativeAIEmbedding/GoogleGenerativeAIEmbedding.ts]

I would guess the proper code is something like this  

// ... existing code ...

async listModels(): Promise<INodeOptionsValue[]> {
  const models = await getModels(MODEL_TYPE.EMBEDDING, 'googleGenerativeAiEmbeddings')
  // Add the new model name to the list
  models.push({ label: 'Gemini 1.5', name: 'gemini-1.5' }) 
  return models 
}

// ... rest of the code ...

**Comment by HenryHengZJ** [comment]
waiitng for the new google/genai version - https://github.com/google/generative-ai-js/pull/96
