### ISSUE TITLE
[BUG] Docker build local 404 `faiss-node`

### ISSUE THREAD

**Issue by TechWithRay** [FlowiseAI/Flowise#217]
**Describe the bug**
`docker build`,  new image failed.

**To Reproduce**

1. `git clone https://github.com/FlowiseAI/Flowise.git`
2. `cd Flowise`
3. `docker build -t flowise --no-cache .`

**Expected behavior**
Error 

```
prebuild-install info begin Prebuild-install version 7.1.1
prebuild-install info looking for local prebuild @ prebuilds/faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/33888e-faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz
prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/download/v0.2.0/faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz
prebuild-install http 404 https://github.com/ewfian/faiss-node/releases/download/v0.2.0/faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz
prebuild-install warn install No prebuilt binaries found (target=8 runtime=napi arch=x64 libc=musl platform=linux)
sh: cmake-js: not found
 faiss-node@0.2.0 build
```

**Setup**

-   OS: `Linux`
-   Browser: `chrome`

**Additional context**
`https://github.com/ewfian/faiss-node/releases/download/v0.2.0/faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz` , there is no `faiss-node-v0.2.0-napi-v8-linuxmusl-x64.tar.gz`.

**Comment by HenryHengZJ** [comment]
temporarily reverted Faiss changes. Should be working fine now.

Leaving this issue open until we have a fix on `faiss-node`

**Comment by ewfian** [comment]
@HenryHengZJ It has been fixed on faiss-node side and the new version was released.

**Comment by HenryHengZJ** [comment]
@ewfian thank you for the fix! 

#257 is now added back and merged 💯
