### ISSUE TITLE
Easy addition for new Gemini 1.5

### ISSUE THREAD

**Issue by AiSatoshiBasilisk** [FlowiseAI/Flowise#2175]
The Google Chat Wrapper should be able to fetch the model list from google to include your finetuned models and gemini 1.5 according to the updated google documentation. If I could code I would do it but I am running on gemini 1.0 still and its limiting my capacity

 [packages/components/nodes/embeddings/GoogleGenerativeAIEmbedding/GoogleGenerativeAIEmbedding.ts]

I would guess the proper code is something like this  

// ... existing code ...

async listModels(): Promise<INodeOptionsValue[]> {
  const models = await getModels(MODEL_TYPE.EMBEDDING, 'googleGenerativeAiEmbeddings')
  // Add the new model name to the list
  models.push({ label: 'Gemini 1.5', name: 'gemini-1.5' }) 
  return models 
}

// ... rest of the code ...

**Comment by HenryHengZJ** [comment]
yes! you can do it this way, or have your own `models.json` file - https://docs.flowiseai.com/configuration/environment-variables#models

**Comment by HenryHengZJ** [comment]
Gemini 1.5 is now available through this [PR](https://github.com/FlowiseAI/Flowise/pull/2180)
