### ISSUE TITLE
[BUG] Zapier Integration no longer accepts/recognizes API Keys

### ISSUE THREAD

**Issue by Compg** [FlowiseAI/Flowise#2177]
**Describe the bug**

Zapier connection (Flowise Ai CLI API@1.0.0) no longer recognizes provided API key. Tried multiple valid keys and connector error says no key was provided

![image](https://github.com/FlowiseAI/Flowise/assets/134229312/5c515542-4ab1-41eb-b6c1-504f1d7a6eb2)

**To Reproduce**

1. Deploy Flowise on AWS following official guide
2. Setup custom domain and enable SSL
3. Generate Flowise API key
4. Go to Zapier "My Apps" and create Flowise connection
5. Enter domain and API Key
6. See error

**Expected behavior**
Flowise connected to Zapier

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation - Docker on EC2
-   Flowise Version 1.6.5
-   OS: Amazon Linux 2
-   Browser: Edge

**Additional context**

Confirmed key and endpoints do work manually. Able to invoke a flow using application-provided python snippet

**Comment by marius-smg** [comment]
I encounter the same Problem

**Comment by florianchevallier** [comment]
Same error :(

**Comment by senturiwebdesign** [comment]
Same!

**Comment by 4rr0wx** [comment]
I have the same problem

**Comment by HenryHengZJ** [comment]
should be resolved in v2.0!

**Comment by neryabCommitted** [comment]
I have the same problem (running version 2.1.1)
