### ISSUE TITLE
[BUG] Authorization failed when connecting to hosted Chroma DB (Error: AuthorizationError)

### ISSUE THREAD

**Issue by mike4lyf** [FlowiseAI/Flowise#2185]
**Describe the bug**
Unable to connect to hosted ChromaDB, error: AuthorizationError

Need clarification on how to connect to a hosted ChromaDB. I have already instantiated a ChromaDB with an existing collection, i defined the header authentication as X-Chroma-Token: <token>. 

[ChromaDB connection pattern ](https://docs.trychroma.com/usage-guide) is using Static API token:
```
# instantiate a http Chroma client
headers = {'X-Chroma-Token': CHROMA_API_KEY)}
# setup client to connect to  chroma server
client = chromadb.HttpClient(host='123.123.123.123', port=8000, headers=headers)
```

**To Reproduce**

1. In Flowise, add Chroma Node
2. Add Chroma URL:  http://123.123.123.123:8000
3. Connect Credential: CREDENTIAL NAME: X-Chroma-Token, Chroma Api Key: CHROMA_API_KEY
4. Run-> error: AuthorizationError

**Expected behavior**
Maybe we can have a clear way of defining the header as part of Chroma's authentication? 

Expect the Chroma node matches Chroma's terminology closely, e.g. change Chroma Api Key (in Connect Credential hover tool-tip) to be X-Chroma-Token: <token> or Authorization: Bearer <token>

**Could we define what the headers are?**

https://docs.trychroma.com/usage-guide#authentication

**Setup**

-   Installation [e.g. docker, `npx flowise start`, ]
-   Flowise Version 1.6.4
-   OS: Windows
-   Browser: Chrome/Firefox

**Additional context**

**Comment by HenryHengZJ** [comment]
As stated from Chroma [docs](https://docs.trychroma.com/usage-guide#static-api-token-authentication), API Key can be added as Bearer Token like so `Authorization: Bearer test-token`

Which was added in this [line](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/vectorstores/Chroma/core.ts#L33)
