### ISSUE TITLE
[BUG] Successfully Upserted and no file uploaded in the pinecone DB

### ISSUE THREAD

**Issue by TarekMahran** [FlowiseAI/Flowise#2193]
**Describe the bug**
Trying to use Curl to add files to the csv document loader and always got Successfully upserted even no vectors inserted in pinecone database.

**To Reproduce**

curl https://flowai.xxxxxx.net/api/v1/vector/upsert/82cac352-4608-1111-b669-50f7909ac31b \ -X POST \ -F "files=@D:/DOCS/LLM Training/Draw.io.csv" \ -F "pineconeApiKey=xxxxx-6381-405b-b68d-xxxxxxxxx" \ -F "pineconeIndex=testai" \ -F "pineconeNamespace=Default" \

**Comment by HenryHengZJ** [comment]
works for me:

1.) Have a flow:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/48c8a0c8-025d-4fcf-82c1-4c8b8ac71d6b)

2.) Make POST HTTP request to `vector/upsert` API:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/5b85d5e2-116d-49ea-9584-f946cd33e01d)

3.) Verify on Pinecone:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/3e9b6b71-fb0d-4598-90a6-a7775b00ab8e)

**Comment by TarekMahran** [comment]
Hi @HenryHengZJ, 

Thanks for your support. Yes, It works fine when using postman however it doesn't work when using CURL command. My usecase id to call the embedding api through CURL command only.

Thanks in advance and waiting for your feedback.

Regards,
Tarek
