### ISSUE TITLE
[BUG]There are no options in the model names in all models, and they are not allowed to be entered.

### ISSUE THREAD

**Issue by musuiot** [FlowiseAI/Flowise#2197]
**Describe the bug**
In the latest version of the model, there is no option in the model name, and it is not allowed to be entered.
![000](https://github.com/FlowiseAI/Flowise/assets/58774718/5b167dca-fd05-4f26-987e-3c8846486aab)

**Comment by qhdrl12** [comment]
it's the same for me when using OpenAI

**Comment by HenryHengZJ** [comment]
oh strange, in the latest version we pull the model list from this file [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/models.json)

There might be some issues to access the file, can you try deleting the old node, and create from scratch? If not you can create a models.json file and specify the env variable - https://docs.flowiseai.com/configuration/environment-variables#models

**Comment by HenryHengZJ** [comment]
also please share how are you running Flowise. There might be company proxy that blocks the access to fetch the file from Github

**Comment by musuiot** [comment]
In order to test, I reinstalled the win11 system and all related environments, but the situation is still the same. This is a locally running program and should not be associated with the network. In particular this should be designed as a local configuration file. I strongly hope this bug can be resolved soon.

**Comment by musuiot** [comment]
I changed the proxy and tested it, and the options can be displayed. But the previous version did not have this problem. It's hard for me to understand why this parameter should be designed to be so closely related to the network? If so, using flowise will be very limited.

**Comment by liyiyiya** [comment]
> I changed the proxy and tested it, and the options can be displayed. But the previous version did not have this problem. It's hard for me to understand why this parameter should be designed to be so closely related to the network? If so, using flowise will be very limited.
Hello, I'm having the same problem, how did you modify the proxy?

**Comment by HenryHengZJ** [comment]
created a PR now to fallback to fetch the local `models.json` file if the link is not accessible - https://github.com/FlowiseAI/FlowiseCloud/pull/397
