### ISSUE TITLE
[BUG] Postgres Vector Store inverted similarity calculation

### ISSUE THREAD

**Issue by vinibs** [FlowiseAI/Flowise#2198]
**Describe the bug**
When using Postgres as the Vector Store for a flow and querying it with a specified minimum score, it's not returning anything. 
Searching the code, I noticed that the Postgres node calculates the distance between the vectors and returns them sorted ascending, but the VectorStore to Document node expects the number to be a similarity value, not the distance, resulting in it discarding the most relevant results for my query.
I'm making a local change to try changing this value returned by Postgres to be "1 - distance", which seems to be enough to fix this situation. 
If it doesn't bring other side effects, I can also make a PR for this little change.

**To Reproduce**

1. Create a flow
2. Configure a Postgres database server
3. Add the (Vector Store) Postgres node, with output set as "Postgres Vector Store" and set the connection up
4. Add the VectorStore to Document node and set its input as being the Postgres node's output
5. Pass "{{question}}" as the Query attribute of the VectorStore to Document node
6. Add a simple custom function as an ending node and set the VectorStore to Document node's output as an input variable for the function
7. Make the custom function only return the provided variable (for debugging purposes)
8. Use the Upsert API to insert data into the vector store for at least two different messages (questions)
9. Ask the chat one of the questions that were inserted into the Vector Store

**Expected behavior**
The output should bring the stored vectors ordered by the most similar to the question, but instead it brings them ordered by the less similar. If a minimum score is passed to the VectorStore to Document node, for the exact same question, no result is brought from the query. 

**Screenshots**
The results when querying without setting the minimum score (it brings all entries):
![Screenshot 2024-04-16 at 11 30 55](https://github.com/FlowiseAI/Flowise/assets/20691391/4254587b-c8d0-4954-b7a2-6ae37c18f978)

The results when querying with a minimum score of 80% (it doesn't bring any data):
![Screenshot 2024-04-16 at 11 31 28](https://github.com/FlowiseAI/Flowise/assets/20691391/0eca872b-7701-4d5f-9c23-8b5e50237987)

The VectorStore documents' log with the calculated similarity for this case (bringing the exact same question with a score of `0` while bringing non-related questions with greater scores - actually, greater distances):
![Screenshot 2024-04-16 at 11 33 30](https://github.com/FlowiseAI/Flowise/assets/20691391/f48ea675-618a-459a-959c-91dd22374aed)

**Flow**
[sql-test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/14998837/sql-test.Chatflow.json)

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]: Docker
-   Flowise Version [e.g. 1.2.11]: 1.6.2
-   OS: [e.g. macOS, Windows, Linux]: macOS
-   Browser [e.g. chrome, safari]: Chrome

**Additional context**
As mentioned before, it seems the Postgres node is calculating the `distance` instead of the `similarity` when querying the vector store. I'm currently testing changing this calculation to bringing "1 - distance" as the similarity score (or changing it directly on the query calculation), but I'm not aware about possible side effects this could cause, since I'm working with Flowise for just 4 days and am not very familiar to its resources.
I'd like to confirm this issue before opening a pull request to fix it.

**Comment by HenryHengZJ** [comment]
The postgres vs in Flowise is using implementation from [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/vectorstores/typeorm.ts) and yes its using `distance`

There's another way to do this via [here](https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/vectorstores/pgvector.ts), and this allow you to do `cosine`, `innerProduct` or `euclidean`

We can change the implementation to use the latter one if that solve the issue

**Comment by PolygonHealth** [comment]
To add to this, calculating cosine similarity on the exact same embedding doesn't give a score of 1, but a score close to 0.5

**Comment by Weilin37** [comment]
To add to this, calculating cosine similarity on the exact same vector does not give a score of 1, but close to a score of 0.5

**Comment by PolygonHealth** [comment]
Is there a follow up on this?

**Comment by Astriel** [comment]
I would be interested to also be able to select the metric to fetch vectors from the pgvector database.

**Comment by HenryHengZJ** [comment]
Possible now with this PR: https://github.com/FlowiseAI/Flowise/pull/3367
