### ISSUE TITLE
⚒️[FEATURE] Support line breaks in UI User Chat 

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#220]
**Describe the feature you'd like**
Support line breaks in user message textbox

Expected:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/94c7e3ce-a287-4d72-a173-85cf6f6a771c)

Currently:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/bf672f44-db66-403a-878b-76982d86dae2)

**Comment by govind-kumarr** [comment]
@HenryHengZJ  can you assign this to me?

**Comment by govind-kumarr** [comment]
@HenryHengZJ  on which key press should take the line break?

**Comment by HenryHengZJ** [comment]
@govind-kumarr we don't need a key press to line break, its just when copy pasting a piece of text with line breaks, it will be able to show it in textinput similar to chatgpt interface

**Comment by govind-kumarr** [comment]
@HenryHengZJ  done with that you can merge it now

**Comment by HenryHengZJ** [comment]
closing as - https://github.com/FlowiseAI/Flowise/pull/280 merged thanks @govind-kumarr !
