### ISSUE TITLE
[BUG] vectorsService.upsertVector Not implemented (Postgres Record Manager)

### ISSUE THREAD

**Issue by enriquesb** [FlowiseAI/Flowise#2200]
When attempting to upsert a new document using a Postgres Record Manager, I encountered the following error: "Error: vectorsService.upsertVector - Error: Error: Not implemented."

**To Reproduce**

1. Connect a Postgres Record Manager element with the "Full" option selected for the "Clean up" parameter, to a Postgres vector store.
2. Upsert the content of a .docx file using Recursive Character text splitter.
3. Change/upload another file in the Docx File loader.
4. Save the chatflow and attempt to upsert the new document.

**Expected behavior**
I expected the content of the first document to be erased from the database, followed by the upsertion of the new document's content into the database.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/29783441/55104fd0-5f33-41d3-a87f-4916deca256c)

**Flow**
[postgres record manager upsert error Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15005525/postgres.record.manager.upsert.error.Chatflow.json)

**Comment by HenryHengZJ** [comment]
is it just postgres record manager?

**Comment by enriquesb** [comment]
I only use postgres databases. So I can't speak about the other record managers.

**Comment by 17lxve** [comment]
> is it just postgres record manager?

I've had the same issue with Postgres, In-memory vector store, and Pinecone. It seems like the embeddings just fail when i load more than a few documents in.

**Comment by jimmy8646** [comment]
I also encountered the same issue. I tried to clear the database, and encountered the same error message when performing an Upsert.

**Comment by jconey87** [comment]
Im getting upsert failed on everything i try with vector db's. 
![image](https://github.com/FlowiseAI/Flowise/assets/45073193/669761cc-fdea-4da4-a9e0-730eb4fc4a75)

**Comment by kyuumeitai** [comment]
> Im getting upsert failed on everything i try with vector db's. ![image](https://private-user-images.githubusercontent.com/45073193/330103242-669761cc-fdea-4da4-a9e0-730eb4fc4a75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTQ4ODIsIm5iZiI6MTcxNTYxNDU4MiwicGF0aCI6Ii80NTA3MzE5My8zMzAxMDMyNDItNjY5NzYxY2MtZmRlYS00ZGE0LWE5ZTAtNzMwZWI0ZmM0YTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDE1MzYyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTQzYWY5MzdkZGM2NDE3NmVlMDZlNWQzYzRkY2Y4YmQ0ZDFiYjZlY2RmMTQzOTMwZWZkZDEzNGExZDZmNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tb_L3vHfW5eyTF1XZ2jDOAUNYEeQcU4jBsJ5F4GKkt0)

Hi there, I think that your error is something else: your error says that "fetch failed". Is ollama up and running?

**Comment by kyuumeitai** [comment]
I have this error as well. It happens to me if I use Postgres Record Manager but also if I use MySQL Record Manager.

The error logs are this:

```2024-05-14 20:32:45 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/52210d19-0993-4960-b05f-297345d28420
2024-05-14 20:32:45 [ERROR]: Error: Not implemented.
Error: Error: Not implemented.
    at Postgres_VectorStores.upsert (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Postgres/Postgres.js:82:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:389:37)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:117:32)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)
2024-05-14 20:32:45 [ERROR]: [server]: Error: Error: Error: Not implemented.
Error: Error: Error: Not implemented.
    at buildFlow (/usr/local/lib/node_modules/flowise/dist/utils/index.js:453:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async upsertVector (/usr/local/lib/node_modules/flowise/dist/utils/upsertVector.js:117:32)
    at async Object.upsertVectorMiddleware (/usr/local/lib/node_modules/flowise/dist/services/vectors/index.js:9:16)
    at async createInternalUpsert (/usr/local/lib/node_modules/flowise/dist/controllers/vectors/index.js:28:29)```
    
It's the same if I use Mysql or Postgres Record Manager. The only way that I can use it is to set the cleanup to "none"

**Comment by pamperherself** [comment]
I encounter the same Error with weaviate

![image](https://github.com/FlowiseAI/Flowise/assets/152131382/1d748a58-2082-49a1-8dd5-a977c4e779dd)

**Comment by oiqm4T** [comment]
Error still occurring when using PG record manager with PG vector. 
Error: Error: Not implemented.
    at Postgres_VectorStores.upsert

**Comment by sergiozaninotti** [comment]
same error here :(

**Comment by NoobOfAll** [comment]
The issue is **resolved** when the `Cleanup` is set to `Full` in the `Additional Parameters` of the `Postgres Record manager`

![FlowiseAI_PostgresqlRecordManager](https://github.com/user-attachments/assets/49562680-7760-4bc9-aa47-2d3a310e3bdb)

I tried with `Incremental` and it gave the same error as above.

p.s. I have added the extension `vector` for both `vector store` and the `Postgres Record Manager`

**Comment by enriquesb** [comment]
I managed to get my chatflow working by following a YouTube video by Leon van Zyl. I connected the record manager block to Supabase, which resolved the issue. It seems that the error I encountered earlier was due to incorrect configuration of my local PostgreSQL database.

I apologize for any confusion caused.

**Comment by jofranjp** [comment]
My setup was postgres as Vector Store and Record Manager, and I got the error mentioned by the author of this thread. This only happened if the Cleanup option is either set to incremental or Full. I was not able to fix this.

But when I change my Vector Store to Qdrant and still the Record Manager is Postgres, everything working fine. The cleanup setting of the Record Manager is still set Incremental.

**Comment by jofranjp** [comment]
Great job Henry. How can we get the update? Is that part of the Flowise release update?

**Comment by orsharon7** [comment]
I am experiencing the same issue:

> Error: vectorsService.upsertVector - Error: Error: No vectors provided

I tried removing the connection and restarting the service, however it didnt solve it. it happens when I try to upsert another PDF file..

Here is my architecture:

![Screenshot 2024-09-29 at 11 19 17](https://github.com/user-attachments/assets/92af3ac4-294c-46bb-a78a-2611ed520897)
