### ISSUE TITLE
FLOWISE TEMPLATES APPEAR OPAQUE WHICH CAUSE CHATBOT INCOHERENT ANSWERS.

### ISSUE THREAD

**Issue by SZ4ME** [FlowiseAI/Flowise#2208]
**Describe the bug** Flowise templates appear opaque causing incoherent answers.

**To Reproduce**
![FLOWISE](https://github.com/FlowiseAI/Flowise/assets/150427774/f0a36762-ae7d-4c22-b5c3-1764944f123a)

**Expected behavior**
The chatbot has to produce coherent answers, but because of the opaqueness in the template it doesnt.

**Screenshots**
Have produced screenshots

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**
After setting up the chatbot, and when you ask questions it keeps repeating the same answer i.e "How can I assit you today?" It never answers anything other than that. Before this happened, it answered accordingly. Please help.

**Comment by HenryHengZJ** [comment]
This is a template, click the Use Template at the top right to edit in a new canvas

**Comment by SZ4ME** [comment]
Thanks Henry. Yes, it is, and when I use it, my chatbot still produces incoherent answers. Infact all of the marketplace templates appear opaque like that, yet before, as in like last year, 2023, when i started using Flowise, none of them were opaque like that. I would simply select a template, edit it and it would work just fine. But now, i select a template, try to edit it, and instead of answering as expected the chatbot keeps asking the question "how can I assist you" on every question I ask it. Every node is connected quite well in the chains.
