### ISSUE TITLE
[FEATURE] OpenAI Assistant API `V2` Release

### ISSUE THREAD

**Issue by AsharibAli** [FlowiseAI/Flowise#2217]
**OpenAI has recently released version 2 of its Assistant API. The previous version, V1, will be deprecated at the end of 2024. The new V2 version comes with many new features and exciting updates. It is highly recommended that Flowise implements this new version. By doing so, consumers will be able to take advantage of the latest OpenAI Assistant API features via the Flowise.**

_New in the Assistants API: retrievals for up to 10,000 files, token controls, JSON mode, tool choice, and more._

**Additional context**
The official details about the V2 Release of OpenAI Assistant can be accessed here:
[What's new in v2? ](https://platform.openai.com/docs/assistants/whats-new)

The official Implementation aka "Migration Guide" of OpenAI Assistants V2:
[Migration Guide](https://platform.openai.com/docs/assistants/migration)

**Comment by Matesanz** [comment]
Could you please show how to use Flowise to allow Json Mode with OpenAI models? Than you in advance
