### ISSUE TITLE
Status: 500 Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

### ISSUE THREAD

**Issue by CoreyH** [FlowiseAI/Flowise#2218]
Hey all - I've never seen this before. Everything was fine and then I get this all of a sudden. Nothing changed that I'm aware of. The last deploy was a week ago and pulls from Docker version 1.6.5. I'm running on Azure App Service and have restarted everything fresh as best as I can. I even switched from Mysql to Postgres believing that might help. But no luck. 

Status: 500 Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

atomic_vishnu on Discord said this:

> yes dude, i am also facing the same issues with that
> try to see the console logs, you will be able to see that there will be a problem over the database.

![image](https://github.com/FlowiseAI/Flowise/assets/213602/56ea49ee-2c87-4f63-a4a6-6a8d4486fb56)

-   Installation [Azure Web App + Postgresql]
-   Flowise Version 1.6.5

**Comment by CoreyH** [comment]
I solved my issue. I'm using mysql so I had to base64 encode the DigiCertGlobalRootCA.crt.pem file and add that to DATABASE_SSL_KEY_BASE64 as an environment variable in Azure. 

the confusing part is I have no idea why/how this worked previously but stopped mysteriously.

**Comment by kei49** [comment]
I faced the same issue on the deployed app on Azure and found that it was fixed by DATABASE_SSL as "true" without setting DATABASE_SSL_KEY_BASE64. It works [in the condition](https://github.com/FlowiseAI/Flowise/blob/363d1bfc44cbcfea2d119498eb0f19673bffe4ed/packages/server/src/DataSource.ts#L106)
