### ISSUE TITLE
⚒️[FEATURE] Confluence Loader Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#222]
## Describe the feature you'd like
Confluence Loader Integration
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/confluence

## ✅Tasks
- [ ] Add Confluence DocumentLoader node

## 🎯Acceptance Criteria
- [ ] Confluence DocumentLoader node should be able to load data from Confluence

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Github Loader](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Github/Github.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by neerajkrbansal1996** [comment]
Hi @HenryHengZJ ,

i would love to take this ticket and contribute!

**Comment by HenryHengZJ** [comment]
sure! assigned :)

**Comment by mrkhachaturov** [comment]
@neerajkrbansal1996 
Trying to use with confluence server, i am getting Request failed with status code 429 error. 

![image](https://github.com/FlowiseAI/Flowise/assets/105451445/ea6636b4-6a39-4547-9b81-2715d330532a)
![image](https://github.com/FlowiseAI/Flowise/assets/105451445/774e1d66-0b4e-41ab-a793-d33a6ec8a250)

**Comment by HenryHengZJ** [comment]
could it be OpenAI API key or pinecone API key expired? try creating a new key
