### ISSUE TITLE
Retrieving chat messages via API 'chatmessage' path not working [BUG]

### ISSUE THREAD

**Issue by xolabsro** [FlowiseAI/Flowise#2224]
**Describe the bug**
While in FlowiseAI web ui, it works to see the history of messages `Cogwheel > View Messages`, trying to retrieve the history of messages for particular chatflowid, always returns 401 error. (https://docs.flowiseai.com/integrations/langchain/memory/threads#message-api)

**To Reproduce**

1. In Postman, configure the url of the chatmessage api: https://url/api/v1/chatmessage/chatflowid
2. The above chatflowid is valid, because I am using it with predictions, via api
3. Set Postman to send a 'GET' query to the api url
4. 401 is always returned, even if you use authentification or not.

**Expected behavior**
FlowiseAi to return the history of messages via api, just like when using the UI.
Maybe I am missing something?

**Comment by HenryHengZJ** [comment]
You'll have to use Basic Authentication for Message API - https://docs.flowiseai.com/using-flowise/api#authentication-2
