### ISSUE TITLE
[BUG] Pinecone API-key is incorrectly cached.

### ISSUE THREAD

**Issue by mcpaddy** [FlowiseAI/Flowise#2235]
**Problem**

When switching between Pinecone Indexes in different projects a 404 error is returned by Pinecone. Even thou the API key has been updated. It seems that Flowise might be caching the API key and not using the new one. This does not always happen; I can reproduce it about 40% of the time in my environment. 

I have another user who saw it every time in their environment, which was on Render. The only way around it was to redeploy.

We know the issue is inside Flowise as we tested the API keys and indexes using `curl`. 

We also set the key as an invalid value in Flowise, and the error message should be 401; it was not.

**To Reproduce**
Please use the Flow I have attached

1. Create two projects in Pinecone
2. Create an index in each project 
3. Set the Pinecone _Connection Credential_ and _Pinecone Index_ to be the details for the first project
4. Click save
4. Run the Flow, it runs successfully
5. Update the Pinecone _Connection Credential_ and _Pinecone Index_ to be from the second project
6. Click save
7. Run the flow. It fails with a 404 error

**Expected Behaviour**

When switching to a different Index and Connect Credential, it uses them and not the old one. 

**Flow**
[new Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15065891/new.Chatflow.json)

The CSV file for the Flow:

```
"Question","Answer"
"Is Pinecone the best database?","Yes, it's the best."
```

**Setup**

-   Installation: `npx flowise start`
-   Flowise Version: 1.6.4 
-   OS: MacOS 14.4.1
-   Browser: Chrome 124.0.6367.61
 
**Additional context**
I work for Pinecone, please let me know if you need more details.

**Comment by HenryHengZJ** [comment]
@mcpaddy hey sorry for late reply. I found a strange fix by adding a `describeIndex`, can you try this PR branch - https://github.com/FlowiseAI/Flowise/pull/2369 and see if that works?

**Comment by HenryHengZJ** [comment]
I was able to replicate from the steps, 404 when we change the credentials, but when I do console log the api key, I can see the new updated API key. And strangely by adding a `describeIndex` it works, so if you can verify that'd be great

**Comment by mahzy** [comment]
I have the same issue on my end

**Comment by mcpaddy** [comment]
Hello all,

I have reproduced this outside of Flowise, the issue is with our Node.js drive. I will work with the team to get this fixed and will let you know when it's in a release.

**Comment by fulgorastral** [comment]
I have the same issue here. Very annoying. Will try out the fix but I don't know code. Hopefully I'll be able to pull through

**Comment by fulgorastral** [comment]
I have the same problem here. @HenryHengZJ how can this "fix by adding a describeIndex" be done? Is it possible to be done without knowning code?

**Comment by HenryHengZJ** [comment]
@mcpaddy verified that 2.2.2 now works. Updated on this PR - https://github.com/FlowiseAI/Flowise/pull/2681, also verified its not working
