### ISSUE TITLE
⚒️[FEATURE] Subtitles Loader Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#224]
## Describe the feature you'd like
Subtitles Loader Integration
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/file_loaders/subtitles

## ✅Tasks
- [ ] Add Subtitles Loader node

## 🎯Acceptance Criteria
- [ ] Subtitles Loader node should be able to load data from subtitle file

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Text Loader](https://github.com/FlowiseAI/Flowise/tree/main/packages/components/nodes/documentloaders/Text)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by govind-kumarr** [comment]
@HenryHengZJ  can you assign this to me?

**Comment by HenryHengZJ** [comment]
#324 merged, closing this
