### ISSUE TITLE
⚒️[FEATURE] Figma Loader Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#225]
## Describe the feature you'd like
Figma Loader Integration
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/figma

## ✅Tasks
- [ ] Add Figma Loader node

## 🎯Acceptance Criteria
- [ ] Figma Loader node should be able to load data from Figma

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Github Loader](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Github/Github.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by Pravesh-mansharamani** [comment]
@HenryHengZJ Can you assign me this issue
