### ISSUE TITLE
[BUG] Qdrant didn't follow metadata search filter

### ISSUE THREAD

**Issue by davide445** [FlowiseAI/Flowise#2253]
**Describe the bug**
Upserting two txt documents marked by a different "source" metadata (following [this ](https://docs.flowiseai.com/use-cases/multiple-documents-qna) approach), and setting in Qdrant filtering parameters the correct structure as defined [here](https://docs.flowiseai.com/integrations/langchain/vector-stores/qdrant#filtering), in any case only a single document information is retrieved during the chat, always the same document. Tested both with Claude and GPT, checked and Qdrant has correctly saved the data with their metadata.

**To Reproduce**

1. Use attached flow, change the system prompt in English
2. Use attached txt (apologize they are in Italian, but doesen't matter with the multilanguage LLMs like Claude)
3. Ask about the content of the document, will be always answered about the Neanderthal even if in the Qdrant filter is set habilis as source

**Expected behavior**
Since the source is set "habilis" I expect will answer questions regarding the habilis document.

**Screenshots**
Ask anything

**Flow**
Attached

**Setup**

-   Installation npx flowise start
-   Flowise Version 1.6.5
-   OS: linux
-   Browser Firefox
-   Qdrant 1.9.0 image running locally using 
`docker run -p 6333:6333 -p 6334:6334     -v $(pwd)/qdrant_storage:/qdrant/storage:z     qdrant/qdrant`

**Additional context**
[Habilis.txt](https://github.com/FlowiseAI/Flowise/files/15105422/Habilis.txt)
[Neanderthal.txt](https://github.com/FlowiseAI/Flowise/files/15105426/Neanderthal.txt)
[Two document Qdrant test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15105428/Two.document.Qdrant.test.Chatflow.json)

**Comment by HenryHengZJ** [comment]
@davide445 thanks for the bug! PR to fix that - https://github.com/FlowiseAI/Flowise/pull/2285

Reason being the filter was not passed to the VectorStore To Document node
