### ISSUE TITLE
[BUG] Status: 500 Error: assistantsService.createAssistant

### ISSUE THREAD

**Issue by yunho0130** [FlowiseAI/Flowise#2254]
**Describe the bug**

Status: 500
Error: assistantsService.createAssistant - Error creating new assistant - 400 Unknown parameter: 'file_ids'.

**To Reproduce**

After deploy on Railway environment (Cloud) & Installation on Macbook Pro M1 14 (Local) 

When I added the api key of OpenAI I got the 400 error message. 
 
**Expected behavior**
I can use the OpenAI api on FlowiseAI. 

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/7574765/772bb7a1-5ce8-457a-8761-ec050c53c61e)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation docker on railway, npx flowise start on macbook
-   Flowise Version Latest
-   OS: macOS 
-   Browser [Chrome] 

**Additional context**

**Comment by HenryHengZJ** [comment]
We've updated Assistant API to V2 - https://github.com/FlowiseAI/Flowise/pull/2258

Can you try again?

**Comment by HenryHengZJ** [comment]
Should be resolved in v1.6.6
