### ISSUE TITLE
[BUG] Upstash memory key TTL dosen't change even though Session Timeouts is set in the Upstash node

### ISSUE THREAD

**Issue by alvinho917** [FlowiseAI/Flowise#2255]
**Describe the bug**
I set the session timeouts in the Upstash node to be 120 and I also send "sessionTTL": 120 as overrideConfig while sending request. However, in Upstash console the TTL of the key is not changed and is still Forever

**To Reproduce**

1. Create Upstash Redis-Backed Chat Memory node
2. Click on 'Additional Parameters' and input value for the Session Timeouts
3. Connect Upstash node to conversation chain
4. Send API request and add "sessionTTL": 120 as overrideConfig 
5. Open Upstash console, find the key and the TTL is still forever
6. Wait for 120 seconds and the key is still not deleted

**Expected behavior**
The TTL of the key should be the same as the Session Timeouts set in the Upstash node. The key automatically delete itself after the timeout.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/168067097/2911357f-fed1-47e8-a520-52fde1508256)
![image](https://github.com/FlowiseAI/Flowise/assets/168067097/447f0cd1-65d3-4f74-a914-9bf4482f09f2)
![image](https://github.com/FlowiseAI/Flowise/assets/168067097/91da35b2-aeca-4e6f-8846-25c188d64d45)

**Flow**
[Test Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15106046/Test.Chatflow.json)

**Additional context**
I am trying to set the TTL because I find out that if an user saved too many memory, it makes the request exceed the maximum token value of the AI model. So I wanna ask is setting TTL for the keys the best way to solve this problem?

**Comment by HenryHengZJ** [comment]
Fixed: https://github.com/FlowiseAI/Flowise/pull/2871
