### ISSUE TITLE
⚒️[FEATURE] LatexTextSplitter Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#226]
## Describe the feature you'd like
LatexTextSplitter Integration
Docs: https://js.langchain.com/docs/modules/indexes/text_splitters/examples/latex

## ✅Tasks
- [ ] Add LatexTextSplitter node

## 🎯Acceptance Criteria
- [ ] LatexTextSplitter node should be able to load documents in Latex format, and split content into documents based on the Latex syntax

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Recursive Text Splitter](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/textsplitters/RecursiveCharacterTextSplitter/RecursiveCharacterTextSplitter.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by Pravesh-mansharamani** [comment]
@HenryHengZJ Can you assign me the issue please.
