### ISSUE TITLE
HTTP error when using Mistral models

### ISSUE THREAD

**Issue by frankwengerek** [FlowiseAI/Flowise#2267]
When using Mistral Models a HTTP error (422) occured:
![Bildschirmfoto 2024-04-26 um 10 49 56](https://github.com/FlowiseAI/Flowise/assets/130894905/7e1d0922-956c-4185-8fc0-f53a3468dc23)

Langsmith:
https://smith.langchain.com/public/24530dd0-34bd-412e-a797-b8dcc5469c5a/r

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/Flowise/pull/2281

There was a bug in the older version, updated with the above PR. Will push a new release shortly

**Comment by HenryHengZJ** [comment]
should be resolved now, if you try pulling the latest
