### ISSUE TITLE
[BUG] Supabase

### ISSUE THREAD

**Issue by jbainpro** [FlowiseAI/Flowise#227]
Running into this error after setting up Flowise with Supabase.

**Bug**
Error searching for documents: 42883 operator does not exist: extensions.vector <=> extensions.vector null

**To Reproduce**

1. Go to 'flowise marketplace and create a new Conversational Retrieval QA Chain'.
2. Replace Pinecone with Supabase.
3. Fill out details to upsert.
4. Document is upserted but returns the above error.

**Expected behavior**
It should reply with the info in the doc..

**Screenshots**
![Screen Shot 2023-05-30 at 04 48 50](https://github.com/FlowiseAI/Flowise/assets/60293260/373ec90b-d5d1-496c-b0a0-583a560f85ad)

**Setup**
-   OS: [Linux / Docker
-   Browser [chrome]

**Additional context**
The same error appears when trying to load index from Supabase.

**Comment by HenryHengZJ** [comment]
here - https://github.com/FlowiseAI/Flowise/issues/169

**Comment by jbainpro** [comment]
After hours of digging I was able to solve the issue with a fresh install. This time there are more functions available compared to the last installation so I guess the issue was with regards to the missing functions.
