### ISSUE TITLE
⚒️[FEATURE] Support for MySQL for SQLDBChain

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#228]
## Describe the feature you'd like
Add Support for MySQL in SQLDBChain
Docs: https://js.langchain.com/docs/modules/chains/other_chains/sql

## ✅Tasks
- [ ] Add MySQL support in existing SQLDBChain codebase

## 🎯Acceptance Criteria
- [ ] SQLDBChain can supports sqlite and mysql

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [SQLDBChain](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/SqlDatabaseChain/SqlDatabaseChain.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by lpongetti** [comment]
#761
