### ISSUE TITLE
Rate_Limit_Bug

### ISSUE THREAD

**Issue by amansoniamazatic** [FlowiseAI/Flowise#2280]
When I go to {{hosted_url}}/api/v1/ip I get this:

{ "statusCode": 412, "success": false, "message": "Error: ipController.configureProxyNrInHostEnv - ip not provided!", "stack": {} }

In the chabot, instead of the rate limit message I get "Oops! There seems to be an error. Please try again."

Note: This error i am getting in latest version but its working fine for version 1.6.2 and below

**Comment by amansoniamazatic** [comment]
@HenryHengZJ please fix this issue

**Comment by palm-ER** [comment]
`{{hosted_url}}/api/v1/ip` is working now in 1.7.1 but the chatbot is still returning "Oops! There seems to be an error. Please try again." instead of the configured Limit Message.
