### ISSUE TITLE
When Conversational Agent connects to ChatOpenAI, an error occurs when calling the tool.[BUG]

### ISSUE THREAD

**Issue by musuiot** [FlowiseAI/Flowise#2286]
**Describe the bug**
1.flowise version is: 1.6.6
2.Workflow:
![20240430091016](https://github.com/FlowiseAI/Flowise/assets/58774718/495e66de-4535-42b7-998e-a10c5bc3eac3)

3.An error occurred：
![2](https://github.com/FlowiseAI/Flowise/assets/58774718/4e49b815-4fc8-463f-b00c-00e49325cbe6)

**Comment by HenryHengZJ** [comment]
We'll deprecate Conversation Agent soon, try Tool Agent instead

**Comment by HenryHengZJ** [comment]
I saw you successfully solved it using ToolAgent - https://github.com/FlowiseAI/Flowise/issues/2287, closng for now
