### ISSUE TITLE
[FEATURE] ChatOllama Function

### ISSUE THREAD

**Issue by musuiot** [FlowiseAI/Flowise#2287]
Describe the bug
1.flowise version is: 1.6.6
2.Workflow:
![3](https://github.com/FlowiseAI/Flowise/assets/58774718/0acf75f2-96d1-481b-8b1f-669d715ee8cc)

3.An error occurred：
![4](https://github.com/FlowiseAI/Flowise/assets/58774718/c132b4dd-54aa-491a-b67d-40a44ff56754)

**Comment by musuiot** [comment]
There is no such error when using ChatOpenAI.

**Comment by HenryHengZJ** [comment]
ChatOllma doesnt support tool yet, something we are looking to add support soon

**Comment by HenryHengZJ** [comment]
Closing as ChatOllama now supports function calling: https://github.com/FlowiseAI/Flowise/pull/2892
