### ISSUE TITLE
[FEATURE] expose a DELETE method in upsert URL to remove records from record manager

### ISSUE THREAD

**Issue by jaredmcqueen** [FlowiseAI/Flowise#2288]
I was wondering if you could provide a method to delete records from the record manager through the upsert URL, perhaps by implementing a DELETE HTTP method. This would greatly enhance the functionality and user experience of my application.

In my app, users can create "workspaces" similar to channels in Slack or Discord. Within each workspace, users have the ability to upload files. The current Flowise record manager implementation correctly handles duplicate chunks by either inserting, skipping, or deleting them, which works flawlessly.

However, when a user deletes a file from a workspace, my app removes the corresponding points from the vector store (Qdrant), but the associated chunks remain in the Postgres record manager. This prevents the user from re-uploading the same file with identical parameters, as the sha1 chunks persist in the database.

I noticed that there is a function called patchDeleteUpsertHistory in the node_modules/flowise/dist/services/upsert-history/index.js file, but it doesn't seem to be publicly exposed. If this function could be made available or if you could provide an alternative solution, it would greatly improve the usability and consistency of my application.

Thank you for considering my request and for your ongoing support in developing this fantastic tool.

**Comment by HenryHengZJ** [comment]
yep `patchDeleteUpsertHistory` deletes record from Record Manager whenever user clear it from UI. We can support as an external API as well

**Comment by HenryHengZJ** [comment]
Available now as API: https://docs.flowiseai.com/api-reference/document-store#/document-store-vectorstore-id
