### ISSUE TITLE
[FEATURE] LocalAI integration

### ISSUE THREAD

**Issue by mudler** [FlowiseAI/Flowise#229]
**Describe the feature you'd like**

https://github.com/go-skynet/LocalAI (https://localai.io/) is a OpenAI drop-in API replacement with support for multiple model families to run LLMs on consumer-grade hardware, locally. As it is compatible with OpenAI, it just requires to set the base path as parameter in the OpenAI client, there is also an example with langchain-js in the LocalAI repository here: https://github.com/go-skynet/LocalAI/blob/577d36b5964ba0873b945f2ea00404ed52556408/examples/langchain/langchainjs-localai-example/src/index.mts#L7

**Additional context**

An integration with Flowise would allow the user to run everything entirely locally - I'm not sure if it makes sense to have a separate integration, or either allow the OpenAI integration which already exists to set a parameter from the user

**Comment by HenryHengZJ** [comment]
hey @mudler great to have you here!

We just integrated LocalAI - https://github.com/FlowiseAI/Flowise/pull/123 into Flowise not long ago, will be publishing the new release in next hour or so!

**Comment by mudler** [comment]
This is fantastic @HenryHengZJ ! thank you!
