### ISSUE TITLE
[FEATURE] Metadata filtering in Postgres

### ISSUE THREAD

**Issue by haimco50** [FlowiseAI/Flowise#2296]
I maybe missing something here but I realy tried hard to make it working w/o success - anyhow I can't make the postgress componnet working to filter the docs results by a given meta data info  - it's basically ignoring my metadata filteeing - here is my test case setup :
DB : 10 docs numbered with source numbered 1-10
<img width="337" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/91170552/da69bfcc-72a8-4772-88ce-f725a7ea57ad">

Postgress comp  - tried few variations of building the filter id tag but nothing works : - based on pgvector documentation it's supported - https://github.com/langchain-ai/langchain/issues/9726

<img width="449" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/91170552/0e113531-217d-4584-bac7-68d8b1299b22">

Anyhow - my failed test case is runnning RAG flow with hard coded '4' within  the source tag but getting other random documents each time. and not the expected  "4"  doc - 
<img width="347" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/91170552/1ae2dffa-8ac5-408f-b0cf-4eb158f152a0">

**Comment by HenryHengZJ** [comment]
Currently we still haven't added the capability to do Metadata filter for PG Vector DB. The Additional Configuration is the config used to connect to Postgres, not for filtering

**Comment by haimco50** [comment]
thanks @HenryHengZJ  for confirming that it's not supported - saved me some time from keep struggling with this.
Postgres DB is a very popular vector store and supporting metadata especially with a lot of files becomes a real necessity for any prod deployment so  appreciate it if you prioritize this item - I am ready also to contribute here with some guidelines.

**Comment by haimco50** [comment]
btw, is it possible to  add more columns  the the current postegree table  current columns are : id, pageContent, metadata, embedding  ? if not I think this could be another great enhancement as it's realy needed for various use cases,

**Comment by SirLucian** [comment]
Please. Need this for supabase please 🥺 

I may see what I can do to contribute

**Comment by Astriel** [comment]
Hey there, facing the same problem with embeddings on PGSQL. I'm using Flowise to be able to parse document, but each time I load a new one, it's always the first one which is loaded through PostGres. Everything was working well with Pinecone.

**Comment by HenryHengZJ** [comment]
here we go - https://github.com/FlowiseAI/Flowise/pull/2674

**Comment by HenryHengZJ** [comment]
Merged now 🎊

**Comment by haimco50** [comment]
This is great news - thanks much!!

**Comment by Astriel** [comment]
I've updated flowise and restarted docker, but seems I can't find the feature into the Postgres vector store ? Is there anything else to do ?

**Comment by mpurani** [comment]
@HenryHengZJ great news. when it will be updated on npm build.

**Comment by lampyon-canada** [comment]
Hi, does this also mean meta filtering should work if I am retrieving via Retriever Tool from a Document Store that uses Postgres as vector store? (Document Store blanked for the screenshot, but it is set.) Seems to be ignoring meta filters.

![Image](https://github.com/user-attachments/assets/1fd462ce-9de9-4dc6-9843-1e3879039a23)

![Image](https://github.com/user-attachments/assets/d1afb34b-6310-4ebe-ab0d-7a2d4849affa)
