### ISSUE TITLE
POST API chain issue, observation?.includes is not a function on large data 

### ISSUE THREAD

**Issue by coders21** [FlowiseAI/Flowise#2299]
Hi, i am using post api chain, i am retrieving property information from an api, each property has around 100 fields that i am getting,sending payload and getting response, issue is when the api response contain large data like 10 properties returning i am facing error of "observation?.includes is not a function" when i ask questions in chatbot, but when it has 2 or 3 properties it predicts the answer right and doesn't throw error.
On large data response i am getting issue.

On small api response:
![small](https://github.com/FlowiseAI/Flowise/assets/72495373/11e3a0f7-6bac-498d-a22d-80551d93981a)

On large api response:
![large](https://github.com/FlowiseAI/Flowise/assets/72495373/006d7a91-4eaa-48b1-a248-7e862aefdd4c)

On both cases the format of response is same.

**Comment by elix1er** [comment]
same
