### ISSUE TITLE
[FEATURE] RequestsGet and RequestsPost tools support

### ISSUE THREAD

**Issue by missmess** [FlowiseAI/Flowise#23]
**Describe the feature you'd like**
It seems that RequestsGet and RequestPosts tools not supported now.
How can I add support to these two tools.

**Comment by HenryHengZJ** [comment]
hey @missmess, they are already available. If you had git cloned the project, pull the latest changes and you'll see it.
![screely-1681912161538](https://user-images.githubusercontent.com/26460777/233096192-6f2e1404-dad2-4007-995d-774d4c619797.png)

For docker and npm installation, waiting for https://github.com/FlowiseAI/Flowise/pull/1 to merge before pushing a release. Will update soon

**Comment by HenryHengZJ** [comment]
New release has been pushed. RequestsGET and POST Tools should be there if you reinstall/pull latest changes.
