### ISSUE TITLE
[FEATURE] Conversational Retrieval QA Chain interaction with Pinecone

### ISSUE THREAD

**Issue by HugoPOIDVIN** [FlowiseAI/Flowise#2305]
Hi everyone,

I struggled a lot for 2 days misunderstanding why my QA Chain wasn't working. I found that the pinecone db I was using hadn't 'text' in vectors metadata. After adding it it finally worked perfectly : is it the way it's supposed to work ? 

Could an indication about this required 'text' metadata field be added in the QA Chain or the Pinecone node ?

**Comment by toi500** [comment]
I dont really undertand what do you mean by adding `metadata text `to pinecone. If the the `metadata text` was not present by default when you upserted the info then somthing there was wrong. What loader node did you use to upsert the data?

Text is mandatory in for pinecone, but you dont need to add it, it come by default.

![Screenshot 2024-05-03 012550](https://github.com/FlowiseAI/Flowise/assets/138339291/ae5709c7-6a61-4a35-8b47-832338cff87a)

**Comment by HugoPOIDVIN** [comment]
> I dont really undertand what do you mean by adding `metadata text` to Pinecone. If the the `metadata text` was not present on Pinecone by default after you upserted the data, then somthing there was wrong. What document loader node did you use to upsert the data?
> 
> `Metadata text` is mandatory, but you dont need to add it, it come by default.
> 
> ![Screenshot 2024-05-03 012550](https://private-user-images.githubusercontent.com/138339291/327628101-ae5709c7-6a61-4a35-8b47-832338cff87a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjI3NDksIm5iZiI6MTcxNDcyMjQ0OSwicGF0aCI6Ii8xMzgzMzkyOTEvMzI3NjI4MTAxLWFlNTcwOWM3LTZhNjEtNGEzNS04YjQ3LTgzMjMzOGNmZjg3YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwM1QwNzQ3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmY3MDRjOWYzMDEzNGNkOTMxOWViZmZlMWM5OWE2OWYzMjZjODQyODE1MGQyNWQ2Njk3MTMzMDg3MTdhOGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.94QZ1gpe72uLos2ROQQ48ERknZ1XcZJofOCE5SbBQ-8)

In fact, i wanted to use an existing pinecone db that hadn't this "text" field, and flowise wasn't giving me a single clue about it

**Comment by HenryHengZJ** [comment]
yeah it needed a `text` field. as normally user upsert through flowise, and by default every chunk comes with the `text` field. but yes we should have a clearer docs to specify that if using existing namespace, some fields are mandatory. will update the docs, closing for now
