### ISSUE TITLE
[BUG] PDF FILE UPLOAD Error: vectorsService.upsertVector - UnknownErrorException: PDFDocument: stream must have data

### ISSUE THREAD

**Issue by TheVoidRoger** [FlowiseAI/Flowise#2312]
**Describe the bug**
PDF File node upserting to Pinecone is giving an error even though the pdf file has been uploaded. File size is less than 5mb.

**To Reproduce**

1.  Connected the following nodes.. Recursive Character Text Splitter with 1000 chunk and 100 chunk overlap --> PDF File with less than 5mb pdf --> Pinecone with valid API, index and namespace. --> Conversational Retrieval QA Chain > ChatOpenAI. 
2. Clicked the green 'Upsert Vector Database' button
3. show error: "Error: vectorsService.upsertVector - UnknownErrorException: PDFDocument: stream must have data"

**Expected behavior**
Expected to show successful upsert.
Tried to replace the "pdf file" with a "plain text" node, it successfully upserted the data.

**Setup**
Via DigitalOcean, docker.

**Comment by HenryHengZJ** [comment]
not sure if this helps, but try using legacy build:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/e09d937e-3de2-4be6-bf78-717ad4ae70e1)

**Comment by TheVoidRoger** [comment]
Thank you @HenryHengZJ . Tried it. But no luck. Noticed with the PDF node, it won't even save as soon I've chosen a pdf. (tried couple of pdf, varying file sizes & compressions). I'm forced to refresh the page and it will remove the pdf that I've previously selected.

**Comment by TheVoidRoger** [comment]
Update: 
I've re-deployed it to render and it works.
I think something is blocking the pdf upload in digitalocean's backend.
It's not just the PDF uploader node as this issue also occurs with "Unstructured File loader" node inside DO environment.

Has anyone experience the same issue with DO? Found any solution?

**Comment by JNNelson** [comment]
Hello.
How did you solve it?
I have the same problem.
Docker v26.1.4
I've already tried with version 1.8.3 and also with 1.72.
VPS Contabo

**Comment by HenryHengZJ** [comment]
Try the latest version, itt should be working now. Feel free to re-open if issue persists
