### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'toLowerCase') - Tool Agent

### ISSUE THREAD

**Issue by PedroMangini** [FlowiseAI/Flowise#2314]
[BUG] I'm having trouble with the tool agent in Flowise. It sometimes returns this error, even though I'm only using GROQ, Buffer and a custom tool (everything works fine). Has anyone seen this before?

![image](https://github.com/FlowiseAI/Flowise/assets/39614021/1177d16c-0f58-4085-a42f-e3e1d76fdcfb)

![image](https://github.com/FlowiseAI/Flowise/assets/39614021/bb11774b-4860-4ff7-8cf4-900015b04ded)

**Comment by PedroMangini** [comment]
No, all the tools are working fine, apparently it's a flowise bug. if i delete the agent node and re-add i,t works perfectly

**Comment by PedroMangini** [comment]
> could be some error on your custom tool? if you try using a built in tool like calculator, do you see this error? it works fine for me: ![image](https://private-user-images.githubusercontent.com/26460777/327947490-b06568a6-7828-4b5c-95c8-72f90cd832ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4Njc3OTcsIm5iZiI6MTcxNDg2NzQ5NywicGF0aCI6Ii8yNjQ2MDc3Ny8zMjc5NDc0OTAtYjA2NTY4YTYtNzgyOC00YjVjLTk1YzgtNzJmOTBjZDgzMmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDAwMDQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMmUzNjRmZGRhOWQ5OTFkYmQ5ZTY5YzE2Mzc0NDhiZTZmYmI3MDZmZWFhMWY0ZTAwOTdiMTliMzVhZDUyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f4H7DWr6tKV2AOuNSp-wqpDJoREGXpsrfXwN0HXXz1E)


No, all the tools are working fine, apparently it's a flowise bug. if i delete the agent node and re-add i,t works perfectly

**Comment by HenryHengZJ** [comment]
Wil close this for now, and open a separate backlog item to better debug this particular error
