### ISSUE TITLE
[BUG] Install failed using MySQL - Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!

### ISSUE THREAD

**Issue by phongtnit** [FlowiseAI/Flowise#2323]
**Describe the current behavior**
Hi, I installed Flowise on Docker using new files in https://github.com/FlowiseAI/Flowise/tree/main/docker and using MySQL in .env. And failed installation with the following error: 

```Status: 500
Error: chatflowsService.getAllChatflows - Error: getRunningExpressApp failed!
```

Error image: 
<img width="1208" alt="Screenshot 2024-05-05 at 12 59 03" src="https://github.com/FlowiseAI/Flowise/assets/5652784/fd322f73-05d0-4e49-8035-58903f86af8a">

**My .env setting**
```PORT=3000
DATABASE_PATH=/root/.flowise
APIKEY_PATH=/root/.flowise
SECRETKEY_PATH=/root/.flowise
LOG_PATH=/root/.flowise/logs
BLOB_STORAGE_PATH=/root/.flowise/storage

# NUMBER_OF_PROXIES= 1
# CORS_ORIGINS="*"
# IFRAME_ORIGINS="*"

DATABASE_TYPE=mysql
DATABASE_PORT=3306
DATABASE_HOST=172.17.0.1
DATABASE_NAME=abc
DATABASE_USER=abc
DATABASE_PASSWORD=abc
```

**Describe the expected behavior**
I am sure that MySQL account information is correct. I checked the MySQL database, it was empty after running the Flowise using `sudo docker compose up -d`.

If I don't use MySQL as my DB backend, the installation is successful and the script worked fine.

What I should do to install Flowise using MySQL? Thanks for your support,

**Additional context**
- OS: Ubuntu 24.04
- Docker version: Docker version 26.1.1, build 4cf5afa
- MySQL version: mysql  Ver 8.0.36-2ubuntu3 for Linux on x86_64 ((Ubuntu))
- My ufw firewall:
```
sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
80/tcp                     ALLOW       Anywhere                  
443                        ALLOW       Anywhere                  
3306 on docker0            ALLOW       172.17.0.0/16   
3306 on docker0            ALLOW       172.18.0.0/16           
22/tcp (v6)                ALLOW       Anywhere (v6)             
80/tcp (v6)                ALLOW       Anywhere (v6)             
443 (v6)                   ALLOW       Anywhere (v6)
```
- My `mysqld.cnf`:
```
bind-address = 0.0.0.0
```
- I tested access the MySQL remotely using `mysql -u <mysql_user> -h <remote_ip> -p` and it worked.
- The IP address of the Flowise container is in 172.18.0.0/16 network.
- My docker logs:
```
2024-05-05 09:51:37 [INFO]: Starting Flowise...
2024-05-05 09:51:37 [INFO]: ⚡️ [server]: Flowise Server is listening at 3000
2024-05-05 09:51:47 [ERROR]: ❌ [server]: Error during Data Source initialization: connect ETIMEDOUT
Error: connect ETIMEDOUT
    at PoolConnection._handleTimeoutError (/usr/local/lib/node_modules/flowise/node_modules/mysql2/lib/connection.js:205:17)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by HenryHengZJ** [comment]
should be resolved now!
