### ISSUE TITLE
[BUG] PineconeArgumentError: The client configuration had validation errors: argument must NOT have additional properties.

### ISSUE THREAD

**Issue by bahimzabir** [FlowiseAI/Flowise#2324]
I just got an error in Flowise when using Pinecone to store document vectors:

`PineconeArgumentError: The client configuration had validation errors: argument must NOT have additional properties.`

It seems to be an issue since the latest version 16.6.6.

**Comment by HenryHengZJ** [comment]
Try to redeploy again it should works - https://github.com/FlowiseAI/Flowise/issues/2316
