### ISSUE TITLE
Error Chaining. (parameter issue?)

### ISSUE THREAD

**Issue by Mobivs** [FlowiseAI/Flowise#233]
**Describe the bug**
When chaining a conversational retrieval QA to a Conversational Agent via a Chain Tool.
"Chain conversational_retrieval_chain expects multiple inputs, cannot use 'run'"

**To Reproduce**
Follow this: https://www.youtube.com/watch?v=jDJIIVWTZDE&t=1109s

**Expected behavior**
Should use the Conversational Retrieval QA

**Screenshots**

**Setup**

-   OS: JS on Render
-   Browser: Chrome

**Additional context**
This seems to be a parameter issue.
I hope this helps!

**Comment by HenryHengZJ** [comment]
Hey you can try using `RetrievalQAChain` for that. 
`ConversationalQAChain` is normally used as the final chain

**Comment by Mobivs** [comment]
I found the issue. If you fail to fill in the additional parameters on the Conversational Retrieval QA you will get the mentioned error.
