### ISSUE TITLE
[BUG] Embed | Styling all white

### ISSUE THREAD

**Issue by vexersa** [FlowiseAI/Flowise#234]
**Describe the bug**
When using the Embed option under "API Endpoint" then "Embed in website or use as API" functionality, the resulting styling is hard to read and isn't easily configurable. 

**To Reproduce**

1. Create flow
2. Save flow
3. Click "API Endpoint" button top right
4. Copy "Embed" code and save it to an HTML file or embed as HTML code block in a CMS (I used Wordpress)
5. Open the embedded chatbot UI using the button in the bottom right
6. Styling looks totally whited out and the text will be very difficult to read

**Expected behavior**
The chatbot should be easy to read or configurable

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/7994227/19ed7624-dd0d-473b-bbdf-f68b8a73eca5)

**Setup**

-   OS: Windows, embedded code in Wordpress page
-   Browse: Chrome

**Comment by chungyau97** [comment]
Hey there, I'm not able to replicate your error.

Results:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/063ca65c-ac5a-49e0-a187-fbc593658114)

**Comment by vexersa** [comment]
Please could you try on this demo page?
https://known.consulting/demo/

**Comment by kushu7** [comment]
## ISSUE
<img width="1053" alt="Screenshot 2023-06-01 at 12 34 13 AM" src="https://github.com/FlowiseAI/Flowise/assets/31707153/eaa3884a-e186-48e2-bed8-d2ccea29f694">
It was inheriting  color from body @chungyau97.  i think we should define color at chatbot level?

**Comment by HenryHengZJ** [comment]
hey guys chat embed will be customizable in the next release. backgroundcolor, icon, size and all

**Comment by HenryHengZJ** [comment]
with the latest update, you can now configure mostly everything on the embedded widget: https://github.com/FlowiseAI/FlowiseChatEmbed#configuration

<img width="661" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/b7d18cc0-27f9-4b98-a78c-8dc17fac4a26">
