### ISSUE TITLE
[BUG] Wrong CMD in Dockerfile making container fail to start

### ISSUE THREAD

**Issue by blazux** [FlowiseAI/Flowise#2340]
The CMD in the Dockerfile seems to be wrong, when building 1.7.1, here's the ouput of the container attempting to start :

```
➜ docker git:(main)  $ docker run --name flowise3 -p 3000:3000 flowise
Flowiseai Server

VERSION
  flowise/1.7.1 linux-x64 node-v20.12.2

USAGE
  $ flowise [COMMAND]

COMMANDS
  start
```

I've replaced the original CMD line with : 
`CMD ["flowise","start"]`

And now it's working fine.

**Comment by HenryHengZJ** [comment]
which dockerfile? the one in `docker` folder or root level?

**Comment by blazux** [comment]
in the docker folder
