### ISSUE TITLE
[BUG] CSV agent is not working with OpenAI ChatGPT

### ISSUE THREAD

**Issue by automaton82** [FlowiseAI/Flowise#2341]
**Describe the bug**
If you attempt to use the CSV agent with the attached public csv city data file, you get the following error:

Question: `what cities are there`

Response:
```
{'LatD': 'int64', ' "LatM"': 'int64', ' "LatS"': 'int64', ' "NS"': 'object', ' "LonD"': 'int64', ' "LonM"': 'int64', ' "LonS"': 'int64', ' "EW"': 'object', ' "City"': 'object', ' "State"': 'object'}
2024-05-06 19:54:32 [ERROR]: [server]: Error: Sorry, I'm unable to find answer for question: "what cities do you have" using following code: "df["City"].unique()"
Error: Sorry, I'm unable to find answer for question: "what cities do you have" using following code: "df["City"].unique()"
    at CSV_Agents.run (C:\git\flowise\packages\components\dist\nodes\agents\CSVAgent\CSVAgent.js:165:23)
    at async utilBuildChatflow (C:\git\flowise\packages\server\dist\utils\buildChatflow.js:232:15)
    at async createInternalPrediction (C:\git\flowise\packages\server\dist\controllers\internal-predictions\index.js:7:29)
```

All questions will fail though.

CSV file: [cities.csv](https://github.com/FlowiseAI/Flowise/files/15227621/cities.csv)

**To Reproduce**

1. Create a chatflow and add a `CSV agent` node
2. Use OpenAI ChatGPT `Chat Model` or `LLM` node, it's the same result for both
3. Upload the attached csv file
4. Ask "what cities are there"

**Expected behavior**
This should work.

**Setup**

-   Installation `pnpm start`
-   Flowise Version latest as of https://github.com/FlowiseAI/Flowise/commit/ef532866fde6b32305eadf076a220926c3c732a6
-   OS: Windows 11
-   Browser all

**Additional context**
Aside from this problem, it also appears the uploaded file does not go into DISK BLOB storage. It goes into the database as base64. This behaviour is different than the CSV document loader which does go into DISK BLOB storage immediately when uploaded. Not sure if this is intended or not.

**Comment by HenryHengZJ** [comment]
OpenAI suddenly gives the prefix `python`, so the whole code becomes:

```
import pandas as pd
```python
print(df["Company Name"])
` ` `
```
which causes error when trying to run on pyodide
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/20a7a717-9089-45a3-95f3-f142cf083eed)

**Comment by HenryHengZJ** [comment]
so the solution is to do some regex check to get rid of the prefix

**Comment by toi500** [comment]
@HenryHengZJ 

It looks like the same issue I just reported with the Airtable Agent

https://github.com/FlowiseAI/Flowise/issues/2364

**Comment by Hariharan1828** [comment]
I would like to take up this issue, planning to implement the changes in the ChatflowPool

**Comment by HenryHengZJ** [comment]
Closing as https://github.com/FlowiseAI/Flowise/pull/2983 merged
