### ISSUE TITLE
404 by In-Memory Vectore Store

### ISSUE THREAD

**Issue by Petopp** [FlowiseAI/Flowise#2346]
I'm encountering a 404 error with the In-Memory Vector Store. I'm currently directly embedding the data as text, so there shouldn't be any missing files. Also, the model's endpoints are functioning properly. I've verified this with Curl. Does anyone have an idea what might be causing this?

![image](https://github.com/FlowiseAI/Flowise/assets/41972011/9d6fd176-d74c-43f0-9415-dc4a93105181)

**Comment by HenryHengZJ** [comment]
Try Conversational Retrieval QA Chain, and recreate the flow. If you can access LocalAI through cURL, it should be able to work.
