### ISSUE TITLE
Upsert button diseaper

### ISSUE THREAD

**Issue by plykiteai** [FlowiseAI/Flowise#2347]
hello, i ve dow a flowise for a pdf file with all the cards (spilltet, openai embedding, pinecone upsert documents,chatopenai and convesationnal retrieval) but the upsert button is no displaying!  2 days ago it was there ;)
Thnk you for your help.
PAscal

![Capture](https://github.com/FlowiseAI/Flowise/assets/168986730/b30baa5a-854a-4db9-9c5d-08a3e81d662a)

**Comment by HenryHengZJ** [comment]
Try changing the Pinecone Upsert node to the new Pinecone node: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/7572a2de-bfb1-4d92-b0be-a14670b6c380)

**Comment by plykiteai** [comment]
@HenryHengZJ Perfect. Thank you very muech. Pascal
