### ISSUE TITLE
Rate Limit Bug

### ISSUE THREAD

**Issue by palm-ER** [FlowiseAI/Flowise#2351]
`{{hosted_url}}/api/v1/ip` is working now in 1.7.1 but the chatbot is still returning "Oops! There seems to be an error. Please try again." instead of the configured Limit Message.

_Originally posted by @palm-ER in https://github.com/FlowiseAI/Flowise/issues/2280#issuecomment-2098372856_

**Comment by HenryHengZJ** [comment]
should be resolved in the new flowise-chat embed v1.2.5
