### ISSUE TITLE
Unable to load open AI models in my docker container [BUG]

### ISSUE THREAD

**Issue by Aaryaveerkrishna23** [FlowiseAI/Flowise#2358]
Even after setting my HTTP and HTTPS proxies in the .env file in my docker conatiner, I am **unable to load OpenAI models into Flowise's UI** in the OpenAI ChatModel section.

**Comment by HenryHengZJ** [comment]
Flowise fetches like models list from [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/models.json)

You can modify the env variable to specify where to fetch the file - https://docs.flowiseai.com/configuration/environment-variables#models
