### ISSUE TITLE
[BUG] overrideConfig for parameter in 2 nodes not working as documented

### ISSUE THREAD

**Issue by grimaldilionbrain** [FlowiseAI/Flowise#2359]
**Describe the bug**

In calling a prediction endpoint of a chatbot via API, I  tried using the overrideConfig method for passing an overrideConfig to two parameters named the same way in two different nodes (in my case openAIEmbeddings and chatOpenAI, both having a modelName parameter), However, the call seems to allow override of all chatflow parameters except the modelName for either of the two nodes. The value of modelName remains fixed to the default, regardless of the values given in overrideConfig. This happens despite the fact that I am specifying the two model names as described in the documentation (in the Embed window of the chatflow web interface):

```
body_data = {
        "question": <some_question>,
        "overrideConfig": {
            "modelName[openAIEmbeddings_0]": <embedding_model_name>,
            "modelName[chatOpenAI_0]": <chat_model_name>,
            ...
        }
}
```

![image](https://github.com/FlowiseAI/Flowise/assets/150141042/b2eaabb4-ab7f-452d-b944-72a307cd23c7)

(I know that the structure of the body_data argument is different in the image snippet, with no "overrideConfig", but I followed the structure of the main documentation. Also, trying to use the format without "overrideConfig" results in none of the parameters being updated)

(I double checked, that seems to be the name of the two nodes, at least according to the export of the chatflow schema)

If I don't specify the node name (i.e. just using one "modelName": ...), the value seems to be read correctly, but then of course one of the two nodes complains about a non-existing model.

The issue seem to be caused by using the "<param_name>[<node_id>]" syntax, since using it for a uniquely named parameter in the chatflow also results in the override value not being used.

**To Reproduce**
I am calling the API from a python script, following the format suggested in the API documentation:

```python
# ... API url and key were read from .env, overrideConfigs stored in settings dictionary
headers = {"Authorization": f"Bearer {API_KEY}"}

def query(body_data) -> Response:
    response = requests.post(API_URL, json=body_data, headers=headers)
    return response

def main() -> None:
    body_data = {
        "question": settings["question"],
        "overrideConfig": {
            "modelName[openAIEmbeddings_0]": settings["modelName_embeddings"],
            "modelName[chatOpenAI_0]": settings["modelName_chat"],
            # other params
        },
    }
    output = query(body_data)
```

The chatflow schema is a simple qna from a text-file document with in-memory store:

![image](https://github.com/FlowiseAI/Flowise/assets/150141042/d585cde4-7ec0-479f-b98b-2218abe3c638)

**Expected behavior**
When using an overrideConfig parameter containing the fields `"modelName[<node_id>]` is expect the value of the modelName parameter to be updated.

**Flow**

[test_overrideConfig_issue Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15246476/test_overrideConfig_issue.Chatflow.json)

**Setup**

-   Installed via docker
-   Flowise Version: 1.4.12
-   OS: Amazon Linux 2023
-   Browser: n.a.

**Comment by HenryHengZJ** [comment]
can you try this instead?
```
# ... API url and key were read from .env, overrideConfigs stored in settings dictionary
headers = {"Authorization": f"Bearer {API_KEY}"}

def query(body_data) -> Response:
    response = requests.post(API_URL, json=body_data, headers=headers)
    return response

def main() -> None:
    body_data = {
        "question": settings["question"],
        "overrideConfig": {
            "modelName": {
                 "openAIEmbeddings_0": model1,
                 "chatOpenAI_0": model2
            }
        },
    }
    output = query(body_data)
```

**Comment by grimaldilionbrain** [comment]
Hi Henry, thanks for the suggestion. It still seems like something is off, since I now get this error:

`DEBUG:root:b"400 We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com.)"`

(to me it seems like the value of the "modelName" field is still sent all to both of the nodes, leading to OpenAI API complaining that they are getting the wrong format for modelName in the call)

**Comment by HenryHengZJ** [comment]
I've tested it works:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/cb9f6778-b4ef-47c2-b87d-a405ef8e1547)

check if you are passing in correct model name (string)

**Comment by grimaldilionbrain** [comment]
You are right, somehow I must have made a mistake in calling the model name. Sorry about that, trying again with your suggested format worked well. Thanks a lot!

**Comment by Cranbaerry** [comment]
I think this one needs to be reopen, it is now acting up and not working with these params:
"modelName": {
      "chatOpenAI_0": "gpt-4o-mini",
      "chatOpenAIEmbeddings_0": "text-embedding-3-small"
    },

throws error as: 400 We could not parse the JSON body of your request. (HINT: This likely means you aren't using your HTTP library correctly. The OpenAI API expects a JSON payload, but what was sent was not valid JSON. If you have trouble figuring out how to fix this, please contact us through our help center at help.openai.com
