### ISSUE TITLE
[BUG] ChatGoogleVertexAI - Chat-Bison

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#2365]
Issue with ChatGoogleVertexAI node when using chat-bison after 1.6.5 versions. Works fine on 1.6.5. 

Error: Unable to verify model params: {"lc":1,"type":"constructor","id":["langchain","chat_models","chat_integration","ChatVertexAI"],"kwargs":{"temperature":0.1,"model":"chat-bison","auth_options":{"

Also Gemini 1.5 model doesn't work. It returns Object Object as the output.

**Comment by HenryHengZJ** [comment]
For Gemini 1.5, I've added a commit [here](https://github.com/FlowiseAI/Flowise/commit/20489765454e7e0a613e86c4ace4664d1219abca) to update the gemini 1.5 model

**Comment by vijaykammili** [comment]
Perfect! Thank you very much @HenryHengZJ! Let me know when chat-bison is fixed please.
