### ISSUE TITLE
[BUG] Document Stores - Confluence: "Please fill in mandatory fields."

### ISSUE THREAD

**Issue by czepan** [FlowiseAI/Flowise#2367]
**Describe the bug**
When trying to save a Confluence Document Store Loader the application says
"Please fill in mandatory fields."
even if all mandatory fields are set.

**To Reproduce**

1. Go to Document Stores
2. Click on a newly created Store
3. Click on Add Document Loader
4. Click on Confluence
6. Fill in all mandatory fields
8. See error

**Expected behavior**
Expect to work :)

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/122617761/d9675260-ea27-44b5-a250-3464a1bf954d)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation: docker
-   Flowise Version: 1.7.1
-   OS:  Linux
-   Browser: Chrome

**Comment by HenryHengZJ** [comment]
should be fixed in this [PR](https://github.com/FlowiseAI/Flowise/pull/2356), will push new version shortly

**Comment by HenryHengZJ** [comment]
should be fixed in latest `v1.7.2`, please try redeploy/pull the latest changes again
