### ISSUE TITLE
[BUG] Data too long for column 'usedTools' at row 1 using MySQL

### ISSUE THREAD

**Issue by pmribeiro** [FlowiseAI/Flowise#2377]
**Describe the bug**

When using a custom tool and the output of this tool is long the result is a Data too long for column 'usedTools' at row 1 and in the logs you can see this is a issue writing to MySQL

**Expected behavior**

<img width="419" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/1893035/6ee26d51-8309-4d9e-9150-19e973dcb4b0">

**Screenshots**

<img width="1027" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/1893035/090403af-fb25-4256-ab0b-bd3eae353659">

**Setup**

-   Docker installation of flowise 1.7.1

**Comment by HenryHengZJ** [comment]
closing as https://github.com/FlowiseAI/Flowise/pull/2908 merged
