### ISSUE TITLE
404 error when embedding chatbot[BUG]

### ISSUE THREAD

**Issue by scooter7** [FlowiseAI/Flowise#2378]
Hi, I have embedded a chatbot that uses the lead form. In HuggingFace (where it is hosted), everything works fine. But, when I embed the chatbot on an external site, the lead form doesn't work. It also has a different look on the external site (no save button, just an arrow for the submission that never submits and blocks the user from entering text in the main text field of the bot. The embedded bot lives at https://vineburgh.weebly.com/flow.html
![image](https://github.com/FlowiseAI/Flowise/assets/114838/6ce6473c-4015-42a8-8aad-320425f07fe0)

**Comment by 0xi4o** [comment]
@scooter7 We pushed a fix earlier today to address this issue. Please use the latest version of the embed library. Let me know if that doesn't work.

**Comment by scooter7** [comment]
Hi @0xi4o , how would I update this on HuggingFace? Thanks!

**Comment by HenryHengZJ** [comment]
Are you using the `cdn.jsdelivr.net`? or your forked chatembed repo? If you are using your own forked repo, simply sync to the latest update -https://docs.flowiseai.com/using-flowise/embed#custom-modificaton

**Comment by scooter7** [comment]
Hi @HenryHengZJ ,

When I export the messages from the Flowise UI into a json file, I only get one user at a time. What I'd like is to be able to download all of the messages cumulatively over a date range:
![image](https://github.com/FlowiseAI/Flowise/assets/114838/3f283b59-c691-4247-a538-e046a0ff9377)

Is there any way to enable that? Thanks!
