### ISSUE TITLE
[BUG] Webchat Embed & Chat in the FlowiseAI UI in the Chatflow editor timeout

### ISSUE THREAD

**Issue by qdrddr** [FlowiseAI/Flowise#2380]
**Describe the bug**
In the Webchat Embed & Chat in the FlowiseAI UI in the Chatflows editor canvas if using Ollama running locally, it may respond with a delay longer thatn for example OpenAI, then the chat times out and soesn't show the responce. However if I'm in the Chatflow editor, I can close the chat, and open it again then I can see the responce. While with Embed chat this workaround doesn't work.

**To Reproduce**
Create Chatflow with Ollama, export: [qdrant2-W Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15266645/qdrant2-W.Chatflow.json)

**Expected behavior**
To not timeout and display the responce without reloading the page or closing and re-opening the chat. 

**Screenshots**
![ScreenShot 2024-05-09 at 12 59 57](https://github.com/FlowiseAI/Flowise/assets/564658/70a5cb19-6179-4f3e-9a28-644eb49f9568)

**Flow**
[qdrant2-W Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15266645/qdrant2-W.Chatflow.json)

**Setup**

-   Installation: k8s [deployment from this helm chart](https://cowboysysop.github.io/charts/), helm chart version 3.3.0, docker image from docker hub, tested with: flowiseai/flowise:1.6.6 & & 1.7.2
-   Flowise Versions tested: 1.6.6 & 1.7.2
-   OS: Ubuntu Linux 22.04  
-   Browser: Tested in both Edge, Chrome, Safari: latest versions (macOS 14)

**Additional context**
I beleve there is some sort of timeout settings that causing this issue that needs to be adjusted. Could it be hardcoded?

**Comment by amansoniamazatic** [comment]
@qdrddr I think you're facing a similar issue to this one, #2291

**Comment by qdrddr** [comment]
I believe it relates to the fact that I'm running an Ollama locally self-hosted model, which may not be as fast and responsive as OpenAI. 

Flowise needs to handle these situations appropriately. It can be beneficial for the Development process and be independent and a cost perspective to ensure people can run their models locally even if they are slower and more responsive than commercially available APIs & Models.

Some RAG/Agrens may respond slowly, and that's fine; not everything should be in a "chat conversation form".

**Comment by HenryHengZJ** [comment]
will close this and continue on #2291
