### ISSUE TITLE
[QUESTION] Tool Agent support for chatollama

### ISSUE THREAD

**Issue by KarthickMani87** [FlowiseAI/Flowise#2383]
There is a use case where I want to post URL API as soon as the user enters his name and phone number. This is working fine when I use chatOpenAI. I am attaching the screenshot for reference. This is the working use case. You can see the webhook post has been sent successfully.

![image](https://github.com/FlowiseAI/Flowise/assets/94393722/505e59c3-8d9b-4897-a048-d4bc56fbecec)

I am trying the same flow except chatOpenAI has been replaced with with ollama running locally. But I am getting following error "_**Error: This agent requires that the "bindTools()" method be implemented on the input model**_.". 

![image](https://github.com/FlowiseAI/Flowise/assets/94393722/50881701-c65b-4524-a6a4-a2d60b694ae8)

**I am aware the tool agents supports models that supports function calling (such as chatOpenAI chatMistral)**. Any suggestions would be helpful.
Is there any other way the same use case can be accomplished with ollama running locally?

Warm Regards,
Karthick

**Comment by HenryHengZJ** [comment]
for ollama, we need to add the integration dedicated for function calling - https://js.langchain.com/docs/integrations/chat/ollama_functions

**Comment by snailbrainx** [comment]
Ah great, good to know I'm not the only one.

Is there an ETA on this. Happy to donate $50. Only for learning/testing atm.

**Comment by napa3um** [comment]
Workarround: use ChatLocalAI block for Ollama with base url http://host.docker.internal:11434/v1, but this is without streaming

**Comment by snailbrainx** [comment]
> http://host.docker.internal:11434/v1

this doesn't seem to use the calculator tool for example:

![image](https://github.com/FlowiseAI/Flowise/assets/17693211/9ea32a20-d397-454c-b637-e726b256c39a)
![image](https://github.com/FlowiseAI/Flowise/assets/17693211/009d058b-7d2c-4893-bcb9-006c52b564a9)

illama itself works. it's the agent tools that is not.

**Comment by KarthickMani87** [comment]
@snailbrainx , 

Yes, I have tried too. It does not look like it used the tools "calculator."

**Comment by KarthickMani87** [comment]
@HenryHengZJ ,

If I understand correctly, this will be a new feature? When can we expect to see this on flowise? ETA, please?

Warm Regards,
Karthick

**Comment by snailbrainx** [comment]
I have sponsored $50 if that helps. 

This will allow a lot of people to run the tools agent locally.

**Comment by HenryHengZJ** [comment]
here - https://github.com/FlowiseAI/Flowise/pull/2403

**Comment by KarthickMani87** [comment]
Hi @HenryHengZJ ,

Thank you very much for the enhancement/feature. I just have to upgrade the flowise to get this feature to work?

Warm Regards,
Karthick

**Comment by KarthickMani87** [comment]
> here - #2403

Hi @HenryHengZJ , 

Please let me know how to use Tool System Prompt. You can give the tool system prompt #2403 for reference.

Warm Regards,
Karthick

**Comment by HenryHengZJ** [comment]
> > here - #2403
> 
> Hi @HenryHengZJ ,
> 
> Please let me know how to use Tool System Prompt. You can give the tool system prompt #2403 for reference.
> 
> Warm Regards, Karthick



> > here - #2403
> 
> Hi @HenryHengZJ ,
> 
> Please let me know how to use Tool System Prompt. You can give the tool system prompt #2403 for reference.
> 
> Warm Regards, Karthick



> > here - #2403
> 
> Hi @HenryHengZJ ,
> 
> Please let me know how to use Tool System Prompt. You can give the tool system prompt #2403 for reference.
> 
> Warm Regards, Karthick

Because every LLM works differently, so the idea is for you to modify the prompt to have the LLM pick and use the tools appropriately. The PR will need to be merged in order to test it on Flowise

**Comment by KarthickMani87** [comment]
Hi @HenryHengZJ ,

In the meantime, I tried cloning the branch you have been working (feature/ChatOllama) built it and ran the flowise. 

This is what I give in Tool System Prompt.

![image](https://github.com/FlowiseAI/Flowise/assets/94393722/6b77442a-0125-4fcf-a8ec-3a3ff9f99242)


This is the output I got (_**Failed to parse a function call from mistral output: {"num1": 8, "num2": 9}**_). 
![image](https://github.com/FlowiseAI/Flowise/assets/94393722/cd7b33fe-0f16-48d2-8bb2-e42528cac913)

I will wait for the merged code. 

Warm Regards,
Karthick

**Comment by HenryHengZJ** [comment]
@KarthickMani87 its generally not recommended to modify the tool prompt, i've added more description to it:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/227ce4cc-31cb-42a7-80c6-88254736a8cd)

Under the hood, Ollama's JSON mode is being used to constrain output to JSON. Output JSON will contains two keys: `tool` and `tool_input fields`. We then parse it to execute the tool. Because different models have different strengths, it may be helpful to pass in your own system prompt.

**Comment by KarthickMani87** [comment]
Hi @HenryHengZJ , Thanks again for completing this feature.

**Comment by KarthickMani87** [comment]
Hi @HenryHengZJ ,

I have a question. In this flow, webhook got triggered only once when a name and phone number were received from a user.

![image](https://github.com/FlowiseAI/Flowise/assets/94393722/25a71650-b8c5-49fa-a59c-3c80d0f9eaaa)

But in the case of ollamaFunction, webhook is getting triggered every time. How to make it call the tool only for a specific condition in the chat? For example, I want to post URL only for name and phone number and the rest of the time it should just answer my questions.

**Comment by napa3um** [comment]
> How to make it call the tool only for a specific condition in the chat?

use Conversational Agent instead Tool Agent

**Comment by erlebach** [comment]
OllamaFunction is no longer available in Flowise. Was that deliberate? What is the alternative, using Open Source tools?
