### ISSUE TITLE
Chat wizard scroll bars[FEATURE]

### ISSUE THREAD

**Issue by mahaboobkhan29** [FlowiseAI/Flowise#239]
@HenryHengZJ 
I just provided a long link as a prompt in the chain. When it comes to the chatbot, I have to move the horizontal scroll bar to see the full link. Could you please check this issue?

Additionally, when a user asks a question in the chatbot, the vertical scroll bar doesn't automatically scroll to the bottom. We have to manually move the vertical scroll bar to view the user's message. However, when the AI responds, it automatically scrolls to the bottom.

And when the user asks a question and minimizes the chatbot, we don't know if the AI assistant has answered the question or not. It would be better to show a red dot above the chatbot icon when the chatbot is minimized to indicate to the user that they have received an answer

I understand that you mentioned the upcoming release will include customizable chat embed options. Please consider addressing these issues in the next release
![image](https://github.com/FlowiseAI/Flowise/assets/88474821/b7cdb99d-af5a-43d8-a606-99abe4f1d743)

**Comment by vkrm-segta** [comment]
@HenryHengZJ  I understood the problem and i can resolve this. Can you assign this to me

**Comment by santoshy1101** [comment]
@HenryHengZJ I am also working on this issue let's see if it works.
