### ISSUE TITLE
Llamaindex Azure - Unkown Model [BUG]

### ISSUE THREAD

**Issue by evan-100** [FlowiseAI/Flowise#2394]
**Describe the bug**
When using any other model than GPT-4 with LlamaIndex Azure nodes, I receive the error "Error: Unknown model:" in the chat. The deprecated Azure nodes still work, but not the newer version.  

**To Reproduce**
Clone the LlamaIndex Context Chat Engine template, and replace all OpenAI nodes with LlamaIndex Azure nodes. Attempt to chat with gpt-3-turbo or any other model than gpt-4.

**Screenshots**

![TinySnap-2024-05-12-09 20 03](https://github.com/FlowiseAI/Flowise/assets/62482366/7f778433-793c-44ff-8899-7607b7d306be)
![TinySnap-2024-05-12-09 25 44](https://github.com/FlowiseAI/Flowise/assets/62482366/cac8ac87-1c66-49da-8b7f-a8796ae326bf)

**Additional context**
Using version flowise@1.7.2
--

[flowise@1.7.2](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.7.2)

**Comment by HenryHengZJ** [comment]
PR fix here - https://github.com/FlowiseAI/Flowise/pull/2440
