### ISSUE TITLE
[BUG] The Chain Tool is not working with the Conversational Retrieval QA Chain

### ISSUE THREAD

**Issue by toi500** [FlowiseAI/Flowise#2400]
**Describe the bug**

@HenryHengZJ please bear with me 1 min, since this issue is a bit tricky to understand.

The `Chain Tool`  node does not work as expected when is conected to a `Conversational Retrieval QA Chain`.

The Agent can not use the `Chain Tool` to get any info from the `Conversational Retrieval QA Chain`. It is unclear if this is a issue with the Agent or the `Chain Tool` node itself. 

**To Reproduce**
1. Upload the attached flow (a Tool Agent conected to a Conversational Retrieval QA Chain via the Chain Tool). See bellow.
2. Once loaded, try to make the Tool Agent to use the `Chain Tool` by asking relevant questions. In this case; "What Tigermergente is all about?"
3. You will see that it gives you an empty response:

![Screenshot 2024-05-13 163307](https://github.com/FlowiseAI/Flowise/assets/138339291/3c7b9e01-151f-467e-8299-863405563a90)

4. If you force the Agent to use the `Chain Tool` via system message, then it will make up a response and will tell you that it cant use the `Tool Chain`

<img width="506" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/138339291/3d1a4bd2-ed63-4cf8-aaf2-e6b0cea3414a">

![Screenshot 2024-05-13 163722](https://github.com/FlowiseAI/Flowise/assets/138339291/1ba133f9-8171-4fab-b63e-2df10673c655)

5. The `Tool Agen`t can see the `Chain Tool` but cant use it.

<img width="311" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/138339291/af3fa5db-692c-459d-8252-70d8fe56f879">

**Expected behavior**

`Tool Agent` uses the `Chain Tool` with no problem.

**Flow**

[test - 004 Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15296255/test.-.004.Chatflow.json)

**Setup**

-   Flowise is up to date.

**Comment by niztal** [comment]
@HenryHengZJ please help

**Comment by niztal** [comment]
Fixed this issue via [PR](https://github.com/FlowiseAI/Flowise/pull/2430) 

@toi500 FYI

**Comment by niztal** [comment]
that's a good point @toi500 I wasn't aware of that agent is going to be deprecated.

I'll try to use the Tool Agent as the base agent and see if it works.

Thanks

**Comment by niztal** [comment]
@toi500 I've changed it to be based on ToolAgent, 

Your comment was very effective, thanks 👏

**Comment by toi500** [comment]
You are the man! Thank you for ur great work here.
