### ISSUE TITLE
[BUG] Data too long for column 'group_id' at row 1 using MySQL

### ISSUE THREAD

**Issue by stefanos87** [FlowiseAI/Flowise#2405]
**Describe the bug**
This message appears when I connect the "Mysql Record Manager" to the DB Quadrant EE vector and perform the upsert.

I'm using version 1.6.6 (docker)

![Schermata 2024-05-14 alle 12 23 59](https://github.com/FlowiseAI/Flowise/assets/21968830/6f122d41-d9f8-49e4-9203-e1f4b7d532c3)

**Comment by HenryHengZJ** [comment]
closing as https://github.com/FlowiseAI/Flowise/pull/2908 merged
