### ISSUE TITLE
[BUG] Error in node-gyp during yarn install on macOS M1

### ISSUE THREAD

**Issue by try-to-fly** [FlowiseAI/Flowise#241]
**Describe the bug**

When running `docker build` on macOS M1, there is an error in node-gyp during the `yarn install` step. The error is caused by missing dependencies.

**To Reproduce**

1. Execute `docker build` command.
2. Observe the error during the `yarn install` step.

**Expected behavior**

The `yarn install` step should complete successfully without any errors.

**Screenshots**

**Setup**

- OS: macOS M1

**Additional context**

The issue can be resolved by modifying the Dockerfile as follows:

Change `RUN apk add --update libc6-compat` to `RUN apk add --update libc6-compat python3 make g++`.

This modification ensures that the necessary dependencies are installed, allowing node-gyp to run successfully during the `yarn install` step.

Please note that the issue occurs specifically on macOS M1, and the provided solution addresses the missing dependencies.

**Comment by HenryHengZJ** [comment]
Thanks for the bug! Will make those update!

**Comment by HenryHengZJ** [comment]
Issue should be resolved as #258 merged
