### ISSUE TITLE
Need GPT-4o access

### ISSUE THREAD

**Issue by ahsan3219** [FlowiseAI/Flowise#2418]
I need GPT-4o access in flowise

**Comment by HenryHengZJ** [comment]
it is already avaiable, is it not appearing for you?
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/13333790-2bc4-4dbb-98eb-8fb9ccb4325b)

**Comment by ahsan3219** [comment]
Thanks for quick reply and may be as It's issue with my api key probably.

**Comment by PastaDeAmendoim** [comment]
It doesn't appear for me, I already repulsed the image in the portainer, and nothing changed.

**Comment by ahsan3219** [comment]
I think your api key do not have access of GPT-4o. Check on openai account
either you have access of GPT-4o or not...

**Comment by PastaDeAmendoim** [comment]
Working now , thx

**Comment by seonghobae** [comment]
How about Azure OpenAI GPT-4o models?

**Comment by pascalvallet** [comment]
I have the same issue, I created a new API key and I still have the same error message : Failed to add new Assistant: Error creating new assistant: Error: 400 The requested model 'gpt-4o' cannot be used with the Assistants API in v1. Follow the migration guide to upgrade to v2: https://platform.openai.com/docs/assistants/migration.

What should I do?

**Comment by pascalvallet** [comment]
I have a similar issue, my assistant in openAI or V2, flowise does not allow me to access the latest model.

![341052812-45ec0492-4acc-4317-ab87-a6571c27b61a](https://github.com/FlowiseAI/Flowise/assets/15332281/3e5129e4-aac7-4508-98bd-8eb42ed5b3a6)
