### ISSUE TITLE
[BUG] LocalAI Embedding and Upsert Vector Store The request protocol is different

### ISSUE THREAD

**Issue by Jacknolfskin** [FlowiseAI/Flowise#2420]
**Describe the bug**
ex：when Upsert Vector Store need {"model":"text2vec","input":["Llamas are members of the camelid family"]}

ex:  when  search Embedding need {"model":"text2vec","input":"Llamas are members of the camelid family"}

**To Reproduce**
when Upsert need input param as list
otherwise throw 422 Unprocessable Entity

![image](https://github.com/FlowiseAI/Flowise/assets/20827954/088afadc-8be5-452a-889e-2f90694c2c19)

**Comment by HenryHengZJ** [comment]
the errors are coming from the localai embedding model, not from flowise
