### ISSUE TITLE
Error when Upserting

### ISSUE THREAD

**Issue by avolel** [FlowiseAI/Flowise#2433]
Hello,

When upserting I am getting the following error.
![Flowise](https://github.com/FlowiseAI/Flowise/assets/6478781/e62ddc48-d7c5-48e4-873a-757b355272a5)
![Flowise-Console](https://github.com/FlowiseAI/Flowise/assets/6478781/37bc6997-96c9-47c7-988d-b86575db3e78)

When I change the Ollama Embeddings Base URL to http://localhost:11434/api/embeddings the error changes to a 404 error. Ollama is running and I can hit http://localhost:11434/api/embeddings using curl. What am I missing?

**Comment by HenryHengZJ** [comment]
Try turning on the `Use MMap` in Additional Config, should work

**Comment by urukalo** [comment]
i have the same issue, it seems that Ollama Embeddings is using GET method, but it must be POST
