### ISSUE TITLE
[FEATURE] Allow file uploads in embedded chat interface

### ISSUE THREAD

**Issue by mhjb** [FlowiseAI/Flowise#2444]
**Describe the feature you'd like**
In ChatGPT & the OpenAI Assistants Playground, I can upload attachments (where the model supports that)
I'd love it if I could do the same with Flowise's embedded chat widget?

**Additional context**
ChatGPT:
<img width="233" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/1380991/7f880af0-9bd0-4293-93de-b661eb6e8749">

**Comment by ksingh-scogo** [comment]
Agree, much needed feature. I am working on a chatbot solution where i need to accept images from the user and send these images with users text response over email. Capability of uploading images in Flowise chatUI is much needed.

**Comment by ingrivia** [comment]
any update on this?

**Comment by blissiraDC** [comment]
Also agreed, this is badly needed, and sorely missed. Also option for Text to speech input. Only having it available in share chatbot is missing a trick, thanks @HenryHengZJ for all your incredible work, this platform is by far the best already. Just a couple of tweaks here and there and its the ultimate monster! BUT you are still the AI god! I appreciate you!

**Comment by HenryHengZJ** [comment]
Closing as https://github.com/FlowiseAI/Flowise/pull/3059 merged!
