### ISSUE TITLE
[BUG]Unable to set environment variable: MODEL_LIST_CONFIG_JSON

### ISSUE THREAD

**Issue by musuiot** [FlowiseAI/Flowise#2447]
![image](https://github.com/FlowiseAI/Flowise/assets/58774718/7f8c8bb7-577e-44c8-ba55-e7b8713dcbfc)
I followed the instructions above to set the environment variables to no avail, I cannot find the file for the environment variables I set from the startup command. After startup, it will still be read from the network.
Here's how I set it up:
npx flowise start 
--MODEL_LIST_CONFIG_JSON=C:\Users\msrobot\AppData\Roaming\npm\node_modules\flowise\node_modules\flowise-components\models.json

**Comment by HenryHengZJ** [comment]
it has to be an online path like `https://s3-your-json-file.json`

**Comment by musuiot** [comment]
How can I use a local file?

**Comment by HenryHengZJ** [comment]
@musuiot made a PR to allow user specify local file path
