### ISSUE TITLE
[Q] - How to call a tool sequentially?

### ISSUE THREAD

**Issue by alfredtan** [FlowiseAI/Flowise#2449]
![call tool with chain](https://github.com/FlowiseAI/Flowise/assets/374446/e76edf8f-bf06-498e-96de-d74a747bc1ed)

Hi, 
I'm designing a flow where, given an input, the chain:

1.  does some basic thinking and structures an output
2. does a search on the internet (I want to call the Web Browser tool)
3. feeds BOTH output from steps 1 and 2 into the last chain for some final task

_Note: This is the initial flow and I might add more intermediary steps._

How do I achieve step 2 using a normal chain? I want to call a tool and pass on the result. It seems to be possible on Langchain via code. 

I've also looked at Agent but i'm not sure how to design the same thing, because I want to feed both (or more) steps into a final step. 

I'm new to Flowise and Langchain and may not have approached this correctly.

Thanks.

**Comment by alfredtan** [comment]
Hi hi, appreciate any help here, or, direct me to any resources for self-reading. thank you.

**Comment by HenryHengZJ** [comment]
You can now achieve using the sequential agents approach. An example flow:
![image](https://github.com/user-attachments/assets/560af7b4-8cc4-4752-946d-c1df20e896c9)
