### ISSUE TITLE
[FEATURE] Llama-cpp embeddings component

### ISSUE THREAD

**Issue by bsalexto** [FlowiseAI/Flowise#245]
**Describe the feature you'd like**
Add Llama-cpp embeddings component. 

**Additional context**
Coupling this feature and other local components (memory, vector stores, ChatLocalAI) would allow a complete local only solutions.

**Comment by owenJiao** [comment]
Looking forward to this feature very much.

**Comment by HenryHengZJ** [comment]
with LocalAI embedding node, you can now use llama.cpp embedding model - https://github.com/FlowiseAI/Flowise/pull/300

Docs - https://docs.flowiseai.com/embeddings/localai-embeddings

**Comment by bsalexto** [comment]
Thank you. I will try it out

**Comment by HenryHengZJ** [comment]
> @HenryHengZJ. Pretty cool. By the way, does LocalAI support any other embedding models, like [SentenceTransformers](https://www.sbert.net/).

you can refer to their model compatibility - https://localai.io/model-compatibility/index.html

will close this issue for now, feel free to open if there is any more question
