### ISSUE TITLE
[BUG] Credentials Not Persisting in Flowwise AI on Google Cloud Setup

### ISSUE THREAD

**Issue by BastiR40** [FlowiseAI/Flowise#2464]
We are experiencing an issue with Flowwise AI where API credentials for services like OpenAPI and Pinecode are not being persistently saved. These credentials seem to disappear after a certain period, requiring re-entry. This problem is occurring in a setup where Flowwise AI is deployed on Google Cloud using Cloud Run and Cloud SQL.

**Steps to Reproduce:**
1. Deploy Flowwise AI on Google Cloud using Cloud Run and Cloud SQL.
2. Add API credentials for services such as OpenAPI and Pinecode through the Flowwise AI interface.
3. Verify that the credentials are saved and operational - run a Flow.
4. Wait for a period (exact duration unknown, typically observed within a few minutes/hours).
5. Re-check the API credentials in the Flowwise AI interface.

**Expected Behavior:**
Credentials should remain saved and persist indefinitely unless explicitly removed or changed by the user.

**Actual Behavior:**
Credentials disappear after a certain period, and users must re-enter them to continue using the respective APIs.

**Environment:**
- Flowwise AI Version:** 1.7.2
- Deployment Platform: Google Cloud
  - Cloud Run
  - Cloud SQL
Like described here: https://medium.com/google-cloud-jp/securing-flowise-on-cloud-run-6ff0e1a70447

**Additional Information:**
- There are no error messages or logs indicating why the credentials are not being saved persistently.
- This issue affects the usability of the application as users need to re-enter credentials frequently.

Workaround:
Currently, there is no known workaround other than repeatedly re-entering the credentials.

Potential Causes:
- Possible misconfiguration in the Google Cloud setup.
- Issues with the Flowwise AI's credential storage mechanism - where their are stored?

Request for Assistance:
We would appreciate any guidance on resolving this issue to ensure that API credentials are saved persistently. If further information is needed, please let us know.

THX and best Sebastian

**Comment by automaton82** [comment]
Likely the container is cycling and when it does the folder containing the encryption key is lost.

You need to store the encryption key on a persistent volume not in the container.
