### ISSUE TITLE
[BUG] overrideConfig.systemMessage not overriding the original system prompt in Flowise

### ISSUE THREAD

**Issue by SikamikanikoBG** [FlowiseAI/Flowise#2465]
**Describe the bug**
When I pass through API the systemMessage parameter - nothing happens. overrideConfig.modelName is OK and it changes the model, but the system message is not changed.

**To Reproduce**

1. Go to 'Generate post API request to the Flowise chat'

{"question": "sup?",
"overrideConfig": {
  "sessionId": "email",
  "systemMessage": "Speak like a pyrate",
  "modelName": "llama2-uncensored"
    }}

2. Nothing changes in the answers:
{
	"text": "Sure, what do you want me to do for you?",
	"question": "sup?",
	"chatId": "email",
	"chatMessageId": "e43e7129-a485-425f-9ca3-4285c297cdd4",
	"sessionId": "email",
	"memoryType": "Buffer Window Memory"
}

**Expected behavior**
Normally the answer should reflect the instruction.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/46193504/19cf4534-3fef-430f-869f-a2687c27ae54)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation docker
-   Flowise Version 1.7.2
-   OS: Windows
-   Insomnia

**Additional context**

**Comment by HenryHengZJ** [comment]
its called `systemMessagePrompt`:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/1c1fe72e-5cd7-4041-9f0a-089a26c69f6d)

**Comment by SikamikanikoBG** [comment]
Thanks, it works!

I got confused by the documentations: https://docs.flowiseai.com/using-flowise/api

![image](https://github.com/FlowiseAI/Flowise/assets/46193504/8a0ec9f3-7044-45f2-8a9d-f7e92865557e)
