### ISSUE TITLE
[FEATURE] Please add RetrievalQAWithSourcesChain 

### ISSUE THREAD

**Issue by Gyro0o** [FlowiseAI/Flowise#247]
This would be very helpful to cite sources where the LLM got the informations from
To avoid hallucinations and double check every information 
Example: Citing the Wikipedia page, Which paragraph...

**Comment by HenryHengZJ** [comment]
Its now supported using ConversationalRetrievalQAChain - https://github.com/FlowiseAI/Flowise/pull/274
