### ISSUE TITLE
[BUG] When building Langgraph agents from scratch, Using tools with Langgraph workers results in Message Stopped -> Cannot concat object and undefined

### ISSUE THREAD

**Issue by zebathon** [FlowiseAI/Flowise#2472]
**Describe the bug**
The demos seem to work ok. However, when building from scratch adding Tools to worker nodes results in this error.
* In the UX the frontend reports 'Message Stopped'
* In langsmith, the Worker node is reporting 'Aborted'
* In langsmith, the RunnableAgent is reporting the 'Cannot concat...' message.

See below

**To Reproduce**
Follow the most basic steps to build an Agent workflow
1. Add 1 Supervisor, 1 Worker, 1 Chat model, and 1 Tool (calculator) all with default values. (Add explicit instructions for worker to use the tool)
2. Start the conversation with a simple 'calculate 5*5'
3. See error 'Message Stopped'
4. Look in Langsmith for root cause Aborted -> Cannot concatenate etc. etc.

**Expected behavior**
The agent flow should be complete.

When disconnecting the tool, AgentFlow proceeds.

**Screenshots**
![Screenshot 2024-05-23 at 4 46 16 PM](https://github.com/FlowiseAI/Flowise/assets/808626/9d7b615b-0a2b-4cf2-ad19-25df221b8a68)

**Flow**
[test Agents.json](https://github.com/FlowiseAI/Flowise/files/15425078/test.Agents.json)

**Setup**

-   Installation `npx flowise start`
-   Flowise Version  1.8.0
-   OS: macOS
-   Browser: chrome

**Additional context**
I've tried all types of Tools and Chat Models. Judging by the message I'm guessing it's a problem with either a null/undefinied input to the tool, or null output.

Cannot concat object and undefined

```
Error: Cannot concat object and undefined
    at concat (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/utils/stream.cjs:165:15)
    at ChatPromptTemplate.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:381:53)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatOpenAI.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:373:26)
    at async RunnableBinding.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:741:9)
    at async ToolCallingAgentOutputParser.transform (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:373:26)
    at async RunnableSequence._streamIterator (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1104:30)
```

**Comment by HenryHengZJ** [comment]
If you try modify the Worker prompt to something related to Math so that the Supervisor can correctly use the Worker, does it work?

**Comment by zebathon** [comment]
No luck with providing more Math related prompting. FWIW I've attached a langsmith screenshot of the worker invoking a Model with valid input (from the demos). And a 2nd screenshot (from the failing test) with no _input_data_ to the Model. Thus the model is never called by the worker without input data.
![Screenshot 2024-05-23 at 5 56 04 PM](https://github.com/FlowiseAI/Flowise/assets/808626/baf69d0b-7f98-4e49-9e82-72f38a3f378b)
![Screenshot 2024-05-23 at 5 55 41 PM](https://github.com/FlowiseAI/Flowise/assets/808626/54658687-759e-483f-a8cb-c84434fdd38e)

**Comment by zebathon** [comment]
I have the [trace](https://smith.langchain.com/public/5f58e0db-ea02-4267-9f5e-e57b5f099034/r) here

**Comment by brucechou1983** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/8468820/20854d7c-4b52-4abf-a072-95c83a6ff603)

Same here.

**Comment by mateusluizfb** [comment]
@HenryHengZJ same happening here. I asked the supervisor to return data, so it called a worker called "data-center" that has access to some custom tools that can perform a GET request. But I'm getting this error:

![Screenshot 2024-05-27 at 16 01 54](https://github.com/FlowiseAI/Flowise/assets/14284674/f4f6f622-37b0-4ce8-b259-d9852eb57068)

**Comment by eskimm** [comment]
Experiencing the similar issues. @HenryHengZJ can you elaborate how to craft prompts to have correct relationship between Supervisor/Workers? Or point to Langraph docs that describe correct use.

**Comment by rupjae** [comment]
reproduced.

**Comment by HenryHengZJ** [comment]
PR bugfix merged, will be pushing to new releases soon!

**Comment by HenryHengZJ** [comment]
can anyone confirm if the issue persists in v1.8.1 or resolved?

**Comment by zoltiskarel** [comment]
issue still persists on 1.8.1

**Comment by toi500** [comment]
Still bugged.

**Comment by toi500** [comment]
@HenryHengZJ still bugged.
