### ISSUE TITLE
Have to reload chatbot to access data from post api chain

### ISSUE THREAD

**Issue by coders21** [FlowiseAI/Flowise#2479]
Hi, i am using post api chain, which pass parameters to an api and get data, the data is huge but limited under the context, the issue is i am facing is that, it returns the data but have to reload the chatbot, first it gives error, on reloading it gives the data return from API, i want to access it without reloading , because it want the chatflow to use an api in my script and it causing issues.

here's below screenshot:

first it gives error
![error](https://github.com/FlowiseAI/Flowise/assets/72495373/0f0fe0b6-fced-40d6-8325-b0d9cfa8b4dc)

on reloading chatbot, it gives output
![resolve](https://github.com/FlowiseAI/Flowise/assets/72495373/716c83b7-39e3-48b5-be18-5850d83d5af6)

i want it to give output first time, because i want it to use as an api

![chatflow](https://github.com/FlowiseAI/Flowise/assets/72495373/a0143c35-4d5a-4e99-9644-6585913aba9e)

@HenryHengZJ any suggestions?

**Comment by HenryHengZJ** [comment]
Few suggestions:
1.) Try connecting separate ChatOpenAI, each for Agent and Chain
2.) Try OpenAPI Chain + Tool Agent (https://docs.flowiseai.com/use-cases/interacting-with-api)
