### ISSUE TITLE
[FEATURE] Add OPENAI_API_BASE to UI to enable usage oobabooga openai plugin

### ISSUE THREAD

**Issue by TheMasterFX** [FlowiseAI/Flowise#248]
**Describe the feature you'd like**
oobabooga Text-generation UI has a plugin which emulates the openAI API. But in the UI of Flowise it is not possible to set the URL of OpenAI. 
Setting the OPENAI_API_BASE via .env doesn't seem to work

**Comment by HenryHengZJ** [comment]
Do you have the link to the plugin?

**Comment by TheMasterFX** [comment]
> Do you have the link to the plugin?

It is build-in already: https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai

**Comment by heresandyboy** [comment]
Instead of running oobabooga to serve your local LLM, you can use LocalAI instead. It gives you an OpenAI compatible API based on whatever model you choose to run. If you set up LocalAI from the repo here:
https://github.com/go-skynet/LocalAI

Then you can use the Existing ChatLocalAI node in flowise:
See example here https://github.com/go-skynet/LocalAI/tree/master/examples/flowise

**Comment by HenryHengZJ** [comment]
@TheMasterFX with this PR merged - https://github.com/FlowiseAI/Flowise/pull/264 you can now specify a base path

**Comment by TheMasterFX** [comment]
> Instead of running oobabooga to serve your local LLM, you can use LocalAI instead. It gives you an OpenAI compatible API based on whatever model you choose to run. If you set up LocalAI from the repo here:
> https://github.com/go-skynet/LocalAI

As far as I can tell LocalAI doesn't seem to support GPTQ models (on GPU)

**Comment by heresandyboy** [comment]
> As far as I can tell LocalAI doesn't seem to support GPTQ models (on GPU)

Looking at the readme and build instructions on their github it looks like they have GPU support now, if still experiential, I'll try it out myself soon.

**Comment by Gavin-YYC** [comment]
[https://github.com/hwchase17/langchainjs/issues/1277](https://github.com/hwchase17/langchainjs/issues/1277)

**Comment by TheMasterFX** [comment]
Start oobabooga with 
`call python server.py --auto-devices --chat --wbits 4 --groupsize 128 --api --listen --extension openai`
Then enter the API url in the model in the UI http://127.0.0.1:5001/v1
However a LLMs might have different Keywords like "### Instruction:" or "User:"

**Comment by ill-yes** [comment]
> However a LLMs might have different Keywords like "### Instruction:" or "User:"

Where do find these keywords?
Any template-suggestions for some known LLMs? 🙏🏽

**Comment by TheMasterFX** [comment]
> > However a LLMs might have different Keywords like "### Instruction:" or "User:"
> 
> Where do find these keywords? Any template-suggestions for some known LLMs? 🙏🏽

This might be a good source: https://github.com/oobabooga/text-generation-webui/tree/main/instruction-templates

**Comment by ill-yes** [comment]
> This might be a good source: https://github.com/oobabooga/text-generation-webui/tree/main/instruction-templates

Thanks! Do you suggest any models + templates for flowise? I've tried a bunch of LLMs but none of them work as expected.

**Comment by jonmach** [comment]
> Instead of running oobabooga to serve your local LLM, you can use LocalAI instead. It gives you an OpenAI compatible API based on whatever model you choose to run. If you set up LocalAI from the repo here: https://github.com/go-skynet/LocalAI
> 
> Then you can use the Existing ChatLocalAI node in flowise: See example here https://github.com/go-skynet/LocalAI/tree/master/examples/flowise

I have a similar query.  I'm already using LM Studio as a local server, which gives me a load of models.  Why should it be necessary to download a completely new local server?  Also, if I want to host LM Studio on a completely different machine, I should only need to change the base_url.
