### ISSUE TITLE
Notion reader on large table times out after 30 seconds

### ISSUE THREAD

**Issue by vahidkowsari** [FlowiseAI/Flowise#2487]
**Describe the bug**
If I use a notion database node to get KB info from a table and vectorize into pinecone and the data on the notion database is large, clicking on the upsert button after exactly 30 seconds it responds back with a HTTP 504 Gateway timeout error.

Same table with Airtable doesnt have the same issue.

Using Docker deployed using cloudformation on AWS.

**To Reproduce**

1. Create a chat flow with notion table, pinecone and chat gpt chat for Q&A. Choose a DB in notion that is large and contains lots of rows.
2. Click on the upsert button
3. After 30 seconds get a timeout 504 popup and see the gateway timeout error.

**Expected behavior**
There shouldnt be any timeout and the data from the table should be vectorized into pinecone.

**Comment by AyushmanChatterjee** [comment]
Hi,

Facing the same issue using Apify Web Crawler or any other web crawler when the number of pages are a bit more. If the crawling and database upsert completes within approximately 30 seconds, then there is no such error.

**Comment by HenryHengZJ** [comment]
Somehow I think it is related to setup on AWS, are you able to reproduce locally?

**Comment by vahidkowsari** [comment]
Ah I think this is the culprit (in the AWS Cloudformation file)

```
PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ["-", [!Ref Stage, public-lb]]
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: "30"
```
