### ISSUE TITLE
[BUG] "stream.getReader is not a function" -> Any template

### ISSUE THREAD

**Issue by DgitalNarrative** [FlowiseAI/Flowise#249]
**Describe the bug**
After local installation with npm was able to run Flowise but when I test the first time, with the web browser template (raw, no editing unless adding the openAI key), by asking for some browser and retrieving answer I get a 500 Internal Server Error and "stream.getReader is not a function" on the chatbot window.

**To Reproduce**
Prompt example tested:
can you read all the information on https://nextjs.org/docs and let me know what are the main Next.js features?

**Screenshots**
<img width="1437" alt="Screenshot 2023-06-03 at 21 22 52" src="https://github.com/FlowiseAI/Flowise/assets/36340070/d19e8bb8-2736-457e-8865-0b503fcd3f6a">

**Setup**
MacOS
Browser Brave

Thank you

**Comment by HenryHengZJ** [comment]
are you on node >= 18.15.0?

**Comment by DgitalNarrative** [comment]
yep, on the 16.18.1 - is there any known issue above that?

**Comment by motin** [comment]
Had the same issue. Works after installing v18. It is necessary to remove node_modules and run yarn install using node v18 before it will work.

**Comment by DgitalNarrative** [comment]
that worked. Thanks

**Comment by DgitalNarrative** [comment]
Hi again. still getting the error "TypeError: stream.getReader is not a function" with node v20, and just updates flowise today.
Was testing the AutoGPT template. Thank you in advance for any help.

**Comment by DgitalNarrative** [comment]
Somehow, every time I restart vscode, my node version is switched to v16 on zsh. Apparently that was the cause, since I forced the use of v18 on the terminal and got it to work.

**Comment by chungyau97** [comment]
Hi @DgitalNarrative, highly recommend using NVM on managing your node versions.
https://github.com/nvm-sh/nvm
