### ISSUE TITLE
[BUG] Can't upload files. Please help to fix it.

### ISSUE THREAD

**Issue by Tom-Stanovsky** [FlowiseAI/Flowise#2491]
Probably it is easy to fix, I just don't see it. Thank you in advance. 
<img width="1338" alt="Screenshot 2024-05-26 at 12 28 42 AM" src="https://github.com/FlowiseAI/Flowise/assets/170845861/517ce396-c633-421a-b57c-b362b78f0c6f">

**Comment by 0xi4o** [comment]
Can you give more context here? Are you getting any error messages? It'll be helpful if you can add the steps to reproduce the issue.

**Comment by gsutton57** [comment]
I am having the same problem.  I try to upload a pdf.  When I do I get the message that it is successful but the popup says zeros all across showing zero documents uploaded and zero rejected etc. When I ask it about the document I get the same response, hmm I don't know.
