### ISSUE TITLE
Error: 404 No thread found with id '9098ea79-1853-467b-ac1d-5485078443c1'.[BUG]

### ISSUE THREAD

**Issue by vinayakhabbu** [FlowiseAI/Flowise#2495]
**Describe the bug**
Unable to clear the messsage generated in the bot.

**To Reproduce**

1. Build a OpenAI assistant flow
2. Link tools to google custom search 
3. Link moderation to openai moderation
4. Chat with the bot
5. Try clearing the message. 

**Expected behavior**
Older chat should be cleared.

**Screenshots**
Pls find attached.

[serverlog.docx](https://github.com/FlowiseAI/Flowise/files/15453061/serverlog.docx)
![Screenshot 2024-05-27 at 4 23 56 PM](https://github.com/FlowiseAI/Flowise/assets/1495625/cc6645f9-64a2-4257-85f7-a411df3bf40c)

**Comment by HenryHengZJ** [comment]
Is this consistent or random? If you try deleting the chatflow and create one again, are you able to reproduce?

**Comment by vinayakhabbu** [comment]
Its consistent. I duplicated the flow and this happened again. Thank you. Best Regards,Vinayak. On 1 Jun 2024, at 6:35 AM, Henry Heng ***@***.***> wrote:﻿
Is this consistent or random? If you try deleting the chatflow and create one again, are you able to reproduce?

**Comment by vinayakhabbu** [comment]
In the system prompt for the assistant, there is a message to create a .txt file. May be thats causing issue, not sure. "Save the final reviewed report as a .txt file. Provide the user with a downloadable link to the .txt file."

**Comment by HenryHengZJ** [comment]
Bugfix PR is merged, will be pushing to new release soon

**Comment by RitaVerissimo86** [comment]
Hi,

I actually have the same issue.
How to proceed to solve it?

Thanks,
R.

**Comment by David7Mejia** [comment]
having the same issue as above, connecting to an OpenAI Assistant throws a thread error

**Comment by ghbranding** [comment]
Same here in a specific chat.
![image](https://github.com/user-attachments/assets/5ea78a65-3368-4bd1-b971-c95b84665ebb)
Flowise version: 2.2.1

**Comment by saravanan-sekar** [comment]
I am encountering the following error. Please help me resolve the issue.


<img width="1496" alt="image" src="https://github.com/user-attachments/assets/8c5c708d-940d-4257-9443-6b93565dfdc1" />
