### ISSUE TITLE
In Memory Vector Store not working [BUG]

### ISSUE THREAD

**Issue by mikkelkrogsholm** [FlowiseAI/Flowise#2501]
Seems like the new docker image is messing up the vector store.

**Comment by toi500** [comment]
I have noticed this too when you try to upsert from the Plain Text node.

**Comment by SoundMindsAI** [comment]
I have seen this too.
I upserted a simple PDF and the In-Memory Vector store.  The error I am getting is:
Received tool input did not match expected schema

```

Error: Received tool input did not match expected schema
    at DynamicStructuredTool.call (/usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/tools.cjs:70:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/agents.js:315:39
    at async Promise.all (index 0)
    at async AgentExecutor._call (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/src/agents.js:302:30)
    at async AgentExecutor.invoke (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chains/base.cjs:58:28)
    at async ConversationalAgent_Agents.run (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/agents/ConversationalAgent/ConversationalAgent.js:119:19)
    at async utilBuildChatflow (/usr/local/lib/node_modules/flowise/dist/utils/buildChatflow.js:251:15)
    at async createInternalPrediction (/usr/local/lib/node_modules/flowise/dist/controllers/internal-predictions/index.js:7:29)
```

**Comment by SoundMindsAI** [comment]
Actually... The AgentExecutor is not required.  This is working for me.
The problem was that I was using the ConversationalAgent but the ToolAgent works better.

**Comment by SoundMindsAI** [comment]
> Actually... The AgentExecutor is not required. This is working for me. The problem was that I was using the ConversationalAgent but the ToolAgent works better.

I forgot to mention... I had previously switched over to a Pinecone DB rather than the in-memory Vector Store and was still getting this error message until I switched out the ConversationalAgent for the ToolAgent.  I have not tested this with the In-Memory Vector Store.

**Comment by toi500** [comment]
I think the team, following the LangChain initiative, is trying to standardize the tools. Some of these tools may become obsolete since they were built just for OpenAI.

Now, in theory, the tools should work for Gemini, Mistral, Clause, and OpenAI, but this is not always the case.

**Comment by drndos** [comment]
Same issue here, seems like reverting to 1.7.2 helped

**Comment by AlehandroL** [comment]
Same issue here.
I use: Tool Agent -> Retriever Tool -> In Memory Vector Store

In the chat window and in Langsmith I can see that output is returning empty. 
The issue **started before** updating from 1.7.2 to 1.8.0
<img width="956" alt="Captura de pantalla 2024-05-28 a la(s) 8 39 08 p  m" src="https://github.com/FlowiseAI/Flowise/assets/100784837/42fc0c8b-7dc9-4f18-b7de-3f889022b55d">

**Comment by trunghuynh228** [comment]
I have the same issue when using OpenAI Assistant. The chatbot cannot get the information from in-memory vector store at all. 1.8.0 is not working and I had to revert to 1.7.2

**Comment by automaton82** [comment]
Hi @HenryHengZJ can you have this one (and https://github.com/FlowiseAI/Flowise/discussions/2494 which I think is the same) looked at? I think something broke in 1.8.0 with RAG.

**Comment by SoundMindsAI** [comment]
Where can we find information on the RoadMap?
Would it be appropriate to include a Roadmap.md file?

Being new to Flowise, I’m not sure if this bug is something that should be
fixed or if there is a RoadMap direction that would mean that this should
never be fixed and that the preferred approach is X.

Do you have any documentation describing what should eventually be
consolidated based upon the direction of LaingChain?  I’m not even sure
what consolidation Langchain is working on anyway.  If someone wanted to
explain that would be great.  If someone does explain this might be a great
GitHub Discussion.

Thanks for your help!
Eric

**Comment by tiago-falves** [comment]
The In-Memory vector store is also not working for me!
![image](https://github.com/FlowiseAI/Flowise/assets/48015828/7ce49a37-4f87-482e-b5c6-74350ea47359)
I Have this workflow, I saved, upserted and then started a new chat. The model does not recognize any information I gave it in the pdf file.
What can I do to fix this?
Thank you very much!

**Comment by HenryHengZJ** [comment]
Will be pushing a new release with this fix soon!

**Comment by HenryHengZJ** [comment]
Pushed to `1.8.1`!

**Comment by automaton82** [comment]
Thanks!!
