### ISSUE TITLE
[FEATURE] Add support for GPT-4o model from Azure OpenAI

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2504]
**Describe the feature you'd like**
I would like Flowise to support the new GPT-4o model available on Azure OpenAI. This feature would allow users to integrate and utilize the capabilities of the GPT-4o model within the Flowise platform.

**Additional context**
The GPT-4o model has been recently released on Azure OpenAI, and it offers advanced capabilities that can enhance the functionalities provided by Flowise. Integrating this model would require updating the relevant code sections to support API calls to Azure OpenAI for the GPT-4o model. Detailed documentation and examples from Azure OpenAI can be referenced to facilitate this integration.

**Comment by thelokeshgoel00** [comment]
https://github.com/FlowiseAI/Flowise/pull/2402
I think it's already supported

**Comment by seonghobae** [comment]
> #2402 I think it's already supported

Not yet for Azure OpenAI.

**Comment by seonghobae** [comment]
It appears that the support for GPT-4o in FlowiseAI is due to the upstream update in the langchainjs repository. The issue [langchain-ai/langchainjs#5346](https://github.com/langchain-ai/langchainjs/issues/5346) discusses the addition of GPT-4o support, and it seems to have been resolved with a new version update. This upstream change likely enabled the GPT-4o support in FlowiseAI.
