### ISSUE TITLE
Metadata filtering via override config flowise parameters is retrieving answers from all collections rather than specified collection/namespace

### ISSUE THREAD

**Issue by anushvst** [FlowiseAI/Flowise#2505]
I made a web app where users upload a pdf file.

My flow is this. The user asks question in the next.js UI. The question is sent to backend in fastapi. The question is then sent via API to flowise and then flowise generates answer and sends to fastapi and to the UI. 

I understand but metadata filtering is a manual process from flowise. How can I send parameters via API to flowise from my backed like metadata for upserting and while retrieving how to set parameters while retrieving via backend code

currently via overriding flowise parameter, it is giving answers from other collections but not from a particular user collection

Frontend: Next.js
Backend: FastAPI
QA: Flowise AI
Database(relational and vector): PostgreSQL

**Comment by haimco50** [comment]
as far I know meta data fwith Postgres isn't supported yet  , alrraay created an issue on this :
https://github.com/FlowiseAI/Flowise/issues/2296 
@HenryHengZJ

**Comment by HenryHengZJ** [comment]
Closing as filter by metadata for Postgres is now supported - https://github.com/FlowiseAI/Flowise/pull/2674
