### ISSUE TITLE
[BUG] ERROR: first message must use the "user" role

### ISSUE THREAD

**Issue by haimco50** [FlowiseAI/Flowise#2516]
I keep getting an error message 'first message must use the "user" role message' evrery 4-5 chatbot interactions -  couldn't able to find any pattern why this happenning.

<img width="944" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/91170552/cf6d0fdf-1cf2-4c27-8b48-6b40e54e484c">

<img width="289" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/91170552/8f4e310e-d115-434e-a8aa-05a7d8e20fdc">

**Comment by haimco50** [comment]
forgot to mention - only way to "fix" it is by clearing the chat history and resend the user message again

**Comment by haimco50** [comment]
ok - I think I figured this out - this issue is originated from connecting  "buffer window memory" node with a size of 4....'when switching to a diffrent memory node ( I changed to Upstash Redis)  the issue is gone....so this could be a vaiable work around until this is fixed.

<img width="200" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/91170552/eb4f5623-0b90-4621-ae1c-414adf458ba5">

**Comment by HenryHengZJ** [comment]
yeah so what happens is that every 4-5 messages, buffer window memory will limit the size of messages to the specified size. For example:

```
user: hello
ai: hello
user: how are you
ai: im good
user: whats the weather
```

then, when you continue chatting, it will append another message like:
```
user: whats the weather
user: whats going on
```

since models like anthropic only accept messages that are taking turn, i.e: it must be followed by user or ai, after another, you cant have 2 consecutive messages with same user or ai roles.

**Comment by HenryHengZJ** [comment]
so by design, this is not solvable, other models like chatgpt, gemini, mistral dont have this constraint

**Comment by netgfx** [comment]
Is there a solution for this? even temporary or somehow to change how it responds? When used from the embedded chat on the flowise board it doesn't throw this error. But when I use React full-page embed it does

**Comment by HenryHengZJ** [comment]
Its now resolved as Anthropic Claude has removed this restriction.
