### ISSUE TITLE
[BUG] AgentFLow error

### ISSUE THREAD

**Issue by Gallisatyricon** [FlowiseAI/Flowise#2523]
**Describe the bug**
I tried the beta version of AgentFlow and as soon as I plug a tool in a worker node, the flow stop working. I tried many configurations and many tools, each time I have the same error. 

The error code as provide by LangSmith analyse is : 

> Aborted!
> 
> Error: Aborted!
>     at agentNode (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Worker/Worker.js:219:15)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async RunnableLambda.workerNode [as func] (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/multiagents/Worker/Worker.js:106:53)
>     at async /usr/local/lib/node_modules/flowise/node_modules/@langchain/core/dist/runnables/base.cjs:1337:34

**Setup**

-   Installation on azure 
-   Flowise Version 1.8.0
-   OS: Azure server
-   Browser Edge

I have absolutely no clue of why. If you understand my issue. Don(t hesitate to ask for mor details.

**Comment by ekelund** [comment]
Same here. As soon as a tool is added.
Green message down to the left in the browser: "Message stopped"
Machine: Mac Air M2
OS: MacOS Sonoma 14.3.1
Node: v20.11.1
Flowise ver: 1.8.0
Browser: Firefox 126.0 (64-bit)

**Comment by rupjae** [comment]
Can replicate.

**Comment by avfirsov** [comment]
Also has the same error

**Comment by HenryHengZJ** [comment]
PR bugfix merged, will be pushing to new releases soon!
