### ISSUE TITLE
[FEATURE] Support for SearxngSearch Tool in Flowise

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2525]
**Describe the feature you'd like**
I would like to kindly request the addition of support for the SearxngSearch tool in Flowise, similar to the support provided in Langchain.js. The SearxngSearch tool is highly beneficial for performing meta search engine queries using the SearxNG API. This functionality is particularly useful for retrieving information on current events and providing comprehensive search results.

**Additional context**
Langchain.js currently supports the SearxngSearch tool, enabling users to perform internet-connected agent and chain searches that yield a wide range of search results. By incorporating this feature into Flowise, users would gain access to enhanced search capabilities, thereby improving the overall utility and effectiveness of the platform. This addition would be greatly appreciated by the user community and would align Flowise with the advanced features available in Langchain.js.

**Comment by toi500** [comment]
@HenryHengZJ This would be very useful now that we are entering the era of Agent as a Service (AAAS) here on Flowise, powered by our LangGraph friends. 

BTW, thank you for taking the time to implement Exa Search. Another great addition.

**Comment by HenryHengZJ** [comment]
closing as https://github.com/FlowiseAI/Flowise/pull/2599 merged!
