### ISSUE TITLE
[BUG] LLM Chain Output Prediction goes to chat

### ISSUE THREAD

**Issue by DrFritzi** [FlowiseAI/Flowise#2527]
**Describe the bug**
"LLM Chains" that provide output for a "Chat prompt template" also output to the chat.

**To Reproduce**

1. Create a simple chatflow with a LLM Chain (set to Ouptut Prediction) and Conversation Chain (as in the screenshot).
2. Chat with the bot.
3. The bot will produce a message for each Chain.

**Expected behavior**
The bot only outputs the Conversation Chain output, as it did <1.8.0

**Screenshots**
![Screenshot 2024-05-30 092446](https://github.com/FlowiseAI/Flowise/assets/7989750/285069fa-d6fc-41c0-a197-1295f0ce3c4e)

**Flow**
[LLMChainBug Chatflow.json](https://github.com/FlowiseAI/Flowise/files/15495435/LLMChainBug.Chatflow.json)

**Setup**

-   Installation Docker (elestio/flowiseai:latest)
-   Flowise Version 1.8.0
-   OS: Windows
-   Browser Chrome

**Additional Context**
This worked in previous versions.

**Comment by HenryHengZJ** [comment]
Verified working with the PR bugfix:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/2596eaa1-a8d9-4592-8973-b8ce62a5c271)
