### ISSUE TITLE
[BUG] Failed to calculate number of tokens

### ISSUE THREAD

**Issue by taweijm** [FlowiseAI/Flowise#2529]
**Describe the bug**
I create agent using agentFlow with supervisor and 7 workers. When tested, the agent only send 1 message by 
Supervisor and stops.

**To Reproduce**

1. Create 1 supervisor and 7 workers
2. Add chatopenAI as tool calling chat  model on supervisor agent
3. try chatting

**Expected behavior**
The supervisor communicate with the worker and each workers run their job

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/105797032/9f92f311-0664-4d50-b7f7-6ad1f0cbb461)

**Setup**

-   Installation :  using docker in easypanel, command: sleep 3; flowise start
-   Flowise Version [1.8.0]
-   OS: [Linux ubuntu [22.04 LTS]
-   Browser [chrome]

**Comment by HenryHengZJ** [comment]
Should be resolved in 1.8.1, can you try and see?
