### ISSUE TITLE
[BUG] Can't delete chat messages (Error clearing chat messages)

### ISSUE THREAD

**Issue by artemdzyuba** [FlowiseAI/Flowise#2532]
**Describe the bug**
I played around with OpenAI Assistant node, adding tasks to my Notion BD. Suddenly I received a weird JSON reply from OpenAI. After that I can' clear the chat history.

I can't chat further, I receive a message like "Error: 404 No thread found with id '6dfb6ed3-5f6b-415f-a7a0-44cc1aa3a55e'."

**upd 1.** I duplicated the flow, and after few messages again can't delete them
**upd 2.** I duplicated again, removed the Assistant Node and added Tool Agent. After a bunch of messages again I can't clear them. It's annoying and I don't know what to do.

**To Reproduce**
I don't know how to reproduce that

**Expected behavior**
Chat history must be cleared

**Screenshots**
![error](https://github.com/FlowiseAI/Flowise/assets/20184727/77669574-8759-44d4-99f3-5779659ff073)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   docker
-   Flowise Version 1.8.0
-   Linux
-   Chrome

**Comment by HenryHengZJ** [comment]
Related https://github.com/FlowiseAI/Flowise/issues/2495

**Comment by HenryHengZJ** [comment]
Bugfix PR is merged, will be pushing to new release soon

**Comment by SCHAT-spec** [comment]
Hi is this bug fixed, I am still getting this error

**Comment by JCvfi** [comment]
I have the same situation on the latest image

**Comment by inacios777** [comment]
I'm experiencing the same issue as shown in the image. I've already created other agents, restarted, and redeployed, but it didn't solve the problem
