### ISSUE TITLE
Adding Custom OpenAi Base URL variable to the chat model node and the LLM node. [FEATURE]

### ISSUE THREAD

**Issue by amrpyt** [FlowiseAI/Flowise#2547]
Adding Custom OpenAi Base URL variable to the chat model node and the LLM node

**Comment by HenryHengZJ** [comment]
You can find the `Base Path` from the node:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/a6d81575-1a83-43e2-97b9-d2e900372cc1)
