### ISSUE TITLE
[BUG] Retriever Tool called with parameter 'query' instead of 'input' - Received tool input did not match expected schema (Reproducible!)

### ISSUE THREAD

**Issue by AlehandroL** [FlowiseAI/Flowise#2552]
**Describe the bug**
Under specific conditions, a Tool Agent can call a Retrieval Tool with a “query” parameter (instead of “input”, as defined in its schema), causing an error “Received tool input did not match expected schema”.

**To Reproduce**
It happens kind of randomly, but following these steps I was finally able to replicate it:

1. Create a chatflow using the exported Flow below.
2. Fill Nodes with your own OpenAI and Pinecone credentials
3. Save
4. Type in chat "tienen tortas de naranja?"  (this translates to "do you have orange cakes?", I don't know why but it always get it done)

**Expected behavior**

The chat should display the error message “Received tool input did not match expected schema”.

When you check the trace using LangSmith, the call to ChatOpenAI should show an output calling the Tool product_information with “query: torta de naranja” (note it uses "query" instead of the normal "input").

![image](https://github.com/FlowiseAI/Flowise/assets/100784837/28bb3947-8e5d-48ee-bdc0-f4a0df7fe8f2)

![image](https://github.com/FlowiseAI/Flowise/assets/100784837/481be824-c5fe-4e80-8846-e4a911732285)

**Flow**

[Bot Volcán Pastelería Chatflow.json](https://github.com/user-attachments/files/15523949/Bot.Volcan.Pasteleria.Chatflow.json)

**Setup**

-   Installation: docker
-   Flowise Version 1.8.1
-   OS: macOS
-   Browser: chrome

**Additional context**

Trying to reproduce this bug, it seems to be associated with several factors:

	1.	Having a custom tool with a schema different from “input”.
	2.	The custom tool being described before the retrieval tool is called.
	3.	The Tool Agent having multiple Retrieval Tools.

It appears that GPT-4o gets confused with the different schemas, and since the description of the “input” parameter for retrieval tools mentions that it is a “query,” it ends up calling the tool with the “query” parameter instead of “input.”

Since this seems to be an issue stemming from the model’s ability to follow a schema, a possible fix would be to allow it to look for the “query” parameter in the absence of “input” for the retrieval tools.

**Comment by chungyau97** [comment]
Hi @AlehandroL, I don't really understand the problem you're facing and I can't replicate it.

- In [LangSmith ](https://github.com/FlowiseAI/Flowise/blob/272fd914bd1dc826ad6abeb32df37407db3cb659/packages/components/nodes/analytic/LangSmith/LangSmith.ts#L23) our code 9 months ago we already using "inputs".
- In [Retriever Tool](https://github.com/FlowiseAI/Flowise/blob/272fd914bd1dc826ad6abeb32df37407db3cb659/packages/components/nodes/tools/RetrieverTool/RetrieverTool.ts#L66) our code 4 months ago we already using "inputs".

This is my chatflow: 
- [issues_2552 Chatflow.json](https://github.com/user-attachments/files/15533733/issues_2552.Chatflow.json)

These are my sample data:
- [Bill Gates.txt](https://github.com/user-attachments/files/15533740/Bill.Gates.txt)
- [Elon_Musk.txt](https://github.com/user-attachments/files/15533741/Elon_Musk.txt)

Results:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/9dbb0b6e-20f8-42ef-b90b-294ae5c21d8c)
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/d95e0091-ca3b-48d4-b516-248b35acb93c)


Could you share your custom tool to me? so I can debug further.

**Comment by HenryHengZJ** [comment]
Some other community member bumped into this issue as well. In short, gpt-4o doesnt quite follow the function calling input.

Here's the solution:
"Tool Agent + gpt4o, where it would sometimes use "query" as input key, where the system expects "input" as input key. The solution for me was adding: `Please ensure that when calling this tool, the input key MUST always be "input".` to each tool description and adding `When calling any tool, the input key MUST always be "input".` to the priming instructions on Tool Agent. Hope this helps for you as well."

**Comment by AlehandroL** [comment]
> Some other community member bumped into this issue as well. In short, gpt-4o doesnt quite follow the function calling input.

This is the problem I tried (poorly) to describe. 

The solution on the side of descriptions seems to work in many cases, but I think you could try to catch this error and try to look for the “query” parameter in the output of the LLM. I know it’s not ideal, but considering that GPT-4 today is (arguably) the most popular model, it’s worth considering a solution for this issue.

@HenryHengZJ

**Comment by HenryHengZJ** [comment]
added a potential fix - https://github.com/FlowiseAI/Flowise/pull/2679, closing for now
