### ISSUE TITLE
DOCKER INSTALLATION ERROR

### ISSUE THREAD

**Issue by gamercoder153** [FlowiseAI/Flowise#2553]
I followed all cmds for installation through docker 

[https://docs.flowiseai.com/getting-started#docker](url)

when I run `docker-compose up -d`  Iam getting this error `no configuration file provided: not found`

**Comment by toi500** [comment]
did you rename the `.env.example` to  `.env` in the docker folder?

https://github.com/FlowiseAI/Flowise?tab=readme-ov-file#docker-compose

**Comment by gamercoder153** [comment]
Yeah did it @toi500

**Comment by toi500** [comment]
Then the error you are getting it because you are in the incorrect folder. You need to execute the `docker-compose up -d` inside the docker folder, where the .env file is.

**Comment by gamercoder153** [comment]
Yeah I did that one too and its fixes Now, Iam having issues with building local docker image

**Comment by toi500** [comment]
I just installed it locally without problem with Docker Desktop 4.30.0 (149282)

--
<img width="905" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/138339291/93c6430a-fb29-42a3-9a56-04baada74268">

**Comment by gamercoder153** [comment]
@toi500 I was getting a bit of trouble btw don't worry I installed it on WSL
