### ISSUE TITLE
[BUG] Websearch tool not responding

### ISSUE THREAD

**Issue by codenamics** [FlowiseAI/Flowise#2555]
**Describe the bug**
Agents websearch does not get response

**To Reproduce**
Create agent flow 

**Expected behavior**
LLM response

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/26750398/daacf14f-c79b-4faf-9e98-f16c2b4a809e)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation npx
-   Flowise Version lataest
-   OS: Windows
-   Browser chrome

**Comment by toi500** [comment]
This happened to me sometimes too. I do not the cause of this or what is the default max interations of the Agent Toot, but it you set the interations, for example, to 2, it should works.

**Comment by codenamics** [comment]
thanks that worked
