### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by last-Programmer** [FlowiseAI/Flowise#2556]
Hi,

How to upload html documents for RAG.

Thank you in advnace.

**Comment by toi500** [comment]
Hi there. 
What is the point to do this? The more clean a document is the best results you get from the RAG.

Here are all the loaders on Flowise:
https://docs.flowiseai.com/integrations/langchain/document-loaders

**Comment by last-Programmer** [comment]
@toi500 thank you for the reply. We have 1000s manual pages written using robohelp and have our manual as html files and we are using azure open ai at present and for this and they allow uploading html files. we have pdf loader which is more complex in nature than a html files. it would be nice if we have html loader.

I managed to do it in flowise by doing this

![image](https://github.com/FlowiseAI/Flowise/assets/1324600/e4eda753-feb3-44ee-9131-80f2bb7750c3)


Is this right way to do ...but the output is in markdown. so not getting proper result for question i ask. But it is stripping down all the tags. thats good to start with.

Having a html file uploader and text splitter for this would be nice addition to the existing loader.

Thanks

**Comment by toi500** [comment]
@last-Programmer I got it now.

As you mentioned, Flowise currently lacks an HTML loader or an HtmlToText splitter. However, these could be useful additions for handling bulky data ingestion tasks.

Having a look to the LangChain documentation, they recoment the use [Unstructured.io](https://github.com/Unstructured-IO/unstructured) for HTML files: https://js.langchain.com/v0.1/docs/integrations/document_loaders/file_loaders/unstructured/

And that can be done by using [Unstructured Folder Loader node](https://docs.flowiseai.com/integrations/langchain/document-loaders/unstructured-folder-loader).

**Comment by HenryHengZJ** [comment]
@last-Programmer you can use the latest document store for more visiblity of the chunks to be upserted
