### ISSUE TITLE
ChatOpenAI Connection error

### ISSUE THREAD

**Issue by wywself** [FlowiseAI/Flowise#2558]
**Describe the bug**
After using chatopenai and configuring the correct key, a connection error is reported. As shown below:
![image](https://github.com/FlowiseAI/Flowise/assets/8843053/c1edb014-7cdb-46f0-858f-6814615e3877)

**Setup**

-   Installation `pnpm start`
-   Flowise Version: `1.8.1`
-   OS: `Windows`
-   Browser: `chrome`
![image](https://github.com/FlowiseAI/Flowise/assets/8843053/39af067b-02ea-45d9-8762-c127c618d2e6)

**Comment by chungyau97** [comment]
Hi @wywself,

I am not able to replicate your error.

![image](https://github.com/FlowiseAI/Flowise/assets/33013947/575c81f4-96f5-4e89-ab84-81be52a1c6b5)

**Comment by wywself** [comment]
Hi @chungyau97 ,

I'm sure my openai key is available. But I don't know the reason for the connection error.

![image](https://github.com/FlowiseAI/Flowise/assets/8843053/8293a629-96ba-414f-bf28-10d5528922f5)

**Comment by chungyau97** [comment]
Hi @wywself, does it happen randomly or always like this?

Could you look into this?
[APIConnectionError](https://platform.openai.com/docs/guides/error-codes/python-library-error-types)

**Comment by zzzzsdsdasdasda111274** [comment]
我也是这样的，希望作者能有时间研究一下，国外用户关于GPT的调用，我能确保我的API和代理VPN都是正常使用的，十分感谢作者

**Comment by wywself** [comment]
Hi @chungyau97 ,

it always "Connection error", as shown in the issue, none of them succeeded. Thank you.

**Comment by HenryHengZJ** [comment]
this should be resolved by adding the proxy url: https://github.com/FlowiseAI/Flowise/pull/3153
