### ISSUE TITLE
Add support for Couchbase as a vector store by upgrading Docker

### ISSUE THREAD

**Issue by prajwal-pai77** [FlowiseAI/Flowise#2560]
Can we please have support for Docker builds to use glibc based distro so that we can have support for Couchbase as a vectore? Current Docker builds using Alpine on Arm64 and is incompatible with the Couchbase SDK, as our SDK does not currently support Alpine + Arm64 due to its reliance on musl instead of glibc.

Context: https://github.com/FlowiseAI/Flowise/pull/2303#issuecomment-2100446029

**Comment by HenryHengZJ** [comment]
Thanks @prajwal-pai77, we have this item in our to-do list, since changing the current alpine requires thorough testing of all the integrations in Flowise

**Comment by HenryHengZJ** [comment]
Merged: https://github.com/FlowiseAI/Flowise/pull/3093
