### ISSUE TITLE
Folder with Files - Folder Path not found (no such file or directory)

### ISSUE THREAD

**Issue by JuliaZamaitat** [FlowiseAI/Flowise#2562]
**Describe the bug**
I have the application running locally with Docker and built a Document Chatbot Flow. Working fine with single .txt files, but as soon as I am trying to add other document sources I am lost because Flowise can't seem to find the paths I am providing under "Folder Path", giving the error: _Error: ENOENT: no such file or directory,_

I am sure the directory exists and tried local folders as well as folders synced with OneCloud. I cannot find any documentation for how the Folder Path is supposed to look like or what I am missing, so any help would be appreciated.

**Expected behavior**
I expect the folder to be found.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/33123853/db8840be-ec25-4300-9e35-8417b76a100b)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation docker-compose up -d
-   flowise/1.8.0 win32-x64 node-v20.14.0
-   OS: Windows 10 Enterprise
-   Browser: Edge

**Comment by danieldabate** [comment]
Hi @JuliaZamaitat, are you referencing local paths? I see you are using docker, so you would need to mount those folders as volumes into the container and reference the path inside the container, not in your local filesystem.

Alternatively you can add those files in the `~/.flowise` local folder, which is already being mounted to the container under `/root/.flowise`. In the node, you would need to reference `/root/.flowise/yourfilesfolder`.

More info [here](https://docs.docker.com/storage/volumes/#use-a-volume-with-docker-compose).

**Comment by JuliaZamaitat** [comment]
Thank you, @danieldabate! I totally didn't think about that! Now it works like a charm. Thanks a lot :)
