### ISSUE TITLE
Suggestion Button

### ISSUE THREAD

**Issue by ahsan3219** [FlowiseAI/Flowise#2564]
I want to implement rule-based chatbot in Flowise like that has button option at the end of the bot reply and based on the button click bot moves to next step.

**Comment by HenryHengZJ** [comment]
Better to move this to Dicussion page

**Comment by rohanprasadsap** [comment]
Any update on this?. I am trying to make chatbot where at the end of the step, the human is directed to confirm/reject based on which it will decide what flow it will follow next
