### ISSUE TITLE
[BUG] Error when trying to save a new or existing assistant

### ISSUE THREAD

**Issue by acoffin76** [FlowiseAI/Flowise#2570]
**Describe the bug**
I receive the following message when trying to save a new or existing assistant

Failed to save Assistant: Error: assistantsService.updateAssistant - Error updating assistant - retrievedAssistant.file_ids is not iterable

**To Reproduce**
Go to assistants
- Edit existing assistant
or
- Create and try to save a new assistant

**Expected behavior**
Changes should save

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/147885114/5c64c00b-81b2-494e-8454-ce59223c424f)

**Flow**

**Setup**

-   Installation `pnpm start`
-   Flowise Version - Not sure.  Last sync was on 5/21
-   OS: Linux
-   Browser Chrome

**Additional context**

**Comment by danieldabate** [comment]
You can see Flowise version if you click on the "gear" icon at the top right on the main screen and go to "About Flowise".

**Comment by acoffin76** [comment]
Thanks.  I’m on version 1.7.2. On Jun 4, 2024, at 8:36 AM, danieldabate ***@***.***> wrote:﻿
You can see Flowise version if you click on the "gear" icon at the top right on the main screen and go to "About Flowise".

**Comment by acoffin76** [comment]
Any updates on this?

**Comment by acoffin76** [comment]
I recloned the code and the issue is no longer occurring.
