### ISSUE TITLE
Adding a gitlab repoloader

### ISSUE THREAD

**Issue by AnjaSimons** [FlowiseAI/Flowise#2574]
As you have a nice Github repoloader, please clone this and modify this for a github repoloader with the same features as github.

**Comment by HenryHengZJ** [comment]
are u looking for this - https://docs.flowiseai.com/integrations/langchain/document-loaders/github ?

**Comment by AnjaSimons** [comment]
The github documentloader url is hardcoded in langchain, so it only accepts https://github.com. So if I try to use https://gitlab.example.com/.... the url-format is rejected. And I tried the github with a gitub repository, and got the error
"Error:vectorsService.upsertVector -Error 500 rpc error: code = Unavailable Desc = error reading from Server". So it seems, it is not really successful.
