### ISSUE TITLE
[BUG] nginx request size limit

### ISSUE THREAD

**Issue by biellil** [FlowiseAI/Flowise#2582]
even put FLOWISE_FILE_SIZE_LIMIT= 200mb and it still gives an error

Failed to process chunking: <html> <head><title>413 Request Entity Too Large 413 Request Entity Too Large nginx/1.18.0 (Ubuntu) a padding to disable MSIE and Chrome friendly error page a padding to disable MSIE and Chrome friendly error page  a padding to disable MSIE and Chrome friendly error page  a padding to disable MSIE and Chrome friendly error page  a padding to disable MSIE and Chrome friendly error page  a padding to disable MSIE and Chrome friendly error page  
![imagem_2024-06-04_185712639](https://github.com/FlowiseAI/Flowise/assets/78098857/8bda6b26-5327-4117-9fc1-085fbbf03acb)

**Comment by danieldabate** [comment]
Can you share more information about how you are running Flowise? 

It seems like you have an nginx in the middle acting as a reverse proxy and the error is not related to Flowise, you should change the configuration of that nginx.

**Comment by biellil** [comment]
> Can you share more information about how you are running Flowise?
> 
> It seems like you have an nginx in the middle acting as a reverse proxy and the error is not related to Flowise, you should change the configuration of that nginx.

So do you think it is the reverse proxy that is giving the error?

**Comment by danieldabate** [comment]
Hard to be 100% sure without having more info about your setup. If you have an nginx acting as a reverse proxy (which it seems because of the error you are getting), then yes, it's definitely it.

More info: https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by biellil** [comment]
> Hard to be 100% sure without having more info about your setup. If you have an nginx acting as a reverse proxy (which it seems because of the error you are getting), then yes, it's definitely it.
> 
> More info: https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

it worked to increase nginx request limit, now it's another error lol
![imagem_2024-06-04_193210443](https://github.com/FlowiseAI/Flowise/assets/78098857/1f202882-2691-4c7e-bda6-d7adb9faa6dd)

**Comment by danieldabate** [comment]
Have you tried to increase FLOWISE_FILE_SIZE_LIMIT, now that the nginx issue is fixed?

We can play this guessing game all day, but it's not fun. So I'll need all the info you can give me about your setup to help you 😅   
- What size is the file you are loading? 
- What is your current FLOWISE_FILE_SIZE_LIMIT config? 
- Apart from the nginx, do you have any loadbalancer, reverse proxy or middleware between you and Flowise?
- Where are you running Flowise? Docker, K8S, something else?

**Comment by zhaoyong5555** [comment]
Hello, I have encountered a problem：Failed to process chunking: request entity too large
1.If I upload too many files, this error will occur, but if I merge these files into one file, the error will be resolved
2.I have tried to modify the parameter FLOWISE-FILE-SIZE-LIMIT=5000mb so that I won't encounter any errors, but my documentstore's vector knowledge base shows that the number of uploaded chunks is 0
3.I ran it using this command：docker-compose up -d
I hope you can help me see if that file can modify the maximum number of uploaded files. Thank you
