### ISSUE TITLE
[BUG] ChatFlowTool using wrong URL depending on infrastructure setup

### ISSUE THREAD

**Issue by danieldabate** [FlowiseAI/Flowise#2584]
**Describe the bug**
Under special infrastructure setups, ChatFlowTool is trying to use a different or wrong URL which leads to a network failure and no answer by the tool.

An example of this is the following setup:
`Browser` --HTTPS--> `AWS ALB` --HTTP--> `Flowise`

The expected URL to execute would be:
https://someurl.com/path

But the executed URL is:
http://someurl.com/path

Which leads to a failure if HTTPS is enforced in the ALB. There might be more complex scenarios where the URL might also change.

**Expected behavior**
There is no expected behavior really, the code works fine. I just want to discuss this issue and propose a solution to make it more flexible.

I can think about different solutions:
* Adding an optional ENV variable "FLOWISE_BASE_URL" to make this base url configurable. Default would be current behavior.
* Adding an optional field to the ChatFlowTool called Base URL. Default would be current behavior.

Approach 1 covers the issue in a more global and central way, but it's not really clear to understand why changing "FLOWISE_BASE_URL" could affect the ChatFlowTool.

Approach 2 is more direct and clear to understand, but every ChatFlowTool added needs to be changed with the right URL.

I would love to get your thoughts on how to tackled this. Thanks!!

**Comment by HenryHengZJ** [comment]
We're getting the `baseURL` like this: `${req.protocol}://${req.get('host')}`
https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/utils/buildChatflow.ts#L57

Does the `req.protocol` changed behind load balancer?

**Comment by danieldabate** [comment]
I saw that code. 

The host header is passed from the LB to Flowise because its part of the request context, but the protocol is not. The protocol depends on the communication to Flowise, in this case from the LB. Communication between the browser and the LB is unknown to Flowise. 

That's when things get mixed up.

In environments without any middleware, like testing locally, current logic works just fine.

**Comment by HenryHengZJ** [comment]
you are right, `req.protocol` becomes `http` when its behind a proxy/load balancer. 

it seems like we can get the protocol from header `x-forwarded-proto`: https://stackoverflow.com/questions/9024783/how-to-force-node-js-express-js-to-https-when-it-is-running-behind-an-aws-load-b

what we can do is first check if the hearder exsits, if yes use that as priority over `req.protocol`. And we can also add an additional field to the node for user to specify the full URL base path like `http://localhost:3000/api/v1`

**Comment by danieldabate** [comment]
Sounds great! Good find, I didn't know about that http header.

I'll submit a pull request as soon as I have some free time.

Thanks!!

**Comment by HenryHengZJ** [comment]
what if we do something like this:
```
export const getBaseURL = (protocol: string, host: string, headers: ICommonObject) => {
    // Check if apps behind load balancer
    if (headers['x-forwarded-proto'] && headers['x-forwarded-proto'] === "http" && !host.includes('localhost')) {
        protocol = 'https'
    }
    if (headers['X-Forwarded-Proto'] && headers['X-Forwarded-Proto'] === "http" && !host.includes('localhost')) {
        protocol = 'https'
    }

    return `${protocol}://${host}`
}
```

Then use it like:
```
const baseURL = getBaseURL(req.protocol, req.get('host') ?? '', req.headers)
```

Theoretically we should just call the `utilBuildChatflow`, but `components` level nodes don't have access to `server` level functions

**Comment by danieldabate** [comment]
I'd try not make any assumptions in code about the infrastructure configuration. A load balancer could also be accessible through HTTP. I submitted a PR that should be generic enough to solve the original issue. I'd release this changes to fix current flow which is broken.

Regarding my concern about security issues, as long as we use `req.get('host')` users will be able to redirect the call to other services. So I'd suggest to avoid using and trusting the host header.

I can open a new issue for this topic if it makes more sense.

**Comment by bradfair** [comment]
if it's helpful, i've seen applications deal with the x-forwarded headers by having allow lists in the app config. it could specify the allowed hosts and a default host, the forwarded protocol, and the forwarded port. that way it has enough info to determine a safe way to build a full url. it also specify a list of proxy addresses/hostnames that are known to be valid. strip those away from the x-forwarded-for header and if you have one address left, it should be the address of the original requester (i.e. the end user). that might make it easier to deal with proxy setups, vs "number of proxies".

**Comment by danieldabate** [comment]
> if it's helpful, i've seen applications deal with the x-forwarded headers by having allow lists in the app config. it could specify the allowed hosts and a default host, the forwarded protocol, and the forwarded port. that way it has enough info to determine a safe way to build a full url. it also specify a list of proxy addresses/hostnames that are known to be valid. strip those away from the x-forwarded-for header and if you have one address left, it should be the address of the original requester (i.e. the end user). that might make it easier to deal with proxy setups, vs "number of proxies".

Thanks! This approach works if we think having something dynamic is better. Another approach I've seen is the one I shared in my first message, letting the user specify the host in the app config and having a default like 127.0.0.1. I'm not sure if the `baseURL` is being used by other nodes or functionalities, so I don't know if either of each approach is better.

What I still don't see is why the ChatFlowTool needs to handle it dynamically, because it's just an "internal" communication that needs to happen. For this particular case, I'd default to `127.0.0.1:port` and let the user optionally override it in the node, instead of using the `baseURL` that comes from the context.
