### ISSUE TITLE
[BUG] Can't seem to upsert

### ISSUE THREAD

**Issue by 17lxve** [FlowiseAI/Flowise#2588]
**Describe the bug**
I get a "TypeError: Cannot read properties of undefined (reading '0')" each time i try to do an upsert

2024-06-05 16:38:04 [ERROR]: [server]: Error: Error: TypeError: Cannot read properties of undefined (reading '0')
Error: Error: TypeError: Cannot read properties of undefined (reading '0')
    at buildFlow (C:\dev\Flowise\packages\server\dist\utils\index.js:493:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async upsertVector (C:\dev\Flowise\packages\server\dist\utils\upsertVector.js:115:32)
    at async Object.upsertVectorMiddleware (C:\dev\Flowise\packages\server\dist\services\vectors\index.js:9:16)
    at async createInternalUpsert (C:\dev\Flowise\packages\server\dist\controllers\vectors\index.js:29:29)

**To Reproduce**
1. Create a chatflow
2. Add elements as seen in screenshot
3. Save
4. Upsert
5. Save

![image](https://github.com/FlowiseAI/Flowise/assets/71525684/dbe928ff-efb1-4920-a45f-46283f662dd3)

Here is a screenshot of my chatflow
I tried using Chroma, In-Memory Vector Store, MongoDB Atlas, Pinecone, PostgreSQL and Redis as Vector Stores, but got the same error everytime.

Tried swapping the embeddings too, same thing.
I tried on my MSI and Lenovo laptops, a Debian Virtualbox VM, and an Ubuntu Server VPS,

First install was done via npm, second install via git, same result

Flowise version is 1.8.1
Node version: tried 18.20.3 & 20.14.0

**Setup**

-   Installation: npm i -g flowise; npx flowise start
-   Flowise Version: 1.8.1
-   OS: Windows, Linux(Debian/Ubuntu)
-   Browser: Chrome, Brave

**Comment by Sdegraauw** [comment]
are there any files in the folder?

**Comment by 17lxve** [comment]
yes, @Sdegraauw , 4 PDFs

**Comment by 17lxve** [comment]
Quick update: Reducing the amount of documents works. Increasing the chunk size also works. So it might be a situation where upserting too much info in small chunks causes the error. What to do? i got like 200 more files to put in that folder

**Comment by HenryHengZJ** [comment]
If you use the new document store PDF Loader does it work? You can upload multiple PDFs in one go:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/3f03abd0-072b-4390-a22e-d4353cac5cc7)
