### ISSUE TITLE
External Post call to upsert API with form data doesn't replace or add file

### ISSUE THREAD

**Issue by Sdegraauw** [FlowiseAI/Flowise#2590]
**Describe the bug**
External Post call done in ASP.net to the upsert API done with MultipartFormDataContent doesn't replace or add file.
the upsert does happen but with the file that was uploaded in the chatflow edditor.

**To Reproduce**
1. upload file into an IFormFile in ASP.
2. use the folowing function to do the post request: [HttpPost]
public async Task<IActionResult> Index(IFormFile file)
{

    HttpClient client = new HttpClient();
    using (var content = new MultipartFormDataContent())
    {
        byte[] fileBytes = new byte[file.OpenReadStream().Length];
        await file.OpenReadStream().ReadAsync(fileBytes, 0, (int)file.OpenReadStream().Length);
        ByteArrayContent bytes = new ByteArrayContent(fileBytes);

        content.Add(bytes, "files", file.FileName);
        Console.WriteLine(await content.ReadAsStringAsync());

        var response = await client.PostAsync("http://localhost:3000/api/v1/vector/upsert/fe443d55-fdde-4c6d-88f6-1c40d14c49e3", content);
        var responseString = await response.Content.ReadAsStringAsync();

        Console.WriteLine(responseString);
    }

    return View();
}

**Expected behavior**
an upsert response with the data from the uploaded file should be printed in console.

**Screenshots**
![old](https://github.com/FlowiseAI/Flowise/assets/144223601/55a251da-1917-4066-b185-83df4f5a1b21)
![new](https://github.com/FlowiseAI/Flowise/assets/144223601/fd0099ec-8580-4af6-b91b-3f9ce4339ba3)
![new](https://github.com/FlowiseAI/Flowise/assets/144223601/e505b7cf-dbd2-47d1-a3d0-7af6c1953c0e)
![Controler method](https://github.com/FlowiseAI/Flowise/assets/144223601/b4aa954e-96f3-4e96-a343-210342fd5383)

**Flow**
[Faiss Chatflow (1).json](https://github.com/user-attachments/files/15614718/Faiss.Chatflow.1.json)

**Setup**

-   Installation `npx flowise start --DEBUG=true`
-   Flowise Version 1.8.0
-   OS: Windows 10
-   chrome

**Comment by HenryHengZJ** [comment]
not sure if this is related to the ASP.net code, but if you try using Python or Postman to make the calls, it should work:
https://docs.flowiseai.com/using-flowise/api#document-loaders-with-upload

**Comment by Yakiw** [comment]
> **描述在 ASP.net 中对使用 MultipartFormDataContent 完成的 upsert API 进行的外部发布调用的错误** ，不会替换或添加文件。upsert 确实发生了，但使用的是 chatflow 编辑器中上传的文件。
> 
> **复制**
> 
> 1. 将文件上传到 ASP 中的 IFormFile 中。
> 2. 使用以下函数执行发布请求： [HttpPost] 
>    public async Task Index(IFormFile file) 
>    {
>    HttpClient 客户端 = new HttpClient();
>    使用（var content = new MultipartFormDataContent()）
>    { 
>    byte[] fileBytes = new byte[file.OpenReadStream().Length];
>    等待 file.OpenReadStream().ReadAsync(fileBytes， 0，（int）file.OpenReadStream().Length); 
>    ByteArrayContent 字节 = new ByteArrayContent(fileBytes);
>    ```
>     content.Add(bytes, "files", file.FileName);
>     Console.WriteLine(await content.ReadAsStringAsync());
>    
>     var response = await client.PostAsync("http://localhost:3000/api/v1/vector/upsert/fe443d55-fdde-4c6d-88f6-1c40d14c49e3", content);
>     var responseString = await response.Content.ReadAsStringAsync();
>    
>     Console.WriteLine(responseString);
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    }
>    返回视图（）；
>    }
> 
> **预期行为是，** 应在控制台中打印包含上传文件数据的 upsert 响应。
> 
> **截图** ![老的](https://private-user-images.githubusercontent.com/144223601/337253176-55a251da-1917-4066-b185-83df4f5a1b21.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDgwNTIsIm5iZiI6MTcyMTAwNzc1MiwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjUzMTc2LTU1YTI1MWRhLTE5MTctNDA2Ni1iMTg1LTgzZGY0ZjVhMWIyMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjJmZTg4YzVmZDMxMGQ1ZjBkY2Q4ZmVkOThmZGI4ZTIzZmFlZjhhNTc2ZGMyZDI2ODE1NjY0MzBiNmQ1YjdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zbL6uKdbBQBxREKbjM95WpXzmVrEM_mDgHWyqREl-RU) ![新的](https://private-user-images.githubusercontent.com/144223601/337253334-fd0099ec-8580-4af6-b91b-3f9ce4339ba3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDgwNTIsIm5iZiI6MTcyMTAwNzc1MiwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjUzMzM0LWZkMDA5OWVjLTg1ODAtNGFmNi1iOTFiLTNmOWNlNDMzOWJhMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODFjNzZkYTEyODcyNmI3NGI4MjEyYjY5NDhkNjlhMGU4YjU1M2U4ZmRjOWNmMTI5ODQxMmFlYjExNGNiOTQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nvsfAdpnzpq6Li_BsbF6hRIziUg2H4VbOllMnu_Rn6Q) ![新的](https://private-user-images.githubusercontent.com/144223601/337256133-e505b7cf-dbd2-47d1-a3d0-7af6c1953c0e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDgwNTIsIm5iZiI6MTcyMTAwNzc1MiwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjU2MTMzLWU1MDViN2NmLWRiZDItNDdkMS1hM2QwLTdhZjZjMTk1M2MwZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzY3MWU1OTRjMTdlNGJlN2RlMDBjOWE3Mjc5MmRhMDA2YTIyZTJlMTEwZWQzNDM5ZmQ0YjYxY2I1MGJhMmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LYc11e4stS_VPxy2rHTnM84Bv47EVxVkb-UkiJLy-Og) ![控制方法](https://private-user-images.githubusercontent.com/144223601/337253458-b4aa954e-96f3-4e96-a343-210342fd5383.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMDgwNTIsIm5iZiI6MTcyMTAwNzc1MiwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjUzNDU4LWI0YWE5NTRlLTk2ZjMtNGU5Ni1hMzQzLTIxMDM0MmZkNTM4My5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwMTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYzQxMDYwZmFlNDc4NTk5MzcxNTIwYWY0YjI3N2EwNDkzOGY4NjJlNGM1ZDFiY2Y2MjcyMGQyMzY0ZWI2NWUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UliWadB4BgpOtsRdfnrXtDeGwVeewkCnAqRj_GHv7Fs)
> 
> **Flow ** [Faiss Chatflow (1).json](https://github.com/user-attachments/files/15614718/Faiss.Chatflow.1.json)
> 
> **设置**
> 
> * 安装`npx flowise start --DEBUG=true`
> * Flowise 版本 1.8.0
> * 操作系统：Windows 10
> * 铬合金

same problem!!!!

**Comment by Yakiw** [comment]
> **描述在 ASP.net 中对使用 MultipartFormDataContent 完成的 upsert API 进行的外部发布调用的错误** ，不会替换或添加文件。upsert 确实发生了，但使用的是 chatflow 编辑器中上传的文件。
> 
> **复制**
> 
> 1. 将文件上传到 ASP 中的 IFormFile 中。
> 2. 使用以下函数执行发布请求： [HttpPost] 
>    public async Task Index(IFormFile file) 
>    {
>    HttpClient 客户端 = new HttpClient();
>    使用（var content = new MultipartFormDataContent()）
>    { 
>    byte[] fileBytes = new byte[file.OpenReadStream().Length];
>    等待 file.OpenReadStream().ReadAsync(fileBytes， 0，（int）file.OpenReadStream().Length); 
>    ByteArrayContent 字节 = new ByteArrayContent(fileBytes);
>    ```
>     content.Add(bytes, "files", file.FileName);
>     Console.WriteLine(await content.ReadAsStringAsync());
>    
>     var response = await client.PostAsync("http://localhost:3000/api/v1/vector/upsert/fe443d55-fdde-4c6d-88f6-1c40d14c49e3", content);
>     var responseString = await response.Content.ReadAsStringAsync();
>    
>     Console.WriteLine(responseString);
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    }
>    返回视图（）；
>    }
> 
> **预期行为是，** 应在控制台中打印包含上传文件数据的 upsert 响应。
> 
> **截图** ![老的](https://private-user-images.githubusercontent.com/144223601/337253176-55a251da-1917-4066-b185-83df4f5a1b21.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTg3NjQsIm5iZiI6MTcyMTAxODQ2NCwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjUzMTc2LTU1YTI1MWRhLTE5MTctNDA2Ni1iMTg1LTgzZGY0ZjVhMWIyMS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNDQxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGNiYTAzODI0NDk4ODhkOTJmMzg4NjYwMDJjYmRmMGZjZDMzM2UwZDU2MjI1Y2VmMTk5MmQyMTJkYzhiMDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XANUviWDNnE6gMLpu5knfpLLPuLXse59lKqx7z8cGS4) ![新的](https://private-user-images.githubusercontent.com/144223601/337253334-fd0099ec-8580-4af6-b91b-3f9ce4339ba3.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTg3NjQsIm5iZiI6MTcyMTAxODQ2NCwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjUzMzM0LWZkMDA5OWVjLTg1ODAtNGFmNi1iOTFiLTNmOWNlNDMzOWJhMy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNDQxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDc0Zjg3ZmI5NjZkMzc4NTYyYzEwZTZjYzI3MGNiMDlhNzUwY2EyNmU5ZjdhYWQyMTBlM2RjM2QzN2Q3NjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EjNTs5Us7u0m3iI_kiJQ3BNYgQD5BhL4_iy163glzqI) ![新的](https://private-user-images.githubusercontent.com/144223601/337256133-e505b7cf-dbd2-47d1-a3d0-7af6c1953c0e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTg3NjQsIm5iZiI6MTcyMTAxODQ2NCwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjU2MTMzLWU1MDViN2NmLWRiZDItNDdkMS1hM2QwLTdhZjZjMTk1M2MwZS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNDQxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWU2MTk4MjIxYTNjZDAzZGRmMmY2YmNiNDY0NmRhMjkwZWUyNjlmMzQzOWJkMWUzYzY1OTA4ZjQzYTg4ZmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-7V4aOuU9t1aErMJ8Tl1CIWidzO3dUn9CCxBGtkhV44) ![控制方法](https://private-user-images.githubusercontent.com/144223601/337253458-b4aa954e-96f3-4e96-a343-210342fd5383.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTg3NjQsIm5iZiI6MTcyMTAxODQ2NCwicGF0aCI6Ii8xNDQyMjM2MDEvMzM3MjUzNDU4LWI0YWE5NTRlLTk2ZjMtNGU5Ni1hMzQzLTIxMDM0MmZkNTM4My5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNDQxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjNjN2FlNzU0ZjkyMDE2NjIzZjIyMDY1NjI4ZjA3Y2FlZmVlYjJhNGJhNTU1ZWJiZWI1NGY0MjVjNzFiZjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.O3eRAhbMf8UYDEPsRqJ-PMKEgcq1E7_QIiJARHxNgZ0)
> 
> **Flow ** [Faiss Chatflow (1).json](https://github.com/user-attachments/files/15614718/Faiss.Chatflow.1.json)
> 
> **设置**
> 
> * 安装`npx flowise start --DEBUG=true`
> * Flowise 版本 1.8.0
> * 操作系统：Windows 10
> * 铬合金

have u solved this problem?

**Comment by HenryHengZJ** [comment]
We have 2 new APIs that should solve the problemn: https://docs.flowiseai.com/using-flowise/api#document-upsert-refresh-api
