### ISSUE TITLE
If I cannot use OpenAI, which model should I use?

### ISSUE THREAD

**Issue by javawangzi** [FlowiseAI/Flowise#2603]
Hi
I can not access openai/chatgpt, but I want follow, study, practice flowise demos, which LLM can I use?
Because my pc don't have good performance, So I can't use Langchain+ollama also.
Could anyone give some suggestions?
BR,

**Comment by eloimarquessilva** [comment]
I'm using ChatGoogleGenerativeAI. You can get your API Key for free via Google AI Studio https://ai.google.dev/aistudio?hl=pt-br

**Comment by javawangzi** [comment]
Hi @eloimarquessilva 
Thanks your reply, I base in China, and also can not use Google  :(  
BR,

**Comment by HenryHengZJ** [comment]
You can try Groq, HuggingFace, Replicate, TogetherAI, Fireworks, plenty of options beside OpenAI. Closing this for now as its better suited for Discussion
