### ISSUE TITLE
asking workflow to begin I get "message stopped"

### ISSUE THREAD

**Issue by webbywebb** [FlowiseAI/Flowise#2608]
**Describe the bug**
When I tell my team to build something, I immediately get 'Message Stopped' error

**To Reproduce**
1. I created the software development team in the demo app exactly
2. Setup my OpenAI API key per the video
3. I tell the system to 'build me a to-do list app'
4. I get the Message Stopped error.

**Expected behavior**
Messages in the window telling the supervisor to get to work.

**Screenshots**

**Flow**
I'm a newbie, so I expect that I missed something and this is my fault.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   flowise/1.8.1 darwin-x64 node-v20.14.0
-   2.3 GHz Quad-Core Intel Core i5 Mac running Sonoma 14.5
-   Browser Chrome

**Additional context**
I searched for 'Flowise error "message stopped" but found nothing. I deleted the flow and started over based on how that fixed another error someone was having, but that did not help.

**Comment by toi500** [comment]
Check this https://github.com/FlowiseAI/Flowise/issues/2557#issuecomment-2148208490

**Comment by HenryHengZJ** [comment]
moving to #2557

**Comment by Syed-Faizal-S** [comment]
[Chat_model Agents.json](https://github.com/user-attachments/files/17975279/Chat_model.Agents.json)


can anyone check this model ,the supervisor calls the worker ,the worker doesnt respond
