### ISSUE TITLE
[BUG] Error: Expected a Runnable, function or object.

### ISSUE THREAD

**Issue by javawangzi** [FlowiseAI/Flowise#2610]
Hi

when I follow up with youtube demo, a error occured. like below.
Flowise is 1.8.1
![image](https://github.com/FlowiseAI/Flowise/assets/50722329/562f9fc5-a0bf-4fe5-ba26-6fcf08444371)
![image](https://github.com/FlowiseAI/Flowise/assets/50722329/1e2e1551-96bb-4806-a70f-dea1de9320c5)

BR,

**Comment by HenryHengZJ** [comment]
Should be able to work, try this 
[Vector Upsert Chatflow.json](https://github.com/user-attachments/files/15795179/Vector.Upsert.Chatflow.json)

**Comment by HenryHengZJ** [comment]
you can load it from the top right:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/02f8a732-6939-46ab-8dfd-85d47966ed9b)
