### ISSUE TITLE
Help in building self improving chains

### ISSUE THREAD

**Issue by gamercoder153** [FlowiseAI/Flowise#2611]
I am familiar with most of the flowise. I want the LLM chains to improve over time. For example, if the first chain generates an output, the second chain will review it and decide whether the quality of the output is high or not. After the second chain, there will be an if-else block. If the output of the first chain is of high quality, the if-else block triggers the 'true' chain. If the output is not high quality, false chain is triggered, which will add improvements to the first chain and rerun from the start.

**Comment by HenryHengZJ** [comment]
coming soon!

**Comment by gamercoder153** [comment]
@HenryHengZJ waiting for it eagerly

**Comment by HenryHengZJ** [comment]
now possible via sequential agentic workflow! https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.0.0

**Comment by gamercoder153** [comment]
@HenryHengZJ I'm running flowise on a Debian machine, installed using the command `npm install -g flowise`. I attempted to update using `npm update -g flowise`, but it didn't work.

![fgdgdfghfh (1)](https://github.com/user-attachments/assets/b960eee5-5d53-41c7-88bf-fbafbc350105)
