### ISSUE TITLE
[FEATURE] Sort by Feedback from Chat

### ISSUE THREAD

**Issue by 4rr0wx** [FlowiseAI/Flowise#2621]
**Describe the feature you'd like**
I really love the Feedback feature in Flowise. But it would be very helpful if you could sort by, for example, only negative feedback. Furthermore, an export feature only for the feedback messages would be great. This helps to find the improvement points where you can improve your chatflow by seeing all the negative feedback from the users.

**Comment by HenryHengZJ** [comment]
PR merged - https://github.com/FlowiseAI/Flowise/pull/2869
