### ISSUE TITLE
[BUG] Custom tool is not working

### ISSUE THREAD

**Issue by OtrisX** [FlowiseAI/Flowise#2623]
**Describe the bug**

**To Reproduce**
Try using any custom tool, it never returns anything.

**Expected behavior**
Return the value defined by the custom tool in the javascript function.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/105071011/741e55fc-faf0-4d60-bd7e-205172cc84d8)
![image](https://github.com/FlowiseAI/Flowise/assets/105071011/b25efdc1-f9aa-4d1f-91a3-085d0c1b8454)
![image](https://github.com/FlowiseAI/Flowise/assets/105071011/e16c2809-d1d3-43f5-bcdb-01614ff3ea86)

**Flow**
[test1 Chatflow.json](https://github.com/user-attachments/files/15793036/test1.Chatflow.json)

**Setup**

-   Installation docker swarm
-   Flowise Version 1.8.1
-   OS: Debian 12 bookworm

**Comment by HenryHengZJ** [comment]
Try Tool Agent - https://docs.flowiseai.com/use-cases/webhook-tool#flowise

**Comment by patrickreinan** [comment]
@HenryHengZJ I think we need to change the default SYSTEM MESSAGE from Coversational Agent, because it is only a descriptive text. 

@OtrisX try to change the SYSTEM MESSAGE for a "You are a helpful assistant.", for example, and try again.

**Comment by TMBMode** [comment]
Is this issue solved? I still can't get custom tools working on non-OpenAI models

**Comment by alwynkhiuzh** [comment]
The issue still there. Is there any solution?

**Comment by gauravkaliadev** [comment]
Does the custom tool support non-OpenAI models? it's not working for me either.
