### ISSUE TITLE
[BUG] Socket.io Streams send "end" event before continuing to answer with "token" events. 

### ISSUE THREAD

**Issue by officialgoat** [FlowiseAI/Flowise#2629]
**Describe the bug**

I'm connecting to Flowise by using to socket.io streaming API. I have the "token" and "end" events wired up and I close the socket when the "end" event is received. 
Normally this works fine, but when I use the Function Calling agent I first receive a few empty tokens (""), then I receive an "end" event and after that (if I ignore that event) I start to receive the actual answer tokens of the agent. 

**To Reproduce**

![image](https://github.com/FlowiseAI/Flowise/assets/35045518/a8439842-3423-42da-8870-29f568c88bc3)

- Set up the streaming API with socket.io as described in the documentation. 
- Set breakpoints to the "token" and "end" events so they can be monitored
- Open the socket and send the query with the socket.io id as described in the documentation.
- Ask a question (in the query) that will cause the tool to be used (for example "search your database for exercises about English literature").
- First some empty token strings ("") should be received, then an "end" event and then the answer token strings of the flow.

**Expected behavior**

The socket connection should be started, "token" events containing the answer strings should be sent. After finishing an "end" event should be sent. 

**Flow**

[bug-chatflow Chatflow.json](https://github.com/user-attachments/files/15802396/bug-chatflow.Chatflow.json)

**Setup**

-   Installation: official docker image from docker.hub
-   Flowise Version: 1.8.1
-   OS: wsl/docker
-   Browser: streaming api/edge

**Comment by HenryHengZJ** [comment]
We now changed to using Server Side Event! https://docs.flowiseai.com/using-flowise/streaming
