### ISSUE TITLE
How to Clear 'asked question' history

### ISSUE THREAD

**Issue by Chunyfong** [FlowiseAI/Flowise#263]
![image](https://github.com/FlowiseAI/Flowise/assets/50175081/b39228b5-56ef-4369-a8a6-7d2674d724f3)

I was wondering how to clear the history log whenever i mouse over the 'Type your question' Thanks !

**Comment by HenryHengZJ** [comment]
strange I've never had that pop up

**Comment by goldzulu** [comment]
I remember seeing this popup sometime ago but couldn't recall under what condition. What is your browser and  OS  @Chunyfong and what was  the content of your chatflow? Was streaming on in the chat?

**Comment by Chunyfong** [comment]
I am having trouble with some popups that keep appearing on my Window 11 and Chrome 114.0.5735.110 while trying to make a demo for my team using Flowise. 

These popups are some of the questions I asked when I first installed Flowise, and I can't seem to get rid of them ever since lol. Even if I try to use incognito mode, clean my history, or start a new blank flow without any content, the popups still appear when I click on my chat.

**Comment by derekcheungsa** [comment]
I think you just have to turn-off autofill in Chrome

**Comment by Chunyfong** [comment]
@derekcheungsa 
> I think you just have to turn-off autofill in Chrome

Yes! That's correct ! the popout gone now, It looks like Chrome treated it as address data, Silly me
