### ISSUE TITLE
[BUG] 502 error after 1.8.2 update

### ISSUE THREAD

**Issue by artemdzyuba** [FlowiseAI/Flowise#2631]
**Describe the bug**
After update to 1.8.2, my instance went down with a 502 error

**To Reproduce**
1. Update 1.8.1 -> 1.8.2:
```
cd Flowise/docker
docker compose down
docker compose up -d
```
2. Refresh the page

**Setup**

-   docker-compose
-   1.8.1
-   Linux
-   chrome, safari

**Additional context**
A discord user experienced the same and suggested to edit **docker-compose.yml**:
delete/comment out this line: `command: /bin/sh -c "sleep 3; flowise start"`
This worked ✔

**Comment by danieldabate** [comment]
Hi! This is expected, not a bug. The docker compose file changed also in 1.8.2 and you should update it accordingly.

**Comment by artemdzyuba** [comment]
> Hi! This is expected, not a bug. The docker compose file changed also in 1.8.2 and you should update it accordingly.
> 
> Also, if you are using "latest" as your Docker image tag (or no tag), I'd highly encourage you to use a specific version as tag to avoid this type of issues happening automatically.

Thank you. It's was completely unclear from the Release info. After your reply, I search it and found this bug fix https://github.com/FlowiseAI/Flowise/pull/2563, which looks to be the issue. And this doesn't contain any mention that I have to alter my docker-compose.yml or I'll get an error.

**Comment by HenryHengZJ** [comment]
thanks @artemdzyuba, updated release for that - https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.8.2
