### ISSUE TITLE
[FEATURE] Session ID Tracking for Agent flow supervisor

### ISSUE THREAD

**Issue by oleke** [FlowiseAI/Flowise#2640]
The agent flow currently lacks a means of keeping track of the user sessions and a persistent memory of contexts based on different user sessions.

It will be important to add a means of sessionId tracking just like we have in the chatflow.

**Comment by HenryHengZJ** [comment]
Now you can use Agent Memory for agentflow:
![image](https://github.com/user-attachments/assets/8a91d6bb-958f-4cff-8c43-91b44d7a964b)

**Comment by timur-nocodia** [comment]
how to override session id using Agent memory to slit up the users?
