### ISSUE TITLE
[BUG] blank response on chat UI

### ISSUE THREAD

**Issue by rupjae** [FlowiseAI/Flowise#2641]
**Describe the bug**
After some run's of a flow using the build in Chat functionality the chat functionality suddenly breaks. When clicking on Chat a blank html page comes up. 

**Expected behavior**
chat working consistently

**Screenshots**
its an empty html body

**Flow**
this happened across chains, simple and complex flows as well as agents. 

**Setup**

-   npx flowise start
-   Flowise Version 1.8.1
-   OS: MacOS
-   Browser Safari

**Additional context**
[Error] Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btool_uses%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Uf — index-DhDV0W-n.js:60:12811
_ — index-DhDV0W-n.js:60:17868
Bn — index-DhDV0W-n.js:62:1478
UE — index-DhDV0W-n.js:62:45770
BE — index-DhDV0W-n.js:62:39793
E4 — index-DhDV0W-n.js:62:39721
np — index-DhDV0W-n.js:62:39573
jv — index-DhDV0W-n.js:62:35937
$E — index-DhDV0W-n.js:62:34886
P — index-DhDV0W-n.js:47:1602
ee — index-DhDV0W-n.js:47:1971

	Pv (index-DhDV0W-n.js:62:167)
	(anonymous function) (index-DhDV0W-n.js:62:390)
	aS (index-DhDV0W-n.js:60:9892)
	kS (index-DhDV0W-n.js:62:32063)
	LE (index-DhDV0W-n.js:62:31482)
	S4 (index-DhDV0W-n.js:62:31032)
	T4 (index-DhDV0W-n.js:62:40923)
	Ia (index-DhDV0W-n.js:62:40281)
	$E (index-DhDV0W-n.js:62:35191)
	P (index-DhDV0W-n.js:47:1602)
	ee (index-DhDV0W-n.js:47:1971)

**Comment by rupjae** [comment]
while I didn't figure out the actual problem I did resolve it by nuking .flowise
I presume something has been written somewhere that did result in the above.

**Comment by rupjae** [comment]
while I didn't figure out the actual problem I did resolve it by nuking .flowise
I presume something has been written somewhere that did result in the above.

**Comment by cuonvyaobianbai** [comment]
Hi @rupjae 
I'm facing the same issue here. Are u saying u delete all the files under ~/.flowise?

**Comment by hipotures** [comment]
After clearing ~/.flowise nothing has changed. Any flow, even with 1-2 nodes, gives a blank html page. Only for a while, by saving the flow it is possible to start a chat, but has input is inactive. 

@cuonvyaobianbai 

EDIT: Solution:
1. install nvm
2. nvm install 20
3. nvm use 20
4. npm install -g flowise 
(added 2847 packages in 12m)
5. npx flowise start 
or if you have busy port 3000
npx flowise start --PORT=3333

Remember that after that, every start must be preceded by the command
1. nvm use 20
2. npx flowise start

**Comment by brolag** [comment]
> After clearing ~/.flowise nothing has changed. Any flow, even with 1-2 nodes, gives a blank html page. Only for a while, by saving the flow it is possible to start a chat, but has input is inactive.
> 
> @cuonvyaobianbai
> 
> EDIT: Solution:
> 
> 1. install nvm
> 2. nvm install 20
> 3. nvm use 20
> 4. npm install -g flowise
>    (added 2847 packages in 12m)
> 5. npx flowise start
>    or if you have busy port 3000
>    npx flowise start --PORT=3333
> 
> Remember, every start must be preceded by the command
> 
> 1. nvm use 20
> 2. npx flowise start

Worked for me, thanks!
