### ISSUE TITLE
Question [BUG]

### ISSUE THREAD

**Issue by JossBossUK** [FlowiseAI/Flowise#2650]
**Describe the bug**
server-error.log gives the message "Output of LLM Chain (llmChain_0) must be LLM Chain, can't be an Output Prediction" but the LLM chain output is set to LLM output. I think this may be a configuration issue not a bug.

**To Reproduce**
Click on the Bot and send a question. There is no response. 

**Expected behavior**
I would not expect this error message as the LLM chain is not set to Output Prediction. 

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/172941460/08da5991-2d9f-45cb-8d0c-bd12fbc4fa45)

**Flow**
n/a

**Setup**

-   Installation [VC, `pnpm start`]
-   Flowise Version [e.g. 1.8.1]
-   OS: [macOS]
-   Browser [safari]

**Additional context**
I also get a connection error " at async createInternalPrediction (/Users/ianjoscelyne/TestVCfolder/Flowise/Flowise/packages/server/dist/controllers/internal-predictions/index.js:7:29)
2024-06-15 19:01:39 [ERROR]: [server]: Error: Connection error.
Error: Connection error.
" maybe these two issues are related?

**Comment by HenryHengZJ** [comment]
Might be a glitch, try create a new flow, it should works no?

**Comment by JosProm** [comment]
I traced the problem down to my VPN connection allowing access to websites but not allowing commands such as ping and curl to work. Changing the vpn app fixed the problem
