### ISSUE TITLE
[BUG] Updated, now Docker container stuck in infinite loop

### ISSUE THREAD

**Issue by themeaningofmeaning** [FlowiseAI/Flowise#2651]
I updated to the most version from the last and now my Docker container gets stuck in an infinite loop after starting the container returning `"Error: Unexpected arguments: /bin/sh, -c, sleep 3; flowise start"` over and over in the logs.  I've never had an issue up until now.
<img width="983" alt="Screenshot 2024-06-15 at 10 03 19 PM" src="https://github.com/FlowiseAI/Flowise/assets/5422554/fe2130eb-143f-4e2c-924e-a0a14aa1a710">

Here is my Dockerfile:
```
FROM node:18-alpine

USER root

RUN apk add --no-cache git
RUN apk add --no-cache python3 py3-pip make g++
# needed for pdfjs-dist
RUN apk add --no-cache build-base cairo-dev pango-dev

# Install Chromium
RUN apk add --no-cache chromium

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# You can install a specific version like: flowise@1.0.0
RUN npm install -g flowise

WORKDIR /data

CMD "flowise"

```

**Comment by pgaurav007** [comment]
hi @themeaningofmeaning , replace this line in docker-compose file:

    entrypoint: /bin/sh -c "sleep 3; flowise start"
instead of 
 command: /bin/sh -c "sleep 3; flowise start"

**Comment by themeaningofmeaning** [comment]
> entrypoint: /bin/sh -c "sleep 3; flowise start"
> ```
> 
> instead of command: /bin/sh -c "sleep 3; flowise start"

That did the trick, thank you!
