### ISSUE TITLE
Add record manager to Agents Interface

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#2652]
**Describe the feature you'd like**
Langchain Record Managers are great for RAG workflows, but for whatever reason they aren't part of the Agents UI.

Why not? 
Can we have also have record managers with Agents?

**Additional context**

![image](https://github.com/FlowiseAI/Flowise/assets/135163019/d2232fc9-9046-4280-9203-f4750bd2a394)

**Comment by toi500** [comment]
You can always use the Chatflow Tool and call your RAG from the Agentflow.

**Comment by dentro-innovation** [comment]
Yes that's a solution, although for most applications I prefer to keep all nodes in the same UI.

**Comment by HenryHengZJ** [comment]
Record Manager are used for upserting embeddings, whereas agentflow is for querying results

Is there any example use case why we would need record manager here?

**Comment by dentro-innovation** [comment]
Perhaps I'm building my flows wrong.

 Before being able to query the embeddings using the agent flow, I need to upsert them as you said.

I always do this using the Flowise doc store in the same flow as where I'm querying.

Where do you normally upsert your embeddings? In a separat flow? I would imagine this could become quite messy when you have a lot of flows no?

**Comment by toi500** [comment]
I used to do it the same way you do it, but a while back I started using upserts like this, keeping my RAGs clean. In my opinion, what Flowise currently lacks is a project management feature where you could group flows into folders. Easier said than done, though.

![capture_240619_230643](https://github.com/FlowiseAI/Flowise/assets/138339291/a182bb12-652b-439c-9f04-b3e3af63481a)

**Comment by HenryHengZJ** [comment]
document store :)
https://docs.flowiseai.com/using-flowise/document-stores
