### ISSUE TITLE
[BUG] ChatOllama Function not reading/parsing outputs from tools.

### ISSUE THREAD

**Issue by snailbrainx** [FlowiseAI/Flowise#2653]
When using Ollama Function with custom tools and retrieval tool, the script cannot continue because it fails to parse the results.

here is an example:

`{
  "input": "how are liverpool doing?",
  "steps": [
    {
      "action": {
        "tool": "get_club_id",
        "toolInput": {
          "input": "Liverpool FC"
        },
        "toolCallId": "",
        "log": "Invoking \"get_club_id\" with {\"input\":\"Liverpool FC\"}\n",
        "messageLog": [
          {
            "lc": 1,
            "type": "constructor",
            "id": [
              "langchain_core",
              "messages",
              "AIMessage"
            ],
            "kwargs": {
              "content": "",
              "tool_calls": [
                {
                  "name": "get_club_id",
                  "args": {
                    "input": "Liverpool FC"
                  }
                }
              ],
              "invalid_tool_calls": [],
              "additional_kwargs": {
                "function_call": {
                  "name": "get_club_id",
                  "arguments": "{\"input\":\"Liverpool FC\"}"
                },
                "tool_calls": [
                  {
                    "id": "1718574102499",
                    "type": "function",
                    "function": {
                      "name": "get_club_id",
                      "arguments": "{\"input\":\"Liverpool FC\"}"
                    }
                  }
                ]
              },
              "response_metadata": {}
            }
          }
        ]
      },
      "observation": "club_id: 40\nunsafe_club_name: Liverpool\nsafe_club_name: Liverpool\n\nclub_id: 45\nunsafe_club_name: Everton\nsafe_club_name: Everton\n\nclub_id: 212\nunsafe_club_name: FC Porto\nsafe_club_name: Porto\n\nclub_id: 2358\nunsafe_club_name: Liverpool Montevideo\nsafe_club_name: Montevideo"
    }
  ]
}`

error: "Failed to parse a function call from llama3:70b output: {}"

it calls the function, gets a response, but is unable to parse it (or output it).

here is another example:

![image](https://github.com/FlowiseAI/Flowise/assets/17693211/ec3ece10-65f3-48a5-9c7a-cfea490fb5dc)

should be a separate issue: also when using the chatollama function with tools agent, it will always call the tool even if you just say "hi".

However i think there is much improvements to be made with the ollama function calling. happy to sponsor some more to get it working properly.
It feels like there is a missing piece for llama3 with ollama to work - should also be "retries" and the like.

**Comment by snailbrainx** [comment]
actually - is it llama3 that does not support function calling..

**Comment by HenryHengZJ** [comment]
Its coming from this [line](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatOllamaFunction/ChatOllamaFunction.ts#L395)

when there is no matching tool name found from the response given by Ollama

**Comment by akram** [comment]
By trying to send the prompt to my local LLM, it seems that `mistral` is not very careful on which name it returns regarding the agent. For example, I have specified `Business Analyst` and `Developer` as agent names but `mistral` returns `BA` and `DV` in its responses.
Is there a way to make it more strict? 
Could this be the cause of the `Failed to parse a function call from` ?

**Comment by snailbrainx** [comment]
Although this is for something different - is it related to missing information in the langchain ollamafunction docs?

https://github.com/msamylea/Llama3_Function_Calling/tree/main

**Comment by HenryHengZJ** [comment]
Ollama now support official function calling for some models - https://github.com/FlowiseAI/Flowise/pull/2892
