### ISSUE TITLE
Not able write to Chroma DB

### ISSUE THREAD

**Issue by pgaurav007** [FlowiseAI/Flowise#2662]
I just upgraded both chorma and flowise. Now i am not able ro write to chome. Although Collection is created when i run the flow, but then nothing is inserted or embedded in chroma. I am not getting any error as well.

![image](https://github.com/FlowiseAI/Flowise/assets/137371133/21029428-816d-44ff-82a6-4cfe42f56000)

![image](https://github.com/FlowiseAI/Flowise/assets/137371133/4b8fecd3-6470-409e-8a8a-9387efa2092f)

**Comment by HenryHengZJ** [comment]
It might because we havent upgraded Chroma version in Flowise, can take a look

**Comment by pgaurav007** [comment]
Appriciate it @HenryHengZJ, thanks a lot. If you can help me in choosing right version to make it work, that would gret help to me.

**Comment by boblyx** [comment]
Hi @pgaurav007, after some testing on my side, `chromadb/chroma:0.5.5` appears to work with `flowiseai/flowise:2.0.7`

**Comment by HenryHengZJ** [comment]
thanks @boblyx for helping to identify that !

**Comment by pgauravtn** [comment]
> Hi @pgaurav007, after some testing on my side, `chromadb/chroma:0.5.5` appears to work with `flowiseai/flowise:2.0.7`

NO, its not working still.

**Comment by pgauravtn** [comment]
> Hi @pgaurav007, after some testing on my side, `chromadb/chroma:0.5.5` appears to work with `flowiseai/flowise:2.0.7`

Thanks a lot @boblyx
