### ISSUE TITLE
[BUG] Iframe Not Working

### ISSUE THREAD

**Issue by asrguru20** [FlowiseAI/Flowise#2664]
**Describe the bug**
in flowise 1.8.2 Chatbot Imbedding iFrame no longer works, the chat bot only work within the canvas only

**Comment by HenryHengZJ** [comment]
how are you using the iframe? can you give example code?

**Comment by asrguru20** [comment]
> how are you using the iframe? can you give example code?

Hi Henry 
I have installed The Flowise 1.8.2 in my ubuntu 20.04 server by using Docker, 
I have created an agent and used the HTML imbedded iFrame in my WordPress website  for AI Tech support . and when I type or ask something it shows fetch error but when I downgraded to 1.8.1 it fixed 
I can attach screen shot or take a video if you want to show you.

**Comment by HenryHengZJ** [comment]
Feel free to re-open if issue still persists
