### ISSUE TITLE
[FEATURE] Please add openrouter as LLM Node

### ISSUE THREAD

**Issue by xenstar** [FlowiseAI/Flowise#2666]
**Describe the feature you'd like**
https://openRouter.ai has more than 150+ different models at cheap prices. Please add it as a llm model so we can easily use it with flowise. 

**Additional context**
Also it would be great, if you add a project in https://pinokio.computer/, then we can easily install flowise in desktop computer.

**Comment by HenryHengZJ** [comment]
you can already use open router - https://docs.flowiseai.com/integrations/langchain/chat-models/azure-chatopenai#open-router
also pinokio - https://github.com/FlowiseAI/Flowise-Pinokio

**Comment by xenstar** [comment]
Hey Thanks for the reply. But can you add openrouter as a separate LLMS? So we can easily import all the models, and quickly change it? Currently if we want to switch the model we have to manually put the model name.. It's a hassle. You have added togetherAI, so please add openrouter aswell.

**Comment by bitsnaps** [comment]
> you can already use open router - https://docs.flowiseai.com/integrations/langchain/chat-models/azure-chatopenai#open-router also pinokio - https://github.com/FlowiseAI/Flowise-Pinokio

Thanks, but it's not possible to enter a customer `Model Name` (e.g; `meta-llama/llama-3.2-3b-instruct`) when using OpenAI LLM even after setting the `basePath`!
