### ISSUE TITLE
[BUG]Unexpected sync check result: window.synccheck={retcode:"1101",selector:"0"}

### ISSUE THREAD

**Issue by Cuttuer** [FlowiseAI/Flowise#2668]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
can you provide more info?
