### ISSUE TITLE
Is there any configuration that could be used to make the chat history limitation when calling the LLM?

### ISSUE THREAD

**Issue by quzhixue-Kimi** [FlowiseAI/Flowise#2685]
hi there,

There has been one flowise chatbot I configured with upstash redis-backed chat memory. And, langsmith has been added to track the whole process and parameters. (It is just a chat bot flow with memory, no vector store and record manager)

I found that when I talked to my LLM, all the histories of chat message will be added as 'chat_history' parameter.

![image](https://github.com/FlowiseAI/Flowise/assets/8235746/fe4817c7-053b-4d0f-903c-40a7e12d2e78)

It will cost the LLM's token a lot. Even, some content of the chat history has no relation with my current topic.

It is appreciated that you may help and guide me to make some configuration about the 'chat_history' limitation to reduce the LLM's token cost.

BR
Kimi

**Comment by toi500** [comment]
Are u the only user that use this chatbot?

**Comment by quzhixue-Kimi** [comment]
Hi there,

I would like to publish the chatbot for registered users.

BR
Kimi

**Comment by HenryHengZJ** [comment]
There are different ways to help with that, have a look at the docs: 
https://docs.flowiseai.com/integrations/langchain/memory/buffer-window-memory
https://docs.flowiseai.com/integrations/langchain/memory/conversation-summary-memory
https://docs.flowiseai.com/integrations/langchain/memory/conversation-summary-buffer-memory

**Comment by quzhixue-Kimi** [comment]
hi Henry,

Thank you for your reply. I am using the upstash redis-backed chat memory in my chatbot. It seems that there is no configuration about it.

![image](https://github.com/FlowiseAI/Flowise/assets/8235746/69f656c4-a99c-4d1f-9ad6-4e4c215d28f3)

What I want to do is to record each user's chat history in upstash redis, and the session id in redis is just the unique user name.

BR
Kimi

**Comment by HenryHengZJ** [comment]
I'm afraid for now you'll have to use one of the memory nodes mentioned above, it's similar to upstash. Messages are stored with session if into your Flowise database

**Comment by quzhixue-Kimi** [comment]
Hi there,

Thank you for your kind help.

BR
Kimi
