### ISSUE TITLE
[BUG] Agent Tool doesn't  generate and show complete response

### ISSUE THREAD

**Issue by blackDZS** [FlowiseAI/Flowise#2686]
**Describe the bug**
Agent Tool doesn't  generate and show complete response

**To Reproduce**

- workflow
![截屏2024-06-20 17 06 25](https://github.com/FlowiseAI/Flowise/assets/38283850/53951695-1fb7-43f5-bc02-5e22b422d17f)

- Langfuse
![截屏2024-06-20 17 09 46](https://github.com/FlowiseAI/Flowise/assets/38283850/170b3634-6a57-4bf0-ad66-188aba59caca)

**Expected behavior**

assistant generate complete answer like: `Fianal Answer: 4`

**Setup**

-   Installation docker
-   Flowise Version 1.8.2
-   OS: Linux
-   Browser chrome

**Comment by HenryHengZJ** [comment]
Qwen might need some custom prompt, have you try modifying the System Prompt on Tool Agent?
