### ISSUE TITLE
[FEATURE] Github recursive scan

### ISSUE THREAD

**Issue by ill-yes** [FlowiseAI/Flowise#269]
**Describe the feature you'd like**
Since the current Github document loader isn't recursive scanning repos, I would like to add this feature as option.

**Additional context**
The `recursive` flag is already implemented, but the UI doesn't have the form for that.

I've already implemented it locally - `it works on my machine`.

**Comment by HenryHengZJ** [comment]
there is a PR - https://github.com/FlowiseAI/Flowise/pull/251
