### ISSUE TITLE
[BUG] 'turn on mmap' seems not work

### ISSUE THREAD

**Issue by b1gcat** [FlowiseAI/Flowise#2693]
finally, it cause 500 internal error

<img width="538" alt="图片" src="https://github.com/FlowiseAI/Flowise/assets/15025254/521d67ce-b311-41e3-a8fe-a2648a8a69e1">
<img width="866" alt="图片" src="https://github.com/FlowiseAI/Flowise/assets/15025254/c5ab8a71-c321-4aed-9ebc-66af26321591">

**Comment by stever100** [comment]
Same here, does it means the MMap is not there or by default it is true, it is enable?  @HenryHengZJ

**Comment by stever100** [comment]
It is actually working eventhough the MMap is not define there

**Comment by HenryHengZJ** [comment]
By default, MMAP should be turned on
