### ISSUE TITLE
[BUG] API of Agentflows not displaying the answers of each worker

### ISSUE THREAD

**Issue by gentilegregoire** [FlowiseAI/Flowise#2706]
**Description**
When I use an Agentflow with "Embed in website or use as API", the answers of each worker are not shown ; only the final conclusion appears. --> it would be great to have access to the whole conversation, as it is the case if the agentflow is tested in the development UI.

However, in the message history interface, we can see the answer of each worker, even if only the conculsion was displayed in the API interface.

**To Reproduce**
1. Go to "Embed in website or use as API"
2. For exemple, test with "Share chatbot" (bug also identified when embedded in a website)
3. Ask a question
4. See that only the final conclusion is shared, and not the whole conversation between workers and supervisor

**Expected behavior**
In the development UI, each message from a worker is shown and this is useful to get a more complete answer. It would be great if we can see the answer of each worker also with the API or when the chatbot is shared.
 
**Screenshots**
Development UI: ![Capture](https://github.com/FlowiseAI/Flowise/assets/17822183/5e2b573f-0155-4919-8831-bc72b7e84955)
API or embedded UI: ![Capture2](https://github.com/FlowiseAI/Flowise/assets/17822183/a08fa506-2970-4d23-8e6e-7742a8aaa1a1)

**Flow**
Tested with an Agentflow of the Flowise marketplace : 
[Prompt template Agents.json](https://github.com/user-attachments/files/15942953/Prompt.template.Agents.json)

Tested on Google Chrome and Microsoft Edge

Thanks in advance!

**Comment by HenryHengZJ** [comment]
just merged :) https://github.com/FlowiseAI/FlowiseChatEmbed/pull/197 

will push to new release soon!
