### ISSUE TITLE
[BUG] Unstructured.io file upload via API not working

### ISSUE THREAD

**Issue by marchdigital** [FlowiseAI/Flowise#2707]
I have a chatflow that uses the Unstructured.io file node to process a pdf file for upserting to Pinecone - it works fine when assigning the file via the upload option in the chatflow node directly but when using the API to post data the 'files' value is ignored (not parsed to the API) and reverts to any file assigned using the chat flow node directly.

**Comment by HenryHengZJ** [comment]
this [PR](https://github.com/FlowiseAI/Flowise/pull/2628) should fixes it, not yet push to new release

**Comment by kennyakers** [comment]
Am seeing this again: POSTing to the API endpoint with a different file under the 'files' value is ignored and the file uploaded to the node is upserted instead. Flowise v2.2.1

I've enabled the appropriate fields in the override config (see below). 

![image](https://github.com/user-attachments/assets/cc72e3fd-885f-4d52-89c5-48e9d6689387)
