### ISSUE TITLE
[BUG] "Inconsistency detected by ld.so" when updating with docker-compose

### ISSUE THREAD

**Issue by aaahariri** [FlowiseAI/Flowise#2713]
**Describe the bug**
When trying to update Flowise by following the steps here:
https://docs.flowiseai.com/configuration/deployment/digital-ocean#steps-to-update-flowise-on-digital-ocean

I get an error in the terminal that stops the docker compose build process.

**To Reproduce**

1. Follow steps 1-4 in the update guide URL shared above.

**Expected behavior**
Flowise updates successfully and I am able to access the app like before.

**Screenshots**
![Screenshot 2024-06-24 at 5 19 30 PM](https://github.com/FlowiseAI/Flowise/assets/22778573/9f51d4fa-490d-4042-9d20-443734590852)

**Flow**
N/A

**Setup**
-   Installation: docker
-   Flowise Version: Updating to latest version
-   OS: Linux machine on Contabo
-   Browser: Chrome

**Additional context**
This is the first time I am trying to update this Flowise docker image, so I can't say that I have done previous updates recently.

**Comment by HenryHengZJ** [comment]
can you try and see if your Dockerfile is updated with the latest one [here](https://github.com/FlowiseAI/Flowise/blob/main/docker/Dockerfile)

tagging @danieldabate to see if you have any idea

**Comment by danieldabate** [comment]
No idea, but it doesn't seem to be related with docker specifically. It seems to be something Linux related. If I search Google for the error, it takes me to Linux forums with different explanations, some got it solved by upgrading their kernel.

**Comment by aaahariri** [comment]
> can you try and see if your Dockerfile is updated with the latest one [here](https://github.com/FlowiseAI/Flowise/blob/main/docker/Dockerfile)
> 
> tagging @danieldabate to see if you have any idea

@HenryHengZJ Thank you for your response. Yes, my file likes exactly the same as the one you shared.

**Comment by aaahariri** [comment]
> No idea, but it doesn't seem to be related with docker specifically. It seems to be something Linux related. If I search Google for the error, it takes me to Linux forums with different explanations, some got it solved by upgrading their kernel.
@danieldabate 
Thanks! I am using a generic server on Contabo with nothing out of the ordinary. I assume it should work normally and its strange that it is related to the kernel. Flowise was working fine until I attempted the update.

**Comment by danieldabate** [comment]
I don't think it's that strange. At the end containers is a Linux feature and they all share the same kernel as the host OS. But I'm not saying that this is the issue either, it's just what I found with a quick search in Google and seems a reasonable thing to try.

I'd try updating the kernel, you have nothing to lose. If that doesn't work and you don't want to waste time debugging, I'd reinstall everything from scratch. 

This is the downside of manually managing VPSs and OSs, things can get complicated (compared to a cloud container service).

**Comment by aaahariri** [comment]
Thanks to you both @HenryHengZJ @danieldabate,
I thought I'd give updating docker a go (despite this being recently) using "sudo apt upgrade" etc.

It seems a recent update may have helped resolve this issue as I was able to update Flowise successfully after doing this update. Thank you!
