### ISSUE TITLE
[FEATURE]how to get the output of one agent and use it into tools called by another agent?

### ISSUE THREAD

**Issue by crack521** [FlowiseAI/Flowise#2724]
**Describe the feature you'd like**
how to get the output of one agent and use it into tools called by another agent?

**Additional context**

I am using FlowiseAI to create two agents in the AgentFlow module. One agent produces structured output parameters in formats such as JSON or a dictionary. I want to use these structured parameters in a custom tool called by another agent. How can I achieve this?

**Comment by dheerajbhadani** [comment]
Hi @crack521,

Do you have any example flow to share?

Thank you

**Comment by HenryHengZJ** [comment]
work in progress! next (1 or 2) release you should be able to

**Comment by HenryHengZJ** [comment]
now you should be able to achieve in the new sequential workflow approach. Example - https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.0.0
