### ISSUE TITLE
[BUG]Since last update 1.8.3 A pending llm response (no timeout) brakes the chatflow

### ISSUE THREAD

**Issue by Gallisatyricon** [FlowiseAI/Flowise#2734]
**Describe the bug**
Since last update 1.8.3 A pending llm response (no timeout) brakes the chatflow

**To Reproduce**

A created a chatflow, in work in progress state, with some queries staying in pending state because I forgot to setup a timeout. 
I shared the chatflow and some queries were made provoking a pending response. After what my chatflow becomes impossible to repair. 

I tried to restart my container, I changed many parts of my flow etc. The only solution is to start over from scratch. 

**Setup**

-   Installation Azure container
-   Flowise Version [e.g. 1.3.8]
-   OS: [e.g., Linux]
-   Browser [e.g. chrome, edge... ]

**Additional context**
My chatflow was working with 1.8.2. The pending queries didn't blocked everything. Sory for my poor explanation, I'm not a programmer. 

Tks if you have any advices. (I did activate timeout now)

**Comment by Gallisatyricon** [comment]
After several tests, I figure out that this occurs only when ChatGPT4o is used in AzureOpenAI chat module. Switching back to ChatGPT4turbo stop creating these infinite pending loops.

**Comment by HenryHengZJ** [comment]
Do you have Azure 4o working correctly for other chatflow?

**Comment by Gallisatyricon** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/147667920/eee5b938-e211-4cdd-b9f1-93303bf713d2)
Here is a exemple of the bug on another chatflow, simplified. You can see in the chatbox, the texte infinitly writing the same text over and over...

**Comment by HenryHengZJ** [comment]
problem should be resolved now:
![image](https://github.com/user-attachments/assets/4daa3808-f868-427b-afb5-eec6c475aaea)
