### ISSUE TITLE
Failed to add new Assistant: undefined

### ISSUE THREAD

**Issue by mirzanejad** [FlowiseAI/Flowise#2739]
I was able to add or load OpenAI Assistants before, but now when I try to do so, I get an error: 'Failed to add new Assistant: undefined.' Do you know what the issue might be?

**Comment by HenryHengZJ** [comment]
I was able to add a new assistant:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/b1c2e76a-7ca2-4832-b7d4-12939cc79e52)
