### ISSUE TITLE
[BUG] Context is not passing throw Agent Flow

### ISSUE THREAD

**Issue by whyike** [FlowiseAI/Flowise#2740]
**Describe the bug**
I am trying to pass {{chat_history}} in a variable to the worker to validate the user before starting a task. anything i have tried, it seems like the history is not passing.

**Comment by HenryHengZJ** [comment]
work in progress, will be releasing in the next (1 or 2) release!

**Comment by sunilhm68** [comment]
Hey @HenryHengZJ , it would be so much helpfull for no code person like me , pls help us and tell us once done! Thanks

**Comment by HenryHengZJ** [comment]
in the new version v2.0, you can connect memory called Agent Memory, then you can pass `chat_history` like always:
![image](https://github.com/user-attachments/assets/1a24223a-8008-4f7b-bbf1-49b675ff0289)
