### ISSUE TITLE
Cannot upload y[BUG]

### ISSUE THREAD

**Issue by Chalk4711** [FlowiseAI/Flowise#2750]
When i try to reproduce the usecase with the OpenAPI flow :

https://docs.flowiseai.com/use-cases/interacting-with-api

1/ I cannot upload the Yaml file with the upload button.
2/ When I try a link i get the error 'Unable to parse from source'

I therefore cannot reproduce the given uses case

**Comment by HenryHengZJ** [comment]
I just tested it, you can definitely upload:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/25e1105d-8f53-49c6-a407-a6b6440b5f1f)

here's the chatflow: [test.json](https://github.com/user-attachments/files/16170264/test.json)
