### ISSUE TITLE
Build error in Flowise huggingface.co version after the latest update. [BUG]

### ISSUE THREAD

**Issue by amrpyt** [FlowiseAI/Flowise#2753]
![image](https://github.com/FlowiseAI/Flowise/assets/77219001/74e9e3d4-f6b0-4f00-a6d4-85eb3b670760)
https://huggingface.co/spaces/FlowiseAI/Flowise

**Even my deployed version has the same error.**

> ###################The error###################################
> `Build logs:
> 
> ===== Build Queued at 2024-06-19 15:53:49 / Commit SHA: 8fb59d0 =====
> 
> --> FROM docker.io/library/node:20-alpine@sha256:66c7d989b6dabba6b4305b88f40912679aebd9f387a5b16ffa76dfb9ae90b060
> DONE 0.0s
> 
> --> RUN npm install -g flowise
> CACHED
> 
> --> Restoring cache
> 
> 
> --> RUN apk add --no-cache chromium git python3 py3-pip make g++ build-base cairo-dev pango-dev
> CACHED
> 
> --> Restoring cache
> DONE 1.6s
> 
> --> RUN npm install -g flowise
> CACHED
> 
> --> Restoring cache
> DONE 1.6s
> 
> --> RUN apk add --no-cache chromium git python3 py3-pip make g++ build-base cairo-dev pango-dev
> CACHED
> 
> --> Restoring cache
> DONE 4.6s
> 
> --> RUN mkdir -p $LOG_PATH $BLOB_STORAGE_PATH $FLOWISE_PATH/uploads && chmod -R 777 $LOG_PATH $BLOB_STORAGE_PATH $FLOWISE_PATH
> BusyBox v1.36.1 (2024-05-21 13:38:37 UTC) multi-call binary.
> 
> Usage: chmod [-Rcvf] MODE[,MODE]... FILE...
> 
> MODE is octal number (bit pattern sstrwxrwxrwx) or [ugoa]{+|-|=}[rwxXst]
> 
> 	-R	Recurse
> 	-c	List changed files
> 	-v	Verbose
> 	-f	Hide errors
> 
> --> ERROR: process "/bin/sh -c mkdir -p $LOG_PATH $BLOB_STORAGE_PATH $FLOWISE_PATH/uploads && chmod -R 777 $LOG_PATH $BLOB_STORAGE_PATH $FLOWISE_PATH" did not complete successfully: exit code: 1
> `###########################################################
>

**Comment by amansoni7477030** [comment]
@amrpyt use below image it will work:


```
FROM node:20-alpine
# Create the /data directory with appropriate permissions
RUN mkdir -p /data && chmod -R 777 /data
USER root

# Arguments that can be passed at build time
ARG FLOWISE_PATH=/usr/local/lib/node_modules/flowise
ARG BASE_PATH=/data/.flowise
ARG DATABASE_PATH=$BASE_PATH
ARG APIKEY_PATH=$BASE_PATH
ARG SECRETKEY_PATH=$BASE_PATH
ARG LOG_PATH=$BASE_PATH/logs
ARG BLOB_STORAGE_PATH=$BASE_PATH/storage

# Set the ARGs as ENV
ENV FLOWISE_PATH=$FLOWISE_PATH
ENV BASE_PATH=$BASE_PATH
ENV DATABASE_PATH=$DATABASE_PATH
ENV APIKEY_PATH=$APIKEY_PATH
ENV SECRETKEY_PATH=$SECRETKEY_PATH
ENV LOG_PATH=$LOG_PATH
ENV BLOB_STORAGE_PATH=$BLOB_STORAGE_PATH

# Install dependencies
RUN apk add --no-cache git python3 py3-pip make g++ build-base cairo-dev pango-dev chromium

ENV PUPPETEER_SKIP_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

# Install Flowise globally
RUN npm install -g flowise

# # Configure Flowise directories using the ARG
RUN mkdir -p $FLOWISE_PATH/uploads && chmod -R 777 $FLOWISE_PATH
CMD ["sh", "-c", "mkdir -p $LOG_PATH && chmod -R 777 $LOG_PATH && npx flowise start"]
```
