### ISSUE TITLE
Parameter "keep_alive" for Ollama

### ISSUE THREAD

**Issue by JBX028** [FlowiseAI/Flowise#2756]
Hi,

Is it in the roadmap to be able to pass the parameter "keep_alive" to Ollama?

https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

I have tried many techniques to set the environment variable OLLAMA_KEEP_ALIVE without success, therefore I would like to pass the parameter in Flowise, but it's not in the list.

Thanks

**Comment by HenryHengZJ** [comment]
PR merged - https://github.com/FlowiseAI/Flowise/pull/2892
