### ISSUE TITLE
[FEATURE] Docs!!

### ISSUE THREAD

**Issue by amandesai01** [FlowiseAI/Flowise#276]
**Describe the feature you'd like**
As I can see Flowise has gained a lot of popularity (which it deserves!) and contributors may want to start contributing. Docs become a necessary part in that process. So may be we can start writing a system level doc describing core entities and assets which makes it easy for developers to get started?

I would be more than happy to start this task. We can write JSDoc within code and export it to a documentation static site.

**Comment by HenryHengZJ** [comment]
love the idea. I recently started writing some docs - https://github.com/FlowiseAI/FlowiseDocs
but I'm up to migrate the docs repo to main repo instead of standalone one. Similar to [langchainjs](https://github.com/hwchase17/langchainjs/tree/main/docs)

**Comment by amandesai01** [comment]
Why not JS Doc? In code documentation is more handy and easy to maintain (When it comes to developer documentation).
Usage documentation can stay different. What say?

**Comment by HenryHengZJ** [comment]
is jsdoc more suitable for API/SDK libraries?
Flowise doens't have much of API docs, and lots of the nodes integration requires screenshots (visual images/vids)
but feel free give it a try and we can see how it looks
