### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'substring')

### ISSUE THREAD

**Issue by mishlaev-personal** [FlowiseAI/Flowise#2760]
**Describe the bug**
After opening a chat window the whole app crushes with an error: Cannot read properties of undefined (reading 'substring')

**To Reproduce**
<img width="1552" alt="Screenshot 2024-07-03 at 3 44 03 PM" src="https://github.com/FlowiseAI/Flowise/assets/22517333/0588bc2c-623d-446d-b565-3f5a6e8f6370">
1. I've created a simple Pinecone to Open AI flow.
2. Opened a chat window
3. Typed a message.
4. After the bot started replying it all crashed.

**Expected behavior**
Not crashing.

**Screenshots**
<img width="1552" alt="Screenshot 2024-07-03 at 3 41 49 PM" src="https://github.com/FlowiseAI/Flowise/assets/22517333/24cbbea2-e9fd-4766-89a8-333532282690">

**Flow**
[Support Chat_ Jira Cloud or All Chatflow.json](https://github.com/user-attachments/files/16085833/Support.Chat_.Jira.Cloud.or.All.Chatflow.json)

**Setup**

-   Installation npx flowise start
-   Flowise Version 1.8.3
-   OS: macOS
-   Browser chrome

**Comment by lnghost** [comment]
Fix it asap please

**Comment by elledanili** [comment]
I have the same issue. Fix it pls

**Comment by Nadyaducalis** [comment]
Have the same issue, waiting for the fixes

**Comment by AsharibAli** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/FlowiseAI/Flowise/issues/2760?shareId=dc7a63f0-0f79-4b88-a7bc-a3a287ce7e55) saved by @AsharibAli using Copilot Workspace v0.22

<details open><summary><b>Topic</b></summary>
<br/>

Does the app crash with the error 'Cannot read properties of undefined (reading 'substring')' when opening a chat window and typing a message? 🐛

</details>

<details open><summary><b>Before</b></summary>
<br/>

- Yes, the app crashes with the error 'Cannot read properties of undefined (reading 'substring')' when opening a chat window and typing a message. 🐛
- The error occurs in the `packages/components/src/storageUtils.ts` file, specifically in the `addBase64FilesToStorage` function at line 20, where `splitDataURI.pop()?.split(':')[1]` can be undefined. 📝
- The `addArrayFilesToStorage` function in the same file also has a similar potential issue at line 60 with `Key.substring(1)`. 🔍
- The `ChatPopUp` component in `packages/ui/src/views/chatmessage/ChatPopUp.jsx` interacts with the chat window and may trigger the error. 💬
- The `chatmessageApi.deleteChatmessage` function in `packages/ui/src/api/chatmessage.js` is called when clearing chat history, which might be related to the issue. 🗑️

</details>
<details open><summary><b>After</b></summary>
<br/>

- No, the app no longer crashes with the error 'Cannot read properties of undefined (reading 'substring')' when opening a chat window and typing a message. 🛠️
- The `addBase64FilesToStorage` function in `packages/components/src/storageUtils.ts` now checks if `splitDataURI.pop()?.split(':')[1]` is undefined before accessing it. ✅
- The `addArrayFilesToStorage` function in the same file now checks if `Key.substring(1)` is undefined before accessing it. 🔍
- The `ChatPopUp` component in `packages/ui/src/views/chatmessage/ChatPopUp.jsx` now handles the chat window interactions without causing the error. 💬

</details>

<details open><summary><b>Plan</b></summary>
<br/>

* `packages/components/src/storageUtils.ts` (CHANGE)
  - Add a check if `splitDataURI.pop()?.split(':')[1]` is undefined before accessing it in the `addBase64FilesToStorage` function
  - Add a check if `Key.substring(1)` is undefined before accessing it in the `addArrayFilesToStorage` function
* `packages/ui/src/views/chatmessage/ChatPopUp.jsx` (CHANGE)
  - Add error handling for chat window interactions to prevent the error
* `packages/ui/src/api/chatmessage.js` (CHANGE)
  - Add error handling for the `deleteChatmessage` function to prevent the error

</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

[View the changes](https://copilot-workspace.githubnext.com/FlowiseAI/Flowise/issues/2760?shareId=dc7a63f0-0f79-4b88-a7bc-a3a287ce7e55)

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at b1e38783e442abc4795f090826d6388b82714a14

</details>

**Comment by HenryHengZJ** [comment]
thanks for reporting! I think we just need to make proper check on the `ChatMessage.jsx` for every `substring` we are calling
