### ISSUE TITLE
[BUG] agentFlow + embed

### ISSUE THREAD

**Issue by tgonzales** [FlowiseAI/Flowise#2761]
**Describe the bug**
Hello friends, an agent flow does not work the same way with a chat flow through an embed/widget. through embed I only receive the last response from the agent flow. Is it a bug or should the embed script be different?

preview
![Screenshot 2024-07-03 at 11 43 36](https://github.com/FlowiseAI/Flowise/assets/2750199/8fab06f0-100b-46b4-a1a7-79de9a8a3653)

embed with AgentFlow
![Screenshot 2024-07-03 at 11 43 52](https://github.com/FlowiseAI/Flowise/assets/2750199/84196983-48b1-4c39-8d57-a27ddc47da0f)

**Comment by HenryHengZJ** [comment]
we have yet pushed the changes to the new release - https://github.com/FlowiseAI/Flowise/pull/2749

**Comment by tgonzales** [comment]
@HenryHengZJ 
I managed to run it here, basically just put showAgentMessages: true in theme.chatWindow

It's not a bug, there's just a doc explaining how to activate this. Congratulations on the excellent work.
