### ISSUE TITLE
[BUG] Difference response from flowise API and Flowise's chat window

### ISSUE THREAD

**Issue by movonstudio** [FlowiseAI/Flowise#2768]
**Describe the bug**
I get a difference answer from the window emulator chat and using API.

**Screenshot**

<img width="879" alt="Screen Shot 2024-07-07 at 10 40 15" src="https://github.com/FlowiseAI/Flowise/assets/86511300/8d1254d2-ddf0-4214-a3b8-d299436e02b0">
<img width="1152" alt="Screen Shot 2024-07-07 at 10 40 36" src="https://github.com/FlowiseAI/Flowise/assets/86511300/fb6f42ae-62ce-42c0-b0ce-5a6cd668c399">

**Comment by HenryHengZJ** [comment]
you need to pass a `sessionId` - https://docs.flowiseai.com/using-flowise/api#persists-memory
