### ISSUE TITLE
Error: predictionsServices.buildChatflow - SQLITE_CONSTRAINT: NOT NULL constraint failed: chat_message.content

### ISSUE THREAD

**Issue by levuepress** [FlowiseAI/Flowise#2776]
**Describe the bug**
Error: predictionsServices.buildChatflow - SQLITE_CONSTRAINT: NOT NULL constraint failed: chat_message.content

**To Reproduce**
Following the steps in the integration document at https://docs.flowiseai.com/using-flowise/streaming resulted in errors as reported above.

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [yarn]
-   Flowise Version [e.g. 1.2.11]
-   OS: [Windows]
-   Browser [chrome]

**Additional context**

**Comment by G-Cyrille** [comment]
I encountered this error today but the reason for me was : 
my prompt template prompt values where "in" and "out"
so in my curl I used "in" in the json variable.

When I replaced it with "question" instead it worked like a charm !

this didn't work (with the error
```
curl https://_________/api/v1/prediction/________ \                                                                                                     
     -X POST \
     -d '{"in": "the input"}' \
     -H "Content-Type: application/json"
```

this did work : 
```
curl https://_________/api/v1/prediction/________ \                                                                                                     
     -X POST \
     -d '{"question": "the input"}' \
     -H "Content-Type: application/json"
```

You might want to check the content of the : 
```
query({
  "question": "Hey, how are you?",
  "socketIOClientId": socketIOClientId
})
```

I hope this helps

**Comment by Abhishek21k** [comment]
trying to call the streaming api and uplaoding the file:
```
client.createPrediction({
            chatflowId: process.env.NEXT_PUBLIC_CHATFLOW_ID!,
            question: data.question,
            uploads: uploads,
            streaming: true,
            chatId: chatflowId,
          })
```
and getting this error:
```{
    "event": "error",
    "data": "Error: predictionsServices.buildChatflow - Cannot read properties of undefined (reading 'split')"
}
```
