### ISSUE TITLE
[FEATURE]Integrating Conversation and Retrieval QA Chains in Flowise Chatbots

### ISSUE THREAD

**Issue by Prakashram27** [FlowiseAI/Flowise#2785]
I am working on a Flowise chatbot and have created two chain flows. The first is a conversation chain that begins when the user starts a conversation, collecting their email and name. The second is a Conversation Retrieval QA chain that assists with questions related to the website or documents. My challenge is connecting these two nodes and ensuring they function correctly, so that the user's questions are routed to the Conversation Retrieval QA chain.

**Comment by HenryHengZJ** [comment]
this can now be achieved using the new seq agent approach
