### ISSUE TITLE
[FEATURE] web scraper with custom tool agent 

### ISSUE THREAD

**Issue by yahya-shalash** [FlowiseAI/Flowise#2787]
i have a web scraper and its working fine and i have create more than custom tools and i have connected them to custom tool agent 
the question is can i used them with the same bot ?

**Comment by HenryHengZJ** [comment]
what do you mean by same bot? you can have a tool agent that connected to multiple custom tools

**Comment by yahya-shalash** [comment]
> what do you mean by same bot? you can have a tool agent that connected to multiple custom tools

i need in the same flow that im used custom tool i want to add a web scrapper
