### ISSUE TITLE
Can not get an expected answer with Ollama and plain text embedding

### ISSUE THREAD

**Issue by sunnysunyuan** [FlowiseAI/Flowise#2791]
**Describe the bug**
I am pretty new for using Flowise. I created a Chartflow like below:
![chatflow](https://github.com/FlowiseAI/Flowise/assets/12287602/3d2cc46a-b609-43a3-9093-ea33c81cca6f)
But when I tried to ask a question like 'Who is Alex Wood?', I could not get the expected answer when the answer can be parsed and got from the Plain Text obviously.
![wronganswer](https://github.com/FlowiseAI/Flowise/assets/12287602/cf036951-d320-4607-9ea8-a8b8a532568a)

The Ollama with Llama 3 can work well. 

Any suggestions would be appreciated. 

**Setup**
-   Installation: pnpm start
-   Flowise Version 1.3.8
-   OS: Windows
-   Browser: Chrome

**Comment by HenryHengZJ** [comment]
have you upserted the data? https://docs.flowiseai.com/use-cases/upserting-data

**Comment by sunnysunyuan** [comment]
Thanks for the reply! Yes, I have.

**Comment by HenryHengZJ** [comment]
It should be fixed in v2.0, feel free to reopen if issue still persists
