### ISSUE TITLE
Can not get answer using MongoDB Atlas

### ISSUE THREAD

**Issue by rms-software-house** [FlowiseAI/Flowise#2792]
**Describe the bug**
I can insert vectors in my paid MongoDB Atlas without problems, but when in another flow i try to get any answer, the chat returns:
$vectorSearch is not allowed or the syntax is incorrect, see the Atlas documentation for more information. What it can be?

**To Reproduce**

That is my flow to insert vectors in the db:
![image](https://github.com/FlowiseAI/Flowise/assets/169939430/5c9a1589-8476-41f8-8fcf-8bba0bc5512e)

and that is the flow to chat with the data
![image](https://github.com/FlowiseAI/Flowise/assets/169939430/a7c8b165-c473-48c0-ba89-9823a1080d72)

**Expected behavior**
The expected behaviour is that the chat answers based on the information.

**Setup**

-   Installation [docker on easypanel]
-   Flowise Version [1.8.3]
-   OS: [Linux]
-   Browser [edge]

**Comment by HenryHengZJ** [comment]
hey @nbbeeken I wonder do you have any insight on this?

**Comment by nbbeeken** [comment]
Hey @rms-software-house and @HenryHengZJ, I am not the best resource, reaching out on https://www.mongodb.com/community/forums/ will get you the domain experts on this. 

Two quick things you can confirm are: 
- What version of MongoDB is running in Atlas? 
- Are you able to see your search indexes already created in the Atlas UI?

**Comment by HenryHengZJ** [comment]
We have updated the docs guide: https://docs.flowiseai.com/integrations/langchain/vector-stores/mongodb-atlas
