### ISSUE TITLE
Request to Ollama server failed: 500 Internal Server Error[BUG]

### ISSUE THREAD

**Issue by a419506442** [FlowiseAI/Flowise#2793]
**Describe the bug**
ollama is runinng with  jupyter code,but error for same component with flowise.

Request to Ollama server failed: 500 Internal Server Error\n\nError: Request to Ollama server failed: 500 Internal Server Error

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/1701838/28eb0b67-e1ff-4c64-bed7-00a5a86e876d)
![image](https://github.com/FlowiseAI/Flowise/assets/1701838/55d8f35d-9d90-4300-abca-129bedcf475a)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by kb-** [comment]
It works after activating MMap in addidional parameters of Ollama Embeddings 
https://github.com/FlowiseAI/Flowise/issues/1673#issuecomment-2159216044

This should be on by default
