### ISSUE TITLE
[FEATURE] OpenSearch Vector Store Integration from Cloud Provider eg : AWS

### ISSUE THREAD

**Issue by SudhaGarimella** [FlowiseAI/Flowise#2794]
Currently I do not see an integration of Flowise with Opensearch service from AWS. Can we please have that feature integrated?
I can connect to my local instance of Open Search but not from the cloud provider

Let me know if I overlooked any functionality .

**Additional context**

**Comment by danieldabate** [comment]
The current implementation of OpenSearch supports AWS, authenticating with username and password.

There is a similar issue open were I discuss how to integrate other auth methods for AWS: 
https://github.com/FlowiseAI/Flowise/issues/1049

**Comment by SudhaGarimella** [comment]
Thanks for your response. I will close this as duplicate.

**Comment by SudhaGarimella** [comment]
There is another duplicate issue on the same topic. Hence closing this one. - https://github.com/FlowiseAI/Flowise/issues/1049
