### ISSUE TITLE
[FEATURE] S3 directory with multiple file support

### ISSUE THREAD

**Issue by Iternal-JBH4** [FlowiseAI/Flowise#2806]
in the documentation it looks like you can only upload a single s3 file (i.e. example.txt) and not a path to multiple files such as

s3://flowise/documents/

Is this supported but not in the docs, or can it be added?

https://github.com/FlowiseAI/Flowise/issues/2778

Thanks!

**Comment by slaplante-raft** [comment]
@Iternal-JBH4 Ive just opened this [pull request](https://github.com/FlowiseAI/Flowise/pull/2818) to add a new component for loading multiple documents from S3.

**Comment by HenryHengZJ** [comment]
closing as https://github.com/FlowiseAI/Flowise/pull/2818 merged 🎊
