### ISSUE TITLE
[BUG] Too many inputs using Azure OpenAI embeddings

### ISSUE THREAD

**Issue by NullVsNone** [FlowiseAI/Flowise#281]
**Describe the bug**
When attempting to use AOI Embeddings on either JSON or PDF, I get a 400 error and am unable to continue.

Using the request sent out, I do get:

```
{
  "error": {
    "message": "Too many inputs. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: <LINK> for further questions.",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

Looks like this is also being worked on in https://github.com/hwchase17/langchainjs/issues/1571
And possibly resolved in https://github.com/hwchase17/langchainjs/pull/1598

But it looked like others using this project were able to get it running, even without those fixes?

**To Reproduce**
Steps to reproduce the behaviour:

1. Use a JSON or PDF file
2. Use Azure OpenAI Embeddings
3. Send request

**Expected behavior**
Able to generate embeddings

**Screenshots**

![image](https://github.com/FlowiseAI/Flowise/assets/66640706/a27ffe73-fbfd-4acd-9dbf-f8de65b7a96d)

**Setup**

-   OS: Windows
-   Browser: Edge
-   Version: flowise@1.2.11

**Additional context**

The response recieved from Flowise terminal is
```
    },
    data: { error: [Object] }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON],
  attemptNumber: 1,
  retriesLeft: 6
}
```

Any chance it's possible to retrieve the object without sending out the request manually?

**Comment by HenryHengZJ** [comment]
possibly related - https://github.com/FlowiseAI/Flowise/issues/195 ?

**Comment by lb1223** [comment]
I have tried many times to use the azure openai api on flowise, and you are the first successful one I have seen

**Comment by NullVsNone** [comment]
Got it, turns out updating the version didn't update the card to the new one. Had to delete the embeddings card, and add it again. After that, the batch size parameter showed up and I was able to get it up and running.
