### ISSUE TITLE
[BUG] Differences between webservice prediction endpoint and langfuse tracing (llmchain/structured ouput parser)

### ISSUE THREAD

**Issue by koorlan** [FlowiseAI/Flowise#2810]
**Describe the bug**
They are differences between webservice output and langfuse tracing using llmchain and json output

On webservices the structure json output is under a "json" key otherwise in langfuse the json is traced under text key

webservices :

```json
{
    "json": {
        "go_back_to_menu": false,
        "transfer_to_agent": false
    },
    "question": "hey",
    "chatId": "issue-1",
    "chatMessageId": "a057c1b8-82c5-4727-9d99-9c0c20d29995",
    "sessionId": "issue-1"
}
```
On langfuse ( LLM chain span ) 

```json
{
text: {
go_back_to_menu: false
transfer_to_agent: false
}
}
```

Note: I use *structured output parser* with *autofix* enabled

**To Reproduce**
Flowise : 1.8.0
LLM chain with output parser ( autofix on) 

Use curl (postman) prediction endpoint 
--> json key

Check on langfuse trace 
--> text key 

**Expected behavior**
Coherent prediction endpoint response and trace on langfuse

**Screenshots**
![image](https://github.com/user-attachments/assets/52141105-b42f-4134-9c1e-db58ac79143c)
![image](https://github.com/user-attachments/assets/d6c9848c-b27a-42e0-bf59-25285f6e4851)

**Additional context**
Basic chain with json output

![image](https://github.com/user-attachments/assets/16c2d7ed-fa0a-46a7-b68c-da3f5ad5f703)

**Comment by HenryHengZJ** [comment]
`text` is the key we used to trace the output - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/src/handler.ts#L455
