### ISSUE TITLE
[BUG] Using CloudFormation template in AWS throws an error

### ISSUE THREAD

**Issue by gsogol** [FlowiseAI/Flowise#2813]
**Describe the bug**
When deploying the AWS CloudFormation templqte where the only change is adding a flowise username and password throws
Error: Unexpected arguments: /bin/sh, -c, sleep 3; flowise start

**To Reproduce**

Deploy a new CloudFormation Stack using the provided template from gist

**Comment by ciscogeek** [comment]
same same

**Comment by MrHertal** [comment]
The issue was related to: https://github.com/FlowiseAI/Flowise/issues/2651

I've fixed the gist

**Comment by HenryHengZJ** [comment]
duplicated - https://github.com/FlowiseAI/Flowise/issues/2651
