### ISSUE TITLE
[BUG] Repeated texts in tool calls

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2814]
**Describe the bug**

I can't describe what is this, but I found this log from my agent flow.

```json
{
    "tool_calls": [
        {
            "id": "call_gxTd504SpQF9ayNvQKe0jE7l",
            "type": "functionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunction",
            "index": 0,
            "function": {
                "name": "route",
                "arguments": {
                     ...
                }
            }
        }
    ]
}
```

**To Reproduce**

1. Make agent flow
2. Link with Chat OpenAI, and Langfuse
3. Run Agent

**Expected behavior**

Type should be `function`, not `functionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunctionfunction`

**Screenshots**
![image](https://github.com/user-attachments/assets/777d5329-099c-4a8f-a5fb-ab41ef29256d)
![image](https://github.com/user-attachments/assets/21fd3341-10a6-4f31-967a-5da37227fdc2)

**Flow**
If applicable, add exported flow in order to help replicating the problem.
Sorry, export of flow was restricted for security reasons.

**Setup**

-   Installation: docker [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version: 81918d5e3ccd
-   OS: Linux
-   Browser: Firefox, Safari (iOS), and Edge

**Additional context**
I route my Azure OpenAI APIs with LiteLLM.

**Comment by HenryHengZJ** [comment]
is there any dummy or example chatflow that we can replicate?

**Comment by seonghobae** [comment]
If you want to check this, could you please provide me with your email address to prevent security issues? Currently, I am connected to LiteLLM Proxy, and this issue only occurs when connecting to the gpt-4o model. The symptoms disappear when I connect to gpt-4o mini. This issue did not occur when I connected the Azure OpenAI gpt-4o model to AgentFlow. It might be a problem on the LiteLLM Proxy side, but I'm not sure what the direct issue is. Further investigation is needed.

**Comment by seonghobae** [comment]
After update to 2.0.0, this symptoms has gone. That's weird.
