### ISSUE TITLE
Warning: Received `false` for a non-boolean attribute `border`.

### ISSUE THREAD

**Issue by inno-elon** [FlowiseAI/Flowise#2819]
**Describe the bug**
Warning: Received `false` for a non-boolean attribute `border`.

**To Reproduce**

npx flowise start, error is in the console

**Expected behavior**
No Warnings

**Screenshots**
<img width="368" alt="image" src="https://github.com/user-attachments/assets/c9f652f2-1765-4dee-b9c1-4611df59d476">
<img width="489" alt="image" src="https://github.com/user-attachments/assets/bc017260-b545-4c7e-a311-aab4ec7b6950">
<img width="689" alt="image" src="https://github.com/user-attachments/assets/f22aa17e-c57e-4c38-8890-a4763e4435a7">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation `npx flowise start`, `pnpm start`
-   Flowise Version latest
-   OS: macOS
-   Browser: chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
i think we can remove it since `border` is not being used inside `MainCard.jsx`

**Comment by HenryHengZJ** [comment]
Fixed: https://github.com/FlowiseAI/Flowise/pull/3275
