### ISSUE TITLE
AWS with docker: Can't update to latest version.

### ISSUE THREAD

**Issue by mehrajagdish** [FlowiseAI/Flowise#2834]
**Describe the bug**
Currently running the version 1.8.3 , pulled the latest code from github then restarted the docker build. Still shows version 1.8.3.

**To Reproduce**

1. connect to EC2 instance.
2. go to Flowise folder
3. take latest pull using git pull
4. got to docker folder
5. stop using docker-compose stop
6. restart using docker-compose up -d
7. open gui , version still not updated

**Expected behavior**
Flowise shoud be on the latest version 1.8.4

**Setup**

-   Installation [Docker on AWS]
-   Flowise Version [1.8.3]
-   OS: [Linux]

**Comment by HenryHengZJ** [comment]
The steps should be correct and working fine, any error logs from docker?

**Comment by mehrajagdish** [comment]
No error logs shown in docker logs

**Comment by mehrajagdish** [comment]
Found the issue i need to do docker-compose pull and then docker-compose up --build -d

**Comment by blissiraDC** [comment]
Massive thanks @mehrajagdish I have been struggling with this.  It seems the commands in the docs no longer have the correct syntax.

**Comment by HenryHengZJ** [comment]
Thanks! Updated the docs
