### ISSUE TITLE
[FEATURE] A way to output or stream AgentFlows like Chat inside Flowise app. 

### ISSUE THREAD

**Issue by blissiraDC** [FlowiseAI/Flowise#2838]
**Describe the feature you'd like**
A way to be able to output or stream Agent flows as seen inside the Flowise test chat. Where you are able to see the supervisor request followed by the answer from the worker. When trying to output this in for instance a shared or embeded window the out comes in 1 complete block of text, after quite some time. Rendering AgentFlows pretty much useless. 

**Additional context**
![Screenshot 2024-07-20 135802](https://github.com/user-attachments/assets/16152e4b-d7ff-4599-9ced-1b36adaf50cd)

**Comment by HenryHengZJ** [comment]
- For embedded, you have to use `showAgentMessages` - https://github.com/FlowiseAI/FlowiseChatEmbed?tab=readme-ov-file#configuration

**Comment by HenryHengZJ** [comment]
Share Chatbot now also will display agent messages
