### ISSUE TITLE
[BUG] Agentflow Not Functioning Properly in Flowise 2.0.0

### ISSUE THREAD

**Issue by seonghobae** [FlowiseAI/Flowise#2847]
**Description:** After upgrading to Flowise 2.0.0, we have encountered an issue where the existing Agentflow is not functioning correctly. Specifically, messages generated by the Worker are not appearing in the final output.

**Steps to Reproduce:**

1. Upgrade to Flowise 2.0.0.
2. Execute an existing Agentflow.
3. Observe that messages from the Worker do not appear in the final result.

**Expected Behavior:** Messages generated by the Worker should be included in the final output.

**Actual Behavior:** Messages from the Worker are missing in the final output.

**Environment:**

- Flowise Version: 2.0.0
- Operating System: Ubuntu
- Browser: Edge

**Additional Context:** This issue was not present in the previous version of Flowise. It appears to be a regression introduced in the 2.0.0 update.

**Screenshots:** If applicable, add screenshots to help explain your problem.
![image](https://github.com/user-attachments/assets/4e22ff5f-f8e8-4c28-abb8-00b76dedbe63)

**Comment by HenryHengZJ** [comment]
This is the new behaviour. Since multi agents are working back and forth between workers, we think the final output should be a summarisation of the whole conversation.

For example. If you have a coder agent and a reviewer agent, and you ask the team to generate piece of code. The expected final output should be the code generated by coder agent. But it will be the reviewer's output.

This new behaviour is somewhat aligns with AutoGen studio 
![1706155331144](https://github.com/user-attachments/assets/355fb6f7-03cc-47f4-967e-5d9678ce65de)

**Comment by seonghobae** [comment]
The problem with this approach is that when you send a POST request, it doesn't get the right text. I think this behaviour is quite misleading because the current Flowise native chat tool doesn't show all the Agent results either, and the Agent results are collapsed.

**Comment by HenryHengZJ** [comment]
Understood, will see if we can create an optional field for supervisor, and provide summary only when user select so

**Comment by HenryHengZJ** [comment]
@seonghobae changes has been pushed to 2.0.1, can you try and see?

**Comment by seonghobae** [comment]
> @seonghobae changes has been pushed to 2.0.1, can you try and see?

I haven't reviewed the regression test in detail so I can't say for sure, but there doesn't seem to be anything out of the ordinary in our normal testing routine. If there is, I'll reopen the issue.

---

# Query
Find the weather in Seoul today specifically and tell me in English.

---

Response: 
# Current Weather in Seoul

- **Current Temperature**: 26°C
- **Feels Like**: 33°C
- **Today's High**: 31°C
- **Today's Low**: 26°C
- **Weather Condition**: Mostly clear and humid

There is a forecast for thunderstorms from Thursday afternoon to Friday night.

For more detailed weather information, you can check the following links:

- [**[Seoul Weather Forecast](https://www.accuweather.com/en/kr/seoul/226081/weather-forecast/226081)**](https://www.accuweather.com/en/kr/seoul/226081/weather-forecast/226081)
- [**[Hourly Weather Forecast](https://www.accuweather.com/en/kr/seoul/226081/hourly-weather-forecast/226081)**](https://www.accuweather.com/en/kr/seoul/226081/hourly-weather-forecast/226081)
- [**[Daily Weather Forecast](https://www.accuweather.com/en/kr/seoul/226081/daily-weather-forecast/226081)**](https://www.accuweather.com/en/kr/seoul/226081/daily-weather-forecast/226081)
- [**[Seoul Weather Radar](https://www.accuweather.com/en/kr/seoul/226081/weather-radar/226081)**](https://www.accuweather.com/en/kr/seoul/226081/weather-radar/226081)
- [**[Air Quality Index](https://www.accuweather.com/en/kr/seoul/226081/air-quality-index/226081)**](https://www.accuweather.com/en/kr/seoul/226081/air-quality-index/226081)
