### ISSUE TITLE
[BUG] Cannot insert header on GET API CHAIN

### ISSUE THREAD

**Issue by NicolasCampana** [FlowiseAI/Flowise#2853]
**Describe the bug**
When i try to insert a key-value custom header on the GET API CHAIN node, it just don't let me add the value to the key.

**To Reproduce**

1. Insert a GET API CHAIN
2. Try to add a new key-value header
3. You are able to add the key
4. You are not able to open the {...} text to insert the value to the key.

**Expected behavior**
The same behavior of other "headers components", such as "Requests Get" node. 

**Screenshots**
GET API CHAIN:
![image](https://github.com/user-attachments/assets/7f2d5629-bff6-45f1-add8-073649e31d4c)
Requs
**Setup**

-   Installation: docker compose
-   Flowise Version: 2.0.0 (but also got the same problem with 1.8.2)
-   OS: Windows
-   Browser: Chrome and Edge

**Additional Context**
It's looks like this strange behavior also happens sometimes in other nodes like Requests Tool.

**Comment by HenryHengZJ** [comment]
yeah there is a bug with that, fixing it @0xi4o

**Comment by HenryHengZJ** [comment]
Is this still the case? By default it should open the bracket:
![image](https://github.com/user-attachments/assets/0ae52a05-981d-4752-bbf8-efa0155beb43)

**Comment by rjbuda** [comment]
Has this issue been fixed? I am working with 2.2.8 and I am experiencing the same issue.  Is there a version where this is corrected?

**Comment by rjbuda** [comment]
I tested and this is fixed in 3.0.4. Not sure about any earlier versions.  Thanks!
