### ISSUE TITLE
The overrideConfig settings are not being passed through to sub chatflows.

### ISSUE THREAD

**Issue by cmak34** [FlowiseAI/Flowise#2861]
**Describe the bug**
The overrideConfig settings are not being passed through to sub chatflows.

**To Reproduce**
1. Create a simple custom JavaScript chatflow that logs the $vars.
![image](https://github.com/user-attachments/assets/ad4fcefd-5263-4323-9a4b-af14664c9eab)

2. Use the API to call the chatflow ID with the overrideConfig parameter in the payload:
```json
{
  "vars": {"hello": "world"}
}
```
- The $vars are logged correctly.

3. Create a Tool Agent that includes the custom JavaScript chatflow.
![image](https://github.com/user-attachments/assets/f08d56b0-d2cb-4e5f-b6f3-141833d794c9)

4. Use the API to call the Tool Agent chatflow ID with the overrideConfig parameter in the payload.
- The $vars are not logged correctly.

**Expected behavior**
The overrideConfig parameter should be passed through to the sub-chatflow correctly.

**Setup**
-   Installation [`pnpm start`]
-   Flowise Version [2.0.1]
-   OS: [macOS]
-   Browser [chrome]

**Additional context**
N/A

**Comment by schieck0** [comment]
I tried with a custom tool to retrieve a variable value and nothing returns:
![image](https://github.com/user-attachments/assets/b4cfbbfc-0d5b-4dd0-8c85-ec1b9f26982a)
![image](https://github.com/user-attachments/assets/e5c9d2b6-0100-40cf-97ee-de0a494dab78)
![image](https://github.com/user-attachments/assets/24e7d937-059b-4117-802d-dccecb39064d)
![image](https://github.com/user-attachments/assets/651c0873-c9f7-40c7-a381-c3d56225ca0e)

When trying to set a new value from the API (overrideConfig), same, nothing changes:
![image](https://github.com/user-attachments/assets/36e69f43-5c4f-407d-8874-56e2c18abcb2)

**Comment by HenryHengZJ** [comment]
fixed now via: https://github.com/FlowiseAI/Flowise/pull/3168
