### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'toLowerCase') - Worker Agent

### ISSUE THREAD

**Issue by TopAgrume** [FlowiseAI/Flowise#2868]
I'm having trouble with the Flowise Worker.
This error occasionally appears (non-deterministically) when I run a multi-agent flow (Supervisor/Workers).

In the case where I don't provide any Tool to my worker (which doesn't need one), this error appears every time. To mitigate the problem, I tried adding an unnecessary tool (calculator), which resolves it for a short time before the error reoccurs. Refreshing the connection between the Tool and the Worker is sometimes not enough

Another issue of this type was closed without being resolved: See: [#2314](https://github.com/FlowiseAI/Flowise/issues/2314)

Here is my AgentFow:
![image](https://github.com/user-attachments/assets/6291bab7-e4a3-4ed5-9573-87a517afa59e)

Here is what is displayed in the Chat:
![image](https://github.com/user-attachments/assets/b020db3b-bf10-42e3-aaf2-3c76ed89d5b0)

Here is what is displayed in LangSmith:
![image](https://github.com/user-attachments/assets/69bcb115-3eec-4f32-ada8-9f10ed128bcd)

Feel free to let me know if you need any adjustments or additional details included.

**Comment by HenryHengZJ** [comment]
thanks for the error message. It happens randomly because LLM failed to output the tool name, hence causing this line to return error:
![image](https://github.com/user-attachments/assets/10e7d41a-3ac0-4274-86c2-52b6f4b15d1e)

**Comment by HenryHengZJ** [comment]
Opened a bugfix PR to avoid returning error, however the root cause is still there, LLM is not able output the tool name correctly

**Comment by NicolasCampana** [comment]
@HenryHengZJ I'm having the same problem. 
But on tool node/agent from sequential agents. 
If I remove or duplicate the node, it works. Very randomly.
