### ISSUE TITLE
[FEATURE] Interface similar to Langflow - node windows

### ISSUE THREAD

**Issue by severfire** [FlowiseAI/Flowise#2872]
**Describe the feature you'd like**
I would be great ot have interface look and some functionalities similar to Langflow 

In node windows, it would be great to be able to:
- change title of the node 
- add note to the node
- hide/show not needed fields
- the feel of Langflow
- etc

Langflow is open source, so why not to try take parts of its code :-)

**Comment by HenryHengZJ** [comment]
we are improving our UI/UX, there are pieces we can learn from each other! can move this to discussion as its not a bug/issue
