### ISSUE TITLE
EMFILE: too many open files

### ISSUE THREAD

**Issue by BoyuanGao** [FlowiseAI/Flowise#2878]
**Describe the bug**
When i trying to use the API of workflow in 3000 times, it show me this error

**Screenshots**
{
    "statusCode": 500,
    "success": false,
    "message": "EMFILE: too many open files, open 'C:\\Users\\gaoby\\AppData\\Roaming\\npm\\node_modules\\flowise\\node_modules\\flowise-ui\\build\\index.html'",
    "stack": {}
}

![image](https://github.com/user-attachments/assets/4f3be7cf-ddf7-4185-9623-a5fb80d52fd3)

**Setup**

-   Installation `npx flowise start`
-   Flowise Version : 1.8.4
-   OS: Win11

**Additional context**

**Comment by HenryHengZJ** [comment]
Not sure how to fix this, but can you add throttling or some delays between API requests?
