### ISSUE TITLE
[FEATURE] Add support for custom API domain through self-hosted OpenAI forwarding service

### ISSUE THREAD

**Issue by shydow** [FlowiseAI/Flowise#288]
**Describe the feature you'd like**
Add support for custom API domain through self-hosted OpenAI forwarding service

**Additional context**
Currently, the API domain for this project is fixed and cannot be customized. However, it would be useful to have the ability to use a custom domain for the API, especially for those who want to use a self-hosted OpenAI forwarding service.

I propose that we add a new configuration option that allows users to specify their own API domain, which can then be used to route requests through a self-hosted OpenAI forwarding service.

This would enable users to have greater control over their API requests and provide a more flexible solution for those who want to use their own infrastructure.

Thank you for considering this feature request!

**Comment by shydow** [comment]
Sorry, I find the repeat.

relate to this - #264

**Comment by HenryHengZJ** [comment]
let us know if #264 is able to satisfy your requirement

**Comment by shydow** [comment]
#264 and it works great for me. Thank you for your help!
