### ISSUE TITLE
[When clicking Plus button to add nodes immediately focus cursor on text area]

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#2881]
**Describe the feature you'd like**
To add a new node, first I need to click on the "+" button:
![image](https://github.com/user-attachments/assets/76a4a78d-a165-41fb-bfb6-2946c7f8b6d9)

Afterwards, I wanna be able to immediately type to search the node I need, e.g. "rera" to find the rerank retriever quickly. 

However, as of now, I always need to click inside the text area first so that I can type. 
I'd like to have the text input area auto-focused so that I can start typing immediately.

Not auto-focused:
![image](https://github.com/user-attachments/assets/2c56da22-4b98-4d74-b242-676a31752924)

**Additional context**
Firefox, flowise 1.8.4

**Comment by HenryHengZJ** [comment]
should be an easy fix by just adding autoFocus
