### ISSUE TITLE
rander [BUG]

### ISSUE THREAD

**Issue by lb1223** [FlowiseAI/Flowise#289]
**Describe the bug**
Jun 10 06:30:57 PM  Error: ENOENT: no such file or directory, stat '/opt/render/project/src/node_modules/flowise-ui/build/index.html'

**To Reproduce**

1. Go to 'RENDER...'
2. Click on '.DEPLOY...'
3. Scroll down to '.Jun 10 06:30:57 PM  Your service is live 🎉
Jun 10 06:30:57 PM  Error: ENOENT: no such file or directory...'
stat '/opt/render/project/src/node_modules/flowise-ui/build/index.html'

**Expected behavior**

**Screenshots**

**Setup**

-   OS: [e.g. iOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
are you following the guide here - https://docs.flowiseai.com/deployment/render ?

**Comment by lb1223** [comment]
Thanks, it worked after manual redeployment
