### ISSUE TITLE
[BUG] Cannot select gpt-3.5-turbo model from OpenAI

### ISSUE THREAD

**Issue by batrashi** [FlowiseAI/Flowise#290]
**Describe the bug**
Cannot select another model except those that are pre-listed in the Model Name menu. When I try to type the model manually, it disappears.

**To Reproduce**
Simply add OpenAI node and try "gpt-3.5-turbo" for model name.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/38015257/439db18e-bcfc-46c9-bf79-3ba22db2aeab)

**Comment by HenryHengZJ** [comment]
its under `Chat Models`

**Comment by ZarkoRashev** [comment]
Thanks, I am super fresh and did not see it 👌🙄🙂

**Comment by batrashi** [comment]
My bad, its in another category!
