### ISSUE TITLE
[BUG] DeepInfra BGE-m3 embedding upsert generate [ERROR]: Error: 404 status code (no body)

### ISSUE THREAD

**Issue by davide445** [FlowiseAI/Flowise#2903]
**Describe the bug**
Trying DeepInfra as OpenAI Embedding Custom I got always this error trying to upsert both on Qdrant and In Memory

**To Reproduce**

1. Test using https://deepinfra.com/BAAI/bge-m3/api?example=openai-emb-js
2. Try to upsert from any source

**Expected behavior**
Complete the upsert in the vectordb

**Screenshots**
![image](https://github.com/user-attachments/assets/955d4e86-2941-40aa-9911-5557711b81d9)

**Flow**
[DeepInfra test Chatflow.json](https://github.com/user-attachments/files/16415697/DeepInfra.test.Chatflow.json)

**Setup**

-   Installation `npx flowise start`
-   Flowise Version 2.0.1
-   OS: Linux
-   Browser firefox

**Additional context**

**Comment by davidezari** [comment]
Wa my fault I needed to use the Base URL and the apiKey shown after the model deployment
Closed
