### ISSUE TITLE
Please help me..."Agent stopped due to max iterations."[BUG]

### ISSUE THREAD

**Issue by ForgottenFrog** [FlowiseAI/Flowise#291]
I've been trying to create an app, but whenever I try to use more than 1 user, it says "Agent stopped due to max iterations."
How can I create different conversations for each individual user? Even with the memory, it started replying to the second user what the first user actually asked.
Can you, please, help me?

**Comment by HenryHengZJ** [comment]
hey @ForgottenFrog Flowise is still single user based, i.e messages/memory is per chatflow, not per user.
