### ISSUE TITLE
[FEATURE] Use larger column to be able to save large chatflows

### ISSUE THREAD

**Issue by sylvain-adeo** [FlowiseAI/Flowise#2918]
**Describe the feature you'd like**
I would like the mysql table column flowData to be MEDIUMTEXT

**Additional context**
I had this error message when saving my flow:
Failed to save Agent: Error: chatflowsService.updateChatflow - Data too long for column 'flowData' at row 1

Solved it by running
ALTER TABLE `chat_flow` 
CHANGE COLUMN `flowData` `flowData` MEDIUMTEXT NOT NULL ;

**Comment by HenryHengZJ** [comment]
we've changed it to longtext, will be pushed in next release - https://github.com/FlowiseAI/Flowise/pull/2908
