### ISSUE TITLE
[Question] Obtain Chatlfow ID

### ISSUE THREAD

**Issue by Bandikyu** [FlowiseAI/Flowise#2919]
**Describe the feature you'd like**
Hi, i'm not sure if this is already an existing feature or if I should suggest it as a possible enhancement (I looked through the GitHub issues but couldn't find anything). **I'm trying to obtain the ID of the flows (the ID that appears in the URL when I generate a new flow). Where could I find or modify this ID?**

Thanks in advance.

**Comment by HenryHengZJ** [comment]
this ID is not modifiable, in what scenario you trying to obtain the ID? through API?
