### ISSUE TITLE
[FEATURE] Implement Metadata Filtering for MongoDB Atlas

### ISSUE THREAD

**Issue by pollitoconpapass** [FlowiseAI/Flowise#2925]
I am writing to suggest the implementation of Metadata Filtering for MongoDB Atlas. 
Flowise currently supports Metadata Filtering with Pinecone, a fantastic feature. However, it would be incredibly useful if we also had Metadata Filtering support for MongoDB Atlas.

### Pinecone Additional Parameters:
![image](https://github.com/user-attachments/assets/1e787596-15ab-4ade-a513-6e8d1d7f9959)

### MongoDB Atlas Additional Parameters
![image](https://github.com/user-attachments/assets/a14ddc2c-cce6-4ff1-8a21-35e60e7e37c7)

Thank you for considering this suggestion,

Regards.

**Comment by concoursdude** [comment]
+1 on this idea, would love to see it.

**Comment by nitish-chhabra** [comment]
Pinecone has many limitations. We wanted to shift to MongoDB but because the metadata filter is not implemented we can't shift.
Is there an ETA on when you plan to implement this?
Or any workaround by building this on a custom node?

**Comment by HenryHengZJ** [comment]
Merged: https://github.com/FlowiseAI/Flowise/pull/3333

![image](https://github.com/user-attachments/assets/5c5db47b-2126-4518-8f26-4e40c79e0734)
