### ISSUE TITLE
[FEATURE] Support to invoke flow through API instead of chat interface

### ISSUE THREAD

**Issue by Mohit21GoJs** [FlowiseAI/Flowise#2930]
**Describe the feature you'd like**
We would like to know if there is any documentation related to documentation of invoking the flow from api call?

**Additional context**
We have a service where we crawl websites and transform the data on our side and feed it to an external service after a given interval, i have made a flow which achieves above and also calculates diff from last version and feeds it to the external service but i am unable to invoke it through api call.

**Comment by danieldabate** [comment]
You can find it here: https://docs.flowiseai.com/using-flowise/api
