### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by otaviojanoskii** [FlowiseAI/Flowise#2937]
**Describe the bug**
Getting repeatedly this error from OpenAI in chat: "Error: predictionsServices.buildChatflow - The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error."

**To Reproduce**

1. Make any question to an Agent on test environment
2. Returns the error

**Expected behavior**
Gets the answer of OpenAi

**Screenshots**
![Captura de Tela 2024-08-05 às 13 19 17](https://github.com/user-attachments/assets/b36e78ac-c196-4ac3-904c-c73ab86d342e)

**Setup**

-   Installation docker
-   Flowise Version 2.0.2
-   OS: [ubuntu-2gb-nbg1-1]
-   Browser Chrome

**Additional context**
It started happening after updating for the latest version of Flowise

**Comment by HenryHengZJ** [comment]
Try checking your OpenAI API key, or create new one

**Comment by HenryHengZJ** [comment]
Closing as duplicated - https://github.com/FlowiseAI/Flowise/issues/2937
