### ISSUE TITLE
[BUG] env: node\r: No such file or directory

### ISSUE THREAD

**Issue by JBX028** [FlowiseAI/Flowise#2938]
**Describe the bug**
I wanted to upgrade Flowise, which is installed on my laptop and for which I regularly upgrade the version, but Flowise doesn't start. I am not seeing any particular errors during the upgrade process.

**To Reproduce**

1. npm install -g flowise
2. npx flowise start
3. **env: node\r: No such file or directory**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/7907db99-4d27-42b0-bb13-394858a91d10)

**Setup**

-  npx flowise start
-  flowise@2.0.2
-  MACOS 14.1 (23B74)
-  Chrome 127.0.6533.89

**Important**

I have a dozen of flows already that I created with <=2.0.1 that I would like to keep alive if possible :)

**Comment by JBX028** [comment]
I'm not sure what happened, but I tried many things and suddenly decided to run "npx flowise start" in the terminal of VSCode instead of iTerm2, and it worked; since then, any subsequent execution in iTerm2 has been working fine.

**Comment by porcorussell** [comment]
I have the same issue even via VScode

**Comment by porcorussell** [comment]
Got it working by running `dos2unix ./bin/run`

**Comment by syedamanat** [comment]
on mac 

`brew install dos2unix`
`npm root -g` to find where your global packages are stored lets call it `PATH` 
`dos2unix /Users/<username>/.nvm/versions/node/v20.11.0/lib/node_modules/flowise/bin/run` 
the `v20.11.0` is my version, make sure you know the `PATH` 
once the execution of `dos2unix` is successful you will get a message like below 
`dos2unix: converting file /Users/<username>/.nvm/versions/node/v20.11.0/lib/node_modules/flowise/bin/run to Unix format...` 
`npx flowise start`

Hope it helps!

**Comment by hugoblanc** [comment]
> on mac
> 
> `brew install dos2unix` `npm root -g` to find where your global packages are stored lets call it `PATH` `dos2unix /Users/<username>/.nvm/versions/node/v20.11.0/lib/node_modules/flowise/bin/run` the `v20.11.0` is my version, make sure you know the `PATH` once the execution of `dos2unix` is successful you will get a message like below `dos2unix: converting file /Users/<username>/.nvm/versions/node/v20.11.0/lib/node_modules/flowise/bin/run to Unix format...` `npx flowise start`
> 
> Hope it helps!

Well done champ
