### ISSUE TITLE
[BUG] Embeddings ko: localAI, Ollama, Mistral

### ISSUE THREAD

**Issue by IzzyHibbert** [FlowiseAI/Flowise#2944]
**Describe the bug**
I am using Flowise 2.0.1
I am trying to setup a workflow and I prefer to work with embeddings which are not OpenAI.

Using a **LocalAI** Embeddings => **Bad Request**
Using **MistralAI** Embeddings => **Bad Request**
Using **Ollama** Embeddings => **Request to Ollama server failed: 500 Internal Server Error**

The local embeddings (LocalAI, Ollama) are correctly available, tested with Postman they work.  In addition, a test to exclude issues of ports/communication/infrastucture has been performed from another machine: all ok.

The flow is a RAG with a 20 pages PDF in Qdrant.
As soon as OpenAI embeddings is in place, it all work smoothly 🫤

**To Reproduce**

**LocalAI :** (text-embedding-ada-002)
(_pls consider that when I use a LocalAI chat model I have no issues at all_)
The setup and error..
![Screenshot 2024-08-06 alle 12 01 28](https://github.com/user-attachments/assets/d370ff24-a94f-4b7a-a3c8-411031c71ef8)
The correct answer of the model when debugging it from the LocalAI side, where all seems fine ...
![Screenshot 2024-08-06 alle 12 02 04](https://github.com/user-attachments/assets/4350d193-29e9-42e7-a131-0e037a916809)

**Mistral:**
(_pls consider that I have a key fully working and when using a Mistral Chat model I have no issues at all_)
![Screenshot 2024-08-06 alle 12 06 58](https://github.com/user-attachments/assets/3a378631-99c9-495c-979d-c1b705098fd6)

**Ollama** (nomic-embed-text)
![Screenshot 2024-08-06 alle 12 07 48](https://github.com/user-attachments/assets/c523a85c-d99d-4e75-b468-6de62e04a18f)

I am including the screenshots and the details are visible. There is anything special.

**Expected behavior**
I'd expect to be able to use any of the embeddings alternatives.

**Screenshots**
IIncluded

**Setup**

-   Installation : Docker
-   Flowise Version : 2.0.1
-   OS: Win
-   Browser : Chrome

**Comment by HenryHengZJ** [comment]
If you are running both Ollama and Flowise on Docker, try this - https://docs.flowiseai.com/integrations/langchain/chat-models/chatollama#additional

**Comment by HenryHengZJ** [comment]
same with LocalIA - https://docs.flowiseai.com/integrations/langchain/chat-models/chatlocalai#flowise-setup

**Comment by IzzyHibbert** [comment]
> same with LocalIA - https://docs.flowiseai.com/integrations/langchain/chat-models/chatlocalai#flowise-setup

I hope the following details will help solving the issues.

My attempts :
**Flowise (docker) => LocalAI (docker)
Flowise (docker) => Ollama (no-docker, just in Windows)**

### **Case: Flowise (docker) => LocalAI (docker)**
There is - apparently - the ability of the LocalAI Chat model to reach anyway the endpoint even when in the form
http://192.168.178.76:8080
See here the success, but in this case I used OpenAI embedding, which is the only one working in this environment.
![LocalAI Chat](https://github.com/user-attachments/assets/383c9892-2867-4e43-b596-bf96c11bcff8).
I have my answer in the chat.

Now I bring in the LocalAI embedding (keep in the LocalAI Chat model) and still use the endpoint 
http://192.168.178.76:8080 in both (embedding and chat model).
As visible here (LocalAI debug view) the call to the endpoint is successful and the embedding is transforming the text into vectors.
![LocalAI Embedding](https://github.com/user-attachments/assets/8063f96d-b5ae-4a3f-8f1a-25504f617940)
....but there is a "Bad Request" in the chat.

Now I update the Base path to: http://host.docker.internal:8080/v1 as per your suggestion. 
Still the endpoint is reached and the embedding works
![endpoint](https://github.com/user-attachments/assets/26e7941b-ea65-4203-9bf6-1570a719f26c)
But again the problem is still the same, Bad Request

![Screenshot 2024-08-07 alle 09 37 22](https://github.com/user-attachments/assets/bdc78b65-09eb-4962-a886-299fc6e6eec4)

Bottomline. My understanding is that the embedding endpoint works apparently well but Flowise is not and is throwing exceptions no matter the embedding I am using (common problem or different I cannot tell).
The Bad Request message behind the scenes is still like this

![Screenshot 2024-08-07 alle 09 34 22](https://github.com/user-attachments/assets/080d96ef-2e8b-4699-ba4a-d2035ecab7f6)


### **Case Flowise (docker) => Ollama (no-docker, just in Windows)**
The Ollama endpoint is at http://192.168.178.76:11434 in the test I am keeping the LocalAI chat model and just using Ollama Embedding model (installed in Win, no docker).

The issue here is shown in this picture 
![Screenshot 2024-08-07 alle 09 48 43](https://github.com/user-attachments/assets/c51907af-eb65-4d8c-9799-41d3f0f4f49b)
while FLowise error detail being displayed in Docker is 
![Screenshot 2024-08-07 alle 09 49 31](https://github.com/user-attachments/assets/026e4cb8-2504-4629-b8c9-8a32f84f23ce)

Now let's repeat the same in Postman. The endpoint , in Flowise I use http://192.168.178.76:11434, in Postman is visible here. The Postman test is successful.

![Screenshot 2024-08-07 alle 09 50 53](https://github.com/user-attachments/assets/c994a8e4-8279-4015-b5fc-320a247ea169)


### **Last case. Mistral Embeddings (model name: mistral-embed).**

The outcome is this :
![Screenshot 2024-08-07 alle 09 56 31](https://github.com/user-attachments/assets/02b50fa4-10fd-4f48-8667-6378f74ca668)

with Flowise debug being 

![Screenshot 2024-08-07 alle 09 57 03](https://github.com/user-attachments/assets/6af8258d-5f50-451d-8ff4-c6136165e222)

My 2 cents:
One could think that using stuff locally brings in issues with infrastructures, ports, etc which is understandable. My tests are here showing, when possible (LocalAI debug) that the requests are reaching the endpoints and processed. In Mistral case I also am excluding these variables and the embedding should perform as nicely as with OpenAI.

**Comment by IzzyHibbert** [comment]
Closing the ticket as it contains multiple issues, not connected into one.

The three topics have been separated into different threads : 

2976 Ollama
2977 LocalAI
2978 Mistral
