### ISSUE TITLE
[BUG] HTML Embeded not working

### ISSUE THREAD

**Issue by noblerboy2004** [FlowiseAI/Flowise#2946]
**Describe the bug**
I'm using flowise and generate html embeded. I tried to insert the code into one page of HTML. Try to chat but response is error.
![image](https://github.com/user-attachments/assets/f6dc0b55-2446-4ec1-81ca-e18f336fb678)

Log of flowise continer
![image](https://github.com/user-attachments/assets/7722942e-cdc1-4e1d-8f01-8da25c797054)

**To Reproduce**

1. Go to one chat flow
2. Click on 'Embed in website or use as API'
3. Copy code and insert to one page of HMTL

**Expected behavior**
FLowise receive not correct request. And log show ? before api request

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation in docker-desktop with command docker-compose up
-   Flowise Version [3.1]
-   OS: [ Windows desktop]
-   Browser [e.g. chrome, ]

**Additional context**

**Comment by HenryHengZJ** [comment]
Looks like it cant reach your Flowise server, maybe its under proxy?

**Comment by noblerboy2004** [comment]
![image](https://github.com/user-attachments/assets/9724f4d9-cfd2-48a7-b1eb-900a39affaa1)
This fixed my problem. Thank you.
