### ISSUE TITLE
Error: 400 Invalid 'messages[5].name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$[BUG]

### ISSUE THREAD

**Issue by PauloSeze** [FlowiseAI/Flowise#2948]
When using Flowise V2.0.2 installed via Docker on Easypanel, an error occurs indicating that the value of 'messages[5].name' does not match the expected pattern. The error message is: "Error: 400 Invalid 'messages[5].name': string does not match pattern. Expected a string that matches the pattern '^[a-zA-Z0-9_-]+$'".

Install Flowise V2.0.2 via Docker on Easypanel.
Set up a flow that includes a 'messages' array with multiple entries.
Ensure one of the 'messages' entries (e.g., 'messages[5]') contains a 'name' with characters outside the allowed pattern ('^[a-zA-Z0-9_-]+$').
Execute the flow.
See the error.

The 'name' value in the 'messages' array should comply with the pattern '^[a-zA-Z0-9_-]+$' and the flow should execute without errors when all 'name' values are valid.

Screenshots

Definição de uma variável de estado chamada 'name':
![image](https://github.com/user-attachments/assets/4eb70f49-926b-4104-9006-c913e26afb95)

Condição para verificar se a variável está vazia:
![image](https://github.com/user-attachments/assets/1b389154-2fc6-42be-8614-96845ea5866f)

LLM node para identificar nome na mensagem e retornar um json 'name1':
![image](https://github.com/user-attachments/assets/6ac6a3f8-8f69-442d-b366-af495523a476)

Atualização da variável de estado 'name' com o output 'name1':
![image](https://github.com/user-attachments/assets/ff6deef9-f644-4103-884f-f34f4603c6c1)

Agente recebendo a variável nome com o parâmetro 'name':
![image](https://github.com/user-attachments/assets/b89d814b-9f33-4a62-861c-465593a39390)

Mapeamento correto do nome:
![image](https://github.com/user-attachments/assets/48d846df-de72-4365-ad10-776bfc8308e3)

Passagem pela condição quando 'name' já não estava mais vazia:
![image](https://github.com/user-attachments/assets/2fccac29-044c-4a9b-9931-e2df818f331d)

Erro ao interagir com o assistente final:
![image](https://github.com/user-attachments/assets/5f6eb5ea-c6b2-4303-8039-5310ad63c283)

Flow
[Sequential 2 Agents.json](https://github.com/user-attachments/files/16512312/Sequential.2.Agents.json)

Setup

Installation: Docker on Easypanel
Flowise Version: V2.0.2
OS: Linux (Ubuntu 20.04)
Browser: Chrome 91.0.4472.124

**Comment by HenryHengZJ** [comment]
can you try renaming the `name` to other namings like `myname`

**Comment by Setter04** [comment]
I have the same problem and unfortunately simply renaming the varibale is not enough

**Comment by ACTDigital10** [comment]
Estou passando pelo mesmo problema

**Comment by ACTDigital10** [comment]
![Captura de tela 2024-09-20 154112](https://github.com/user-attachments/assets/299ee30b-f888-422f-b1d0-5a5aff6621d4)

**Comment by nestor-is-a-developer** [comment]
Hello @HenryHengZJ ! 
How did you solve this issue? I'm facing the same.
Thanks in advance.

**Comment by nestor-is-a-developer** [comment]
For me, I removed spaces from the agents name and It seems that the error dissapeared
