### ISSUE TITLE
[BUG] Feedback buttons missing on web embed

### ISSUE THREAD

**Issue by palm-ER** [FlowiseAI/Flowise#2953]
**Describe the bug**
Feedback buttons missing on web embed despite being enabled.

**To Reproduce**

1. Create webpage using 'Fullpage Html' embed code
2. Chat
3. No feedback buttons shown. They are working on the chat in the Flowise interface.

**Expected behavior**
Feedback buttons should be available

**Setup**
-   Installation docker
-   Flowise Version 2.0.2
-   OS: Linux
-   Browser any

**Comment by HenryHengZJ** [comment]
should be resolved in embed v1.3.11 (PR: https://github.com/FlowiseAI/FlowiseChatEmbed/pull/224)
