### ISSUE TITLE
[BUG] ReAct Agent for LLMs couldn't invoke tool.

### ISSUE THREAD

**Issue by wellCh4n** [FlowiseAI/Flowise#2959]
**Describe the bug**
ReAct Agent for LLMs couldn't invoke tool.

**To Reproduce**

1. Create a "ChatFlow".
2. Add "React Agent for LLMs" Node.
3. Add "ChatOpenAI" Node or "OpenAI" Node.
4. Add "Custom Tool" and Select a NO Args tool.

**Expected behavior**
return current time in my case

**Screenshots**
<img width="1428" alt="image" src="https://github.com/user-attachments/assets/42219333-c744-4425-b092-d82f50185955">
<img width="1426" alt="image" src="https://github.com/user-attachments/assets/a8756c68-c92d-4612-9bf6-827233f8bedf">

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation pnpm start
-   Flowise Version 2.0.2
-   OS: macOS
-   Browser chrome

**Additional context**
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/f023b683-2f3e-47f1-bcde-8216d35fb45f">
`await this.schema.parseAsync(arg)` throw a exception when arg is a empty string.

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/7f02ee85-56a0-470b-9cc7-de1e1c8798af">
No tool call in langsmith

**Comment by HenryHengZJ** [comment]
If you want to invoke tool, try using Tool Agent

**Comment by wellCh4n** [comment]
> If you want to invoke tool, try using Tool Agent

Yes, tool agent is ok.
What confuses me is that the ReActAgent also has allowed tools, but I’m unable to use them. Is this due to a known bug or some other reason?

**Comment by wellCh4n** [comment]
I see. cuz no function call in ReAct Agent. so, input params can not parse to object.
