### ISSUE TITLE
[BUG] Docker image 2.0.3 not working

### ISSUE THREAD

**Issue by danieldabate** [FlowiseAI/Flowise#2967]
**Describe the bug**
When running the newest version 2.0.3 of the docker image, it doesn't run and exists with this error:
` ›   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load
 ›   /usr/local/lib/node_modules/flowise/dist/commands/start.js: Cannot find
 ›   module 'langchainhub'
 ›   Require stack:
 ›   - /usr/local/lib/node_modules/flowise/dist/services/load-prompts/index.js
 ›   -
 ›   /usr/local/lib/node_modules/flowise/dist/controllers/load-prompts/index.js
 ›   - /usr/local/lib/node_modules/flowise/dist/routes/load-prompts/index.js
 ›   - /usr/local/lib/node_modules/flowise/dist/routes/index.js
 ›   - /usr/local/lib/node_modules/flowise/dist/index.js
 ›   - /usr/local/lib/node_modules/flowise/dist/commands/start.js
 ›   - /usr/local/lib/node_modules/flowise/node_modules/@oclif/core/lib/module-
 ›   loader.js
 ›   - /usr/local/lib/node_modules/flowise/node_modules/@oclif/core/lib/config/
 ›   plugin.js
 ›   - /usr/local/lib/node_modules/flowise/node_modules/@oclif/core/lib/config/
 ›   config.js
 ›   - /usr/local/lib/node_modules/flowise/node_modules/@oclif/core/lib/config/
 ›   index.js
 ›   - /usr/local/lib/node_modules/flowise/node_modules/@oclif/core/lib/command
 ›   .js
 ›   -
 ›   /usr/local/lib/node_modules/flowise/node_modules/@oclif/core/lib/index.js
 ›   - /usr/local/lib/node_modules/flowise/bin/run
 ›   Code: MODULE_NOT_FOUND`

**To Reproduce**
1. `docker run flowiseai/flowise:2.0.3`

**Expected behavior**
Flowise should start successfully 

**Setup**

-   Installation [docker]
-   Flowise Version [2.0.3]
-   OS: [macOS, Linux]

**Comment by bradfair** [comment]
I'm not sure if this error is relevant, but it points to a line that looks langchain related: 
```
13 0.798  WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
#13 0.798 	* error performing lockfile operation: Unable to convert to yaml: could not find expected ':' at line 19384 column 3138, while scanning a simple key at line 19384 column 5
```
