### ISSUE TITLE
[BUG] - Update variable using a custom tool don't work

### ISSUE THREAD

**Issue by alziromoraes** [FlowiseAI/Flowise#2968]
**Describe the bug**
I created a variable and I need to change its value during the flow with api callback. Using $vars.VariableName does not change the value stored for the variable in other calls.

**Expected behavior**
The variable value should be updated and persisted in the database

**Setup**

-   Installation docker
-   Flowise Version 1.8.2
-   OS: Linux

How can I update the values ​​of these variables?

**Comment by danieldabate** [comment]
I don't think this is a bug, variables are not supposed to be modified and persisted across flow calls.

Could you explain your use case? Maybe it can be solved in another way.

**Comment by alziromoraes** [comment]
To connect to an external API I need to request a token, which has an expiration date, to send in all requests. I need to check the expiration to request a new token and I cannot always request a new token due to limit issues from the API provider.

I thought about storing the token and the expiration date in variables so I can check it in the custom tool.

Another thing I need is to be able to place this verification code in a separate function because I will have to call it in several custom tools and I have already tried several ways without success.

Tks

**Comment by danieldabate** [comment]
About the repeating code, you can have a custom tool that retrieves the token, storing it/retrieving it from a cache if necessary. The agent would have to use it every time it needs to call a tool.

There are a few alternatives here, depending on your infrastructure setup. One alternative is to store the token in a file in disk, but that will only work well if you have one replica of Flowise running and you have persistent storage.

Another way is using an external database or storage. S3, DynamoDB, etc. might work. You might event be able to store it in the same Postgres instance you are using for Flowise.

I know that this is more work than just changing a variable, but it's the only solution I can think of atm.

Let's see what others think.

**Comment by HenryHengZJ** [comment]
You can pass it here: https://docs.flowiseai.com/integrations/langchain/tools/custom-tool#pass-variables-to-function
```
"overrideConfig": {
        "vars": {
            "apiKey": "abc"
        }
    }
```

**Comment by schieck0** [comment]
As mentioned here, I also cannot set a value in variables using the API.
https://github.com/FlowiseAI/Flowise/issues/2991#issuecomment-2296643132

**Comment by AnnoyingTechnology** [comment]
> you can have a custom tool that retrieves the token

With long chains of function calling, the model tends to mess up. 
In my case I have an API token per database, and at some point the model collapses and uses the wrong tokens.
Being able to use **flow variable and have the custom tool read/write to it would be much more reliable**, and it would let the model focus on the relevant stuff. 

@HenryHengZJ this has been marked as _completed_ but doesn't point to a commit ?

Can you please document how this has been completed ?
