### ISSUE TITLE
[FEATURE] Conversational Retrieval QA Chain with memory buffer

### ISSUE THREAD

**Issue by dkrief** [FlowiseAI/Flowise#297]
Hi, thanks for this amazing tool.

Is it possible to have the component called "Conversational Retrieval QA Chain", but that would use a memory buffer ? To remember the rest of the conversation, not only the last prompt.

I tried to chain it with the chain tool but i'm unsure it's really possible.

**Comment by HenryHengZJ** [comment]
`ConversationalRetrievalQAChain` internally is using a BufferMemory already - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chains/ConversationalRetrievalQAChain/ConversationalRetrievalQAChain.ts#L109

Are you having issue using `ConversationalRetrievalQAChain` to follow up on previous conversation?

**Comment by dkrief** [comment]
thanks for your swift response. No it's ok, i found what i needed.
I'd just like to customise the message given in the chain to make the model understand it's historical data... it says "given the following conversation...etc"
And I'd like to put it in other languages like French.

**Comment by HenryHengZJ** [comment]
in the system prompt, specify something like this:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/f426ec1f-b8db-41a7-a596-8cf2928c73b4)

`I want you to act as a document that I am having a conversation with. Your name is "AI Bot". You will provide me with answers from the given info. Only reply me in Chinese. If the answer is not included, say exactly "我不知道" and stop after that. Refuse to answer any question not about the info. Never break character.`

then it will reply in the language u asked for:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/bb06ace8-7844-49c5-8e09-fef16e9b3ab2)

**Comment by dkrief** [comment]
thanks a lot !
