### ISSUE TITLE
[BUG] Mistra-embed: Bad request

### ISSUE THREAD

**Issue by IzzyHibbert** [FlowiseAI/Flowise#2978]
I decided to open single and specific tickets instead of a unique one [2944](https://github.com/FlowiseAI/Flowise/issues/2944) because after a bit of investigation the KO on different embeddings have nothing in common.

Test performed on Flowise 2.0.1, installed in Docker.

### **Mistral Embeddings (model name: mistral-embed).**

The outcome is this :
![Screenshot 2024-08-07 alle 09 56 31](https://github.com/user-attachments/assets/02b50fa4-10fd-4f48-8667-6378f74ca668)

with Flowise debug being 

![Screenshot 2024-08-07 alle 09 57 03](https://github.com/user-attachments/assets/6af8258d-5f50-451d-8ff4-c6136165e222)

**Comment by HenryHengZJ** [comment]
what is your settings? Flowise running on Docker, and Mistral cloud embeddings? or self hosted

**Comment by IzzyHibbert** [comment]
> what is your settings? Flowise running on Docker, and Mistral cloud embeddings? or self hosted

Flowise is in Docker, Mistral it's their cloud.

**Comment by HenryHengZJ** [comment]
I'm running Flowise on Docker, using Mistral cloud:

![image](https://github.com/user-attachments/assets/74b3846b-be37-4e67-9196-2bca3d8efac6)

![image](https://github.com/user-attachments/assets/bc6e6ad9-3556-4856-9863-363e0462e04d)

seems to be working as expected

**Comment by HenryHengZJ** [comment]
I think this is the default message coming from 3rd party, we could have a look and see how to improve the error messaging and validation check in future. Closing for now
