### ISSUE TITLE
Cannot create property 'chatHistory' on string '' [BUG]

### ISSUE THREAD

**Issue by ms6rb** [FlowiseAI/Flowise#298]
**Describe the bug**
I'm getting this error ``Cannot create property 'chatHistory' on string ''`` in the chat on a fresh install.

**To Reproduce**
1- Install
2- Add OpenAI agent and MRKL agent for LLMs (any agent actually)
3- Chat with the bot
4- See error in the chat ``Cannot create property 'chatHistory' on string ''``
5- See error in the browser console:
```
xhr.js:220 
POST http://localhost:3000/api/v1/internal-prediction/7e589d54-11e0-4ee0-b0c1-7a598c885163 500 (Internal Server Error)
```
 
**Expected behavior**
I expected to get a response from the bot.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/33758164/ffb9bf69-0c7c-4296-a60f-1fbf347e3389)

**Setup**

-   Browser: Microsoft Edge Version 114.0.1823.41 (Official build) (64-bit)
-   OS: Windows 11
-   Node v19.9.0
-   npx\npm 9.6.5

**Comment by HenryHengZJ** [comment]
connect `Memory` of ConversationalAgent to a memory node like `BufferMemory`

**Comment by ms6rb** [comment]
> connect `Memory` of ConversationalAgent to a memory node like `BufferMemory`

well, idk what is this
![image](https://github.com/FlowiseAI/Flowise/assets/33758164/f0e72946-0d5e-49bc-b5c0-18c5200c71dd)

```json
{{
    "action": string, // The action to take. Must be one of []
    "action_input": string // The input to the action. May be a stringified object.
}}
```". Error: SyntaxError: Expected property name or '}' in JSON at position 1
```

console:

```
:3000/api/v1/internal-prediction/7e589d54-11e0-4ee0-b0c1-7a598c885163:1 
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**Comment by eitanwaxman** [comment]
I'm having the same issue

**Comment by chungyau97** [comment]
Hi @eitanwaxman,

could you share a screenshot of your flow?

**Comment by eitanwaxman** [comment]
@chungyau97 My flow looked exactly like the one above. I did find an answer on the discord - apparently you need to use a Chat LLM Model with a Chat agent. (I was trying to use a regular one). - Now it's working

Thanks!
