### ISSUE TITLE
Is there a way to pass variables to System Prompt via an api call for Conversational Retrieval QA Chain or Tool Agent or Conversation Chain?

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#2991]
@HenryHengZJ How can i pass variables to the System Prompt via the API?

<img width="569" alt="image" src="https://github.com/user-attachments/assets/de5e73cd-243d-4b67-a619-861cbeb78e7f">

I know the following works for nodes that have promptValues defined like Chat Prompt Template. Is there something like this for Conversational Retrieval QA Chain or Tool Agent or Conversation Chain? Trying to find a way so I don't have to override the whole system prompt and just pass the variables necessary.

{"question": "Hi", 
    "overrideConfig": {
        "promptValues": {
            "input_language": "French",
            "output_language": "Italian"
        }
    }
}

**Comment by HenryHengZJ** [comment]
Just added a PR for that https://github.com/FlowiseAI/Flowise/pull/2986

**Comment by vijaykammili** [comment]
Fantastic! Thanks a lot, @HenryHengZJ

**Comment by vijaykammili** [comment]
@HenryHengZJ: This works when you send the variables for the 1st turn but doesn't work for the subsequent turns. 

Here is an example:

1st Turn:

Input Payload:

{
    "question": "Hello",
    "overrideConfig": {
        "sessionId": "88880",
        "vars" : {
            "date": "Jun 4 2024"
        }
    }
}

Output: Jun 4 2024

2nd Turn

Input Payload:

{
    "question": "Hello",
    "overrideConfig": {
        "sessionId": "88880",
        "vars" : {
            "date": "Jun 5 2024"
        }
    }
}

Output: Jun 4 2024

<img width="549" alt="image" src="https://github.com/user-attachments/assets/2c09d56a-3052-4ea3-aa48-836e6958f8a9">

Also, does this work for Tool Agent?

**Comment by HenryHengZJ** [comment]
@vijaykammili in your case, you will need to turn off the cache: `DISABLE_CHATFLOW_REUSE` https://docs.flowiseai.com/configuration/environment-variables

**Comment by vijaykammili** [comment]
@HenryHengZJ  - Thank you. I tried to turn off cache and I still have the same issue.

**Comment by HenryHengZJ** [comment]
does it work if you try a simple conversation chain?
![image](https://github.com/user-attachments/assets/e8da1c2a-1e2c-4d92-b2af-28cba45a18cb)

**Comment by vijaykammili** [comment]
@HenryHengZJ - Nope. It doesn't.  I tested it with a conversation chain.

**Comment by schieck0** [comment]
Same problem here, I can't pass a variable through the API. I tried type static and runtime, but the value doesn't change.
![image](https://github.com/user-attachments/assets/1a8873c4-eed9-42c3-9bc3-5afee37c4827)
![image](https://github.com/user-attachments/assets/75215878-166f-4bcd-90e4-4e773af605bb)

**Comment by HenryHengZJ** [comment]
Im not sure why but it works for me.

1.) 1st request:
![image](https://github.com/user-attachments/assets/bfe06f89-b79c-4d7f-bd4c-3c88d6396772)

2.) 2nd request:
![image](https://github.com/user-attachments/assets/7545ef2f-1591-411e-a317-e2c62477c880)

using a simple flow:
![image](https://github.com/user-attachments/assets/b89faec7-88ec-4948-9aa6-a65a07478b24)

**Comment by vijaykammili** [comment]
@HenryHengZJ  - I tested this again today on version 2.0.7 for Conversation Chain, Tool agent and Conversational Retrieval QA Chain and this is working as expected. Not sure what changed but glad it's working. Thank you.

**Comment by vijaykammili** [comment]
@HenryHengZJ - I've done some additional testing. Is there a limit to the number of variables you can pass via the API? some of the variables don't get passed, it's very inconsistent. Tested with Simple Conversation Chain, Tool Agent and Conv QA Retrieval Chain. 
<img width="1070" alt="image" src="https://github.com/user-attachments/assets/c057fb36-7291-422f-84cf-bcabc46b7950">
<img width="728" alt="image" src="https://github.com/user-attachments/assets/87d78cd0-19df-4ae0-8ccb-5c598d488888">

**Comment by HenryHengZJ** [comment]
@vijaykammili good spot! put up a bugfix here: https://github.com/FlowiseAI/Flowise/pull/3129
