### ISSUE TITLE
ChatGoogleVertexAI - Streaming doesn't work for Gemini Models

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#2994]
@HenryHengZJ - It looks like Streaming doesn't work for Gemini Models for ChatGoogleVertexAI node. ChatOpenAI, AzureChatOpenAI and ChatAnthropic, all of them return a stream of tokens in the websocket but not Gemini models. It just returns a JSON response. 

<img width="969" alt="image" src="https://github.com/user-attachments/assets/087994bc-cac1-4a9e-a556-b22f3746da50">

**Comment by haimco50** [comment]
Yep - noticed this long time ago but forgot to report - @HenryHengZJ  - it would be great to fix this

**Comment by vijaykammili** [comment]
Looks like streaming is working with 2.2.2 version.
