### ISSUE TITLE
multithreading request Prediction API to achieve concurrent operations

### ISSUE THREAD

**Issue by Yakiw** [FlowiseAI/Flowise#2995]
Can I use multithreading to request the Prediction API of Flowise to achieve concurrent operations?

Although I used multithreading in Python, I saw that another request was made after one request was completed in the background.

**Comment by HenryHengZJ** [comment]
yeah but is up to the implementation on your python side to do the multithreading, flowise API by default is just an Node Express API. Moving to discussion
