### ISSUE TITLE
[BUG]tool agent returning "output.match is not a function"

### ISSUE THREAD

**Issue by thebacons** [FlowiseAI/Flowise#2999]
**Describe the bug**
Using Agentflows and the agent "tool agent", it's returning "output.match is not a function" when I add a tool. such as calculator or SerpAPI

**To Reproduce**
Steps to reproduce the behaviour: flow 1st steps as in the video 
https://www.youtube.com/watch?v=YuEw3NTMmT0&t=6s
Create AgentFlow
Add Tool Agent
Add chatAnthropic model
Add buffer memory
Add Calculator (or other tools)

Run the flow and any prompt will trigger the error output.match is not a function". When you delete the calculator the response works as expected
 

**Expected behaviour**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicate the problem.

**Setup**

-   Installation [`npx flowise start`, ] and also checked on Render
-   Flowise Version [flowise@2.0.4](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.0.4)
-   OS: [Windows,]
-   Browser [chrome]

**Additional context**

**Comment by HenryHengZJ** [comment]
there is a bug in 2.0.4, bugfix here - https://github.com/FlowiseAI/Flowise/pull/2990

**Comment by thebacons** [comment]
Thanks. That work fine now :-)
