### ISSUE TITLE
Can't connect openai to buffer memory

### ISSUE THREAD

**Issue by umaar** [FlowiseAI/Flowise#3]
Probably doing something silly, but can't recreate this:

![image](https://user-images.githubusercontent.com/381495/231763818-ac55a535-075f-4462-a5a8-51fccf0b0f48.png)

Can't form a connection between ChatOpenAI and the buffer memory

**Comment by HenryHengZJ** [comment]
The `ChatOpenAI` is not connecting to `Buffer Memory`. Its connected to `Conversational Agent`. It just looks like its connected to Memory but the flow is actually underneath it. Had to squeeze them in a picture so thats why 😅
