### ISSUE TITLE
[FEATURE] Can ChatAlibabaTongyi be added to Chat Models?

### ISSUE THREAD

**Issue by SAIL-Fang** [FlowiseAI/Flowise#3005]
Describe the feature you'd like

Hopefully, the addition of ChatAlibabaTongyi will be more beneficial to developers in China。
like https://js.langchain.com/v0.2/docs/integrations/chat/alibaba_tongyi

**Comment by lzj1991** [comment]
i need ChatAlibabaTongyi

**Comment by HenryHengZJ** [comment]
Good suggestion! Welcome any contribution to that. A similar guide: https://docs.flowiseai.com/contributing/building-node

**Comment by definitelynotchirag** [comment]
@HenryHengZJ Hey i made a Pull Request about this could you look into it?
