### ISSUE TITLE
[BUG] Dependency problems with recent releases of Flowise, including critical vulnerabilities

### ISSUE THREAD

**Issue by Eric-Catalyst** [FlowiseAI/Flowise#3008]
**Describe the bug**
Installing Flowise via npm result in dependency conflicts and use of deprecated package with significant security issues. Problem occurs with 2.0.4 and 2.0.5 releases

**To Reproduce**
1. Clean install of node.js version 20.16.0
2. Installed flowise via npm as follows:

% npm i flowise
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: @mui/icons-material@5.0.3
npm warn Found: react@18.3.1
npm warn node_modules/react
npm warn peerOptional react@">=17.0.0" from lunary@0.6.16
npm warn node_modules/flowise-components/node_modules/lunary
npm warn lunary@"^0.6.16" from flowise-components@2.0.4
npm warn node_modules/flowise-components
npm warn 30 more (flowise-ui, lunary, @emotion/react, @emotion/styled, ...)
npm warn
npm warn Could not resolve dependency:
npm warn peer react@"^17.0.2" from @mui/icons-material@5.0.3
npm warn node_modules/@mui/icons-material
npm warn @mui/icons-material@"5.0.3" from flowise-ui@2.0.4
npm warn node_modules/flowise-ui
npm warn
npm warn Conflicting peer dependency: react@17.0.2
npm warn node_modules/react
npm warn peer react@"^17.0.2" from @mui/icons-material@5.0.3
npm warn node_modules/@mui/icons-material
npm warn @mui/icons-material@"5.0.3" from flowise-ui@2.0.4
npm warn node_modules/flowise-ui
npm warn ERESOLVE overriding peer dependency
npm warn deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated google-p12-pem@4.0.1: Package is no longer maintained
npm warn deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm warn deprecated are-we-there-yet@2.0.0: This package is no longer supported.
npm warn deprecated gauge@3.0.2: This package is no longer supported.
npm warn deprecated domexception@4.0.0: Use your platform's native DOMException instead
npm warn deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
npm warn deprecated npmlog@5.0.1: This package is no longer supported.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @aws-sdk/protocol-http@3.374.0: This package has moved to @smithy/protocol-http
npm warn deprecated @aws-sdk/signature-v4@3.374.0: This package has moved to @smithy/signature-v4
npm warn deprecated vm2@3.9.19: The library contains critical security issues and should not be used for production! The maintenance of the project has been discontinued. Consider migrating your code to isolated-vm.
npm warn deprecated puppeteer@20.9.0: < 22.8.2 is no longer supported
npm warn deprecated @oclif/screen@3.0.8: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated glob@5.0.15: Glob versions prior to v9 are no longer supported
npm warn deprecated set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated highlight.js@9.15.10: Version no longer supported. Upgrade to @latest

**Expected behavior**
Flowise should install without dependency issues and should not make use of deprecated packages and packages with serious security vulnerabilities

**Screenshots**
See install log above.

**Flow**
N/A - installation issue.

**Setup**

-   Installation: npm i flows
-   Flowise Version 2.0.4 and 2.0.5
-   OS: macOS Sonoma 14.6.1
-   Browser N/A

**Additional context**
node.js version 20.16.0

**Comment by Moeen082** [comment]
Were you able to fix this im having the same problem

**Comment by HenryHengZJ** [comment]
critical vulnerabilities dependencies should be now resolved in v2.1.1 release
