### ISSUE TITLE
[BUG] pgvector / postgres database data not inserting / upsert working but empty data

### ISSUE THREAD

**Issue by Astriel** [FlowiseAI/Flowise#3009]
**Describe the bug**
When I'm making an upsert on an existing database, and some flows that were working with pgvector and Amazon Bedrock, data are not inserted in to the database.

**To Reproduce**

1. Go to 'Upsert'
2. Click on 'Upsert'
3. See the message of data being upserted
4. No data into the database

**Expected behavior**
Normally, when I'm making an upsert, data should be in the database, either in documents by default, or into a new table if specified into the PostGreSQL block.

**Screenshots**
<img width="566" alt="image" src="https://github.com/user-attachments/assets/2e9f767a-b512-4778-9574-f9b340d2d285">
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/3663351f-814a-4042-acb5-c74d0ddb239e">

**Setup**

-   Installation `npx flowise start` on local and docker-compose up -d in production
-   Flowise Version : 2.0.5
-   OS: Windows for testing and Linux for production
-   Browser : Chrome

**Additional context**
Using PostgreSQL 14

**Comment by Astriel** [comment]
I tried to create another database, same problem. I tried with Pinecone, same problem. 
Sounds like upsert is "working" but not creating data on the target vector store. Could be similar to : https://discord.com/channels/1087698854775881778/1105430878101962826/threads/1227230360912269392

**Comment by Astriel** [comment]
Rollbacking on the 1.8.4 made it work, even if I had some trouble with a big CSV file. 
Should check the PGVector part I guess, because insert / upsert not working on 2.0.4.

**Comment by HenryHengZJ** [comment]
It is working from testing:

1.) Empty table
![image](https://github.com/user-attachments/assets/bff680d4-45a7-4b8d-a2e9-68a410a3b6a9)

2.) Upsert:
![image](https://github.com/user-attachments/assets/697a6c66-5263-44b5-b957-6e62d25af070)

3.) Data now available:
![image](https://github.com/user-attachments/assets/d042fe01-d044-43be-9b75-de869e3eb42b)

**Comment by Astriel** [comment]
Problem is solved after migrating to the latest version. If you were using this component since for example the 1.8.3 or the 1.8.4 you have to delete the old component and add it again to your flow or data won't be inserted.
