### ISSUE TITLE
[BUG] Error when starting a chat with OpenAI Assistant

### ISSUE THREAD

**Issue by schieck0** [FlowiseAI/Flowise#3014]
**Describe the bug**
The error occurs when starting a chat with OpenAI Assistant.
ERROR: invalid input syntax for type uuid: "thread_xxxxxxxxxxxxxxxxxxxxx"

**To Reproduce**
Just add the OpenAI Assistant component with a configured assistant and say something in the chat.

**Expected behavior**
No errors :D

**Screenshots**
![image](https://github.com/user-attachments/assets/4536fd5b-9578-4544-8e18-828ab8bc9dcd)

**Setup**

-   Installation docker
-   Flowise Version: 2.0.5
-   OS: Linux (AWS)
-   Browser chrome
-   Database: Postgres

**Comment by schieck0** [comment]
I solved the problem. It was the sessionId field that was as uuid in postgres. Thanks to someone who fixed the type directly in the original migration instead of creating another one.
Changing to varchar in postgres solved the problem.
[commit](https://github.com/FlowiseAI/Flowise/commit/7e840499908399082783a9bf0257b69dafe24bba)
![image](https://github.com/user-attachments/assets/9602dd38-1eac-4bcd-a11d-fa888e684c17)

**Comment by HenryHengZJ** [comment]
feel free to
