### ISSUE TITLE
[BUG] Bug with function calling when Using 'Tool Node' with Ollama 3.1:70b model

### ISSUE THREAD

**Issue by kpado** [FlowiseAI/Flowise#3021]
**Describe the bug**
The 'Tool Node' connected to multiple retrieval tools is expected to call the correct tool based on the input. This works fine with both OpenAI and the llama3-70b-8192 model on Groq. However, when connected to the Ollama 3.1:70b model, it always fails. While the node sometimes routes to the correct tool, it raises an error and fails to continue the flow.

**To Reproduce**

1. Go to a flow using the 'Tool Node' connected to multiple retrieval tools.
2. Set up the flow to use the Ollama 3.1:70b model.
3. Run the flow with various inputs that should trigger different tools.
4. Observe that, while it sometimes routes correctly, the flow fails with an error after attempting to call the tool.

**Expected behavior**
The 'Tool Node' should consistently route to the correct tool and complete the flow without raising an error, similar to its behavior when connected to OpenAI or llama3-70b-8192 on Groq.

**Screenshots**
![error1](https://github.com/user-attachments/assets/4327910c-41bb-4da1-b252-6dd24c52b4b0)
![error2](https://github.com/user-attachments/assets/ee9301c4-a400-48db-9da1-89d314717d4a)

**Setup**

-   Flowise Version [2.0.5]
-   OS: [Linux]
-   Browser: [Chrome]

**Additional context**
This issue only occurs when using the Ollama 3.1:70b model. Other models like OpenAI and llama3-70b-8192 on Groq do not exhibit this behavior, and the flow runs successfully with those models. The attached screenshots and flow should provide more details on the error.

**Comment by Eyalm321** [comment]
Im getting that too sometimes with llama3.1:7b

**Comment by HenryHengZJ** [comment]
If you turn on analytics, does Ollama actually gives any output? If not, then thats the cause - LLM is not giving any response, not from Flowise side
