### ISSUE TITLE
[FEATURE] Add Markdown and Folder with Files loaders to the document store.

### ISSUE THREAD

**Issue by LuisFX** [FlowiseAI/Flowise#3030]
In issue #2652, @HenryHengZJ (correctly) suggested that the new document store is the way to go, and I gotta say, I love it. Yet the document store doesn't have a couple of very convenient loaders:

- Markdown
- Folder with Files

(also, I'm assuming the new document store automatically handles dupes? as in it has a built-in record manager?)

**Comment by HenryHengZJ** [comment]
For markdown, you should be able to use Text Loader for that. Folder with Files is unfortunately not doable, you will have to use specific loader to upload the files

**Comment by HenryHengZJ** [comment]
Closing this for now and moving to Discussion. Feel free to comment if there is anymore questions
