### ISSUE TITLE
[BUG] State Memory Override config not working

### ISSUE THREAD

**Issue by BadrLaajali** [FlowiseAI/Flowise#3032]
**Describe the bug**
When creating a Key in State and attempting to customize it during a Flowise API call, the value is not being sent to the state variable. During debugging, the value remains empty, even when creating a Node condition to verify the value sent via POST.

**To Reproduce**
Create a Key in the Node State in Flowise
Make an API call to Flowise with the following JSON structure:
 ```JSON
  {
       "question": "hello",
       "overrideConfig": {
           "stateMemory": [
               {
                   "Key": "usecase",
                   "Operation": "Replace",
                   "Default Value": "examplevalue"
               }
           ]
       }
   }
``` 
Create a condition to check the value

**Expected behavior**
The value specified in the API call ("examplevalue" in this case) should be correctly sent to the state variable and be accessible within the flow.

**Screenshots**
![CleanShot 2024-08-17 at 16 44 47](https://github.com/user-attachments/assets/46129a6d-ab5f-4d6e-9844-4f1d64451eeb)
[TestCondition Agents.json](https://github.com/user-attachments/files/16646459/TestCondition.Agents.json)

**Setup**

-   Installation : Railway
-   Flowise Version : flowise@2.0.5
-   Browser : Arc and Brave

**Additional context**
I tried to create a simple workflow just to isolate the problem (workflow in attachment)

**Comment by HenryHengZJ** [comment]
works perfectly from testing:

1.) Condition correctly checks that `state.usecase` is not empty, route to dog agent
![image](https://github.com/user-attachments/assets/52e28f82-97cc-4964-88b6-4d2bc125c6b6)

2.) When no state is provided, correctly route to cats agent:
![image](https://github.com/user-attachments/assets/3543bddd-c900-4aba-a0bf-f1fd43ed0734)

**Comment by BadrLaajali** [comment]
Thanks @HenryHengZJ for confirming :)
It was a deployment problem, but I don't know exactly what it was.
I redeployed the image on Railway, and now everything is good.
