### ISSUE TITLE
[BUG] Vectara chat didn't work both using Vectara QA chain and Conversational Retrieval QA Chain

### ISSUE THREAD

**Issue by davide445** [FlowiseAI/Flowise#3036]
**Describe the bug**
Creating in Vectara a Corpora with his access key, I'm able using Vectara UI to chat with it. 
Vectara is useful due integrate a powerful hybrid search feature.
Setting up in Flowise the chat with Vectara node and setting in the Connect credential the correct Corpora ID and key, I'm not able to get any answer both using Vectara own QA chain or a generic Conversational Retrieval chain. 

**To Reproduce**

1. Create a Corpora in Vectara and add data, generate an API key to access it
2. Test using Vectara own UI a chat with the data to check is answering
3. In flowise add the Vectara Vector Store, connect to Vectara QA Chain or create a simple Conv Retrieval QA Chain
4. Try to ask a question
5. See no answer is given

**Expected behavior**
Answer to specific question regarding the data.

**Screenshots**
![image](https://github.com/user-attachments/assets/78403290-c259-4205-b4da-e9cfb1e95a8f)

**Flow**
If applicable, add exported flow in order to help replicating the problem.
[Vectara test Chatflow.json](https://github.com/user-attachments/files/16651492/Vectara.test.Chatflow.json)

**Setup**

-   Installation `npx flowise start`
-   Flowise Version 2.0.5
-   OS: Linux
-   Browser Firefox

**Additional context**
The screenshot is using the Conv Retrieval QA Chain, using Vectara QA node always get this type of answer:
"{ "text": "", "sourceDocuments": [], "question": "I need to know the specs of the SA 37 product", "chatId": "cc3830bc-953d-4ed9-b4de-e0426a18c8c9", "chatMessageId": "d78ad9bd-d1de-4213-a32f-4ea39a22fafc", "sessionId": "cc3830bc-953d-4ed9-b4de-e0426a18c8c9" }"
Trying to setup an empty corpora in Vectara, providing in the credential the right Corpora ID, adding in Vectara Vector Store node a document I didn't find any way to first upsert it into the vectordb

**Comment by HenryHengZJ** [comment]
last I checked it was working perfectly, @ofermend you mind to have a look?

**Comment by ofermend** [comment]
Let me check. @davide445 - can you please add more information?
1. Are you on Vectara free tier or a Scale customer?
2. If you use Vectara's console and run the same query - do you get the response you're expecting?
3. What is the Flow look like (if you can share w/o credentials or take screenshot that would help).

**Comment by davide445** [comment]
@ofermend thanks for your interest 
1. Using Vectara free tier
2. Yes as written using the Vectara own console I got an answer
3. the flow is attached in my first post

**Comment by adeelehsan** [comment]
@davide445 I just followed this tutorial https://www.youtube.com/watch?v=rBqpvFcD5XY and its seems to be working. Can you please try that ? Meanwhile I can try your  exported flow.

**Comment by davidezari** [comment]
@adeelehsan 
I have tested now with the very same flow attached and all works in both ways (both using Vectara QA chain and Conversational Retrieval QA Chain). 
I have had a temporary upgrade of the Vectara license to the Growth plan (from the Free) so I can maybe check again when I come back to the Free to understand if there was the issue.

**Comment by davide445** [comment]
@adeelehsan 
I have tested now with the very same flow attached and all works in both ways (both using Vectara QA chain and Conversational Retrieval QA Chain).
I have had a temporary upgrade of the Vectara license to the Growth plan (from the Free) so I can maybe check again when I come back to the Free next week to understand if there was the issue.

**Comment by HenryHengZJ** [comment]
Closing for now, thanks guys!
