### ISSUE TITLE
[BUG] Receiving: Error buildAgentGraph - TypeError: Cannot read properties of undefined (reading 'includes') after including Conditional Agent.

### ISSUE THREAD

**Issue by jannech** [FlowiseAI/Flowise#3045]
**Describe the bug**
The flow stopped working after including the Conditional Agent.

**To Reproduce**
1. Load the provided JSON Agent file.
2. Observe that the flow stops working.

Agent JSON File
You can download the JSON file here: https://github.com/user-attachments/files/16683760/Sequential.Agents.v2.Agents.json

Expected behavior
The flow should continue working as expected after including the Conditional Agent.

**Screenshots**
<img width="1563" alt="Screen Shot 2024-08-20 at 21 20 30" src="https://github.com/user-attachments/assets/1fdae320-0a2b-4c71-b488-002eb123aed3">

**Flow**
I was following Leon's tutorial from this YouTube video:: https://www.youtube.com/watch?v=6LbvgTbS0BE&t=1573s.

**Setup**
- Flowise Version 2.0.3 (also occurs on version 2.0.5)
- Running Docker locally. The problem also occurs in an online version.

**Error Trace**
2024-08-20 21:20:16 Error: Error buildAgentGraph - TypeError: Cannot read properties of undefined (reading 'includes')
2024-08-20 21:20:16     at buildAgentGraph (/usr/src/packages/server/dist/utils/buildAgentGraph.js:345:15)
2024-08-20 21:20:16     at async utilBuildAgentResponse (/usr/src/packages/server/dist/utils/buildChatflow.js:363:31)
2024-08-20 21:20:16     at async utilBuildChatflow (/usr/src/packages/server/dist/utils/buildChatflow.js:159:20)
2024-08-20 21:20:16     at async createInternalPrediction (/usr/src/packages/server/dist/controllers/internal-predictions/index.js:7:29)

**Comment by HenryHengZJ** [comment]
In your Condition node, change it to `$flow.output.route`:
![image](https://github.com/user-attachments/assets/5c7dfa96-48b9-4616-977f-0943c7a15bf1)

![image](https://github.com/user-attachments/assets/f37aab55-a809-44b2-b91b-bdb978003b2d)

It should works fine now.

**Comment by jamieduk** [comment]
```
{
  "nodes": [
    {
      "id": "1",
      "type": "ollama",
      "position": {
        "x": 100,
        "y": 200
      },
      "data": {
        "api_endpoint": "http://localhost:11434",
        "api_key": "NA",
        "model": "crewai-llama3.2-vision:latest",
        "parameters": {
          "temperature": 0.7,
          "max_tokens": 2048,
          "top_p": 1.0,
          "frequency_penalty": 0.0,
          "presence_penalty": 0.0
        },
        "prompt_template": {
          "input": "User: {{input}}\nAssistant:",
          "output": "{{output}}"
        },
        "logging": {
          "enabled": true,
          "level": "info",
          "path": "/root/.flowise/logs"
        },
        "cors": {
          "origins": "*"
        },
        "metrics": {
          "enabled": false,
          "provider": "prometheus",
          "include_node_metrics": true,
          "service_name": "FlowiseAI"
        }
      }
    },
    {
      "id": "2",
      "type": "end",
      "position": {
        "x": 300,
        "y": 400
      }
    }
  ],
  "edges": [
    {
      "id": "e1-2",
      "source": "1",
      "target": "2",
      "type": "default"
    }
  ]
}

```

i also get error:

Failed to import: Error: exportImportService.importAll - Cannot read properties of undefined (reading 'length')
