### ISSUE TITLE
[FEATURE] Add "base path" to Azure OpenAI embeddings node

### ISSUE THREAD

**Issue by bodzebod** [FlowiseAI/Flowise#3048]
**Describe the feature you'd like**
Similar to "base path" added to AzureAI chat model in flowiseAI 2.0.5, I request to add the same feature to the Azure OpenAI embeddings node.

**Additional context**
Previously,  I had to set the following environment variables in docker-compose file to make a chat work on Flowise 2.0.2:
AZURE_OPENAI_BASE_PATH
AZURE_OPENAI_API_DEPLOYMENT_NAME
OPENAI_API_KEY
AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME
AZURE_OPENAI_API_INSTANCE_NAME
AZURE_OPENAI_API_VERSION

I saw that release 2.0.5 added the possibility to set the AzureAI API base path in the AzureAI chat model node. However, this doesn't exist for AzureAI embeddings node.
I happen to have to use a chat model and an embedding model that are not deployed in the same subnet, and I need to define a different base path for both.

At the moment, I have set the base path for the chat model in "base path" in flowise 2.0.5. I tried to set the one for the embedding model via the environment variable, but it doesn't work.
Please could you add also this "base path" feature to the AzureAI embedding node? Thank you!

**Comment by motojinc25** [comment]
I fixed the issue with different endpoints in Azure OpenAI Embeddings. 
I'll create a pull request.

**Comment by motojinc25** [comment]
![image](https://github.com/user-attachments/assets/cb422eb5-a1fa-479d-b395-94c65203cfb2)
![image](https://github.com/user-attachments/assets/9a605088-2db3-4c04-b93b-b02cc3da1d0f)

**Comment by bodzebod** [comment]
That's great, thank you! I'm waiting for the next release so 👍

**Comment by Code-is-hope** [comment]
Would it be possible to have this also for the OpenAi Embedding component?

**Comment by motojinc25** [comment]
@Code-is-hope 
There are separate OpenAI Embedding and Azure OpenAI Embedding nodes, so please use the OpenAI Embedding Node.

**Comment by Code-is-hope** [comment]
Yes ofcourse, however the openai embedding comp is missing the base options option.
I was hoping that this can be added.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
