### ISSUE TITLE
[BUG] Error occurs in all chatflows and agentflows: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by tehmann83** [FlowiseAI/Flowise#3051]
**Describe the bug**
Starter plan on render, (but also locally, I receive the same output) all setup like in the docs/video.
From Marketplace -> Prompt Engineering Team -> Use Template
In Agentflows: added ChatOpenAI Connect Credential, saved, and started the chat (copy/paste the example)
Error: Cannot read properties of undefined (reading 'length')

PLUS: It seems this is happening on all my created agentflows, as well as all templates I have tried. This makes me think of that there might be something on render?

**To Reproduce**

1. Go to 'Marketplace -> Prompt Engineering Team -> Use Template'
2. In Agentflows: add ChatOpenAI Connect Credential, save
3. start the chat (just copy/paste the example)
4. See error in the first (and thus also last) message

**Expected behavior**
Of course the expected behavior would be, to see the agentflow start working. 

**Screenshots**
![image](https://github.com/user-attachments/assets/7405b366-0800-46f8-8751-507116e1d9d1)
![image](https://github.com/user-attachments/assets/0a082bad-19b6-421c-8a8e-4199ffb84a8e)
![image](https://github.com/user-attachments/assets/e452244c-e8cb-4e69-8b1a-e35135052a6a)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation: Docker on render
-   Flowise Version 2.0.5
-   OS: Windows
-   Browser: Chrome/Chromium

**Additional context**

**Comment by HenryHengZJ** [comment]
was openai down? I was able to use the template without any problem:
![image](https://github.com/user-attachments/assets/3fa99154-b77b-4f37-805d-f0e2636466ea)

Deployed on Render as well

**Comment by toi500** [comment]
@HenryHengZJ in relation to this, it is working for me too but my logs shows the same error https://github.com/FlowiseAI/Flowise/issues/2899#issuecomment-2302474183

**Comment by tehmann83** [comment]
Redeployed today, and all problems seem gone:

![image](https://github.com/user-attachments/assets/aca265d6-d530-4cf1-a283-f41679600140)

**Comment by toi500** [comment]
@tehmann83 any error in the logs?

**Comment by tehmann83** [comment]
@toi500 no, not a single one

**Comment by RoniKush** [comment]
@tehmann83 I am having this problem also - Render deployment. What was your process to fixing it? Do you deploy a fresh copy to render while removing the errored one? Or did you update?

**Comment by tehmann83** [comment]
@RoniKush 
I deleted the webservice and setup a completely new one, from zero. 
Thanks to render this is a straightforward process with not too many clicks, also all environment variables were detected automatically. So, basically just this: [flowise on render](https://docs.flowiseai.com/configuration/deployment/render)

**Comment by tonygil** [comment]
My problem is i have exported a workflow from a localhost flowise 2.0.7 and attempted to import workflow in render flowise 2.0.7 . got this error Failed to import chatflows: Error: chatflowsService.saveChatflows - Cannot read properties of undefined (reading 'length')

**Comment by tonygil** [comment]
It seems the issue is related to the "import chatflows" option. However, if I export a chatflow, create a new blank chatflow, and then use the "load chatflow" option, it works correctly.
