### ISSUE TITLE
[BUG] Error: Returned message history must be an array

### ISSUE THREAD

**Issue by meksico** [FlowiseAI/Flowise#3054]
**Describe the bug**
Error: predictionsServices.buildChatflow - Error: Error: Returned message history must be an array

**To Reproduce**
Precondition:
Deployed on Render
Workflow is next:
- Conversation chain:
- ChatOpenAI model
- Chat Prompt Template (system message is filled)
- Buffer Memory

**Expected behavior**
Expectine the answer, and history chain

**Screenshots**
<img width="1121" alt="Screenshot 2024-08-21 at 19 36 47" src="https://github.com/user-attachments/assets/07e424f7-4ed1-494f-94bd-95dce0510f66">

**Flow**
[TEMP Chatflow.json](https://github.com/user-attachments/files/16695336/TEMP.Chatflow.json)

**Setup**

-   Render from official for
-   Flowise Version 2.0.5
-   OS: macOS
-   Browser: Chrome

**Comment by panalexeu** [comment]
the same issue with llm chain too

**Comment by tomgersic-altimetrik** [comment]
I have this same problem when running Flowise in Render, but it works fine on localhost. Same version 2.0.5

**Comment by toi500** [comment]
Same issue.
