### ISSUE TITLE
[FEATURE] Support gpt-4o-mini model for Azure Open AI

### ISSUE THREAD

**Issue by x-du** [FlowiseAI/Flowise#3055]
**Support gpt-4o-mini model for Azure Open AI**
gpt-4o-mini is available on Azure OpenAI. But Flowise doesn't show it in the list of models.  Need to support it. 

![image](https://github.com/user-attachments/assets/a543a557-55c9-4389-bc54-8d46190182bf)

**Comment by Gpwner** [comment]
@x-du您好，请问你能成功用上Azure OpenAI API吗？我这边按照这个指导 https://docs.flowiseai.com/integrations/langchain/chat-models/azure-chatopenai-1 来操作也没有调成功，一直提示“Connection error”

**Comment by x-du** [comment]
> @x-du您好，请问你能成功用上Azure OpenAI API吗？我这边按照这个指导 https://docs.flowiseai.com/integrations/langchain/chat-models/azure-chatopenai-1 来操作也没有调成功，一直提示“Connection error”

Yes. We can use Azure OpenAI without a problem.

**Comment by Gpwner** [comment]
@x-du Have you ever encountered a situation where the bot's response speed is initially slow, but then becomes very slow when you ask a certain question? Thank you.

**Comment by x-du** [comment]
> @x-du Have you ever encountered a situation where the bot's response speed is initially slow, but then becomes very slow when you ask a certain question? Thank you.

Suggest you enable langsmith to see the langchain log. Very likely it is because you didn't use memory node. By default all the chat history will be added in the context.

**Comment by Gpwner** [comment]
I do know why I always got this error after I enable langsmith .
![image](https://github.com/user-attachments/assets/70c65a67-bef0-4da6-95ef-446125c8fafd)
Here is my flow,
![image](https://github.com/user-attachments/assets/2de52e28-5ef8-438d-9feb-61c2e4f68ffd)
