### ISSUE TITLE
stream.getReader is not a function

### ISSUE THREAD

**Issue by waelmansourx** [FlowiseAI/Flowise#306]
**Describe the bug**
This error happens everytime I send a message and in any template

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup**

-   OS: Windows
-   Browser Firefox

**Comment by HenryHengZJ** [comment]
are you on node >=18.15.0?

**Comment by govind-kumarr** [comment]
@waelmansourx  can you show the screenshot, So that we can resolve it?

**Comment by 1337-ishaan** [comment]
facing the same error, any fix available?

**Comment by Kohze** [comment]
node >=18.15.0 fixes the error - those facing are on earlier node versions.

**Comment by suraj-potnuru** [comment]
> node >=18.15.0 fixes the error - those facing are on earlier node versions.

This works. Thanks !
