### ISSUE TITLE
[BUG]Buffer Memory not available?

### ISSUE THREAD

**Issue by ajerni** [FlowiseAI/Flowise#3064]
Under Memory only "Agent Memory" is available and this is not connectable to the memory input of the Conversation Chain.

Buffer Memory not available in version 2.0.5

**Comment by toi500** [comment]
This is not a bug. When you use Agentflows, that is the only memory u need.

![image](https://github.com/user-attachments/assets/88edb474-5895-4378-a63b-12ed5f2f7e95)

**Comment by ajerni** [comment]
thanks - it is still available in the chat flows
