### ISSUE TITLE
[FEATURE] Add support for Gemini API

### ISSUE THREAD

**Issue by rakyll** [FlowiseAI/Flowise#3071]
Google DeepMind owned models sometimes make a first debut on the [Gemini API](https://ai.google.dev/), e.g. `gemini-1.5-pro-exp-0801`. Please add support for Gemini API endpoints to make it possible to prototype with the latest model revisions.

There is an official [Node/Typescript](https://github.com/google-gemini/generative-ai-js) client library which could be useful, otherwise please take a look at the API reference at  https://ai.google.dev/api. Gemini API works with an API key that could be obtained at https://aistudio.google.com/.

**Comment by toi500** [comment]
@rakyll Flowise has supported the Gemini API for a while now. 

Check it out:

![image](https://github.com/user-attachments/assets/c1506621-7b7b-4648-aff4-463e4b67dac2)

**Comment by HenryHengZJ** [comment]
To add new model, we can simply add a new key value pair in [models.json](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/models.json#L357)

**Comment by HenryHengZJ** [comment]
Added a PR that allow users to specify a custom model name - https://github.com/FlowiseAI/Flowise/pull/3088
