### ISSUE TITLE
[BUG] AWS Deployment error with Docker compose

### ISSUE THREAD

**Issue by RoniKush** [FlowiseAI/Flowise#3073]
**Describe the bug**
After installing several flowise instances to AWS the commands in the documentation no longer works. 

docker compose up -d

Produces this error:

[ec2-user@ip-172-00-33-2 docker]$ docker compose up -d
unknown shorthand flag: 'd' in -d
See 'docker --help'.

**To Reproduce**

1. Clone the repo
2. Cd into docker folder
3. Create a .env file
4. Run docker compose

**Expected behavior**
Docker compose runs and Flowise instance can be seen at http://ec2-123-456-789.compute-1.amazonaws.com:3000

**Comment by patrickreinan** [comment]
Hi @RoniKush, 

This is not a Flowise error. This problem is in your deployment environment.
