### ISSUE TITLE
[BUG] Azure OpenAI Embeddings Api Version has error

### ISSUE THREAD

**Issue by XuDL** [FlowiseAI/Flowise#310]
I used the Embeddings API of Azure OpenAI, but I noticed that flowise can only choose two API versions, 2023-03-15-preview and 2022-12-01, can it be modified to a custom version of the custom input box?

Here is Azure's documentation for reference:
https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/embeddings?tabs=console

**Comment by HenryHengZJ** [comment]
@chungyau97

**Comment by chungyau97** [comment]
Hi @XuDL,

Currently Azure only support [3 version](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#embeddings)

I could add `2023-05-15` this into the option list.
or
You still prefer an input text field to fill in yourself?

**Comment by XuDL** [comment]
I suggest that I can modify it to fill in by myself. I have to say that the AI ​​update is too fast now 
ヾ (o ° ω ° O ) ノ゙

**Comment by chungyau97** [comment]
#344 done.
Please help test it out.

**Comment by XuDL** [comment]
It's work! thx
