### ISSUE TITLE
[BUG] Version 2.0.6 broke API chatmessage

### ISSUE THREAD

**Issue by xolabsro** [FlowiseAI/Flowise#3104]
**Describe the bug**
Previously (2.0.5 and lower versions) I was able to retrieve the entire chat history, with api key authorization enabled, for previously chat ids. Basically, it worked just fine. Now, using 2.0.6, the api fails to provide the conversations history.

**Additional context**
I had to revert back to version 2.0.5 and without any changes made to my workflow, it magically started working again.
I am talking about this api endpoint: https://docs.flowiseai.com/api-reference#/chatmessage-id

**Comment by HenryHengZJ** [comment]
works fine for me:
![image](https://github.com/user-attachments/assets/72dea5e4-baa3-487e-a85a-8ed0b3475767)

**Comment by HenryHengZJ** [comment]
> Hmm... then it might be because I am running it on docker with apache as a reverse proxy?

im not sure, you can also use our docs page to test it: https://docs.flowiseai.com/api-reference/chat-message#/chatmessage-id
![image](https://github.com/user-attachments/assets/aa354ec1-c6b3-44f9-9581-a53f0640c33f)

Closing for now. Feel free to re-open if issue persists
