### ISSUE TITLE
⚒️[FEATURE] Puppeteer Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#311]
## Describe the feature you'd like
Puppeteer Integration
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/web_puppeteer

## ✅Tasks
- [ ] Add Puppeteer Loader node

## 🎯Acceptance Criteria
- [ ] Puppeteer Loader node should be able to scrape data from webpages

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Cheerio Loader](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Cheerio/Cheerio.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by AidanTilgner** [comment]
Hey, I'm new here but I'd be interested in taking this on. I've worked with puppeteer recently so it's fresh.
