### ISSUE TITLE
[BUG] MongoDB Atlas Chat Memory client closes and breaks flow

### ISSUE THREAD

**Issue by jtguzman** [FlowiseAI/Flowise#3115]
**Describe the bug**
When using the MongoDB Atlas Chat Memory, after some uses the client closes and it does not reconnect. This makes the flow to break with the message "Client must be connected before running operations"
The client reconects if the server is restarted, but after a random time it will close.

**To Reproduce**

1. Create a flow
2. Configure a new MongoDB Atlas Chat Memory node
3. Try the node successfully
4. Wait some time
5. Try again until it closes.

**Expected behavior**
The client should reconnect and the flow should continue without breaking.

**Screenshots**
![image](https://github.com/user-attachments/assets/80ade62d-c1a0-42a1-b779-793f4f2182ac)

**Flow**
Any flow with the node

**Setup**

-   Installation docker-compose up -d
-   Flowise Version 2.0.5
-   OS: AWS Linux
-   Browser: Edge

**Additional context**
A lot of problems with MongoDB and the 2.x.x update...

**Comment by HenryHengZJ** [comment]
Closing as https://github.com/FlowiseAI/Flowise/pull/3469 merged
