### ISSUE TITLE
[BUG] Passing state to tool through toolNode

### ISSUE THREAD

**Issue by Jrakru** [FlowiseAI/Flowise#3117]
**Describe the bug**
This is a follow up on [issue](https://github.com/FlowiseAI/Flowise/pull/3103)

I can replicate the results that you have if I use an agentNode as follows:

![image](https://github.com/user-attachments/assets/750e5cb2-bbb4-418f-9bb8-c076511200de)

I am still having the same issue when I am using a toolNode like the following:
![image](https://github.com/user-attachments/assets/c3ae358d-c777-44e5-872e-4a3b1bc13bf8)

Am I not understanding how tooNode is supposed to be used?

**To Reproduce**
Use a toolNode to connect to the tool

**Expected behavior**
To be able to access the variable inside the tool

**Comment by HenryHengZJ** [comment]
merged 🎊  https://github.com/FlowiseAI/Flowise/pull/3103
