### ISSUE TITLE
⚒️[FEATURE] Playwright Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#312]
## Describe the feature you'd like
Playwright Integration
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/web_playwright

## ✅Tasks
- [ ] Add Playwright Loader node

## 🎯Acceptance Criteria
- [ ] Playwright Loader node should be able to scrape data from webpages

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Cheerio Loader](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Cheerio/Cheerio.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by Bingolast** [comment]
I am interested! Please assign this issue to me

**Comment by tiwariParth** [comment]
> I am interested! Please assign this issue to me

heyyy maintainers Im sorry to say this but due heavy rain fall last night at my place. My internet will be down for 3-4 days . When its fix and this if this issue will remain open I will work on it! Thanks and sorry for inconvenience.

**Comment by disflyer** [comment]
#327
Please check this PR. Hope can help.

**Comment by HenryHengZJ** [comment]
closing as #327 merged

**Comment by burak626** [comment]
Is it possible to use flowise with playwright? Can we do function calling?
