### ISSUE TITLE
[BUG] SearxNG tool call fails with TypeError

### ISSUE THREAD

**Issue by Banbury** [FlowiseAI/Flowise#3120]
Using the SearXNG tool with a Conversational agent fails with a TypeError in langchain. I think the output of the tool cannot be parsed. The reason might be, that the tool has been changed in langchain only recently.
I have attached the log and the chat flow.

* [log.txt](https://github.com/user-attachments/files/16823994/log.txt)
* [chatflow.json](https://github.com/user-attachments/files/16823996/Search.Movie.by.ISBN.Chatflow.json)

**Comment by HenryHengZJ** [comment]
might be related: https://github.com/FlowiseAI/Flowise/issues/2815

**Comment by HenryHengZJ** [comment]
fixed in this PR: https://github.com/FlowiseAI/Flowise/pull/3263
