### ISSUE TITLE
[FEATURE] Add PyMuPDF4llm loader

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#3123]
**Describe the feature you'd like**
Using PDFs for RAG is a classic use case. 

PyMuPDF is an amazing lib to turn PDFs into markdown which is easy to understand for LLMs, and easy to split for RAG: https://github.com/pymupdf/RAG

Would be great if we could leverage this library directly in Flowise, not sure if their AGPL-3.0 license allows this though.

**Comment by HenryHengZJ** [comment]
Its in python, so you have to do it outside of Flowise Then use the markdown inside Flowise after the conversion. Currently its not possible to have direct integration
