### ISSUE TITLE
[BUG] Sharing Chatbot should have a toggle to show and hide Agent Messages

### ISSUE THREAD

**Issue by tobeasim** [FlowiseAI/Flowise#3126]
**Describe the bug**

**To Reproduce**

1. Open Agent Flow
2. Click on "API Endpoint" or the <> button on the top
3. Select Share Chatbot
4. Copy the Sharing URL 
5. Open in another browser tab or window
6. Chat with the bot
7. See "Agent Messages"

**Expected behavior**
Agent Messages display should be toggle-able but the required config is missing from the options.  In the "embed" option, the toggle is defined as "showAgentMessages", and when that is set to false, the embedded page does not show Agent Messages. However, in the Sharing chatbot option, there is now way to do so.

**Screenshots**
![2FE80785-EDD6-4706-BD27-A6F50E840DC4_1_105_c](https://github.com/user-attachments/assets/3715b374-1ed2-46b8-ba1e-85ca2c24129a)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
You can toggle it:

- Collapsed:
![image](https://github.com/user-attachments/assets/3af160f2-2d4e-49d3-bb3f-c4ee3d014cb5)

- Expanded:
![image](https://github.com/user-attachments/assets/a336a1d3-7df4-4e8f-a23b-1e3e3c8696a4)

**Comment by tobeasim** [comment]
Thanks, but that's not what I mean. I mean that we should allow showAgentMessages to be set up to False so that the Agent Messages are not shown at all.

The issue is that previously, it was easy to create a chatbot prototype and then share the share the full URL of the bot to others for a quick review, but now with the Agent Messages showing, it can confuse others, such as business users.

Using the "Embed" option, we can turn the messages off but setting showAgentMessages=False. But there is no such option  for Share Chatbot.

**Comment by tobeasim** [comment]
so by toggle, I mean't to be able to hide Agent Messages when doing a Share Chatbot in full using the URL
