### ISSUE TITLE
Welcome to Flowise Discussions!

### ISSUE THREAD

**Issue by Howie0928** [FlowiseAI/Flowise#3133]
Originally posted by Howie Yu

👋 Welcome!
Hello everyone,

I'm Howie Yu, and I'm currently working on AI music applications. I've organized several seminars in this field and am now interested in exploring the use of AI agents. I have a question that I'm hoping someone could help me with:

My Question:
Even though my OpenAI API account is in a paid status with $10 credit remaining, my Flowise is still showing the message "You exceeded your current quota." Could anyone please help me understand why this might be happening?

Thank you, and I appreciate any advice or assistance you can provide![
![457093562_1809590292903066_6106753593586796416_n](https://github.com/user-attachments/assets/4aa30390-be93-4c04-974c-6e5286ead4ad)
![457585174_1868431420334024_1309286908115794461_n](https://github.com/user-attachments/assets/ffeac42e-16d8-4dee-a3a1-386a7b65d552)
](url)

**Comment by HenryHengZJ** [comment]
Its a limit from OpenAI, I suggest try asking on OpenAI forum and see. Closing this as its not from Flowise. Feel free to create a dicussion - https://github.com/FlowiseAI/Flowise/discussions
