### ISSUE TITLE
[BUG]404 The model gpt-4-vision-preview has been deprecated - Vision API

### ISSUE THREAD

**Issue by ayanna-africa** [FlowiseAI/Flowise#3145]
When I tried to upload an image on the chat to extract some infos, I got a 404 error "The model gpt-4-vision-preview has been deprecated"

**To Reproduce**

1. Add a Conversation Chain
2. Connect a ChatOpenAI on the Chat Model and choose the model "gpt-4o (latest)"
[Premier Image Chatflow.json](https://github.com/user-attachments/files/16871568/Premier.Image.Chatflow.json)
3. Allow Image Upload on the previous module
4. Connect a buffer memory to "Memory" on the Conversation Chain
5. Launch the chat, upload an image, and ask him to describe it

**Expected behavior**
I would expect the extracted information once I uploaded my image.

**Screenshots**
![CaptureBug](https://github.com/user-attachments/assets/c543260c-2554-4263-a9aa-e89220319612)

**Flow**
[Premier Image Chatflow.json](https://github.com/user-attachments/files/16871591/Premier.Image.Chatflow.json)

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version 1.6.5
-   OS: Linux
-   Browser: chrome

**Additional context**
N/A

**Comment by ryanhalliday** [comment]
Try updating Flowise, 1.6.5 is quite out of date.

**Comment by ayanna-africa** [comment]
> Try updating Flowise, 1.6.5 is quite out of date.

Ok will do thanks

**Comment by ayanna-africa** [comment]
It fixed, thanks @ryanhalliday
