### ISSUE TITLE
[openai]add a config of openai domain

### ISSUE THREAD

**Issue by wangsp188** [FlowiseAI/Flowise#3146]
**Describe the feature you'd like**
when add openai api please provide a config of api domain ,default is "https://api.openai.com".

**Comment by amansoni7477030** [comment]
Hii @wangsp188 this feature is already their, in advance parameter type the domain in base path.

**Comment by HenryHengZJ** [comment]
you can specify the base path: 
![image](https://github.com/user-attachments/assets/bb1f7fd2-e69e-41d4-87d1-4fe9250c8613)
