### ISSUE TITLE
[BUG] Message export fails when using tools

### ISSUE THREAD

**Issue by zeitderforschung** [FlowiseAI/Flowise#3150]
**Describe the bug**

Cannot export chat messages. Tested with version 2.0.7.

**To Reproduce**

Chatflow with Tool Calling > View Messages > Export

**Solution**

Fix typo in the code, `Jchatmsg` should be `chatmsg`.

https://github.com/FlowiseAI/Flowise/blob/f4647044bdfe2b7c64a5107a1b86cbf774922c90/packages/ui/src/ui-component/dialog/ViewMessagesDialog.jsx#L206

**Comment by HenryHengZJ** [comment]
thanks! fix in this PR https://github.com/FlowiseAI/Flowise/pull/3173

**Comment by ArkMaster123** [comment]
yesss Henry!!!
