### ISSUE TITLE
[FEATURE] Connection to Dify

### ISSUE THREAD

**Issue by taowang1993** [FlowiseAI/Flowise#3158]
I have a chatbot on Dify. And I love Flowise as well.

Is it possible to build an agent on Flowise that connects to Dify via API?

If possible, then I can make Dify agent and Flowise agent collaborate.

**Comment by amansoni7477030** [comment]
@taowang1993 I think this feature is already in flowise you can use Custom tool to achieve this.

**Comment by HenryHengZJ** [comment]
yes! there is no direct integration but definitely can be achieved by creating a custom tool and a HTTP call to Dify API. Moving to discussion

**Comment by taowang1993** [comment]
I tried using custom tool and tool agent, but this approach requires attaching a chatmodel on flowise in order to make calls.

I am afraid this approach will increase latency. 

Is there going to be a native support for dify agent in the near future. In this way, users can utilize the power of both platforms. 

Furthermore, Dify only supports iframe embed, which will expose the url to bad actors. 

I prefer Flowise's <flowise-fullchatbot> approach, because it is more secure.

Besides Dify, if Flowise will support RAGflow agent, that will be a huge plus, since RAGflow is more specialized in RAG than langchain and llamaindex. 

Thank you
