### ISSUE TITLE
Error in Upsert Config

### ISSUE THREAD

**Issue by mdlmarkham** [FlowiseAI/Flowise#3160]
**Describe the bug**
I have configured a Document Store with a couple of sample PDF files. I have set up a Postgres database in my local lab environment, and I would like to use it for both the vector store and the record manager:

![image](https://github.com/user-attachments/assets/5440e52c-ae0a-44dc-aee3-653ebbe5e184)

When I press "Upsert" I get this error:

`_Status: 500
Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - Error: Not implemented.`

Am I doing something wrong... or have I found the Daily Double? - Thanks.

**Comment by phamquyhai** [comment]
@mdlmarkham i take same a bug
To fix: don't using _, - (special characters) for db, table name.

**Comment by HenryHengZJ** [comment]
i think its the same problem as this: https://github.com/FlowiseAI/Flowise/issues/3004
