### ISSUE TITLE
[BUG]-Error buildAgentGraph - Error: Worker name is required

### ISSUE THREAD

**Issue by stzogas** [FlowiseAI/Flowise#3164]
![image](https://github.com/user-attachments/assets/3b25152f-4670-49c7-b8cc-d3eea4b76885)
I get the error Error buildAgentGraph - Error: Worker name is required!

**Comment by HenryHengZJ** [comment]
you have duplicated nodes: 
![image](https://github.com/user-attachments/assets/0a477f13-cb4b-487c-9763-9f61b46a1457)

**Comment by amritpaul010** [comment]
<img width="1452" alt="Image" src="https://github.com/user-attachments/assets/e41be7cb-5bee-49c8-83bf-c2639fe640db" />

I see the same issue. Dont have multi node issue. can someone help please
