### ISSUE TITLE
Updating Flowise Hosted on Railway

### ISSUE THREAD

**Issue by scooter7** [FlowiseAI/Flowise#3166]
Hi,

If I click "Update available" on my Flowise instance hosted on Railway and elect to update my Flowise instance, will my current flows and associated data be deleted?

Thanks!

**Comment by taowang1993** [comment]
If you created volumes when you installed flowise, you will be fine.

**Comment by HenryHengZJ** [comment]
https://docs.flowiseai.com/configuration/deployment/railway#persistent-volume
