### ISSUE TITLE
How to hide the node modules while keeping the chat

### ISSUE THREAD

**Issue by dnagpal1** [FlowiseAI/Flowise#317]
### Discussed in https://github.com/FlowiseAI/Flowise/discussions/164

<div type='discussions-op-text'>

<sup>Originally posted by **Wany917** May 24, 2023</sup>
Hi ! I created a chatbot and would like to have only the chatbot displayed, not the nodes that compose it, so that people can't modify it. Also, I don't know how to code</div>

**Comment by HenryHengZJ** [comment]
As mentioned from the PR, we will implement a standalone chat application that connect to your flow at a later stage

**Comment by HenryHengZJ** [comment]
closing as https://github.com/FlowiseAI/Flowise/pull/416 merged
