### ISSUE TITLE
[BUG] My flow work with Gpt-4o but not with claude-3.5-sonnet

### ISSUE THREAD

**Issue by abernardini-inc** [FlowiseAI/Flowise#3181]
Hello everyone!

I have developed an AgentFlow capable of collecting and returning the information contained in the image of an ID card or a passport. If the uploaded image does not contain one of these documents, it will return an empty JSON.

The flow works using Gpt-4o as the ChatModel, but when I try to change it to Claude-3.5-sonnet, I get the following error:

Error buildAgentGraph - Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"Your API request included an assistant message in the final position, which would pre-fill the assistant response. When using tools, pre-filling the assistant response is not supported."}}

It manages to identify through the first LLM Node whether it is an ID card or a passport, but once it reaches the point of evaluating the condition, it stops and returns the error.

Here is the flow:

[CM OCR 5.0 Agents.json](https://github.com/user-attachments/files/16977739/CM.OCR.5.0.Agents.json)

I hope someone can help me. Thank you!

<img width="814" alt="Screenshot 2024-09-12 123919" src="https://github.com/user-attachments/assets/a20b1783-98ec-45d2-afc9-5d62d401b169">

**Comment by HenryHengZJ** [comment]
This is related to the strict requirement of Claude models that require alternate roles between each messages. Currently, every messages between the LLM nodes above is "assistant" role, and Claude doesnt allow that

**Comment by HenryHengZJ** [comment]
Should now be possible as Claude removed the restriction

**Comment by sagestudiosai** [comment]
Are there any necessary changes on our end for this to work? We still receive this error when using Claude models.
