### ISSUE TITLE
[FEATURE] allow me to display markdown content and render image links 

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#3185]
**Describe the feature you'd like**
Right now it's not possible to display any images using the Flowise Public Chatbot or Embedded Chatbot for Websites.

I imagine it should be rather easy to allow text to be displayed as markdown, with this it's normally possible to just display an image markdown style (an image of a dog)[urlofmyimage.com] and it's rendered automatically.

Right now I have a use case for a RAG Bot of manuals, where the images display important info that can't be communicated with text alone.

**Additional context**
Keep going, you rock!

**Comment by HenryHengZJ** [comment]
The only way for now is to ask the LLM to return the image in markdown format. Flowise can then display images in markdown format. Take a look at Image Generation template: 
![image](https://github.com/user-attachments/assets/e516767b-845e-47c3-920b-9c585c40f768)

**Comment by dentro-innovation** [comment]
Oh that's exactly what I wanted, I thought it doesn't work!

Thank you for the clarification, just tried it out myself and can confirm that it works!
