### ISSUE TITLE
[BUG] Placeholders appear in main UI but not in Public URL mode

### ISSUE THREAD

**Issue by scooter7** [FlowiseAI/Flowise#3188]
I have an agentflow that shows placeholders in the main UI where the flow is created.

![image](https://github.com/user-attachments/assets/06871b84-9bbc-4bad-b097-e77f86aeee70)

However, when I make the chatbot public, the placeholders do not show up.

![image](https://github.com/user-attachments/assets/e011d74d-fe4b-405b-bc8c-a96920a9a978)

This just started happening with today's update.

Interestingly, I had a prior version of Flowise that displayed the placeholders in both the UI chat as well as the shared, public URL version.

The URL that should have placeholders but doesn't is https://flowiseai-railway-production-ab01.up.railway.app/chatbot/6e5581e2-b5b7-43f2-8280-0406efc1f645

Thanks!

**Comment by subhamengine** [comment]
Hey, I would like to work on it.

**Comment by scooter7** [comment]
Hi @subhamengine , Just curious if you have made any progress on fixing the placeholders issue.

Thanks!
