### ISSUE TITLE
[BUG] QA Conversational retrieval chain does not work with OpenAI chat block and OpenAI embedding block anymore. 

### ISSUE THREAD

**Issue by SirL0gic** [FlowiseAI/Flowise#3193]
**Describe the bug**

QA Conversational retrieval chain does not work with OpenAI chat block and OpenAI embedding block anymore. 

**To Reproduce**

Check the screenshot and the flow. 

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/f7a88b39-8c52-4e4f-910a-953b9e46c821)

**Flow**
[Ordo Chatflow.json](https://github.com/user-attachments/files/17006218/Ordo.Chatflow.json)

**Setup**

Docker Image

**Additional context**

OpenAI or Langchain have updated their libraries and APIs.

**Comment by xhorizont** [comment]
Same here

**Comment by AmaanUsmani** [comment]
Facing the same issue.

**Comment by HenryHengZJ** [comment]
works for me on Docker though: 
![image](https://github.com/user-attachments/assets/724d2b59-fb23-4d42-a2d4-308aecc7a350)

What errors are you seeing?

**Comment by toi500** [comment]
@SirL0gic try to remove the cache node, which is buggy.
