### ISSUE TITLE
[BUG] Chat isn't working

### ISSUE THREAD

**Issue by dnish** [FlowiseAI/Flowise#3195]
When I create a new chat flow and save it (f.e. http://localhost:3000/canvas/bf22db38-623b-44da-b5b5-aceea6ba8d8c), the chat module isn't working anymore. As far as I click on the chat icon, the whole pages crashes and I only see a white empty space. The following error is logged:

```
TypeError: Cannot read properties of undefined (reading 'map')
    at index-iUz5VanK.js:615:4031
```

Which represents the following line:

```
N((te = B.data) == null ? void 0 : te.fileUploadSizeAndTypes.map(re => re.fileTypes).join(",")))
```

I've tried it with my own template and also used one from the marketplace. Both are not working. I'm on Node 22 and Flowise 2.0.7

**Comment by subhamengine** [comment]
hey, i would like to fix this issue.

**Comment by dnish** [comment]
Hey,
it seems that the issue only occurs with Node 22, downgrading to Node 20 solves the issue.

**Comment by subhamengine** [comment]
so is it already fixed, or I have to work upon it?

**Comment by dnish** [comment]
Depends, if Node 22 is already supported (the docs say Node 20 and above). The bug only appeared with this versions. I also tried to downgrade Flowise to 2.0.5 but got the same error there. After that, I removed Node 22 and installed Node 20 and everything worked after that.

**Comment by HenryHengZJ** [comment]
Currently we only support up to Node 20. Closing for now
