### ISSUE TITLE
[Feature Support]The Flowise setup does not support OpenAI's newly released O1 series models. When attempting to configure these models, the following errors are encountered:

### ISSUE THREAD

**Issue by wayneWudh** [FlowiseAI/Flowise#3198]
**Describe the bug**
The Flowise setup does not support OpenAI's newly released O1 series models. When attempting to configure these models, the following errors are encountered:

- `400 Unsupported value: 'messages[0].role' does not support 'system' with this model.`
- `400 Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.`
- `400 Unsupported value: 'temperature' does not support 0.9 with this model. Only the default (1) value is supported.`

**To Reproduce**

1. Go to the Flowise interface or API integration.
2. Configure the OpenAI O1 series model.
3. See the 400 error messages as described above.

**Expected behavior**
The O1 series models should support configurations for `system` roles, enabling message flow customization, and allow more flexibility with the `stream` and `temperature` parameters, similar to other OpenAI models.

**Comment by HenryHengZJ** [comment]
![image](https://github.com/user-attachments/assets/93ea57f0-3e39-4d6d-8220-183e1398b73a)

https://openai.com/index/introducing-openai-o1-preview/
