### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tejaswiniallikanti** [FlowiseAI/Flowise#320]
I am using flowise on render.com and the chatflows that I have created are not saving at all.

**Comment by govind-kumarr** [comment]
@tejaswiniallikanti  is it showing some error?

**Comment by kwlockwo** [comment]
I have a feeling this may have something to do with Render (and other PaaS') using ephemeral disks, and the server seems to use sqlite: https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/DataSource.ts#L13.  The data stored here will be lost on server restarts.

It would be nice if FlowiseAI could configure this location to something other than `$HOME/.flowsise` and then it could work with Render and a persistent disk: https://render.com/docs/disks

This wouldn't work on Heroku at all.  Probably need to support a datasource other than sqlite.

**Comment by tejaswiniallikanti** [comment]
I am not able to save the chatflows that i have created here. I want to use the API from these chatflows but i am not able to do that here

**Comment by tejaswiniallikanti** [comment]
Is there any way around it?

**Comment by johnbeynon** [comment]
👋 From the Render Support team - I opened an issue yesterday on the Flowise docs page, specifically about this and suggestion for the docs on how to resolve

https://github.com/FlowiseAI/FlowiseDocs/issues/5

**Comment by HenryHengZJ** [comment]
thanks @johnbeynon for the suggestion!

In the latest v1.2.13 release, you can specify an env `DATABASE_PATH`. This will allow you to specify where the data is being stored. And using Render's Disk, you can mount that path and have persistent storage. 

Here's the step by step guide - https://docs.flowiseai.com/deployment/render#persistent-disk

Let us know if that resolves the issue

**Comment by gHashTag** [comment]
@HenryHengZJ I did everything as in the documentation, but chats are still not saved. What could be the problem?
<img width="1054" alt="Screenshot 2023-12-25 at 17 30 31" src="https://github.com/FlowiseAI/Flowise/assets/6774813/9e152140-f0df-4e57-9ecb-28d8f61f0fd9">
