### ISSUE TITLE
[BUG] PineconeClient: Error getting project name: SyntaxError... after first input in chat

### ISSUE THREAD

**Issue by HorstA** [FlowiseAI/Flowise#321]
**Describe the bug**
PDF->Pinecone->Conversational Retrieval QA Chain (see attachement)
pdf is not loaded and this error occures:
[ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]

**To Reproduce**
Load Chatflow
Choose a pdf
start chat
ask something

**Expected behavior**
loading the pdf into pinecone and answer

**Screenshots**
[oas-cash-pdf Chatflow.json.txt](https://github.com/FlowiseAI/Flowise/files/11743919/oas-cash-pdf.Chatflow.json.txt)

**Setup**

-   OS: Windows
-   Browser chrome
-  [flowise@1.2.12]

tried with several pdfs, has worked with older version

**Comment by HenryHengZJ** [comment]
can you try deleting the node, drag n drop a new one to canvas and see if that works?

**Comment by HorstA** [comment]
when deleting and redrop the Pinecone Upsert Document Node, there is an input field Pinecone namespace instead of Additional Params. 
Filling it with my namespace (or leaving it blank) results in the same old error (ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0)

I put it to railway, but still same error

Found this in the deploy logs, maby it helps: 

﻿Starting Flowise...
﻿TypeError: Cannot read properties of undefined (reading 'startsWith')
﻿at Pdf_DocumentLoaders.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/documentloaders/Pdf/Pdf.js:81:27)
﻿at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:208:72)
﻿at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:539:44)
﻿at async /usr/local/lib/node_modules/flowise/dist/index.js:294:13
﻿[ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]
﻿[ErrorWithoutStackTrace: PineconeClient: Error getting project name: SyntaxError: Unexpected token A in JSON at position 0]

**Comment by HorstA** [comment]
Same with the "Metadata Filter Load" template from the marktplace, no change after delete and redrop the node

**Comment by HenryHengZJ** [comment]
are you installing flowise via docker or `npx flowise start` or `yarn start` ?

if using npx can you reinstall `npm install -g flowise` and `npx flowise start`?

if using `yarn start`:
```
git clone https://github.com/FlowiseAI/Flowise.git
cd Flowise
yarn install
yarn build-force
yarn start
```

This flow works for me:
[example Chatflow.txt](https://github.com/FlowiseAI/Flowise/files/11751062/example.Chatflow.txt)

**Comment by HorstA** [comment]
I have solved it.

Reinstalling with yarn did not bring any changes. I then deleted the index and created a new one. Now it works. Not understandable, but obviously not a problem on Flowise's part.
Thanks a lot for helping me troubleshoot this.

Flowise is such a great project with fantastic developers.
Thanks again Henry!
