### ISSUE TITLE
[BUG] SSE Streaming Bugs for multiple tools

### ISSUE THREAD

**Issue by hahl9000** [FlowiseAI/Flowise#3222]
**Describe the bug**
When using chains as tools the new version streams both an answer that tool 1 doesnt know and then streams tool 2 answer. It doesnt adhere to my system prompt anymore.

**To Reproduce**

1. Create 2 tools from flows. One that doesnt know and one which does.
2. Ask it to always use tool 1 first. If tool 1 doesnt know then use tool 2. 
3. Embed to a page, ask questions that tool 2 knows and then it will stream both that it doesnt know and right after the answer.
4. See output.

**Expected behavior**
To be able to sort out the answer that doesnt know. Prompt adherence seems off and it worked great in previous version.

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [render]
-   Flowise Version [flowise 2.1.1, embed 2.0.1]
-   OS: [Windows]
-   Browser [chrome]

**Additional context**
Worked better in previous version. Creates a problem with to flowtools that should complement each other.

**Comment by HenryHengZJ** [comment]
Do you have an example chatflow we can use to replicate?

**Comment by hahl9000** [comment]
No, I've looked into it and from what I can see, even though its a bit laggy the test chat concatenates the answer and remove the streaming answer from the tool that doesn't know. I'm thinking this could be an issue with the latest embed instead?
