### ISSUE TITLE
[BUG] SQL Chain 

### ISSUE THREAD

**Issue by takefy-dev** [FlowiseAI/Flowise#3225]
**Describe the bug**
The SQL Chain never worked even with default prompt! It always fail because the llm return a full string instead of a sql query even though if he return a sql valid query it does not run.   sqlMessage: `Erreur de syntaxe près de 'Question: "commandes client email@gmail.com"\n` +
    `SQLQuery: "SELECT * FROM ps...' à la ligne 1`,
  sql: 'Question: "commandes client 
email@gmail.com"\n' +
    `SQLQuery: "SELECT * FROM ps_orders WHERE id_customer = (SELECT id_customer FROM ps_customer WHERE email = 'email@gmail.com');"`
**To Reproduce**

1. Go to 'Agent flow'
2. Create a SQL chain
3. Run

**Expected behavior**
I wanted to give a good result and return actual data of my database (prestashop 1.7.8 model)

**Screenshots**

**Flow**

.

**Setup**

-   Installation [, `npx flowise start`]
-   Flowise Version [2.1.1]
-   OS: [$Windows]
-   Browser [e.g. chrome]

**Additional context**
The llm does not need to retreive the database column names ect because i specified on the prompt it's a prestashop 1.7.8 database and the llm knows already which column is it.

**Comment by HenryHengZJ** [comment]
Flowise cant handle circular logic, try connecting each chatopenai to the nodes separately:
![image](https://github.com/user-attachments/assets/aef38f80-afb5-4469-8ba3-27d80c2adcd0)

**Comment by takefy-dev** [comment]
Ok dang it I fault so thanks very much ; ) will def do this

**Comment by takefy-dev** [comment]
I will test Monday at work & le you know

**Comment by takefy-dev** [comment]
hey i've testde again still does not work... it just respond 
 code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlState: '42000',
  sqlMessage: `Erreur de syntaxe près de 'Question: "commandes client exemple@exemple.com"\n` +
    `SQLQuery: "SELECT * FROM ps...' à la ligne 1`,
  sql: 'Question: "commandes client julesdix71@gmail.com"\n' +
    `SQLQuery: "SELECT * FROM ps_orders WHERE id_customer = (SELECT id_customer FROM ps_customer WHERE email = 'exemple@exemple.com');"`
}

and never execute sql queries

**Comment by yangzishy** [comment]
> hey i've testde again still does not work... it just respond code: 'ER_PARSE_ERROR', errno: 1064, sqlState: '42000', sqlMessage: `Erreur de syntaxe près de 'Question: "commandes client exemple@exemple.com"\n` + `SQLQuery: "SELECT * FROM ps...' à la ligne 1`, sql: 'Question: "commandes client [jexemple@exemple.com](mailto:jexemple@exemple.com)"\n' + `SQLQuery: "SELECT * FROM ps_orders WHERE id_customer = (SELECT id_customer FROM ps_customer WHERE email = 'exemple@exemple.com');"` }
> 
> and never execute sql queries

Hello, I encountered the same problem. Have you solved it yet?
