### ISSUE TITLE
[BUG] Does NOT show version

### ISSUE THREAD

**Issue by asrguru20** [FlowiseAI/Flowise#3227]
**Describe the bug**
in the latest version when I go to the about flowise it does not show what is the current version 

is this a bug or no

**Comment by HenryHengZJ** [comment]
its correctly showing: 
![image](https://github.com/user-attachments/assets/d7511fe6-6dad-476e-a12f-bf4638b6cc5f)

**Comment by asrguru20** [comment]
Thank you henry
