### ISSUE TITLE
[FEATURE] Enable streaming in Embed versions

### ISSUE THREAD

**Issue by blissiraDC** [FlowiseAI/Flowise#3230]
**Describe the feature you'd like**
As per the title. Is this possible? 

"Will there ever come a day when embed UI matches the quality of styling and formatting as the Test chat in Flowise UI? "

**Comment by HenryHengZJ** [comment]
Embed is always able to stream same as the UI

**Comment by blissiraDC** [comment]
I still the old style responses with loading animation followed by text.  Flowise 2.1.1 - FlowiseEmbed 2.0.1

![image](https://github.com/user-attachments/assets/ff73bdb9-4423-415a-ab85-02fb8f8af560)

**Comment by alper1969** [comment]
Hi, this is exactly correct. It seams that we have a serious problem for streaming.

**Comment by saxoji** [comment]
<img src=> or <iframe src=> tags are not rendered properly and the code is displayed as is. in the latest version

**Comment by HenryHengZJ** [comment]
can you try igconito or other browser?
