### ISSUE TITLE
[BUG ]"Required" field in  custom tool is not sent to LLM.

### ISSUE THREAD

**Issue by me-tetr** [FlowiseAI/Flowise#3232]
**Describe the bug**
"Required" field in  custom tool is not sent to LLM. This leads to a very weird behaviour -  if not ALL the fields are present (including the ones declared  as not required) an agent does not use the tool and instead tells me that the instructions have been successfully completed. I've tried various approaches such as saying that the field is optional or not required in the description field.

**To Reproduce**
1 - create a custom tool. mark some fields as not required and send them over to your favourite llm.
2 - analyse via langsmith
3- look at metadata sent to llm
4- see that agent confirms action whilst not really calling the tool 

**Expected behavior**
The agent should invoke the tool when all required 

**Screenshots**

![Screenshot 2024-09-22 at 17 04 17](https://github.com/user-attachments/assets/9b670169-d78b-40c8-90a2-9c6ec1fd5c9a)
![Screenshot 2024-09-22 at 17 03 32](https://github.com/user-attachments/assets/a00941cf-f675-4d86-aa92-981ba7356932)
![Screenshot 2024-09-22 at 17 02 46](https://github.com/user-attachments/assets/9888220a-dc9b-42a4-8568-181b5734e18b)
![Screenshot 2024-09-22 at 16 56 17](https://github.com/user-attachments/assets/a0bb8b52-024c-4d51-936e-23d3eb354532)

**Setup**

-   Installation :`pnpm start`
-   Flowise Version  - 2.1.1
-   OS: mac os
-   Browser chrome

**Comment by HenryHengZJ** [comment]
ahh I see, so the `required` should only contains those we ticked required on the custom tool
