### ISSUE TITLE
[BUG] Reseting API Keys when redeploying

### ISSUE THREAD

**Issue by schieck0** [FlowiseAI/Flowise#3236]
**Describe the bug**
My generated API Keys are being lost and the default one is reset when the container is redeployed.

**To Reproduce**
1. Go to 'API Keys'
2. Click on 'Create Key'
3. Redeploy de server container
4. The created key is lost and the default one changes value.

**Expected behavior**
Keep the same generated keys.

**Setup**

-   Installation docker
-   Flowise Version 2.1.1
-   OS: AWS Linux on Elastic Container Service

**Comment by schieck0** [comment]
Solved by setting APIKEY_STORAGE_TYPE env as 'db'

**Comment by HenryHengZJ** [comment]
glad you figured out! https://docs.flowiseai.com/configuration/environment-variables#for-flowise-api-keys
