### ISSUE TITLE
[BUG] API Loader with Self-Signed Certificate

### ISSUE THREAD

**Issue by El-Tommy** [FlowiseAI/Flowise#3239]
I am trying to perform an Upsert based on an API Loader that calls an endpoint with a self-signed certificate.

But I am seeing this error:

`Error: vectorsService.upsertVector - Error: Failed to post https://192.168.1.1:9200/myindex/_search?filter_path=hits.hits._source: Error: self-signed certificate in certificate chain`

How can I disable this verification? I don't see any configuration option in the API Loader.

**Comment by HenryHengZJ** [comment]
Alternative is to use Custom Document Loader:
![image](https://github.com/user-attachments/assets/e51c9452-f61e-48db-bee8-4cbd76ba4a83)

**Comment by Y785071** [comment]
You can set env  export NODE_TLS_REJECT_UNAUTHORIZED='0' 
before flowise start. 
It's worked for me.
