### ISSUE TITLE
[BUG] Flowise freezes UI and takes 300+ seconds to answer

### ISSUE THREAD

**Issue by vitusan** [FlowiseAI/Flowise#3246]
**Describe the bug**
I don't know why, but seems that, after the fourth or fifth message, flowise, both self hosted and cloud version, halt the execution and take this much long to finish the run.

Doesn't seem like a rate limiting from the OpenAI but something within flowise, because smaller sequential agents flows won't present such beahavior, not as often at least. 

[LangSmith Report](https://smith.langchain.com/public/6d81c2e9-c60b-4079-96fb-646fcbf0fc18/r)

**To Reproduce**

1. Ask anything for the flow, until it reaches the fourth or fifth message, through UI or API
2. It freezes and hangs until it quits or finishes after 300 seconds or so.

**Expected behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/ce4edbd4-c9f1-44c2-86c8-4b84080a8a2d)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

[Time Protocolo da autoconfiança Agents (3).json](https://github.com/user-attachments/files/17120235/Time.Protocolo.da.autoconfianca.Agents.3.json)

**Setup**

-   Installation Docker
-   Flowise Version 2.1.1
-   OS: Ubuntu 20.04
-   Browser opera

**Additional context**
Help

**Comment by HenryHengZJ** [comment]
thats a nice graph! I think something about the retriever is not working correctly, since you can see alot of not making sense response, and this causes ChatGPT not able to respond correctly:
![image](https://github.com/user-attachments/assets/e4f3e202-3761-4519-86c0-949a54681d0f)
