### ISSUE TITLE
[BUG] : Embed to website code problem. Cause duplicate request chatid and multiple looping

### ISSUE THREAD

**Issue by zahili** [FlowiseAI/Flowise#3247]
**Describe the bug**
Embed chatbot in website problem. It cause duplicate request chatid. it will loop forever and causing my openai api credit usage very high. 

**To Reproduce**
Just embed the chatbot to your website

**Expected behavior**
Causing duplicate chatid and it will loops forever until i stop the system with docker stop.  It will cause openai api credit usage very high.

**Screenshots**
Screenshot from server-requests.log.jsonl logs
![image](https://github.com/user-attachments/assets/e2f3877b-cf6d-41c9-8d4a-a84bc69ba1bd)

{"level":"info","message":"⬆️ POST /api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a","package":"server","request":{"body":{"chatId":"666a1339-ebd8-4774-8483-35f763892f5a","overrideConfig":{},"question":"pgdt","streaming":true},"headers":{"accept":"text/event-stream","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9","connection":"close","content-length":"104","content-type":"application/json","host":"chatbot.oum.edu.my","origin":"[https://myoumnew.com","referer":"https://myoumnew.com/","sec-ch-ua":"\"Google](https://myoumnew.com","referer":"https//myoumnew.com/%22,%22sec-ch-ua%22:%22%5C%22Google) Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":""Windows"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"cross-site","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","x-forwarded-for":"1.32.16.184","x-real-ip":"1.32.16.184"},"method":"POST","params":{},"query":{},"url":"/api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a"},"timestamp":"2024-09-25 02:03:51"}
{"level":"info","message":"⬆️ POST /api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a","package":"server","request":{"body":{"chatId":"666a1339-ebd8-4774-8483-35f763892f5a","overrideConfig":{},"question":"pgdt","streaming":true},"headers":{"accept":"text/event-stream","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9","connection":"close","content-length":"104","content-type":"application/json","host":"chatbot.oum.edu.my","origin":"[https://myoumnew.com","referer":"https://myoumnew.com/","sec-ch-ua":"\"Google](https://myoumnew.com","referer":"https//myoumnew.com/%22,%22sec-ch-ua%22:%22%5C%22Google) Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":""Windows"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"cross-site","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","x-forwarded-for":"1.32.16.184","x-real-ip":"1.32.16.184"},"method":"POST","params":{},"query":{},"url":"/api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a"},"timestamp":"2024-09-25 02:03:57"}
{"level":"info","message":"⬆️ POST /api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a","package":"server","request":{"body":{"chatId":"666a1339-ebd8-4774-8483-35f763892f5a","overrideConfig":{},"question":"pgdt","streaming":true},"headers":{"accept":"text/event-stream","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9","connection":"close","content-length":"104","content-type":"application/json","host":"chatbot.oum.edu.my","origin":"[https://myoumnew.com","referer":"https://myoumnew.com/","sec-ch-ua":"\"Google](https://myoumnew.com","referer":"https//myoumnew.com/%22,%22sec-ch-ua%22:%22%5C%22Google) Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":""Windows"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"cross-site","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","x-forwarded-for":"1.32.16.184","x-real-ip":"1.32.16.184"},"method":"POST","params":{},"query":{},"url":"/api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a"},"timestamp":"2024-09-25 02:04:01"}
{"level":"info","message":"⬆️ POST /api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a","package":"server","request":{"body":{"chatId":"666a1339-ebd8-4774-8483-35f763892f5a","overrideConfig":{},"question":"pgdt","streaming":true},"headers":{"accept":"text/event-stream","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9","connection":"close","content-length":"104","content-type":"application/json","host":"chatbot.oum.edu.my","origin":"[https://myoumnew.com","referer":"https://myoumnew.com/","sec-ch-ua":"\"Google](https://myoumnew.com","referer":"https//myoumnew.com/%22,%22sec-ch-ua%22:%22%5C%22Google) Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":""Windows"","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"cross-site","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","x-forwarded-for":"1.32.16.184","x-real-ip":"1.32.16.184"},"method":"POST","params":{},"query":{},"url":"/api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a"},"timestamp":"2024-09-25 02:04:06"}
{"level":"info","message":"⬆️ POST /api/v1/prediction/a26d3532-5013-4877-aa6d-b6ce9eb2162a","package":"server","request":{"body":{"chatId":"666a1339-ebd8-4774-8483-35f763892f5a","overrideConfig":{},"question":"pgdt","streaming":true},"headers":{"accept":"text/event-stream","accept-encoding":"gzip, deflate, br, zstd","accept-language":"en-US,en;q=0.9","connection":"close","content-length":"104","content-type":"application/json","host":"chatbot.

**Flow**
just embed your flow to website

**Setup**

-   Installation docker
-   Flowise Version 2.0.7
-   OS: Linux
-   Browser chrome

**Additional context**

**Comment by Fserlut** [comment]
Same

**Comment by HenryHengZJ** [comment]
What version of Flowise you are using? and on the embed, are you using `https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js`? https://docs.flowiseai.com/using-flowise/embed#using-specific-version

**Comment by zahili** [comment]
i use Flowise Version 2.0.7

i use this import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js" and this import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed@1.3.14/dist/web.js. Both problem. Causing infinite loop with duplicate request chatid

**Comment by Fserlut** [comment]
I downgraded to 1.3.10, and now it works.

**Comment by HenryHengZJ** [comment]
> i use Flowise Version 2.0.7
> 
> i use this import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js" and this import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed@1.3.14/dist/web.js. Both problem. Causing infinite loop with duplicate request chatid

can you try the latest 2.1.1 Flowise?

**Comment by zahili** [comment]
> > i use Flowise Version 2.0.7
> > i use this import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js" and this import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed@1.3.14/dist/web.js. Both problem. Causing infinite loop with duplicate request chatid
> 
> can you try the latest 2.1.1 Flowise?

I have upgrade to latest version. Now it's OK. But I have to paid around 700 dollars because of infinite loop to openai. 😔

**Comment by HenryHengZJ** [comment]
ahh damn im sorry to hear that!

**Comment by makarovartyom** [comment]
Had the same problem over here and also been charged quite an amount (around 1k since the issue arised). Just an idea - could be great to aquire the additional credits from openAI team and share with the others affected by the bug. 
The request could come from Flowise team, I'm sure they could support the framework future develpment.

**Comment by HenryHengZJ** [comment]
Found out the issue: it was because the Embed keeps retrying to send server side event request every 1sec if it fails. We need to throw an error to prevent it from keep retrying: https://github.com/FlowiseAI/FlowiseChatEmbed/pull/256

CDN is also updated: https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js

Therefore we should be okay now, even if you still didnt update Flowise

**Comment by zahili** [comment]
Tq Henry. Appreciate your help.
