### ISSUE TITLE
RAG in Arabic using document store

### ISSUE THREAD

**Issue by aboodmanna** [FlowiseAI/Flowise#3253]
### Discussed in https://github.com/FlowiseAI/Flowise/discussions/3252

<div type='discussions-op-text'>

<sup>Originally posted by **aboodmanna** September 25, 2024</sup>
Hi,
I am creating a Flowise RAG model using document store for some Arabic documents, I have tried the same model for English documents and it worked fine, but for the Arabic documents it is not giving a response and not searching inside
 the Arabic documents.
Does any body know how to fix this? 
![Screenshot 2024-09-25 125951](https://github.com/user-attachments/assets/a8520536-8141-4409-8ce6-cb79b70bd17b)
</div>

**Comment by HenryHengZJ** [comment]
try specifying prompt and explicily ask LLM to return and read in your language:
![image](https://github.com/user-attachments/assets/66bd28c7-3db1-4d88-bed2-3cf3f4d7ca4f)
