### ISSUE TITLE
[BUG]Infinite loop

### ISSUE THREAD

**Issue by kampmannNFT** [FlowiseAI/Flowise#3254]
**Describe the bug**
all flows are ending in a infinite loop and the GUI throws multiple errors in dev console of chrome.

**To Reproduce**

1. Go to 'Chat Flows'
2. Click on 'Add New'
3. Drag and Drop some simple Nodes 'For example ChatOpenAI, Prompt Template, LLM CHat'
4. Save Flow
5. Flow is supposed to translate the given text in another language (YouTube Example)
6. the flow starts end never ends
7. the gui chat window updates only after closing and open again

**Expected behavior**
Enter a text in the chat window an get a single result.

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [docker compose (Docker Desktop)]
-   Flowise Version [latest]
-   OS: [Windows 10]
-   Browser [chrome]

**Additional context**

**Comment by HenryHengZJ** [comment]
I have Flowise on Docker Desktop, and a simple flow, it works as expected, response are streamed back:
![image](https://github.com/user-attachments/assets/c23e59de-9125-456e-96fe-123b28394145)

**Comment by kampmannNFT** [comment]
I started the container on another System. It seems due to my notebook or browser. Have you ever seen this?

***@***.***
Von: Henry Heng ***@***.***>
Gesendet: Mittwoch, 25. September 2024 18:25
An: FlowiseAI/Flowise ***@***.***>
Cc: Jens Kampmann - NFT automates ***@***.***>; Author ***@***.***>
Betreff: Re: [FlowiseAI/Flowise] [BUG]Infinite loop (Issue #3254)


I have Flowise on Docker Desktop, and a simple flow, it works as expected, response are streamed back:
image.png (view on web)<https://github.com/user-attachments/assets/c23e59de-9125-456e-96fe-123b28394145>

**Comment by kampmannNFT** [comment]
My colleague has the same behavior.

***@***.***

Von: Henry Heng ***@***.***>
Gesendet: Mittwoch, 25. September 2024 18:25
An: FlowiseAI/Flowise ***@***.***>
Cc: Jens Kampmann - NFT automates ***@***.***>; Author ***@***.***>
Betreff: Re: [FlowiseAI/Flowise] [BUG]Infinite loop (Issue #3254)


I have Flowise on Docker Desktop, and a simple flow, it works as expected, response are streamed back:
image.png (view on web)<https://github.com/user-attachments/assets/c23e59de-9125-456e-96fe-123b28394145>

**Comment by HenryHengZJ** [comment]
No I havent came across this, and no related issues reported as well. I'd say check other browser, or other deployment method

**Comment by kampmannNFT** [comment]
The problem was Sophos Cybersecurity.

Von: Henry Heng ***@***.***>
Gesendet: Donnerstag, 26. September 2024 16:51
An: FlowiseAI/Flowise ***@***.***>
Cc: Jens Kampmann - NFT automates ***@***.***>; Author ***@***.***>
Betreff: Re: [FlowiseAI/Flowise] [BUG]Infinite loop (Issue #3254)


No I havent came across this, and no related issues reported as well. I'd say check other browser, or other deployment method
