### ISSUE TITLE
Provide the ability to load Multiple pdf-s

### ISSUE THREAD

**Issue by ashokrs** [FlowiseAI/Flowise#328]
**Describe the feature you'd like**
Provide the ability to load Multiple pdf-s
Currently, I have to create multiple single pdf loader on the web flow UI. IS there anything am I missing?

**Comment by HenryHengZJ** [comment]
you can upload multiple files from pdf loader

**Comment by ashokrs** [comment]
WoW. IS that right? I didn't know.. Let me try.
