### ISSUE TITLE
[BUG] Terraform - After deployment Issue

### ISSUE THREAD

**Issue by Krishna-Maiden** [FlowiseAI/Flowise#3291]
**Describe the bug**
I am able to deploy the application but its getting error to display chatflows.

<img width="909" alt="image" src="https://github.com/user-attachments/assets/b97b6348-0007-495e-8757-fe05480ed370">
<img width="827" alt="image" src="https://github.com/user-attachments/assets/cc841cd4-c003-47c7-9635-cee4c6c1bef7">

**Comment by Krishna-Maiden** [comment]
To close this issue.

1. need to enable uuid-ossp in postgres sql
2. remove zone option in database tf
3. add DATABASE_SSL=true in webapp.tf

**Comment by HenryHengZJ** [comment]
which terraform guide are you using? if possible, an update on the docs would be helpful! https://github.com/FlowiseAI/FlowiseDocs
