### ISSUE TITLE
[BUG] Chat dialog showing raw HTML

### ISSUE THREAD

**Issue by raw-brt** [FlowiseAI/Flowise#3295]
**Describe the bug**
The chat dialog shows raw HTML as response while working properly in flowise canvas.

**To Reproduce**

1. Create a chatbot
2. Inject the script on a webpage
3. Start talking to it

**Screenshots**
![CleanShot 2024-10-02 at 14 30 36@2x](https://github.com/user-attachments/assets/f389462a-7cb3-4eda-8905-8f3a1154d5b0)

**Additional context**
Was working properly until two days ago.

**Comment by HenryHengZJ** [comment]
can you attach a screenshot on the flowise UI response? In embedded this is prevented to avoid cross site scripting. In other words, users can inject some code into your embedded chatbot and do harm on your application

**Comment by raw-brt** [comment]
Sure thing.

Here it is, working properly:

![CleanShot 2024-10-02 at 18 59 46@2x](https://github.com/user-attachments/assets/4c729ea9-f307-49d6-95ba-5865c5534cf0)

The injected script is exactly as it's shared in the < /> dialog triggered from the flowise ui.

Thank you, Henry!

**Comment by HenryHengZJ** [comment]
are you on the latest version on flowise? in the meantime, this might helps: https://docs.flowiseai.com/using-flowise/embed#using-specific-version

**Comment by raw-brt** [comment]
We have this version:

![image](https://github.com/user-attachments/assets/ae3fb19b-3722-4b1c-9b1f-dbb9d5e82c04)

**Comment by raw-brt** [comment]
We've updated to the latest version and it's working properly again.
