### ISSUE TITLE
[BUG] Embedded Flowise chatbot is no longer responding on the website

### ISSUE THREAD

**Issue by k88joshi** [FlowiseAI/Flowise#3298]
**Describe the bug**
Embedded Chatbot on the website is no longer serving response.  It is working on the deployed Flowise app but not serving responses to the website.

**To Reproduce**

1. Go to Flowise application
2. Create a custom QA chatbot workflow
3. Get the full HTML embed code to embed into your website.
4. Embed this code into the website and run it locally.

**Expected behavior**
When you talk to the chatbot locally, you should get the same response that you would get in the chatbot on the Flowise instance. 

**Setup**

-   Installation on Railway
-   Flowise Version 1.8.4
-   OS: Linux
-   Browser: Chrome

**Comment by matheusduzzi** [comment]
I'm taking the same problem in my application. Anyone took a look at this issue?

**Comment by HenryHengZJ** [comment]
here: https://docs.flowiseai.com/using-flowise/embed#using-specific-version

**Comment by matheusduzzi** [comment]
But is there any explication about these error? Sorry but I don't understand what are happening

**Comment by HenryHengZJ** [comment]
yes, if you are using latest embed version, and your Flowise app is not on version v2.1.0 and above, it will not work.

You can either use a specific version of embed, which works with older version of Flowise

or

Update flowise app and use latest embed version
