### ISSUE TITLE
[BUG]Chatbot input design distorted

### ISSUE THREAD

**Issue by vkrm-segta** [FlowiseAI/Flowise#330]
**Describe the bug**
When i  paste text in input more than three lines  chatbot input design are distorted
<img width="484" alt="Screenshot 2023-06-14 at 11 55 44 PM" src="https://github.com/FlowiseAI/Flowise/assets/124426279/089a22b5-3a50-4f06-b113-831fb539c422">

**Comment by vkrm-segta** [comment]
@HenryHengZJ i want to work on this issue.

**Comment by kswitch** [comment]
@HenryHengZJ is this still an issue?
@vkrm-segta have you been able to fix this issue?

**Comment by HenryHengZJ** [comment]
oh sorry forgot to close the issue. It has been fixed and merged - https://github.com/FlowiseAI/Flowise/pull/333
