### ISSUE TITLE
Issue while upserting with mysql records manager

### ISSUE THREAD

**Issue by coders21** [FlowiseAI/Flowise#3302]
Hi i am upserting data on pinecone with mysql record manager and it throws UUID and namespace error, unable to get what is the issue any suggestions?

![issue2](https://github.com/user-attachments/assets/2cb488ab-deae-4a7b-80fe-17b2662a74a8)

**Comment by coders21** [comment]
@HenryHengZJ  any suggestions please?

**Comment by coders21** [comment]
@HenryHengZJ

**Comment by HenryHengZJ** [comment]
Moving to: https://github.com/FlowiseAI/Flowise/issues/3354
