### ISSUE TITLE
[BUG] Rate limit message not displaying

### ISSUE THREAD

**Issue by Daniel-DDV** [FlowiseAI/Flowise#3305]
The Rate Limit Message is not displaying. Rate limit works, but no message appears.

**To Reproduce**
Select Rate Limiting in Chatflow Configuration, set rate limit, set limit message and then save. 

Rate limit will trigger, but no message will appear.

**Expected behavior**
Displaying the rate limit message when the rate limit is hit.

**Setup**
Docker
Flowise 2.1.1

@HenryHengZJ

**Comment by Daniel-DDV** [comment]
I would like to add to that that once you remove the rate limit, it remains. Workaround is to set 999 per 60 and add a message. This could probably do with an on/off button as well?

**Comment by HenryHengZJ** [comment]
PR: https://github.com/FlowiseAI/FlowiseChatEmbed/pull/263
