### ISSUE TITLE
[FEATURE] Prometheus metrics

### ISSUE THREAD

**Issue by turbotankist** [FlowiseAI/Flowise#3310]
**Describe the feature you'd like**
It would be nice to have a Prometheus metric for path `/metrics`.
I am running Flowise in Kubernetes and monitoring resource metrics is not a problem, but I need metrics for chats.

**Additional context**
Node.js client https://github.com/siimon/prom-client.

**Comment by HenryHengZJ** [comment]
Merged: https://github.com/FlowiseAI/Flowise/pull/3420
Docs: https://docs.flowiseai.com/using-flowise/monitoring#opentelemetry
