### ISSUE TITLE
[BUG] File vector upsert (API) - how to attach overrideConfig

### ISSUE THREAD

**Issue by bendadaniel** [FlowiseAI/Flowise#3320]
Hello,

**Describe the bug**
I upsert file to Pinecone vector store via API. It works fine. Hovewer I also want to include overrideConfig to push some specific metadata to vector store. I cannot find a way how to do it. When document is upserted it always contains string "{{$vars.mediaId}}" as metadata value. Chatflow should be fine I think, because if I change Document loader setting - additional metadata to awMediaId:"{{$flow.chatId}}" it works and in Pinecone's metadata 'awMediaId' is real chat id in value.

Base js code: (it works fine)
```ts
let formData = new FormData();
  formData.append("files", base64ToBlob(fileBase64, 'application/pdf'), "document.pdf");
  formData.append("chatId", chatId);  
  const response = await fetch(
      `${apiHost}/api/v1/vector/upsert/${chatflowid}`,
      {
          method: "POST",
          body: formData
      }
  );
  const result = await response.json();
```

I tried to append overrideConfig like this but it doesnt work:
```js
// 1
formData.append("overrideConfig", JSON.stringify(
  {
    "vars": {
      "mediaId": "media-id-123"
  }
}));

// 2
formData.append("overrideConfig[vars][mediaId]", "media-id-123");  

// 3
formData.append("mediaId", "media-id-123");
```

**Document loader**
<img width="685" alt="Screenshot 2024-10-08 at 14 38 00" src="https://github.com/user-attachments/assets/29d7a738-157b-4f5d-a58a-ef6a8364fa41">

**Pinecode result**
<img width="547" alt="Screenshot 2024-10-08 at 14 38 18" src="https://github.com/user-attachments/assets/9c780933-d76b-4ae7-b2ae-2a3c84a3f1fb">

**Test with variable $flow.chatId -- it works**
<img width="609" alt="Screenshot 2024-10-08 at 14 47 57" src="https://github.com/user-attachments/assets/5cc525aa-62c5-46cf-9dd2-f6dc4e24f6d2">
<img width="580" alt="Screenshot 2024-10-08 at 14 46 31" src="https://github.com/user-attachments/assets/5f677fc7-8684-4dab-b339-83ef418386a5">

Do you have please any idea how to solve my problem?

Thank you

**Comment by HenryHengZJ** [comment]
I think one workaround is to have `metadata` in the formBody

```
formData.append("metadata", JSON.stringify({ "mediaId": "media-id-123" }));
```
