### ISSUE TITLE
[BUG] I am not able to access my flowise cloud instance for the second day https://elena-tsemirava-it-beratung.app.flowiseai.com/. 

### ISSUE THREAD

**Issue by etsemirava** [FlowiseAI/Flowise#3323]
**Describe the bug**
I am not able to access my flowise cloud instance for the second day https://elena-tsemirava-it-beratung.app.flowiseai.com/. 
<img width="789" alt="Screenshot 2024-10-09 at 13 10 19" src="https://github.com/user-attachments/assets/f4533893-3d25-49f7-900b-a7ef1e71881e">

**To Reproduce**

1. Go to https://flowiseai.com/
2. Click on Dashboard
3. Wait for 1-2 mins
4. See error :
This site can't be reached
elena-tsemirava-it-beratung.app.flowiseai.com took too long to respond.
Try:
• Checking the connection
• Checking the proxy and the firewall
ERR_CONNECTION_TIMED_OUT

**Expected behavior**
Access to Flowiseai dashboard

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation Flowise Cloud
-   Flowise Version
-   OS: macOS,
-   Browser Chrome, Safari, Firefox

**Additional context**
I was using a free version which is valid until Oct 11th (2 days more). I am happy to pay, but I cannot access the instance.

**Comment by HenryHengZJ** [comment]
sorry for the downtime! its up and running now :)

**Comment by etsemirava** [comment]
Thank you Henry! You are my hero!
I would like to use Flowiseai in my commercial product. Could you please share my contacts with your Sales Guys?
elena.tsemirava@gmail.com 
Thanks!
