### ISSUE TITLE
[BUG] Document Store (Vector) node doesn't allow selection from existing document store.

### ISSUE THREAD

**Issue by mapachekurt** [FlowiseAI/Flowise#3338]
**Describe the bug**
The document store (vector) doesn't allow for selection from an existing document store even though the document store exists. You can see this in the screenshots.

**To Reproduce**
Add the document store vector node to your canvas and try to connect it to an existing document store.

**Expected behavior**
Should allow for the selection any existing document store.

**Screenshots**
Attached.

**Flow**
If applicable, add exported flow in order to help replicating the problem.

![Screenshot 2024-10-11 12 57 47](https://github.com/user-attachments/assets/85addd7e-215a-4052-ac55-0835d6eb9461)
[Flowise Documents WIP Chatflow.json](https://github.com/user-attachments/files/17342284/Flowise.Documents.WIP.Chatflow.json)

**Comment by mapachekurt** [comment]
I should also mention that I'm using the flowwise cloud version

**Comment by HenryHengZJ** [comment]
To use it, first you have to perform an upsert first: 
![image](https://github.com/user-attachments/assets/22d0e613-c18d-43a0-a5a6-69e175cc83ce)
