### ISSUE TITLE
[FEATURE]Can we add agent tool support for xinference besides Ollama

### ISSUE THREAD

**Issue by SairoUltraman** [FlowiseAI/Flowise#3345]
When using the xinference deployed model for inference, I am unable to use the agent tool through chatlocalisai and will receive an error message of 400.

10.19.193.218:30003 is the API address for xinference, and simple chat is available.

![b91eb5208381ebb357f6896447e1c58c](https://github.com/user-attachments/assets/2fdc0d6e-41cf-442d-892a-901580dc2ad5)

![e2c7856a81878f16a9f565ea2cc06e47](https://github.com/user-attachments/assets/f1965f33-9fc5-4d00-88fd-52d51d373c3d)

But when using the agent tool, it cannot be used.Like this：

![e52bf89b5e4ea98f911ec379fad5c07b](https://github.com/user-attachments/assets/266a697a-2456-4cc5-91ac-977fc18b40b0)

Please help me take a look at this issue, I suspect it is caused by the deployment of LLM using xinference

**Comment by HenryHengZJ** [comment]
Only certain Mistral models are capable of function calling: https://docs.mistral.ai/capabilities/function_calling/#available-models

`instruct` is not one of them
