### ISSUE TITLE
[BUG] Unable to receive answer in chainlit frontend

### ISSUE THREAD

**Issue by davidezari** [FlowiseAI/Flowise#3349]
**Describe the bug**
Starting from this https://github.com/HenryHengZJ/flowise-streamlit I created a new chainlit version with Claude help.
Was working without sessionid management, now no answer is shown.
Not sure how to manage this with flowise.

**To Reproduce**

1. copy files (see below zip files)
2. install dependencies
3. update .env file with APP_URL and FLOW_ID
4. launch app using "chainlit run chainlit_app.py --port 8501"
5. try to ask anything

**Expected behavior**
Receive an answer.

**Screenshots**
![image](https://github.com/user-attachments/assets/5d65fb67-28e7-438f-bdbf-3ca10d316754)
![image](https://github.com/user-attachments/assets/955dad08-8bef-42ea-aa25-d59a12619669)

**Flow**
[Chainlit test Chatflow.json](https://github.com/user-attachments/files/17357009/Chainlit.test.Chatflow.json)

**Setup**

-   Installation: npx flowise start
-   Flowise Version: 2.1.1
-   OS: Linux
-   Browser Firefox

**Additional context**
[chainlit_app.zip](https://github.com/user-attachments/files/17357017/chainlit_app.zip)

**Comment by davidezari** [comment]
This release seems to work, even if I need to test his stability during time
[chainlit_app_unique.zip](https://github.com/user-attachments/files/17430131/chainlit_app_unique.zip)

**Comment by HenryHengZJ** [comment]
Thanks for figuring out the correct release, by right what works on streamlit should works on other similar apps as well, we are using the standard Server Side Event (same as OpenAI)
