### ISSUE TITLE
[BUG] Failed to npm update

### ISSUE THREAD

**Issue by ZhuPeng1314** [FlowiseAI/Flowise#335]
**Describe the bug**
Failed to npm update

**To Reproduce**
Encountering version conflicts when using npm update.

% npm update                         
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: flowise-ui@1.2.11
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from flowise-ui@1.2.11
npm ERR!   packages/ui
npm ERR!     flowise-ui@1.2.11
npm ERR!     node_modules/flowise-ui
npm ERR!       workspace packages/ui from the root project
npm ERR!       1 more (flowise)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 0.14.0 < 18.0.0" from react-device-detect@1.17.0
npm ERR! node_modules/react-device-detect
npm ERR!   react-device-detect@"^1.17.0" from flowise-ui@1.2.11
npm ERR!   packages/ui
npm ERR!     flowise-ui@1.2.11
npm ERR!     node_modules/flowise-ui
npm ERR!       workspace packages/ui from the root project
npm ERR!       1 more (flowise)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 

**Setup**
-   Flowise Version : main branch or 1.2.12
-   OS: macOS

**Comment by govind-kumarr** [comment]
@ZhuPeng1314  let me check. i will get back to you

**Comment by HenryHengZJ** [comment]
I use `npm install -g flowise` everytime to automatically reinstall the latest version
