### ISSUE TITLE
[BUG] Rate Limiting settings in Chatflow Configuration not persisting

### ISSUE THREAD

**Issue by mattli001** [FlowiseAI/Flowise#3373]
**Describe the bug**
The Rate Limiting settings in Chatflow Configuration are not being saved correctly. After configuring and saving the Rate Limiting settings, switching to another tab and then returning to the Rate Limiting tab shows that the settings have not been retained.

**To Reproduce**
1. Go to 'Chatflow Configuration'
2. Click on 'Rate Limiting' tab
3. Enable Rate Limiting and configure settings
4. Click 'Save' button
5. Switch to another tab in Chatflow Configuration
6. Return to the 'Rate Limiting' tab
7. Observe that the settings are not retained and Rate Limiting is shown as Disabled

**Expected behavior**
After saving the Rate Limiting settings and returning to the tab, the previously configured settings should be displayed and Rate Limiting should remain Enabled.

**Screenshots**

https://github.com/user-attachments/assets/ae847101-dfde-4107-8a91-0b84e5f7f123

**Setup**
- Installation: Docker
- Flowise Version: 2.1.2
- OS: Ubuntu 22.04
- Browser: Chrome

**Comment by HenryHengZJ** [comment]
thanks! we have a PR fixed here: https://github.com/FlowiseAI/Flowise/pull/3311
will be pushing to new release!

**Comment by mattleei** [comment]
Thank you for your response. However, I noticed that PR #3311 (merged on Oct 5) is already included in [Flowise 2.1.2](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.1.2) (released on Oct 10), which is the version where I'm experiencing this issue. 

Could you help verify if the fix in PR #3311 fully addresses the Rate Limiting persistence problem? 
I'm still observing the following behavior in version 2.1.2:

1. Rate Limiting settings are not persisting after:
   * Configuring and saving the settings
   * Switching to another configuration tab
   * Returning to the Rate Limiting tab

2. Reproduction environment:
   * Flowise Version: 2.1.2 (Docker)
   * OS: Ubuntu 22.04
   * Browser: Chrome

Timeline reference:
* PR #3311 was merged on October 5, 2023
* Flowise v2.1.2 was released on October 10, 2023

Let me know if you need any additional information to help investigate this issue.
Thank you for your time and assistance.

**Comment by mattli001** [comment]
Thank you for your response. However, I noticed that PR #3311 (merged on Oct 5) is already included in [Flowise 2.1.2](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.1.2) (released on Oct 10), which is the version where I'm experiencing this issue. 

Could you help verify if the fix in PR #3311 fully addresses the Rate Limiting persistence problem? 
I'm still observing the following behavior in version 2.1.2:

1. Rate Limiting settings are not persisting after:
   * Configuring and saving the settings
   * Switching to another configuration tab
   * Returning to the Rate Limiting tab

2. Reproduction environment:
   * Flowise Version: 2.1.2 (Docker)
   * OS: Ubuntu 22.04
   * Browser: Chrome

Timeline reference:
* PR #3311 was merged on October 5, 2023
* Flowise v2.1.2 was released on October 10, 2023

Let me know if you need any additional information to help investigate this issue.
Thank you for your time and assistance.
