### ISSUE TITLE
Document Store (Vector) - Store options not available

### ISSUE THREAD

**Issue by rrubio** [FlowiseAI/Flowise#3375]
**Version**
2.1.2@latest

**Describe the bug**
Whe i select the new  "Document Store (Vector)", my existing Documents aren't available. However, they are available under the "Document Store" node, from the dropdown box.

**To Reproduce**

1. Got to "Vector Stores"
2. Click on 'Document Store (Vector)'
3. Drag node to canvas
4. Click on dropdown box and you'll notice that no list is available

**Expected behavior**
See a list of available document stores.

**Screenshots**
![image](https://github.com/user-attachments/assets/2915e050-4540-432a-80f5-53af3c90bce3)

**Comment by rrubio** [comment]
Looks like I miss-understood how it's meant to work. I've added "In-Memory Vector Store" and the list is now available. 

![image](https://github.com/user-attachments/assets/ed8c4db4-a5c4-49cf-b240-9ae020a1f4ba)

**Comment by HenryHengZJ** [comment]
Unfortunately at this stage, you have to use other vector store. We missed that one, should've disabled in memory store for document store
