### ISSUE TITLE
[BUG] Yarn install gives "Duplicate workspace name flowise" error

### ISSUE THREAD

**Issue by emrahtoy** [FlowiseAI/Flowise#338]
**Describe the bug**
Yarn 3.5.1 under ubuntu 20.04

**To Reproduce**

1. Install yarn as it defined at https://yarnpkg.com/
2. clone the repository
3. do install "yarn install"
4. See error "Error: Duplicate workspace name flowise"

**Expected behavior**
It should install all the dependencies without an issue

**Setup**
-   Installation : "yarn install"
-   Flowise Version [e.g. 1.2.12]
-   OS: [e.g. WSL2 - Ubuntu 20.04]
-   Node v18.15.0

**Additional context**
As far as I can see package also has the same name with the main projects name ( flowise exist in package.json )

**FIX**
Changing main projects name to flowiseMain and adding it into workspaces solves installation problem but then we face with another problem "ERROR Unable to find Go binary." turbo suggest update at this point. I will open another issue regarding this error.

**Comment by emrahtoy** [comment]
Note : Upgrading turbo does solve go binary problem but compiles with so many errors. It does not work after all.

**Comment by emrahtoy** [comment]
Progress: I have updated and added some missing libraries and type definitions. Now it builds component and server without an issue but when it comes to the UI it is such a dependency hell...

I share package.json files I end up with, I really would appreciate help on solving peer dependency problems. After that I look forward to deal with the other issues and bugs..

root package.json
`{
    "name": "flowiseMain",
    "version": "1.2.12",
    "private": true,
    "homepage": "https://flowiseai.com",
    "workspaces": [
        "packages/*",
        "flowise",
        "ui",
        "components",
        "flowiseMain"
    ],
    "scripts": {
        "build": "turbo run build",
        "build-force": "turbo run build --force",
        "dev": "turbo run dev --parallel",
        "start": "run-script-os",
        "start:windows": "cd packages/server/bin && run start",
        "start:default": "cd packages/server/bin && ./run start",
        "clean": "npm exec -ws -- rimraf dist build",
        "format": "prettier --write \"**/*.{ts,tsx,md}\"",
        "test": "turbo run test",
        "lint": "eslint \"**/*.{js,jsx,ts,tsx,json,md}\"",
        "lint-fix": "yarn lint --fix",
        "quick": "pretty-quick --staged",
        "postinstall": "husky install"
    },
    "lint-staged": {
        "*.{js,jsx,ts,tsx,json,md}": "eslint --fix"
    },
    "devDependencies": {
        "@babel/preset-env": "^7.19.4",
        "@babel/preset-typescript": "7.18.6",
        "@types/express": "^4.17.13",
        "@typescript-eslint/parser": "^5.59.11",
        "@typescript-eslint/typescript-estree": "^5.39.0",
        "eslint": "^8.24.0",
        "eslint-config-prettier": "^8.3.0",
        "eslint-config-react-app": "^7.0.1",
        "eslint-plugin-jsx-a11y": "^6.6.1",
        "eslint-plugin-markdown": "^3.0.0",
        "eslint-plugin-prettier": "^3.4.0",
        "eslint-plugin-react": "^7.26.1",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-unused-imports": "^2.0.0",
        "husky": "^8.0.1",
        "lint-staged": "^13.0.3",
        "prettier": "^2.7.1",
        "pretty-quick": "^3.1.3",
        "rimraf": "^3.0.2",
        "run-script-os": "^1.1.6",
        "turbo": "^1.10.3",
        "typescript": "^4.8.4"
    },
    "engines": {
        "node": ">=18.15.0"
    }
}` 

component package.json
`{
    "name": "flowise-components",
    "version": "1.2.13",
    "description": "Flowiseai Components",
    "main": "dist/src/index",
    "types": "dist/src/index.d.ts",
    "scripts": {
        "build": "tsc && gulp",
        "dev": "tsc --watch"
    },
    "keywords": [],
    "homepage": "https://flowiseai.com",
    "author": {
        "name": "Henry Heng",
        "email": "henryheng@flowiseai.com"
    },
    "license": "SEE LICENSE IN LICENSE.md",
    "dependencies": {
        "@dqbd/tiktoken": "^1.0.7",
        "@getzep/zep-js": "^0.3.1",
        "@huggingface/inference": "1",
        "@pinecone-database/pinecone": "^0.0.12",
        "@supabase/supabase-js": "^2.21.0",
        "@types/js-yaml": "^4.0.5",
        "axios": "^0.27.2",
        "cheerio": "^1.0.0-rc.12",
        "chromadb": "^1.4.2",
        "cohere-ai": "^6.2.0",
        "d3-dsv": "2",
        "dotenv": "^16.0.0",
        "express": "^4.17.3",
        "faiss-node": "^0.2.1",
        "form-data": "^4.0.0",
        "graphql": "^16.6.0",
        "html-to-text": "^9.0.5",
        "langchain": "^0.0.94",
        "linkifyjs": "^4.1.1",
        "lodash": "^4.17.21",
        "mammoth": "^1.5.1",
        "moment": "^2.29.3",
        "node-fetch": "^2.6.11",
        "pdf-parse": "^1.1.1",
        "puppeteer": "^20.7.1",
        "socker.io": "^0.0.0-alpha-beta",
        "socket.io": "^4.6.2",
        "typeorm": "^0.3.16",
        "weaviate-ts-client": "^1.1.0",
        "ws": "^8.9.0"
    },
    "devDependencies": {
        "@types/gulp": "4.0.9",
        "@types/lodash": "^4.14.195",
        "@types/node-fetch": "2.6.2",
        "@types/socket.io": "^3.0.2",
        "@types/ws": "^8.5.3",
        "gulp": "^4.0.2",
        "typescript": "^4.8.4"
    }
}`

server package.json
`{
    "name": "flowise",
    "version": "1.2.12",
    "description": "Flowiseai Server",
    "main": "dist/index",
    "types": "dist/index.d.ts",
    "bin": "./bin/run",
    "files": [
        "bin",
        "marketplaces",
        "dist",
        "npm-shrinkwrap.json",
        "oclif.manifest.json",
        "oauth2.html"
    ],
    "oclif": {
        "bin": "flowise",
        "commands": "./dist/commands"
    },
    "scripts": {
        "build": "tsc",
        "start": "run-script-os",
        "start:windows": "cd bin && run start",
        "start:default": "cd bin && ./run start",
        "dev": "concurrently \"yarn watch\" \"nodemon\"",
        "oclif-dev": "run-script-os",
        "oclif-dev:windows": "cd bin && dev start",
        "oclif-dev:default": "cd bin && ./dev start",
        "postpack": "shx rm -f oclif.manifest.json",
        "prepack": "yarn build && oclif manifest && oclif readme",
        "typeorm": "typeorm-ts-node-commonjs",
        "watch": "tsc --watch",
        "version": "oclif readme && git add README.md"
    },
    "keywords": [],
    "homepage": "https://flowiseai.com",
    "author": {
        "name": "Henry Heng",
        "email": "henryheng@flowiseai.com"
    },
    "engines": {
        "node": ">=18.15.0"
    },
    "license": "SEE LICENSE IN LICENSE.md",
    "dependencies": {
        "@oclif/core": "^1.13.10",
        "axios": "^0.27.2",
        "cors": "^2.8.5",
        "dotenv": "^16.0.0",
        "express": "^4.17.3",
        "express-basic-auth": "^1.2.1",
        "flowise-components": "*",
        "flowise-ui": "*",
        "lodash": "^4.17.21",
        "moment": "^2.29.4",
        "moment-timezone": "^0.5.34",
        "multer": "^1.4.5-lts.1",
        "reflect-metadata": "^0.1.13",
        "socket.io": "^4.6.1",
        "sqlite3": "^5.1.6",
        "typeorm": "^0.3.6"
    },
    "devDependencies": {
        "@types/cors": "^2.8.12",
        "@types/express": "^4.17.17",
        "@types/lodash": "^4.14.195",
        "@types/multer": "^1.4.7",
        "concurrently": "^7.1.0",
        "nodemon": "^2.0.15",
        "oclif": "^3",
        "run-script-os": "^1.1.6",
        "shx": "^0.3.3",
        "ts-node": "^10.7.0",
        "typescript": "^4.8.4"
    }
}`

UI package.json
`{
    "name": "flowise-ui",
    "version": "1.2.11",
    "license": "SEE LICENSE IN LICENSE.md",
    "homepage": "https://flowiseai.com",
    "author": {
        "name": "HenryHeng",
        "email": "henryheng@flowiseai.com"
    },
    "dependencies": {
        "@emotion/cache": "^11.4.0",
        "@emotion/react": "^11.10.6",
        "@emotion/styled": "^11.10.6",
        "@mui/icons-material": "^5.0.3",
        "@mui/material": "^5.11.12",
        "@tabler/icons": "^1.39.1",
        "axios": "^1.4.0",
        "clsx": "^1.1.1",
        "formik": "^2.2.6",
        "framer-motion": "^4.1.13",
        "history": "^5.0.0",
        "html-react-parser": "^3.0.4",
        "lodash": "^4.17.21",
        "moment": "^2.29.3",
        "notistack": "^2.0.4",
        "prismjs": "^1.28.0",
        "prop-types": "^15.7.2",
        "react": "^18.2.0",
        "react-code-blocks": "^0.0.9-0",
        "react-datepicker": "^4.8.0",
        "react-device-detect": "^2.2.3",
        "react-dom": "^18.2.0",
        "react-is": "^18.2.0",
        "react-json-view": "^1.21.3",
        "react-markdown": "^8.0.6",
        "react-perfect-scrollbar": "^1.5.8",
        "react-redux": "^8.0.5",
        "react-router": "~6.3.0",
        "react-router-dom": "~6.3.0",
        "react-simple-code-editor": "^0.11.2",
        "react-syntax-highlighter": "^15.5.0",
        "reactflow": "^11.5.6",
        "redux": "^4.0.5",
        "rehype-mathjax": "^4.0.2",
        "remark-gfm": "^3.0.1",
        "remark-math": "^5.1.1",
        "socket.io-client": "^4.6.1",
        "styled-components": "^6.0.0-rc.3",
        "yup": "^0.32.9"
    },
    "scripts": {
        "start": "react-scripts start",
        "dev": "react-scripts start",
        "build": "react-scripts build",
        "test": "react-scripts test",
        "eject": "react-scripts eject"
    },
    "babel": {
        "presets": [
            "@babel/preset-react"
        ]
    },
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "devDependencies": {
        "@babel/eslint-parser": "^7.15.8",
        "@testing-library/jest-dom": "^5.11.10",
        "@testing-library/react": "^14.0.0",
        "@testing-library/user-event": "^12.8.3",
        "pretty-quick": "^3.1.3",
        "react-scripts": "^5.0.1",
        "sass": "^1.63.4",
        "sass-loader": "^13.3.2",
        "typescript": "^4.8.4"
    }
}`

**Comment by emrahtoy** [comment]
Guys feeling a little lonely here :) is it only me having this issue?  If so I rather stop spending time on this.
@chungyau97 @HenryHengZJ

**Comment by HenryHengZJ** [comment]
looking into it

**Comment by emrahtoy** [comment]
I have been keep diggin with the help of .yarnrc.yml file to solve peerDependency errors yet it gets deeper as I dig :(

**Comment by HenryHengZJ** [comment]
do you have trouble installing using yarn v1? 
```
yarn set version 1.22.19
```

**Comment by emrahtoy** [comment]
Yarn has made some changes;

Added a line in to package.json
"packageManager": "yarn@1.22.19"

created .yarnrc.yml file and filled with this line;
yarnPath: .yarn/releases/yarn-1.22.19.cjs

created the directory as following: 
.yarn/releases 
and created this file :
yarn-1.22.19.cjs

all of those changes can be seen in git change list. Shall we push or make PR for these changes @HenryHengZJ  ?

**Comment by emrahtoy** [comment]
By the way MarketPlace and ApiKeys seems empty and the requests belong to these pages are giving 404
![image](https://github.com/FlowiseAI/Flowise/assets/4387637/a8bbb364-bee0-4095-b0a7-dda89cf88dbc)

**Comment by emrahtoy** [comment]
@HenryHengZJ also see #349

**Comment by HenryHengZJ** [comment]
@emrahtoy we can leave the changes out as people can be using different yarn version.

looks like the apps doesn't start correctly, here's what I would do:

1.) remove the project
2.) cd to your home directory and make sure yarn is v1.22.19
3.) git clone and cd to Flowise
4.) before installing, make sure yarn is v1.22.19
5.) yarn install
6.) yarn build-force
7.) yarn start

**Comment by emrahtoy** [comment]
I have done the almost same
1. deleted the folder and cloned the git repository from the start.
2. Set the yarn version v1.22.19
3. yarn install
4. yarn dev

#349 and #353 still occur.

I think it would be nice to see a warning in the documentation about the yarn version as mine were not compatible.

**Comment by SidSyrus** [comment]
+1 to the issue. Facing same with Yarn on v3.3.1

**Comment by HenryHengZJ** [comment]
Updated [README](https://github.com/FlowiseAI/Flowise/blob/main/README.md#prerequisite) for compatible yarn version

Although its not ideal to keep it at yarn v1, we have plan to migrate to pnpm in future

**Comment by drobnikj** [comment]
+1 

If you are using Corepack as described in [yarn doc](https://yarnpkg.com/getting-started/install)
You need to install v1 version of yarn to make it work:

`corepack prepare yarn@v1.22.19 --activate`

**Comment by HenryHengZJ** [comment]
closing this as it should be resolved with `pnpm` PR https://github.com/FlowiseAI/Flowise/pull/1272
