### ISSUE TITLE
[BUG] Postgres DB + Document Store 

### ISSUE THREAD

**Issue by LeandroVidal555** [FlowiseAI/Flowise#3384]
**Describe the bug**
Getting imprecise error message with status 500 after trying to upsert vectors into Postgres. Happens with any kind of file and chunk content. Happens even if I only leave 1 chunk with simple alphanumeric text. The same DB works perfectly when upserting from a Chatflow without a record manager. If a record manager is introduced in the Chatflow, another error shows up, but let's concentrate on the Document Store's error.

**To Reproduce**
1. Go to "Document Stores"
2. Create a Document Store
3. Create and setup an S3 directory loader
4. Preview chunks and process
5. Create an "Upsert Config" with:
- Embeddings: OpenAI Embeddings
- Vector Store: Postgres
- Record Manager: Postgres Record Manager
6. Click on "Upsert"
7. See error:
> Status: 500
> Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - Error: Error inserting: [chunk 2 text contents]

No helpful messages in server logs, as far as I have seen.

**Expected behavior**
Upsertion is performed without any errors after click the upsert button in document store menu

**Screenshots**
![image](https://github.com/user-attachments/assets/e43cc35d-5479-4ac6-b29b-7528f70fcdc8) 
![image](https://github.com/user-attachments/assets/6b02da37-0680-4ac2-a5c3-52664263241a)

**Setup**
-   Installation docker
-   Flowise Version 2.1.2
-   OS: Linux
-   Browser chrome

**Additional context**
Flowise is running in AWS on an EC2 instance.
Postgres is deployed as RDS database.

**Comment by LeandroVidal555** [comment]
Seems like the bug is related to Flowise not creating the schema that the Record Manager needs in Postgres table.
- Missing columns "updated_at", "key", "namespace", "group_id"
- Missing unique constraints for "key" and "namespace"

Running this got it to work correctly:
```
ALTER TABLE salesforce_flowise_contacts
ADD COLUMN updated_at text;

ALTER TABLE salesforce_flowise_contacts
ADD COLUMN key text;

ALTER TABLE salesforce_flowise_contacts
ADD COLUMN namespace text;

ALTER TABLE salesforce_flowise_contacts
ADD COLUMN group_id text;

ALTER TABLE salesforce_flowise_contacts
ADD CONSTRAINT unique_key_namespace UNIQUE (key, namespace);
```

**Comment by HenryHengZJ** [comment]
Thats strange, the columns should be created at [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/recordmanager/PostgresRecordManager/PostgresRecordManager.ts#L201)

**Comment by LeandroVidal555** [comment]
Thanks for your response @HenryHengZJ .

I think that there is some sort of mutual exclusion between Postgres and Postgres Record Manager columns creation.

I have just tried to create a table from scratch from Document Store (the one in my original post was created upon upsertion in a Chatflow WITH PostgresDB and WITHOUT Record Manager, sorry for the confusion) and got the error + in the DB itself I see only the Record Manager schema!

```
\d test_borrar
                        Table "public.test_borrar"
   Column   |       Type       | Collation | Nullable |      Default      
------------+------------------+-----------+----------+-------------------
 uuid       | uuid             |           | not null | gen_random_uuid()
 key        | text             |           | not null | 
 namespace  | text             |           | not null | 
 updated_at | double precision |           | not null | 
 group_id   | text             |           |          | 
Indexes:
    "test_borrar_pkey" PRIMARY KEY, btree (uuid)
    "test_borrar_key_namespace_key" UNIQUE CONSTRAINT, btree (key, namespace)
```

Missing: id, metadata, pagecontent, embedding

**Comment by LeandroVidal555** [comment]
What's more, once I get it to "work", the vector data and the record manager data seem to get inserted separately:

![image](https://github.com/user-attachments/assets/c4e1b53d-268d-4ee4-b8ce-b91a6bcff3e2)

Only 8 chunks are shown in the loader, yet I get 8 rows with vectors + 8 rows with the Record Manager stuff.

**Comment by HenryHengZJ** [comment]
yes, you have specify separate table names for those 2, they cannot be the same table name as seen from the screenshots.

**Comment by LeandroVidal555** [comment]
Ok, I would call myself satisfied then if the expected behaviour was that an error message popped up when the two tables names are equal. Be it on click of "Upsert" or "Save Config", or even while completing the form. It shouldn't let you go on.
