### ISSUE TITLE
[FEATURE] Add mysql, postgres support to agent memory 

### ISSUE THREAD

**Issue by takefy-dev** [FlowiseAI/Flowise#3393]
I don't know why this is not by default and why it's sqlite by default,  been 2 weeks still no support of mysql, postgres, redis ect. I'm running on a uge ecommerce website already got 2k2 session in 4 days, sqlite is slow it makes crash flowise makes it unsuable...

**Comment by kumar-asista** [comment]
@HenryHengZJ 

how to set limit for Agent Memory node?

i can limit is used while select chat messages, hot to set this parameter?

@takefy-dev do you found any workaround?

**Comment by HenryHengZJ** [comment]
PR opened: https://github.com/FlowiseAI/Flowise/pull/3495

@kumar-asista you can't set limit for agent memory for now
