### ISSUE TITLE
[BUG] SSO implementation

### ISSUE THREAD

**Issue by sanknoorsachin** [FlowiseAI/Flowise#3400]
Hi we want to implement SSO on the flowise instance that we have hosted . As I don't see any documentation regarding the same can you please guide us on how to proceed with this.

@HenryHengZJ

**Comment by HenryHengZJ** [comment]
Hi @sanknoorsachin , SSO will be available as part of our enterprise offering, suggest get in touch with hello@flowiseai.com for more info
