### ISSUE TITLE
[FEATURE]Using Document Store and file loader API to upload, process and upsert files.

### ISSUE THREAD

**Issue by quzhixue-Kimi** [FlowiseAI/Flowise#3407]
Hi there,

I have checked the API document at https://docs.flowiseai.com/api-reference/document-store, but I couldn't find any endpoint to upload a file using the file loader or PDF loader via the API. Currently, we can upload files via the UI.

![image](https://github.com/user-attachments/assets/a00ef566-6e40-4a7f-8000-994e685f20d0)

How can I use this feature via the API? It seems there are no parameters in the request body for file objects in the /document-store/loader/preview and /document-store/loader/process APIs.

We cannot create multiple users for separate document stores and file uploads. Therefore, we want to create a UI for multiple users to upload files to one public folder on a desired server, and we need a method to load these files and call the document store process and upsert APIs.

I am currently trying the API loader, but there is limited documentation available. 
Any suggestions or feedback would be appreciated.

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
I use the API loader to resolve this issue.

**Comment by santhosh-hu-tfs** [comment]
> I use the API loader to resolve this issue.

Hi @quzhixue-Kimi , Can you please share the details on how you used API loader to load the document via API?

**Comment by quzhixue-Kimi** [comment]
Hi, @santhosh-hu-tfs 

It requires a bit of skill and is somewhat convoluted.

First, there is an HTML page for users to upload files, which saves the files on the server side. This HTML page will invoke the backend upload functionality.

The backend code also has another function that reads the recently uploaded files, which is implemented as a RESTful API. When configuring in Flowise, this RESTful API is specified. The interface for the Flowise document store uses /api/v1/document-store/loader/process to process chunks, which will automatically trigger the backend code you wrote to read the content of the uploaded files.

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
Hi @santhosh-hu-tfs 

Here is some code snippet as below, my API just returned the content of what the used uploaded and, do some special processes of PDF file.

async def read_file_content(file_path: str, filename: str) -> str:
    try:
        ext = os.path.splitext(filename)[1].lower()

        if ext in ['.txt', '.md', '.json']:
            async with aiofiles.open(file_path, 'r', encoding='utf-8') as file:
                return await file.read()
        elif ext in ['.pdf']:
            num_pages = get_page_count(file_path)
            pages = list(range(1, num_pages + 1))
            tables = get_tables(file_path, pages=pages)
            page_texts = get_page_text(file_path, pages=pages, tables=tables)
            markdown_content = [] 
            for i, page_tables in enumerate(tables):
                current_page = i + 1
                text_content = page_texts.get(current_page, "").strip()
                markdown_content.append(f"### Page {current_page} Text\n{text_content}\n")

                for table in page_tables:
                    data_list_dict = table.to_dict(orient='records')
                    markdown_data = table.to_markdown(index=False)
                    markdown_content.append(f"#### Table on Page {current_page}\n{markdown_data}\n")
                        output_md_file = os.path.splitext(file_path)[0] + ".md"
            with open(output_md_file, "w", encoding="utf-8") as md_file:
                md_file.write("\n".join(markdown_content))
            logging.info(f"Markdown content has been saved to {output_md_file}")
            return markdown_content
        elif ext in ['.docx']:
            doc = Document(file_path)
            text = '\n'.join([para.text for para in doc.paragraphs])
            return text


BR
Kimi

**Comment by workwise1988** [comment]
Thank you @quzhixue-Kimi . I implemented the same concept in a Spring Boot and it is functioning as expected. 

@HenryHengZJ, @quzhixue-Kimi , Please inform me if you discover any alternative methods for upserting the files into Pinecone/Postgres repositories using only Flowise APIs. Appreciate your input on this
