### ISSUE TITLE
[FEATURE] Programmatically edit a flowise flow

### ISSUE THREAD

**Issue by mannyyang** [FlowiseAI/Flowise#3408]
**Describe the feature you'd like**
Is there a way or an API to directly edit a flowise flow? It'd be cool if you could build a flowise chat to edit the JSON object of a flowise flow.

**Comment by raduhi** [comment]
That would be awesome

**Comment by HenryHengZJ** [comment]
You can update the `flowData` of the chatflow: https://docs.flowiseai.com/api-reference/chatflows#chatflows-id-1

But you need to provide in the format as the exported chatflow JSON

**Comment by mannyyang** [comment]
> You can update the `flowData` of the chatflow: https://docs.flowiseai.com/api-reference/chatflows#chatflows-id-1
> 
> But you need to provide in the format as the exported chatflow JSON

Is there an openAPI format available (or something similar)? So we can use tools like the openAPI tool :)

**Comment by HenryHengZJ** [comment]
unfortunately not, flowise has its own JSON structure in order to work with all other integrations
