### ISSUE TITLE
[BUG] Full File Upload not working if file name has unusual symbols

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#3416]
**Describe the bug**
I can't use "Enable Full File Upload" when the file name includes e.g. 'ß', special letter in the German language.
It's not inserted in the context window.

**To Reproduce**
I followed the video of the discord announcement channel: https://discord.com/channels/1087698854775881778/1096577675163865200/1299036797908553820

**Expected behavior**
The LLM can see the uploaded file and work with it

**Comment by boble23** [comment]
same problem with æøå

**Comment by opp1opp1** [comment]
i guess traditional chinese has same problem

**Comment by HenryHengZJ** [comment]
Fixed now!
