### ISSUE TITLE
Document-store -> vectorstore -> insert -> Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - TypeError: fetch failed

### ISSUE THREAD

**Issue by dev3py** [FlowiseAI/Flowise#3417]
**Describe the bug**
While upserting a new Document Store getting a 500 error

**To Reproduce**

1. Adding an ollama embeddings nomic-embed-text:latest
2. Adding a Faiss as a Vector Store
3. Upsert

**Expected behavior**
The success upsert message is expected, but the 500 error is coming
Status: 500
Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - TypeError: fetch failed

**Screenshots**
![image](https://github.com/user-attachments/assets/f6582abd-5dc8-4813-a21f-df75baa08103)
![image](https://github.com/user-attachments/assets/54c97b98-0277-4d14-a5fd-bd7818220024)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-  Docker running locally 
-   Flowise Versionv2.1.3
-   OS: windows
-   Browser: chrome,

**Comment by AlamokCR** [comment]
I have the exact issue,  it doesn't mater if I use docker or install all manually.

**Comment by HenryHengZJ** [comment]
is your FAISS dimension compatible with nomic embed text embedding dimension?

**Comment by shighcloud-ea** [comment]
same issue for me

Status: 500
Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - TypeError: fetch failed

**Comment by suresh-jbt** [comment]
@shighcloud-ea @HenryHengZJ @AlamokCR @dev3py I found the solution and its worked 
In the Ollama node configuration, use `http://host.docker.internal:11434` instead of `http://localhost:11434`.

Since Ollama is installed on the host machine and not within Docker, Docker containers cannot connect to the host’s services via `localhost`. By using `host.docker.internal`, you enable Docker to communicate with services on the host.

**Comment by OtisMacOS** [comment]
> http://host.docker.internal:11434

Man you are a life saver!!!
May the force be with you everyday everyday!!!

**Comment by OtisMacOS** [comment]
> [@shighcloud-ea](https://github.com/shighcloud-ea) [@HenryHengZJ](https://github.com/HenryHengZJ) [@AlamokCR](https://github.com/AlamokCR) [@dev3py](https://github.com/dev3py) I found the solution and its worked In the Ollama node configuration, use `http://host.docker.internal:11434` instead of `http://localhost:11434`.
> 
> Since Ollama is installed on the host machine and not within Docker, Docker containers cannot connect to the host’s services via `localhost`. By using `host.docker.internal`, you enable Docker to communicate with services on the host.

Man you are a life saver!!!
May the force be with you everyday everyday!!!

**Comment by akirsila** [comment]
I got same problem with openai. I have plus account. 

Error: predictionsServices.buildChatflow - 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

Troubleshooting URL: https://js.langchain.com/docs/troubleshooting/errors/MODEL_RATE_LIMIT/

**Comment by ajshan** [comment]
Is it resolved? What is the work around?

**Error as soon as I am cliking upsert:**
<img width="1130" height="709" alt="Image" src="https://github.com/user-attachments/assets/95123c93-f09b-436b-9e57-94883f459070" />

**Flowise Self Hosted:**

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/5f5a2f6f-94a2-4a43-bbab-f0a3f64e9c43" />
