### ISSUE TITLE
How use your API endpoints?

### ISSUE THREAD

**Issue by ScratchyFo** [FlowiseAI/Flowise#3425]
Hi. 
How can I use my API, which is located on a local or external server, for example?
I saw an example with the connection "POST / (GET) API CHAIN" + Chaintool.
As a result: I will not receive the expected request and response, and LLM (Grog Llama/Mistral) invented the answer.

The task is to ensure that the agent can access the database, take the necessary data and go with it to my API server (for example, VLM), process it and return the response to the agent.

**Comment by HenryHengZJ** [comment]
this might be useful: https://docs.flowiseai.com/use-cases/interacting-with-api
