### ISSUE TITLE
[BUG] Streaming chat for ChatOpenAI Custom

### ISSUE THREAD

**Issue by newfarmer** [FlowiseAI/Flowise#3427]
**Describe the bug**
Streaming chat does not “really  work” on ChatOpenAI Custom

**To Reproduce**
![image](https://github.com/user-attachments/assets/76ab71e8-5ff0-4624-82db-d8ee5d0f8868)

If HTTPS is used, a piece of text is returned at a time, not a word by word.
First return：
![image](https://github.com/user-attachments/assets/12c39a98-1ec9-4073-9258-223db4024d67)
Second return：
![image](https://github.com/user-attachments/assets/5dd11999-58dc-47b3-9094-6ab04bba9c8b)

If http is used, the return is word by word.

**Expected behavior**
the return is word by word.

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

https://github.com/FlowiseAI/Flowise/issues/1081

**Comment by fbchan** [comment]
@HenryHengZJ is the right syntax should be stream=true or streaming=true and vice versa for false? I noticed the flowise debug show stream=true but the settings uses streaming.
