### ISSUE TITLE
[BUG] faiss-node can't find

### ISSUE THREAD

**Issue by skyrain888** [FlowiseAI/Flowise#343]
my environment ： mac m1
run docker build --no-cache -t flowise . 

------
#12 179.7 prebuild-install info begin Prebuild-install version 7.1.1
#12 179.7 prebuild-install info looking for local prebuild @ prebuilds/faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#12 179.7 prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/c598fd-faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#12 179.7 prebuild-install http request GET https://github.com/ewfian/faiss-node/releases/download/v0.2.1/faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#12 179.7 prebuild-install http 404 https://github.com/ewfian/faiss-node/releases/download/v0.2.1/faiss-node-v0.2.1-napi-v8-linuxmusl-arm64.tar.gz
#12 179.7 prebuild-install warn install No prebuilt binaries found (target=8 runtime=napi arch=arm64 libc=musl platform=linux)
#12 179.7
#12 179.7 > faiss-node@0.2.1 build
#12 179.7 > cmake-js compile
#12 179.7
#12 179.7 sh: cmake-js: not found
#12 179.7 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
executor failed running [/bin/sh -c yarn install]: exit code: 127

**Comment by HenryHengZJ** [comment]
thanks for the bug! its in work - https://github.com/ewfian/faiss-node/issues/17

**Comment by HenryHengZJ** [comment]
its now fixed in v1.2.14
