### ISSUE TITLE
[FEATURE]How to upload multiple files to set up a local knowledge base with Flowise

### ISSUE THREAD

**Issue by holylong** [FlowiseAI/Flowise#3433]
There's an issue: suppose I have this RAG (Retrieval-Augmented Generation) system for 100 users, where each user can upload their own files. FAISS acts like a library where everyone can look up the information they need. Is there an API to upload files individually? Does every file upload require an upsert operation? Does this upsert operation re-vectorize all the files? Or does it only vectorize the newly uploaded ones? If all files are re-vectorized, wouldn't that consume a lot of resources, especially if the number of files is large?
![1730370548258](https://github.com/user-attachments/assets/4116a229-0d4d-4228-ad41-6689b2190522)

**Comment by HenryHengZJ** [comment]
We have 2 file uploads type: https://docs.flowiseai.com/using-flowise/uploads#files

Using FAISS, you can only do full upload, not the vectorize RAG upload
