### ISSUE TITLE
[FEATURE]Is it possible to add the FrontEnd tag to all front-end issues? I really want to join FlowiseAI

### ISSUE THREAD

**Issue by LofiSu** [FlowiseAI/Flowise#3437]
In addition to Discord, is there a communication group, such as qq, WeChat and the like?

**Comment by HenryHengZJ** [comment]
thank you! we'll tag them soon!

**Comment by HenryHengZJ** [comment]
Added the tags! There arent many of them, but if you see some UI bugs/small improvement, feel free to open PR!
