### ISSUE TITLE
[BUG] API chatmessages filter by chatId does not work

### ISSUE THREAD

**Issue by takefy-dev** [FlowiseAI/Flowise#3447]
**Describe the bug**
I want to filter by chatId on the chatmessages endpoint like it is mentionned in the api doc but it does not work it always return empty array with the query param ?chatId
**To Reproduce**
Filter by chat id on the chatmessages endpoint

**Expected behavior**
To return all chatmessages from the chat id
**Screenshots**
![image](https://github.com/user-attachments/assets/64de2ae4-4aad-4bb5-9393-e41c6a4a0834)

`GET /api/v1/chatmessage/51be1c61-0c8b-4f14-8c8e-191a639bad57?chatId=528345+954539a4-c5ed-4fc8-8be2-aa59f74af4fa`
![image](https://github.com/user-attachments/assets/9b5ea90f-8f73-4940-bf39-71c5d90ef150)

**Comment by HenryHengZJ** [comment]
Works fine: 
![image](https://github.com/user-attachments/assets/9b4139d3-cf4e-4ed9-b021-2317fa049237)

Could be the strange chatId format with the plus sign
