### ISSUE TITLE
[FEATURE] Document Loader for generic Git repositories

### ISSUE THREAD

**Issue by spoletum** [FlowiseAI/Flowise#3455]
**Describe the feature you'd like**
At present, Flowise supports Git document loading only from GitHub. It would be extremely convenient to be able to fetch documents from any Git repository.

**Additional context**
None

**Comment by HenryHengZJ** [comment]
What do you mean by generic git repository? Is the current github loader not able to fetch that? 
![image](https://github.com/user-attachments/assets/c3bdce89-b729-43ef-aa22-d0fbd121a9ca)

**Comment by forcewake** [comment]
Hi @HenryHengZJ 
I've just checked and faced in with the same issue:

```
Failed to preview chunks: Error: documentStoreServices.previewChunks - Error: documentStoreServices.splitIntoChunks - Invalid GitHub URL format.
```

![image](https://github.com/user-attachments/assets/c2898daa-c94d-498a-a61c-3a025a3b6d6f)

And based on my research - https://github.com/langchain-ai/langchainjs/blob/main/libs/langchain-community/src/document_loaders/web/github.ts#L226 there is now way to use it for generic git repositories.
