### ISSUE TITLE
How to stress test FlowiseAI?

### ISSUE THREAD

**Issue by valdecircompasso** [FlowiseAI/Flowise#3466]
Hello everyone! 
We are using FlowiseAI to support our GenAI application but as the application is getting more and more used, I would like to ask you some ways to stress test Flowise based on number of requests, number of flows, etc. 
Thanks!
--VC

**Comment by HenryHengZJ** [comment]
We provide this script - https://github.com/FlowiseAI/Flowise/blob/main/artillery-load-test.yml which allow user to use artillery for load testing
