### ISSUE TITLE
UI Turns White When Accessing Agents Chat and Marketplace in Flowise

### ISSUE THREAD

**Issue by Santiago30032** [FlowiseAI/Flowise#3478]
Describe the bug When using the Agents chat feature in Flowise, the interface window unexpectedly turns white. Additionally, error messages appear in the console. This issue is consistently reproducible across both macOS and Windows platforms. The same behavior occurs in the marketplace section, where the window also turns white, suggesting a potential UI rendering issue.

To Reproduce Steps to reproduce the behavior:

Go to the 'Agents' section in Flowise.
Click on 'Start Chat'.
Observe that the window turns blank and console logs display error messages.
Similarly, navigate to the 'Marketplace' section and witness the window turning white there as well.
Expected behavior I expected the chat window and marketplace to load normally, allowing for interaction without any interruptions or visual disruptions. The expected behavior is for the UI to remain stable and responsive, providing the necessary functionality without crashing or turning white.

Screenshots

![image](https://github.com/user-attachments/assets/d24bf18c-4f97-4a48-9c95-ac54a2c20ceb)
![image](https://github.com/user-attachments/assets/ee2a48c2-2c7a-4924-a40d-ff6be6e51849)

Setup

Installation methods: npx flowise start on macOS and Windows
Flowise Version: flowise/1.6.0 win32-x64 node-v18.20.4
OS: macOS, Windows
Browser: Chrome 
Additional context The issue persists regardless of the Node.js version used, with tests conducted on Node v22 and v18. This problem seems related to UI rendering processes as it affects multiple sections of the application across different operating systems and installation setups. Further investigation into console errors might provide more insights into the potential causes of these rendering issues.

**Comment by HenryHengZJ** [comment]
This is fixed in the latest version `v2.1.3`. If issue still persists, feel free to re-open the issue

**Comment by stiliajohny** [comment]
Following , I have same issue 
Tried Chrome and Safari

**Comment by erlebach** [comment]
I have the same issue. Also cannot access Marketplace, or use the Chat icon. This seems like a very serious problem.

**Comment by stiliajohny** [comment]
apparently latest version solved it :/

**Comment by stiliajohny** [comment]
@HenryHengZJ  Why you closed the issue? IS that fixed ?

**Comment by suhas4497** [comment]
is it fixed ?
i am still facing the same issues

**Comment by erlebach** [comment]
I installed flowise 2.2.1 and the issue disappeared.

**Comment by prjames409** [comment]
I am having this same issue and I have version 2.2.3 has this been fixed?

**Comment by Mufika** [comment]
Same proble, version 2.2.3, on Mac

**Comment by prjames409** [comment]
> Same problem, version 2.2.3, on Mac

@Mufika I opened up a new issue to address this problem since this issue has been closed.

**Comment by myertas** [comment]
Hello all, I solve my same problem with  [flowise@2.2.5]..

remove old and install with ....

npm install -g flowise@2.2.5

**Comment by waltonjm** [comment]
Hello @myertas, I ran a npm install -g flowise @2.2.5 and have white screen issues.  Are you saying uninstall and reinstall flowise@2.2.5 or that upgrading to that version solved your particular problem? Thank you for your insights!

**Comment by myertas** [comment]
> Hello [@myertas](https://github.com/myertas), I ran a npm install -g flowise @2.2.5 and have white screen issues. Are you saying uninstall and reinstall flowise@2.2.5 or that upgrading to that version solved your particular problem? Thank you for your insights!

Yes, I removed everything with the 

npm install -g flowise@2.2.5
command I wrote and reinstalled it. I can use it now without any problems.

**Comment by myertas** [comment]
> > Hello [@myertas](https://github.com/myertas), I ran a npm install -g flowise @2.2.5 and have white screen issues. Are you saying uninstall and reinstall flowise@2.2.5 or that upgrading to that version solved your particular problem? Thank you for your insights!
> 
> Yes, I removed everything with the
> 
> npm install -g flowise@2.2.5 command I wrote and reinstalled it. I can use it now without any problems.

![Image](https://github.com/user-attachments/assets/4fb1933e-0b14-48a3-9a7a-c9df28d7c9e0)
