### ISSUE TITLE
[BUG] On website chat doesn't work

### ISSUE THREAD

**Issue by sebaxakerhtc** [FlowiseAI/Flowise#3479]
**Describe the bug**
Created simple chat engine for test purposes.
Tested and working.
Shared and tested - works fine.
But when I putted embedded code on my website - the chat is there, but gives error
In docker I see this, when I send any message from website
```
? OPTIONS /api/v1/prediction/ae40ba1f-5c63-4e5a-8cb8-f2921b58ecfd
```

**To Reproduce**

1. Go to 'API endpoint'
2. Click on 'Embed'
3. Copy the code
4. Paste it on my website
5. Chat to the bot
6. See error instead of response `Error: NetworkError when attempting to fetch resource.`

**Expected behavior**
Bot should answer, like it works with CURL and shared bot link

**Screenshots**
![изображение](https://github.com/user-attachments/assets/54b92b64-3538-4c0e-8e0b-3b8d1422891d)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [docker]
-   Flowise Version [2.1.3]
-   OS: [Windows]
-   Browser [chrome, firefox, edge, safari]

**Additional context**
Localy and remotely it works just fine, but doesn't work on wordpress website

**Comment by HenryHengZJ** [comment]
possibly related to CORs or proxy issue: https://docs.flowiseai.com/using-flowise/embed#cors

**Comment by sebaxakerhtc** [comment]
> possibly related to CORs or proxy issue: https://docs.flowiseai.com/using-flowise/embed#cors

Thank you for your reply.
I have `CORS_ORIGINS=*` filled out, but not `IFRAME_ORIGINS=*`
How it should be filled? The same way? `IFRAME_ORIGINS=https://mydomain.com`?

**Comment by sebaxakerhtc** [comment]
> possibly related to CORs or proxy issue: https://docs.flowiseai.com/using-flowise/embed#cors

Thank you. It works now.
