### ISSUE TITLE
[FEATURE] Add AIRTABLE & Other Databases to the Data Loader list 

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#348]
**Describe the feature you'd like**
Add AIRTABLE to the Data Loader list 

**Airtable Data loader would do the following:**

- Load the data from the source.
- Convert the data to text or arrays.
- Split the data into smaller segments (with overlapping content).
- Return the list of segments of the data.

**Additional context**
**Airtable**: loads rows of an Airtable database as a list of JSONs.

- Parameters: API key (https://support.airtable.com/docs/creating-and-using-api-keys-and-access-tokens), Base id, and table id (https://support.airtable.com/docs/finding-airtable-ids).

- Outputs: List of text segments (connects to a vector database).

<img width="300" alt="Screenshot 2023-06-17 at 3 29 22 PM" src="https://github.com/FlowiseAI/Flowise/assets/129256153/5fd0f786-462a-47be-8884-33a1264502ab">

<img width="600" alt="Screenshot 2023-06-17 at 3 41 06 PM" src="https://github.com/FlowiseAI/Flowise/assets/129256153/36f4930c-1751-48b0-8b02-bc9f5cc05785">

**Comment by WizKid1968** [comment]
I added image examples. This would be an awesome feature.

**Comment by HenryHengZJ** [comment]
thanks for the idea! Love airtable and definitely will add it to one of the doc loaders

**Comment by HenryHengZJ** [comment]
Both airtable agent and loader added:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/3e0c5ef6-7f20-403a-a59a-987421f21396)
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/dc528158-de8f-441a-a9d1-c2c2a65136d2)

**Comment by WizKid1968** [comment]
> Both airtable agent and loader added: 

Amazing!!! Will be checking it out.
