### ISSUE TITLE
[BUG] couldn't start after installation

### ISSUE THREAD

**Issue by Yifat-sh** [FlowiseAI/Flowise#3481]
**Describe the bug**
![WhatsApp Image 2024-11-08 at 10 04 41_aa693339](https://github.com/user-attachments/assets/64cd663b-832c-4677-b489-4e2c1985ef09)

after installation - tried to start using the command from the website and it gave this answer:

 »   ModuleLoadError: [MODULE_NOT_FOUND] require failed to load
 »   C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\dist\commands\start.js: Cannot find module 'langchainhub'
 »   Require stack:
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\dist\index.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\dist\commands\start.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\node_modules\@oclif\core\lib\module-loader.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\node_modules\@oclif\core\lib\config\plugin.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\node_modules\@oclif\core\lib\config\config.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\node_modules\@oclif\core\lib\config\index.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\node_modules\@oclif\core\lib\command.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\node_modules\@oclif\core\lib\index.js
 »   - C:\Users\Yifatsh\AppData\Roaming\npm\node_modules\flowise\bin\run
 »   Code: MODULE_NOT_FOUND

**Comment by fpscit** [comment]
i am also facing same problem . any solution ?
