### ISSUE TITLE
[BUG] [cause]: ConnectTimeoutError: Connect Timeout Error (attempted addresses: 172.66.47.182:443, timeout: 10000ms)

### ISSUE THREAD

**Issue by bodzebod** [FlowiseAI/Flowise#3484]
**Describe the bug**
I'm building an agentflow with a supervisor and multiple workers. When I test it, I see the following error multiple times from supervisor node:

Failed to calculate number of tokens, falling back to approximate count TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RetryOperation._fn (/usr/local/lib/node_modules/flowise/node_modules/p-retry/index.js:50:12) {
  [cause]: ConnectTimeoutError: Connect Timeout Error (attempted addresses: 172.66.47.182:443, timeout: 10000ms)
      at onConnectTimeout (/usr/local/lib/node_modules/flowise/node_modules/undici/lib/core/connect.js:232:24)
      at Immediate._onImmediate (/usr/local/lib/node_modules/flowise/node_modules/undici/lib/core/connect.js:206:11)
      at process.processImmediate (node:internal/timers:483:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}

However, there's no configuration related to this mysterious IP 172.66.47.182 that is not in my infrastructure. This IP is a cloudflare one, and I suspect there's a hidden telemetry somewhere. I have disabled Flowise telemetry with DISABLE_FLOWISE_TELEMETRY=true, but it remains.
I'm running flowise inside an AWS private subnet that has no access to the internet, hence this IP is blocked.

**To Reproduce**

1. Build an agent flow with a chatbot model, a supervisor and some workers
2. Send a question to the chat
3. Inspect the container logs (can be tailed with: sudo docker logs -f --tail 100 flowise_1)

**Expected behavior**
This error comes after a default timeout of 10s, putting some unacceptable latency. 
It's not normal to have such data leak behavior while I have disabled the telemetry with DISABLE_FLOWISE_TELEMETRY=true in the container environment variables in docker-compose.yml.

**Screenshots**
![image](https://github.com/user-attachments/assets/5a52f5e5-8c31-45f7-9db0-98ac37a35b9f)
![image](https://github.com/user-attachments/assets/2b98976c-27d6-4ce3-b14c-a14ab54751b8)

**Setup**

-   Installation: using docker-compose
-   Flowise Version 2.1.3
-   OS: Linux
-   Browser: Edge

**Additional context**

**Comment by bodzebod** [comment]
I found that those calls are made by langchain, and targets the URL https://tiktoken.pages.dev:

`
/usr/local/lib/node_modules/flowise # grep -R 'pages.dev' .
./node_modules/@langchain/anthropic/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/anthropic/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/aws/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/aws/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/cohere/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/cohere/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/community/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/community/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/google-common/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/google-common/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/google-gauth/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/google-gauth/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/groq/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/groq/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/mongodb/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/mongodb/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/pinecone/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/pinecone/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/weaviate/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/@langchain/weaviate/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/langchain/node_modules/@langchain/core/dist/utils/tiktoken.cjs:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/langchain/node_modules/@langchain/core/dist/utils/tiktoken.js:            .fetch(`https://tiktoken.pages.dev/js/${encoding}.json`)
./node_modules/psl/data/rules.json:"pages.dev",
./node_modules/psl/dist/psl.js:"pages.dev",
`

**Comment by HenryHengZJ** [comment]
thanks for figuring out the issue! closing for now

**Comment by Hbmr9000** [comment]
would be great to have a feasible way to deactivate this via flowise env-variables. do you @bodzebod or @HenryHengZJ know what this traffic is actually used for? to me it seems that the tokenization still happens locally within flowise, but then why use the servers?

**Comment by Hbmr9000** [comment]
it would be great to have some documentation about modules/nodes have built-in interfaces to external services. what do you think?
for the moment its not clear to me which nodes require this tiktoken and as far as i understood now its getting the encoding instructions and, once loaded, they are stored in the memory (const cache = {};) if the addresses are blocked - how does it impact the flow? is it only used for token-counting?
