### ISSUE TITLE
[FEATURE] add a postgresql record manager in agent flows

### ISSUE THREAD

**Issue by bodzebod** [FlowiseAI/Flowise#3485]
**Describe the feature you'd like**
I'm building an agent flow and I'm using postgresql with pgvector as a vector database in order to be able to upload files via the chat.
However, there's no record manager to avoid duplicate upserts. Please can you make it available in agentflows? Thank you!

**Additional context**
![image](https://github.com/user-attachments/assets/1e1f509c-ee7c-4806-a6b6-3aa96d55a7d9)

**Comment by isikepalaku** [comment]
same here

**Comment by isikepalaku** [comment]
![postgress](https://github.com/user-attachments/assets/2fc61ef7-7cb6-4a69-b681-7ac646790626)

when upsert using postgresql record manager using supabase

**Comment by HenryHengZJ** [comment]
Can you try using Document Store? 
![image](https://github.com/user-attachments/assets/ecdf9449-54ca-4ad2-8d62-c5d4635c763d)

You can setup embeddings, vector store, record manager from there, then use it within the chatflow/agentflow

**Comment by bodzebod** [comment]
hi @HenryHengZJ , I aim at allowing a file upsert from the chat UI. I'm not sure if using document stores allows that.
In addition, I want to be able to upsert text files (mainly application log files). When adding a File loader in a document store, there's no options for setting up the record manager and vector store. It gives this option for PDF loader.

**Comment by shanequ** [comment]
I am using Milvus and hope the record manager can be available in agent flow as well.

**Comment by bodzebod** [comment]
I finally could configure a document store with a file loader, and the upsert config offers everything (embedding, vector store, record manager) in a central place. No more need for a record manager inside the agent flow.
