### ISSUE TITLE
[BUG] Flowise ui and server tries to use same port

### ISSUE THREAD

**Issue by emrahtoy** [FlowiseAI/Flowise#349]
**Describe the bug**
Flowise ui and server tries to use same port.

**To Reproduce**
yarn dev 

**Expected behavior**
Both module should have their own port to work on

**Additional context**
To solve the issue package/ui should have .env file with a different port as it shown in example .env.example file.

**Note**
Changing server's port doesn't work as flowise expect it working on the port 3000

**Comment by HenryHengZJ** [comment]
Thats because by default ui react uses port 3000
And by default server uses port 3000 too

Thats why setting PORT on `.env` file to tell ui react to work on other port.

Do you have any other recommendations besides setting the PORT on `.env` file?

**Comment by emrahtoy** [comment]
We could set the different ports as default for the server or the UI ( by checking if there is a corresponding env variable in the system otherwise we could use the default ports like 8080 and 3001 ) or we could mention this in the documentation.

**Comment by HenryHengZJ** [comment]
Updated [README](https://github.com/FlowiseAI/Flowise/blob/main/README.md#setup) for development build
