### ISSUE TITLE
[BUG] Not loading marketplace page in local environment

### ISSUE THREAD

**Issue by DefaultJARR** [FlowiseAI/Flowise#3492]
**Describe the bug**
Getting full white page when trying to navigate to marketplace page.
![image](https://github.com/user-attachments/assets/3cf5f13c-b6b7-4f3a-b525-af14f933f483)

**To Reproduce**
1. Normal flowise local installation "npm i -g flowise"
2. Langchain installation "npm i -g langhcainhub", because I was facing an error related.
3. Flowise run "npx flowise start"
4. Load "localhost:3000"
5. Open top left burger menu and navigate to "Marketplace" page

**Expected behavior**
Expected to see Marketplace page after navigating to it through burger menu.

**Screenshots**
At the beginning I attached one.

**Setup**
-   Installation: Node local installation
-   Flowise Version: flowise 1.6.0
-   OS: Windows
-   Browser: Edge

**Comment by HenryHengZJ** [comment]
What is your Flowise version?

**Comment by DefaultJARR** [comment]
> What is your Flowise version?

I've just edited the comment, I published uncompleted by mistake

**Comment by HenryHengZJ** [comment]
Fixed in newer version, try the latest one. Feel free to reopen if issue still there

**Comment by DefaultJARR** [comment]
> issue

How can I install the fixed version?

**Comment by DefaultJARR** [comment]
> Fixed in newer version, try the latest one. Feel free to reopen if issue still there

Thanks!
How can I install the fixed version?

**Comment by DefaultJARR** [comment]
"npm i -g flowise" is pointing to "flowise@1.6.0" which has this error, but looking in npm repo, the last version published by today is "flowise@2.1.3" so i installed it with "npm i -g flowise@2.1.3" and now its working, but always i get a "punycode deprecated" warning

![image](https://github.com/user-attachments/assets/4fac7dc0-cfcb-4a77-88a0-64d207b134bb)

But now, marketplace page is working, thanks
