### ISSUE TITLE
[BUG]Cannot read properties of undefined (reading 'incrementCounter')

### ISSUE THREAD

**Issue by Rrrrnnyg** [FlowiseAI/Flowise#3493]
When I send message in the chat window, I'll receive message from AI and another message says :

> Cannot read properties of undefined (reading 'incrementCounter')

<img width="376" alt="image" src="https://github.com/user-attachments/assets/69e66dc4-4576-4202-a95b-8af825ad36ec">

I have tried both the chatOpenAI and chatOpenAI custom node, and also tried using OpenAI API key directly instead of using Openrouter API KEY, but the problem has not been resolved.

**Comment by HenryHengZJ** [comment]
Should be fixed now, try updating your forked repo

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/Flowise/pull/3489

**Comment by Rrrrnnyg** [comment]
@HenryHengZJ Thanks
