### ISSUE TITLE
[BUG] Paths for file uploads are hard coded

### ISSUE THREAD

**Issue by graipher** [FlowiseAI/Flowise#3510]
**Describe the bug**
Flowise uses a hard coded folder path for some file uploads. This breaks on read-only file systems and cannot be configured.

**To Reproduce**

1. Try to run flowise in a read-only file system
2. See error

```
Error: EROFS: read-only file system, mkdir
'/usr/local/lib/node_modules/flowise/uploads'
Code: EROFS
```

**Expected behavior**
File uploads should respect the storage settings passed in via env variables (ie either `BLOB_STORAGE_PATH` if using local storage or the `S3_*` variables).

**Setup**

-   kubernetes (official docker image), read-only file system, S3 storage, Postgres DB
-   Flowise Version 2.1.3
-   OS: Linux

**Additional context**
Hardcoded paths are here:
- https://github.com/FlowiseAI/Flowise/blob/d0571291b76883a60cec7a004069a4175647172c/packages/server/src/routes/attachments/index.ts#L8
- https://github.com/FlowiseAI/Flowise/blob/d0571291b76883a60cec7a004069a4175647172c/packages/server/src/routes/openai-assistants-vector-store/index.ts#L7
- https://github.com/FlowiseAI/Flowise/blob/d0571291b76883a60cec7a004069a4175647172c/packages/server/src/routes/predictions/index.ts#L8

And `multer` will try to create the destination directory if passed as a string and if it does not exist:

> **Note**: You are responsible for creating the directory when providing destination as a function. When passing a string, multer will make sure that the directory is created for you.
https://www.npmjs.com/package/multer#diskstorage

There seems to already be some functionality for getting the right paths elsewhere: https://github.com/FlowiseAI/Flowise/blob/d0571291b76883a60cec7a004069a4175647172c/packages/server/src/controllers/get-upload-path/index.ts#L4

**Comment by HenryHengZJ** [comment]
Yep, I think we should definitely change the hard coded multer path to either whatever env variables that was set, if not, default to the hard coded path

**Comment by PylotLight** [comment]
Would this be as simple as just replacing __dirname with imported getPathForUploads()?

**Comment by graipher** [comment]
> Would this be as simple as just replacing __dirname with imported getPathForUploads()?

I think so, but I do not know enough TypeScript or about the internals of Flowise to confirm or deny.

**Comment by PylotLight** [comment]
Unfortunately it didn't work, I tried several variations but I also don't know ts that well.
Given the controller is async it was a little complicated to get a string out, 
otherwise we could convert to a sync func perhaps.

**Comment by graipher** [comment]
@HenryHengZJ This then only works for storing the blobs locally, right?
