### ISSUE TITLE
[BUG] Multi-agent Workers don't access Supervisor instructions

### ISSUE THREAD

**Issue by taras-svystun** [FlowiseAI/Flowise#3512]
### Describe the bug
In a multi-agent setup using agentflow, the workers rely solely on chat history and do not access Supervisor instructions.

### To Reproduce
Refer to the attached agentflow, which consists of a simple multi-agent system: one worker (dishes_browser_agent) displays dishes, while another (make_order_agent) handles orders.
![image](https://github.com/user-attachments/assets/726b15d3-4209-4cc7-800a-3c7cb00f9eba)

### Expected behavior
When a user enters a query such as "I want something Jamaican/Canadian/etc.," the Supervisor directs the dishes_browser worker, which generates three relevant dishes.

For a specific case:
If the user input is "I want something Italian," it should be interpreted as a request for Japanese dishes. The Supervisor’s instruction correctly specifies "Retrieve Japanese dishes ...," but the dishes_browser worker outputs Italian dishes instead. It seems that Supervisor instructions are not accessible to the workers.

### Screenshots
Ordinary flow:

![image](https://github.com/user-attachments/assets/ab780296-c90a-4c5d-bddd-5bb780fb6bd1)

Special case with "I want something Italian."

![image](https://github.com/user-attachments/assets/ad1912fb-6966-4630-bcd9-798aa1cec1db)

### Flow
Refer to the attached agentflow.

### Setup

-   Installation: Docker on Digital Ocean droplet
-   Flowise Version: 2.1.2
-   OS: Linux
-   Browser: Safari

**I would appreciate any support. Thanks!**

[simple-multi-agent Agents.json](https://github.com/user-attachments/files/17753758/simple-multi-agent.Agents.json)

**Comment by HenryHengZJ** [comment]
This is the behaviour by design, workers are the lowest level, and they do not have context about supervisor instruction, this is because workers are designed to only execute the task given by supervisor: https://docs.flowiseai.com/using-flowise/agentflows/multi-agents#id-1.-system-architecture

**Comment by taras-svystun** [comment]
Thanks for the answer, @HenryHengZJ.

"workers are designed to only execute the task given by supervisor". How (if the workers do not have context about supervisor instruction)?

From my example the worker doesn't seem to execute the task given by supervisor.

**Comment by HenryHengZJ** [comment]
Supervisor will generate the instruction, which then passed to worker to execute

![image](https://github.com/user-attachments/assets/fed48a32-12d0-418b-871f-45080942aefc)

I'd suggest turning on analytic https://docs.flowiseai.com/using-flowise/analytic for more details
