### ISSUE TITLE
[BUG]Chatbox returns a blank page after saving the chatflow

### ISSUE THREAD

**Issue by cuonvyaobianbai** [FlowiseAI/Flowise#3514]
**Describe the bug**
I followed the youtube guide(https://www.youtube.com/watch?v=kAyKOsm8L5Y&t=270s) to create my first chat flow. If I am not saving the chatflow(leaving this as untitled chatflow), I can click the chatbox button and this will return a chatbox. But after I saved this chatflow, the chatbox will return an empty page.

**To Reproduce**

1. Create a new chatflow
2. Add LLM Chain + ChatOpenAI + Prompt Template and fill in mandatory fields
3. Click the chatbox, and this will open a chatbox window
4. Save this chatflow and give it a new name
5. Click the chatbox, and an empty window return

**Expected behavior**
Chatbox can successfully show

**Screenshots**
![Snipaste_2024-11-15_10-01-58](https://github.com/user-attachments/assets/a96e0793-208a-463b-984d-bb5587198943)

**Flow**
[STARING2 Chatflow.json](https://github.com/user-attachments/files/17760427/STARING2.Chatflow.json)

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version: flowise/1.6.0 darwin-x64 node-v22.11.0]
-   OS: macOS
-   Browser chrome

**Additional context**
Recording for reference

https://github.com/user-attachments/assets/fb4bd123-d72f-4a1b-9f39-dfbfd0e63dea

**Comment by kentan88** [comment]
I experienced the same issue. So I switched to run it using docker and it works.

**Comment by cuonvyaobianbai** [comment]
> I experienced the same issue. So I switched to run it using docker and it works.

Yes, I tried running with docker and it is running fine. Hope npm version can be fixed soon

**Comment by HenryHengZJ** [comment]
how are you installing it? `npx flowise start`?

**Comment by stephabauva** [comment]
i had to clone the repo, npm install and build it to have that issue fixed
