### ISSUE TITLE
[BUG] v2.1.4 Cannot override variables

### ISSUE THREAD

**Issue by hans00** [FlowiseAI/Flowise#3521]
**Describe the bug**
Cannot override variables, whatever security enabled or not.

**To Reproduce**

1. Import flow from old version
2. Enable override for the variable
3. Make request

**Expected behavior**

Override success

**Screenshots**

![image](https://github.com/user-attachments/assets/7d04eae5-7461-4cec-8a49-627fd3c8a51b)
![image](https://github.com/user-attachments/assets/ebc6985e-07ad-421e-860d-165433eb3d96)
![image](https://github.com/user-attachments/assets/a8351ab8-5a0f-4a05-b4fe-b7d82f890723)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation docker
-   Flowise Version: 2.1.4
-   OS: Linux
-   Browser chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
Do you have a simple flow for me to test? are the variables used in custom tool or other places? chatflow or agentflow

**Comment by hans00** [comment]
[ExportData.json](https://github.com/user-attachments/files/17779419/ExportData.1.json)

```sh
docker run -it --rm --name flowise -p 3000:3000 flowiseai/flowise

# Import data

curl http://localhost:3000/api/v1/prediction/479d9db3-9606-40e6-b78c-bd4405a87931 \
     -X POST \
     -d '{"question": "Hey, how are you?", "overrideConfig": {"vars":{"test":"overrided"}}}' \
     -H "Content-Type: application/json"
```

**Comment by HenryHengZJ** [comment]
Fixed now in main branch, will update to new Docker version soon!
