### ISSUE TITLE
Flowise: Facing below issue while using Upsert documentStoreServices._insertIntoVectorStoreWorkerThread - AggregateError

### ISSUE THREAD

**Issue by santhosh-hu-tfs** [FlowiseAI/Flowise#3523]
Flowise:
Facing below issue when I try to enable Record Manager

Status: 500
Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - AggregateError

![image](https://github.com/user-attachments/assets/9a69583c-8018-46ef-a609-b5fbc2913e8b)

@ocflowiseai

**Comment by HenryHengZJ** [comment]
Is your Pinecone Dimension compatible with OpenAI Embedding?

i.e: if you have 1536 on Pinecone, you have to use text-ada-002

embedding 3 large has 3072 dimension. https://openai.com/index/new-embedding-models-and-api-updates/

**Comment by santhosh-hu-tfs** [comment]
Hi,

I tried using text-embedding-ada-002 but still facing the same issue. Open AI + Pinecone were working fine before configuring the Record Manager but issue started once after adding Postgres Record Manager.

Below is my pinecone configuration

***@***.***

And my Open AI embedding configuration.

***@***.***



Regards,
Santhosh

**Comment by santhosh-hu-tfs** [comment]
This is resolved now, the issue was with the incorrect port being used for Record Manager Database.
![image](https://github.com/user-attachments/assets/420bde8d-97aa-491c-a115-b4d361cd4965)

**Comment by dev01AID** [comment]
Had exactly the same problem. The port of the Record Manager seems to change. Everyone who has the problem, check the port even when you copied it before.
