### ISSUE TITLE
[BUG] v2.1.4 Cannot override variables - NPM

### ISSUE THREAD

**Issue by CesarPetrescu** [FlowiseAI/Flowise#3526]
**Describe the bug**
Cannot override variables

**To Reproduce**
I triedn enabling the Override Config, yet nothing worked

1. Go to 'Settings on a chatflow'
2. Enable 'Global override and specific for each nodde parameters'
3. I tried with postman to upsert a vector with a different text in the textarea:

{
         "stopNodeId": "redis_2",
         "overrideConfig": {
             "text": {
                 "plainText_2": "Jane Smith is a project manager with expertise in agile methodologies and over 8 years of experience..."
             }
         }
}

Yet only the default character in the node ( # ) was upserted

**Expected behavior**
See this in the redis store:
Jane Smith is a project manager with expertise in agile methodologies and over 8 years of experience

**Screenshots**
![{0D5975CD-F003-4200-9B15-06993E70C86D}](https://github.com/user-attachments/assets/a061447c-b6a3-4ae0-839c-1cdc9008d0da)

**Setup**

-   npx flowise start
-   Flowise Version [2.1.4]
-   OS: [Linux - Debian]
-   Browser [I am using curl mostly for now since i need to debug, but i made the flow in chrome]

**Additional context**
I updated [npm install flowise@latest] since i've seen that this has been merged to main branch but it sill doesnt work

**Comment by CesarPetrescu** [comment]
Temporary fix for my issue:
npm install flowise@2.1.3

**Comment by HenryHengZJ** [comment]
Fix is merged to main, will be pushing to new release soon
