### ISSUE TITLE
[BUG] Icons are not going to be showing without a build ( gulp file is not triggered in dev mode )

### ISSUE THREAD

**Issue by emrahtoy** [FlowiseAI/Flowise#353]
**Describe the bug**
Icons are not working in the panel in case you don't trigger build before "yarn dev"

**To Reproduce**

1. Clone the project
2. yarn install
3. yarn dev
4. check the panel 

**Expected behavior**
Icons should be seen as it should be.

**Comment by HenryHengZJ** [comment]
perhaps we can change this [line](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/package.json#L9)
to `tsc --watch && gulp`?

**Comment by emrahtoy** [comment]
I believe it won't work as the dependency to the components is a library dependency, not a local library dependency or a link dependency.

Depending on version of the yarn it should be something like one of these;

>= 2.x
yarn add flowise-components@file:../components
yarn add flowise-ui@file:../ui

yarn < 2
yarn add file:../components
yarn add file:../ui

yet I still am not sure if this could work as intended in the development mode. Because we need all the projects running in development mode so we can debug.

I also remember something about  [yarn link](https://classic.yarnpkg.com/en/docs/cli/link) but I couldn't have time for a test.

**Comment by emrahtoy** [comment]
It should be `gulp && tsc --watch`

I have tested "yarn link" and it solves local library problem.

1. cd packages/ui
2. yarn link
3. cd ../components
5. yarn link
6. cd ../server
7. yarn link flowise-ui flowise-components

I think this should be exist in documentation too.
