### ISSUE TITLE
Perform a semantic search on multiple tables in postgres/multiple indexes in elasticsearch for RAG

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#3536]
@HenryHengZJ  - Is it possible to retrieve documents from multiple indexes or tables for postgres or elastic search vector stores? If yes, how is it done using Conversational Retrieval QA chain or using other nodes.

**Comment by HenryHengZJ** [comment]
this could be helpful: https://docs.flowiseai.com/use-cases/multiple-documents-qna

**Comment by vijaykammili** [comment]
@HenryHengZJ - Is it possible to add an option to force tool calling for retriever tool? The model isn't using the retriever tool for some questions despite explicitly stating to use the tool in the prompt, i think this is because it's set to tool choice of any currently.
