### ISSUE TITLE
[BUG] Dynamic Postgres Metadata Filtering via Agent State

### ISSUE THREAD

**Issue by sirsimonson** [FlowiseAI/Flowise#3545]
## Describe the bug
The metadata filter for Retriever Tool does not work with Postgres Metadata Filtering when used with the new dynamic filtering feature via agent state. (https://github.com/FlowiseAI/Flowise/pull/3501) The filter is not passed down to the Postgres query, resulting in an unfiltered response.

## To Reproduce

Configure a metadata filter for Retriever Tool using the new dynamic filtering feature.
Observe that filters are not applied as described in the PR.
Expected behavior
The metadata filter should correctly apply to the Postgres query and return filtered results.

![image](https://github.com/user-attachments/assets/9480807a-598d-43da-9564-9bca0e83c8cb)

## Additional context

Filters configured as "Postgres Additional Metadata Filter" works currently in "Test Retrieval Query" Playground but fail when dynamically added as "Additional Metadata Filter" to the Retriever Tool.

**Comment by sirsimonson** [comment]
@HenryHengZJ Please describe how this could be verified/tested...
![image](https://github.com/user-attachments/assets/ed75273a-3c4f-49e1-9d21-7955a96ab889)
I've logged the vectorstore instance used and it seems to have the correct "filter" property attached. shouldn't this be the same as "Additional Metadata" for Postgres Node itself?

**Comment by HenryHengZJ** [comment]
I've tried it on Pinecone and it works. Will test it on PG.

**Comment by sirsimonson** [comment]
Yes I can confirm that it works like a charm with pinecone. I wonder why it's not applied to the Postgres Instance. Overall the feature is a very valuable addition to Flowise. 

If you point out the issue I'm excited to fix it. Unfortunately I wasn't able to debug further then checking if the filter prop is even passed from the retriever tool. As far as I can see this works but since the PG Node is a VectorStoreRetriever and not a VectorStore it doesn't work.

**Comment by sirsimonson** [comment]
Seems like my issue has been fixed with: #3579 
Thanks to @HenryHengZJ 

I can't use the agent state directly but pass it to the prompt as the query and extract metadata in the retrieval step which is then correctly applied to the postgres pre-configured Document Store node.
