### ISSUE TITLE
[BUG]pinecone can not works (Request failed with status code 400)

### ISSUE THREAD

**Issue by smallanything** [FlowiseAI/Flowise#355]
I just want to try pdf reading flow
and I have setup the pinecone,but the result always be Request failed with status code 400

Seeking you help to solution about it~

<img width="1290" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/132641800/93c9b622-c44e-44ad-91c3-5d534d8cf684">

**Comment by HenryHengZJ** [comment]
might be related to this - https://github.com/FlowiseAI/Flowise/issues/8
