### ISSUE TITLE
[BUG] Provided file is ignored when upserting via API

### ISSUE THREAD

**Issue by kennyakers** [FlowiseAI/Flowise#3560]
**Describe the bug**
When POSTing a file to the `/vector/upsert/{id}` endpoint, the provided file is ignored, and instead the file uploaded within the Flowise UI is upserted. In my case, I'm upserting PDFs to a Pinecone vector store. All credentials have been double-checked.

**To Reproduce**

An example upsertion flow is shown below:
<img width="785" alt="Screenshot 2024-11-24 at 6 12 46 PM" src="https://github.com/user-attachments/assets/2697289e-bb5a-4897-9104-fe0acfd1d5e1">

Override config has been enabled so API calls should be able to overwrite the PDF file:
<img width="1166" alt="Screenshot 2024-11-24 at 6 26 25 PM" src="https://github.com/user-attachments/assets/f878aaf0-1ddd-4310-b822-d1a26995e973">

Note that the file originally uploaded is of the classic book _Frankenstein_. When I make a call to upsert a different book, _Of Mice and Men_, Frankenstein still ends up getting upserted (see response):
<img width="797" alt="Screenshot 2024-11-24 at 6 17 01 PM" src="https://github.com/user-attachments/assets/d320e8ad-4356-4c93-8e62-93e4c9d2bd56">

If I remove the file from the "PDF Loader" node, uploading any PDF (I even used the same Frankenstein file) to it will result in 0 documents getting upserted:
<img width="808" alt="Screenshot 2024-11-24 at 6 14 26 PM" src="https://github.com/user-attachments/assets/037be8f8-5434-40b5-9969-2b8d6fc3a36d">

**Expected behavior**
The file provided in the form data should be upserted, not the file originally uploaded.

**Setup**

-   Installation: Repocloud.io instance
-   Flowise Version 2.1.5

**Additional context**
This only started becoming a problem ~3-4 weeks ago (i.e., beginning of November). It was working for months before then.

**Comment by ThijsObers** [comment]
I face the same issue as well.

**Comment by HenryHengZJ** [comment]
thanks for reporting, I knew something was missing! Fix is here: https://github.com/FlowiseAI/Flowise/pull/3569, will be pushed to new release some time this week

**Comment by marsalan06** [comment]
any update on this issue ? the version 2.2.1 still has this bug :/

**Comment by kennyakers** [comment]
> any update on this issue ? the version 2.2.1 still has this bug :/

It appeared to be fixed briefly after upgrading to v2.2.1, but returned to the original behavior soon after.

After trying both the PDF loader and Unstructured loader (same result), the upsert history shows the 'files' parameter is never updated with the API-provided file -- perhaps the override config isn't taking effect here?

@HenryHengZJ hope that ^ context is useful. Appreciate all your work.
