### ISSUE TITLE
Is it not possible to disable app level auth?

### ISSUE THREAD

**Issue by PylotLight** [FlowiseAI/Flowise#3561]
**Describe the bug**
If adding FLOWISE_USERNAME etc should enable auth, 
then not having them should disable it by default and allow no login access.

Currently using the helm chart, but that shouldn't make any difference.

**To Reproduce**

1. Go to deploy helm chart for flowise
2. Load main page
3. Get login screen despite no env vars being configured.
4. Can't login

**Expected behavior**
Load the page with no login screen

**Screenshots**
N/A

**Flow**
N/A

**Setup**

-   Installation [docker]
-   Flowise Version [2.1.5]
-   OS: [linux/helm]
-   Browser [chrome]

**Additional context**
N/A

**Comment by HenryHengZJ** [comment]
The docker image is working as expected, if no `FLOWISE_USERNAME` set, you dont see the login dialog

**Comment by PylotLight** [comment]
So it seems the reason I was having issues is due to the basepath issue, and once I updated frontend source code to use the correct prefix that it just put me through. Although weirdly I do have the un/pw set in env vars and it still doesn't ask for them.
