### ISSUE TITLE
[BUG] File upload node stopped working on cloud

### ISSUE THREAD

**Issue by Tokail** [FlowiseAI/Flowise#3573]
**Describe the bug**
File upload node stopped working

**Setup**

-   Installation [Cloud]
-   Flowise Version [e.g. 1.2.11]
-   OS: [Windows]
-   Browser [Edge]

**Comment by HenryHengZJ** [comment]
Should be fixed now. Can you try again?

**Comment by HenryHengZJ** [comment]
Do you see the file upload button from the chat? Or you are able to upload but it's not processing? Do you have a recordings to show the issue?

**Comment by Tokail** [comment]
@HenryHengZJ Here's a loom video of the issue [](https://www.loom.com/share/2ffa7e39d4fc4706b10ce7b9b5a0c63f?sid=378678fa-15f8-4cf2-ba4d-b2eecb01a261)

**Comment by HenryHengZJ** [comment]
should be fixed in v2.2.2!

feel free to re-open if issue still there
