### ISSUE TITLE
[BUG] Unable to Connect 'Similarity Score Threshold Retriever' Node to Any Vector Store

### ISSUE THREAD

**Issue by jmm-usu** [FlowiseAI/Flowise#3575]
I’m experiencing an issue with the "**_Similarity Score Threshold Retriever_**" node in Flowise. It seems that this node cannot be connected to any vector store. I’ve tried various vector stores, but none of them work.

I only found [this](https://github.com/FlowiseAI/FlowiseDocs/blob/main/integrations/langchain/retrievers/similarity-score-threshold-retriever.md) empty Readme page about it.

Could you please clarify:

- How exactly does the "Similarity Score Threshold Retriever" node function?

- With which vector store nodes is it compatible?

- Are there any specific steps or configurations required to make it work?

![image](https://github.com/user-attachments/assets/e3032451-859b-4006-ab29-4b6f18744260)

**Comment by HenryHengZJ** [comment]
Click the drop down from Faiss Retriever, change it to Faiss Vector Store:
![image](https://github.com/user-attachments/assets/16376a6b-5a09-4bd5-adbb-d1a8573ec3ea)

How does it work: https://js.langchain.com/v0.1/docs/modules/data_connection/retrievers/similarity-score-threshold-retriever/

Every vector store is compatible
