### ISSUE TITLE
[BUG] JSON parse error in Prompt Values when used in LLMChain

### ISSUE THREAD

**Issue by kevjett** [FlowiseAI/Flowise#360]
**Describe the bug**
I am using a LLMChain like the Prompt Chaining marketplace template. For the first prompt, I am asking GPT3 to return a JSON object in the response. I am passing the Output Prediction as a Prompt Value for the second prompt to use as a variable in the input text. When I do that, it returns a JSON parse error trying to parse the Prompt Values of the second prompt.

**To Reproduce**

1. Start with the Prompt Chaining template.
2. Add Open API key to Model inputs
3. Change the first prompt Template to this "You are an AI who performs one task based on the following objective: {objective}.
Respond with how you would complete this task as a JSON object with your answer as an "answer" key:"
4. Change the second prompt Prompt Values to this so it will populate the result key with the output of the first: 
{
  "objective": "{{question}}",
  "result": "{{llmChain_2.data.instance}}"
}
5. Run the chat and ask it any question: What is a bug?
6. It will respond with a syntax error like this - SyntaxError: Unexpected token A in JSON at position 49 

**Expected behavior**
I expect to use the first output as a string to input in the second prompt. The only way to do this is to add it as a Prompt Value.

**Setup**
-   Installation docker
-   Flowise Version 1.2.12
-   OS: macOS
-   Browser Chrome

**Comment by HenryHengZJ** [comment]
hey @kevjett do you mind to export the flow? 

This is likely due to incorrect format of JSON response

**Comment by dimknaf** [comment]
{{llmChain_2.data.instance}}, this was not working for me either.
I turned it to {{llmChain_0.data.instance}} and worked.

**Comment by dimknaf** [comment]
Where can I find the debug info?

**Comment by HenryHengZJ** [comment]
> 5\. What is a bug

I just tried it there it was because how you asked the chain to return as JSON and thats why its doesn't parse correctly.

Instead of this:
`You are an AI who performs one task based on the following objective: {objective}.
Respond with how you would complete this task in a JSON object with your answer as a "answer" key:`

I'd remove the JSON part like this:
`You are an AI who performs one task based on the following objective: {objective}.
Respond with how you would complete this task:`

and this works for me

**Comment by HenryHengZJ** [comment]
Closing for now, feel free to reopen if issue persists

**Comment by mehrajagdish** [comment]
Using this in prompt template

Output your script in this JSON format:

{
  "greeting": "Hello {name}, how are you ?"
}

if i simply write a name instead of {name} it works , but doesnt work this way
