### ISSUE TITLE
[BUG] error in upsert config: Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - TypeError: fetch failed

### ISSUE THREAD

**Issue by bodzebod** [FlowiseAI/Flowise#3603]
**Describe the bug**
Hi, 
Using **Flowise AI 2.1.5**.

I try to set up a document store with a file loader. The upsert config is made of:
- ollama embedding model
- postgresql with pgvector as vector store
- the same postgresql as record manager

![image](https://github.com/user-attachments/assets/35de8e95-200f-45ac-860a-6722bd499556)

When clicking "upsert", I get the error:

```
Status: 500
Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - TypeError: fetch failed
```

I don't see any output in flowiseAI docker log. Is it possible to increase the level of verbosity for debugging?

**To Reproduce**

1. Create a document store with a file loader
2. Reproduce the same upsert config as in the screenshot
3. Click upsert button

**Expected behavior**
I expect a successful upsert.

**Screenshots**

**Flow**
![image](https://github.com/user-attachments/assets/13bcd52b-9063-4736-9b31-55c66239b0bd)

**Setup**

-   Installation: Docker
-   Flowise Version: 2.1.5
-   OS: Linux
-   Browser: Edge

**Additional context**
Many thanks for your help!

**Comment by bodzebod** [comment]
I found the issue. For embedding, I'm using ollama serving from a remote server.
I updated it recently, and forgot to update the file /etc/systemd/system/ollama.service to allow remote access, i.e:
Environment="OLLAMA_HOST=0.0.0.0"

After updating the service (sudo systemctl daemon-reload) and restarting (sudo systemctl restart ollama), I no longer have the error. The error was occuring because the embedding model was not accessible.

**Comment by laurentbekaert593-rgb** [comment]
its not working?

**Comment by laurentbekaert593-rgb** [comment]
i have this error 

Status: 500
Error: documentStoreServices.insertIntoVectorStoreMiddleware - Error: documentStoreServices.insertIntoVectorStore - Error: documentStoreServices._insertIntoVectorStoreWorkerThread - Error: getaddrinfo ENOTFOUND postgres
