### ISSUE TITLE
[BUG] Chat widget variables not working in custom tool ( Flowise 2.2.0 )

### ISSUE THREAD

**Issue by thenextsolutions** [FlowiseAI/Flowise#3604]
**Describe the bug**
Chat widget variables not working in custom tool.

chatflowConfig: {
            vars: {
                user_id: "user_id",
            },
        },

Flowise 2.2.0

**Comment by SirLucian** [comment]
All variables are down. 
I cannot access variables using the $vars.{variableName} that i pass it using the api. I'm rolling back my version now.

**Comment by SirLucian** [comment]
UPDATE: I found a fix

This is a feature not a bug to do with override variables. 

You now have to configure them in your global variables, you can't just declare them on the fly. so I add a couple empty objects for things I want to declare in api calls and then in my chatflow config I can toggle them to allow for overwriting
