### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by santhoshRK98** [FlowiseAI/Flowise#3605]
**Describe the bug**
I am trying to set up Flowise.ai to interact with a local AI model stored on my machine. However, I'm encountering issues when trying to use the chat functionality, which throws errors. I need help troubleshooting the issue. throws 500 error i use flowise on cmd using npx flowise start and local ai on docker

**Expected behavior**
suppose to give me a response

**Screenshots**
![image](https://github.com/user-attachments/assets/1880671d-3d43-41ac-8111-13057c2842a9)

![image](https://github.com/user-attachments/assets/c255ae31-4e76-446c-900e-f5bf874f69fb)

**Setup**

-   Docker version 27.3.1, build ce12230
-   Flowise Version flowise/2.1.5 win32-x64 node-v20.18.1
-   OS: Windows
-   Browser : Brave

**Comment by PylotLight** [comment]
Why did you not include a title, please make sure this issue is way more descriptive with a title and full details of your issue.

**Comment by HenryHengZJ** [comment]
Better suited for Discussion, there's lot of answers and docs about how to use it
