### ISSUE TITLE
[BUG] syntaxerror: Unexpected token 'F', Failed is not valid JSON

### ISSUE THREAD

**Issue by simsherpa** [FlowiseAI/Flowise#361]
**Describe the bug**
Thank you so much for this very inspired resource! 

I am encountering the following error with the flow below: 

> SyntaxError: Unexpected token 'F', "Failed to "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:6613:19)
    at successSteps (node:internal/deps/undici/undici:6587:27)
    at node:internal/deps/undici/undici:1236:60
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  attemptNumber: 7,
  retriesLeft: 0
}

**To Reproduce**

1. Copy Conversational Retrieval QA Chain flow from Marketplace
2. Replace Text File component with PDF File component 
3. Replace OpenAI components with HuggingFace component 
4. Enter API Keys
5. Save flow
6. Select PDF
7. Enter Prompt in Chat panel

**Expected behavior**

Expected the flow to execute allowing inspection of PDF file entries.

**Screenshots**

![image](https://github.com/FlowiseAI/Flowise/assets/96396667/f8b81800-f480-4789-87ee-d4fb5e19e3fd)

**Flow**
If applicable, add exported flow in order to help replicating the problem.
[PDF-Explorer Chatflow.zip](https://github.com/FlowiseAI/Flowise/files/11780439/PDF-Explorer.Chatflow.zip)

**Setup**
-   Installation: `npx flowise start`
-   Flowise Version: 1.2.11
-   OS: macOS (Sonoma)
-   Browser: Arc/chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
hey @simsherpa do you face same problem when using ChatOpenAI and OpenAIEmbedding nodes?

**Comment by simsherpa** [comment]
Hi @HenryHengZJ, thanks for the follow-up. I'm exploring strictly open source LLMs -- so I do not have an OpenAI account and therefore have not tried those OpenAI components. Any other suggestions?

**Comment by trepont** [comment]
> hey @simsherpa do you face same problem when using ChatOpenAI and OpenAIEmbedding nodes?

Hey, @HenryHengZJ, it was functioning properly when utilizing the ChatOpenAI and OpenAIEmbedding nodes. However, we are currently seeking an open-source language model like LLM-Falcon. Could you please investigate this matter?

**Comment by raffareis** [comment]
I have this same problem in two different flows. Both uing ChatOpenAi. The common characteristic is that it is a LLM Chain feeding an OutPut prediction into an Prompt Template, and the LLM Chain outputs predictions that contains `"`

Seems like the `"` character is not being escaped, and thus it is breaking the json.

![image](https://github.com/FlowiseAI/Flowise/assets/4365623/fce8356d-687a-430b-9a1e-350253551f75)


![image](https://github.com/FlowiseAI/Flowise/assets/4365623/45441e83-159b-4b66-9e60-c6eb4f9446fa)

**Comment by HenryHengZJ** [comment]
good news we have a PR addressing this issue - https://github.com/FlowiseAI/Flowise/pull/558

**Comment by raffareis** [comment]
Update: The former PR got closed, now on #612
