### ISSUE TITLE
Simple agent workflow fails to start with AWS Bedrock (Anthropic)

### ISSUE THREAD

**Issue by dmitryn96** [FlowiseAI/Flowise#3614]
**Describe the bug**
Sample agent workflow (with one agent story generator and second - title generator) fails to start (giving Message Stopped message) when connected to AWS ChatBedrock model

**To Reproduce**

1. Create new Agent Flow, with one supervisor and two worker nodes. Exact prompts don't matter but for this test first agent was asked to generate short story in magical realism genre and the second one was asked to give it a title
2. Add ChatOpenAI Chat Flow (gpt-4o-mini model) and connect it Supervisor. Save the flow
3. Trigger the flow by typing (any) topic in Chat window. Observe successful flow progression and completion
4. Add AWS ChatBedrock Chat Flow (anthropic-claude-3.5-sonnet.20241022-v2.0 model; same result with 3.5 haiku). Disconnect ChatOpenAI model from Supervisor node and connect AWS ChatBedrock flow. Save the flow
5. Trigger the flow by typing (any) topic in Chat window. Observe the popup "Message Stopped" immediately after starting the flow

**Expected behavior**
Expected to see the same result with AWS ChatBedrock as with ChatOpenAI  (i.e successful flow execution)
.

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.
See the model export and corresponding logs
[Model-1 Agents.json](https://github.com/user-attachments/files/17967249/Model-1.Agents.json)
[logs.txt](https://github.com/user-attachments/files/17967250/logs.txt)
The actual error message in the logs is:
Chain run errored with error: "A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.\n\nValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again

**Setup**

-   Installation: docker installation on AWS EC2 (started with docker compose)
-   Flowise Version 2.2.0 (from package.json)
-   OS: Amazon Linux 2023
-   Browser:  Chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
Answered here: https://github.com/FlowiseAI/Flowise/issues/3624
