### ISSUE TITLE
can you check this error the supervisor calls the workers , and then gets stopped the workers doesnt respond [BUG] 

### ISSUE THREAD

**Issue by Syed-Faizal-S** [FlowiseAI/Flowise#3618]
[Chat_model Agents.json](https://github.com/user-attachments/files/17975263/Chat_model.Agents.json)

**Comment by PylotLight** [comment]
Why did you not include a title, please make sure this issue is way more descriptive with a title and full details of your issue.

**Comment by HenryHengZJ** [comment]
Could be multiple issue, I'd suggest turning on Analytics https://docs.flowiseai.com/using-flowise/analytic for debugging.
