### ISSUE TITLE
[BUG] Error buildAgentGraph - ValidationException: A conversation must alternate between user and assistant roles. Make sure the conversation alternates between user and assistant roles and try again.

### ISSUE THREAD

**Issue by limbergarciavilchez** [FlowiseAI/Flowise#3624]
**Describe the bug**

I have a sequential agent flow that evaluates the relevance of information returned from a vector database in Qdrant, using OpenAI. The flow works correctly and I get the expected result. However, the error occurs when I try to use AWS ChatBedrock with the model anthropic.claude-3.5-sonnet-20240620-v1:0.

**Screenshots**

![image](https://github.com/user-attachments/assets/c477d630-e16f-4329-876a-54f35e9b2db1)

![image](https://github.com/user-attachments/assets/19e888bc-5877-413e-b788-22afde9d7f97)

**Comment by HenryHengZJ** [comment]
Similar: https://github.com/FlowiseAI/Flowise/issues/3181

Bedrock still hasnt remove the alternate message limitations

Hopefully they will be implementing this soon
