### ISSUE TITLE
[BUG] Copy Icon in Feedback Config "On" State Fails to Copy Chat Response Content to Clipboard

### ISSUE THREAD

**Issue by diptesh-bose** [FlowiseAI/Flowise#3625]
**Describe the bug**
The Copy Icon that becomes available Feedback Config is toggled to On state is not copying the content from the chat response.

![image](https://github.com/user-attachments/assets/7e77f0d6-f7ae-49a8-9edf-453496530e74)

**To Reproduce**

1. Go to 'Existing Chat Flow'.
2. Click on 'Gear Icon of Chat Flow Configuration'
3. Scroll down to 'Configuration >> Chat Feedback Tab'
4. See error - There is no error as the text is not being copied to Clipboard. Hence, cannot replicate.

**Expected behavior**
The Copy Icon should be able to copy the content to Clipboard.

![image](https://github.com/user-attachments/assets/ac1d16eb-ceb5-4f6d-bd3f-5d09f8aa2095)

**Screenshots**
![image](https://github.com/user-attachments/assets/7d671728-39f7-465c-9b1a-7eb59e5cd7db)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by PylotLight** [comment]
Can you add proper title for this issue?

**Comment by diptesh-bose** [comment]
@PylotLight Done

**Comment by HenryHengZJ** [comment]
Is this embedded chat?

**Comment by diptesh-bose** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HenryHengZJ** [comment]
couldnt replicate it, was able to copy successfully on Flowise UI, Share Chatbot, Embedded Chat: 
![image](https://github.com/user-attachments/assets/8500bdf1-9195-49d4-9ee5-f917b4ce5060)
