### ISSUE TITLE
[FEATURE] Add support for loading EPUB files

### ISSUE THREAD

**Issue by kennyakers** [FlowiseAI/Flowise#3629]
**Describe the feature you'd like**
An ePub file loader, similar to that of the PDF loader. This would be a simple, free alternative to paid offerings like Unstructured.io

**Additional context**
LangChain already has an [EPUBLoader](https://js.langchain.com/docs/integrations/document_loaders/file_loaders/epub/) that this node could wrap.

**Comment by Ajay-Satish-01** [comment]
@kennyakers please take a look at #3668
