### ISSUE TITLE
Request failed with status code 404

### ISSUE THREAD

**Issue by lb1223** [FlowiseAI/Flowise#363]
I had no problem using flowise+pinecone a few days ago, but after updating today, Error: Request failed with status code 404 keeps appearing. Can anyone tell me what went wrong?

**Comment by HenryHengZJ** [comment]
are you using docker, npm or yarn?

**Comment by lb1223** [comment]
yes，I used render to arrange this program. Now I have no problem using the chat model, and some functions of the agent can also be used, but every time I load the pinecone database, it is an error.Is there any way to solve this?

**Comment by TheTinkerJ** [comment]
what's the llm you used, i found the same issue, when i changed the llm to `gpt-3.5-turbo-0613` then it worked

**Comment by lb1223** [comment]
I used azure openai gpt-3.5, I can't afford openai's api，I have given up and switched to the application that comes with azure. Besides flowise, do you know other flexible commercial applications?

**Comment by zakiso** [comment]
same error here with azure openai gpt-3.5

**Comment by chungyau97** [comment]
Hi guys,

I just added some documentation on implementing Azure OpenAI
1. [Embeddings](https://github.com/FlowiseAI/FlowiseDocs/blob/main/embeddings/azure-openai-embeddings.md)
2. [Chat Models](https://github.com/FlowiseAI/FlowiseDocs/blob/main/chat-models/azure-chatopenai.md)
