### ISSUE TITLE
[BUG] Can't upload a file in the chat for agent flows

### ISSUE THREAD

**Issue by bodzebod** [FlowiseAI/Flowise#3630]
**Describe the bug**
I have a document store where the vector store is set as "file upload" enabled. (please note that I have tried with both postgresql/pgvector and qdrant as vector stores).

Then I have created a basic test agentflow (see screenshot below). I have also enabled the full file upload setting in the agentflow configuration.

Whenever I upload an application log file (text file) to the chat, and ask a question about it, the worker always reply that he's unable to access this file (see the screenshot below).

**To Reproduce**

1. create a document store and configure the embedding, vector store (qdrant or pgvector) and record manager
2. Create an agentflow similar to the one in the screenshot
3. In the chat, attach a test file and ask a question about it. For example: analyze the errors in the uploaded file application.log
4. See the worker's response

**Expected behavior**
The workers should have access to the uploaded file.

**Screenshots**
![image](https://github.com/user-attachments/assets/4aa4d7bf-b0c9-48c8-bd80-bf373fccb93c)

![image](https://github.com/user-attachments/assets/c0337996-8094-4b57-8af2-0290ebdbb611)

![image](https://github.com/user-attachments/assets/754ce9c0-ba22-4e0e-bb0b-9dcf08d55c9e)

**Flow**
exported flow: 
[Test Agent Agents.json](https://github.com/user-attachments/files/18005557/Test.Agent.Agents.json)

**Setup**

-   Installation: docker
-   Flowise Version: 2.2.1
-   OS: Linux
-   Browser: edge

**Additional context**
N/A

**Comment by Tokail** [comment]
I'm having the same issue in the cloud version, even basic file upload is not working.

**Comment by HenryHengZJ** [comment]
> I'm having the same issue in the cloud version, even basic file upload is not working.

this will be fixed in the next week release: https://github.com/FlowiseAI/Flowise/pull/3609
