### ISSUE TITLE
[FEATURE] Question: is there a way of routing between several chatflows?

### ISSUE THREAD

**Issue by taras-svystun** [FlowiseAI/Flowise#3632]
**Describe the feature you'd like**
I have several chatflows, each handling specific chatbot functionalities. I call these chatflows from the backend and wonder if there’s a way to dynamically route user queries to the appropriate chatflow.

For context:
- Routing can sometimes be determined by conditions (e.g., if a user isn’t found in the database, route them to the register-chatflow).
- However, in other cases, the decision isn’t straightforward based on context or user state.
I’m not aware of any built-in Flowise feature for routing but would like to know if anyone has a more efficient solution.

Ideas I’ve considered:

1. Create an additional chatflow to act as a router, analyzing user input and responding with the appropriate chatflow to call. This router would  know when each one of other chatflows should be called.
2. Use predefined user commands to switch functionalities (e.g., type "menu" to view the menu or "add dish" to modify it).

Both approaches have drawbacks, so I’m looking for a smarter way to implement routing.

**Comment by HenryHengZJ** [comment]
You might be looking for agentflow condition agent: https://docs.flowiseai.com/using-flowise/agentflows/sequential-agents#id-8.-condition-agent-node

you can chain multiple agents/llm, but not chatflow (work in progress)
