### ISSUE TITLE
[BUG] Agent Repeat response

### ISSUE THREAD

**Issue by AdkinsHan** [FlowiseAI/Flowise#3640]
**Describe the bug**
After I downloaded a anent template "Software Team" from market and changed the chatmodel to ollama and then asked  some question, it kept repeating the output;
At first I thought it was a misconfiguration on my part, but when I removed the worker node to just one, the condition persisted, and then I limited the supervisor to 5, and then I got the other errors.

**To Reproduce**

1. Go to 'Marketplace'
2. Click on 'Software Team' then chose use this template 
3. delete other worker node then aks
4.  Repeat response appear

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/28820f9f-88df-459d-985f-8777e9341030)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [flowise@2.2.1](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%402.2.1)
-   OS: Linux
-   Browser chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
You can try other models and see. Each model performs differently. Smaller model might not works too well with supervisor worker.
