### ISSUE TITLE
Should VectorStores Document * connector be plural?

### ISSUE THREAD

**Issue by macasas** [FlowiseAI/Flowise#366]
**Describe the situation**
I am trying to use a Folder of Files, plus a Cheerio Webscraper connected to either Pinecone or Memory Vector store Document input connector.

**Problem**
When only Cheerio is connected it answers questions correctly, but when I then add Folder of files to same Document connector, it answers from Folder of Files, but can not longer answer from Cheerio.

Either Document is singular, in which case only allow a single connection, or it allows multiple connections so it should be Documents *

and even after all of that, why does the Cheerio information get lost after adding Folder of Files? Does it need to go through a different node somehow?

**Comment by HenryHengZJ** [comment]
are you using smtg like this? 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/a35b6a83-6058-4a81-bb79-3a95aeb355fa)

documents are plural, every docs are flattened out, see implementation [here](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/vectorstores/InMemory/InMemoryVectorStore.ts#L69)

**Comment by macasas** [comment]
Yes, just like that.  

I started with just the Cheerio and it answers the questions correctly, but then after adding the folder it says I doesn't know to those same questions.

I have been playing with it since and I'm getting varied results, caused most likely by my ignorance, but the same question gets different responses. I am trying to find the pattern in it all, and will let you know when the lightbuld goes on :-)
