### ISSUE TITLE
[FEATURE] Option to hide credentials UI/ prevent adding new credentials

### ISSUE THREAD

**Issue by danielstankw** [FlowiseAI/Flowise#3672]
**Describe the feature you'd like**
Add ability to hide `credentials` tab in the UI/ prevent adding new credentials.
I am setting up flowiseai to be used by multiple users, I want to define credentials for them but not let them add new ones

**Goal**
After setting up flowiseai, prevent user from adding any extra credentials.

**Comment by HenryHengZJ** [comment]
This is possible with enterprise version with RBAC and Workspaces: https://docs.flowiseai.com/using-flowise/workspaces#sharing-credential
