### ISSUE TITLE
[FEATURE] Allow me to branch from a condition agent

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#3675]
**Describe the feature you'd like**
It's possible to run multiple agent nodes in parallel if the branching starts at an agent node:

![image](https://github.com/user-attachments/assets/ffdb61e4-f5d6-46d5-b1a0-ddca203d5b1b)

[Debug Branching Agent Flow Agents(1).json](https://github.com/user-attachments/files/18083397/Debug.Branching.Agent.Flow.Agents.1.json)

But it doesn't work when I branch away directly from a condition agent node (error `Error buildAgentGraph - Error compile graph - Node agent1 is not reachable`):
![image](https://github.com/user-attachments/assets/70010664-49f6-4764-83f9-1cc4d2f2317f)

[Debug Branching Agent Flow Agents.json](https://github.com/user-attachments/files/18083386/Debug.Branching.Agent.Flow.Agents.json)

I want to be able to branch away from a condition agent without having to run an normal agent first.

**Comment by dentro-innovation** [comment]
OOOOh so I found the culprit: it's ChatAnthropic! When I use ChatOpenAI with the agent that generates images, it works.

ChatAnthropic often causes problems with sequential agents, related to https://github.com/FlowiseAI/Flowise/issues/3540

On Flowise 2.2.1 right now

**Comment by HenryHengZJ** [comment]
Closing this and move to #3540

**Comment by dentro-innovation** [comment]
but if we close this issue, we won't address the initial problem: `allow to branch from a condition agent`
