### ISSUE TITLE
[BUG] Flowise version 2.2.2 reports as version 2.2.1 in about section.

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#3679]
@HenryHengZJ : Flowise version 2.2.2 is reporting in About page as 2.2.1. [baseurl]/api/v1/version return 2.2.1 instead of 2.2.2. 

<img width="569" alt="image" src="https://github.com/user-attachments/assets/2ddf2c30-0cb6-4162-8221-ff1aa932cb5f">

<img width="163" alt="image" src="https://github.com/user-attachments/assets/ce3b177f-ba39-40cd-b296-7007780e153d">

**Comment by vijaykammili** [comment]
This happens with the flowiseai/flowise:2.2.2 docker image.

**Comment by mayphilc** [comment]
same problem here in k8s

**Comment by HenryHengZJ** [comment]
Can you try pulling the tag `latest` instead of tag `2.2.2` docker image?

**Comment by vijaykammili** [comment]
@HenryHengZJ Latest tag has the same issue.

**Comment by vijaykammili** [comment]
@HenryHengZJ  - Are you using docker-compose or docker? I tried to do this in runpod and a couple of other platforms and I still see 2.2.1. Also some of the new features are not enabled. For Ex: Assistants. 
![image](https://github.com/user-attachments/assets/2e8a2124-4d29-49ef-90ab-54e4db5cb2f4)

**Comment by ryanhalliday** [comment]
I'm seeing this for both latest and 2.2.2 (index digest c4bee64d40db5d088b99b9faa4daa9b1c2831bcce10deae69d483459b14c09a8) images.

Builds look like they went alright in CI so not sure what has happened here

**Comment by npnpatidar** [comment]
Having same problem.  I have used podman with both latest and 2.2.2 tag.

**Comment by huwtao** [comment]
![企业微信截图_17340710192363](https://github.com/user-attachments/assets/54a0483b-7e95-4b34-a621-cc584a48223c)
![企业微信截图_17340710685140](https://github.com/user-attachments/assets/526c49fd-2e8c-43a5-af81-9dbeb0acc836)

**Comment by artemdzyuba** [comment]
Confirm. Not updating to 2.2.2. Can downdate to any version like 2.2.0 but when updating, still moving to 2.2.1

**Comment by JustMrMendez** [comment]
i was about to pull my hair, I have the right version up, but the front end keeps thinking it's on 2.2.1

**Comment by sashlabs-cyber** [comment]
Same here. I tried both the latest as well as 2.2.2 tags both are pulling the 2.2.1 version.
<img width="397" alt="image" src="https://github.com/user-attachments/assets/5a3a3f4f-2646-409f-82ba-0b95310bdaf7" />
<img width="542" alt="image" src="https://github.com/user-attachments/assets/7ccb94e3-4a6d-4768-83e2-91705cdd3129" />

I am pulling the images from dockerhub.

**Comment by mayphilc** [comment]
works for me now, i had to change my image pull policy to always to force the re-pull, but it works now

**Comment by artemdzyuba** [comment]
> Confirm. Not updating to 2.2.2. Can downdate to any version like 2.2.0 but when updating, still moving to 2.2.1

Retried. Got fixed, now on 2.2.2

**Comment by vijaykammili** [comment]
Yes, looks like a new image was pushed to the docker hub. Thank you @HenryHengZJ
