### ISSUE TITLE
⚒️[FEATURE] Redis-Backed Chat Memory

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#369]
## Describe the feature you'd like
Redis-Backed Chat Memory
Docs: https://js.langchain.com/docs/modules/memory/examples/redis

## ✅Tasks
- [ ] Add Redis Memory node

## 🎯Acceptance Criteria
- [ ] Redis Memory node should be able to remember conversations

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Zep Memory](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/memory/ZepMemory/ZepMemory.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by ivalkshfoeif** [comment]
Hi @HenryHengZJ, I'd like to work on the issue.
