### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by dentro-innovation** [FlowiseAI/Flowise#3703]
**Describe the feature you'd like**
When I create a new Chat Node (ChatOpenAI, ChatAnthropic etc.) the default temperature is always 0.9 :

![image](https://github.com/user-attachments/assets/df5f5c42-d5db-4961-8129-5db92765fc56)

I believe most AI engineers work with temperatures much lower than 0.9, probably 0.0 - 0.3 . 

Every time I have to manually change the 0.9 temperature. Can we set it to 0.3 by default instead, or 0.5 ? 

I think this would also help newcomers, as 0.3 is easier to prompt than 0.9 .

**Comment by HenryHengZJ** [comment]
I think it depends on the user preference. Currently model default is set to 1 (https://platform.openai.com/docs/api-reference/chat/create#chat-create-temperature)

As this would involve changing all the chat models, and causing the node version to be outdated, we'll leave it as it is at the moment.
