### ISSUE TITLE
[BUG] White screen after clicking create-button in Tools

### ISSUE THREAD

**Issue by giuliage** [FlowiseAI/Flowise#3704]
**Describe the bug**
When I click on the button 'Create' in the section 'Tools' I get a white screen.

**To Reproduce**

1. Go to 'Tools'
2. Click on 'Create'
3. White screen appears
4. Browser console errors:
---
index-DEvqzCna.js:62 Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at r (CodeEditor-BBetQVRT.js:4:19676)
    at r (CodeEditor-BBetQVRT.js:4:19255)
    at r (CodeEditor-BBetQVRT.js:4:19255)
    at r (CodeEditor-BBetQVRT.js:4:19255)
    at V0 (CodeEditor-BBetQVRT.js:4:19869)
    at _d.resolve (CodeEditor-BBetQVRT.js:4:18373)
    at mt.create (CodeEditor-BBetQVRT.js:4:27502)
    at CodeEditor-BBetQVRT.js:18:82083
    at zp (index-DEvqzCna.js:62:24283)
    at fl (index-DEvqzCna.js:62:42409)
Bv @ index-DEvqzCna.js:62
FC.n.callback @ index-DEvqzCna.js:62
yS @ index-DEvqzCna.js:60
DS @ index-DEvqzCna.js:62
JC @ index-DEvqzCna.js:62
q4 @ index-DEvqzCna.js:62
t5 @ index-DEvqzCna.js:62
$a @ index-DEvqzCna.js:62
FS @ index-DEvqzCna.js:62
xa @ index-DEvqzCna.js:60
fl @ index-DEvqzCna.js:62
(anonymous) @ index-DEvqzCna.js:62
P @ index-DEvqzCna.js:47
q @ index-DEvqzCna.js:47Understand this errorAI
index-DEvqzCna.js:60 Uncaught Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at r (CodeEditor-BBetQVRT.js:4:19676)
    at r (CodeEditor-BBetQVRT.js:4:19255)
    at r (CodeEditor-BBetQVRT.js:4:19255)
    at r (CodeEditor-BBetQVRT.js:4:19255)
    at V0 (CodeEditor-BBetQVRT.js:4:19869)
    at _d.resolve (CodeEditor-BBetQVRT.js:4:18373)
    at mt.create (CodeEditor-BBetQVRT.js:4:27502)
    at CodeEditor-BBetQVRT.js:18:82083
    at zp (index-DEvqzCna.js:62:24283)
    at fl (index-DEvqzCna.js:62:42409)
---
**Expected behavior**
Page to start creating a Tool.

**Screenshots**
n/a

**Flow**
n/a

**Setup**

-   Installation [`pnpm start`]
-   Flowise Version [2.2.2]
-   OS: [Windows]
-   Browser [Chrome Version 131.0.6778.140 (Official Build) (64-bit)]

**Additional context**
Same behaviour on localhost:3000 as well as via public SSL URL

**Comment by HenryHengZJ** [comment]
can't replicate that, can you try `pnpm i`, `pnpm build-force` ?

**Comment by giuliage** [comment]
Hi, thanks for lookint at this.
Tried pnpm i, pnpm build-force but the problem remained.
Also tried

pnpm store prune
rm -rf node_modules pnpm-lock.yaml
pnpm install
pnpm build

but still the same issue. I attached my current pnpm-lock.yaml file (renamed to .txt)
[pnpm-lock.txt](https://github.com/user-attachments/files/18181619/pnpm-lock.txt).
Maybe it helps. Any other idea what I could do?

**Comment by giuliage** [comment]
Hi Henry
I now updated node 20.15.1->20.18.1 and npm 10.7.0 -> 10.8.2 (pnpm 9.15.0) , cloned/installed flowise 2.2.2 again and it works now.
