### ISSUE TITLE
[BUG] Flowsie 2.2.2 does not show Knowledge (Document Stores) in dropdown for Custom Assistants

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#3710]
@HenryHengZJ  - Flowsie version 2.2.2 does not show Knowledge (Document Stores) in dropdown for Custom Assistants. I've seen Leon show this on the youtube video but the dropdown isn't listing any doc stores that were created. 

Existing Document Store:
<img width="515" alt="image" src="https://github.com/user-attachments/assets/c262fc61-78c2-4d9c-8fdf-58a16c1dd12b" />

Custom Assistant:

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/f0221cbf-fdd7-4b96-97fe-e7a91b0b0b2c" />

**Comment by stekum** [comment]
Same over here - no knowledge stores are available for selection

**Comment by dip00dip** [comment]
I think the "Upserted" status on Document Store is required to make it visible in Assistant.  Means you need to "Process" first.

**Comment by HenryHengZJ** [comment]
> I think the "Upserted" status on Document Store is required to make it visible in Assistant.

that's correct, should've made it clearer. Will add to description!

**Comment by Ennazk** [comment]
Same issue still occurring here. Was this solved?
