### ISSUE TITLE
[BUG] assistant always error?

### ISSUE THREAD

**Issue by isikepalaku** [FlowiseAI/Flowise#3715]
While using Flowise via Docker, I created an assistant successfully. However, after chatting for some time, an error occurs when attempting to send a message. The error message displayed is:
### Error: predictionsServices.buildChatflow - Unauthorized.

**Steps to Reproduce**

1. Set up Flowise using Docker as described in the documentation.
2. Create an assistant/chatbot with a valid configuration.
3. Begin interacting with the assistant.
4. After some time, attempt to send another message.
5. Observe the error.

**Expected Behavior**
The chat should proceed without interruptions, and responses should be generated successfully.

**Actual Behavior**
An error occurs during the interaction, preventing further communication with the assistant. The following error message appears:
Error: predictionsServices.buildChatflow - Unauthorized.
![bug](https://github.com/user-attachments/assets/b71343b4-8890-409a-aeaa-2fbf22990ffd)

**Comment by HenryHengZJ** [comment]
can you check if you have any API key on the chatflow? if yes, try selecting No Authorization: 
![image](https://github.com/user-attachments/assets/3318afb6-a4a5-4ffe-9e48-4b6a3943fa43)

**Comment by LA-Gabriel** [comment]
This could be a bug in Flowise for already-created chatbot assistants. Fixed it by removing the old knowledge base & saving it, then re-upserting the chunks until they appeared in the knowledge base list, and then adding the knowledge base & saving it again. The Flowise error message didn't detect the issue in the knowledge base.
