### ISSUE TITLE
⚒️[FEATURE] JSONLines Loader

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#373]
## Describe the feature you'd like
JSONLines Loader Integration
Docs: https://js.langchain.com/docs/modules/indexes/document_loaders/examples/file_loaders/jsonlines

## ✅Tasks
- [ ] Add JSONLines Loader node

## 🎯Acceptance Criteria
- [ ] JSONLines Loader node should be able to load data from `.jsonl` file

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [JSON Loader](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Json/Json.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by ivalkshfoeif** [comment]
Hi @HenryHengZJ , I'd like to work on it.

**Comment by HenryHengZJ** [comment]
closing as merged
