### ISSUE TITLE
⚒️[FEATURE] Redis Vector Store Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#374]
## Describe the feature you'd like
Redis Upser and Load Existing Index Integration
Docs: https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/redis

## ✅Tasks
- [ ] Add Redis Upsert and Load Existing Index nodes

## 🎯Acceptance Criteria
- [ ] Redis nodes should be able to upsert embeddings and load existing index from Redis instance

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Pinecone Upsert](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/vectorstores/Pinecone_Upsert/Pinecone_Upsert.ts)
- [Pinecone Load Index](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/vectorstores/Pinecone_Existing/Pinecone_Existing.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by govind-kumarr** [comment]
@HenryHengZJ  I am working on #221  it will be easy for me to implement this. Can you assign this to me?

**Comment by HenryHengZJ** [comment]
@govind-kumarr thanks! do you have any issues working on qdrant integration that needs help?

**Comment by Kamleshpaul** [comment]
any update ?

**Comment by ggurjar333** [comment]
Can I TAKE this?

**Comment by vinodkiran** [comment]
Released in [v1.3.9](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.3.9)
