### ISSUE TITLE
[BUG] Marketplace is balnk

### ISSUE THREAD

**Issue by nurdol26** [FlowiseAI/Flowise#3740]
**Describe the bug**

**To Reproduce**

1. Go to ' localhost3000'
2. Click on '.marketplace'
4. See error blank page :
<img width="730" alt="image" src="https://github.com/user-attachments/assets/af96ab55-f63f-4917-88a1-9b4ef2e84ca2" />

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**

-   Installation [e.g. docker, `npx flowise start`, `pnpm start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
Which version of Flowise are you using? How are you installing it?

Refer to this for fix: https://github.com/FlowiseAI/Flowise/issues/3583
