### ISSUE TITLE
[BUG] documentStoreServices.splitIntoChunks - fetch failed

### ISSUE THREAD

**Issue by tangkunyin** [FlowiseAI/Flowise#3753]
**Describe the bug**
Test local **Unstructured File Loader** service with **Flowise local docker container**, and got an error: _documentStoreServices.splitIntoChunks - fetch failed_

**To Reproduce**

1. Add a new document store in http://localhost:3000/document-stores
2. Add document loader with **Unstructured File Loader**
3. Add required config to the form, **the field of Unstructured API URL**: http://127.0.0.1:8000/general/v0/general
4. Click Preview Chunks, and the error appeared

**Expected behavior**
No error and preview chunks correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/41eca62f-b8b4-4985-ae84-a87c1643ba9c)

**Payload data is**
```json
{
  "loaderId": "unstructuredFileLoader",
  "id": "c2b8355b-c6cf-42c5-8663-a46fe643ffc5",
  "storeId": "4edb4b25-b015-4475-8d79-36d2033790a1",
  "loaderName": "Unstructured File Loader",
  "loaderConfig": {
    "fileObject": "data:text/markdown;base64,IyBN...",
    "unstructuredAPIUrl": "http://127.0.0.1:8000/general/v0/general",
    "strategy": "auto",
    "encoding": "utf-8",
    "skipInferTableTypes": "[\"pdf\", \"jpg\", \"png\"]",
    "hiResModelName": "detectron2_onnx",
    "chunkingStrategy": "by_title",
    "ocrLanguages": "[\"eng\",\"cmn\"]",
    "sourceIdKey": "source",
    "coordinates": false,
    "xmlKeepTags": "",
    "includePageBreaks": true,
    "multiPageSections": true,
    "combineUnderNChars": "200",
    "newAfterNChars": "4000",
    "maxCharacters": "20000",
    "metadata": "",
    "omitMetadataKeys": "",
    "FLOWISE_CREDENTIAL_ID": ""
  },
  "previewChunkCount": 20
}
```
**There were no errors in flowise container logs**
![image](https://github.com/user-attachments/assets/30a46cb9-fc48-49e9-920f-d8b5af44c978)

**Related environment**

-  OS: macOS 15.2 
-  Flowise Version: 2.2.2
-  Browser: Chrome 131.x
-  Unstructured api service: 0.0.82, built with its source: https://github.com/Unstructured-IO/unstructured-api

**Additional context**
1. Have you checked the API server? Yes - **I have checked the Unstructured API server, but I found no request with it! I am sure that the api service worked well**
2. Have you refers to the official documents? Yes - But nothing about that: https://docs.flowiseai.com/integrations/langchain/document-loaders/unstructured-file-loader

Any feedback is greatful. 🙏 😊 🙌

**Comment by HenryHengZJ** [comment]
when you are running both flowise and unstructured on docker, you might have to change the base url to `http://host.docker.internal:8000`

https://docs.flowiseai.com/integrations/langchain/vector-stores/chroma#additional

**Comment by tangkunyin** [comment]
@HenryHengZJ That works! Thanks a lot 🙏
