### ISSUE TITLE
[FEATURE] Automatic generation of REST-API for data sync with vector stores

### ISSUE THREAD

**Issue by amersabag** [FlowiseAI/Flowise#380]
**Describe the feature you'd like**

I would like to have a REST-API automatically generated whenever I add a document loader of any type. This generated API should provide a way of upserting/deleting documents from the connected vector store on demand as a mean to synchronize the vector store connected to the document loader with the data of an external system.

This will prevent duplicating code between different systems just to use the same text splitter or setting meta data, and because of that, I was forced to move my code from Flowise to LangChain/Next.js system.

It would be nice to have a check box to enable/disable the API per document loader.

I am not sure if adding this to the document loader is the right way to do it, but it seems the most correct one. But maybe, it would be to have a new type of nodes specifically for generating these APIs while allowing the user to choose the text splitter they want, even without providing any data loader node.

**Additional context**

**Comment by HenryHengZJ** [comment]
Our doc sore API now available: https://docs.flowiseai.com/api-reference/document-store

You can add, sync, delete your data from vector store
