### ISSUE TITLE
[BUG] Chat does not stop to load and freezes

### ISSUE THREAD

**Issue by lost15** [FlowiseAI/Flowise#383]
Hello! when i ask a question to my txt document using gpt-3.5-turbo, the answer starts to appear but never ends, the chatbox stays with the loading circle spinning and i cant continue to ask questions.
Can someone help?

Thanks

**Comment by HenryHengZJ** [comment]
try clear the conversations, then do a simple `hello` to see if that works?

**Comment by lost15** [comment]
after clear, still freezing the chat for new conversations and keeps spinning the loading icon.
