### ISSUE TITLE
[BUG] Not able to use cURL on DigitalOcean

### ISSUE THREAD

**Issue by oskarkramarz** [FlowiseAI/Flowise#386]
After installing Flowise on my DigitalOcean droplet I'm not able to run API calls. Chat in Flowise works fine. I followed official [installation guide](https://docs.flowiseai.com/deployment/digital-ocean).

Command that I run in terminal (copied from Flowise dashboard):

`curl http://[MY_IP_ADDRESS]:3000/api/v1/prediction/d45395a3-3cc6-41f6-b887-df5229b79541 \
     -X POST \
     -d '{"question": "Hey, how are you?"}'
`

Error that I receive:

`Chatflow d45395a3-3cc6-41f6-b887-df5229b79541 first message not found%`

<img width="1132" alt="bug" src="https://github.com/FlowiseAI/Flowise/assets/16004001/aa126e6a-6bca-491d-ba92-19c74723fe36">

Anyone can help with this issue?

**Comment by HenryHengZJ** [comment]
hey @oskarkramarz sorry for the bug!

the fix will be pushed to the docker and npm tomorrow. For now you can have a simple `hello` message in the Flowise UI Chat, then call the API, it should work

**Comment by oskarkramarz** [comment]
Hello @HenryHengZJ, thanks for prompt reaction. 

Just to let you know: I followed your instruction and sent a simple `hello` message in Flowise UI Chat. After that, I made API call again, but responses are either out of context or I get errors. 

Below example response for second API call, after I sent `hello` message in Flowise UI Chat. For your information: my chatflow is just `Conversational Agent` template from marketplace, nothing complex. 

<img width="977" alt="bug2 2" src="https://github.com/FlowiseAI/Flowise/assets/16004001/6997d918-0a70-4aff-bf18-8779352051f1">

Thank you in advance for solving this - Flowise is a great software with huge potential.

**Comment by emrahtoy** [comment]
also related with #332

**Comment by HenryHengZJ** [comment]
@oskarkramarz issue should be resolved now in v1.2.13 with this PR - https://github.com/FlowiseAI/Flowise/pull/354

**Comment by oskarkramarz** [comment]
@HenryHengZJ I made an update and response `first message not found` is gone. However responses via API still are out of context or I get an error `400`.

Example response for first message to chatflow through cURL: 

<img width="1002" alt="bug-1" src="https://github.com/FlowiseAI/Flowise/assets/16004001/0c2ac9ec-5bad-4ace-8238-05b660897811">

And an error that I get after sending next messages: 

<img width="922" alt="bug-2" src="https://github.com/FlowiseAI/Flowise/assets/16004001/43945939-f6cd-4185-981c-2eab991ba531">
