### ISSUE TITLE
[BUG]The temperature tuning in the openAI LLM node with the arrow button can't stop

### ISSUE THREAD

**Issue by ivalkshfoeif** [FlowiseAI/Flowise#389]
**Describe the bug**
The temperature tuning in the openAI LLM node with the arrow button can't stop

**To Reproduce**
1. Create an open LLM node
2. click the arrow button in the temperature attribute
3. The increasing/decreasing of the temperature can't stop

**Expected behavior**
The temperature will be increased or decreased by a small value and stop.

**Screenshots**

https://github.com/FlowiseAI/Flowise/assets/61750044/66be8261-5176-4f5b-8130-3539492707f3

**Flow**

The number of temperature increases/decreases by 0.1 per click

**Setup**
-   Installation without docker
-   Flowise Version 1.2.12
-   OS: macOS
-   Browser chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
wow that's quite a bug! thanks for spotting that, will put up a fix!

**Comment by HenryHengZJ** [comment]
issue now fixed and pushed to v1.2.14
