### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 0bvio** [FlowiseAI/Flowise#395]
**Describe the bug**
Unable to run the app after entering "npx flowise start", giving me error code ERESOLVE unable to resolve dependency tree

**To Reproduce**
Not sure?

**Expected behavior**
It should run, I suppose.

**Screenshots**
# npm resolution error report

2023-06-22T22:07:11.449Z

Found: puppeteer@20.7.3
node_modules/puppeteer
  puppeteer@"^20.7.1" from flowise-components@1.2.14
  node_modules/flowise-components
    flowise-components@"*" from flowise@1.2.13
    node_modules/flowise
      flowise@"*" from the root project

Could not resolve dependency:
peerOptional puppeteer@"^19.7.2" from langchain@0.0.96
node_modules/langchain
  langchain@"^0.0.96" from flowise-components@1.2.14
  node_modules/flowise-components
    flowise-components@"*" from flowise@1.2.13
    node_modules/flowise
      flowise@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "puppeteer",
    "version": "20.7.3",
    "location": "node_modules/puppeteer",
    "dependents": [
      {
        "type": "prod",
        "name": "puppeteer",
        "spec": "^20.7.1",
        "from": {
          "name": "flowise-components",
          "version": "1.2.14",
          "location": "node_modules/flowise-components",
          "dependents": [
            {
              "type": "prod",
              "name": "flowise-components",
              "spec": "*",
              "from": {
                "name": "flowise",
                "version": "1.2.13",
                "location": "node_modules/flowise",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "flowise",
                    "spec": "*",
                    "from": {
                      "location": "/home/sly/.npm/_npx/8b95a19c5c9c8708"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  },
  "edge": {
    "type": "peerOptional",
    "name": "puppeteer",
    "spec": "^19.7.2",
    "error": "INVALID",
    "from": {
      "name": "langchain",
      "version": "0.0.96",
      "location": "node_modules/langchain",
      "dependents": [
        {
          "type": "prod",
          "name": "langchain",
          "spec": "^0.0.96",
          "from": {
            "name": "flowise-components",
            "version": "1.2.14",
            "location": "node_modules/flowise-components",
            "dependents": [
              {
                "type": "prod",
                "name": "flowise-components",
                "spec": "*",
                "from": {
                  "name": "flowise",
                  "version": "1.2.13",
                  "location": "node_modules/flowise",
                  "dependents": [
                    {
                      "type": "prod",
                      "name": "flowise",
                      "spec": "*",
                      "from": {
                        "location": "/home/sly0bvio/.npm/_npx/8b95a19c5c9c8708"
                      }
                    }
                  ]
                }
              }
            ]
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`] ?
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
first make sure you are on node >= 18.15.0 - `node -v`

then try reinstall `npm install -g flowise`

and start `npx flowise start`

**Comment by 0bvio** [comment]
What if I am on Node 18.16.1?

**Comment by 0bvio** [comment]
Never mind!  It works!
