### ISSUE TITLE
[BUG] Issue using Custom Tool

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#397]
**Describe the bug**
I get the following messages when test the chatbot using the custom tool:

"Cannot find module 'airtable'"

"I apologize for the inconvenience. It seems that there is an issue with accessing the Airtable module, which is required to retrieve data from the database.

To resolve this issue, please ensure that the Airtable module is properly installed and imported in the current environment. Additionally, make sure that you have the necessary permissions to access the Airtable database.

If you continue to experience difficulties, please provide more details about the specific environment or platform you are using, so that I can assist you further."

**To Reproduce**
I'm using the custom tool to to fetch record from Airtable

**Expected behavior**
I expect to be able to make queries against my Airtable table.

**Screenshots**

**Setup**
-   Installation [ Render.com `yarn; yarn build`, `yarn start`] Render
-   Flowise Version [e.g. 1.2.11]
-   OS: macOS M1
-   Browser Chrome

**Comment by HenryHengZJ** [comment]
you can't just import `airtable` package. You can import any built-in NodeJS [modules](https://www.w3schools.com/nodejs/ref_modules.asp) and [supported external libraries](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/src/utils.ts#L289).

https://docs.flowiseai.com/tools/custom-tool

**Comment by WizKid1968** [comment]
> you can't just import `airtable` package. You can import any built-in NodeJS [modules](https://www.w3schools.com/nodejs/ref_modules.asp) and [supported external libraries](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/src/utils.ts#L289).
> 
> https://docs.flowiseai.com/tools/custom-tool

Thanks for the response Henry. I didn't include node-fetch in my script, so that issue is gon but I'm running into another problem. I keep getting the following error:

Request failed with status code 400 and body {"error":{"message":"'content' is a required property - 'messages.7'","type":"invalid_request_error","param":null,"code":null}}
