### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'data') with Chroma VectorStore

### ISSUE THREAD

**Issue by saviorand** [FlowiseAI/Flowise#40]
**Describe the bug**
Getting `Cannot read properties of undefined (reading 'data')` error when using the Chroma Vector Store in any combination, e.g. in AutoGPT

**To Reproduce**

1. Use one of the marketplace examples or build a chatflow with Chroma
2. Try running the flow
3. Error is thrown

**Setup**

-   OS: MacOS, M1 chip

Are there any additional steps required to set up Chroma with Flowise? Not quite sure based on the onboarding

**Comment by HenryHengZJ** [comment]
Have you got Chroma running locally?

If not you'll have to clone the Chroma repo: `git clone https://github.com/chroma-core/chroma.git`
And start its docker container: `docker-compose up -d --build`

https://docs.trychroma.com/api-reference?lang=js

**Comment by kayue** [comment]
Running into same issue, Chroma already running at port 8000

**Comment by chungyau97** [comment]
@kayue are using mac os or linux? 
@saviorand could you check whether the docker image is running?
![image](https://user-images.githubusercontent.com/33013947/235355277-c1de7fea-cb08-4721-b16c-bc5b9f112bf7.png)

I could run it as shown below
![image](https://user-images.githubusercontent.com/33013947/235355230-a05c4af0-a8d0-4957-bb2d-ed393abe96cd.png)

**Comment by saviorand** [comment]
The chroma container is running and I can reach Chroma on port 8000, but having the same issue... My flow is on the screenshot:
![image](https://user-images.githubusercontent.com/37780080/235360191-06209a34-95d3-4cfa-afb5-6e99a39afd67.png)

**Comment by chungyau97** [comment]
> The chroma container is running and I can reach Chroma on port 8000, but having the same issue... My flow is on the screenshot: ![image](https://user-images.githubusercontent.com/37780080/235360191-06209a34-95d3-4cfa-afb5-6e99a39afd67.png)

I believe is not an error from `Chroma`, I will create a similar flow as you to investigate further.

**Comment by chungyau97** [comment]
@saviorand did you upsert your document into chroma? 
I'm able to run the same flow as you without encountering error.
![image](https://user-images.githubusercontent.com/33013947/235726619-0a0cd4d0-b6b7-484c-9ff9-521c719410d5.png)

**Comment by saviorand** [comment]
I did not upsert anything to Chroma, maybe that's why! Let me try it out

**Comment by Dojimanoryyu** [comment]
hi, i have similar problem, i did upsert docs into chroma and already start chroma docker container, but i cant see any ingestion progresss whatsoever and chat test will return error "Error: Request failed with status code 400". Any idea?

**Comment by HenryHengZJ** [comment]
We've identified a bug where if you run both Flowise and Chroma on docker, it will not work.

Are you guys running Flowise on docker? @kayue @Dojimanoryyu @saviorand ?

**Comment by Dojimanoryyu** [comment]
im running flowise via npx flowise start, it is chroma db that use docker. Also, i don't know how to check ingestion in chroma docker progress since it's not stated in the terminal.  For the pinecone one I can check via pinecone consol.

**Comment by sknightq** [comment]
I'm running Chroma locally, but there is a bug in Chroma.
[This is  the description of bug](https://github.com/hwchase17/langchainjs/issues/1311)

**Comment by alexk1919** [comment]
Hi, can I use a hosted Chroma instance or does it have to be local?

**Comment by HenryHengZJ** [comment]
you can add a url to Chroma node - https://github.com/FlowiseAI/Flowise/pull/151

**Comment by alexk1919** [comment]
Thank you... I see where I can make those modifications.

**Comment by saviorand** [comment]
> We've identified a bug where if you run both Flowise and Chroma on docker, it will not work.
> 
> Are you guys running Flowise on docker? @kayue @Dojimanoryyu @saviorand ?

Yes I run on Docker

**Comment by ill-yes** [comment]
> 

Lifting to chromadb 1.5.0 didnt fix the issue for me. Running it locally.

**Comment by pavanjava** [comment]
I am facing the same issue my "chromadb" is running in docker and ran the flowise as "npx flowise start", unable to figure out what could be the issue.
<img width="1402" alt="Screenshot 2023-06-09 at 5 48 26 PM" src="https://github.com/FlowiseAI/Flowise/assets/25398886/561ede3c-5110-4c1a-896b-e4638d31fe4d">

**Comment by aghasaadmohammad** [comment]
i am running flowise on local and I am running chroma db on docker but i get this error
![image](https://github.com/FlowiseAI/Flowise/assets/61001884/8a20aebb-c125-4057-a8cb-12f1f5b7c49d)

**Comment by Enophi** [comment]
> i am running flowise on local and I am running chroma db on docker but i get this error ![image](https://private-user-images.githubusercontent.com/61001884/274602335-8a20aebb-c125-4057-a8cb-12f1f5b7c49d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTcyNDcsIm5iZiI6MTcwMjMxNjk0NywicGF0aCI6Ii82MTAwMTg4NC8yNzQ2MDIzMzUtOGEyMGFlYmItYzEyNS00MDU3LWE4Y2ItMTJmMWY1YjdjNDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE3NDkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjOWQ0ZmFjY2ZmNzQ3NDIwY2NlMTFhNGYzOGZhYjM5YzMwNTRmYzMwMTdlNTNhY2NhZmFmZGE5ZmUyZjM0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eNKq_4rDWL7DKjd5LNU-6HqzrfNDxW9KuU1rJVHNYPs)

Hi! Just remove the trailing slash :)

**Comment by webconsulting** [comment]
Hi all, i was the same issue cause i'm embed docs with openai Embedding in a chroma collection and use the same collection with localai embedding.
When use a new collection only for localai embedding all is ok !
I hope this'll be helpful

**Comment by AlmaAROM** [comment]
Hi! anyone can help me?
 Cannot read properties of undefined (reading 'length') let me know

 
![youtubeflowise](https://github.com/user-attachments/assets/47bd722f-7304-42ec-bc7e-d33c09a32c1e)

**Comment by HenryHengZJ** [comment]
> Hi! anyone can help me? Cannot read properties of undefined (reading 'length') let me know
> 
> ![youtubeflowise](https://private-user-images.githubusercontent.com/3358301/352793016-47bd722f-7304-42ec-bc7e-d33c09a32c1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTA0MjcsIm5iZiI6MTcyNjc1MDEyNywicGF0aCI6Ii8zMzU4MzAxLzM1Mjc5MzAxNi00N2JkNzIyZi03MzA0LTQyZWMtYmM3ZS1kMzNjMDlhMzJjMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTlUMTI0ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjRhNWRhNWYyMTY5OTBmZmQwMDQ0ZDA4MzgxOGMzMDZhOTZkZjEzMTA1MTk0NjBkMDM1ZjEwMDc4MzZlYTBhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.N2jD-9EUeHcuc6aZRtr6Wc390oXT0hgYiKQH2lOypeo)

this is not related specifically to Chroma right?

For Chroma issue, seems like its resolved with correct setup. Closing
