### ISSUE TITLE
Docker - Arm64 support

### ISSUE THREAD

**Issue by Surgical17** [FlowiseAI/Flowise#401]
It seems like currently Arm64 is not supported as shown in response below:

`WARNING: The DATABASE_PATH variable is not set. Defaulting to a blank string.
WARNING: The EXECUTION_MODE variable is not set. Defaulting to a blank string.
Creating network "docker_default" with the default driver
Pulling flowise (flowiseai/flowise:)...
latest: Pulling from flowiseai/flowise
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`

I also see there is a Database Path and Execution mode in the .env but no details regarding its use.

**Comment by IMPranshu** [comment]
Built a docker image with multiple platform support using the original DockerFile.

https://hub.docker.com/repository/docker/impranshu/flowise-ai/tags?page=1&ordering=last_updated

Use the following command to build :
```
docker buildx build --platform linux/arm64,linux/amd64 --tag replace_with_with_your_dockername/flowise-ai:v1 --output "type=registry" .

```

**Comment by HenryHengZJ** [comment]
You can now pull from arm64 docker image in v1.2.14:
<img width="953" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/7de2ea55-03a8-4c4d-add0-135208bc7689">
