### ISSUE TITLE
[FEATURE] Save Chat Histories

### ISSUE THREAD

**Issue by scooter7** [FlowiseAI/Flowise#404]
Hi,

Is there a way to save the chat histories in Flowise interactions?

Also, is there a way to see the full code that the visual builder is creating behind the scenes?

Thanks!

**Comment by HenryHengZJ** [comment]
chat histories coming from embedded chat or API?

exporting full code is on the roadmap

**Comment by scooter7** [comment]
Hi Henry,

Great news about code exports being on the roadmap.

In terms of saving the chat histories, in an ideal world, I'd like to save each user question and chatbot response per session in a text or csv file that would be stored in my Github repository or in Google Drive.

Additionally, I wonder if you know of a way to require the user to provide full name and email address prior to asking questions.

Thanks!

**Comment by scooter7** [comment]
Henry,

I'm also curious if there is a way to host the chat widgets in a live hosting environment so that the active state isn't dependent upon being served by my localhost.

Thanks again!

**Comment by HenryHengZJ** [comment]
here's the docs on deployment - https://docs.flowiseai.com/deployment

as for saving chat messages, we will enable this feature soon.

for require the user to provide full name and email address prior to asking questions, this will have to implemented on your front end application

**Comment by scooter7** [comment]
Thanks!

**Comment by govind-kumarr** [comment]
> here's the docs on deployment - https://docs.flowiseai.com/deployment
> 
> as for saving chat messages, we will enable this feature soon.
> 
> for require the user to provide full name and email address prior to asking questions, this will have to implemented on your front end application

hey @HenryHengZJ  Can You elaborate more on this feature I would like to work on it. Currently, I am working on #374

**Comment by HenryHengZJ** [comment]
thanks @govind-kumarr for the volunteer! I've started working on this 😅

**Comment by scooter7** [comment]
Hi, I'm just curious when you think that this might be completed? Thanks!

**Comment by hisune** [comment]
I also need the embedded chat to save the chat history, after refreshing the page or jumping to other sub-pages the chat history is lost, there is a bad experience

**Comment by scooter7** [comment]
> for require the user to provide full name and email address prior to asking questions, this will have to implemented on your front end application

What files would I need to access in the repository to make the required changes?

Thanks!

**Comment by HenryHengZJ** [comment]
> Hi, I'm just curious when you think that this might be completed? Thanks!

we are estimating around 1-2 weeks. As we also want to include features where you can export the conversations and where they are coming from. 

for the full name and email address we are not providing this feature atm, if you are using Flowise as API, you will have to implement on your front end application

**Comment by scooter7** [comment]
Hi @HenryHengZJ ,

That sounds great and thanks for updating me!

Would you please tell me which files I'd need to edit to add the name and email fields on the front end? I'm new to typescript...

Thanks again!

**Comment by askprateek** [comment]
Hi, I went thru the docs and if you enable Zep Memory, then your flow will save the chat history using the `sessionId`.

https://docs.flowiseai.com/memory/zep-memory

**Comment by HenryHengZJ** [comment]
yeah for now you can retrieve chat history if you are using Long Term memory like Zep/Motorhead etc. Chat histories are stored on their side. For Flowise, we have to retrieve and display them.

As it gets more complicated when the chatflow is using different memory, different sessions, and chat messages can come from API/embed/UI, its taking longer than expected to implement the feature

**Comment by scooter7** [comment]
Thanks for the update, @HenryHengZJ !

**Comment by Cat-Vader** [comment]
I think Zep, might have solved a bigger aspect of this issue

**Comment by eple0030** [comment]
Hi @HenryHengZJ 

Great news! 
In my dreams, I would like to embed a chatbot in website and be able to collect session's histories through an API. Best

**Comment by FultonStDigital** [comment]
Hi @HenryHengZJ,

Reading into this chain and was wondering if there is a solution for this. I'd love to be able to see all the transcripts on my embed chats, it would be really useful. Do you have any updates?

**Comment by Cat-Vader** [comment]
zep memory  does this
