### ISSUE TITLE
[BUG]Error in start

### ISSUE THREAD

**Issue by qiansheng2** [FlowiseAI/Flowise#410]
**Describe the bug**
When I start in my Macbook, there is an error.
How to avoid this？

**To Reproduce**

Download and Install [NodeJS](https://nodejs.org/en/download) >= 18.15.0

Install Flowise

npm install -g flowise
Start Flowise

npx flowise start

**Expected behavior**
Start the server

**Screenshots**
Error message in my console：

Starting Flowise...
⚡️[server]: Flowise Server is listening at 3000
❌[server]: Error during Data Source initialization: QueryFailedError: SQLITE_READONLY: attempt to write a readonly database
    at Statement.handler (/Users/nick/Flowise/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:81:26)
    at Statement.replacement (/Users/nick/Flowise/node_modules/sqlite3/lib/trace.js:25:27)
    at Statement.replacement (/Users/nick/Flowise/node_modules/sqlite3/lib/trace.js:25:27) {
  query: `CREATE TABLE "tool" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "color" varchar NOT NULL, "schema" varchar, "func" varchar, "createdDate" datetime NOT NULL DEFAULT (datetime('now')), "updatedDate" datetime NOT NULL DEFAULT (datetime('now')))`,
  parameters: undefined,
  driverError: Error: SQLITE_READONLY: attempt to write a readonly database
  --> in Statement#all(undefined, [Function: replacement])
      at Database.<anonymous> (/Users/nick/Flowise/node_modules/sqlite3/lib/sqlite3.js:88:19)
      at Database.<anonymous> (/Users/nick/Flowise/node_modules/sqlite3/lib/sqlite3.js:20:19)
      at execute (/Users/nick/Flowise/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:62:46)
      at /Users/nick/Flowise/node_modules/typeorm/driver/sqlite/SqliteQueryRunner.js:103:19 {
    errno: 8,
    code: 'SQLITE_READONLY',
    __augmented: true
  },
  errno: 8,
  code: 'SQLITE_READONLY',
  __augmented: true

**Setup**
-> % node -v      
v18.16.1

**Comment by qiansheng2** [comment]
When I use ROOT user to start the server.
The error message dispeared.
But I can't enter the main screen of Flowise.
<img width="1748" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/5198358/948876e5-9944-4713-9028-d6b98cdfec0b">

**Comment by HenryHengZJ** [comment]
try uninstalling and reinstall npm, and reclone
```
git clone https://github.com/FlowiseAI/Flowise.git
cd Flowise
yarn install
yarn build-force
yarn start
```

**Comment by luoweb** [comment]
ERROR almost the same:
flowise:dev: [1] ❌[server]: Error during Data Source initialization: QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_chat_flow.isPublic
flowise:dev: [1]     at Statement.handler (/Users/block/code/llm/Flowise/node_modules/typeorm/src/driver/sqlite/SqliteQueryRunner.ts:113:26) {
flowise:dev: [1]   query: 'INSERT INTO "temporary_chat_flow"("id", "name", "flowData", "apikeyid", "createdDate", "updatedDate") SELECT "id", "name", "flowData", "apikeyid", "createdDate", "updatedDate" FROM "chat_flow"',
flowise:dev: [1]   parameters: undefined,
flowise:dev: [1]   driverError: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_chat_flow.isPublic] {
flowise:dev: [1]     errno: 19,
flowise:dev: [1]     code: 'SQLITE_CONSTRAINT'
flowise:dev: [1]   },
flowise:dev: [1]   errno: 19,
flowise:dev: [1]   code: 'SQLITE_CONSTRAINT'
flowise:dev: [1] }
flowise:dev: [0] 
flowise:dev: [0] 12:11:27 - Found 0 errors. Watching for file changes.

**Comment by luoweb** [comment]
> ERROR almost the same:
> flowise:dev: [1] ❌[server]: Error during Data Source initialization: QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_chat_flow.isPublic
> flowise:dev: [1] at Statement.handler (/Users/block/code/llm/Flowise/node_modules/typeorm/src/driver/sqlite/SqliteQueryRunner.ts:113:26) {
> flowise:dev: [1] query: 'INSERT INTO "temporary_chat_flow"("id", "name", "flowData", "apikeyid", "createdDate", "updatedDate") SELECT "id", "name", "flowData", "apikeyid", "createdDate", "updatedDate" FROM "chat_flow"',
> flowise:dev: [1] parameters: undefined,
> flowise:dev: [1] driverError: [Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: temporary_chat_flow.isPublic] {
> flowise:dev: [1] errno: 19,
> flowise:dev: [1] code: 'SQLITE_CONSTRAINT'
> flowise:dev: [1] },
> flowise:dev: [1] errno: 19,
> flowise:dev: [1] code: 'SQLITE_CONSTRAINT'
> flowise:dev: [1] }
> flowise:dev: [0]
> flowise:dev: [0] 12:11:27 - Found 0 errors. Watching for file changes.

the problem solved when configure DATABASE_PATH
cat packages/server/.env
DEBUG=true
DATABASE_PATH=/Users/block/code/data/.flowise
