### ISSUE TITLE
[BUG] web.js loads a non-existent livereload.js file

### ISSUE THREAD

**Issue by hisune** [FlowiseAI/Flowise#412]
**Describe the bug**
web.js loads a non-existent livereload.js file

**To Reproduce**
I have deployed the following code to my own website:
```
<script type="module">
    import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js"
    Chatbot.init({
        chatflowid: "MY CHATFLOW ID",
        apiHost: "http://MY_API_HOST",
    })
</script>
```
After refreshing my site, I see the chat button, but opening the chrome console, I see he he keeps trying to value the file livereload.js, which does not exist on my site, and port 35729 is also not open

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/7941669/009a9452-eeb2-4d25-bf1f-d95b5931d7bf)

**Flow**
![image](https://github.com/FlowiseAI/Flowise/assets/7941669/86a0aa76-ce9d-45b7-847f-2392088e6676)

**Setup**
-   Installation: npx flowise start
-   Flowise Version: [1.2.13](https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.2.13)
-   OS: Windows
-   Browser: Edge

**Comment by HenryHengZJ** [comment]
Does the embedded chat successfully send and receive message?

**Comment by hisune** [comment]
> Does the embedded chat successfully send and receive message?

The embedded chat function works fine, but the browser keeps spinning around to load this non-existent js file

**Comment by hisune** [comment]
The latest version of flowise-embed has solved this bug

**Comment by azzuwayed** [comment]
Version 1.4.5 still has the same issue. Not sure if this is a bug or misconfiguration during deployment. I can't find anything in the documentation or even in search engines about it.

I opened this discussion before finding your post https://github.com/FlowiseAI/Flowise/discussions/1380
