### ISSUE TITLE
[BUG]type error

### ISSUE THREAD

**Issue by comey246** [FlowiseAI/Flowise#414]
**Describe the bug**
the type of 'apikeyid' is 'string', but in database that @Column({ nullable: true }) is allowed, when I create a flow, the apikeyid is ‘null’， why the author allowed the ’apikeyid‘ is ‘null’ index of ‘’.

**To Reproduce**

1. Go to 'the chatflow'
2. Click on 'add chatflow' and save it
3. Click F12 and check the chatflow api in network
4. See the chatflow that the apikeyid is null

**Comment by HenryHengZJ** [comment]
thanks will update it to optional string 👍

**Comment by HenryHengZJ** [comment]
issue fixed - https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/entity/ChatFlow.ts
