### ISSUE TITLE
[BUG]Error in reading json and csv files

### ISSUE THREAD

**Issue by Studying-365** [FlowiseAI/Flowise#421]
**Describe the bug**
I find a chart with QA conversational retrieval chain cannot read csv and json files correctly.

**To Reproduce**

1. I use chatgpt to create 10 random transactions
2. put them into a csv file and json file
3. put it into a chart and ask 'how many transactions are there?'
4. It tells me 4

Thank you for developing FlowiseAI! It is really a useful tool and I hope the problem can be fixed soon.

**Comment by govind-kumarr** [comment]
@Studying-365 Thank you for informing. I will check it. can you share any screenshots?

**Comment by Studying-365** [comment]
> @Studying-365 Thank you for informing. I will check it. can you share any screenshots?

Thank you for your reply! Please find the attached screenshot. I also tried other CSV files, and the error persists.

![Screenshot 2023-06-26 144900](https://github.com/FlowiseAI/Flowise/assets/112904166/ebd5c64a-78bd-4d02-be21-19d525d44ba8)
![Screenshot 2023-06-26 144920](https://github.com/FlowiseAI/Flowise/assets/112904166/c6ce7c4c-fcd1-4b0f-8572-1c4c009f6d43)
![Screenshot 2023-06-26 144839](https://github.com/FlowiseAI/Flowise/assets/112904166/c2743a5a-7574-4bd4-850f-b5f4a434a5c3)

**Comment by govind-kumarr** [comment]
![testing-csv](https://github.com/FlowiseAI/Flowise/assets/106414173/06f73e8f-2703-46b4-af7b-68e49ffafb1f)
You will need to increase the number of K i.e. Context. The default value of context is 4 hence LLM is responding with 4.

**Comment by Studying-365** [comment]
> @Studying-365 You will need to increase the number of K i.e. Context. The default value of context is 4 hence LLM is responding with 4.

Thank you so much for helping me solve the problem!
