### ISSUE TITLE
[BUG] embed code configuration doesnt show up

### ISSUE THREAD

**Issue by michaelkaspy** [FlowiseAI/Flowise#426]
i am on localhost, windows...when i click on embed code i dont have the checkbox the display the code configuration in order to customize it. 
i have a "show input config" for python, javascript and curl, but not for embed

**Comment by chungyau97** [comment]
Hi there, 

do you mean you do not have this in your `embed code` tab?
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/a4a41882-031b-4da5-b77f-bc83f944709b)
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/8e6fe861-945a-4ea2-8d96-cb482b4afba0)

**Comment by michaelkaspy** [comment]
Hello,

Exactly.. Also i dont have the 4 sub titles (pop-up html, fullpage html
etc...)
And i dont have share chatbot

I have updated my installation of flowise using the command box (i haven't
restarted my computer yet).

Do u know where it comes from and what i should do?

Le mer. 28 juin 2023 à 13:17, Ong Chung Yau ***@***.***> a
écrit :

**Comment by chungyau97** [comment]
If you're running it on `npx/docker` got to wait for the new release.
