### ISSUE TITLE
[BUG] ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response

### ISSUE THREAD

**Issue by ljubarskij** [FlowiseAI/Flowise#43]
**Describe the bug**
From the exception it seems like a bug on pinecone side, but I did not find a solution online, so maybe you can help... I followed your tutorial on youtube 1:1 (pdf, openai embeddings, pinecone, conversational QA chain)

**To Reproduce**
1. Setup the same configuration as on your youtube video
2. save
3. open chat window
4. ask questions

**Expected behavior**
Should work without exception

**Screenshots**
![image](https://user-images.githubusercontent.com/3154404/235324480-26a1096a-3d5e-4239-a89e-e64cbcdc11df.png)

**Setup**

-   OS: Windows 10 Home
-   Browser: Chrome Version 112.0.5615.138 (Official Build) (64-bit)

**Additional context**
I am blown away by this simple and concise UI and the 2 minute youtube tutorial... keep it up!

**Comment by HenryHengZJ** [comment]
Hey @ljubarskij! Sorry for the confusion, should've explained it in the video.

You'll have to first create a Pinecone index at https://app.pinecone.io/organizations
It must have 1536 dimensions, to match the OpenAI embedding size.
It should use the metric "cosine" to get the results below.

![image](https://user-images.githubusercontent.com/26460777/235327634-4c1a3891-af43-4f59-ab88-4ddfbb931481.png)

**Comment by ljubarskij** [comment]
Got it. I had only 1024 dimensions. Thank you for the quick answer!

**Comment by ljubarskij** [comment]
Unfortunately it did not help :(

**Comment by HenryHengZJ** [comment]
@ljubarskij any luck? Recommend try creating new index, new api key similar to the screenshot above and see

**Comment by choigawoon** [comment]
it doesn't work
