### ISSUE TITLE
[BUG] NumericUpDown temperature control sticks on a single click

### ISSUE THREAD

**Issue by vertigoa** [FlowiseAI/Flowise#436]
**Describe the bug**
The NumericUpDown temperature control sticks on a single click, rapidly incrementing values. 

**To Reproduce**

1. Go to 'ChatOpenAi node Temperature Setting.'
2. Click on NumericUpDown control once, up arrow or down arrow.
3. Notice that it may rapidly increase or decrease values more than one means to.

**Expected behavior**
Increment value by a single unit.

**Screenshots**
https://drive.google.com/file/d/1CAn4UBaVkfDyTqstE70yu9mBggVrRcXy/view?usp=sharing

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation  docker
-   Flowise Version1.2.13
-   OS:  Windows 10
-   Browser chrome, edge

**Additional context**

**Comment by HenryHengZJ** [comment]
PR for the fix was merged - https://github.com/FlowiseAI/Flowise/pull/406, will be pushed to new release in a few days

**Comment by HenryHengZJ** [comment]
should be fixed in v1.2.14
