### ISSUE TITLE
[FEATURE] Table Analyzer Plugin

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#437]
**Describe the feature you'd like**
Table Analyzer Plugin: Enable your LLM to perform numerical analysis on tables for you (from Excel or CSVs). 
Connect a Table Analyzer plugin and compute averages, std. deviations, differences, and summations.

**Additional context**
This is very important! Still waiting on an Airtable solution. There's a need for tabular data to be analyzed, but this feature seems to be ignored.

**Comment by HenryHengZJ** [comment]
because langchainjs doesnt yet have native integration with airtable - https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/ so thats why its taking us more time to develop. For tabular data, have you tried CSV loader?

**Comment by WizKid1968** [comment]
@HenryHengZJ  CSV loader isn't very good. It's a struggle to get the right information out of it. Maybe my parameters are set correctly. It would help if there we Docs explicitly detailing the nodes and its required parameters.

**Comment by HenryHengZJ** [comment]
yeah we will definitely improve the docs. In the meantime you can refer to langchain docs - https://js.langchain.com/docs/modules/indexes/document_loaders/examples/file_loaders/csv

**Comment by chungyau97** [comment]
@WizKid1968 do checkout #421 to increase the performance of CSV suggested by @govind-kumarr

**Comment by WizKid1968** [comment]
> @WizKid1968 do checkout #421 to increase the performance of CSV suggested by @govind-kumarr

Ah ok, it makes a lot more sense now. Thank you. 
I look forward for a complete documentation, it will probably solve the majority of the users issues.
