### ISSUE TITLE
no chat option 

### ISSUE THREAD

**Issue by text2sql** [FlowiseAI/Flowise#44]
i can't enter anything into a chat window 
<img width="2204" alt="Screenshot 2023-04-29 at 7 07 48 PM" src="https://user-images.githubusercontent.com/127912312/235327659-47fce886-ec0e-45e2-9214-b82e31c6a1ca.png">

**Comment by text2sql** [comment]
never mind : -) apparently i should click "save" button first

**Comment by HenryHengZJ** [comment]
Have you saved the chat?

**Comment by text2sql** [comment]
what is the right prompt schema if i want it to answer history questions as a history teacher? :-)

**Comment by HenryHengZJ** [comment]
you can find a list of prompts here: https://github.com/f/awesome-chatgpt-prompts/blob/main/prompts.csv

**Comment by text2sql** [comment]
The thing { } is the one I am asking in the chat , correct?

**Comment by HenryHengZJ** [comment]
Yes, when there is a `{variable}` in the prompt, it will be the chat input. 
When there are multiple `{variable}`, thats when you have to use `Format Prompt Values` to specify the values for other `{variable}`.

However in your case, I think you don't need the `{variable}`. Here's the example prompt that I tested: 
`I want you to act as a mathematical history teacher and provide information about the historical development of mathematical concepts and the contributions of different mathematicians. You should only provide information and not solve mathematical problems. Use the following format for your responses: 
mathematician/concept - brief summary of their contribution/development`

![image](https://user-images.githubusercontent.com/26460777/235328208-2eff1cc9-3a03-4448-8e54-5a4fa581da22.png)

**Comment by text2sql** [comment]
That’s awesome , thank you so much !On Apr 29, 2023, at 7:31 PM, Henry Heng ***@***.***> wrote:﻿
Yes, when there is a {variable} in the prompt, it will be the chat input.
When there are multiple {variable}, thats when you have to use Format Prompt Values to specify the values for other {variable}.
However in your case, I think you don't need the {variable}. Here's the example prompt that I tested:
I want you to act as a mathematical history teacher and provide information about the historical development of mathematical concepts and the contributions of different mathematicians. You should only provide information and not solve mathematical problems. Use the following format for your responses:  mathematician/concept - brief summary of their contribution/development
