### ISSUE TITLE
[BUG] Error: Azure OpenAI API instance name not found

### ISSUE THREAD

**Issue by tonygenai** [FlowiseAI/Flowise#446]
Running it locally on localhost:3000 with nodejs at version 18.10 and trying any of the templates in the marketplace I am getting this error in the chat Error: Azure OpenAI API instance name not found and in the terminal I am getting
npx flowise start     
Starting Flowise...
⚡️[server]: Flowise Server is listening at 3000
📦[server]: Data Source has been initialized!
Error: Azure OpenAI API instance name not found
    at new ChatOpenAI (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/chat_models/openai.cjs:239:23)
    at ChatOpenAI_ChatModels.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/chatmodels/ChatOpenAI/ChatOpenAI.js:139:23)
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:212:72)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:611:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:362:13

Can you help with that please?

**Comment by tonygenai** [comment]
Sure 

1. Git cloned the repo
2. In the flowise directory npm install -g flowise
3. After installing in the same directory npx flowise start
4. http://localhost:3000
5. From the Marketplace create a conversational AI but any other gave me the same error
6. Screenshot
![image](https://github.com/FlowiseAI/Flowise/assets/137122489/514d1727-0104-4f45-a2fe-616405e9e997)

**Comment by HenryHengZJ** [comment]
you dont have to clone the repo if you are using npx flowise start.

just follow the quick guide - https://github.com/FlowiseAI/Flowise#quick-start and make sure you are above node >= 18.15.0

**Comment by tonygenai** [comment]
Sorry - but has the same error I completely delete the directory and didn't cloned the repo but it's the same thing in Azure Web app works perfect getting the image from docker

**Comment by tonygenai** [comment]
Correction now also in Azure I have the same problem
![image](https://github.com/FlowiseAI/Flowise/assets/137122489/ed9487f3-542c-428f-9f26-5e890707f4e3)

**Comment by govind-kumarr** [comment]
> Correction now also in Azure I have the same problem ![image](https://user-images.githubusercontent.com/137122489/249986225-ed9487f3-542c-428f-9f26-5e890707f4e3.png)

You have not entered the open AI API key in the embedding node.

**Comment by tonygenai** [comment]
Good call - Thank you but still not working in localhost.
