### ISSUE TITLE
multiple files

### ISSUE THREAD

**Issue by text2sql** [FlowiseAI/Flowise#47]
is there a way to add multiple files/urls?

**Comment by HenryHengZJ** [comment]
Not for now, working on them!

**Comment by text2sql** [comment]
so the main purpose is to visualize and test it out and then write python code by hand? or can i see the code somewhere?

**Comment by chungyau97** [comment]
> is there a way to add multiple files/urls?

Regarding on multiple files we have already merge it to `main` branch

**Comment by HenryHengZJ** [comment]
For python, you can use [Langflow](https://github.com/logspace-ai/langflow), Flowise is built on JS/TS

**Comment by text2sql** [comment]
> For python, you can use [Langflow](https://github.com/logspace-ai/langflow), Flowise is built on JS/TS

You showed the option to embed the code in the last webinar, is it in the works?

**Comment by HenryHengZJ** [comment]
Yep, but it will be in JS/TS code. Will be available in next few releases, feel free to join the [Discord](https://discord.gg/jbaHfsRVBW) channel to get updated :)
