### ISSUE TITLE
[FEATURE] Can the system support multiple account logins?

### ISSUE THREAD

**Issue by shaowin16** [FlowiseAI/Flowise#472]
**Describe the feature you'd like**
A clear and concise description of what you would like Flowise to have.

**Additional context**

**Comment by HenryHengZJ** [comment]
not yet, for now is still single user based. Multi tenant is definitely on the roadmap!

**Comment by shaowin16** [comment]
已收到，谢谢！

**Comment by govind-kumarr** [comment]
> not yet, for now is still single user based. Multi tenant is definitely on the roadmap!

is anyone working on it?

**Comment by shaowin16** [comment]
@HenryHengZJ  When will it be finished？

**Comment by tyarhlan** [comment]
Hi @HenryHengZJ,

Any idea on the target date? Apology in advance for chasing.

Thanks

**Comment by touhi99** [comment]
> Hi @govind-kumarr,
> 
> Yup, @HenryHengZJ is currently working on it.

is it already here or being implemented currently? @HenryHengZJ  sorry for the tag

**Comment by HenryHengZJ** [comment]
@touhi99 not yet 😄

**Comment by gitgrooves** [comment]
_What do we want..._

### **### multiple account logins!!**

_When do we want it..._

### **### NOW!!** 

please!! 😄

**Comment by HenryHengZJ** [comment]
Now supported on enterprise and cloud pro plan - https://docs.flowiseai.com/using-flowise/workspaces

**Comment by shaowin16** [comment]
已收到，谢谢！
