### ISSUE TITLE
[BUG]embed bubblechat's anwser is different from the flowchat's anwser

### ISSUE THREAD

**Issue by wangfengyuan** [FlowiseAI/Flowise#473]
**Describe the bug**

when test the QA chat in flowchat, it works well
<img width="1356" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/30677408/e35450bf-92fa-48a4-856b-0ec67d3d4516">

but when I embed in my personal blog website, use the same question, Its response is not as accurate as the one above.
<img width="1208" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/30677408/7ae66f19-d863-45ef-8fc6-f524bc3e2dd1">
```
import { BubbleChat } from "flowise-embed-react";

const Chatbot = () => {
  return (
    <BubbleChat
      chatflowid="eddfac63-bcc5-4c3b-ab68-e1eaa2f8c5e2"
      apiHost="https://flowise.codefe.top"
    />
  );
};
```

so, what's the problem, What did I miss?

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
seems to be the same in https://github.com/FlowiseAI/Flowise/issues/332

tried replicating but couldnt. will have a deeper look since quite a few having the same problem.

do you have a simple example where I can test? 中文也可以

**Comment by wangfengyuan** [comment]
> 
here is an example

**Comment by wangfengyuan** [comment]
> seems to be the same in #332
> 
> tried replicating but couldnt. will have a deeper look since quite a few having the same problem.
> 
> do you have a simple example where I can test? 中文也可以

sure, here is an example 
1、use this [flowise flow](https://cos.codefe.top/flowise-chatflow/minimal-reproduction%20Chatflow.json) and the [source document file](https://cos.codefe.top/flowise-chatflow/blog-ai-chat.md) , use the same question: Flowise是什么，如何安装使用
2、test in flowsie workflow
3、test in embed bubble chat for example https://stackblitz.com/edit/web-platform-1efehx?file=index.html

my test results:
<img width="500" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/30677408/19a9fbd6-933d-4833-aacc-aae417ac6d8c">
logs
```
[llm/start] [1:chain:ConversationalRetrievalQAChain > 2:chain:StuffDocumentsChain > 3:chain:LLMChain > 4:llm:ChatOpenAI] Entering LLM run with input: {
  "messages": [
    [
      {
        "type": "human",
        "data": {
          "content": "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\n# 自部署\n\n使用`Flowise`很简单，注意：`node`要求是最新版`18`\n\n```jsx\nnpm install -g flowise\nnpx flowise start\n\n# `Flowise`介绍\n\n[Flowise](https://flowiseai.com/)是基于🦜️🔗 `LangChainJS`构建的可免费供商业和个人使用的免费开源项目，它有着一个非常易用的图形用户界面，旨在让人们轻松地可视化和构建`LLM`应用程序，也就是`nocode`开发`LLM`应用。类似的工具比这个还早的有[`langflow`](https://github.com/logspace-ai/langflow)，但是因为`Flowise`它有着好看的`UI`界面以及这个项目就是`js`开发的，因此我选择`Flowise`。举个例子，下面的应用程序展示了一个基本的翻译机器人，同时也演示了如何格式化提示值，而实现下面这个你只需要简单拖拽就可以完成。\n\n![Untitled](https://cos.codefe.top/images/flowise-translateflow-demo.png)\n\n而本文要构建网站聊天机器人，本质上和很常见的与已有pdf或者doc文档对话原理是一致的，这里引用[一篇文章](https://towardsdatascience.com/all-you-need-to-know-to-build-your-first-llm-app-eb982c78ffac)的示例图片\n\n![https://miro.medium.com/v2/resize:fit:1400/format:webp/1*njagJOgiT-VTJjQ18bugcw.png](https://miro.medium.com/v2/resize:fit:1400/format:webp/1*njagJOgiT-VTJjQ18bugcw.png)\n\n本质上原理大致是：\n\n- 将源文件切成多个文本片段，创建**`Embeddings`** 然后存到向量数据库\n- 将用户提问也创建**`Embeddings`** ，将它和上一步创建好的向量对比，通过相近搜索找到最相关的文本片段，它的特点是能发现文本相关性，比如汽车和公路\n- 把问题和历史聊天还有相关片段一起发送给`**LLM**`它便能从中总结出回答\n\n# 自部署\n\n使用`Flowise`很简单，注意：`node`要求是最新版`18`\n\n```\n\n执行上面命令后，打开 [http://localhost:3000](http://localhost:3000/) 就可以使用了，但是如果是生产环境使用，就需要自己部署一份了，[官方文档](https://docs.flowiseai.com/)提供了多种部署方式，包括[Render](https://docs.flowiseai.com/deployment/render)、[Railway](https://docs.flowiseai.com/deployment/railway)、[Replit](https://docs.flowiseai.com/deployment/replit)等云服务商各自部署方式，对于无服务器可以尝试下。\n\n> 如果是使用云服务商部署，因为项目使用了`SQLite`，所以需要查阅其文档了解持久化数据的方式，避免服务在重启时数据部分数据丢失，同时向量数据库也推荐也使用云服务商的比如[`Supabase pgvecto](https://supabase.com/docs/guides/database/extensions/pgvector)r`或者[`pinecone](https://www.pinecone.io/)`\n> \n\n因为我有腾讯云服务器，并且上面提到的`suapabase`与`pinecone`会在你一周没有使用或者说是没有请求调用时，会关闭或者或删除你数据库，所以这里我直接使用docker自己部署，首先`clone`代码\n\n```bash\ngit clone https://github.com/FlowiseAI/Flowise.git\n```\n\n进入`docker`目录，创建`.env`文件，并填入下面环境变量，其中`port`是服务暴露端口，用户名和密码是为网页访问添加认证\n\n```bash\nPORT=3000\nFLOWISE_USERNAME=admin\nFLOWISE_PASSWORD=你的密码\n```\n\n然后在这个`docker`目录执行下面命令启动，我的是`docker`最新版，因此和文档有点小区别\n\n```bash\ndocker compose up -d\n\n![Untitled](https://cos.codefe.top/images/flowise-embed-desc.png)\n\n同时也提供了API的调用方式，那么你可以结合自己场景，赋予了更高的自由度。\n\n![Untitled](https://cos.codefe.top/images/flowise-api-integration.png)\n\n但是从它的`github`上可以找到其实有一个对应的`[React`版本的`npm`包](https://github.com/FlowiseAI/FlowiseEmbedReact)的\n\n```bash\npnpm install flowise-embed flowise-embed-react\n\nQuestion: Flowise是什么，如何安装使用\nHelpful Answer:",
          "additional_kwargs": {}
        }
      }
    ]
  ]
}
```
<img width="500" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/30677408/dd108a25-2c9e-40d8-b2c7-abdb5ba06856">

```
[llm/start] [1:chain:LLMChain > 2:llm:ChatOpenAI] Entering LLM run with input: {
  "messages": [
    [
      {
        "type": "human",
        "data": {
          "content": "Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.\n\nChat History:\nAssistant: Hi there! How can I help?\nHuman: Flowise是什么，如何安装使用\nFollow Up Input: Flowise是什么，如何安装使用\nStandalone question:",
          "additional_kwargs": {}
        }
      }
    ]
  ]
}
[llm/end] [1:chain:ConversationalRetrievalQAChain > 2:chain:LLMChain > 3:llm:ChatOpenAI] [3.52s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": "What is Flowise and how do I install and use it?",
        "message": {
          "type": "ai",
          "data": {
            "content": "What is Flowise and how do I install and use it?",
            "additional_kwargs": {}
          }
        }
      }
    ]
  ],
  "llmOutput": {
    "tokenUsage": {
      "completionTokens": 13,
      "promptTokens": 78,
      "totalTokens": 91
    }
  }
}
[llm/end] [1:chain:LLMChain > 2:llm:ChatOpenAI] [3.52s] Exiting LLM run with output: {
  "generations": [
    [
      {
        "text": "What is Flowise and how do I install and use it?",
        "message": {
          "type": "ai",
          "data": {
            "content": "What is Flowise and how do I install and use it?",
            "additional_kwargs": {}
          }
        }
      }
    ]
  ],
  "llmOutput": {
    "tokenUsage": {
      "completionTokens": 13,
      "promptTokens": 78,
      "totalTokens": 91
    }
  }
}
[chain/end] [1:chain:ConversationalRetrievalQAChain > 2:chain:LLMChain] [3.52s] Exiting Chain run with output: {
  "text": "What is Flowise and how do I install and use it?"
}
[chain/end] [1:chain:LLMChain] [3.52s] Exiting Chain run with output: {
  "text": "What is Flowise and how do I install and use it?"
}
```

i found in embed chat case my question is auto translated into: What is Flowise and how do I install and use it?

**Comment by HenryHengZJ** [comment]
@wangfengyuan thanks for the step by step guide, that really helps to replicate and identified the issue!

In short, the issue should be fixed. Update your repository (git pull or sync fork) and use the latest embed version: `https://cdn.jsdelivr.net/npm/flowise-embed@1.0.11/dist/web.js`.

What was the issue?
1.) From ChatEmbed side, the first message (Flowise是什么，如何安装使用) was sent as `chat_history`, causing the LLM to rephrase the question to English. This [PR](https://github.com/FlowiseAI/FlowiseChatEmbed/pull/17) fixed that

2.) From Flowise side, the prompt used for ConversationalRetrievalQAChain was modified to tell LLM to rephrase in its original language, and an additional question generator prompt is used, [PR](https://github.com/FlowiseAI/Flowise/pull/516/files#diff-e0edb40536df9ed321a73ab3911ccba4f459a061d817ae7a825b4e2c0078f4e6)

Combining these 2 PRs, I can see improvement and much stable response from the chain.

Try that and let me know if that resolves the issue.

**Comment by wangfengyuan** [comment]
> @wangfengyuan thanks for the step by step guide, that really helps to replicate and identified the issue!
> 
> In short, the issue should be fixed. Update your repository (git pull or sync fork) and use the latest embed version: `https://cdn.jsdelivr.net/npm/flowise-embed@1.0.11/dist/web.js`.
> 
> What was the issue? 1.) From ChatEmbed side, the first message (Flowise是什么，如何安装使用) was sent as `chat_history`, causing the LLM to rephrase the question to English. This [PR](https://github.com/FlowiseAI/FlowiseChatEmbed/pull/17) fixed that
> 
> 2.) From Flowise side, the prompt used for ConversationalRetrievalQAChain was modified to tell LLM to rephrase in its original language, and an additional question generator prompt is used, [PR](https://github.com/FlowiseAI/Flowise/pull/516/files#diff-e0edb40536df9ed321a73ab3911ccba4f459a061d817ae7a825b4e2c0078f4e6)
> 
> Combining these 2 PRs, I can see improvement and much stable response from the chain.
> 
> Try that and let me know if that resolves the issue.
> 
> Changes will be pushed to next release, so if you are using docker/npm you wont be able to see the changes yet. Only if you are running `yarn start` locally, or have a forked branch

it works well now, the problem has gone and this issue can be closed now, BTW, the project is amazing, I can not believe AI application can be built in such an easy way, you are doing a great job,thank you
