### ISSUE TITLE
Building Docker Image in Main Repo [BUG]

### ISSUE THREAD

**Issue by inayet** [FlowiseAI/Flowise#476]
**Describe the bug**
Building local docker image installs deprecated packages with dependency issues. 

**To Reproduce**
cd into flowise and run 'podman build --no-cache -t flowise .'

Errors upon errors are produced, plus consistently get message about network issues, however, have network access...

'warning workspace-aggregator-7623eb15-e726-44a6-8b28-1ccee6aab77f > flowise-ui > react-scripts > css-minimizer-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning workspace-aggregator-7623eb15-e726-44a6-8b28-1ccee6aab77f > flowise-ui > react-scripts > jest > @jest/core > jest-runner > jest-environment-jsdom > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
warning workspace-aggregator-7623eb15-e726-44a6-8b28-1ccee6aab77f > flowise-ui > react-scripts > workbox-webpack-plugin > workbox-build > @surma/rollup-plugin-off-main-thread > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
warning @qdrant/js-client-rest@1.3.0: The engine "pnpm" appears to be invalid.
warning @qdrant/openapi-typescript-fetch@1.2.1: The engine "pnpm" appears to be invalid

**Comment by IMPranshu** [comment]
Are you able to build the docker image?

I built a docker image with amd64 and arm64 yesterday successfully.
https://hub.docker.com/repository/docker/impranshu/flowise-ai/tags?page=1&ordering=last_updated

**Comment by HenryHengZJ** [comment]
`v1.2.14` is now released. try and see if that works

**Comment by inayet** [comment]
Hi guys, thank you for responding. I updated my repository, in building from the Dockerfile in the root folder, I am getting errors :

 is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning workspace-aggregator-b1d10517-fb8f-4619-9aa8-31e2070ccce7 > flowise-ui > react-scripts > jest > @jest/core > jest-config > jest-environment-jsdom > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
warning workspace-aggregator-b1d10517-fb8f-4619-9aa8-31e2070ccce7 > flowise-ui > react-scripts > workbox-webpack-plugin > workbox-build > @rollup/plugin-replace > magic-string > sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...


Am going to try another installation method.

**Comment by Acsigen** [comment]
This is still an issue, I tried 1.5.0 and I get the following message when building the docker image:

```
warning @datastax/astra-db-ts@0.1.4: Unable to read "bin" directory of module "@datastax/astra-db-ts" 
=> => # info There appears to be trouble with your network connection. Retrying...
```
