### ISSUE TITLE
import 

### ISSUE THREAD

**Issue by text2sql** [FlowiseAI/Flowise#48]
sorry , how do i import the json schema into python? 
do i use your library?

**Comment by HenryHengZJ** [comment]
Currently we don't have Python integration

**Comment by text2sql** [comment]
How can I use the exported schema in json?

**Comment by chungyau97** [comment]
> How can I use the exported schema in json?

Here are some few use cases: 

1. Once `Flowise hosted version` is released, you can import your local schema in JSON.
2. Easier duplication of same schema with different documents, tuning, & credentials.
3. Easier migration between different local system such as different virtual machine.
