### ISSUE TITLE
[BUG] Inconsistent response from Embed and UI

### ISSUE THREAD

**Issue by Zenyker** [FlowiseAI/Flowise#486]
I create a Chatbot and its working fine, the chat bot chats in spanish fine, but when I copy the code to the html, it works but responds in English and it doesn't greet like he has to, in conversational retrieval QA Chain in system message I wrote the greeting but doesnt did it

**Comment by HenryHengZJ** [comment]
so you're saying it works fine on the Flowise UI, but not on the embedded html chat widget?

**Comment by Zenyker** [comment]
Yes,fot now  I am trying to write the system message in English to check if it works

**Comment by HenryHengZJ** [comment]
see here - https://github.com/FlowiseAI/Flowise/issues/473

**Comment by mibtim** [comment]
hi @HenryHengZJ mate hope all is well. 
just a quick questions to see when will be the next release for docker/npm (#473)?  cheers

**Comment by HenryHengZJ** [comment]
@mibtim am planning 19th/20th, will update

**Comment by mibtim** [comment]
sounds awesome @HenryHengZJ , thank you heaps for the msg. i will check after 20th and update.. tc

**Comment by HenryHengZJ** [comment]
pushed to 1.2.16, feel free to reopen if you still see the same
