### ISSUE TITLE
[BUG] Chat related workflows for LocalAI server

### ISSUE THREAD

**Issue by yarray** [FlowiseAI/Flowise#488]
First thanks for the excellent framework! It is very easy to use and promising. I have built several workflows with it using ChatGPT and am currently switching to LocalAI and open source models.

**Describe the bug**

Currently with a LocalAI backend Flowise can support single shot completion but not chat related workflows. I have observed:

What works:

Given template, using normal prompt node and connect to LLM chain.

![截屏2023-07-06 10 50 29](https://github.com/FlowiseAI/Flowise/assets/1227829/a3a6a961-180f-4a02-870b-614c9983f002)

What does not work:

1. Use ChatPromptTemplate and connect to LLM chain.

![截屏2023-07-06 11 50 23](https://github.com/FlowiseAI/Flowise/assets/1227829/7fc6ea32-bd00-4bec-b7e4-48d2da4342d5)

Chat and the AI will respond with "}"

2. The same settings, but with the OpenAI node and the endpoint of LocalAI

![截屏2023-07-06 10 45 59](https://github.com/FlowiseAI/Flowise/assets/1227829/cffb891f-e0b5-42f2-b075-1a70bf9ed6cc)

Chat and the AI will report undefined property "text"

**To Reproduce**

See the picture above.

**Expected behavior**

AI can respond with actual answers

**Screenshots**

See the above.

**Flow**

See the above.

**Setup**
-   Installation: docker compose
-   Flowise Version: latest
-   OS: Linux
-   Browser: Firefox

**Additional context**

**Comment by HenryHengZJ** [comment]
For `ChatPromptTemplate`, you need to fill in the System Message and Human Message fields. If you put `{text}` to Human Message field, should be working
