### ISSUE TITLE
[FEATURE] HF TextGenInf API Support

### ISSUE THREAD

**Issue by toby-lm** [FlowiseAI/Flowise#489]
**Describe the feature you'd like**
I'd like to be able to connect Flowise to LLMs I host with https://github.com/huggingface/text-generation-inference. I see you have LocalAI support, hopefully you can consider adding support for this one too for heavier GPU workflows.

**Comment by SwannSchilling** [comment]
You could use this template to build your own...this is how I am connecting Flowise to the Textgeneration Webui! 

```
from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

@app.route('/v1/chat/completions', methods=['POST'])
def chat_completions():
    data = request.json
    messages = data.get('messages')

    # Extract the content from messages
    content = messages[0]['content']
    
    # Prepare the payload for the API
    api_payload = {
        "prompt": content,
        "max_context_length": 2048,
        "max_length": 200,
        "do_sample": True,
        "temperature": 0.5,
        "top_p": 1,
        "typical_p": 1,
        "rep_pen": 1.1,
        "top_k": 0,
        "min_length": 0,
        "no_repeat_ngram_size": 0,
        "num_beams": 1,
        "penalty_alpha": 0,
        "length_penalty": 1,
        "early_stopping": False,
        "seed": -1,
        "add_bos_token": True,
        "custom_stopping_strings": [],
        "truncation_length": 2048,
        "ban_eos_token": False
    }

    # Call the API and get the response
    api_endpoint = 'http://127.0.0.1:5000/api/v1/generate'
    response_from_api = requests.post(api_endpoint, json=api_payload).json()

    # Prepare the response to be returned
    response = {
        "model": data.get('model'),
        "choices": [
            {
                "message": {
                    "role": "assistant",
                    "content": response_from_api["results"][0]["text"]
                }
            }
        ]
    }

    return jsonify(response)

if __name__ == '__main__':
    app.run(host='localhost', port=8080)
    #app.run(host='0.0.0.0', port=8080)
```

**Comment by HenryHengZJ** [comment]
you should be able to use your deployed inference endpoint in HF node:
<img width="920" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/efc44670-fd4d-464f-b589-a603cf0cee2f">

**Comment by HenryHengZJ** [comment]
you dont need to put anything to the model field, just the API key (sorry its lil bit confusing for now, we have a PR updating the HF node), also here's a [video](https://www.youtube.com/watch?v=VU4uFsglfXM) that is using HF node with own endpoint

**Comment by nathkooldebug** [comment]
> You could use this template to build your own...this is how I am connecting Flowise to the Textgeneration Webui!
> 
> ```
> from flask import Flask, request, jsonify
> import requests
> 
> app = Flask(__name__)
> 
> @app.route('/v1/chat/completions', methods=['POST'])
> def chat_completions():
>     data = request.json
>     messages = data.get('messages')
> 
>     # Extract the content from messages
>     content = messages[0]['content']
>     
>     # Prepare the payload for the API
>     api_payload = {
>         "prompt": content,
>         "max_context_length": 2048,
>         "max_length": 200,
>         "do_sample": True,
>         "temperature": 0.5,
>         "top_p": 1,
>         "typical_p": 1,
>         "rep_pen": 1.1,
>         "top_k": 0,
>         "min_length": 0,
>         "no_repeat_ngram_size": 0,
>         "num_beams": 1,
>         "penalty_alpha": 0,
>         "length_penalty": 1,
>         "early_stopping": False,
>         "seed": -1,
>         "add_bos_token": True,
>         "custom_stopping_strings": [],
>         "truncation_length": 2048,
>         "ban_eos_token": False
>     }
> 
>     # Call the API and get the response
>     api_endpoint = 'http://127.0.0.1:5000/api/v1/generate'
>     response_from_api = requests.post(api_endpoint, json=api_payload).json()
> 
>     # Prepare the response to be returned
>     response = {
>         "model": data.get('model'),
>         "choices": [
>             {
>                 "message": {
>                     "role": "assistant",
>                     "content": response_from_api["results"][0]["text"]
>                 }
>             }
>         ]
>     }
> 
>     return jsonify(response)
> 
> if __name__ == '__main__':
>     app.run(host='localhost', port=8080)
>     #app.run(host='0.0.0.0', port=8080)
> ```

WHERE YOU PUT THIS CODE IN THE FLOWISE?

**Comment by SwannSchilling** [comment]
You can put it anywhere on your machine and run it...it connects to the api of texgeneration webui!
