### ISSUE TITLE
[FEATURE] OpenSearch Vector Store Integration

### ISSUE THREAD

**Issue by vamshin** [FlowiseAI/Flowise#494]
**Describe the feature you'd like**
OpenSearch supports approximate vector search powered by Lucene engine, nmslib engine, faiss engine. As OpenSearch is popular search engine, it would be good to have this available as one of the supported vector stores

**Comment by vjsai** [comment]
Have tried adding support for OpenSearch in this PR https://github.com/FlowiseAI/Flowise/pull/512 @vamshin

**Comment by vamshin** [comment]
This is pretty fast. Thanks a lot @vjsai.

**Comment by HenryHengZJ** [comment]
thanks @vjsai PR merged!

**Comment by freemjstudio** [comment]
@vjsai 
Hi I'm also trying to use OpenSearch on flowise but I have no idea to give master user id & password for authorization 
Where can I input master user id & password of OpenSearch on Flowise ?

**Comment by mozg31337** [comment]
> @vjsai Hi I'm also trying to use OpenSearch on flowise but I have no idea to give master user id & password for authorization Where can I input master user id & password of OpenSearch on Flowise ?

Yes, indeed. I was actually trying to do that a few days ago and couldn't figure it out. Any Documentation on that would be much appreciated

**Comment by vjsai** [comment]
@freemjstudio @mozg31337 Let me take a look at it and update you guys. Thanks!

**Comment by kevin91nl** [comment]
> @vjsai Hi I'm also trying to use OpenSearch on flowise but I have no idea to give master user id & password for authorization Where can I input master user id & password of OpenSearch on Flowise ?

Not ideal security-wise, but you can access OpenSearch via http://<username>:<password>@host/.
