### ISSUE TITLE
[FEATURE] Adding chatbot prompts to require name and email for user

### ISSUE THREAD

**Issue by scooter7** [FlowiseAI/Flowise#498]
Hi,

I'd like to have the chat collect user name and email address prior to answering any user questions.

Could I do this by modifying (from https://github.com/FlowiseAI/FlowiseChatEmbed#configuration):

<script type="module">
  import Chatbot from "https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js";
  Chatbot.init({
    chatflowid: "91e9c803-5169-4db9-8207-3c0915d71c5f",
    apiHost: "http://localhost:3000",
    chatflowConfig: {
      // topK: 2
    },
    theme: {
      button: {
        backgroundColor: "#3B81F6",
        right: 20,
        bottom: 20,
        size: "medium",
        iconColor: "white",
        customIconSrc:
          "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/svg/google-messages.svg",
      },
      chatWindow: {
        welcomeMessage: "Hello! This is custom welcome message",
        backgroundColor: "#ffffff",
        height: 700,
        width: 400,
        fontSize: 16,
        poweredByTextColor: "#303235",
        botMessage: {
          backgroundColor: "#f7f8ff",
          textColor: "#303235",
          showAvatar: true,
          avatarSrc:
            "https://raw.githubusercontent.com/zahidkhawaja/langchain-chat-nextjs/main/public/parroticon.png",
        },
        userMessage: {
          backgroundColor: "#3B81F6",
          textColor: "#ffffff",
          showAvatar: true,
          avatarSrc:
            "https://raw.githubusercontent.com/zahidkhawaja/langchain-chat-nextjs/main/public/usericon.png",
        },
        textInput: {
          placeholder: "Type your question",
          backgroundColor: "#ffffff",
          textColor: "#303235",
          sendButtonColor: "#3B81F6",
        },
      },
    },
  });
</script>

**Comment by chungyau97** [comment]
You can try using `Zep Memory`
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/f4a78119-881a-4b1c-96a7-b375a803cd14)

When detected a new user you can use a new `Session Id` in `Additional Parameters` for it to act like a new conversation
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/63f9df87-9cc7-4aff-9765-ed0a4492f6bf)

After that you can use `Zapier NLA` tool to record it into anywhere you want
The docs on how to use [Zapier NLA](https://nla.zapier.com/start/)
Flowise Example: #114
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/6715b5c3-19ef-4d5f-ae85-51c4c8d47a46)

**Comment by mmhurston** [comment]
I'm interested in this feature, too. I use pabbly connect for my integrations.

**Comment by chungyau97** [comment]
Hi @mmhurston,

[Flowise PR 715](https://github.com/FlowiseAI/Flowise/pull/715) currently in progress.

**Comment by HenryHengZJ** [comment]
PR - https://github.com/FlowiseAI/Flowise/pull/1948 in work
