### ISSUE TITLE
[FEATURE] Is there any chain for sumarizing large context ?

### ISSUE THREAD

**Issue by LegendLeo** [FlowiseAI/Flowise#507]
**Describe the feature you'd like**
I want to summarize a webpage, the webpage content resulted tokens exceed the maximum, langchain provide a load_summarize_chain for this situation, is there any component can i use

**Comment by chungyau97** [comment]
Will need to dive deeper on how to solve max tokens limitation in Flowise, as it will hit the limit of OpenAI.

[langchainjs](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/openai.ts#L282) reference on how to implement into Flowise

Reference:
[langchainjs #1827](https://github.com/hwchase17/langchainjs/issues/1872)
[Auto-GPT #2906](https://github.com/Significant-Gravitas/Auto-GPT/issues/2906)

**Comment by LegendLeo** [comment]
> Will need to dive deeper on how to solve max tokens limitation in Flowise, as it will hit the limit of OpenAI.
> 
> [langchainjs](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/openai.ts#L282) reference on how to implement into Flowise
> 
> Reference: [langchainjs #1827](https://github.com/hwchase17/langchainjs/issues/1872) [Auto-GPT #2906](https://github.com/Significant-Gravitas/Auto-GPT/issues/2906)

I just want a loadSummarizationChain component, langchain has provided: [loadSummarizationChain](https://js.langchain.com/docs/modules/chains/other_chains/summarization)

**Comment by chungyau97** [comment]
Alright, I can do that. 

Once PR is opened I will update you here.

**Comment by HenryHengZJ** [comment]
@LegendLeo have you tried using ConversationalRetrievalQAChain with different chain type?
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/cf4d8704-969b-47d3-9786-787e7de4f9de)

you can read more what are these for - https://js.langchain.com/docs/modules/chains/document/map_reduce , these chain types are used to summarize long context

**Comment by LegendLeo** [comment]
ConversationalRetrievalQAChain is used in conversation situation, but I just want to summarize a very long text, not a chat history.
