### ISSUE TITLE
[QUERY] Deploy Docker image via Portainer

### ISSUE THREAD

**Issue by Surgical17** [FlowiseAI/Flowise#509]
I Noticed in the Docker Compose that deploying the container pulls a image (That I Assume is from Docker Hub)

Is it then still required to clone the repo and then deploy the container via that or cant you just deploy it directly via Portainer as an example?

Last question is that I have noticed when you upgrade to the latest version of the image you loose your current setup/files. I know there is a backup function within Flowise, but it shouldn't replace your configuration especially if the volume was set?

**Comment by HenryHengZJ** [comment]
No you don't need to clone the repo, you just need that docker-compose.yml file.

For setup files, which configurations were replaced?

**Comment by Surgical17** [comment]
> No you don't need to clone the repo, you just need that docker-compose.yml file.
> 
> For setup files, which configurations were replaced?

I followed the Deployment of Docker as per the instructions (Cloning the Repo, accessing the docker file, editing the docker-compose and the .env) and the running. Everything works.

When I update the Image (Docker pull) and start the container again all the Chatflows is gone. Must be a issue with the Volume:

services:                                                                                                                                             
 4     flowise:                                                                                                                                          
 5         image: flowiseai/flowise:latest                                                                                                               
 6         restart: unless-stopped                                                                                                                       
 7         labels:                                                                                                                                       
 8             - com.centurylinklabs.watchtower.monitor-only=true                                                                                        
 9         environment:                                                                                                                                  
10             - PORT=${PORT}                                                                                                                            
11             - FLOWISE_USERNAME=${FLOWISE_USERNAME}                                                                                                    
12             - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}                                                                                                    
13             - DATABASE_PATH=${DATABASE_PATH}                                                                                                          
14             - EXECUTION_MODE=${EXECUTION_MODE}                                                                                                        
15         ports:                                                                                                                                        
16             - '${PORT}:${PORT}'                                                                                                                       
17         volumes:                                                                                                                                      
18             - ~/.flowise:/root/.flowise                                                                                                               
19         command: /bin/sh -c "sleep 3; flowise start"

**Comment by Surgical17** [comment]
I do see by default in the .env the database path is Hashed out

**Comment by Surgical17** [comment]
Thanx for the update.
I followed the instructions as you gave and still the Chatflows vanish:

Should we not rather add each as a volume?

.env:
4 # DEBUG=true                                                                                                                                                                           
5 DATABASE_PATH=/home/ubuntu/DockerCompose/Flowise/docker/.flowise                                                                                                                       
6 APIKEY_PATH=/home/ubuntu/DockerCompose/Flowise/docker/.flowise                                                                                                                         
7 LOG_PATH=/home/ubuntu/DockerCompose/Flowise/docker/.flowise/logs                                                                                                                       
8 # LOG_LEVEL=debug (error | warn | info | verbose | debug)                                                                                                                              
9 EXECUTION_MODE=main (child | main)                                                                                                                                                     
                                          
Docker-Compose.yml:
 version: '3.1'                                                                                                                                                                        
 2                                                                                                                                                                                       
 3 services:                                                                                                                                                                             
 4     flowise:                                                                                                                                                                          
 5         image: flowiseai/flowise:latest                                                                                                                                               
 6         restart: unless-stopped                                                                                                                                                       
 7         labels:                                                                                                                                                                       
 8             - com.centurylinklabs.watchtower.monitor-only=true                                                                                                                        
 9         environment:                                                                                                                                                                  
10             - PORT=${PORT}                                                                                                                                                            
11             - FLOWISE_USERNAME=${FLOWISE_USERNAME}                                                                                                                                    
12             - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}                                                                                                                                    
13             - DATABASE_PATH=${DATABASE_PATH}                                                                                                                                          
14             - EXECUTION_MODE=${EXECUTION_MODE}                                                                                                                                        
15         ports:                                                                                                                                                                        
16             - '${PORT}:${PORT}'                                                                                                                                                       
17         volumes:                                                                                                                                                                      
18             - ~/.flowise:/root/.flowise                                                                                                                                               
19         command: /bin/sh -c "sleep 3; flowise start"

**Comment by Surgical17** [comment]
I tried the same as what I am use to with containers as in setup a volume path, but even then the "data" folder was created but empty:

version: '3.1'

services:
    flowise:
        image: flowiseai/flowise:latest 
        restart: unless-stopped 
        labels:  
            - com.centurylinklabs.watchtower.monitor-only=true
        environment:
            - PORT=${PORT}
            - FLOWISE_USERNAME=${FLOWISE_USERNAME}
            - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
            - DATABASE_PATH=${DATABASE_PATH}
            - EXECUTION_MODE=${EXECUTION_MODE}
        ports:
            - '${PORT}:${PORT}'
        volumes:
            - /home/ubuntu/DockerCompose/Flowise/data:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"

**Comment by Surgical17** [comment]
Great stuff. Sorted.
Thank you for the Document update
