### ISSUE TITLE
[BUG] Chatflows automatically getting deleted during flow setup

### ISSUE THREAD

**Issue by Salman585** [FlowiseAI/Flowise#517]
I installed Flowise on Azure via Docker image, the setup is completed and looks fine. While I was setting a new chatflow from scratch, it automatically got deleted in the middle of the setup, although the flow was saved previously. The deletion did not show errors or any warning or close the chatflow setup page. When interacting with the chatbot within the chatflow, it shows an error "Chatflow <canvas number> not found".

After that, the flow does not seem to work and can't be found. 

Also to mention this issue did appear when I tried to install it from the official stable source code from the [Flowise github repo](https://github.com/FlowiseAI/Flowise/releases).

**Comment by chungyau97** [comment]
Hi @Salman585 

Kindly refer to #526
