### ISSUE TITLE
Yarn Start giving me an error for module not found at Server

### ISSUE THREAD

**Issue by imanmalhi** [FlowiseAI/Flowise#525]

**Comment by chungyau97** [comment]
Hi @imanmalhi, 

Could you try running `yarn install` and `sudo yarn build-force` before `sudo yarn start`

Do join our [discord community](https://discord.gg/AfZaQA5k), you can access this information in our discord
Help > Support > Search for `driverError: [Error: SQLITE_READONLY: attempt to write a readonly database]`
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/5e389612-ee28-4290-9c66-d1d32e8b9025)
