### ISSUE TITLE
[BUG] Receiving "Request failed with status code 400" error

### ISSUE THREAD

**Issue by trda** [FlowiseAI/Flowise#527]
I am able to smoothly chat using the "Conversational Retrieval QA Chain" I created. However, after sending around 30 messages, I start receiving a "Request failed with status code 400" error in the chat panel. When I inspect the page, I see the error message "Failed to load resource: the server responded with a status of 500 (Internal Server Error)." I have tried this multiple times with the "Conversational Retrieval QA Chain," and I consistently encounter a similar error. There is no restriction on the limit of the chatbot I am using.

Nodejs version 
```
node -v 
v20.3.1
```

<img width="1375" alt="Screen Shot 2023-07-12 at 06 50 10" src="https://github.com/FlowiseAI/Flowise/assets/4353845/d04db5d9-2610-451e-b13d-a3509d77ce1a">
<img width="1398" alt="Screen Shot 2023-07-12 at 06 50 39" src="https://github.com/FlowiseAI/Flowise/assets/4353845/5de47d13-9b5e-4f37-858a-c7d8ebeb4f1f">

**Comment by chungyau97** [comment]
Hi @trda,

Could you share the error logs from your terminal?

**Comment by trda** [comment]
`[llm/error] [1:chain:ConversationalRetrievalQAChain > 2:chain:LLMChain > 3:llm:ChatOpenAI] [924ms] LLM run errored with error: "Request failed with status code 400"
[llm/error] [1:chain:LLMChain > 2:llm:ChatOpenAI] [923ms] LLM run errored with error: "Request failed with status code 400"
[chain/error] [1:chain:ConversationalRetrievalQAChain > 2:chain:LLMChain] [926ms] Chain run errored with error: "Request failed with status code 400"
[chain/error] [1:chain:LLMChain] [925ms] Chain run errored with error: "Request failed with status code 400"
[chain/error] [1:chain:ConversationalRetrievalQAChain] [929ms] Chain run errored with error: "Request failed with status code 400"
2023-07-12 22:27:50 [ERROR]: [server]: Error: Request failed with status code 400
Error: Request failed with status code 400
    at createError (/opt/homebrew/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/homebrew/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/homebrew/lib/node_modules/flowise/node_modules/openai/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:523:35)
    at endReadableNT (node:internal/streams/readable:1367:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by chungyau97** [comment]
There are not much information I can look into based on the terminal logs.

Some troubleshoots options:
1. Check the OpenAI's account billing
2. Is the OpenaAI API Key correct
3. Re-create the same flow

**Comment by emrahtoy** [comment]
I am facing with the same issue, same logs are appearing on terminal.
No problem with the open ai account
API key is correct
It happens on freshly created flows too

**Comment by eitanwaxman** [comment]
Have something similar
![image](https://github.com/FlowiseAI/Flowise/assets/97314610/629ca435-1224-440d-ad45-90d8a167776c)

**Comment by ZippeyKeys12** [comment]
The memory's becoming too large and going over the OpenAI token limit.

I used Buffer Window Memory to limit how much it includes, which fixed it.

Flowise should deal with this better though, either truncating the memory, or throwing a better error. Maybe it's supposed to, but some check is slightly off.

**Comment by emrahtoy** [comment]
I am having the same issue as well
