### ISSUE TITLE
[BUG]  "Command start not found" when running _npx flowise start_ on Flowise version 1.2.15

### ISSUE THREAD

**Issue by basilbowman** [FlowiseAI/Flowise#533]
**Describe the bug**
After updating npm/npx along with node, and re-installing the latest build of Flowise, I cannot start Flowise.

I have not tested building it locally, just running the most recent install from npm.

**To Reproduce**

1.) Update to the latest release of Flowise
2.) Attempt to start it using npx flowise start
3.) You get this error "Command start not found" 
4.) No further activity.

**Expected behavior**
It ought to run, right?

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation: npx flowise start
-   Flowise Version: Most recently released, 1.2.15
-   OS: Windows 10, 64bit
-   Browser: Chrome

**Additional context**
multiple reports in the discord with similar issue: https://discord.com/channels/1087698854775881778/1128745812080472064

**Comment by basilbowman** [comment]
The package.json has the same 'start' command as before, it's not a typo or something dumb like that.

**Comment by basilbowman** [comment]
I'm going to abandon this issue for now and switch to Docker instead - this issue appears to be related to versioning of npm/npx/node on my local machine.

**Comment by momoadeli** [comment]
I can't npm install flowise (see error) unless I 'force'.. i'm on node 18.5.0 (via nvm). Even after --force npx flowise start gives error command start not found. what gives? Same error with npx flowise start. I'm on latest macOS. 
![image](https://github.com/FlowiseAI/Flowise/assets/3706255/83f674fb-813e-4ac4-8890-d1e4c72d658c)

pnpm install failed too. cannot curently run flowise. seems there's a bad react dependency
