### ISSUE TITLE
[BUG] shouldn't deep clone component on processPrediction 

### ISSUE THREAD

**Issue by shanghaikid** [FlowiseAI/Flowise#535]
```javascript
// in processPrediction
 const nodeToExecute = reactFlowNodes.find((node: IReactFlowNode) => node.id === endingNodeId)
                    if (!nodeToExecute) return res.status(404).send(`Node ${endingNodeId} not found`)

                    const reactFlowNodeData: INodeData = resolveVariables(nodeToExecute.data, reactFlowNodes, incomingInput.question)
                    nodeToExecuteData = reactFlowNodeData

                    const startingNodes = nodes.filter((nd) => startingNodeIds.includes(nd.id))
                    this.chatflowPool.add(chatflowid, nodeToExecuteData, startingNodes, incomingInput?.overrideConfig)

```

```javascript

export const resolveVariables = (reactFlowNodeData: INodeData, reactFlowNodes: IReactFlowNode[], question: string): INodeData => {
    let flowNodeData = cloneDeep(reactFlowNodeData)
    if (reactFlowNodeData.instance && isVectorStoreFaiss(reactFlowNodeData)) {
        // omit and merge because cloneDeep of instance gives "Illegal invocation" Exception
        const flowNodeDataWithoutInstance = cloneDeep(omit(reactFlowNodeData, ['instance']))
        flowNodeData = merge(flowNodeDataWithoutInstance, { instance: reactFlowNodeData.instance })
    }
    const types = 'inputs'

    const getParamValues = (paramsObj: ICommonObject) => {
        for (const key in paramsObj) {
            const paramValue: string = paramsObj[key]
            if (Array.isArray(paramValue)) {
                const resolvedInstances = []
                for (const param of paramValue) {
                    const resolvedInstance = getVariableValue(param, reactFlowNodes, question)
                    resolvedInstances.push(resolvedInstance)
                }
                paramsObj[key] = resolvedInstances
            } else {
                const isAcceptVariable = reactFlowNodeData.inputParams.find((param) => param.name === key)?.acceptVariable ?? false
                const resolvedInstance = getVariableValue(paramValue, reactFlowNodes, question, isAcceptVariable)
                paramsObj[key] = resolvedInstance
            }
        }
    }

    const paramsObj = flowNodeData[types] ?? {}

    getParamValues(paramsObj)

    return flowNodeData
}

```

if a component is using grpc to communicate, if you deep clone the component node here, the grpc channel can not be reused for later requests due to security issue. 

Can we define a component type, so that here you can get the node instance by different way based on the type?

**Comment by shanghaikid** [comment]
or maybe we can lazy initialize these nodes.

**Comment by chungyau97** [comment]
Hi @shanghaikid,

Could you create a PR on how it should look like?

**Comment by shanghaikid** [comment]
> Hi @shanghaikid,
> 
> Could you create a PR on how it should look like?

Sure, I will create a PR soon.

**Comment by HenryHengZJ** [comment]
thanks @shanghaikid for figuring out the issue with Milvus - https://github.com/FlowiseAI/Flowise/issues/154

what do you mean by define a component type? would be great to see a PR of a rough idea on how to overcome this

**Comment by shanghaikid** [comment]
> 

I am working on the pr,  today or tomorrow.

**Comment by shanghaikid** [comment]
> thanks @shanghaikid for figuring out the issue with Milvus - #154
> 
> what do you mean by define a component type? would be great to see a PR of a rough idea on how to overcome this

I try many ways to avoid deep clone, but seems too complicated to do, I don't wanna add any complexity here.  I saw you do it for faiss only, could you tell me if we can remove the limit, will it introduce bugs for other components?   

![image](https://github.com/FlowiseAI/Flowise/assets/185051/624d14b0-f182-415f-a586-29185f1b31a3)

I've tested milvus node, no deep clone here will make it work. 

![image](https://github.com/FlowiseAI/Flowise/assets/185051/f199ea96-2aa0-4201-bb0a-d2d4fab1e962)

**Comment by HenryHengZJ** [comment]
Found a workaround, refer to this PR #794
