### ISSUE TITLE
[BUG] warning: 'invalid prop value of type number supplied to input expected string' the method of [DEBUG]

### ISSUE THREAD

**Issue by comey246** [FlowiseAI/Flowise#536]
**Describe the bug**
when the card‘s input have inut that is number, the console will log the warning:"invalid prop value of type number supplied to input expected string"

**To Reproduce**
1. use the dev
2. add the chatmodel or any card that input contant the number 
3. watch the console

**cause**
in the input component(packages/ui/src/ui-component/input/Input.js)
```
Input.propTypes = {value: PropTypes.string}
```
the value's type is `string` ,

but some input value's type is `number` such as the temperature

**debug**
debug the input component(packages/ui/src/ui-component/input/Input.js)
```
Input.propTypes = {value: PropTypes.string}
```
replace to=>
```
Input.propTypes = {value: PropTypes.oneOfType([PropTypes.string, PropTypes.number])}
```

**Comment by chungyau97** [comment]
Hi @comey246, 

Could you create a PR on that?

**Comment by comey246** [comment]
ok, I will creat a PR to branch: fixbug/inputNumber

**Comment by HenryHengZJ** [comment]
closing as https://github.com/FlowiseAI/Flowise/pull/567 merged
