### ISSUE TITLE
[BUG] docker database Data Source has been initialized!

### ISSUE THREAD

**Issue by av8dtop** [FlowiseAI/Flowise#538]
Every time I redeploy docker, my data will disappear and I have to renew

**Comment by HenryHengZJ** [comment]
If you like to persist your data (flows, logs, apikeys), set these variables in the .env file inside docker folder:

DATABASE_PATH=/root/.flowise
APIKEY_PATH=/root/.flowise
LOG_PATH=/root/.flowise/logs

Updated [README](https://github.com/FlowiseAI/Flowise/tree/main/docker#-env-variables)
