### ISSUE TITLE
Memory 

### ISSUE THREAD

**Issue by Cat-Vader** [FlowiseAI/Flowise#542]
I am trying to set up a conversational chain, so two chains, one for upsert the other for conversations. The bot however does not really index new documents, even after resaving, any insights to solve this aspect?

**Comment by govind-kumarr** [comment]
@Cat-Vader  Can you share the exact steps or Can you share any screenshots of the chat flow?

**Comment by Cat-Vader** [comment]
Sure
![image](https://github.com/FlowiseAI/Flowise/assets/94360277/a3ec1f4b-f486-42ee-b07b-9f56d0fce4ff)
(the upload stream)
![image](https://github.com/FlowiseAI/Flowise/assets/94360277/955ba7db-f161-45aa-ac19-8a546ab9a15f)
The chat flow

**Comment by Cat-Vader** [comment]
@govind-kumarr Did you see the flow?
I can send you a proper export via mail

**Comment by govind-kumarr** [comment]
@Cat-Vader  yeah

**Comment by govind-kumarr** [comment]
@Cat-Vader I will look into it.

**Comment by Cat-Vader** [comment]
I appreciate it
