### ISSUE TITLE
[BUG] docker-compose up is not working

### ISSUE THREAD

**Issue by sugarforever** [FlowiseAI/Flowise#543]
**Describe the bug**
When I followed the documentation to launch with `docker-compose up`, it failed with the following error information:
```
WARN[0000] The "EXECUTION_MODE" variable is not set. Defaulting to a blank string. 
[+] Running 11/11
 ⠿ flowise Pulled                                                                                                           141.3s
   ⠿ 31e352740f53 Pull complete                                                                                               3.3s
   ⠿ 560412e561fb Pull complete                                                                                               8.9s
   ⠿ 02735cb6c78b Pull complete                                                                                               9.1s
   ⠿ 86d562f7b855 Pull complete                                                                                               9.2s
   ⠿ 15f985e6dc44 Pull complete                                                                                               9.4s
   ⠿ 4c9c0eb63016 Pull complete                                                                                              26.8s
   ⠿ cb4f570b3753 Pull complete                                                                                              28.5s
   ⠿ 2447bf789036 Pull complete                                                                                              53.0s
   ⠿ 3a30a7c35dcc Pull complete                                                                                             135.6s
   ⠿ 4f50ed55a122 Pull complete                                                                                             136.1s
[+] Running 2/2
 ⠿ Network docker_default      Created                                                                                        0.1s
 ⠿ Container docker-flowise-1  Created                                                                                        1.0s
Attaching to docker-flowise-1
docker-flowise-1  |     Error: ENOENT: no such file or directory, mkdir
docker-flowise-1  |     Code: ENOENT
docker-flowise-1 exited with code 1
docker-flowise-1  |     Error: ENOENT: no such file or directory, mkdir
docker-flowise-1  |     Code: ENOENT
docker-flowise-1 exited with code 1
docker-flowise-1  |     Error: ENOENT: no such file or directory, mkdir
docker-flowise-1  |     Code: ENOENT
docker-flowise-1 exited with code 1
docker-flowise-1  |     Error: ENOENT: no such file or directory, mkdir
docker-flowise-1  |     Code: ENOENT
```

**To Reproduce**

1. Git clone flowise
2. Go to docker folder, copy .env.example to .env
3. Run docker-compose up

**Expected behavior**
The docker process should be up and running on port 300.

**Comment by cjrujo** [comment]
Same issue here, the service is not up and listening on the desired port by "docker-compose up -d" and the error message can be seen by "docker-compose up".

**Comment by mwalol** [comment]
seem like not a bug, you should set the .env vars

LOG_PATH=/data/logs

and this should start it without issue

**Comment by sugarforever** [comment]
> seem like not a bug, you should set the .env vars
> 
> LOG_PATH=/data/logs
> 
> and this should start it without issue

Cool. Thanks. I will give it a try and close this issue once it's verified.

**Comment by sugarforever** [comment]
> > seem like not a bug, you should set the .env vars
> > LOG_PATH=/data/logs
> > and this should start it without issue
> 
> Cool. Thanks. I will give it a try and close this issue once it's verified.

By the way, probably it should be documented somewhere, or properly handled by the code, for example, if log path is not set, use some default one.

**Comment by queenvictoria** [comment]
Perhaps we could remove the comment from the line in `docker/.env.example` so that it's clear that it's not optional?
https://github.com/FlowiseAI/Flowise/blob/main/docker/.env.example#L7

**Comment by HenryHengZJ** [comment]
added fix to use a default log path, and also updated [README](https://github.com/FlowiseAI/Flowise/tree/main/docker#-env-variables)

```
If you like to persist your data (flows, logs, apikeys), set these variables in the .env file inside docker folder:

DATABASE_PATH=/root/.flowise
APIKEY_PATH=/root/.flowise
LOG_PATH=/root/.flowise/logs

```

**Comment by sugarforever** [comment]
> Perhaps we could remove the comment from the line in `docker/.env.example` so that it's clear that it's not optional? https://github.com/FlowiseAI/Flowise/blob/main/docker/.env.example#L7

It worked.

**Comment by sugarforever** [comment]
> added fix to use a default log path, and also updated [README](https://github.com/FlowiseAI/Flowise/tree/main/docker#-env-variables)
> 
> ```
> If you like to persist your data (flows, logs, apikeys), set these variables in the .env file inside docker folder:
> 
> DATABASE_PATH=/root/.flowise
> APIKEY_PATH=/root/.flowise
> LOG_PATH=/root/.flowise/logs
> ```
> 
> Will keep this open until we push to a new release

Thanks for the update. I will leave this issue to you guys. Feel free to close after a new release.

**Comment by HenryHengZJ** [comment]
should be updated in 1.2.16 release
