### ISSUE TITLE
[BUG] Javascript API is expecting SocketID in request

### ISSUE THREAD

**Issue by atishamte** [FlowiseAI/Flowise#550]
**Describe the bug**
When I try to integrate the Javascript API, it actually reloads the page. The API is getting called successfully as I can see the logs in the server console when debug=true in the env file. But When I submit the request from the front end, I just give me status of the fetch API as "Canceled" in the developer console.
![Screenshot 2023-07-16 at 1 36 40 AM](https://github.com/FlowiseAI/Flowise/assets/8375139/878836f3-526e-4a3f-a778-4a2ba2f6ff90)

**Comment by HenryHengZJ** [comment]
might be related to - https://github.com/FlowiseAI/Flowise/pull/555

probably you'll have to use:
```
const response = await fetch(
        "your-url/api/v1/prediction/chatflowid",
        {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(data)
        }
    );
    const result = await response.json();
```
