### ISSUE TITLE
[BUG] Failed to execute turbo

### ISSUE THREAD

**Issue by ck3d** [FlowiseAI/Flowise#556]
**Describe the bug**
I package your project in Nix and the execution of yarn build fails. This issue could be related to https://github.com/vercel/turbo/issues/3280 .
Updating turbo to version 1.8.8 could fix the issue.

**To Reproduce**
Execute turbo run build returns following error:

```
❯ turbo run --verbosity 10 build
2023-07-16T13:42:34.084+0200 [DEBUG] turborepo_lib::shim: Global turbo version: 1.7.4
2023-07-16T13:42:34.085+0200 [DEBUG] turborepo_lib::shim: Local turbo version: 1.7.4
2023-07-16T13:42:34.085+0200 [DEBUG] turborepo_lib::shim: Running local turbo binary in /home/chris/work/Flowise/node_modules/turbo/bin/turbo

2023-07-16T13:42:34.085+0200 [DEBUG] turborepo_lib::shim: supports_skip_infer_and_single_package true
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/turborepo/src/main.rs:50:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Expected behavior**
`yarn build` should not fail.

**Setup**
-   Installation `yarn build`
-   Flowise Version 1.2.15
-   OS: Linux

**Comment by chungyau97** [comment]
Hi @ck3d,

Before we proceed would like to ask you some questions
1. What's your node version? >= 18.15.0
2. Could you try `sudo yarn build` or `sudo yarn build-force`?

**Comment by chungyau97** [comment]
Could you try these steps on a fresh Flowise without modifying anything: 
1. `git clone https://github.com/FlowiseAI/Flowise.git`
2. `yarn install` or `sudo yarn install`
3. `yarn build` or `sudo yarn build`
4. `yarn start` or `sudo yarn start`

**Comment by ck3d** [comment]
Based on git commit ffc8033a9 (after release 1.2.16) the same error occurs:#

```
❯ yarn build
yarn run v1.22.19
$ turbo run build
╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│                   Update available v1.7.4 ≫ v1.10.9                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.10.9    │
│                      Run "npm i turbo" to update                      │
│                                                                       │
│     Follow @turborepo for updates: https://twitter.com/turborepo      │
╰───────────────────────────────────────────────────────────────────────╯
thread 'main' panicked at 'Failed to execute turbo.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', crates/turborepo/src/main.rs:50:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error Command failed with exit code 101.
```

**Comment by trm217** [comment]
What's the current status of this?
A new initial setup of a turbo mono-repo with 'pnp' didn't work.

**Comment by chungyau97** [comment]
Hi @trm217,

I'm not able to replicate the errors you guys are having.
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/df30fdad-b2c7-42a9-ae05-c506f27339fc)
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/903be50a-458e-4c4a-a6fa-e2645908036b)

cc @HenryHengZJ

**Comment by kenzik** [comment]
I had this same issue when attempting to use in OSX.

When I switched to Linux, I did not have the issue.

**Comment by chungyau97** [comment]
Hey @kenzik,

Could you try this out? 
https://github.com/FlowiseAI/Flowise/issues/768#issuecomment-1679188977

**Comment by kenzik** [comment]
@chungyau97 - I will when I can and have some more free time. 

I'm just using Linux now and have no real preference either way -- especially since it won't be deployed on a Mac.

**Comment by ck3d** [comment]
Is updating of turbo not an option? It would fix this issue.

**Comment by chungyau97** [comment]
Hey @ck3d,

We can update Turbo, but me and @HenryHengZJ don't own a Mac to test it. 

You can try it on your forked repo. If it works, you can submit a PR along with some screenshots of different type of tested flow results.

**Comment by HenryHengZJ** [comment]
should be resolved with moving to pnpm - https://github.com/FlowiseAI/Flowise/pull/1272
