### ISSUE TITLE
responses

### ISSUE THREAD

**Issue by matigumma** [FlowiseAI/Flowise#56]
Hi there, thanks for this development.

just want to ask why aswers are too short?

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/794606/235941526-5c33b343-8c82-4b7a-9995-b30caea08a77.png">

**Comment by HenryHengZJ** [comment]
You can play around with the OpenAI temperature to get different response - https://platform.openai.com/docs/api-reference/completions/create#completions/create-temperature

**Comment by HenryHengZJ** [comment]
Found out that if you connect to ChatOpenAI, it produces longer form of answer
