### ISSUE TITLE
[BUG] Could not determine executable to run in node 18.15.0

### ISSUE THREAD

**Issue by joaoaspimienta** [FlowiseAI/Flowise#562]
**Describe the bug**
Whenever I try to run the command npx flowise start in this version of node, I always get "npm ERR! could not determine executable to run", in 16.18.1 I can run flowise but when I try to chat with the bot I get "ReferenceError: Blob is not defined".

**To Reproduce**

1. Run npx flowise start in node 18.15.0
2. See error

**Expected behavior**
The browser should load the Flowise program.

**Comment by chungyau97** [comment]
`EMIYA` in Discord updated his `npm` and reinstalled Flowise then it solve the problem

Highly recommend to install `NVM` to manage different node versions
[Windows NVM](https://github.com/coreybutler/nvm-windows)
[Linux NVM](https://github.com/nvm-sh/nvm)

**Comment by joaoaspimienta** [comment]
@chungyau97 it worked, thank you very much
