### ISSUE TITLE
Integrate Azure Open AI

### ISSUE THREAD

**Issue by ram-msft** [FlowiseAI/Flowise#58]
Can you integrate Azure Open AI also

**Comment by OwenVanV** [comment]
please do, us enterprise devs would love to show this off to management, but cant due to the inability to get non azure OpenAI approved under security policies.

**Comment by levidehaan** [comment]
Rawkin, it got merged. So I pulled that lib in and wow, a lot of breaking changes. Are you guys seeing the same thing?

I wanted to help get these changes in for Azure but wanted to see if there was a plan to cover the breaking changes? I can help out on that for sure.

**Comment by levidehaan** [comment]
> please do, us enterprise devs would love to show this off to management, but cant due to the inability to get non azure OpenAI approved under security policies.

It took a while but the legal team at my co finally gave in and let us get it for internal use, but now BI wants to use it for customer stuff. Exciting times ahead  :)

I can test all the way up to 32k once this is merged.

**Comment by OwenVanV** [comment]
Any news?

**Comment by HenryHengZJ** [comment]
Would you guys be willing to test the branch - `feature/Azure` @OwenVanV , @ram-msft , @levidehaan?

as we don't have access to Azure OpenAI, we'll have to rely the community to test it out.

Thanks!

**Comment by OwenVanV** [comment]
@HenryHengZJ  For sure, I wil test for you tomorrow and let you know!

**Comment by levidehaan** [comment]
Yes I have tested it, and it is working for me.

Sorry for the wait my work computer died and I've been working on recovery because wsl doesn't get backed up... anyways, last test I did was working. Still can't do huge docs on my last test but that could have been fixed in all the updates this past week.

**Comment by HenryHengZJ** [comment]
Closing as #92 merged

**Comment by HenryHengZJ** [comment]
here - https://github.com/FlowiseAI/Flowise/blob/bugfix/PromptSchema/packages/components/nodes/llms/Azure%20OpenAI/AzureOpenAI.ts#L111 you can just add another one

**Comment by sullivanzheng** [comment]
> here - https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/llms/Azure%20OpenAI/AzureOpenAI.ts#L106 you can just add another one

Updated and restart the server using npx  flowise start. But it is not updated. Should I recompile or something? (Apologies since I am abs newbie in Node.js)
