### ISSUE TITLE
[BUG] Cannot find module '../build/Release/canvas.node'

### ISSUE THREAD

**Issue by atishamte** [FlowiseAI/Flowise#581]
**Describe the bug**
Getting this error on yarn start

(node:25502) [MODULE_NOT_FOUND] ModuleLoadError Plugin: flowise: [MODULE_NOT_FOUND] require failed to load /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/dist/commands/start.js: Cannot find module '../build/Release/canvas.node'
Require stack:
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/canvas/lib/bindings.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/canvas/lib/canvas.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/canvas/index.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/utils.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/living/events/MouseEvent-impl.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/living/generated/MouseEvent.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/living/interfaces.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/jsdom/browser/Window.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/node_modules/jsdom/lib/api.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/components/dist/src/utils.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/components/dist/src/index.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/dist/utils/index.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/dist/index.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/dist/commands/start.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/node_modules/@oclif/core/lib/module-loader.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/node_modules/@oclif/core/lib/config/plugin.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/node_modules/@oclif/core/lib/config/config.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/node_modules/@oclif/core/lib/config/index.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/node_modules/@oclif/core/lib/command.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/node_modules/@oclif/core/lib/index.js
- /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server/bin/run
module: @oclif/core@1.26.2
task: toCached
plugin: flowise
root: /Users/testuser/Desktop/projects/code/flowiseai-local/packages/server

**To Reproduce**
1. Updated to main branch
2. yarn install && yarn build && yarn start
3. Got this error after yarn start

**Comment by josh900** [comment]
Same here, did you find a fix?

**Comment by josh900** [comment]
fixed by clearing node_modules

**Comment by chungyau97** [comment]
I will delete grey-out folders in Flowise and re-install Flowise.
1. Flowise\node_modules
2. Flowise\packages\\[components/server/ui]\\.turbo
3. \Flowise\packages\\[components/server/ui]\dist
4. \Flowise\packages\\[components/server/ui]\node_modules
