### ISSUE TITLE
[FEATURE] Create multi-lingual bots

### ISSUE THREAD

**Issue by jan-koch** [FlowiseAI/Flowise#596]
**Describe the feature you'd like**
I'd like the option to set the starting language for a chat conversation. 

**Additional context**
I'm working with German-speaking businesses only and they'd expect a chat bot to start the conversation in German. Is this possible already? Maybe I'm just missing a simple option.

**Comment by chungyau97** [comment]
You are able to set the starting `welcome message` in German.
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/9a9da9d6-1417-4cba-8bc6-be8d793a3be8)

In terms of replying customer based on their language used or German, you need to play around with `system message`
```
I want you to act as a document that I am having a conversation with. Your name is "AI Bot". You will provide me with answers from the given info. Only reply me in Chinese. If the answer is not included, say exactly "我不知道" and stop after that. Refuse to answer any question not about the info. Never break character.
```

**Comment by jan-koch** [comment]
Thanks so much @chungyau97 !

**Comment by jan-koch** [comment]
This fixed it for me :)
