### ISSUE TITLE
The browser/environment lacks native support for critical functionality used by the PDF.js

### ISSUE THREAD

**Issue by bdecarne** [FlowiseAI/Flowise#6]
**Describe the bug**

When we use the PDF document loader, we have the following error :   

`UnknownErrorException: The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. Path2D and/or ReadableStream); please use a legacy-build instead.`

**To Reproduce**

1. Add a PDF document loader
2. Complete the chain
3. Interact with the agent

**Expected behavior**
The PDF document is loaded

**Screenshots**

![image](https://user-images.githubusercontent.com/1277131/231871378-03726886-14fe-422d-adfc-af7572adb14a.png)

**Setup**

-   OS: Linux
-   Browser: Chrome, Firefox

**Comment by HenryHengZJ** [comment]
Hey @bdecarne, thanks for the issue! It has been fixed here: https://github.com/FlowiseAI/Flowise/pull/5. If you do reinstall or git clone it should works now. Let me know if this is still an issue

**Comment by bdecarne** [comment]
It works great now, thanks!
