### ISSUE TITLE
[FEATURE] Add open graph tags in website

### ISSUE THREAD

**Issue by theritikchoure** [FlowiseAI/Flowise#60]
## Issue Description
I would like to request that Open Graph tags be added to website to improve the way it is shared on social media. These tags help provide information to social media platforms like Facebook, Twitter, and LinkedIn, and can improve the way our website appears when it is shared.

## Proposed Solution
I would like to add the following Open Graph tags to our website:

```html
<meta property="og:title" content="Website Title">
<meta property="og:description" content="Website description">
<meta property="og:image" content="https://example.com/image.jpg">
<meta property="og:url" content="https://example.com">
```

The `og:title` tag would be used to specify the title of the website, the `og:description` tag would be used to provide a brief description of the website, the `og:image` tag would be used to specify the image to use when the website is shared, and the `og:url` tag would be used to specify the URL of the website.

## Additional Information
Please let me know if you have any questions or concerns about adding these Open Graph tags. I believe that this change would improve the way, the website is shared on social media and help increase online presence.

**Comment by Arshdeep-13** [comment]
### To solve this issue, you can try the following steps:

First, make sure you have the latest version of pip installed by running the following command:

**1. python -m pip install --upgrade pip**

Then, try to install the grpcio package directly using pip:

**2. pip install grpcio**

If the installation of grpcio succeeds, you can try installing Flowise again using pip:

**3. pip install Flowise**

If you still encounter the same error message, you can try installing a specific version of grpcio that is known to work with Flowise. You can find the compatible versions of grpcio in the requirements.txt file of the Flowise repository. For example, to install version 1.36.0, you can run:

**4. pip install grpcio==1.36.0**

I hope these steps will help you solve the installation issue.

**Comment by Arshdeep-13** [comment]
### **You can also these tags to enhance your website :-**

`<meta property="og:title" content="Website Title">`
`<meta property="og:description" content="Website description">`
`<meta property="og:image" content="https://example.com/image.jpg">`
`<meta property="og:url" content="https://example.com">`
`<meta property="og:type" content="article">`
`<meta property="og:site_name" content="Example Site">`
`<meta property="og:locale" content="en_US">`

**Comment by Arshdeep-13** [comment]
### You can also add these tags to enchance your website :-
```html

  <meta property="og:title" content="Website Title">
  <meta property="og:description" content="Website description">
  <meta property="og:image" content="https://example.com/image.jpg">
  <meta property="og:url" content="https://example.com">
  <meta property="og:type" content="article">
  <meta property="og:site_name" content="Example Site">
  <meta property="og:locale" content="en_US">


``` 
#

**Comment by HenryHengZJ** [comment]
As this is not a NextJS type of front end only website, hence we don't see the needs of adding these tags. Having said that, you can always fork the repo and add it to your forked repo
