### ISSUE TITLE
[BUG] Conversational QA Chain seems not reacting on System message

### ISSUE THREAD

**Issue by artemdzyuba** [FlowiseAI/Flowise#601]
**Describe the bug**
I put a system description, tried different prompts there. Doesn't see any reaction. 
I tried messages like "You are a pirate". And when asking if it is a pirate, it tells no
Or I put a name: "You name is Jarvis". And after asking it's name I get "I am an AI assistant and do not have a name."

**To Reproduce**

1. Add a Conversational QA Chain along with other components
2. Click on 'Additional parameters'
3. Type 'You are an old pirate'
4. Save and ask if it is a pirate.

**Expected behavior**
"Yes, iIm a pirate"

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/20184727/0dba9c72-4c31-47e0-9e8f-b2aa1eef1252)
![image](https://github.com/FlowiseAI/Flowise/assets/20184727/8c85cb08-08ec-4b57-a1c4-8cd445d96cd7)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation - docker
-   Flowise Version 1.2.16
-   OS: [e.g. macOS, Windows, Linux] - Linux
-   Browser [e.g. chrome, safari] - chrome

**Comment by atishamte** [comment]
I have also faced this problem.

When you choose any chain option, you can see a second input below the system prompt, it neglects the system prompt.

**Comment by nieljacobs** [comment]
There’s also an issue if you try to override the system message from an API call. The system message in the override gets ignored.

**Comment by HenryHengZJ** [comment]
thanks for the bug guys!

with this PR merged, I believe it solved the issue (not yet pushed to new release)

- Map Reduce
![1](https://github.com/FlowiseAI/Flowise/assets/26460777/31b1f78f-470d-4a11-9fdd-a50caade6841)

- Refine
![2](https://github.com/FlowiseAI/Flowise/assets/26460777/5c418809-4f8e-4c56-b28e-37b68ee847e5)

- Stuff (If not selected, this is used by default)
![3](https://github.com/FlowiseAI/Flowise/assets/26460777/8e204d0e-7e47-4e42-9300-a316427d97f1)

**Comment by nieljacobs** [comment]
Thanks Henry. I'm still having an issue when I try to add a systemMessage in the overrideConfig object send through the API on a Conversation Chain. The systemMessage in overrideConfig gets ignored.
Thanks

**Comment by nieljacobs** [comment]
> Thanks Henry. I'm still having an issue when I try to add a systemMessage in the overrideConfig object send through the API on a Conversation Chain. The systemMessage in overrideConfig gets ignored. Thanks

Ignore this. I changed systemMessage to systemMessagePrompt and it works now. Thanks

**Comment by HenryHengZJ** [comment]
should be resolved in latest version `v1.3.1`. Feel free to reopen if still seeing same issues
