### ISSUE TITLE
[BUG] Error: Single '}' in template.

### ISSUE THREAD

**Issue by Dan-Profind** [FlowiseAI/Flowise#606]
**Describe the bug**
After adding Cheerio Web Scraper to a basic chat template, trying to prompt the chat results in a 500 internal server error. Removing the scraper module from the template thereafter to try without it results in same error, seemingly corrupting other modules on the initial error call. Works as intended before introducing web scraper.
Template is very simple and works fine until the scraper module is introduced into it.

Conversation Chain module (no additioonal params):
     -> ChatOpenAI (Language Model)
             - Valid API key provided, gpt-3.5-turbo, temp. 0.7, no additional params
     -> Buffer Memory (Memory)
             - Default values for Memory Key and Input Key
     -> Cheerio Web Scraper (Document)
             - No additional params, providing 'https://www.careerplanner.com/ListOfCareers.cfm' as URL

Tried to stack trace it and seems like it originates from ~/static/js/views/chatmessage/ChatMessage.js  addChatMessage.js line 75 but could be way off, just following the stack trace of the error with some debug tools.
 
**To Reproduce**

1. Create a new template
2. Replicate the above template I have detailed above (provided you have a valid OpenAi API key)
3. Save the template and open the chat box
4. Type anything in (I just type 'hi' for faster testing)

For further testing:
1. Replicate the above template WITHOUT the scraper module
2. Test the chat
3. Introduce the web scraper module and test the chat again
4. Remove the web scraper and test the chat again

**Expected behavior**
A response from ChatGPT based on the previous prompt with additional context from the scraped document.

**Setup**
Fresh install of flowise on MacOS but has been tested and replicated on Windows 11 as well as WSL on Windows.

**Additional context**
My first bug report on GitHub, hope I did alright but go easy on me anyway ;)

**Comment by HenryHengZJ** [comment]
hey thanks for the details!

so you're including whole document into the context window which can easily over the context limit. 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/6c5661bb-8236-405c-87bf-3ce14167d955)

The reason why a Document anchor is there, is because for model like Antropic Claude 2 which has 100k context, you can ingest the whole document without upserting and query via vector database. However for model like ChatGPT which usually have 16k or GPT4 32k context, it might not be enough

**Comment by abslearn** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/52988245/1d987a14-3adf-4999-98a6-966e85c8baad)
![image](https://github.com/FlowiseAI/Flowise/assets/52988245/f41f3f43-4658-4116-b742-8e9be6993e38)

I've tried using the Cheerio Web Scraper with https://google.com, I keep getting this error: Error: Single '}' in template.
Screenshots attached. Appreciate any help @HenryHengZJ

**Comment by chungyau97** [comment]
Solution #624
