### ISSUE TITLE
[BUG] ChatOpenAI uses "parseInt" where it should use "parseFloat" instead

### ISSUE THREAD

**Issue by rozek** [FlowiseAI/Flowise#610]
**Describe the bug**
the "topP" parameter is parsed using `parseInt` rather than `parseFloat`

**Comment by rozek** [comment]
the "OpenAI" llm has the same problem...

**Comment by HenryHengZJ** [comment]
nice spot! will fix that

**Comment by rozek** [comment]
Thank you very much!

Both for this fix in particular and Flowise in general!

**Comment by chungyau97** [comment]
#617

**Comment by HenryHengZJ** [comment]
closing as #617 merged
