### ISSUE TITLE
Api key is used with unsecure connection. Bad Request [BUG]

### ISSUE THREAD

**Issue by prononext** [FlowiseAI/Flowise#616]
**Describe the bug**
When doing a LocalAI QA Workflow I get a Bad Request error. When doing the same with OpenAI it workes without problems.

![image](https://github.com/FlowiseAI/Flowise/assets/24569958/ce360ac6-1d0f-4d45-b09f-b5db58dc0c0f)

**Logs:**
2023-07-25 15:04:25 [ERROR]: [server]: Error: Error: Bad Request
Error: Error: Bad Request
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:227:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:708:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:427:13
2023-07-25 15:04:25 [INFO]: ⬆️ POST /api/v1/chatmessage/80cbf5e8-d6d7-42b8-a6da-67972a46d9a3
2023-07-25 15:05:33 [INFO]: ⬆️ POST /api/v1/chatmessage/80cbf5e8-d6d7-42b8-a6da-67972a46d9a3
2023-07-25 15:05:34 [INFO]: ⬆️ POST /api/v1/internal-prediction/80cbf5e8-d6d7-42b8-a6da-67972a46d9a3
Api key is used with unsecure connection.
2023-07-25 15:05:34 [ERROR]: Bad Request
Error: Bad Request
    at Object.fun [as upsertPoints] (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/openapi-typescript-fetch/dist/cjs/fetcher.js:150:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async QdrantClient.upsert (/usr/local/lib/node_modules/flowise/node_modules/@qdrant/js-client-rest/dist/cjs/qdrant-client.js:488:26)
    at async QdrantVectorStore.addVectors (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/qdrant.cjs:66:9)
    at async QdrantVectorStore.addDocuments (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/qdrant.cjs:51:9)
    at async QdrantVectorStore.fromDocuments (/usr/local/lib/node_modules/flowise/node_modules/langchain/dist/vectorstores/qdrant.cjs:111:9)
    at async QdrantUpsert_VectorStores.init (/usr/local/lib/node_modules/flowise/node_modules/flowise-components/dist/nodes/vectorstores/Qdrant_Upsert/Qdrant_Upsert.js:93:29)
    at async buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:217:50)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:708:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:427:13
2023-07-25 15:05:34 [ERROR]: [server]: Error: Error: Bad Request
Error: Error: Bad Request
    at buildLangchain (/usr/local/lib/node_modules/flowise/dist/utils/index.js:227:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.processPrediction (/usr/local/lib/node_modules/flowise/dist/index.js:708:44)
    at async /usr/local/lib/node_modules/flowise/dist/index.js:427:13
2023-07-25 15:05:34 [INFO]: ⬆️ POST /api/v1/chatmessage/80cbf5e8-d6d7-42b8-a6da-67972a46d9a3

**To Reproduce**

1. Have a LocalAI instance with bert-embeddings and gpt4all-j ready
2. Create a QnA Workflow on Flowise using a qdrant Database

**Expected behavior**
Chat is working without problems

I have compared direct API calls to qdrant, openai and localai for every single step in the process of the QnA workflow to be sure and there is no difference between localai compared to openai  in the responses given. 
The only difference is that qdrant is storing the openai embeddings but not the localai embeddings even if the api response is the same between localai and openai. Stragely the localai is creating a qdrant collection but without any content. 

**Be sure that every single step of the process is tested without using Flowise also by doing plain API calls, to be sure that the problem is inside the Flowise workflow.**

I am quite new in the field and maybe I have overlooked something.

**Comment by chungyau97** [comment]
Are you running Flowise on `yarn`, `docker` or `npx`?

**Comment by prononext** [comment]
I am running on docker on latest version, sorry.

**Comment by prononext** [comment]
I also noticed that when I replace the LocalAI Embeddings node with a OpenAI node but keep the main LocalAI node for Chat Completion it works. Very strange as the API Request for embeddings between LocalAI to bert-embeddings and OpenAI to text-embedding-ada-002 have the same response output...

**Comment by chungyau97** [comment]
Hi @prononext,

If you're running on [Docker Compose Flowise](https://github.com/flowiseai/flowise#docker-compose), you need to modify the Flowise and LocalAI `docker-compose.yml`.
This is to open a network of communication between 2 docker

Examples:
1. [LocalAI](https://github.com/FlowiseAI/Flowise/discussions/528#discussioncomment-6506411)
2. [Chroma](https://docs.flowiseai.com/vector-stores/chroma#additional)

**Comment by vladaman** [comment]
I am experiencing the same issue with n8n running in docker and **not using Flowise**. When using embeddings with qdrant store the task gets stuck in execution mode. The logs contains the following:

```
n8n-1  | Api key is used with unsecure connection.
n8n-1  | Api key is used with unsecure connection.
n8n-1  | Request timed out.
n8n-1  | TimeoutError: Request timed out.
n8n-1  |     at wrapOpenAIClientError (/usr/local/lib/node_modules/n8n/node_modules/@langchain/openai/dist/utils/openai.cjs:14:17)
n8n-1  |     at /usr/local/lib/node_modules/n8n/node_modules/@langchain/openai/dist/embeddings.cjs:275:69
n8n-1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5)
n8n-1  |     at RetryOperation._fn (/usr/local/lib/node_modules/n8n/node_modules/p-retry/index.js:50:12)
```

![image](https://github.com/user-attachments/assets/e60f894e-c319-42e7-b7a4-ce4edbef1d42)


```
docker image inspect docker.n8n.io/n8nio/n8n
[
    {
        "Id": "sha256:139317e73218a5805a68f04673d4a925f1846d4a9a4aab286962b790ad3c2fb3",
        "RepoTags": [
            "docker.n8n.io/n8nio/n8n:latest"
        ],
        "RepoDigests": [
            "docker.n8n.io/n8nio/n8n@sha256:d4821fb27106870a987145aa1914bdfc9f253251a751a29a76c0f8d5c2af6e24"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-12-12T14:00:57.434014606Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "node",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5678/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "NODE_VERSION=20.18.0",
                "YARN_VERSION=1.22.22",
                "NODE_ICU_DATA=/usr/local/lib/node_modules/full-icu",
                "N8N_VERSION=1.72.1",
                "NODE_ENV=production",
                "N8N_RELEASE_TYPE=stable",
                "SHELL=/bin/sh"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": null,
            "WorkingDir": "/home/node",
            "Entrypoint": [
                "tini",
                "--",
                "/docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {
                "org.opencontainers.image.description": "Workflow Automation Tool",
                "org.opencontainers.image.source": "https://github.com/n8n-io/n8n",
                "org.opencontainers.image.title": "n8n",
                "org.opencontainers.image.url": "https://n8n.io",
                "org.opencontainers.image.version": "1.72.1"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 656286577,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/1a81725b7ed826f4147fab37e8c00a59e7b8425b1ed6a3f4ac6760808a39721a/diff:/var/lib/docker/overlay2/3b558b77d22c0d44a20039ca49e9a684fb8ba86eb492b77b327a003007ca3017/diff:/var/lib/docker/overlay2/28e0d62114ad726d20086d3d095bb12b88d96610ccfe7980b7ae689322126b14/diff:/var/lib/docker/overlay2/590f7d2a283af8d2e80dfadecd5e48fbd06de44f35aa95792c5b581f06c9f025/diff:/var/lib/docker/overlay2/7ebcd04a46feff6a5177b74af61ac29f9904df1b0d272bd555fa292383b0b62e/diff:/var/lib/docker/overlay2/d61c21a6c1a8235be5c107b0434026cae5a0ee28a6b3618de913e78abddb154c/diff:/var/lib/docker/overlay2/28a73a76556565fb32a864a9656741209b981c781f746874c0ce562262058795/diff:/var/lib/docker/overlay2/cccdedb7fdcbdf3ccf952aa9fab4f455a8d2d46b27bf24cc814427ee358995f5/diff:/var/lib/docker/overlay2/0d0a6760e9954773250f31d6a8d5035eb08c214bf6f1bfe79a6001bcc7a6c767/diff:/var/lib/docker/overlay2/6f2deb4e21aa8ef58085321d3640ee33cd231d6d7961c1a89b42a166693756e9/diff:/var/lib/docker/overlay2/71ef3ccf356ca945de175846e43b0dcdddc71ffbc2d0485c38b96e63fcadc320/diff:/var/lib/docker/overlay2/475a677ea7c0598745a7ccc3d73a46b57e325301bce0b2724b0810fc35b2da67/diff",
                "MergedDir": "/var/lib/docker/overlay2/13a147639ba1952c88d9de073d00adfcf9e5cb31c9376caf94fdc93774bcc0ad/merged",
                "UpperDir": "/var/lib/docker/overlay2/13a147639ba1952c88d9de073d00adfcf9e5cb31c9376caf94fdc93774bcc0ad/diff",
                "WorkDir": "/var/lib/docker/overlay2/13a147639ba1952c88d9de073d00adfcf9e5cb31c9376caf94fdc93774bcc0ad/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:63ca1fbb43ae5034640e5e6cb3e083e05c290072c5366fcaa9d62435a4cced85",
                "sha256:9e884bd721881ef518283e1aea76c3575e68be9b4a577f1dd3476d51b8237e66",
                "sha256:70736de621abc27e1cc19a59bb958bc94eb567dcaeeb361e8c5f8ce7b2639023",
                "sha256:04f5f57834bac45ff193dee87cbdde5c3eb8b5cd9f3e183e61b78092882ec62f",
                "sha256:4ca75f6253f0b693c2a9d6f59d9b7e3c30a3979963f4202dbbc10eba242d7f1a",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:acc930f088f832dfad94c9593bc0f5c85c4bc93fbeac8a1d38ee46bc07771f5c",
                "sha256:e03a4a65040ebd09fef6bb3355e05057d53c9f9daad8d596e0838182959aa9be",
                "sha256:b0987299034125ea0d7ab67400e47fdcb2abf6e970a8fa3f5b41ad383dc0db0a",
                "sha256:0b8bc993e16b70fe65a007beed7e237bd3751fc61c74ea06c6fb9b0568165198",
                "sha256:83259a88c9af27c57c4268ef90c045d26090b48c695a01c4ff4e85b80dd1da99"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]
```
