### ISSUE TITLE
Docker Secrets Compability in sensitive ENVs

### ISSUE THREAD

**Issue by prononext** [FlowiseAI/Flowise#623]
### Description

It would be really nice to have the possibility to use Docker Secrets on the following ENV. The ENVs should support the _FILE suffix to get it working like this:

        - DATABASE_NAME_FILE=/run/secrets/FLOWISE_POSTGRES_DB
        - DATABASE_USER_FILE=/run/secrets/FLOWISE_POSTGRES_USER
        - DATABASE_PASSWORD_FILE=/run/secrets/FLOWISE_POSTGRES_PASSWORD
        - FLOWISE_USERNAME_FILE=/run/secrets/FLOWISE_GUI_USER
        - FLOWISE_PASSWORD_FILE=/run/secrets/FLOWISE_GUI_PASSWORD
        - PASSPHRASE_FILE=/run/secrets/FLOWISE_ENCRYPTION_PASSPHRASE

So you can use the docker stack in a more save manner and create the docker secrets before you run the stack in a excrypted manner https://docs.docker.com/engine/reference/commandline/secret_create/

```
version: '3.9'

services:

  flowise: 
    image: docker.io/flowiseai/flowise:1.2.16
    command: /bin/sh -c "sleep 3; flowise start"
    secrets:
      # Database Postgresql
      - FLOWISE_POSTGRES_DB
      - FLOWISE_POSTGRES_PASSWORD 
      - FLOWISE_POSTGRES_USER
      # Flowise Access
      - FLOWISE_GUI_USER
      - FLOWISE_GUI_PASSWORD
      # Flowise Security
      - FLOWISE_ENCRYPTION_PASSPHRASE
    environment:
        - PORT=3000
        - DATABASE_TYPE=postgres
        - DATABASE_PORT=5432
        - DATABASE_HOST=flowise-postgresql
        - DATABASE_NAME_FILE=/run/secrets/FLOWISE_POSTGRES_DB
        - DATABASE_USER_FILE=/run/secrets/FLOWISE_POSTGRES_USER
        - DATABASE_PASSWORD_FILE=/run/secrets/FLOWISE_POSTGRES_PASSWORD
        - APIKEY_PATH=/root/.flowise
        - LOG_PATH=/root/.flowise/logs
        - FLOWISE_USERNAME_FILE=/run/secrets/FLOWISE_GUI_USER
        - FLOWISE_PASSWORD_FILE=/run/secrets/FLOWISE_GUI_PASSWORD
        - PASSPHRASE_FILE=/run/secrets/FLOWISE_ENCRYPTION_PASSPHRASE
        - DEBUG=true
        - LOG_LEVEL=debug
        - EXECUTION_MODE=main
        #- TOOL_FUNCTION_BUILTIN_DEP=*
        #- TOOL_FUNCTION_EXTERNAL_DEP=moment,lodash
    ports:
        - '3000:3000'
    volumes:
        - flowise_data:/root/.flowise
    networks:
      - ai-net        
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
        
networks:
    ai-net:

volumes:
  flowise_data:   
  flowise_db_data:    

secrets:
  #Flowise Application
  FLOWISE_GUI_USER:
    name: FLOWISE_GUI_USER
    external: true
  FLOWISE_GUI_PASSWORD:
    name: FLOWISE_GUI_PASSWORD
    external: true
  FLOWISE_ENCRYPTION_PASSPHRASE:
    name: FLOWISE_ENCRYPTION_PASSPHRASE
    external: true
  # Flowise Postgres Database   
  FLOWISE_POSTGRES_DB:
    name: FLOWISE_POSTGRES_DB
    external: true
  FLOWISE_POSTGRES_PASSWORD:
    name: FLOWISE_POSTGRES_PASSWORD
    external: true
  FLOWISE_POSTGRES_USER:
    name: FLOWISE_POSTGRES_USER
    external: true        
```

**Comment by gregoryca** [comment]
Have you tried creating a .env file, and use the secrets defined in the env file in the docker compose ? it should work exactly how you want.

So for example, DATABASE_NAME_FILE="/run/secrets/FLOWISE_POSTGRES_DB".
And then in compose you could try:
DATABASE_NAME_FILE={DATABASE_NAME_FILE}

**Comment by prononext** [comment]
no I did not use that and also cannot. some setups do not allow .env files. Therefore almost all standard services like databases have implemented the _FILE suffix to be compatible with their .envs

**Comment by gregoryca** [comment]
Or try to append them as a command opposed to adding them via an .env file

**Comment by prononext** [comment]
> 

Yes did that, but service crashed somehow.
I suppose its better to go the standard way and just accept the _FILE suffix for working with secrets on envs.

**Comment by gregoryca** [comment]
do you have crash logs for example. Could be something in the docker-compose stack, and not perse the service

**Comment by gregoryca** [comment]
There are quite some good alternatives looking at this stackoverflow link - https://stackoverflow.com/questions/48094850/docker-stack-setting-environment-variable-from-secrets
