### ISSUE TITLE
[BUG]  PineconeClient: Error calling upsert

### ISSUE THREAD

**Issue by Ledjob** [FlowiseAI/Flowise#632]
ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response

I'm trying to use Pinecone Upsert Document but I have this error each time I try to speak to the bot. 

**Screenshots**
https://imgur.com/a/6Lrmbsu

`[ERROR]: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response
2023-07-27 18:56:51 [ERROR]: [server]: Error: ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response
Error: ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response
    at buildLangchain (C:\Users\EP\AppData\Roaming\npm\node_modules\flowise\dist\utils\index.js:227:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async App.processPrediction (C:\Users\EP\AppData\Roaming\npm\node_modules\flowise\dist\index.js:708:44)
    at async C:\Users\EP\AppData\Roaming\npm\node_modules\flowise\dist\index.js:427:13`

**Setup**
-  npm install -g flowise
-  node -v : v20.5.0
-   OS: [Windows]
-   Browser [e.g. chrome]

**Comment by rickaustin** [comment]
I seem to be having a similar issue:
- Flowise starts, I am able to set up a flow, save it, etc.
- Simple PDF reader (three PDF files), OpenAI LLM and Embeddings
- When I ask it a question, I get...

ErrorWithoutStackTrace: PineconeClient: Error calling upsert: ErrorWithoutStackTrace: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response

**Comment by chungyau97** [comment]
Hi @Ledjob and @rickaustin,

Could you guys try the pay version of Pinecone? 
If not you guys can give Supabase a try

**Comment by rickaustin** [comment]
Unfortunetly, while exploring I won't be paying Pinecone $70/month. Any thoughts as to why Pinecone is misbehaving for this use case? Any expectation as to why Supabase would work and Pinecone would not?

Lastly, seems at least Supabase and Chroma can be run locally - do you forsee any issues running either locally?

**Comment by Justinandjohnson** [comment]
Getting this same error. II wonder why this is happening.

**Comment by HenryHengZJ** [comment]
possibly related - https://github.com/mayooear/gpt4-pdf-chatbot-langchain/issues/97

**Comment by Justinandjohnson** [comment]
So, for anyone else that runs into this issue. 
The solution: 

Create a pinecone index with 1536 Dimensions. 

Problem solved.

**Comment by rickaustin** [comment]
Hi @Justinandjohnson - thanks much! How did you figure this out (and wondering if setup shouldn't have done this out of the box)?

**Comment by chungyau97** [comment]
Hi @rickaustin,

Troubleshoot steps:
1. Your `NodeJS` version? >= 18.15.0
2. Try [Supabase](https://docs.flowiseai.com/vector-stores/supabase)
3. Install Flowise on other device [WSL/VM]

**Comment by Justinandjohnson** [comment]
I watched a bunch  of videos and then finally noticed this trend in errors devs got while setting this up.
