### ISSUE TITLE
[BUG] Conversational Retrieval QA Chain Node won't accepts BufferMemory

### ISSUE THREAD

**Issue by darkcurrent** [FlowiseAI/Flowise#633]
**Bug description:**
When using "Conversational Retrieval QA Chain Node", the memory is not activated by default. While mouse hover on the memory pin _(see screenshot below)_ it says "If no memory connected, BufferMemory will be used." Leaving it is not connected won't activate a BufferMemory, all the previous entries is forgotten by the chain. And the BufferMemory is not an allowed memory type for this node. So you can not connect by yourself.

**Expected behavior:**

- Chat memory should be conserved.
- Node should be accept to connect the BufferMemory.

**Screenshot:**
![image](https://github.com/FlowiseAI/Flowise/assets/6089944/732c3701-b13a-495d-bdea-83ecb02fed54)

**Setup:**
-   Installation: docker
-   Flowise Version 1.2.16
-   OS: Ubuntu 20.04

**Comment by chungyau97** [comment]
Hi @darkcurrent,

Thanks for the bug. 
I went and check whether the memory is initialize and found out it was initialize.
Currently look like our default `System Message` is causing the issue.

**Comment by HenryHengZJ** [comment]
I tested and it did remember conversations: 

![image](https://github.com/FlowiseAI/Flowise/assets/26460777/96959536-6d7e-482c-9820-41d63b3223a5)

Also in v1.3.0 it allows all memory types to be connected

**Comment by darkcurrent** [comment]
I have also updated to 1.3.0 and memory works. 

> I tested and it did remember conversations:
> Also in v1.3.0 it allows all memory types to be connected

Do you mean only DynamoDBChatMemory, RedisBakedChatMemory and ZepMemory are working? Or do you mean all the available memory types in the memory menu? I am asking because Conversation Summary Memory can't be connected to the Conversational Retrieval QA Chain.

**Comment by HenryHengZJ** [comment]
delete the current Conver.QA Chain node and readd it from menu, then you should be able to connect all types of memory (recently found a bug where RedisBackedChatMemory doesnt work with Conver.QA Chain)

**Comment by darkcurrent** [comment]
I deleted the node than readded from the menu and cant connect all the memory types. Only 3 of them can be connected.
I also created a new flow and add Conversational retrieval QA Chain from the menu and no luck...

![image](https://github.com/FlowiseAI/Flowise/assets/6089944/52ffb741-f6c5-481d-a908-9667d8293b0c)

**Comment by HenryHengZJ** [comment]
@darkcurrent dont think you have upgraded to 1.3.0 onwards, as you can see the icons circled red are still there, it should be gone for new release: 

![image](https://github.com/FlowiseAI/Flowise/assets/26460777/5b6e7ab1-e008-45f9-9511-4bb3cb4112a8)

if you are using docker, try pulling the latest image `docker pull flowiseai/flowise`, or reinstall `npm install -g flowise` if using npx
