### ISSUE TITLE
[BUG] Conversational Retrieval QA Chain "Cannot set properties of undefined (setting 'llm')"

### ISSUE THREAD

**Issue by josh900** [FlowiseAI/Flowise#636]
**Describe the bug**
When using Conversational Retrieval QA Chain after sending the second message in a chat I always get back "Cannot set properties of undefined (setting 'llm')" no matter what I've tried

**To Reproduce**

1. Create flow with Conversational Retrieval QA Chain and some type of vector retriever
2. send first message
3. send second message

**Expected behavior**
I send the second message and keep chatting as usual 

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/6858436/37ed49fc-a27c-47e6-b4f4-d6712bf08848)

**Flow**
`{"nodes":[{"width":300,"height":378,"id":"markdownTextSplitter_0","position":{"x":1081.1540334344143,"y":-112.79571289117655},"type":"customNode","data":{"id":"markdownTextSplitter_0","label":"Markdown Text Splitter","version":1,"name":"markdownTextSplitter","type":"MarkdownTextSplitter","baseClasses":["MarkdownTextSplitter","RecursiveCharacterTextSplitter","TextSplitter","BaseDocumentTransformer"],"category":"Text Splitters","description":"Split your content into documents based on the Markdown headers","inputParams":[{"label":"Chunk Size","name":"chunkSize","type":"number","default":1000,"optional":true,"id":"markdownTextSplitter_0-input-chunkSize-number"},{"label":"Chunk Overlap","name":"chunkOverlap","type":"number","optional":true,"id":"markdownTextSplitter_0-input-chunkOverlap-number"}],"inputAnchors":[],"inputs":{"chunkSize":"500","chunkOverlap":"50"},"outputAnchors":[{"id":"markdownTextSplitter_0-output-markdownTextSplitter-MarkdownTextSplitter|RecursiveCharacterTextSplitter|TextSplitter|BaseDocumentTransformer","name":"markdownTextSplitter","label":"MarkdownTextSplitter","type":"MarkdownTextSplitter | RecursiveCharacterTextSplitter | TextSplitter | BaseDocumentTransformer"}],"outputs":{},"selected":false},"selected":false,"positionAbsolute":{"x":1081.1540334344143,"y":-112.79571289117655},"dragging":false},{"width":300,"height":407,"id":"memoryVectorStore_0","position":{"x":1845.7166174330946,"y":484.60473328470243},"type":"customNode","data":{"id":"memoryVectorStore_0","label":"In-Memory Vector Store","version":1,"name":"memoryVectorStore","type":"Memory","baseClasses":["Memory","VectorStoreRetriever","BaseRetriever"],"category":"Vector Stores","description":"In-memory vectorstore that stores embeddings and does an exact, linear search for the most similar embeddings.","inputParams":[{"label":"Top K","name":"topK","description":"Number of top results to fetch. Default to 4","placeholder":"4","type":"number","optional":true,"id":"memoryVectorStore_0-input-topK-number"}],"inputAnchors":[{"label":"Document","name":"document","type":"Document","list":true,"id":"memoryVectorStore_0-input-document-Document"},{"label":"Embeddings","name":"embeddings","type":"Embeddings","id":"memoryVectorStore_0-input-embeddings-Embeddings"}],"inputs":{"document":["{{github_0.data.instance}}"],"embeddings":"{{openAIEmbeddings_0.data.instance}}","topK":"3"},"outputAnchors":[{"name":"output","label":"Output","type":"options","options":[{"id":"memoryVectorStore_0-output-retriever-Memory|VectorStoreRetriever|BaseRetriever","name":"retriever","label":"Memory Retriever","type":"Memory | VectorStoreRetriever | BaseRetriever"},{"id":"memoryVectorStore_0-output-vectorStore-Memory|VectorStore","name":"vectorStore","label":"Memory Vector Store","type":"Memory | VectorStore"}],"default":"retriever"}],"outputs":{"output":"retriever"},"selected":false},"selected":false,"positionAbsolute":{"x":1845.7166174330946,"y":484.60473328470243},"dragging":false},{"width":300,"height":481,"id":"conversationalRetrievalQAChain_0","position":{"x":2311.697827287373,"y":228.14841720207832},"type":"customNode","data":{"id":"conversationalRetrievalQAChain_0","label":"Conversational Retrieval QA Chain","version":1,"name":"conversationalRetrievalQAChain","type":"ConversationalRetrievalQAChain","baseClasses":["ConversationalRetrievalQAChain","BaseChain"],"category":"Chains","description":"Document QA - built on RetrievalQAChain to provide a chat history component","inputParams":[{"label":"Return Source Documents","name":"returnSourceDocuments","type":"boolean","optional":true,"id":"conversationalRetrievalQAChain_0-input-returnSourceDocuments-boolean"},{"label":"System Message","name":"systemMessagePrompt","type":"string","rows":4,"additionalParams":true,"optional":true,"placeholder":"I want you to act as a document that I am having a conversation with. Your name is \"AI Assistant\". You will provide me with answers from the given info. If the answer is not included, say exactly \"Hmm, I am not sure.\" and stop after that. Refuse to answer any question not about the info. Never break character.","id":"conversationalRetrievalQAChain_0-input-systemMessagePrompt-string"},{"label":"Chain Option","name":"chainOption","type":"options","options":[{"label":"MapReduceDocumentsChain","name":"map_reduce","description":"Suitable for QA tasks over larger documents and can run the preprocessing step in parallel, reducing the running time"},{"label":"RefineDocumentsChain","name":"refine","description":"Suitable for QA tasks over a large number of documents."},{"label":"StuffDocumentsChain","name":"stuff","description":"Suitable for QA tasks over a small number of documents."}],"additionalParams":true,"optional":true,"id":"conversationalRetrievalQAChain_0-input-chainOption-options"}],"inputAnchors":[{"label":"Language Model","name":"model","type":"BaseLanguageModel","id":"conversationalRetrievalQAChain_0-input-model-BaseLanguageModel"},{"label":"Vector Store Retriever","name":"vectorStoreRetriever","type":"BaseRetriever","id":"conversationalRetrievalQAChain_0-input-vectorStoreRetriever-BaseRetriever"},{"label":"Memory","name":"memory","type":"BaseMemory","optional":true,"description":"If left empty, a default BufferMemory will be used","id":"conversationalRetrievalQAChain_0-input-memory-BaseMemory"}],"inputs":{"model":"{{chatOpenAI_0.data.instance}}","vectorStoreRetriever":"{{memoryVectorStore_0.data.instance}}","memory":"","returnSourceDocuments":true,"systemMessagePrompt":"","chainOption":"stuff"},"outputAnchors":[{"id":"conversationalRetrievalQAChain_0-output-conversationalRetrievalQAChain-ConversationalRetrievalQAChain|BaseChain","name":"conversationalRetrievalQAChain","label":"ConversationalRetrievalQAChain","type":"ConversationalRetrievalQAChain | BaseChain"}],"outputs":{},"selected":false},"selected":false,"dragging":false,"positionAbsolute":{"x":2311.697827287373,"y":228.14841720207832}},{"width":300,"height":675,"id":"github_0","position":{"x":1460.1858988997,"y":-137.83585695472374},"type":"customNode","data":{"id":"github_0","label":"Github","version":1,"name":"github","type":"Document","baseClasses":["Document"],"category":"Document Loaders","description":"Load data from a GitHub repository","inputParams":[{"label":"Connect Credential","name":"credential","type":"credential","description":"Only needed when accessing private repo","optional":true,"credentialNames":["githubApi"],"id":"github_0-input-credential-credential"},{"label":"Repo Link","name":"repoLink","type":"string","placeholder":"https://github.com/FlowiseAI/Flowise","id":"github_0-input-repoLink-string"},{"label":"Branch","name":"branch","type":"string","default":"main","id":"github_0-input-branch-string"},{"label":"Recursive","name":"recursive","type":"boolean","optional":true,"id":"github_0-input-recursive-boolean"},{"label":"Metadata","name":"metadata","type":"json","optional":true,"additionalParams":true,"id":"github_0-input-metadata-json"}],"inputAnchors":[{"label":"Text Splitter","name":"textSplitter","type":"TextSplitter","optional":true,"id":"github_0-input-textSplitter-TextSplitter"}],"inputs":{"repoLink":"https://github.com/rtyley/small-test-repo","branch":"main","recursive":true,"textSplitter":"{{markdownTextSplitter_0.data.instance}}","metadata":""},"outputAnchors":[{"id":"github_0-output-github-Document","name":"github","label":"Document","type":"Document"}],"outputs":{},"selected":false},"selected":false,"positionAbsolute":{"x":1460.1858988997,"y":-137.83585695472374},"dragging":false},{"width":300,"height":525,"id":"chatOpenAI_0","position":{"x":1860.1873636456692,"y":-105.19095721504263},"type":"customNode","data":{"id":"chatOpenAI_0","label":"ChatOpenAI","version":1,"name":"chatOpenAI","type":"ChatOpenAI","baseClasses":["ChatOpenAI","BaseChatModel","BaseLanguageModel"],"category":"Chat Models","description":"Wrapper around OpenAI large language models that use the Chat endpoint","inputParams":[{"label":"Connect Credential","name":"credential","type":"credential","credentialNames":["openAIApi"],"id":"chatOpenAI_0-input-credential-credential"},{"label":"Model Name","name":"modelName","type":"options","options":[{"label":"gpt-4","name":"gpt-4"},{"label":"gpt-4-0613","name":"gpt-4-0613"},{"label":"gpt-4-32k","name":"gpt-4-32k"},{"label":"gpt-4-32k-0613","name":"gpt-4-32k-0613"},{"label":"gpt-3.5-turbo","name":"gpt-3.5-turbo"},{"label":"gpt-3.5-turbo-0613","name":"gpt-3.5-turbo-0613"},{"label":"gpt-3.5-turbo-16k","name":"gpt-3.5-turbo-16k"},{"label":"gpt-3.5-turbo-16k-0613","name":"gpt-3.5-turbo-16k-0613"}],"default":"gpt-3.5-turbo","optional":true,"id":"chatOpenAI_0-input-modelName-options"},{"label":"Temperature","name":"temperature","type":"number","default":0.9,"optional":true,"id":"chatOpenAI_0-input-temperature-number"},{"label":"Max Tokens","name":"maxTokens","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-maxTokens-number"},{"label":"Top Probability","name":"topP","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-topP-number"},{"label":"Frequency Penalty","name":"frequencyPenalty","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-frequencyPenalty-number"},{"label":"Presence Penalty","name":"presencePenalty","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-presencePenalty-number"},{"label":"Timeout","name":"timeout","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-timeout-number"},{"label":"BasePath","name":"basepath","type":"string","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-basepath-string"}],"inputAnchors":[],"inputs":{"modelName":"gpt-3.5-turbo","temperature":"0.5","maxTokens":"","topP":"","frequencyPenalty":"","presencePenalty":"","timeout":"","basepath":""},"outputAnchors":[{"id":"chatOpenAI_0-output-chatOpenAI-ChatOpenAI|BaseChatModel|BaseLanguageModel","name":"chatOpenAI","label":"ChatOpenAI","type":"ChatOpenAI | BaseChatModel | BaseLanguageModel"}],"outputs":{},"selected":false},"selected":false,"positionAbsolute":{"x":1860.1873636456692,"y":-105.19095721504263},"dragging":false},{"width":300,"height":330,"id":"openAIEmbeddings_0","position":{"x":1299.9983863833309,"y":581.8406384863323},"type":"customNode","data":{"id":"openAIEmbeddings_0","label":"OpenAI Embeddings","version":1,"name":"openAIEmbeddings","type":"OpenAIEmbeddings","baseClasses":["OpenAIEmbeddings","Embeddings"],"category":"Embeddings","description":"OpenAI API to generate embeddings for a given text","inputParams":[{"label":"Connect Credential","name":"credential","type":"credential","credentialNames":["openAIApi"],"id":"openAIEmbeddings_0-input-credential-credential"},{"label":"Strip New Lines","name":"stripNewLines","type":"boolean","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-stripNewLines-boolean"},{"label":"Batch Size","name":"batchSize","type":"number","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-batchSize-number"},{"label":"Timeout","name":"timeout","type":"number","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-timeout-number"},{"label":"BasePath","name":"basepath","type":"string","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-basepath-string"}],"inputAnchors":[],"inputs":{"stripNewLines":"","batchSize":"","timeout":"","basepath":""},"outputAnchors":[{"id":"openAIEmbeddings_0-output-openAIEmbeddings-OpenAIEmbeddings|Embeddings","name":"openAIEmbeddings","label":"OpenAIEmbeddings","type":"OpenAIEmbeddings | Embeddings"}],"outputs":{},"selected":false},"selected":false,"dragging":false,"positionAbsolute":{"x":1299.9983863833309,"y":581.8406384863323}}],"edges":[{"source":"memoryVectorStore_0","sourceHandle":"memoryVectorStore_0-output-retriever-Memory|VectorStoreRetriever|BaseRetriever","target":"conversationalRetrievalQAChain_0","targetHandle":"conversationalRetrievalQAChain_0-input-vectorStoreRetriever-BaseRetriever","type":"buttonedge","id":"memoryVectorStore_0-memoryVectorStore_0-output-retriever-Memory|VectorStoreRetriever|BaseRetriever-conversationalRetrievalQAChain_0-conversationalRetrievalQAChain_0-input-vectorStoreRetriever-BaseRetriever","data":{"label":""}},{"source":"markdownTextSplitter_0","sourceHandle":"markdownTextSplitter_0-output-markdownTextSplitter-MarkdownTextSplitter|RecursiveCharacterTextSplitter|TextSplitter|BaseDocumentTransformer","target":"github_0","targetHandle":"github_0-input-textSplitter-TextSplitter","type":"buttonedge","id":"markdownTextSplitter_0-markdownTextSplitter_0-output-markdownTextSplitter-MarkdownTextSplitter|RecursiveCharacterTextSplitter|TextSplitter|BaseDocumentTransformer-github_0-github_0-input-textSplitter-TextSplitter","data":{"label":""}},{"source":"github_0","sourceHandle":"github_0-output-github-Document","target":"memoryVectorStore_0","targetHandle":"memoryVectorStore_0-input-document-Document","type":"buttonedge","id":"github_0-github_0-output-github-Document-memoryVectorStore_0-memoryVectorStore_0-input-document-Document","data":{"label":""}},{"source":"chatOpenAI_0","sourceHandle":"chatOpenAI_0-output-chatOpenAI-ChatOpenAI|BaseChatModel|BaseLanguageModel","target":"conversationalRetrievalQAChain_0","targetHandle":"conversationalRetrievalQAChain_0-input-model-BaseLanguageModel","type":"buttonedge","id":"chatOpenAI_0-chatOpenAI_0-output-chatOpenAI-ChatOpenAI|BaseChatModel|BaseLanguageModel-conversationalRetrievalQAChain_0-conversationalRetrievalQAChain_0-input-model-BaseLanguageModel","data":{"label":""}},{"source":"openAIEmbeddings_0","sourceHandle":"openAIEmbeddings_0-output-openAIEmbeddings-OpenAIEmbeddings|Embeddings","target":"memoryVectorStore_0","targetHandle":"memoryVectorStore_0-input-embeddings-Embeddings","type":"buttonedge","id":"openAIEmbeddings_0-openAIEmbeddings_0-output-openAIEmbeddings-OpenAIEmbeddings|Embeddings-memoryVectorStore_0-memoryVectorStore_0-input-embeddings-Embeddings","data":{"label":""}}]}`

**Setup**
-   Installation [yarn start`]
-   Flowise Version [e.g. 1.3.0]  also happening on other recent commits
-   OS: [Linux]
-   Browser [chrome]

**Additional context**

**Comment by josh900** [comment]
I had EXECUTION_MODE=child.
Once setting this to EXECUTION_MODE=main this issue stopped. 

The problem there is when I use the Conversational Retrieval QA Chain it send back all the refinements or attempts and similar from the MapReduceDocumentChain and RefineDocumentChain which is confusing. 

I liked that EXECUTION_MODE=child made it so only the response is put into the chat window. 
Is there another way to accomplish this, or is this actually a bug with EXECUTION_MODE=child?

**Comment by HenryHengZJ** [comment]
so what you're looking for is turning off the streaming.

`EXECUTION_MODE=child` does not have streaming, so response return is the final response
Whereas `main` has streaming by default, response returned is the token output. However the final response should both looks the same

Try upgrade to latest version and see if the issue still persist
