### ISSUE TITLE
Flowise - Make.com - Telegram

### ISSUE THREAD

**Issue by hany-girgis** [FlowiseAI/Flowise#647]
I am currently working on building a custom knowledge chatbot that can access a vector database and interact with users through Telegram. For this project, I am using Flowise and have successfully connected it to my Pinecone database.

However, I'm facing some challenges in understanding how to send incoming chats from Telegram to Flowise and receive the responses back from Flowise. I would greatly appreciate your assistance in guiding me through this process. I am currently using make.com but somthing is wrong with the connection back and forth. for reciving the query and responding with the LLM.

If you need any further clarification or additional information about the project, please do not hesitate to ask.

Can you guide me?

Hany

**Comment by HenryHengZJ** [comment]
Hey here's a link that walkthrough how to connect Flowise to Telegram https://twitter.com/FlowiseAI/status/1684543294087258112?t=tziEKwynZ4Ar7Ah0TnNl4w&s=19

**Comment by hany-girgis** [comment]
> Hey here's a link that walkthrough how to connect Flowise to Telegram https://twitter.com/FlowiseAI/status/1684543294087258112?t=tziEKwynZ4Ar7Ah0TnNl4w&s=19

This is connecting it with a memory only with zep ai, do you know how to do it with make.com

**Comment by HenryHengZJ** [comment]
Maybe somebody else who have done it can chime in, but I would've expected a workflow like this:
Incoming Telegram webhook message -> HTTP (Flowise API) -> Send message to Telegram
docs on Flowise API: https://docs.flowiseai.com/how-to-use#api
