### ISSUE TITLE
[BUG] Exit process when database init fails

### ISSUE THREAD

**Issue by sebastien-prudhomme** [FlowiseAI/Flowise#648]
**Describe the bug**
Flowise process continue to live if database initialisation raise an exception. To make the application works better with orchestrators such as Kubernetes, the process should exit.

**To Reproduce**
Configure Flowise with an SQL database with a wrong database hostname.

**Expected behavior**
The application should exit.

**Setup**
-   Installation [e.g. docker + kubernetes]
-   Flowise Version 1.3.1
-   OS: Linux

**Comment by HenryHengZJ** [comment]
feel free to make a PR for that!
