### ISSUE TITLE
⚒️[FEATURE] SerpAPI Loader Integration

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#652]
## Describe the feature you'd like
SerpAPI Loader Integration
Docs: https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/serpapi

## ✅Tasks
- [ ] Add SerpAPI Loader node

## 🎯Acceptance Criteria
- [ ] SerpAPI loader node should be able to  load data from serpi API

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Gitbook](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Gitbook/Gitbook.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by fantastic-genius** [comment]
@HenryHengZJ I would like to work on this issue

**Comment by vishwasg217** [comment]
I would like to work and solve this issue

**Comment by fantastic-genius** [comment]
@vishwasg217 I am already working on this
