### ISSUE TITLE
⚒️[FEATURE] Sonix Audio Loader

### ISSUE THREAD

**Issue by HenryHengZJ** [FlowiseAI/Flowise#653]
## Describe the feature you'd like
Sonix Audio Loader Integration
Docs: https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/sonix_audio_transcription

## ✅Tasks
- [ ] Add Sonix Audio Loader node

## 🎯Acceptance Criteria
- [ ] Sonix Audio loader node should be able to load audio files into documents

## 👨‍💻How to contribute
Follow this [guide](https://github.com/FlowiseAI/Flowise/blob/main/CONTRIBUTING.md#step-by-step) for step by step on how to fork, commit, and submit PR.

## 👨‍💻Reference code
- [Gitbook](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/documentloaders/Gitbook/Gitbook.ts)

## More info
Like to work on this issue? Let us know, and we will assign it to you 🚀
If you need any help or just want to hangout, reach out to us on our [Discord server](https://discord.gg/jbaHfsRVBW)👾

**Comment by vermabraj** [comment]
what need to do here? I will do this,but i want a bit explaination about.

**Comment by chungyau97** [comment]
Hi @vermabraj,

I'm glad that you're interested in this feature. 😄 

Prerequisite: you got to register and get API [here](https://sonix.ai/)

You will need to map [this](https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/web_loaders/sonix_audio_transcription) into one of our template [[credentials input](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts#L26), [credentials class](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/credentials/OpenAIApi.credential.ts), [inputs](https://github.com/FlowiseAI/Flowise/blob/main/packages/components/nodes/chatmodels/ChatOpenAI/ChatOpenAI.ts#L32)]

**Comment by fantastic-genius** [comment]
@HenryHengZJ I would like to pick this up

**Comment by vermabraj** [comment]
@chungyau97 should i get to register and paid to get API for this feature ?

**Comment by HenryHengZJ** [comment]
if you already have the Sonix paid account, otherwise dont sweat it 😅

**Comment by vermabraj** [comment]
@chungyau97 but i can,t afford it,s subscription

**Comment by chungyau97** [comment]
Hey @vermabraj, don't worry about it. 😄

**Comment by uvamsi76** [comment]
Hi @chungyau97 I tried  the mapping of sonixai by taking openai thing as reference. I added the node of SonixAi in chatmodels and sonixapi.cred.ts file as well in credentials, The build was successful but i was getting an error after i did yarn start. Is there any extra modules that are need to be added? Can you please help me with that . I am pasting the error below .
"Error during Data Source initialization: Cannot find module 'sonix-speech-recognition'"
Thankyou.

**Comment by uvamsi76** [comment]
I did not raise the pr but these are the changes from my fork :https://github.com/uvamsi76/Flowise/tree/feature/SonixAi_Audio_Loader

This is the ss of the error : 
![image](https://github.com/FlowiseAI/Flowise/assets/84193223/1038a4aa-4f98-4d8a-badb-18371cc09b4a)
