### ISSUE TITLE
How can I create a flow using document loader and a prompt at the same time?

### ISSUE THREAD

**Issue by evilguru10101** [FlowiseAI/Flowise#656]
there is some tutorial online but nothing covering this issue
What i want to do is build a chatbot, that retreive information from a document, but behave in a certain manner, or present the information in a certain way, trough a prompt i have carefully given it.
here is my base model
![image](https://github.com/FlowiseAI/Flowise/assets/140845309/95de9722-eea1-4f8c-80be-1f2db31863c1)
WHICH work

here is what I want to mix it with 
![image](https://github.com/FlowiseAI/Flowise/assets/140845309/6cc6fbbf-2bb5-4266-863e-57a5d96201d5)

here is what I tried 
![image](https://github.com/FlowiseAI/Flowise/assets/140845309/11e29a31-cffc-49e6-bef4-c018181ff636)

but unfortunately it doesn't behave the way I want, I gave him the instruction

"you're Charlie Unicorn an expert in unicorn who retrieve information from the pdf file you have, without mentioning it, like the information came from you, you answer to the question asked without talking about anything else, and make a sshort joke at the end"
and he don't answer to the questions I ask he either just straight up come with his own question or just repeat the same thing.
![image](https://github.com/FlowiseAI/Flowise/assets/140845309/943b5d2d-12b1-4dc1-a7ec-fa3abac14b45)

**Comment by evilguru10101** [comment]
btw i don't know anything about python or coding, an I'm eager to learn more

**Comment by HenryHengZJ** [comment]
from the conversationalretrievalqachain node, click additional parameters, from there you can specify the system message prompt

**Comment by evilguru10101** [comment]
> from the conversationalretrievalqachain node, click additional parameters, from there you can specify the system message prompt: ![image](https://user-images.githubusercontent.com/26460777/257375933-f7202acd-5b2b-40c7-9241-e5c7571ecc28.png)

exactly  what i was looking for, thanks a lot

**Comment by evilguru10101** [comment]
> from the conversationalretrievalqachain node, click additional parameters, from there you can specify the system message prompt: ![image](https://user-images.githubusercontent.com/26460777/257375933-f7202acd-5b2b-40c7-9241-e5c7571ecc28.png)

btw your videos are great i love the help you're giving to the community. Keep up the good work.
Are you one of flowise founders?
I really don't understand how you make a profit at the end of the month

**Comment by HenryHengZJ** [comment]
Thanks! Yes I am. Well, we are not at the moment. It's all about helping more people from non tech background to have better and easier access to LLM framework
