### ISSUE TITLE
Integration of LangSmith

### ISSUE THREAD

**Issue by sergedahdouh** [FlowiseAI/Flowise#658]
Integration of LangSmith

I would like to propose the integration of LangSmith into the project. LangSmith is a platform designed for building production-grade Language Model (LLM) applications. It provides capabilities for debugging, testing, evaluating, and monitoring chains and intelligent agents built on any LLM framework. 

Please consider this feature request as I believe it would greatly benefit our project. Thank you for your time and consideration.

**Comment by renyuantime** [comment]
exactly, prompt engeering debugging is a must!

**Comment by renyuantime** [comment]
> we can already use LangSmith, just need to add the env variables - https://docs.flowiseai.com/environment-variables#langsmith-tracing

Need to pass thoese variables in  the compose file too. It's working now.
