### ISSUE TITLE
[FEATURE]How to achieve multiple rounds of dialogue

### ISSUE THREAD

**Issue by Pressten** [FlowiseAI/Flowise#661]
I want to use multiple rounds of dialogue.
like
first：I say something ，ai extract keywords from it
second：ai compare the extract keywords with doc in vector store to select konwledge
third：ai give answer by combining the extracted keywords with knowledge in the database

**Comment by iNdefHub** [comment]
You can start as follows:  
1 - System prompt :  "The following question from the user requires a single word answer only" - 
2 - Capture user question 
3 - convert user question to embedding 
4 - Send the embedded to be compared with you vectore store
5 - The response is sent to Ai for processing into natural language
6 - Ai processes the response and return a Json package to the client
7 - Process the content of the Json to display

**Comment by Pressten** [comment]
> You can start as follows: 1 - System prompt : "The following question from the user requires a single word answer only" - 2 - Capture user question 3 - convert user question to embedding 4 - Send the vector embedding to be compared with you vectore store 5 - The response is sent to Ai for processing into natural language 6 - Ai processes the response and return a Json package to the client 7 - Process the content of the Json to display

Can you show me how to build it? I'm a bit confused about how to build it

**Comment by Pressten** [comment]
chain1：
![图片](https://github.com/FlowiseAI/Flowise/assets/49391611/bd73a364-9f7a-4661-8a7c-8f00ba5dc19c)
chain2：
![图片](https://github.com/FlowiseAI/Flowise/assets/49391611/edfa562a-4899-42b8-b4cf-af33e8045ee5)
head：
![图片](https://github.com/FlowiseAI/Flowise/assets/49391611/07b7d2a4-a1f9-45ed-bee2-5afdb7241325)

I build this ，but it works bad

**Comment by iNdefHub** [comment]
Haha, ok I'll replicate what you have done and get back to you
