### ISSUE TITLE
[BUG] No place to input OpenAPI key After upgrade

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#663]
**Describe the bug**

i upgraded flowise through npx packages update and after that i am unable to find a placeholder for openai keys

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/141017916/57379bc6-5aac-40cc-82a6-34088eaa24c8)

**Setup**
-   Installation [`npx flowise start`]
-   Flowise Version [e.g. 1.3.0]
-   OS: [ Linux]
-   Browser [chrome]

**Comment by HenryHengZJ** [comment]
Try delete and add it from the menu again. In dashboard you should be able to see Credentials
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/6cd1d509-5ed2-40c8-8f06-f6a4b4174bf3)

and node:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/8c4eee81-ad0e-490d-bbe7-529d89f1a792)
