### ISSUE TITLE
Feature Request - Adding Support for Bot asking Optional Type Questions and It builds context based on user response [FEATURE]

### ISSUE THREAD

**Issue by Vikson97** [FlowiseAI/Flowise#664]
**Issue Description:**
As a user of Flowise, I would like to propose a feature enhancement that allows the chatbot to ask optional type questions to users. The implementation of this feature will enable the chatbot to create context based on the user's responses, leading to more engaging and personalized conversations.

**Problem Statement:**
Currently, the chatbot in Flowise lacks the ability to ask optional questions to users. As a result, the conversation flow may become rigid and less interactive, hindering the bot's ability to gather specific information for context generation. By incorporating the proposed feature, the chatbot will be empowered to prompt users with optional questions, thus capturing additional relevant details and enriching the context.

A suggestion on this will be much helpful if i can achieve the above functionality with latest release of flowise or any chatflow diagram?

**Comment by HenryHengZJ** [comment]
good suggestion! this sounds more like a workflow based approach, as in you can use [tagging chain](https://js.langchain.com/docs/modules/chains/additional/openai_functions/tagging) to determine the tone, categories that user is asking, and route that to a chain/agent with specific system message prompt, so on and so forth

**Comment by Matr1xCode** [comment]
Hello, any update ? thanks

**Comment by HenryHengZJ** [comment]
Merged: https://github.com/FlowiseAI/Flowise/pull/3280
