### ISSUE TITLE
no tools menu after update ???

### ISSUE THREAD

**Issue by supernitant** [FlowiseAI/Flowise#670]
### Discussed in https://github.com/FlowiseAI/Flowise/discussions/425

<div type='discussions-op-text'>

<sup>Originally posted by **nsitnov** June 27, 2023</sup>
Can I update to the latest version doing docker pull flowiseai/flowise

because i installed it on AWS?</div>

**Comment by atishamte** [comment]
the new update is having a credentials table. check whether you have OVERRIDE_DATABASE=true in the env file.

I was also facing this issue and this actually resolved it
