### ISSUE TITLE
[BUG] Network Error: Azure OpenAI Connection Setup

### ISSUE THREAD

**Issue by aidin-zadeh** [FlowiseAI/Flowise#674]
**Describe the bug**
Not able to set up an Azure OpenAI LLM in local mode.

![image](https://github.com/FlowiseAI/Flowise/assets/33791593/93bfa47a-98a3-40bc-835e-1413559f1e84)

**To Reproduce**

![image](https://github.com/FlowiseAI/Flowise/assets/33791593/11a91f89-e4f6-425d-a055-589acc226b10)

**Expected behavior**
Translate any texts to english uitilizing an Azure OpenAI model.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/33791593/73059fd6-0ea3-44bf-b0fb-2aca1d488467)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation: Docker, local
-   Flowise Version: latest 1.3.0
-   OS: Mac
-   Browser: Edge running on VPN

**Additional context**

**Comment by TMwrhere** [comment]
The same problem, trying to call api/v1/internal-prediction/id locally is also a Network Error！

**Comment by chungyau97** [comment]
Hi @aidin-zadeh,

Could you try setting up Flowise using this [method](https://github.com/flowiseai/flowise#setup)?

I suspect that `docker` do not have access to the URL/Local network you provided.

**Comment by aidin-zadeh** [comment]
I was able to solve my issue by changing the azure API version to `2023-06-01-preview` as [recommended by Azure](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference). 
![image](https://github.com/FlowiseAI/Flowise/assets/33791593/70bf64da-24bd-4227-b3e1-e138309918fb)

Though, I am facing with another issue where the response generated is not being parsed correctly. It seems that the bot is returning the entire Langchain response instead of parsing the HumanMessage content. See the flow below:

![image](https://github.com/FlowiseAI/Flowise/assets/33791593/9abab860-da46-429c-8b9c-1721550b089d)

I would greatly appreciate any advice or suggestions to fix this issue. Thank you in advance for your help!

**Comment by chungyau97** [comment]
Hi @aidin-zadeh,

I just requested access to Azure OpenAI service, currently waiting for their review.
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/96b7c041-72ff-4226-baa2-5c948d266939)

**Comment by aidin-zadeh** [comment]
I might help you to expedite the process.

**Comment by chungyau97** [comment]
Hi @aidin-zadeh,

I'm not able to replicate your error shown below:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/0002087c-eb7e-4f4a-9b2f-c59bb7ada9e2)


I can see your flow is using LLM Azure OpenAI with `text-davinci-003`
I do not have the options to choose that model shown below:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/ff1c2c05-5901-4512-bb3d-c542c20f0bd5)

**Comment by aidin-zadeh** [comment]
I think it's happening because I'm using the completion API for the translation task.

BTW, I had a chat with the Microsoft team, and they're all in to speed up anything Flowise-related. If you're up for a chat, shoot me a message in Discord, and I'll hook you up with a Microsoft AI Cloud Solution Architect who can lend a hand to the team through the process.

**Comment by aidin-zadeh** [comment]
@chungyau97  Can you please share which API version and model you're currently using?

**Comment by chungyau97** [comment]
@aidin-zadeh

I have created some documentation on how I setup `Azure OpenAI` on my end.
- [Chat Models](https://github.com/FlowiseAI/FlowiseDocs/blob/main/chat-models/azure-chatopenai.md)
- [Embeddings](https://github.com/FlowiseAI/FlowiseDocs/blob/main/embeddings/azure-openai-embeddings.md)

Our [official docs](https://docs.flowiseai.com/) is currently not showing some images.

**Comment by devosthomas** [comment]
Same here. Network error. Using local Docker.

**Comment by devosthomas** [comment]
Same issue here. Aswel in the local docker as an Azure container. Network error.

**Comment by dzbaiyang** [comment]
> Same issue here. Aswel in the local docker as an Azure container. Network error.

Have you solved this problem yet?

**Comment by dzbaiyang** [comment]
I'm having the same problem, please also ask for help. I am also docker local deployment. openAI interface are working fine!
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/9654c442-19f0-41f7-a450-93ad7268e3f7)
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/d855608b-30fd-47e6-86f9-8a4b04860755)

**Comment by chungyau97** [comment]
Hey @dzbaiyang, replied in #866

I will close this issue here as the Original Poster already get Azure OpenAI working.
