### ISSUE TITLE
[FEATURE] How to run FlowiseAI with Nginx in sub-directory?

### ISSUE THREAD

**Issue by NISHANTSHRIVASTAV** [FlowiseAI/Flowise#677]
I want to run FlowiseAI with Nginx as a reverse proxy on the server.

When I access the app URL in a browser such as https://demo.example.ai/flowsie-app/ it should redirect to Flowise UI.

How to achieve the same with Nginx?

**Comment by chungyau97** [comment]
Hi @NISHANTSHRIVASTAV,

Highly recommend you to join in our [discord](https://discord.gg/yy83UjzN). One of our user have solved it.
`Support` > `nginx reverse proxy digital ocean - SOLVED - see notes for root cause - me!`

Reference from our docs:
[Installing Nginx](https://docs.flowiseai.com/deployment/digital-ocean#step-1-installing-nginx)

**Comment by NISHANTSHRIVASTAV** [comment]
> Hi @NISHANTSHRIVASTAV,
> 
> Highly recommend you to join in our [discord](https://discord.gg/yy83UjzN). One of our user have solved it. `Support` > `nginx reverse proxy digital ocean - SOLVED - see notes for root cause - me!`
> 
> Reference from our docs: [Installing Nginx](https://docs.flowiseai.com/deployment/digital-ocean#step-1-installing-nginx)

Hi @chungyau97 ,

I want to run the FlowiseAI application with a sub-path such as` /genai-studio/` and not in `/`. 

The Nginx config shared in the above documentation reference run on `'/'` as below

```
server {
    listen 80;
    listen [::]:80;
    server_name your_domain; #Example: demo.flowiseai.com
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
    }
}
```

And when I tried to run Nginx with the below config for sub-path '/genai-studio/'  it is not redirecting.

### Setup

1. Clone the repository

    ```bash
    git clone https://github.com/FlowiseAI/Flowise.git
    ```

2. Go into the repository folder

    ```bash
    cd Flowise
    ```

3. Install all dependencies of all modules:

    ```bash
    yarn install
    ```

4. Build all the code:

    ```bash
    yarn build
    ```

5. Start the app:

    ```bash
    yarn start
    ```

   Here able to access the app on [http://localhost:3000](http://localhost:3000)


### Nginx Config Setup
```
server {
    listen 80;
    listen [::]:80;
    server_name demo.example.ai #Example: demo.flowiseai.com
    location /genai-studio/ {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;
    }
}
```

How to resolve the same?

Please let me know if you need more information.

**Comment by NISHANTSHRIVASTAV** [comment]
Able to figure out on windows.  Need to add sub directory path in package.json with homepage.

**Comment by automaton82** [comment]
@NISHANTSHRIVASTAV can you share what you did? I'm trying to deploy on nginx in a subpath but there's no direction on how

**Comment by snchoh** [comment]
@automaton82 Did you figure this out? @automaton82  can you please show the solution

**Comment by vincenzomanzoni** [comment]
Same interest here. @NISHANTSHRIVASTAV can you please share more details about your solution? Thank you!

**Comment by automaton82** [comment]
I have subpath working in a forked repo, namely https://github.com/LogiComposer/Flowise and https://github.com/LogiComposer/FlowiseChatEmbed

It requires a fair number of changes, and had to be updated with the move to Vite. The embed chat also has to be updated so you can't use the stock one. You can go through my public repos and should be able to figure out how to do it from there.

**Comment by kangsan0420** [comment]
any progress here?

**Comment by wdlid** [comment]
any progress here? Or can we define it in env file?
