### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ronnysmerino** [FlowiseAI/Flowise#68]
**Describe the bug**
In the API endpoint the Input Config checkbox is not appearing.

**To Reproduce**

1. Go to 'chatflows'
2. Click on 'any chatflow created'
3. Click on 'API endpoint icon'

**Expected behavior**
A checkbox with a label that says "Input Config" should appear.

**Screenshots**
![issue](https://user-images.githubusercontent.com/42942808/236631135-3c75953a-45bc-4af4-ae54-981c2785b64f.PNG)

**Setup**

-   OS: Windows
-   Browser Chrome

**Comment by HenryHengZJ** [comment]
Hey @ronnysmerino have you tried pulling latest changes if you're using git clone or docker, sync your fork, or reinstall Flowise using npm?

**Comment by ronnysmerino** [comment]
> Hey @ronnysmerino have you tried pulling latest changes if you're using git clone or docker, sync your fork, or reinstall Flowise using npm?

Im using Render as deployment, let me check again.

**Comment by ronnysmerino** [comment]
> Hey @ronnysmerino have you tried pulling latest changes if you're using git clone or docker, sync your fork, or reinstall Flowise using npm?

Solved! You were right
