### ISSUE TITLE
[FEATURE] Execute evaluation jobs

### ISSUE THREAD

**Issue by georgeseifada** [FlowiseAI/Flowise#683]
**Describe the feature you'd like**
It would be great to be able to build a flow that loads input data, loops / parses through it, and sends sequential requests to an LLM model, and then outputs the results somewhere for review (or even better, we can additionally have an evaluation function at the end). This would give users the ability to quickly evaluate their flows on test data.

**Comment by HenryHengZJ** [comment]
Evaluation is now available on cloud: https://youtu.be/kgUttHMkGFg?si=ypEtGIfYkywPa2YL
