### ISSUE TITLE
[BUG] ChatLocalAI model not working

### ISSUE THREAD

**Issue by Shekhar-Gudepu** [FlowiseAI/Flowise#695]
Below is the flow I created for a simple agent that uses SERP API to generate responses.
<img width="446" alt="flowise" src="https://github.com/FlowiseAI/Flowise/assets/28714300/d4b2e6f5-ae7a-482d-8a28-6d690c7f82a5">

But I am getting multiple errors when I ask simple questions to the agent . Below are the errors,

Question: Hi
Error: Failed to parse. Text: "". Error: SyntaxError: Unexpected end of JSON input
Error: Failed to parse. Text: "". Error: SyntaxError: Unexpected end of JSON input

Question: What is flowise
Failed to parse. Text: "Error: Failed to parse. Text: "ERROR: The prompt size exceeds the context window size and cannot be processed.". Error: SyntaxError: Unexppected token E in JSON at position 0 ". Error: SyntaxError: Unexpected token E in JSON at position 0

**Expected behavior**
I expect the agent to call the SERP API if necessary and return correct responses.

**Setup:**
Installation: docker	
Flowise Version: flowise@1.3.0
OS: Windows	
Browser: Chrome

**Note**:
The flow works as expected when the ChatOpenAI chat model is used. gpt4all.bin model was downloaded from (https://gpt4all.io/models/ggml-gpt4all-j.bin)

**Comment by HenryHengZJ** [comment]
Open source models like gpt4all is not capable for agent, they only work for simpler prompt using LLMChain: 
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/f76a7c99-e56a-4c5f-b6a6-1ab365682a68)

**Comment by gregoryca** [comment]
is there a way to identify how to use the right models ? looks like the current implementation of chatlocalai is a bit limited.
