### ISSUE TITLE
[BUG] Problem with js nodes when using Make with http access - codes 400 and 500

### ISSUE THREAD

**Issue by mickahouan** [FlowiseAI/Flowise#699]
**Describe the bug**

Hello,
I'm planning to use Flowise to help me create automated content from Make.
I have a Make workflow that seems pretty solid. 
But at the moment I'm getting random 400 and 500 errors. 
That is, sometimes it works and sometimes it doesn't using exactly the same http calls.
Sometimes it bugs on the first HTTP call of the workflow, and sometimes on subsequent calls (the 4th for example).

**To Reproduce**

1. Use the same Flow in Flowise
2. Make several http calls from Make

**Expected behavior**

Successfully complete my workflow from Make.
It consists in creating several text elements.
Having not errors during workflow processing.

**Screenshots**

Error 400 on my first http call from Make
![statucode500 - flowise node](https://github.com/FlowiseAI/Flowise/assets/31423109/58ff5927-abaf-4892-9ffb-4d9f37507f84)

Code 200 en utilisant exactement le même workflow et les mêmes instructions http
![code 200 on the same node](https://github.com/FlowiseAI/Flowise/assets/31423109/339f699c-0341-417a-a3d9-91ae7147d2a5)

My Make configuration
![http Make module config 1](https://github.com/FlowiseAI/Flowise/assets/31423109/e62ef8b8-14ae-483a-acfd-53e337c3c741)
![http make module config 2](https://github.com/FlowiseAI/Flowise/assets/31423109/45afba1d-6537-45a3-a0cd-39c3724bab26)

configuration flowise
![flow on flowise](https://github.com/FlowiseAI/Flowise/assets/31423109/be07ee52-e5ca-4a55-92a6-3ef2467d4b79)

Make workflow to execute 5 http calls to Flowise
![Make workflow](https://github.com/FlowiseAI/Flowise/assets/31423109/735120a0-c516-4cb8-a078-91b75822a452)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation : docker, but also tried on node with the same problem
-   Flowise Version [1.3.0] - [ac931cf] - But same problem on other, on several recent versions
-   Installed on render (paid starter package)

**Additional context**
[logs_flowise error.txt](https://github.com/FlowiseAI/Flowise/files/12267406/logs_flowise.error.txt)

**Comment by HenryHengZJ** [comment]
First i would check if the error is coming from Make not being able to get response within certain period of time, or its coming from Flowise.

1.) Use gpt-3.5-turbo-16k (this is faster and more reliable)
2.) Try hitting several Flowise API from Postman to see if that works
