### ISSUE TITLE
Unable to link Pinecone Upsert Document to Conversational Retrieval QA

### ISSUE THREAD

**Issue by bdecarne** [FlowiseAI/Flowise#7]
**Describe the bug**
I pulled a new Docker image to test the #6 fix, but i'm now unable to link en Vector Store (Pinecone or Chroma) to a Conversational Retrieval QA Chain

**To Reproduce**

1. Add a Pinecone Upsert Document node
2. Add a Conversational Retrieval QA Chain node
3. Try to link them

**Expected behavior**
Link as the previous version

**Screenshots**

![image](https://user-images.githubusercontent.com/1277131/231897341-e335984c-f1ed-4a14-a0de-ebfcbe5199d4.png)

![image](https://user-images.githubusercontent.com/1277131/231897376-3a9daf9f-7e7b-4167-9fe9-5e1b93702d0e.png)

**Setup**

-   OS: Linux
-   Browser: Chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
Nice spot! Merged in the latest Langchain version PR(https://github.com/FlowiseAI/Flowise/pull/4) and broke some classes there. Updated docker and package, if you reinstall or pull latest changes, should works now

**Comment by bdecarne** [comment]
Yep, it's works fine, thank you
