### ISSUE TITLE
[FEATURE] is thier a way to configure a message while loading a generation

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#703]
**Describe the feature you'd like**
b.	Maybe once the delay exceeds a certain value, an interim message should be displayed “sorry for the delay as I am trying to answer your question”

**Comment by HenryHengZJ** [comment]
is it for embedded chat or Flowise UI?

**Comment by HenryHengZJ** [comment]
for now the floating bubble is signifying that AI is generating response, but you can always change the source code [here](https://github.com/FlowiseAI/FlowiseChatEmbed)
