### ISSUE TITLE
Error- nodeInstance.run is not a function

### ISSUE THREAD

**Issue by apt-team-018** [FlowiseAI/Flowise#71]
It's creating an issue when trying to use chatbot
Error- nodeInstance.run is not a function

<img width="727" alt="image" src="https://user-images.githubusercontent.com/74986481/236637271-5b3cc3cf-adec-4a70-896e-1f5b8e395f72.png">

---
i am getting issues from this code
const nodeInstanceFilePath = this.nodesPool.componentNodes[nodeToExecuteData.name].filePath as string
            const nodeModule = await import(nodeInstanceFilePath)
            const nodeInstance = new nodeModule.nodeClass()
            const result = await nodeInstance.run(nodeToExecuteData, incomingInput.question, { chatHistory: incomingInput.history })

----
file path - packages/server/src/index.ts

**Comment by HenryHengZJ** [comment]
Hey have you saved the chatflow?

**Comment by urbanscribe** [comment]
the same error happened when I had not connected the document box to the pinecone upset box.

**Comment by fabrietech** [comment]
the same error I had meet, how to resolve it
