### ISSUE TITLE
Request failed with status code 401 - Unauthorized.  Access token is missing, invalid, audience is incorrect 

### ISSUE THREAD

**Issue by NISHANTSHRIVASTAV** [FlowiseAI/Flowise#710]
Hello All,

I have created a simple chat flow in flow wise and getting the below error when testing:

```
Request failed with status code 401 and body {"statusCode":401, "message": "Unauthorized. Access token is missing, invalid, and the audience is incorrect (
https://cognitiveservices.azure.com/
), or have expired."}
```

**Chat Flow Screenshot**:

![image](https://github.com/FlowiseAI/Flowise/assets/31445132/0d9bdce8-2164-4e52-8c71-b06b6121bdc8)

I have provided the correct Azure OpenAI API keys which are not expired.

### **Versions**:

**OS**: Windows 10 
**NodeJS:** [18.17.0 LTS](https://nodejs.org/en)
**Method of setting up**: 

#### Prerequisite

-   Install [Yarn v1](https://classic.yarnpkg.com/en/docs/install)
    ```bash
    npm i -g yarn
    ```

#### Setup

1. Clone the repository

    ```bash
    git clone https://github.com/FlowiseAI/Flowise.git
    ```

2. Go into the repository folder

    ```bash
    cd Flowise
    ```

3. Install all dependencies of all modules:

    ```bash
    yarn install
    ```

4. Build all the code:

    ```bash
    yarn build
    ```

5. Start the app:

    ```bash
    yarn start
    ```

    I am able to access the app on [http://localhost:3000](http://localhost:3000)

How to resolve the above issue?

Please let me know if you need more information.

**Comment by chungyau97** [comment]
Hi @NISHANTSHRIVASTAV 

[OpenAI](https://platform.openai.com/account/usage) does not equate to [Msft Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?pivots=programming-language-studio&tabs=command-line)

**Comment by chungyau97** [comment]
Hi @NISHANTSHRIVASTAV,

I just added some documentation on implementing Azure OpenAI
1. [Embeddings](https://github.com/FlowiseAI/FlowiseDocs/blob/main/embeddings/azure-openai-embeddings.md)
2. [Chat Models](https://github.com/FlowiseAI/FlowiseDocs/blob/main/chat-models/azure-chatopenai.md)

**Comment by dzbaiyang** [comment]
> Hello All,
> 
> I have created a simple chat flow in flow wise and getting the below error when testing:
> 
> ```
> Request failed with status code 401 and body {"statusCode":401, "message": "Unauthorized. Access token is missing, invalid, and the audience is incorrect (
> https://cognitiveservices.azure.com/
> ), or have expired."}
> ```
> 
> **Chat Flow Screenshot**:
> 
> ![image](https://user-images.githubusercontent.com/31445132/258815631-0d9bdce8-2164-4e52-8c71-b06b6121bdc8.png)
> 
> I have provided the correct Azure OpenAI API keys which are not expired.
> 
> ### **Versions**:
> **OS**: Windows 10 **NodeJS:** [18.17.0 LTS](https://nodejs.org/en) **Method of setting up**:
> 
> #### Prerequisite
> * Install [Yarn v1](https://classic.yarnpkg.com/en/docs/install)
>   ```shell
>   npm i -g yarn
>   ```
> 
> #### Setup
> 1. Clone the repository
>    ```shell
>    git clone https://github.com/FlowiseAI/Flowise.git
>    ```
> 2. Go into the repository folder
>    ```shell
>    cd Flowise
>    ```
> 3. Install all dependencies of all modules:
>    ```shell
>    yarn install
>    ```
> 4. Build all the code:
>    ```shell
>    yarn build
>    ```
> 5. Start the app:
>    ```shell
>    yarn start
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    I am able to access the app on http://localhost:3000
> 
> How to resolve the above issue?
> 
> Please let me know if you need more information.

Hi，Is this problem solved?
