### ISSUE TITLE
Error when i try to add credentials[BUG]

### ISSUE THREAD

**Issue by marius-smg** [FlowiseAI/Flowise#712]
**Describe the bug**
When i try to add credentials i get an error. I host it on render.com on a paid plan. I get a huge wall of text on a red background (see screenshot). in the log it says: "[server]: Error during Data Source initialization: EACCES: permission denied, open '/root/.flowise/encryption.key"

i added the Environment variables as described here: https://docs.flowiseai.com/migration-guide/v1.3.0-migration-guide 

**To Reproduce**
![Bildschirmfoto 2023-08-08 um 10 03 56](https://github.com/FlowiseAI/Flowise/assets/132438025/a9051c77-74a3-4300-88c9-5d26dbecfbd7)

**Expected behavior**

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: macOS
-   Browser [Brave]

**Additional context**

**Comment by HenryHengZJ** [comment]
have you tried to clear build cache and deploy? and is the runtime using Docker, same as the docs - https://docs.flowiseai.com/deployment/render ?

**Comment by marius-smg** [comment]
Yes i have tried to clear build cache and deploy. I cant find a way to lookup, which runtime is beeing used. However when i set up this webservice two months ago i followed the docs and if nothing has changed, it should be running on docker.
this is the whole error log:

Aug 9 09:15:46 AM  2023-08-09 07:15:46 [INFO]: ⬆️ POST /api/v1/credentials
Aug 9 09:15:47 AM  error Command failed with exit code 1.
Aug 9 09:15:47 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Aug 9 09:15:47 AM  error Command failed with exit code 1.
Aug 9 09:15:47 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Aug 9 09:15:49 AM  ==> Using Node version 20.5.0 via /opt/render/project/src/package.json
Aug 9 09:15:49 AM  ==> Docs on specifying a Node version: https://render.com/docs/node-version
Aug 9 09:15:49 AM  ==> Starting service with 'yarn start'
Aug 9 09:15:49 AM  yarn run v1.22.5
Aug 9 09:15:50 AM  $ run-script-os
Aug 9 09:15:50 AM  $ cd packages/server/bin && ./run start
Aug 9 09:15:53 AM  2023-08-09 07:15:53 [INFO]: Starting Flowise...
Aug 9 09:15:53 AM  2023-08-09 07:15:53 [INFO]: ⚡️ [server]: Flowise Server is listening at 10000
Aug 9 09:15:53 AM  2023-08-09 07:15:53 [INFO]: 📦 [server]: Data Source has been initialized!
Aug 9 09:15:55 AM  2023-08-09 07:15:55 [ERROR]: ❌ [server]: Error during Data Source initialization: EACCES: permission denied, open '/root/.flowise/encryption.key'
Aug 9 09:15:55 AM  Error: EACCES: permission denied, open '/root/.flowise/encryption.key'

**Comment by marius-smg** [comment]
Thank you! In Fact my webservice was running for ca. 2 months and back then the docs suggested to have Nodes as the runtime environment. I set up a new webservice with docker as runtime and now it works.
