### ISSUE TITLE
[BUG] Credentials could not be decrypted issue while using MySQL as database

### ISSUE THREAD

**Issue by cnj125** [FlowiseAI/Flowise#714]
**Describe the bug**
After switching to MySQL as database, it is failed to decrypt the credential during chatting.

**To Reproduce**

1. Configure the .env to use MySQL (empty database)
2. Start server
3. Create a flow with "Simple Conversation Chain" template
4. Change the "ChatOpenAI" to "Azure ChatOpenAI"
5. Add new credential to "Azure ChatOpenAI"
6. Save the flow
7. Start chatting
8. A "Credentials could not be decrypted" message is returned

**Expected behavior**
It has no error if I don't change the database. The chatbot can reply me correctly.

**Screenshots**
![bug_log_1](https://github.com/FlowiseAI/Flowise/assets/5063048/c09e6616-8f14-43e5-965a-62fc488ab2c2)
![bug_log_2](https://github.com/FlowiseAI/Flowise/assets/5063048/dfdfc3eb-fae1-492e-9bc6-ae0ffa291c00)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation: `yarn start`
-   Flowise Version flowise@1.3.0
-   OS: Windows
-   Browser Brave

**Comment by HenryHengZJ** [comment]
Have you specify `SECRETKEY_PATH` to persist `encryption.key`?

**Comment by cnj125** [comment]
> Have you specify `SECRETKEY_PATH` to persist `encryption.key`?

No. Is it compulsory to set this path?

**Comment by cnj125** [comment]
> Have you specify `SECRETKEY_PATH` to persist `encryption.key`?

I tried to set `SECRETKEY_PATH` and I can see the  `encryption.key` the file. But the same issue persist.

Thanks.

**Comment by HenryHengZJ** [comment]
> > Have you specify `SECRETKEY_PATH` to persist `encryption.key`?
> 
> No. Is it compulsory to set this path?

if you are using cloud services like Render, Railway, yes. If you are running locally, nope. The reason credential is not able to decrypt is because when using SQLite, all credentials are saved into SQLite database into `credentials` table. Then switching to MySQL these credentials are obviously not saved there, so it wont be able to decrypt or get those credentials

**Comment by cnj125** [comment]
> 

I have set `SECRETKEY_PATH` and I can see the `encryption.key` in the folder, but the same issue persist.

**Comment by yanpassaro** [comment]
I'm facing the same error, with postgres and sqlite, I have two cloud services and I've been facing this same problem, even using sqlite as the main database

**Comment by ahakobyan79** [comment]
I am using a docker image with Flowise, which was working ok, and at some point I started getting the same exact error, though I haven't changed anything on the container.

**Comment by yanpassaro** [comment]
This issue arises when the key within the .key file is not preserved. To resolve this, simply define the SECRETKEY_PATH environment variable and, in your specific scenario, link it to a volume. Consider the following example:

```
environment:
      - SECRETKEY_PATH=/root/flowise/secrets
volumes:
      - ./secrets:/root/flowise/secrets
```

**Comment by bekmuradov** [comment]
With latest flowise you can set your secret variable:
`FLOWISE_SECRETKEY_OVERWRITE=myencryptionkey`

Please refer to this documentation
https://docs.flowiseai.com/configuration/environment-variables#for-credentials
