### ISSUE TITLE
[BUG] Qdrant fetch failure in Flowise

### ISSUE THREAD

**Issue by samsam002** [FlowiseAI/Flowise#716]
**Description**
When utilizing the Qdrant integration in the Flowise library, I encountered an error related to the fetch function failing. This issue seems to be emanating from the Qdrant's OpenAPI TypeScript fetch implementation.

Expected behavior:
The fetch function should successfully retrieve data from Qdrant without any errors.

Actual behavior:
The fetch function fails with a TypeError.

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation : both docker and npx
-   Flowise Version 1.3
-   OS: Linux
-   Browser Edge

**Comment by HenryHengZJ** [comment]
Is it cloud hosted or open source Qdrant? 

both load and upsert works for me:

![image](https://github.com/FlowiseAI/Flowise/assets/26460777/c8aed491-4b6a-4037-9267-237edecc421a)

![image](https://github.com/FlowiseAI/Flowise/assets/26460777/d978b399-19d8-4243-a9c9-e2fd305e2931)

**Comment by samsam002** [comment]
It's the on prem version docker based. 
it's working without problem out of flowise, when trying to use it withing it. It gives fetch errror on the chat ui

**Comment by HenryHengZJ** [comment]
@samsam002 some community member suggested appending `:443` port to the end of url, not sure if that is able to resolves the issue

**Comment by kientv** [comment]
I my case: "Error: Insufficient Permission"
![image](https://github.com/FlowiseAI/Flowise/assets/3217438/d2e2c9c0-893e-43bf-a45a-0f9f4d4a7c54)

> chatbot  | 2023-12-11 08:42:23 [INFO]: ⬆️ POST /api/v1/vector/internal-upsert/6c643457-d5b2-4076-b0e3-cba4f7747ad6
> chatbot  | 2023-12-11 08:42:24 [ERROR]: Error: Insufficient Permission
> chatbot  | Error: Error: Insufficient Permission
> chatbot  |     at Qdrant_VectorStores.upsert (/usr/src/packages/packages/components/dist/nodes/vectorstores/Qdrant/Qdrant.js:47:27)
> chatbot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> chatbot  |     at async buildLangchain (/usr/src/packages/packages/server/dist/utils/index.js:232:17)
> chatbot  |     at async App.buildChatflow (/usr/src/packages/packages/server/dist/index.js:1250:40)
> chatbot  |     at async /usr/src/packages/packages/server/dist/index.js:938:13
> chatbot  | 2023-12-11 08:42:24 [ERROR]: [server]: Error: Error: Error: Insufficient Permission
> chatbot  | Error: Error: Error: Insufficient Permission
> chatbot  |     at buildLangchain (/usr/src/packages/packages/server/dist/utils/index.js:258:19)
> chatbot  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> chatbot  |     at async App.buildChatflow (/usr/src/packages/packages/server/dist/index.js:1250:40)
> chatbot  |     at async /usr/src/packages/packages/server/dist/index.js:938:13
>

**Comment by Vik-BC** [comment]
The fetch failed error seems to be related not to **Qdrant** directly, but to the **embeddings model** that's connected to Qdrant. **Check the connection to your embeddings provider.**
For example, if you're using **Ollama**, you might want to verify by accessing: `http://localhost:11434`
