### ISSUE TITLE
[FEATURE]aws-sdk-js-v3 when i try run the source code with 'npm run dev' ,it always say i should migrate to v3

### ISSUE THREAD

**Issue by howie-cn** [FlowiseAI/Flowise#718]
![image](https://github.com/FlowiseAI/Flowise/assets/30275483/cb577de4-e947-4c31-98e7-4ff553c7d75b)

could you please telll me if you have plan to do the  sdk upgrade ?

**Comment by HenryHengZJ** [comment]
we're using `"@aws-sdk/client-dynamodb": "^3.360.0"`. feel free to submit PR if you have successfully upgraded and tested everything still works fine 👍
