### ISSUE TITLE
[FEATURE] add a custom prompt agent

### ISSUE THREAD

**Issue by zhengxiang5965** [FlowiseAI/Flowise#720]
**Describe the feature you'd like**
I hope to add a custom prompt agent, and even customize the output_ parser, because in non openai llm scenarios, many models do not have good support for langchain's built-in prompt

**Additional context**
Alternatively, have existing agents support customizing prompts according to certain specifications

**Comment by chungyau97** [comment]
Hi @zhengxiang5965,

Could you explain more on how you wanna implement `custom prompt agent` using this [reference](https://js.langchain.com/docs/modules/agents/)?
