### ISSUE TITLE
[BUG] The webhook module integrated with Make.com is not able to detect the data

### ISSUE THREAD

**Issue by LongRodSilver** [FlowiseAI/Flowise#726]
**Describe the bug**
Hey, there seems to be some error with the make.com integration in flowise when we use the webhook module. It is not able to detect any data, causing it to not send any data. I combined the webhook with a gmail email sent on Make.com but the email that's sent is empty. 

**To Reproduce**

1. Go to 'Create a Zapier NLA Chat flow on Flowise, remove the NLA module and replace it by a webhook'
2. Go To 'Make.com, create a new scenario with a custom webhook and a Gmail (send an email) module.'
3. Go To 'Flowise and add your webhook address then run the whole thing '
4. See error "The agent tells me he has sent the email but when I check the webhook there is something it has received but there is no content and the email that is sent is empty."

**Expected behavior**
The Agent I built should use a webhook configured on Make.com and send an email to a specific address.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/4752342/328bc28a-3064-4075-8166-6d28d6244515)
![image](https://github.com/FlowiseAI/Flowise/assets/4752342/eedc77f8-1a7f-44c8-a8b4-792ffbb2eb69)

**Flow**
Here is the exported flow: https://drive.google.com/file/d/1GGr6Rx4Tw7GPLwZ_a_mj_b-CwYqUMzdY/view?usp=sharing

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by HenryHengZJ** [comment]
I've written a guide on how to create custom tool that can call any webhook endpoint and pass in dynamic body - https://docs.flowiseai.com/use-cases/webhook-tool

**Comment by HenryHengZJ** [comment]
we'll be removing Make Tool in next release
