### ISSUE TITLE
[FEATURE]Hello, I have a problem, I would like to create an htaccess file to protect access to the domain when I have this rent at the root of the server "111.11.111.21:3000" but I don't know where to place the file

### ISSUE THREAD

**Issue by bookz971** [FlowiseAI/Flowise#727]
Hello, I have a problem, I would like to create an htaccess file to protect access to the domain when I have this rent at the root of the server "111.11.111.21:3000" but I don't know where to place the file

**Comment by riosje** [comment]
Don't use htaccess
Why would you need an htaccess?

Just configure an nginx as reverse proxy

https://www.nginx.com/resources/wiki/start/topics/examples/likeapache-htaccess/
