### ISSUE TITLE
[FEATURE] Allow entire chatflows available as Tools.

### ISSUE THREAD

**Issue by rkeshwani** [FlowiseAI/Flowise#736]
You've already implemented the ability to convert an entire flow as a chain tool but this isn't accessible across different chat flows. You have to build everything into a single large flow. I suggest aggregating all flows that end with a chain tool and adding those to a new flow tool node. This way you can build out your individual tools/flows and then connect them as/when needed.

Example, you've build a flow that performs lookups for a certain vertical. Now you need to rebuild the entire thing for the next vertical. Then want the flows combined into a single assistant. Right now you'd have to put all of this in a single flow. And duplicating it won't help. 

This could also help you build a so called JARVIS if you wanted. Where you combine a variety of different operations, let the model decide which flow to take. Similar to your multi-prompt example, but think multi-flow.

**Comment by HenryHengZJ** [comment]
You can make a custom tool that makes a POST call to the chatflow, here's a similar use case to create a custom tool making a POST webhook call with dynamic body - https://docs.flowiseai.com/use-cases/webhook-tool

**Comment by rkeshwani** [comment]
Interesting! So you can make webhook requests to the bot's own api? Thanks for pointing this out.
