### ISSUE TITLE
[Question] message response is slow

### ISSUE THREAD

**Issue by kientv** [FlowiseAI/Flowise#739]
**Describe the questions**
1. Why message response very slow (about 18 seconds)
2. How to turn on streaming on Chat Widget embed 
**To Reproduce**

**Expected behavior**
It's faster

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/3217438/e8b53741-6207-41cd-99f1-51c88f3a3f74)

**Flow**
Conversational Retrieval QA Chain (Using faiss vector store)

**Setup**
-   Installation: docker, yarn start
-   Flowise Version: 1.3.3
-   OS: Linux
-   Browser: chrome

**Additional context**
OpenAI API free trial

**Comment by HenryHengZJ** [comment]
oh currently faiss vector store is not working with streaming, other vector stores should work

**Comment by kientv** [comment]
it work now, thanks.
