### ISSUE TITLE
[BUG] Credentials only saves last API key and rewrites all others

### ISSUE THREAD

**Issue by kaveshan1** [FlowiseAI/Flowise#748]
**Describe the bug**
Adding API key results in overwriting all other API keys 

**To Reproduce**

1. Add more than 1 api key
2. check the API key (copy and paste into text editor)
3. Will notice all API keys are the same

**Expected behavior**
Store credentials with different API keys 

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Have tried all 1.3.3 installation options
-   Flowise Version [e.g. 1.3.3]
-   macOS and linux
-   Browser: chrome, safari

**Additional context**

**Comment by mcmanusslim** [comment]
same issue

**Comment by HenryHengZJ** [comment]
So I tested it;

1.) create a credential with correct api key
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/a887fbb0-1833-4c39-8a8a-187199a9465c)

2.) create another credential with incorrect api key
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/54f7d816-a681-49a3-b184-85ab5fcffd73)

3.) use first credential, works:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/dfb1674c-92c3-40a1-97d9-38c967188ba8)

4.) use 2nd incorrect api credential, expected 401:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/52cafe48-0b3c-4391-9fe4-00ae425fe983)

**Comment by kaveshan1** [comment]
Thanks Henry! Do you know of a quick fix or workaround? as I've just started using flowise (love the concept) however I'm unable to build any bots as a result of this error

**Comment by kaveshan1** [comment]
Btw, the result I got was using the first as an openAI API key and the next 2 as pinecone api keys

**Comment by HenryHengZJ** [comment]
But I'm not able to replicate the issue, from the screenshots I attached, it seems to work as expected, different api keys are used

**Comment by chungyau97** [comment]
Hi @kaveshan1, 

Could you open up your db and check whether your data under `credential` table for `encryptedData` column.
default db located for Linux/Mac: `~/.flowise/database.sqlite`

**Comment by kaveshan1** [comment]
Thank you for your help. I am running it on render so not sure how to check that sorry. It's ok, I'll just go back to using langchain programmatically

**Comment by ChatWithStoics** [comment]
Please solve this issue, it happens to me as well and I tried many things so I can't use flowise at all. Isn't there a way at leasat to not use credentials and just stay with the older and working version of flowise?
