### ISSUE TITLE
[BUG] Playwright is not loading?

### ISSUE THREAD

**Issue by TotalLag** [FlowiseAI/Flowise#754]
**Describe the bug**
I have a test flow that works to load a page with Puppeteer but when I swap out with Playwright, I get the following error:

```TypeError: Cannot read properties of undefined (reading 'pageContent')```

**To Reproduce**

1. Create a Conversational Web QnA flow (you can use the marketplace template)
2. Replace the document loader with Playwright
3. Ask a question

**Expected behavior**
Return results similar if not exactly identical to Puppeteer

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/1744428/1a30d2d6-025e-42ac-9244-112562ca9584)

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation: Fargate on AWS
-   Flowise Version: 1.3.3
-   OS: Linux
-   Browser: Chrome

**Additional context**
If I fill out the Additional Parameters, the error I get instead is 

```TypeError: (intermediate value) is not iterable (cannot read property undefined)```

**Comment by chungyau97** [comment]
Hi @TotalLag,

Please try this as your URL: `https://www.reddit.com/`
I'm able to retrieve data from and store it into vector stores
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/d8d59977-671c-47bb-9760-db1b36310f8e)

**Comment by TotalLag** [comment]
I'v

> Hi @TotalLag,
> 
> Please try this as your URL: `https://www.reddit.com/` I'm able to retrieve data from and store it into vector stores ![image](https://user-images.githubusercontent.com/33013947/260290525-d8d59977-671c-47bb-9760-db1b36310f8e.png)

I've tried other URLs with `https://` as well. Including those that would work with Puppeteer. The container I built is from this example: https://github.com/go-skynet/LocalAI/blob/master/examples/flowise/docker-compose.yaml

I'll try rebuilding my environment with just flowise today and report back. Does the flowise image already have `playwright install-deps` baked in?

**Comment by chungyau97** [comment]
Hi @TotalLag,

We didn't add the integration for Playwright. Would you like to take up the challenge and submit a PR? 

Document Reference: [Playwright Docker Integration](https://playwright.dev/docs/docker)
Source Code: [/main/Dockerfile](https://github.com/FlowiseAI/Flowise/blob/main/Dockerfile) and [/main/docker/Dockerfile](https://github.com/FlowiseAI/Flowise/blob/main/docker/Dockerfile)

**Comment by TotalLag** [comment]
I will try :)
