### ISSUE TITLE
[BUG] LangSmith configured , but it's not taking effect.

### ISSUE THREAD

**Issue by aihes** [FlowiseAI/Flowise#755]
**Describe the bug**
I noticed that the environment variable can be configured for LangSmith, and I have already configured it. However, no matter what, when I configure Chatflow in Flowise, there is no corresponding Trace in LangSmith. Even after I deleted the Docker image and restarted, it did not take effect. I tried multiple times but it didn't work.

**To Reproduce**
1. Go to the Docker directory.
2. Configure the .env file.
<img width="604" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/17943411/236be194-4c75-4c86-a02d-863e9b875691">
3. Run docker-compose up -d.
4. Create a new chatflow on port 127.0.0.1:3000, test it, and find it's not effective.
5. I tried the same configuration using LangChain code and found it was effective, so I'm sure there's no problem with the configuration. But I don't know why Flowise doesn't take effect.

**Expected behavior**

**Screenshots**
<img width="1131" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/17943411/ca54034b-a2ba-4963-affb-e38bf8eda86b">

**Flow**
If applicable, add exported flow in order to help replicate the problem.

**Setup**
1. My commit id:
commit 2550212dac1db3dd2355e11f6519c3eebee5c963 (HEAD -> main, origin/main, origin/HEAD)
2. docker-compose up -d
3. "version": "1.3.3"
4. OS: macOS
5. Browser: Chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
have you modified the `docker-compose.yml` file to pass in the env variables?

**Comment by jan-koch** [comment]
> have you modified the `docker-compose.yml` file to pass in the env variables?

Can you please elaborate on how to update the docker-compose.yml? 🙏
