### ISSUE TITLE
Hoax.JS.ExtMsg.a

### ISSUE THREAD

**Issue by neoOpus** [FlowiseAI/Flowise#77]
Event: Object deleted
User: 
User type: Initiator
Application name: node.exe
Application path: C:\Program Files\nodejs
Component: File Anti-Virus
Result description: Deleted
Type: Software that may cause harm
Name: Hoax.JS.ExtMsg.a
Precision: Exactly
Threat level: Medium
Object type: File
Object name: _postinstall.js
Object path: C:\Users\xxx\AppData\Roaming\npm\node_modules\flowise\node_modules\es5-ext
MD5 of an object: 7DE8D84BD9ECC1D0904048956C94817B

**Comment by HenryHengZJ** [comment]
hey sorry but Im not following the error here

whats the steps to replicate, your OS? Kindly follow the template so we can help to identify the issue
