### ISSUE TITLE
[QUESTION] Error [ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by bookz971** [FlowiseAI/Flowise#770]
hello, i have a problem, i created a saas application from the flowise api, the problem is that when i run this on multiple users, it gives me the following error message
I discussed on the discord support with someone and he gave me the following answer Sounds like an express error. If you call res.send multiple times in a single request then it will throw that error, because you can only respond to a request once.

Make sure to do return res.send... instead of res.send... by itself.
^^ of course, that's express specific. If you're using a different framework then the syntax might be different,
Error [ERR_HTTP_HEADERS_SENT]: Unable to set headers after sending to client
      to the new NodeError (node:internal/errors:405:5)
      on ServerResponse.setHeader (node:_http_outgoing:648:11)
      at ServerResponse.header

I would like to know how to fix this

telling me which file I have to modify and which line is there

**Setup**
-   Installation  `yarn start`]
-   Flowise Version : last version
-   OS:  Linux] UBUNTU 22.04
-   Browser  chrome,

**Comment by HenryHengZJ** [comment]
I think this error is coming from your implementation of your sass application, not from flowise
