### ISSUE TITLE
[BUG] Azure Documentation

### ISSUE THREAD

**Issue by magnoeasy** [FlowiseAI/Flowise#777]
Following the tutorial the username is set using the environment variable FLOWISE_USER instead of FLOWISE_USERNAME

Set Restart policy to On failure. Next, add 2 Environment variables FLOWISE_USER and FLOWISE_PASSWORD. Add Command override ["/bin/sh", "-c", "flowise start"]. Finally click "Review + create":

The correct text should be:

Set Restart policy to On failure. Next, add 2 Environment variables FLOWISE_USERNAME and FLOWISE_PASSWORD. Add Command override ["/bin/sh", "-c", "flowise start"]. Finally click "Review + create":

**Comment by HenryHengZJ** [comment]
thanks! fixed now
