### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by chiencarlos11** [FlowiseAI/Flowise#790]
**Describe the feature you'd like**
is it possible to have a Conversational Retrieval QA chain with prompt template. 

**Additional context**
For example create a "Conversational Retrieval QA Chain" that can respond with a system prompt like "you are a pirate and you respond in pirate language"

**Comment by HenryHengZJ** [comment]
Click the Additional Parameter, then you can specify system prompt: 
<img width="887" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/76d3c320-cfd1-44a2-9c01-0c768230d682">
