### ISSUE TITLE
[FEATURE] To add PETAL support in API

### ISSUE THREAD

**Issue by PiotrEsse** [FlowiseAI/Flowise#806]
Hi, It would be great to add Petal as an alternative backend to OpenAI. 

https://python.langchain.com/docs/integrations/llms/petals_example

**Comment by cam-s-hunt** [comment]
+1

**Comment by HenryHengZJ** [comment]
we can specify the base path to use other OpenAI compatible API: 
![image](https://github.com/user-attachments/assets/d1fd7c2f-66ad-4894-8175-9890ec55de2c)
