### ISSUE TITLE
Empty page with Vercel

### ISSUE THREAD

**Issue by Klaudioz** [FlowiseAI/Flowise#81]
**Describe the bug**
Trying to use Vercel, I can see the site for one second and after that, I got an empty website. I've tried with Chrome, Firefox and Safari

**To Reproduce**

1. Go to https://flowise-ui-delta.vercel.app

**Expected behavior**
See the site

**Additional context**
I've hosted the site with the Vercel hobby plan and the pro plan. The deployment doesn't have any issues.
One weird thing is I can't see any logs: `No active logs yet. Push changes to see results.`

<img width="1139" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/632625/3f252d92-25fe-4d8a-b9cb-b65da293cc8e">

**Comment by HenryHengZJ** [comment]
Hey we have not tried hosting it on Vercel, thus not sure if Vercel will work

**Comment by Klaudioz** [comment]
Why shouldn't work on Vercel?

**Comment by HenryHengZJ** [comment]
I was able to get the frontend working - 
<img width="928" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/1f9f338f-3f09-4028-8a54-218646cd3ce8">

But having trouble connecting to backend API. Seems like we have to create a `vercel.json` file and deploy backend code `packages/server` and frontend `packages/ui` seperately.

So its not straight-forward

**Comment by goldzulu** [comment]
AFAIK the frontend react is fine as you said to deploy on Vercel. Backend however needs bit of tweak as it's based on Express which at the fundamental level requires some form of server (Vercel is server less). It can be done but you would have to migrate the functions to be server less. https://vercel.com/guides/using-express-with-vercel It's might be straight forward with the first steps is rewriting the backend routes to go and get served from the Vercel api directory. Fair bit of refactoring though and its better to be done earlier than later if this is an architectural decision.

**Comment by PublicTrades** [comment]
> 

Great that you were able to get frontend working, what would be better is if you shared how you did it so others can learn

**Comment by PublicTrades** [comment]
Hey all, Having a similar issue deploying Flowise onto Vercel 'successfully', but not able to load the UI ( check it out: https://forgedmartaiflow.vercel.app). Please share if anyone has been able to figure out how to solve this. Thanks in advance
