### ISSUE TITLE
Unable to run Flowise and Chroma on Docker[BUG]

### ISSUE THREAD

**Issue by Ramanpreet56** [FlowiseAI/Flowise#810]
**Describe the bug**
Hi I just followed the guide mentioned to run flowise and chroma on docker. Modified my docker-compose.yml for chroma as requested but still encountering this error 

**Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed**

**To Reproduce**

I updated docker compose of Chroma to include the flowise env file and flowise reference and then ran the build up command.

This is my flow 

<img width="871" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/114490364/9919dc1d-de03-4857-beca-0ec97661e2b7">

**Expected behavior**
I would expect an answer or donot know

**Screenshots**
My Docker instance
<img width="730" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/114490364/6652b3b7-0481-4581-9df9-2ebae4694556">

**Flow**
If applicable, add exported flow in order to help replicating the problem.
<img width="871" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/114490364/08bc5f1e-cf8a-4ee3-adfd-8296a4d44c09">

**Setup**
-   Installation [e.g. docker`]
-   Flowise Version [latest]
-   OS: [Ubuntu WSL]
-   Browser [e.g. chrome, edge]

**Additional context**

**Comment by chungyau97** [comment]
Hi @Ramanpreet56, 

Try to follow this guide https://docs.flowiseai.com/vector-stores/chroma#additional

Reference:
https://github.com/FlowiseAI/Flowise/discussions/286

**Comment by Initonedeb** [comment]
HI i´m running everything in a windows machine, using Faiss works ok, but on chromadb upsert usage i get Chroma getOrCreateCollection error: Error: TypeError: fetch failed
Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed
![2023-10-10 081527](https://github.com/FlowiseAI/Flowise/assets/38872457/d1b09f59-9a07-4f82-9e25-c5a6bc32dc82)

**Comment by Initonedeb** [comment]
PLeaSE HELP!

**Comment by aghasaadmohammad** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/61001884/2c981904-d444-47f5-8452-bfa1a5e9f97c)

this error , i need help

**Comment by wenwenc9** [comment]
> ![图像](https://user-images.githubusercontent.com/61001884/274595709-2c981904-d444-47f5-8452-bfa1a5e9f97c.png)
> 
> 这个错误，我需要帮助

我遇到和你一样的错误，请问你解决了吗

**Comment by wenwenc9** [comment]
> ![图像](https://user-images.githubusercontent.com/61001884/274595709-2c981904-d444-47f5-8452-bfa1a5e9f97c.png)
> 
> 这个错误，我需要帮助

https://github.com/FlowiseAI/Flowise/issues/810#issuecomment-1759493771

@aghasaadmohammad  
I encountered the same error as you, have you solved it?

**Comment by wenwenc9** [comment]
> ![image](https://user-images.githubusercontent.com/61001884/274595709-2c981904-d444-47f5-8452-bfa1a5e9f97c.png)
> 
> this error , i need help
@aghasaadmohammad 
Remove the last /
![image](https://github.com/FlowiseAI/Flowise/assets/62178731/6db2bdad-e30d-430d-a9b0-e1143a032d6e)

**Comment by fzafir66** [comment]
Hi there I am currently facing this issue and I don't know how to resolve it. I've tried everything. I'm using Podman. 
I am actually following the tutorial posted in https://medium.com/@bjohns_49809/gen-ai-on-openshift-series-episode-3-e77b746d607e . 

Its a relatively simple tutorial however I keep getting the same error that everyone here is facing.
As you can see I've been generating the similar error for every query
![image](https://github.com/FlowiseAI/Flowise/assets/159418607/f32426b8-f431-4de6-bab4-c4b0e0525f7a)

This is the logs from the container running flowise
![image](https://github.com/FlowiseAI/Flowise/assets/159418607/6d5f6f47-8e3a-4956-a43f-aad1938261d6)

I tried the solutions available here but to no avail. Does anyone have any idea on this? Would really appreciate any help available!
