### ISSUE TITLE
[BUG] Duplicate responses

### ISSUE THREAD

**Issue by mahmoudsorf** [FlowiseAI/Flowise#813]
**Describe the bug**
when I use,
conversational retrieval QA chain => chain Tool => Open AI function agent
OR
conversational retrieval QA chain => chain Tool => conversational retrieval agent

I am getting duplicate answers.

**Comment by HenryHengZJ** [comment]
have you tried RetrievalQAChain -> ChainTool -> Agent?
Or try turning on Return Direct on ChainTool

**Comment by jrcapicua** [comment]
I notice the same, using:
MultiRetrievalQAChain => ChainTool => Open AI function agent.

I think the agent action and the chain tool response are being streamed in the agent answer.

**Comment by mahmoudsorf** [comment]
Yes I tried the function agent as well and getting the same duplication.

**Comment by HenryHengZJ** [comment]
Seems to work fine on my side using RetrievalQAChain -> ChainTool -> OpenAI Function Agent: 
<img width="1268" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/d128d327-a944-41f2-870c-5c581ae0e716">

**Comment by segelmache** [comment]
Same error as well. It's happening, when having more than one chain tools as input for the agent.

**Comment by EgorZakharov97** [comment]
Same thing here

**Comment by HenryHengZJ** [comment]
for now, a temporary workaroound is to enable Return Direct

**Comment by Dakes** [comment]
Unfortunately, this is a big issue for me as well. 
Would the fix likely be relatively straight forward, or more complicated?

**Comment by mateusluizfb** [comment]
Same happening here, even with the `Return Direct` enabled:

What is happening is:
-  `ChatOpenAI` is called by `MultiPromptChain`, returns a json containing the selected prompt 
   - This output json is streamed back to the user chat
- `ChatOpenAI` is called a second time with the selected prompt
   - The answer is streamed back to the user chat as well

Something like this:
![Screenshot 2024-05-17 at 14 43 37](https://github.com/FlowiseAI/Flowise/assets/14284674/c49c7f82-3de3-4bfc-82de-3bcfdef883c9)

In the end, the final output is looking something like:


```
`json { "destination": "selected_prompt", "next_inputs": { "input": "prompt input" } }`Some answer to some question. 
```

**Comment by moymoussan** [comment]
Same here. I get duplicate responses after the tool agent uses a custom tool

**Comment by io4x** [comment]
I also get duplicate responses, but in two messages, where the message is completed.

![Bildschirmfoto 2024-07-29 um 22 14 44](https://github.com/user-attachments/assets/8fb83f29-681c-4a31-9165-90932f46e3b4)

**Comment by Ghazalsalameh** [comment]
@io4x did u manage to solve it ?

**Comment by moymoussan** [comment]
I noticed it happens on the embedded chat but not in the built in chat of the flow editor

**Comment by io4x** [comment]
@Ghazalsalameh Aman soni was able to idenfity the fix. Resolve in next few days!

https://discord.com/channels/1087698854775881778/1267529485893238935/1268953277400088626

**Comment by HenryHengZJ** [comment]
should be resolved with https://github.com/FlowiseAI/FlowiseChatEmbed/pull/221
