### ISSUE TITLE
History of shared bot losts when refresh the web page

### ISSUE THREAD

**Issue by boxter007** [FlowiseAI/Flowise#816]
**Describe the bug**
I shared a bot , when I refresh the shared page, the chat histories  lost.

**Expected behavior**
I think that the history will be displayed

**Screenshots**
This is the bot set up.
![image](https://github.com/FlowiseAI/Flowise/assets/9445146/7eeaf2f7-95df-4c83-a449-5b57f1c4e3fd)

**Comment by HenryHengZJ** [comment]
if you mean embedded chat, currently we don't save history there

**Comment by HenryHengZJ** [comment]
history is now persists even if you refresh the embedded chatbot
