### ISSUE TITLE
NPM installation

### ISSUE THREAD

**Issue by Asterecho** [FlowiseAI/Flowise#820]
I can install Flowise with the commandline 'npm install -g flowise'

![2023-8-23 21-28-24](https://github.com/FlowiseAI/Flowise/assets/40272885/64dc02c1-87e9-4154-b64b-ebf1b2c0620e)

**Comment by HenryHengZJ** [comment]
Do you have node >= 18.15.0 ?

**Comment by GSSfearless** [comment]
I have the same issue when I follwing your guide with ndoe =18.7.1. Appreciate if you can help!
