### ISSUE TITLE
[BUG]yarn start not working

### ISSUE THREAD

**Issue by amzamani** [FlowiseAI/Flowise#832]
**Describe the bug**
Cloned the repo and followed the steps using yarn

**To Reproduce**

1. cloned and changed directory then=>
2. yarn install && yarn build && yarn start
3. install and build work fine with no error
4. when start is executed, error is encountered

**Error**
`
 Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
  Time:    2m25.321s 

✨  Done in 146.13s.
yarn run v1.22.19
$ run-script-os
$ cd packages/server/bin && ./run start
(node:1212) [ERR_DLOPEN_FAILED] Error Plugin: flowise: dlopen(/Users/amzamani/Desktop/incoming/ai/Flowise/node_modules/canvas/build/Release/canvas.node, 1): Library not loaded: @loader_path/libpixman-1.0.42.2.dylib
  Referenced from: /Users/amzamani/Desktop/incoming/ai/Flowise/node_modules/canvas/build/Release/canvas.node
  Reason: no suitable image found.  Did find:
	/Users/amzamani/Desktop/incoming/ai/Flowise/node_modules/canvas/build/Release/libpixman-1.0.42.2.dylib: cannot load 'libpixman-1.0.42.2.dylib' (load command 0x80000034 is unknown)
	/Users/amzamani/Desktop/incoming/ai/Flowise/node_modules/canvas/build/Release/libpixman-1.0.42.2.dylib: cannot load 'libpixman-1.0.42.2.dylib' (load command 0x80000034 is unknown)
module: @oclif/core@1.26.2
task: toCached
plugin: flowise
root: /Users/amzamani/Desktop/incoming/ai/Flowise/packages/server
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
 ›   Error: command start not found
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Abus-MacBook-Air:Flowise amzamani$ 

`

**Comment by amzamani** [comment]
MacOS Mojave- Version 10.14.4

Node- Version v18.17.1

**Comment by chungyau97** [comment]
Hi @amzamani. 

I believe your issue is related https://github.com/FlowiseAI/Flowise/issues/556

but do try `sudo yarn` from install to start

**Comment by isikhi** [comment]
I guess it is related with node-canvas. I did not faced this problem but i may suggest to this path to solve it:

Take a look: https://github.com/Automattic/node-canvas#compiling
Install them:
`brew install pkg-config cairo pango libpng jpeg giflib librsvg pixman`
then;
- remove `node_modules` (remove build artifacts)
- yarn install
- yarn build
- yarn dev

if it wont succeed i can also suggest to install this 
`npm install canvas --build-from-source`

then reproduce steps starting with remove `node_modules`
