### ISSUE TITLE
[BUG] Huggingface Embeddings + Pincone Upsert getting PineCone error

### ISSUE THREAD

**Issue by predoctech** [FlowiseAI/Flowise#836]
**Describe the bug**
A typical Conversational Retrieval QA Chain but with HF embeddings and LLM instead of that of OpenAI.  I have tested the same setup with in-memory vector store so has to believe it's related to Pinecone Upsert and not with API keys etc.

**To Reproduce**
1. Using a deployed Flowise 1.3.4 on Render. 
1. HF embeddings with dimension of 768.  Used a sentence-transformer model with that dimension like "sentence-transformers/all-mpnet-base-v2"
2. Initiated a Pinecone index with that dimension and named "legaldoc"
3. Run the chatflow in Flowise.  From log got this "PineconeError: PineconeClient: Error calling upsert: PineconeError: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response" 

**Setup**
-   Installation: Render
-   Flowise Version 1.3.4
-   OS: Render
-   Browser: Chrome

**Additional context**
Tried many suggestions from websearch including deleting and reinitializing a new index or making sure name of Pincone environment name is right.  Wondering how HF embedding was done behind the scene?

**Comment by darshan8850** [comment]
Hello there, @predoctech  I ran across the same error for "efederici/sentence-bert-base" , while adding hugging face inference Embeddings. Have you found a solution?

**Comment by predoctech** [comment]
@darshan8850 no I didn't find any solution.  I was hoping if it could be confirmed as a bug and fixed in upcoming version.

**Comment by chungyau97** [comment]
Hi @predoctech,

Could you share out your flow export and the models URLs?

**Comment by chungyau97** [comment]
Hey @predoctech,

I'm able to do it shown below:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/5d4705b3-f281-47ac-a246-2854843f7528)

Could you verify again whether your Pinecone config are set correctly?

**Comment by predoctech** [comment]
Thanks @chungyau97 .  Can you please take a look and see what's the problem with my Pinecone setup?

![Screenshot-Pincone](https://github.com/FlowiseAI/Flowise/assets/64902553/478fe13c-f69c-4e0d-919e-caf28aa8c970)

**Comment by darshan8850** [comment]
> @darshan8850 no I didn't find any solution. I was hoping if it could be confirmed as a bug and fixed in upcoming version.



> Hello there, @predoctech I ran across the same error for "efederici/sentence-bert-base" , while adding hugging face inference Embeddings. Have you found a solution?


Hello @predoctech I found and alternative , as not using pinecone, we can use in memory vector store instead of it.
![Screenshot 2023-08-31 223311](https://github.com/FlowiseAI/Flowise/assets/83301891/6df83d18-2f9f-4301-a423-1ed09999128e)

**Comment by chungyau97** [comment]
Hi @predoctech,

I remember that a lot of users have issue with the env name ending with `-free` and upgrading it will solve the issue.

Firstly, you could try removing the `-free` first and see whether it works. Else you will need to upgrade it.

**Comment by predoctech** [comment]
> > @darshan8850 no I didn't find any solution. I was hoping if it could be confirmed as a bug and fixed in upcoming version.
> 
> > Hello there, @predoctech I ran across the same error for "efederici/sentence-bert-base" , while adding hugging face inference Embeddings. Have you found a solution?
> 
> Hello @predoctech I found and alternative , as not using pinecone, we can use in memory vector store instead of it. ![Screenshot 2023-08-31 223311](https://user-images.githubusercontent.com/83301891/264722892-6df83d18-2f9f-4301-a423-1ed09999128e.png)

@darshan8850 thanks for the suggestion.  I know the in-memory store works but that's for a totally different scenario from a cloud storage, which offered processed embedding storage and access.

**Comment by predoctech** [comment]
> Hi @predoctech,
> 
> I remember that a lot of users have issue with the env name ending with `-free` and upgrading it will solve the issue.
> 
> Firstly, you could try removing the `-free` first and see whether it works. Else you will need to upgrade it.

Thanks @chungyau97 but removing '-free' means no longer able to use Pinecone's free plan?  So the Free Plan is not usable for Flowise?

**Comment by predoctech** [comment]
OK hard to believe this but it may have to do with which cloud environment your project resides on.  I tried all 3 free environments and now settle with "us-west4-gcp-free" and the upsert works.
