### ISSUE TITLE
[BUG]docker-flowise-1 Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by lascqy** [FlowiseAI/Flowise#841]
**Describe the bug**
start with docker use the 'docker compose up'

pull the latest image again

then
 ✔ Network docker_default      Created                                                                 0.2s 
 ✔ Container docker-flowise-1  Created                                                                 4.3s 
Attaching to docker-flowise-1
docker-flowise-1  |     Error: ENOENT: no such file or directory, mkdir
docker-flowise-1  |     Code: ENOENT
docker-flowise-1 exited with code 0

how could I deal with this?

**Comment by HenryHengZJ** [comment]
do you have the `.env` set similar to [here](https://github.com/FlowiseAI/Flowise/tree/main/docker)

**Comment by adolfousier** [comment]
I was able to solve this issue by setting up a variable NODE_VERSION=18.15.0 but also increasing RAM from 512mb to 2gb, now everything is working fine on render/railway with node or docker.
