### ISSUE TITLE
Critical vulnerabilities related to the vm2 package and its usage within the flowise-components package.

### ISSUE THREAD

**Issue by jbinnscornick** [FlowiseAI/Flowise#850]
# npm audit report

vm2  *
Severity: critical
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-cchq-frgv-rjh5
vm2 Sandbox Escape vulnerability - https://github.com/advisories/GHSA-g644-9gfx-q4q4
No fix available
node_modules/vm2
  flowise-components  >=1.2.14
  Depends on vulnerable versions of vm2
  node_modules/flowise-components

2 critical severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

**Comment by PythonbergIT** [comment]
Do you know when this will be fixed?

**Comment by HenryHengZJ** [comment]
resolved now in v2.1.1
