### ISSUE TITLE
[QUESTION] customer support agent

### ISSUE THREAD

**Issue by makemoney2023** [FlowiseAI/Flowise#855]
**Describe the feature you'd like**
How do you create a chain that acts as a customer support agent and is able to capture primary and secndary keys and writes json to a function to be used with an api for data CRUD. Also want to be able to summarize the conversation when completed and capture the sentiment and uses a tool to send an email with the conversation summary and sentiment attached.

**Comment by HenryHengZJ** [comment]
for now flowise can't capture information from chat to be used for other operation yet. sounds like you have to use different chatflows to achieve what you're trying to do, also with chatbot builder like botpress/voiceflow

**Comment by HenryHengZJ** [comment]
most likely we can achieve this using agentflow: 
![image](https://github.com/user-attachments/assets/b4856d2b-ac69-402b-9a7d-b2656b2fd636)
