### ISSUE TITLE
[BUG]unable to connect to https://cdn.jsdelivr.net/npm/flowise-embed/dist/web.js from mainland China

### ISSUE THREAD

**Issue by delinecnlin** [FlowiseAI/Flowise#856]
In this case the visitor of the page cannot call out the chat window

**Comment by chungyau97** [comment]
Hey @delinecnlin,

Another workaround will be accessing the file through GitHub on your Forked Repo shown in this guide: https://docs.flowiseai.com/how-to-use#embed
