### ISSUE TITLE
[BUG] Custom tool is not working

### ISSUE THREAD

**Issue by FahadAltaf** [FlowiseAI/Flowise#857]
I am trying to call an API. It's giving the same error every time. I have used the test sample in the custom tool but still the same.

Request failed with status code 400 and body {"error":{"message":"'Get the weather' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.0.name'","type":"invalid_request_error","param":null,"code":null}}

**Comment by chungyau97** [comment]
Hey @FahadAltaf,

Could you share the export of your flow and the source code of the tool?

**Comment by FahadAltaf** [comment]
Sure

[API test v1 Chatflow.txt](https://github.com/FlowiseAI/Flowise/files/12484955/API.test.v1.Chatflow.txt)

**Comment by chungyau97** [comment]
Hi @FahadAltaf,

My result below:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/8024bbd9-7c74-4917-b2d2-4c841abcfb17)
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/44fddc91-0e06-4a39-bc88-4893940da930)

**Comment by FahadAltaf** [comment]
ok found the problem name of the tool should be lowercase without spaces.

Its little confusing you have to hover on the information icon to see how the name should be formatted but by just looking at placeholder you can have spaces in the name. Would be great if you can also update placeholder, add name validation or add helper text under the field so that its visible to user
![image](https://github.com/FlowiseAI/Flowise/assets/5881092/35cb5b8c-5507-45ae-a14a-f7a4317ab452)
