### ISSUE TITLE
[FEATURE] PaLM API support

### ISSUE THREAD

**Issue by mdda** [FlowiseAI/Flowise#862]
**Describe the feature you'd like**
[PaLM API](https://developers.googleblog.com/2023/03/announcing-palm-api-and-makersuite.html) is a gentler entry point to accessing Google's PaLM model than the 'enterprise ready' Vertex AI APIs (which are covered by Flowise, according to accepted PRs like https://github.com/FlowiseAI/Flowise/pull/713 )

**Additional context**
Getting the API key for PaLM is a couple of clicks on [their API page](https://developers.generativeai.google/tutorials/setup), and may be more suitable for quick experimentation than the full Vertex AI account set-up.

It appears that PaLM API is [integrated into langchainjs](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/googlepalm.ts) - which should make it easier, correct?

If people think this is a reasonable idea, I'd be happy to put together a PR, and (likely) some presentation/video content to go along with it.  If, on the other hand, this is a silly idea (for whatever reason) just let me know :-)

**Comment by HenryHengZJ** [comment]
I think this is an awesome idea, been meaning to do this but don't have time yet. Would be great if you are able to make a PR 🙏

**Comment by mdda** [comment]
I'm happy to do this - give me a couple of days...

**Comment by HenryHengZJ** [comment]
thanks again @mdda !

**Comment by kientv** [comment]
Palm API in makersuite is not working with models/chat-bison-001
