### ISSUE TITLE
[BUG] Conversational Retrieval Agent can't connect to Azure Chat open AI.

### ISSUE THREAD

**Issue by eheading** [FlowiseAI/Flowise#864]
**Describe the feature you'd like**
Conversational Retrieval Agent can only connect to Chat open AI now, it can't connect to Azure Chat open AI.
Please consider to support it. Thanks.

**Comment by dzbaiyang** [comment]
Is the problem solved?

**Comment by paulduraiin** [comment]
Would be eager to see this issue fixed. Need to connect Azure OpenAI LLM.

**Comment by eheading** [comment]
> Is the problem solved?

No, the problem is still here. Azure open AI can only do retrieval QA on Flowise and it can't work on conversational retrieval chain. As a result, we can't use memory in chains and it lets Azure open AI not useful enough on Flowise AI. It can only do simple Q&A in such case. 

Please correct me if I was wrong. I am still learning it actually. Many thanks.

**Comment by chungyau97** [comment]
Hi @eheading,

I believe this is not a bug as the `agentType: 'openai-functions'` do not support Azure OpenAI
Tested Below:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/56a12db8-1f17-404b-a4f4-2c69466a82c1)
```
[llm/error] [1:chain:AgentExecutor > 2:llm:ChatOpenAI] [1.28s] LLM run errored with error: "Request failed with status code 404 and body {\"error\":{\"message\":\"Unrecognized request argument supplied: functions\",\"type\":\"invalid_request_error\",\"param\":null,\"code\":null}}"
[chain/error] [1:chain:AgentExecutor] [1.28s] Chain run errored with error: "Request failed with status code 404 and body {\"error\":{\"message\":\"Unrecognized request argument supplied: functions\",\"type\":\"invalid_request_error\",\"param\":null,\"code\":null}}"
```

cc @HenryHengZJ

**Comment by eheading** [comment]
Hi @chungyau97 Yes, I know it's not a bug. That's why I listed it's a feature originally. Thanks.

**Comment by zeitderforschung** [comment]
The retrieval agent works as expected, when changing the model type from `ChatOpenAI` to `BaseModel`. I don't think it is a good solution, but it works.
See patch at https://github.com/exdatic/flowise/commit/a05dd2b55998a8116430c2294bda1901c6b3322a.

**Comment by Jakub-Zak** [comment]
Facing exactly the same issue: I'm not able to successfully call any service on our endpoint and all calls ends with this error. I did a test and tried to call CURL command from our server where I have deployed Flowise. Both chat and embedding services, when utilized via CURL works. When I setup configuration in Flowise, both calls ends with **404 status code (no body)**. I've tested all possible configurations (using both types - Agents and Chains)...No success. Any idea when there will be a fix?

**Comment by Proteusiq** [comment]
I would like this to work as Azure OpenAI is becoming most used more and more.

**Comment by Proteusiq** [comment]
> > Is the problem solved?
> 
> No, the problem is still here. Azure open AI can only do retrieval QA on Flowise and it can't work on conversational retrieval chain. As a result, we can't use memory in chains and it lets Azure open AI not useful enough on Flowise AI. It can only do simple Q&A in such case.
> 
> Please correct me if I was wrong. I am still learning it actually. Many thanks.

Could you share QA retrieval example that works?

**Comment by Proteusiq** [comment]
Lots of thanks @dkindlund 🙏🏿🫶🏾. Everything is working perfectly
