### ISSUE TITLE
How to use Azure ChatOpenAI?

### ISSUE THREAD

**Issue by dzbaiyang** [FlowiseAI/Flowise#866]
I'm deploying with Docker and reporting a network error when using Azure ChatOpenAI.
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/e348999c-4b74-4dfc-b1b3-b0d60b30c06c)
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/abd8552d-c11d-4de3-86dc-acb140cc9970)

My call to OpenAI's interface is working fine.

Is something configured incorrectly?

**Comment by dzbaiyang** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/76d06933-e8f0-482d-b490-5684f940465a)

**Comment by chungyau97** [comment]
Hi @dzbaiyang,

Azure is working properly tested below: 
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/15319317-cb79-4d98-9416-f870c84c5678)

Do checkout our docs on how to setup Azure OpenAI:
1. [Azure OpenAI Embeddings](https://docs.flowiseai.com/embeddings/azure-openai-embeddings)
2. [Azure ChatOpenAI](https://docs.flowiseai.com/chat-models/azure-chatopenai)

**Comment by dzbaiyang** [comment]
> Hi @dzbaiyang,
> 
> Azure is working properly tested below: ![image](https://user-images.githubusercontent.com/33013947/265243058-15319317-cb79-4d98-9416-f870c84c5678.png)
> 
> Do checkout our docs on how to setup Azure OpenAI:
> 
> 1. [Azure OpenAI Embeddings](https://docs.flowiseai.com/embeddings/azure-openai-embeddings)
> 2. [Azure ChatOpenAI](https://docs.flowiseai.com/chat-models/azure-chatopenai)

I've checked it three times.
There is no problem using OpenAI's interface, but this problem occurs with Azure. I'm in a Docker container and executing Python is also passable.

![image](https://github.com/FlowiseAI/Flowise/assets/20250566/aad4503e-4567-4c48-bcee-9f64d1fc31c6)
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/02ee01e7-9463-4101-9d67-6cba48ad15e6)

**Comment by dzbaiyang** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/e48508ea-91ca-408f-8d45-5562d621afd3)
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/c50f0ef2-94ce-4581-8d2b-93ea06eaab0e)
The instance in this form is for Endpoint, right?

**Comment by paulduraiin** [comment]
I fixed the issue I had by replacing the value in "Azure openai API instance name" field to the Azure OAI portal "Resource Name" which you can see on the top right corner of your azure portal when you go https://oai.azure.com/portal/

**This is not the API Base URL value.**

**Comment by chungyau97** [comment]
Hi @dzbaiyang, 

As mentioned in [step 5 of the document](https://docs.flowiseai.com/chat-models/azure-chatopenai#azure-chatopenai), clarifies that `Instance name` is at the top right corner in Azure AI Studio.

**Comment by dzbaiyang** [comment]
> I fixed the issue I had by replacing the value in "Azure openai API instance name" field to the Azure OAI portal "Resource Name" which you can see on the top right corner of your azure portal when you go https://oai.azure.com/portal/
> 
> **This is not the API Base URL value.**

I tried this method but it feels like a new error.

![image](https://github.com/FlowiseAI/Flowise/assets/20250566/e872114d-3806-4d9a-abd2-40c697ceaaff)
![image](https://github.com/FlowiseAI/Flowise/assets/20250566/b27b5053-befc-42be-bb03-283069dba20a)

![image](https://github.com/FlowiseAI/Flowise/assets/20250566/325278d9-85b6-4f60-a82b-c542e9f2312f)

**Comment by dzbaiyang** [comment]
> 

![image](https://github.com/FlowiseAI/Flowise/assets/20250566/bad3145b-9be0-444c-9ded-318bccf808f3)

![image](https://github.com/FlowiseAI/Flowise/assets/20250566/eabe8fe3-f1dd-4fb6-b798-ce2a9e32a1bd)

![image](https://github.com/FlowiseAI/Flowise/assets/20250566/f66b144d-302d-4a65-987e-9f6ab0f7200a)

I tried this method but it feels like a new error.

**Comment by chungyau97** [comment]
Hey @dzbaiyang,

Are you using this as your `Azure OpenAI API Key`?
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/c4bd654f-4308-4b75-b468-eb973b2a7144)

**Comment by dzbaiyang** [comment]
> Hey @dzbaiyang,
> 
> Are you using this as your `Azure OpenAI API Key`? ![image](https://user-images.githubusercontent.com/33013947/265572008-c4bd654f-4308-4b75-b468-eb973b2a7144.png)

I resolved the issue after restarting Docker.
