### ISSUE TITLE
Replicate error: "Invalid version. It must be in the format \"owner/name:version\""

### ISSUE THREAD

**Issue by kientv** [FlowiseAI/Flowise#877]
I tried to use Replicate on latest version (build from main branch today)
```
flowise-flowise-1  | [chain/error] [1:chain:ConversationalRetrievalQAChain] [80.29s] Chain run errored with error: "Invalid version. It must be in the format \"owner/name:version\""
flowise-flowise-1  | 2023-09-05 12:08:47 [ERROR]: [server]: Error: Invalid version. It must be in the format "owner/name:version"
flowise-flowise-1  | Error: Invalid version. It must be in the format "owner/name:version"
flowise-flowise-1  |     at Replicate.run (/usr/src/packages/node_modules/replicate/index.js:102:13)
flowise-flowise-1  |     at /usr/src/packages/node_modules/langchain/dist/llms/replicate.cjs:67:102
flowise-flowise-1  |     at /usr/src/packages/node_modules/langchain/dist/util/async_caller.cjs:60:66
flowise-flowise-1  |     at RetryOperation._fn (/usr/src/packages/node_modules/p-retry/index.js:50:18)
flowise-flowise-1  |     at Timeout._onTimeout (/usr/src/packages/node_modules/retry/lib/retry_operation.js:85:10)
flowise-flowise-1  |     at listOnTimeout (node:internal/timers:569:17)
flowise-flowise-1  |     at process.processTimers (node:internal/timers:512:7)

```

**Comment by HenryHengZJ** [comment]
@kientv are you running Flowise via docker/npm/yarn ?

**Comment by kientv** [comment]
> @kientv are you running Flowise via docker/npm/yarn ?

I used `yarn run` in docker

**Comment by KewkLW** [comment]
I was getting this issue as well, the problem ended up being the model was not correct. It was: 

`meta/llama-2-70b-chat`

but it wanted: 

`meta/llama-2-70b-chat:02e509c789964a7ea8736978a43525956ef40397be9033abf9fd2badfe68c9e3`

I got the full model name from the [replicate API page](https://replicate.com/meta/llama-2-70b-chat/api).

**Comment by KewkLW** [comment]
I was getting this issue as well, the problem ended up being the model was not correct. It was:

meta/llama-2-70b-chat

but it wanted:

meta/llama-2-70b-YOUR-CUSTOM-API-KEY

I got the full model name from the [replicate API page](https://replicate.com/meta/llama-2-70b-chat/api).
