### ISSUE TITLE
Flowise + Qdrant Load Existing Index (cloudhosted). Qdrant Receiver never returns any output.

### ISSUE THREAD

**Issue by cinemapara** [FlowiseAI/Flowise#883]
**Describe the bug**
Flowise + Qdrant Load Existing Index (cloudhosted) never retuns any context. 
When you create a basic QA setup with Qdrant Load Existing Index, the Qdrant Receiver never returns any output. 
Qdrant Server URL is pointing to the cloud hosting.

When i test the same setup in a google colab, it works with no problems. When i use pinecone load index it also works, so it must be related to the qdrant load existing Index Features in combination with cloud based hosting of the qdrant vectorDB.
See my 2 screenshots attached for details.

Screenshot of the flowise setup
<img width="1488" alt="Flowise_does_not_work" src="https://github.com/FlowiseAI/Flowise/assets/59502516/20411a26-b851-4e37-a9d0-ef644fffb7b3">
Setup in google colab which is working with the same index
<img width="1423" alt="Colab_works" src="https://github.com/FlowiseAI/Flowise/assets/59502516/fda11f1c-9bbc-4387-a9e4-eca63e5f01fd">

**Comment by cinemapara** [comment]
@govind-kumarr Thanks for your implementation of qdrant. I am really a fan of their vector DB. Unfortunately it does not work for me. Can you take a look? This would be awesome. Thx.

**Comment by Anush008** [comment]
Hey @cinemapara. I've got a setup similar to you and the generations work fine for me. Can you confirm the collection points have payloads with content to answer your query?
<img width="1006" alt="Screenshot 2023-09-10 at 12 34 43 PM" src="https://github.com/FlowiseAI/Flowise/assets/46051506/e65266b3-1b8b-47a0-9731-42d1462048f1">

**Comment by cinemapara** [comment]
Hello @Anush008 thanks for your feedback. The Qdrant collection is correctly searched according to qdrant logs and response returned - but the response is never submitted to the conversational retrieval QA chain. You can test this by activating "return source documents" in your sample. It will not list any documents.

**Comment by Anush008** [comment]
@cinemapara. I did get the flow to return source documents. Can you confirm that you've saved your flow after enabling "Return source documents"?
<img width="1127" alt="Screenshot 2023-09-11 at 11 18 38 PM" src="https://github.com/FlowiseAI/Flowise/assets/46051506/fcf6a292-9a8c-4ed0-80e4-794b580403cc">

<img width="1127" alt="Screenshot 2023-09-11 at 11 18 52 PM" src="https://github.com/FlowiseAI/Flowise/assets/46051506/c3c147e0-5643-4262-bfe8-4d47d5aeb06e">

**Comment by cinemapara** [comment]
@Anush008 yes i saved it but still i do not get any output from the qdrant receiver. Do you specify anything under qdrant -> loading index -> additional parameters ? i tried adding the collection name there aswell but it did not help either (see screenshot). I am lost. Thanks a lot for taking your time supporting on this


<img width="1218" alt="Bildschirmfoto 2023-09-12 um 09 38 36" src="https://github.com/FlowiseAI/Flowise/assets/59502516/9fe04039-f045-4cd4-a748-0d636a5be149">

**Comment by Anush008** [comment]
No additional configurations. The only variability I can see among our setups are the collections.

**Comment by cinemapara** [comment]
Hello @Anush008 thanks for your feedback. I figured it out. My payload inside qdrant was page_content but flowise seems to expect payload = content. That was the problem. Thanks for your support.

**Comment by Anush008** [comment]
Great👍👍
