### ISSUE TITLE
Maintain Session ID to differentiate conversations between each user

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#885]
I have the following flow that works well for one user at a time but not multiple users at once. How can i pass a sessionID to this flow and maintain each user's session? I know we can use Zep memory for other use cases. What are the options in this case?

![image](https://github.com/FlowiseAI/Flowise/assets/121184261/d20e44aa-9cb1-4ebf-b1c5-0f75adb89ed8)

**Comment by chungyau97** [comment]
This PR will be what you're looking for https://github.com/FlowiseAI/Flowise/pull/715, currently awaiting completions in this sequence https://github.com/FlowiseAI/Flowise/pull/873 > https://github.com/FlowiseAI/Flowise/pull/843 > https://github.com/FlowiseAI/Flowise/pull/715

**Comment by vijaykammili** [comment]
Thank you @chungyau97 for the quick response. Are you able to provide a timeline? I'm assuming this will fix two users not receiving responses for each other's questions? (It didn't seem clear from the other PRs so I wanted to clarify). 

Currently if we make a call via API for user A with question a and another API call with User B with question b, User A is getting responses for User B and vice versa. Let me know. Great work btw!

**Comment by chungyau97** [comment]
Hi @vijaykammili,

You have no other options beside using `Zep Memory` or alternative memory like `Motorhead Memory`.
Finally, you will need to provide a unique `sessionId` for each users in your API request.
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/17ae7023-26bb-4126-ba5a-14ea04112afe)

This PR #715, will create a unique `sessionId`. Hopefully, I can complete it before this 3 PRs [#873 > #843 > #715] before October starts.

**Comment by vijaykammili** [comment]
Thank you, again @chungyau97!
