### ISSUE TITLE
[FEATURE] Use FineTuned Models from ChatGPT

### ISSUE THREAD

**Issue by SerenityNrrd** [FlowiseAI/Flowise#886]
Is it possible to allow to use our Own Funetines models in the Flow?

**Comment by chungyau97** [comment]
Hi @SerenityNrrd, 

Do you mean this?
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/76b5a6ef-0717-4a6e-b6fc-59fb7a2c19e1)

**Comment by SerenityNrrd** [comment]
Thanks... not sure how i missed that. Maybe i need to make sure i am up to date.

**Comment by chungyau97** [comment]
Hey @SerenityNrrd,

Just to add it's not yet release to the public yet, but you can use it through [developer setup guide](https://github.com/flowiseai/flowise#-developers).

To keep up to dates on our releases, you can follow our [Twitter](https://twitter.com/FlowiseAI) and join our [Discord](https://discord.gg/y72X65SWrs) community.

**Comment by SerenityNrrd** [comment]
@chungyau97 that is awesome... I might have to try the dev version... Do you know is it possible to bring the Flowise Bot to The Teams App... ? that would be awesome...

**Comment by chungyau97** [comment]
Hey @SerenityNrrd,

You can try using Zapier to achieve this. https://docs.flowiseai.com/3rd-party-platform-integration/zapier-zaps
