### ISSUE TITLE
InsufficientQuotaError: You exceeded your current quota, please check your plan and billing details.

### ISSUE THREAD

**Issue by minazkh** [FlowiseAI/Flowise#887]
I keep getting this error - InsufficientQuotaError: You exceeded your current quota, please check your plan and billing details when I am running Flowise.

I checked my OpenAI account and its good. My render account is brand new. I tried with Pinecone and Qdrant vectors. I deleted and reinstalled Flowise, but still keep getting that errors.

Has anyone else encountered that or found the reason?

**Comment by chungyau97** [comment]
Hi @minazkh,

Try checking your OpenAI account's usage: https://platform.openai.com/account/usage

Reference:
[Official OpenAI Article](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details)

**Comment by Coffey1319** [comment]
I'm having the same issue.  Not sure what side it's coming form

**Comment by chungyau97** [comment]
Hi @Coffey1319,

Refer to my previous comment.

**Comment by minazkh** [comment]
> Hi @minazkh,
> 
> Try checking your OpenAI account's usage: https://platform.openai.com/account/usage
> 
> Reference: [Official OpenAI Article](https://help.openai.com/en/articles/6891831-error-code-429-you-exceeded-your-current-quota-please-check-your-plan-and-billing-details)

Yes, that was the issue. Thanks
