### ISSUE TITLE
[BUG]When I use ChatOpenAI，throw the follow error

### ISSUE THREAD

**Issue by huicewang** [FlowiseAI/Flowise#890]
Request failed with status code 404 and body {"error":{"message":"This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?","type":"invalid_request_error","......

**Comment by huicewang** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/19237481/0961a12e-0fd6-4069-b35e-8cf481a3a4a4)

**Comment by chungyau97** [comment]
Hi @huicewang, 

I think your issue is related to https://github.com/FlowiseAI/Flowise/issues/8#issuecomment-1573057901
