### ISSUE TITLE
[FEATURE] Embedded chat: Open links returned by bot in a new tab

### ISSUE THREAD

**Issue by christos-bsq** [FlowiseAI/Flowise#895]
**Describe the feature you'd like**
If the chatbot returns a link (e.g. you are what's Google's homepage), then the link should open in a new tab.

This is applicable to the embedded chatmessage (pop-up or full screen).

**Comment by HenryHengZJ** [comment]
PR merged and released! - https://github.com/FlowiseAI/FlowiseChatEmbed/pull/102
