### ISSUE TITLE
[BUG] OpenaiChat & Airtable Agent Causing Memory Problems 

### ISSUE THREAD

**Issue by WizKid1968** [FlowiseAI/Flowise#897]
**Describe the bug**
When using Airtable Agent server (RENDER) runs out of memory. A query against an Airtable table produces a large string of what looks like html and json code. The Airtable table has approximately 1000 records.

The provided logs give insight into a sequence of events happening on a server. Here's a breakdown of the significant steps:

API Calls:

At 03:13:50 AM, an HTTP PUT request is made to the /api/v1/credentials endpoint.
At 03:15:10 AM, an HTTP POST request is made to the /api/v1/chatflows endpoint.
Two POST requests are made at 03:15:25 AM to /api/v1/chatmessage and /api/v1/internal-prediction endpoints, respectively.
A new chatflow with a specific ID is added to the ChatflowPool.
Python Libraries Loading:

The server attempts to load Python packages, such as pandas, numpy, python-dateutil, six, and pytz.
For each package, if it isn't found locally, the server attempts to fetch it from a CDN (https://cdn.jsdelivr.net/pyodide/).
The successful loading of the packages is indicated by the logs mentioning they are being cached.
Error & Restart:

At 03:16:01 AM, there's a SIGKILL signal error, which is a forceful termination of a process.
This is followed by a Command failed with exit code 1 error message, indicating that the process didn't end gracefully.
Yarn (a package manager) logs indicate that a command failed, and the documentation link is provided.
Immediately after the error, there's an attempt to restart the server with yarn run.
Server Restart:

At 03:16:11 AM, the server logs suggest that the server (named Flowise) is starting.
The server is successfully listening at port 10000, and the data source has been initialized.
Possible Implications:

The logs might suggest that there was an issue with memory or some resource constraint when trying to load Python libraries (like Pandas, Numpy, etc.) in an environment like Pyodide. This is inferred from the sequence where packages are loaded, followed by a SIGKILL signal.

After the error, there's an automatic recovery mechanism to start the server, which seems to be successful.

**To Reproduce**

1. Connect ChatOpenAI to Airtable Agent
2. Ask a question
3. See useless html codes of data.
4. Server runs out of memory

**Expected behavior**
I expect an answer to my question related to the dataset that is connected to airtable.

**Setup**
-   Installation [render]
-   Flowise Version [latest]
-   OS: [MacOS]
-   Browser [Chrome]

**Additional context**

**Comment by chungyau97** [comment]
Hi @WizKid1968,

Try upgrading to `Standard`. If error still occurs, go up 1 more level.
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/4cfadbbe-2423-49d8-9f9f-47d97055adfe)

**Comment by chungyau97** [comment]
Hi @WizKid1968,

Just upgrade to `Standard` and it will work.
