### ISSUE TITLE
Google Makersuite Palm 2 support

### ISSUE THREAD

**Issue by 135Prithvi** [FlowiseAI/Flowise#901]
**Adding support for palm 2 without GCP with makersuite free api**
It would be nice to support this as most people dont have vertex ai.
https://makersuite.google.com

Also
**I dont know to to submit a PR**

**Comment by chungyau97** [comment]
Hi @135Prithvi,

It's also shown that it's required in [LangChain JS Google PaLM](https://js.langchain.com/docs/modules/model_io/models/llms/integrations/google_palm). It's required to add API key to access to Google PaLM. 

Could you try your API Key with Google PaLM, ignore the current naming `Google MakerSuite`
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/0b0d4321-9f43-4e30-9ce2-94066e3975ea)

**Comment by kientv** [comment]
Cannot read properties of undefined (reading 'text')

**Comment by HenryHengZJ** [comment]
Closing as Palm now deprecated
