### ISSUE TITLE
[BUG] chat window 

### ISSUE THREAD

**Issue by thebrahman** [FlowiseAI/Flowise#904]
**Describe the bug**
The whole browser window goes white while a reply is being streamed. upon refresh, the whole browser window goes white as soon as you click the icon to open the chat window. I get this error when using a 'conversational retrieval QA chain' OR 'a retrieval QA chain' with pinecone retrieval, sentence-transformers/all-MiniLM-L6-v2 and gpt3.5turbo.

No error occurs while using the API, it works as intended.

If I duplicate the bugged flow and chat with it, it might get halfway through a response that involves retrieval before the whole window turns white.  Then If i refresh the window, it turns white as soon as soon as I click the chat Icon. 

Server logs show no error, just the normal POST (although I am sure there must be a dev mode for terminal that shows more logs?)

the white web page displays this upon inspection:
"<noscript>You need to enable JavaScript to run this app.</noscript>"

**To Reproduce**

1. create a flow like in my screenshot/provided export 
2. Click on the chat icon
3. ask the bot to do a retrieval task

**Expected behavior**
The chat to happen as normal

**Screenshots**

![image](https://github.com/FlowiseAI/Flowise/assets/8326480/cfbb5d16-6233-4bed-8317-3d2f0b0fea23)

**Flow**
attached in zip

**Setup**
-   tested on local dev install and server install
-   tested with pull from september 10th
-   OS: windows + render node env
-   Brave +edge

**Additional context**

[buggedChatflow.zip](https://github.com/FlowiseAI/Flowise/files/12572418/buggedChatflow.zip)

**Comment by thebrahman** [comment]
I have reinstalled multiple times and still get the same error. node version 20.6.1, fresh docker install. Can someone please replicate the error so that this gets acknowledged, it is really hindering my work.

**Comment by chungyau97** [comment]
Hi @thebrahman, I'm not able to replicate your error.

Upsert:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/8729e81e-0d7e-4517-9f58-f1e0384b56c2)
Load Existing:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/6ba14400-5b31-4ddb-bc6e-e2d5c453867a)

**Comment by thebrahman** [comment]
@chungyau97  thank you, I have tried multiple browsers on the same computer, I will now try on a different computer and see if I can find the issue.

**Comment by chungyau97** [comment]
Hi @thebrahman, 

The model used is in 384 dimension, make sure to setup pinecone to that dimension.
Furthermore, try [nvm windows](https://github.com/coreybutler/nvm-windows) to manage different nodejs version. I'm currently using `v18.17.0`.

**Comment by thebrahman** [comment]
I have done further testing, when using Upsert within flowise you get the following schema:
```
{
  "content": "Example content",
  "metadata": {
    "blobType": "",
    "loc": {
      "lines": {
        "from": 1,
        "to": 2
      }
    },
    "source": "blob"
  }
}
```

when uploading to the VDB manually I have experimented with many schemas, this is one example:

```
{
  "Content": {
    "Chunk": "Chunk-2/3",
    "Markdown": " Example markdown content",
    "Title": "example title",
    "URL": "https://www.example-title.com"
  },
  "index": {
    "Title": "example title",
    "URL": "https://www.example-title.com"
  }
}
```
This is another example:
```
{
    "Chunk": "Chunk-2/3",
    "Markdown": " Example markdown content",
    "Title": "example title",
    "URL": "https://www.example-title.com"
}
```

All custom schemas I try result in the page turning white when i try to chat with the bot.
