### ISSUE TITLE
[BUG]Issue with Qdrant Collection Configuration Filter in JSON Payload

### ISSUE THREAD

**Issue by samsam002** [FlowiseAI/Flowise#910]
Description:
I am trying to send a JSON payload with a specific filter configuration according to the Flowise documentation. However, I am encountering issues with the filter not working as expected.

JSON Payload:
```

{
    "question": "isms",
    "overrideConfig": {
        "qdrantCollectionCofiguration": {
            "filter": {
                "must": [
                    {
                        "key": "classuers",
                        "match": {
                            "any": [
                                "black",
                                "yellow"
                            ]
                        }
                    }
                ]
            }
        }
    }
}
```
Expected Outcome:
I expected the filter to work correctly, filtering the results based on the classuers field matching any of the specified values ("black", "yellow").

But it never filters the output.

Here is the strucutre of points in Qdrant 
![image](https://github.com/FlowiseAI/Flowise/assets/13945150/b13c48a4-20f8-4cda-ad74-cfad1ad5dcf3)

**Comment by Anush008** [comment]
Hey @samsam002. Could you provide your flow-setup?

**Comment by samsam002** [comment]
hey, here is it, 
![image](https://github.com/FlowiseAI/Flowise/assets/13945150/d597b63c-bb0f-489f-84b4-e7f742530e98)

**Comment by Anush008** [comment]
The filter used by you appears to be in order. What were the steps you took to apply the filters and was the output a search result without your filters applied?

**Comment by Anush008** [comment]
I seem to found the issue here. You're trying to filter the results by passing the filter obj to the `qdrantCollectionConfiguration` property which is meant to receive collection creation config.
https://github.com/qdrant/qdrant-js/blob/b9f9333c491c41819518f4e58d6df002a7032108/packages/js-client-rest/src/openapi/generated_schema.ts#L1093-L1134

**Comment by samsam002** [comment]
thanks for the feedback, any clue to get filtered result as in the "pinecone load existing " one ?

**Comment by Anush008** [comment]
As of now, the filters params aren't configurable when querying with Flowise and Qdrant.

**Comment by Anush008** [comment]
As of now, the filters params aren't configurable when querying with Flowise and Qdrant.

I'll see to parameterize this value.

**Comment by samsam002** [comment]
thnak you @Anush008 .
 i'm really sad to head this, i've build a whole project assuming it is supported since it is a core concept at Qdrant. I'll be grateful if some one gives me a turn around to acheive this. i compared the pinecone class with qdrant and seems possible to me. although i'm not experienced with nodejs projects.

**Comment by Anush008** [comment]
I'm working on adding the filter. Should be done by today if everything goes right. I'll let you know when the PR is up.

**Comment by Anush008** [comment]
@samsam002, you can checkout #912.

**Comment by samsam002** [comment]
GREAT thanks to you. i'll test it out and feed back.
