### ISSUE TITLE
[BUG] Can't update credentials

### ISSUE THREAD

**Issue by artemdzyuba** [FlowiseAI/Flowise#916]
upd. deleted creds and re-created them, problem gone

**Describe the bug**
I can't update credentials. I see a window I can't type in.

**To Reproduce**

1. Go to Credentials
2. Click on Edit button
3. See error — non-editable window

**Expected behavior**
A pop-up where I can edit the credentials

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/20184727/31f92588-aa70-4f6a-a052-543913939a8a)

**Setup**
-   Installation - docker compose
-   Flowise Version - I can't see my version, in About Flowise I see 1.3.4, but this is the latest version I guess.
-   OS - Ubuntu installation, Windows on my device
-   Browser Chrome

**Comment by chungyau97** [comment]
Hi @artemdzyuba, 

Refer here: https://github.com/FlowiseAI/Flowise/issues/915#issuecomment-1720915633
