### ISSUE TITLE
[BUG] PineconeClient: Error calling upsert:

### ISSUE THREAD

**Issue by artemdzyuba** [FlowiseAI/Flowise#919]
**Describe the bug**
When created a Conversational QA Chain with Pinecone, I get this:

PineconeError: PineconeClient: Error calling upsert: PineconeError: PineconeClient: Error calling upsertRaw: FetchError: The request failed and the interceptors did not return an alternative response

**To Reproduce**

1. Go to Marketplace
2. Use the "Conversational Retrieval QA Chain" teplate
3. Assign creds, attach a text file
4. Save and start dialog

**Expected behavior**
Chatting with the model

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/20184727/40740692-25e2-4ee7-aca9-2e18f615cef9)

**Setup**
-   Installation - docker compose
-   Flowise Version 1.3.4
-   OS - Ubuntu installation, Windows on my device
-   Browser Chrome

**Comment by chungyau97** [comment]
Hi @artemdzyuba, refer here https://github.com/FlowiseAI/Flowise/issues/836

**Comment by artemdzyuba** [comment]
> Hi @artemdzyuba, refer here #836

Thank you. But I found no solution there. Removing "free" from environment means misspelling the its name. And I don't want to switch to a paid tariff. I tried this case via raw API and it works perfectly,
