### ISSUE TITLE
[BUG] 400 error API Call from Bubble.io (FOR BUSINESS)

### ISSUE THREAD

**Issue by camilordg96** [FlowiseAI/Flowise#920]
Hi guys.

I am using Flowise, Bubble and Whatsapp API to have AI on whatsapp. However when I make the API call it works only some times. Most of the times it returns this 400 error: Temporary error connecting to Flowise API - Camilo CEO API (raw message: Request failed with status code 400)
{"statusCode":400,"message":"Temporary error connecting to Flowise API - Camilo CEO API (raw message: Request failed with status code 400)","args":{"bubble_code":"1694619600175x964857302873715700"}}

However when I talk to the chat of my flowise project and then send a message, the workflow runs perfectly. It seems like the API 'falls asleep'? Has anyone had this issue? I added a quick video showing the 400 error and  how it then works after interacting with it directly, very weird. 

I'm using this version. https://github.com/FlowiseAI/Flowise/releases/tag/flowise%401.3.4
Loom video: https://www.loom.com/share/Flowise-400-errror-bubbleio-707f6653fc2e45c09062039a5a72d64f?sid=6ab84e39-27dc-43a5-9f5f-e63e7f08cbd9

<img width="904" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/98601378/78b9e1fc-882a-45ea-b92a-da7bfcb84024">

**Comment by chungyau97** [comment]
Hi @camilordg96, 

Could you share out how you write to connect Flowise API using Postman?
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/9aaaaf48-73c8-461e-bae1-6a2b997cfc25)
