### ISSUE TITLE
[BUG] API Request Error: OpenAI or Azure OpenAI API key not found

### ISSUE THREAD

**Issue by Pyot** [FlowiseAI/Flowise#926]
**Describe the bug**
Problem with executing a request via the API. Returns error: Error: OpenAI or Azure OpenAI API key not found.

**To Reproduce**

**Making a request to:**

> Request URL: http://localhost:8100/api/v1/prediction/fdb3aba6-0230-42c3-83e8-34f3d038cce4
> Request Method: POST
> Status Code: 500 Internal Server Error
> Remote Address: [::1]:8100
> Referrer Policy: strict-origin-when-cross-origin

Body:
```
{
   "question": "test",
   "overrideConfig": {
      "openAIApiKey":"sk-EXAMPLEFr6",
      "stripNewLines":true,
      "batchSize":1,
      "timeout":1
   }
}
```

**Expected behavior**
I should receive a response from OpenAI.

**Screenshots**

![Screenshot 2023-09-15 at 11 28 10](https://github.com/FlowiseAI/Flowise/assets/24312172/28e1279f-6ed5-4a50-8687-8592f24031f2)

**Setup**
Installation: Docker
Flowise Version: flowise@1.3.4
OS: macOS
Browser: Chrome
Additional context
Everything works when the keys are provided in the Flowise chart. The problem is when communicating through the API.

**Comment by chungyau97** [comment]
Hi @Pyot,

Got to specify their node id shown below:
``` json
{
    "question": "What's Jane?",
    "overrideConfig": {
        "openAIApiKey": {
            "chatOpenAI_0": "sk-EXAMPLEFr6",
            "openAIEmbeddings_0": "sk-EXAMPLEFr6"
        }
    }
}
```
