### ISSUE TITLE
"Pinecone Upsert Document" creating duplicate vectors under a name-space for every chat-session

### ISSUE THREAD

**Issue by rajeshdavidbabu** [FlowiseAI/Flowise#930]
**Describe the bug**
I am using "Pinecone Upsert Document" as part of searching a PDF along with Conversational Retrieval QA Chain.

However as I see it, every time I start a new chat-session and open the chat-window and chat the pinecone embeddings seem to create duplicate vector

For example in this image, the vectors number increased from 325 to 650.

<img width="965" alt="Screenshot 2023-09-16 at 23 06 01" src="https://github.com/FlowiseAI/Flowise/assets/15684795/531a7ffb-4505-409b-b81a-097b17fffa2f">

**To Reproduce**
Build a simple "Conversational Retrieval QA template" and test it with "Pinecone Upsert Document"

<img width="1040" alt="Screenshot 2023-09-16 at 23 10 51" src="https://github.com/FlowiseAI/Flowise/assets/15684795/878b4376-034f-4a6e-952e-c89bb0a2f583">

**Expected behavior**
No duplicate vectors should be created on every chat session

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
-   Installation [e.g. docker, `npx flowise start`, `yarn start`]
-   Flowise Version [e.g. 1.2.11]
-   OS: [e.g. macOS, Windows, Linux]
-   Browser [e.g. chrome, safari]

**Additional context**

**Comment by rajeshdavidbabu** [comment]
Chat flow json

`{"nodes":[{"width":300,"height":525,"id":"chatOpenAI_0","position":{"x":1250.7179518733046,"y":293.77680367447635},"type":"customNode","data":{"id":"chatOpenAI_0","label":"ChatOpenAI","version":1,"name":"chatOpenAI","type":"ChatOpenAI","baseClasses":["ChatOpenAI","BaseChatModel","BaseLanguageModel"],"category":"Chat Models","description":"Wrapper around OpenAI large language models that use the Chat endpoint","inputParams":[{"label":"Connect Credential","name":"credential","type":"credential","credentialNames":["openAIApi"],"id":"chatOpenAI_0-input-credential-credential"},{"label":"Model Name","name":"modelName","type":"options","options":[{"label":"gpt-4","name":"gpt-4"},{"label":"gpt-4-0613","name":"gpt-4-0613"},{"label":"gpt-4-32k","name":"gpt-4-32k"},{"label":"gpt-4-32k-0613","name":"gpt-4-32k-0613"},{"label":"gpt-3.5-turbo","name":"gpt-3.5-turbo"},{"label":"gpt-3.5-turbo-0613","name":"gpt-3.5-turbo-0613"},{"label":"gpt-3.5-turbo-16k","name":"gpt-3.5-turbo-16k"},{"label":"gpt-3.5-turbo-16k-0613","name":"gpt-3.5-turbo-16k-0613"}],"default":"gpt-3.5-turbo","optional":true,"id":"chatOpenAI_0-input-modelName-options"},{"label":"Temperature","name":"temperature","type":"number","default":0.9,"optional":true,"id":"chatOpenAI_0-input-temperature-number"},{"label":"Max Tokens","name":"maxTokens","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-maxTokens-number"},{"label":"Top Probability","name":"topP","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-topP-number"},{"label":"Frequency Penalty","name":"frequencyPenalty","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-frequencyPenalty-number"},{"label":"Presence Penalty","name":"presencePenalty","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-presencePenalty-number"},{"label":"Timeout","name":"timeout","type":"number","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-timeout-number"},{"label":"BasePath","name":"basepath","type":"string","optional":true,"additionalParams":true,"id":"chatOpenAI_0-input-basepath-string"}],"inputAnchors":[],"inputs":{"modelName":"gpt-3.5-turbo","temperature":"0","maxTokens":"","topP":"","frequencyPenalty":"","presencePenalty":"","timeout":"","basepath":""},"outputAnchors":[{"id":"chatOpenAI_0-output-chatOpenAI-ChatOpenAI|BaseChatModel|BaseLanguageModel","name":"chatOpenAI","label":"ChatOpenAI","type":"ChatOpenAI | BaseChatModel | BaseLanguageModel"}],"outputs":{},"selected":false},"positionAbsolute":{"x":1250.7179518733046,"y":293.77680367447635},"selected":false,"dragging":false},{"width":300,"height":330,"id":"openAIEmbeddings_0","position":{"x":192.70209069733744,"y":503.3585229507323},"type":"customNode","data":{"id":"openAIEmbeddings_0","label":"OpenAI Embeddings","version":1,"name":"openAIEmbeddings","type":"OpenAIEmbeddings","baseClasses":["OpenAIEmbeddings","Embeddings"],"category":"Embeddings","description":"OpenAI API to generate embeddings for a given text","inputParams":[{"label":"Connect Credential","name":"credential","type":"credential","credentialNames":["openAIApi"],"id":"openAIEmbeddings_0-input-credential-credential"},{"label":"Strip New Lines","name":"stripNewLines","type":"boolean","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-stripNewLines-boolean"},{"label":"Batch Size","name":"batchSize","type":"number","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-batchSize-number"},{"label":"Timeout","name":"timeout","type":"number","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-timeout-number"},{"label":"BasePath","name":"basepath","type":"string","optional":true,"additionalParams":true,"id":"openAIEmbeddings_0-input-basepath-string"}],"inputAnchors":[],"inputs":{"stripNewLines":true,"batchSize":"50","timeout":"10000","basepath":""},"outputAnchors":[{"id":"openAIEmbeddings_0-output-openAIEmbeddings-OpenAIEmbeddings|Embeddings","name":"openAIEmbeddings","label":"OpenAIEmbeddings","type":"OpenAIEmbeddings | Embeddings"}],"outputs":{},"selected":false},"selected":false,"positionAbsolute":{"x":192.70209069733744,"y":503.3585229507323},"dragging":false},{"width":300,"height":481,"id":"conversationalRetrievalQAChain_0","position":{"x":2158.4919971222607,"y":305.22768972225106},"type":"customNode","data":{"id":"conversationalRetrievalQAChain_0","label":"Conversational Retrieval QA Chain","version":1,"name":"conversationalRetrievalQAChain","type":"ConversationalRetrievalQAChain","baseClasses":["ConversationalRetrievalQAChain","BaseChain"],"category":"Chains","description":"Document QA - built on RetrievalQAChain to provide a chat history component","inputParams":[{"label":"Return Source Documents","name":"returnSourceDocuments","type":"boolean","optional":true,"id":"conversationalRetrievalQAChain_0-input-returnSourceDocuments-boolean"},{"label":"System Message","name":"systemMessagePrompt","type":"string","rows":4,"additionalParams":true,"optional":true,"placeholder":"I want you to act as a document that I am having a conversation with. Your name is \"AI Assistant\". You will provide me with answers from the given info. If the answer is not included, say exactly \"Hmm, I am not sure.\" and stop after that. Refuse to answer any question not about the info. Never break character.","id":"conversationalRetrievalQAChain_0-input-systemMessagePrompt-string"},{"label":"Chain Option","name":"chainOption","type":"options","options":[{"label":"MapReduceDocumentsChain","name":"map_reduce","description":"Suitable for QA tasks over larger documents and can run the preprocessing step in parallel, reducing the running time"},{"label":"RefineDocumentsChain","name":"refine","description":"Suitable for QA tasks over a large number of documents."},{"label":"StuffDocumentsChain","name":"stuff","description":"Suitable for QA tasks over a small number of documents."}],"additionalParams":true,"optional":true,"id":"conversationalRetrievalQAChain_0-input-chainOption-options"}],"inputAnchors":[{"label":"Language Model","name":"model","type":"BaseLanguageModel","id":"conversationalRetrievalQAChain_0-input-model-BaseLanguageModel"},{"label":"Vector Store Retriever","name":"vectorStoreRetriever","type":"BaseRetriever","id":"conversationalRetrievalQAChain_0-input-vectorStoreRetriever-BaseRetriever"},{"label":"Memory","name":"memory","type":"BaseMemory","optional":true,"description":"If left empty, a default BufferMemory will be used","id":"conversationalRetrievalQAChain_0-input-memory-BaseMemory"}],"inputs":{"model":"{{chatOpenAI_0.data.instance}}","vectorStoreRetriever":"{{pineconeUpsert_0.data.instance}}","memory":"{{bufferMemory_0.data.instance}}","returnSourceDocuments":true,"systemMessagePrompt":"","chainOption":"stuff"},"outputAnchors":[{"id":"conversationalRetrievalQAChain_0-output-conversationalRetrievalQAChain-ConversationalRetrievalQAChain|BaseChain","name":"conversationalRetrievalQAChain","label":"ConversationalRetrievalQAChain","type":"ConversationalRetrievalQAChain | BaseChain"}],"outputs":{},"selected":false},"positionAbsolute":{"x":2158.4919971222607,"y":305.22768972225106},"selected":false,"dragging":false},{"width":300,"height":378,"id":"bufferMemory_0","position":{"x":1228.0327881837907,"y":877.994429152935},"type":"customNode","data":{"id":"bufferMemory_0","label":"Buffer Memory","version":1,"name":"bufferMemory","type":"BufferMemory","baseClasses":["BufferMemory","BaseChatMemory","BaseMemory"],"category":"Memory","description":"Remembers previous conversational back and forths directly","inputParams":[{"label":"Memory Key","name":"memoryKey","type":"string","default":"chat_history","id":"bufferMemory_0-input-memoryKey-string"},{"label":"Input Key","name":"inputKey","type":"string","default":"input","id":"bufferMemory_0-input-inputKey-string"}],"inputAnchors":[],"inputs":{"memoryKey":"chat_history","inputKey":"input"},"outputAnchors":[{"id":"bufferMemory_0-output-bufferMemory-BufferMemory|BaseChatMemory|BaseMemory","name":"bufferMemory","label":"BufferMemory","type":"BufferMemory | BaseChatMemory | BaseMemory"}],"outputs":{},"selected":false},"selected":false,"dragging":false,"positionAbsolute":{"x":1228.0327881837907,"y":877.994429152935}},{"width":300,"height":378,"id":"recursiveCharacterTextSplitter_0","position":{"x":268.1274192719065,"y":12.31594473738835},"type":"customNode","data":{"id":"recursiveCharacterTextSplitter_0","label":"Recursive Character Text Splitter","version":1,"name":"recursiveCharacterTextSplitter","type":"RecursiveCharacterTextSplitter","baseClasses":["RecursiveCharacterTextSplitter","TextSplitter","BaseDocumentTransformer","Runnable"],"category":"Text Splitters","description":"Split documents recursively by different characters - starting with \"\\n\\n\", then \"\\n\", then \" \"","inputParams":[{"label":"Chunk Size","name":"chunkSize","type":"number","default":1000,"optional":true,"id":"recursiveCharacterTextSplitter_0-input-chunkSize-number"},{"label":"Chunk Overlap","name":"chunkOverlap","type":"number","optional":true,"id":"recursiveCharacterTextSplitter_0-input-chunkOverlap-number"}],"inputAnchors":[],"inputs":{"chunkSize":1000,"chunkOverlap":"200"},"outputAnchors":[{"id":"recursiveCharacterTextSplitter_0-output-recursiveCharacterTextSplitter-RecursiveCharacterTextSplitter|TextSplitter|BaseDocumentTransformer|Runnable","name":"recursiveCharacterTextSplitter","label":"RecursiveCharacterTextSplitter","type":"RecursiveCharacterTextSplitter | TextSplitter | BaseDocumentTransformer | Runnable"}],"outputs":{},"selected":false},"selected":false,"positionAbsolute":{"x":268.1274192719065,"y":12.31594473738835},"dragging":false},{"width":300,"height":509,"id":"pdfFile_0","position":{"x":720.0780317200447,"y":-282.2997035947215},"type":"customNode","data":{"id":"pdfFile_0","label":"Pdf File","version":1,"name":"pdfFile","type":"Document","baseClasses":["Document"],"category":"Document Loaders","description":"Load data from PDF files","inputParams":[{"label":"Pdf File","name":"pdfFile","type":"file","fileType":".pdf","id":"pdfFile_0-input-pdfFile-file"},{"label":"Usage","name":"usage","type":"options","options":[{"label":"One document per page","name":"perPage"},{"label":"One document per file","name":"perFile"}],"default":"perPage","id":"pdfFile_0-input-usage-options"},{"label":"Use Legacy Build","name":"legacyBuild","type":"boolean","optional":true,"additionalParams":true,"id":"pdfFile_0-input-legacyBuild-boolean"},{"label":"Metadata","name":"metadata","type":"json","optional":true,"additionalParams":true,"id":"pdfFile_0-input-metadata-json"}],"inputAnchors":[{"label":"Text Splitter","name":"textSplitter","type":"TextSplitter","optional":true,"id":"pdfFile_0-input-textSplitter-TextSplitter"}],"inputs":{"textSplitter":"{{recursiveCharacterTextSplitter_0.data.instance}}","usage":"perPage","legacyBuild":"","metadata":""},"outputAnchors":[{"id":"pdfFile_0-output-pdfFile-Document","name":"pdfFile","label":"Document","type":"Document"}],"outputs":{},"selected":false},"selected":false,"positionAbsolute":{"x":720.0780317200447,"y":-282.2997035947215},"dragging":false},{"width":300,"height":557,"id":"pineconeUpsert_0","position":{"x":1222.6582523135314,"y":-358.65905252625606},"type":"customNode","data":{"id":"pineconeUpsert_0","label":"Pinecone Upsert Document","version":1,"name":"pineconeUpsert","type":"Pinecone","baseClasses":["Pinecone","VectorStoreRetriever","BaseRetriever"],"category":"Vector Stores","description":"Upsert documents to Pinecone","inputParams":[{"label":"Connect Credential","name":"credential","type":"credential","credentialNames":["pineconeApi"],"id":"pineconeUpsert_0-input-credential-credential"},{"label":"Pinecone Index","name":"pineconeIndex","type":"string","id":"pineconeUpsert_0-input-pineconeIndex-string"},{"label":"Pinecone Namespace","name":"pineconeNamespace","type":"string","placeholder":"my-first-namespace","additionalParams":true,"optional":true,"id":"pineconeUpsert_0-input-pineconeNamespace-string"},{"label":"Top K","name":"topK","description":"Number of top results to fetch. Default to 4","placeholder":"4","type":"number","additionalParams":true,"optional":true,"id":"pineconeUpsert_0-input-topK-number"}],"inputAnchors":[{"label":"Document","name":"document","type":"Document","list":true,"id":"pineconeUpsert_0-input-document-Document"},{"label":"Embeddings","name":"embeddings","type":"Embeddings","id":"pineconeUpsert_0-input-embeddings-Embeddings"}],"inputs":{"document":["{{pdfFile_0.data.instance}}"],"embeddings":"{{openAIEmbeddings_0.data.instance}}","pineconeIndex":"flowise-ai","pineconeNamespace":"basic-german-law-2","topK":"10"},"outputAnchors":[{"name":"output","label":"Output","type":"options","options":[{"id":"pineconeUpsert_0-output-retriever-Pinecone|VectorStoreRetriever|BaseRetriever","name":"retriever","label":"Pinecone Retriever","type":"Pinecone | VectorStoreRetriever | BaseRetriever"},{"id":"pineconeUpsert_0-output-vectorStore-Pinecone|VectorStore","name":"vectorStore","label":"Pinecone Vector Store","type":"Pinecone | VectorStore"}],"default":"retriever"}],"outputs":{"output":"retriever"},"selected":false},"selected":false,"positionAbsolute":{"x":1222.6582523135314,"y":-358.65905252625606},"dragging":false}],"edges":[{"source":"chatOpenAI_0","sourceHandle":"chatOpenAI_0-output-chatOpenAI-ChatOpenAI|BaseChatModel|BaseLanguageModel","target":"conversationalRetrievalQAChain_0","targetHandle":"conversationalRetrievalQAChain_0-input-model-BaseLanguageModel","type":"buttonedge","id":"chatOpenAI_0-chatOpenAI_0-output-chatOpenAI-ChatOpenAI|BaseChatModel|BaseLanguageModel-conversationalRetrievalQAChain_0-conversationalRetrievalQAChain_0-input-model-BaseLanguageModel","data":{"label":""}},{"source":"bufferMemory_0","sourceHandle":"bufferMemory_0-output-bufferMemory-BufferMemory|BaseChatMemory|BaseMemory","target":"conversationalRetrievalQAChain_0","targetHandle":"conversationalRetrievalQAChain_0-input-memory-BaseMemory","type":"buttonedge","id":"bufferMemory_0-bufferMemory_0-output-bufferMemory-BufferMemory|BaseChatMemory|BaseMemory-conversationalRetrievalQAChain_0-conversationalRetrievalQAChain_0-input-memory-BaseMemory","data":{"label":""}},{"source":"recursiveCharacterTextSplitter_0","sourceHandle":"recursiveCharacterTextSplitter_0-output-recursiveCharacterTextSplitter-RecursiveCharacterTextSplitter|TextSplitter|BaseDocumentTransformer|Runnable","target":"pdfFile_0","targetHandle":"pdfFile_0-input-textSplitter-TextSplitter","type":"buttonedge","id":"recursiveCharacterTextSplitter_0-recursiveCharacterTextSplitter_0-output-recursiveCharacterTextSplitter-RecursiveCharacterTextSplitter|TextSplitter|BaseDocumentTransformer|Runnable-pdfFile_0-pdfFile_0-input-textSplitter-TextSplitter","data":{"label":""}},{"source":"pdfFile_0","sourceHandle":"pdfFile_0-output-pdfFile-Document","target":"pineconeUpsert_0","targetHandle":"pineconeUpsert_0-input-document-Document","type":"buttonedge","id":"pdfFile_0-pdfFile_0-output-pdfFile-Document-pineconeUpsert_0-pineconeUpsert_0-input-document-Document","data":{"label":""}},{"source":"openAIEmbeddings_0","sourceHandle":"openAIEmbeddings_0-output-openAIEmbeddings-OpenAIEmbeddings|Embeddings","target":"pineconeUpsert_0","targetHandle":"pineconeUpsert_0-input-embeddings-Embeddings","type":"buttonedge","id":"openAIEmbeddings_0-openAIEmbeddings_0-output-openAIEmbeddings-OpenAIEmbeddings|Embeddings-pineconeUpsert_0-pineconeUpsert_0-input-embeddings-Embeddings","data":{"label":""}},{"source":"pineconeUpsert_0","sourceHandle":"pineconeUpsert_0-output-retriever-Pinecone|VectorStoreRetriever|BaseRetriever","target":"conversationalRetrievalQAChain_0","targetHandle":"conversationalRetrievalQAChain_0-input-vectorStoreRetriever-BaseRetriever","type":"buttonedge","id":"pineconeUpsert_0-pineconeUpsert_0-output-retriever-Pinecone|VectorStoreRetriever|BaseRetriever-conversationalRetrievalQAChain_0-conversationalRetrievalQAChain_0-input-vectorStoreRetriever-BaseRetriever","data":{"label":""}}]}`

**Comment by chungyau97** [comment]
Hi @rajeshdavidbabu,

It will rerun every node when Flowise's server status changes (shut down, restart, or update) or when the canvas is modified (moved or edited).

Recommend to make another node using `Pinecone Load Existing Index` node

**Comment by rajeshdavidbabu** [comment]
That means, can I use both the nodes at the same time?

I tried but wasn't able to do it because the Upsert node will not have any
output connected. Or do you recommend first use Upsert node and then remove
it and continue with the Load Index node ?
