### ISSUE TITLE
[BUG] "Failed to parse. Text: ", Buffer Memory

### ISSUE THREAD

**Issue by U-G-Twohill** [FlowiseAI/Flowise#931]
Buffer memory error "Failed to parse. Text: "

I am following along with the following tutorial on Flowise Agents locally on port 3000
https://www.youtube.com/watch?v=fn4GCZuiwdk

I am getting the following error and suggestion when trying to interact with the agent:

______________________________________________________________________________________________________________________________________________
AI
Hi there! How can I help?

Me
Hello

AI
Failed to parse. Text: "

Output a JSON markdown code snippet containing a valid JSON object in one of two formats:

Option 1: Use this if you want the human to use a tool. Markdown code snippet formatted in the following schema:
---------------------------------------------------------------------------------------------------------------------------------------------------
json
{{
    "action": string, // The action to take. Must be one of [search, calculator]
    "action_input": string // The input to the action. May be a stringified object.
}}
---------------------------------------------------------------------------------------------------------------------------------------------------

Option #2: Use this if you want to respond directly and conversationally to the human. Markdown code snippet formatted in the following schema:
---------------------------------------------------------------------------------------------------------------------------------------------------
json
{{
    "action": "Final Answer",
    "action_input": string // You should put what you want to return to use here and make sure to use valid json newline characters.
}}
---------------------------------------------------------------------------------------------------------------------------------------------------
For both options, remember to always include the surrounding markdown code snippet delimiters (begin with "json" and end with "")!". Error: SyntaxError: Unexpected token { in JSON at position 1

I'm not sure how to reproduce as I can't find any similar issues online and it seems to work fin in the video.
![image](https://github.com/FlowiseAI/Flowise/assets/142637941/619c0f1e-1f77-4263-96db-6e8d13c7eda7)
![image](https://github.com/FlowiseAI/Flowise/assets/142637941/c4fde522-c498-41cb-9a78-84a8eaafc24c)

What information I could find suggests that it's some sort of javascript error so I have ensured it is enabled in my browser and I'm not sure what else to do.

I have also viewed the source for the page and it seems like it could be some kind of internal server error but I just don't know how to fix it or what it exactly means.
![image](https://github.com/FlowiseAI/Flowise/assets/142637941/9291fe6a-203f-47f3-8eeb-c79cd744bcf2)

If anyone has encountered a similar problem or has ideas on what could help fix this it would be greatly appreciated.

For expected behavior see video tutorial linked at the start, relevant content from 12:30.

**Comment by HenryHengZJ** [comment]
You'll need to use a ChatOpenAI node instead of OpenAI
