### ISSUE TITLE
[FEATURE]Add support for LLMonitor and other APM-like chain tracing tools

### ISSUE THREAD

**Issue by mousounikki** [FlowiseAI/Flowise#935]
**Describe the feature you'd like**
Currently flowise only supports tracking APM call links by viewing them in console logs, which is difficult for low-code debugging of each step's output and building applications in production environments. Already seen that LLMonitor is supported in langchain.js, is it a follow up to consider adding a tracking id that integrates LLMonitor by default in every flowise app? similar to LangSmith's private deployment solution

**Additional context**
https://js.langchain.com/docs/ecosystem/integrations/llmonitor
https://github.com/llmonitor/llmonitor

**Comment by HenryHengZJ** [comment]
definitely can add support for LLMonitor, in the meantime, the latest version allow you to use LangSmith and Langfuse

1.) In your chatflow, click Analyse Chatflow:
<img width="200" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/71cefd55-7aae-465f-9de7-43db8282f417">

2.) 
<img width="481" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/7b22d370-3e8b-4b54-ab43-b95c49bf20fd">

**Comment by vinodkiran** [comment]
If no one has commenced work on this, I can take it up. 

@HenryHengZJ Kindly confirm.

**Comment by HenryHengZJ** [comment]
sure @vinodkiran thanks!

**Comment by vinodkiran** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/842544/ef0501c4-6ec2-4ca2-867d-4ce011d8f27d)
![image](https://github.com/FlowiseAI/Flowise/assets/842544/b37a7d84-7d2d-4c98-aa21-00c1800eaa2e)
![image](https://github.com/FlowiseAI/Flowise/assets/842544/4a32c4bc-bd97-4dd6-bbc6-02c16255420c)
![image](https://github.com/FlowiseAI/Flowise/assets/842544/a25af37d-5920-4b52-a28e-baa4d6670ab9)

**Comment by vinodkiran** [comment]
https://github.com/FlowiseAI/Flowise/pull/952

**Comment by vincelwt** [comment]
hey guys! Founder/maintainer of LLMonitor here :) Thanks a bunch @vinodkiran for the PR. Great project!

A mutual user contacted us to ask how to setup user tracking with Flowise. 

Currently we support passing `userId` and `userProps` fields to Langchain's metadatas to track users.

Is there a standard way to identify users by ID in Flowise already?

**Comment by HenryHengZJ** [comment]
hey @vincelwt unfortunately we don't have users id in Flowise

**Comment by matthewlal** [comment]
Can it be possible to implement user id and metadata as a part of the input config when interacting with Flowise via the API? Which would then forward this info to whatever analytics/tracing tool that's been integrated, ie: Langsmith, LLMonitor, Langfuse, etc
