### ISSUE TITLE
In progress messages for AutoGPT

### ISSUE THREAD

**Issue by goldzulu** [FlowiseAI/Flowise#95]
I am not sure if I configure the project properly but for autogpt using the marketplace template, I don't see the in progress messages ie the reasoning, thinking etc in the chat message window. Is the autogpt template meant to only display the final outcome?

**Comment by HenryHengZJ** [comment]
Flowise chat window currently still doesnt support displaying the reasoning, thinking. It's added to one of the feature to develop along with streaming capability. For now, you can see it through terminal/console

**Comment by goldzulu** [comment]
Do you know how far is this feature? I was thinking if having a crack at it Via the token callback.

**Comment by HenryHengZJ** [comment]
No progress yet, feel free to take a stab :)

**Comment by goldzulu** [comment]
Is the latest streaming commit a fix for this?

**Comment by goldzulu** [comment]
Do i have to do anything to turn onthe websocket streaming. Currently i am unable to observe this behaviour? @HenryHengZJ

**Comment by HenryHengZJ** [comment]
streaming only works for Chain, there is a problem on Langchain when streaming using agent.
having said that, you still be able to see the logs:
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/341ef0c7-2acc-4e76-8498-1338095415df)

**Comment by goldzulu** [comment]
Ah ok. That's a bummer! I'll search for the issue. Many thanks!

**Comment by HenryHengZJ** [comment]
AutoGPT is now showing thought processes - https://github.com/FlowiseAI/Flowise/pull/852
