### ISSUE TITLE
[BUG]"code":500,"message":"could not load model: rpc error: code = Unavailable desc = error reading from server: EOF"

### ISSUE THREAD

**Issue by noblerboy2004** [FlowiseAI/Flowise#953]
I'm following https://docs.flowiseai.com/embeddings/localai-embeddings to install localai-embeddings. however, when i tried 
curl http://localhost:8080/v1/embeddings -H "Content-Type: application/json" -d '{
"input": "Test",
"model": "ggml-all-MiniLM-L6-v2-f16.bin"
}'

The output is "could not load model: rpc error: code = Unavailable desc = error reading from server: EOF"
![image](https://github.com/FlowiseAI/Flowise/assets/15341167/adc34855-a4fe-42d6-9b7c-5b2f76e7e1d5)

any body could help on that?

**Comment by chungyau97** [comment]
Hi @noblerboy2004,

This is my example of doing it:
![image](https://github.com/FlowiseAI/Flowise/assets/33013947/23525e53-d10b-4b0c-87fa-1e0a402e7447)
```
curl --location 'http://localhost:8080/models/apply' \
--header 'Content-Type: application/json' \
--data '{
    "url":"github:go-skynet/model-gallery/bert-embeddings.yaml",
    "name": "text-embedding-ada-002"
}'
```

**Comment by noblerboy2004** [comment]
> Hi @noblerboy2004,
> 
> This is my example of doing it: ![image](https://user-images.githubusercontent.com/33013947/269592188-23525e53-d10b-4b0c-87fa-1e0a402e7447.png)
> 
> ```
> curl --location 'http://localhost:8080/models/apply' \
> --header 'Content-Type: application/json' \
> --data '{
>     "url":"github:go-skynet/model-gallery/bert-embeddings.yaml",
>     "name": "text-embedding-ada-002"
> }'
> ```

Hi Chungyau97,
Thank you for your support. however, i got the same error when calling testing embedding. As picture below:
<img width="385" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/15341167/d3bff754-362c-4f16-9787-11938c3af748">

Hope you help to solve that.

Thank you.
