### ISSUE TITLE
[BUG] PayloadTooLargeError: request entity too large

### ISSUE THREAD

**Issue by kristianjackson** [FlowiseAI/Flowise#96]
**Describe the bug**
Loading in a 48M PDF file is producing the following error:

Failed to save chatflow: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at readStream (/home/kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/raw-body/index.js:156:17)<br> &nbsp; &nbsp;at getRawBody (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/raw-body/index.js:109:12)<br> &nbsp; &nbsp;at read (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/body-parser/lib/read.js:79:3)<br> &nbsp; &nbsp;at jsonParser (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/body-parser/lib/types/json.js:135:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/express/lib/router/index.js:328:13)<br> &nbsp; &nbsp;at /home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/express/lib/router/index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at expressInit (/home/Kristian/.nvm/versions/node/v18.12.1/lib/node_modules/flowise/node_modules/express/lib/middleware/init.js:40:5)</pre> </body> </html>

**To Reproduce**

Use PDF file to load the PDF, when clicking save on the flow the error is produced.

**Expected behavior**
I expected the document to be loaded for use by the flow.

**Screenshots**
![image](https://github.com/FlowiseAI/Flowise/assets/44676703/662e564f-ae3e-46ee-ac41-03cfea1c61ba)

**Additional context**

**Comment by HenryHengZJ** [comment]
Can you try increase the size to 100mb here: 
https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/index.ts#L66
and
https://github.com/FlowiseAI/Flowise/blob/main/packages/server/src/index.ts#L67

**Comment by kristianjackson** [comment]
That resolved the problem. So not really a "bug" but a configuration. Closing.

**Comment by halil-cosdu-bear** [comment]
Hello @kristianjackson Im getting same error, can you write me down how did you fix it? How can i increase limits? Thanks.

**Comment by toto83fr** [comment]
Same here.

**Comment by KeLeKaPe** [comment]
I have this issue right now, I have a exported DB file larger than 50MB, and now it won't import again.
Where can the limit be set, I can only see it hard coded.

**Comment by Toolfolks** [comment]
I have added 9 PDF File components. Total pdf files is 138mb
I changed this in the index.js file

my local install
C:\Users\User\node_modules\flowise\dist

async config(socketIO) {
        // Limit is needed to allow sending/receiving base64 encoded string
        this.app.use(express_1.default.json({ limit: '150mb' }));
        this.app.use(express_1.default.urlencoded({ limit: '150mb', extended: true }));

I still get this error after restarting flowise.

Failed to save chatflow: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <title>Error</title> </head> <body> <pre>PayloadTooLargeError: request entity too large<br> &nbsp; &nbsp;at readStream (C:\Users\User\node_modules\raw-body\index.js:156:17)<br> &nbsp; &nbsp;at getRawBody (C:\Users\User\node_modules\raw-body\index.js:109:12)<br> &nbsp; &nbsp;at read (C:\Users\User\node_modules\body-parser\lib\read.js:79:3)<br> &nbsp; &nbsp;at jsonParser (C:\Users\User\node_modules\body-parser\lib\types\json.js:135:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (C:\Users\User\node_modules\express\lib\router\layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (C:\Users\User\node_modules\express\lib\router\index.js:328:13)<br> &nbsp; &nbsp;at C:\Users\User\node_modules\express\lib\router\index.js:286:9<br> &nbsp; &nbsp;at Function.process_params (C:\Users\User\node_modules\express\lib\router\index.js:346:12)<br> &nbsp; &nbsp;at next (C:\Users\User\node_modules\express\lib\router\index.js:280:10)<br> &nbsp; &nbsp;at expressInit (C:\Users\User\node_modules\express\lib\middleware\init.js:40:5)</pre> </body> </html>

Any ideas.

Or a different approach ? The project is regulation documents spread over 9 PDF files.

**Comment by Toolfolks** [comment]
I had to lose the project as it would not save.
I added the merged pdf file 138 mb to another project and it saved ok.

So I presume the above settings are correct. ( Can anyone from admin confirm this )

**Comment by int211** [comment]
adding  FLOWISE_FILE_SIZE_LIMIT =  200mb
the same error, someone findout the fix pls?
