### ISSUE TITLE
[BUG] Vector Store Retriever output can not be connected to Conversational Retrieval QA Chain's similar input

### ISSUE THREAD

**Issue by vanetreg** [FlowiseAI/Flowise#963]
**Describe the bug**
Vector Store Retriever output can not be connected to Conversational Retrieval QA Chain's relevant input

**To Reproduce**
using:
flowise/1.3.6 win32-x64 node-v18.16.0
the 2 items can not be connected

**Expected behavior**
They can be connected

**Screenshots**

**Flow**
If applicable, add exported flow in order to help replicating the problem.

**Setup**
npx flowise start
flowise/1.3.6 
win32-x64 
node-v18.16.0
Chrome

**Additional context**

**Comment by HenryHengZJ** [comment]
Do you have a screenshot?

**Comment by HenryHengZJ** [comment]
oh I get what you mean, take a look at Multi Retrieval QA Chain template to see how Vector Store Retriever is being used. And Conversational Retrieval QA Chain to see how to connect vector stores to Conversaitonal Retrieval QA Chain

**Comment by vanetreg** [comment]
![Flowise-Low-code-LLM-apps-builder](https://github.com/FlowiseAI/Flowise/assets/20775061/870fcc1c-ef9e-49ba-9de8-388549543d3f)

**Comment by HenryHengZJ** [comment]
Select Faiss Retriever:
<img width="881" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/f05a3241-3375-4b8d-85d9-94a5903d4582">
