### ISSUE TITLE
[FEATURE] RAG (retrieval augmented generation) Sample flows?

### ISSUE THREAD

**Issue by vijaykammili** [FlowiseAI/Flowise#967]
**Describe the feature you'd like**

Hey @chungyau97. Does Flowise marketplace have a sample flow for RAG (Retrieval Augmented Generation) where we can take the source documents and meta data for a given question and pass it as context to answer the user's question? 

**Additional context**
N/A

**Comment by HenryHengZJ** [comment]
You can try Conversational Retrieval QA Chain: 
<img width="245" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/1a82c8f3-8c59-49a7-b503-5ef6565cfe9d">

**Comment by vijaykammili** [comment]
Thank you @HenryHengZJ . I am using a similar flow based on the Conversational Retrieval QA Chain. I would like to take the source documents/metadata returned from the Conversational Retrieval QA Chain node and pass it back to the LLM with user's question and context (source documents/metadata) to achieve RAG. Is this possible? If so, what node can i use?

**Comment by zuchi238** [comment]
Would be great if someone posted such a test .. ;)

**Comment by HenryHengZJ** [comment]
> Thank you @HenryHengZJ . I am using a similar flow based on the Conversational Retrieval QA Chain. I would like to take the source documents/metadata returned from the Conversational Retrieval QA Chain node and pass it back to the LLM with user's question and context (source documents/metadata) to achieve RAG. Is this possible? If so, what node can i use?

You have to create 2 flows to do that. Take the output from the first flow that contains source documents, and use it as input for the second flow, both via API

**Comment by vijaykammili** [comment]
@HenryHengZJ - Thank you. Do you have any sample flows? I have the following setup.

Flow 1: Retrieves data from existing pinecone index including metadata and source

<img width="1084" alt="Screenshot 2023-09-28 at 7 06 42 PM" src="https://github.com/FlowiseAI/Flowise/assets/121184261/b1809441-5328-4c48-b548-2559638035fe">


Flow 2: Loads data from Flow 1's output via API loader and ends up with a LLM chain. Ideally, I'd like to end with a Conversational Retrieval QA Chain node if possible to get the metadata/source documents. Disregard the In-memory vector store, we can replace it with Pinecone. I'm not sure if this is correct. Let me know. Appreciate all your help!

<img width="1352" alt="Screenshot 2023-09-28 at 7 07 04 PM" src="https://github.com/FlowiseAI/Flowise/assets/121184261/1d36bccc-9b62-4ff9-9921-e8aeb0e6a66c">

**Comment by zuchi238** [comment]
Isn't this a replica of the https://www.youtube.com/watch?v=m0nr1_pnAxc&t=1s
Bart
