### ISSUE TITLE
PINECONE_ENVIRONMENT nowhere to be found in the (pinecone upsert Document ) vector store

### ISSUE THREAD

**Issue by zuchi238** [FlowiseAI/Flowise#969]
All,

Good evening.

In the PineCone Upsert Document node I can not find PINECONE_ENVIRONMENT ...

Where can I input this value?

Be well,

Bart

**Comment by HenryHengZJ** [comment]
you have to create a credential:
<img width="782" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/962a2051-7920-48f4-a8ba-c5c9ad19c347">

**Comment by zuchi238** [comment]
Henry, many thanks!

Bart
