### ISSUE TITLE
[BUG] Fantastic No Code Solution, but files folder import does not work. "Error: ENOENT: no such file or directory, scandir '"

### ISSUE THREAD

**Issue by BenbaxMBA** [FlowiseAI/Flowise#970]
Hi, everytime I want to use the files folder option to use multiple files, I get the "Error: ENOENT: no such file or directory, scandir '" message in the chat.

I did not find any solution related to flowise on this. Could there be an approach to solve it?

Kind regards,
Ben

**Comment by chiru-maddala** [comment]
Facing the same issue. If someone can help me with this, that would be great. 

Also, how to provide the file path when we are running the Flowise on render.com?

**Comment by adolfousier** [comment]
Having the same issue while locally everything runs perfectly but then when deployed on Render.com or Railway.app, you type to the bot and it crashes the whole server, can anyone point out how they solve this? I also tried node and docker just in case but nothing seems to work. If I try to run a basic flow like web browser it works on the cloud but most of the flows crash.  


Any help is appreciated.

Thank you very much 
<img width="1680" alt="Screenshot 2023-10-18 at 12 06 57" src="https://github.com/FlowiseAI/Flowise/assets/35583002/5d3705da-0cc5-471a-9336-a60e4791f9b6">
<img width="1680" alt="Screenshot 2023-10-18 at 12 06 30" src="https://github.com/FlowiseAI/Flowise/assets/35583002/2d25d50b-f878-4225-a44c-24dc3d49198f">

**Comment by adolfousier** [comment]
I was able to fix this issue by setting up a variable NODE_VERSION=18.15.0 but also increasing RAM from 512mb to 2gb, now everything is working fine on render/railway with node or docker.
