### ISSUE TITLE
Ability to share credentials to custom tools. 

### ISSUE THREAD

**Issue by thekevshow** [FlowiseAI/Flowise#973]
**Describe the feature you'd like**
When I create a tool. Simply put, using the example provided, this works great if the API I am reaching out to is open, and doesn't require authentication. But if it does require authentication, let's say an API key. I have to insecurely store that in the code as a hard code, and potentially rotate it every time in code, vs just the credentials store like we have for the other modules. Ideally creating a way to attach credentials that get loaded into the custom tool, as an input would help make this more secure and more manageable for api keys you have to rotate.

**Additional context**
Here is a simpele example of the problem 

```
const fetch = require('node-fetch');

const url = 'https://api.example.com/endpointRequiresAuth';
const body = {
    text: $text
};

const options = {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'Authorization': 'authKey'
    },
    body: JSON.stringify(body)
};

try {
    const response = await fetch(url, options);
    const text = await response.text();
    return text;
} catch (error) {
    console.error(error);
    return null;
}
```
![image](https://github.com/FlowiseAI/Flowise/assets/1961133/6bed0daf-d52a-41e7-96d6-ce8a15ee720b)
Location of where I am meaning in terms of adding the ability to store here, and link to a tool, in a fashionable way.

**Comment by HenryHengZJ** [comment]
Closing as duplicate https://github.com/FlowiseAI/Flowise/issues/888
