### ISSUE TITLE
BabyAGI - connect to vector store

### ISSUE THREAD

**Issue by zuchi238** [FlowiseAI/Flowise#977]
Hi,

I'm trying to connect BabyAGI to Chroma or Pinecoine without luck.

Has anybody else the same problems?

Bart

**Comment by HenryHengZJ** [comment]
you should be able to connect to Pinecone no?

<img width="996" alt="image" src="https://github.com/FlowiseAI/Flowise/assets/26460777/7f57a5e5-941a-4b58-a0b4-28f0466e91a3">
