### ISSUE TITLE
a function box that allow me to inspect my data splits so I can adjust splits length and type for best result  [FEATURE]

### ISSUE THREAD

**Issue by kmashal** [FlowiseAI/Flowise#985]
**Describe the feature you'd like**
function box that allow me to inspect my data splits so I can adjust splits length and type for best result.

**Additional context**
its hard to see what splits I have what text inside each split

**Comment by HenryHengZJ** [comment]
with the new document store [PR](https://github.com/FlowiseAI/Flowise/pull/2106), this should give you better visiblity of the splits
