### ISSUE TITLE
[FEATURE] Custom tool for Conversational Retrieval QA Chain?

### ISSUE THREAD

**Issue by kientv** [FlowiseAI/Flowise#987]
I have just ask langchainjs for making external request in `Conversational Retrieval QA Chain` like custom tool.
They said that: They already support `RemoteLangChainRetriever` 
Could flowiseai support custom tool for `Conversational Retrieval QA Chain`

[Do Conversational Retrieval QA Chain support custom tool? #2747](https://github.com/langchain-ai/langchainjs/discussions/2747)

**Comment by zuchi238** [comment]
Something like this? https://www.youtube.com/watch?v=m0nr1_pnAxc&t=1s

**Comment by kientv** [comment]
> Something like this? https://www.youtube.com/watch?v=m0nr1_pnAxc&t=1s

Yep, but how to this chatflow both answer from the documents and allow custom tool like (calculator, call api, serp api, add user to hubspot ...)

**Comment by zuchi238** [comment]
I (better) understand your question. Theoretically you should be able to create an agent with acces to all these tools, in one hit). I have not tried it yet in Flowwise. But when you read last weeks developments on RAG, you can imagine you create 4 or 5 agents (each for a specific domain), and then combine them towards a LLM. What is your use case?

**Comment by chungyau97** [comment]
Hi @kientv,

I believe you can use `Conversational Retrieval Agent` to achieve that.

**Comment by kientv** [comment]
> Hi @kientv,
> 
> I believe you can use `Conversational Retrieval Agent` to achieve that.

But `Conversational Retrieval Agent` don't have `VectorStoreRetriever`

**Comment by WilliWespe** [comment]
Hi @kientv ,
I have the same question as you. Did you an answer yet?

**Comment by kientv** [comment]
> Hi @kientv , I have the same question as you. Did you already find a solution?

My solution is using Retrieval tool. But it's not smooth:
![image](https://github.com/FlowiseAI/Flowise/assets/3217438/77b60653-a939-49b6-b228-5dc6787c793f)
