### ISSUE TITLE
[FEATURE] Pls. add Similarity Score Threshold retriever to Flowise

### ISSUE THREAD

**Issue by vanetreg** [FlowiseAI/Flowise#991]
**Describe the feature you'd like**
Pls add Similarity Score Threshold retriever to Flowise.
Docs:
https://js.langchain.com/docs/modules/data_connection/retrievers/how_to/similarity-score-threshold-retriever

**Additional context**
It adds some nice advanced retrieval methods to Flowise.

According to Langchain's chatbot, we should simply be able to set some Vectorstore parameters:
```
# Convert the vector store into a retriever with Similarity Score Threshold retrieval method
retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": 0.5})
```
but that input is not available yet in Vector Store Retriever node.

**Comment by HenryHengZJ** [comment]
Will definitely add that! In the meantime you can try using the Vector to Document node, that allows you to specify the similarity threshold

**Comment by vanetreg** [comment]
> In the meantime you can try using the Vector to Document node, that allows you to specify the similarity threshold
I tried to search for "Vector to Document" in 
https://docs.flowiseai.com/
but it hasn't found any such info,
so where is it available in the docs / Flowise?

**Comment by HenryHengZJ** [comment]
![image](https://github.com/FlowiseAI/Flowise/assets/26460777/fafce36b-0bd1-4089-8b67-a46bbb6deb18)
 
try update your flowise version

**Comment by HenryHengZJ** [comment]
https://github.com/FlowiseAI/Flowise/pull/1012

**Comment by vanetreg** [comment]
Thank you!
